gitextensions/gitextensions

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/UserControls/RevisionGrid/IndexWatcher.cs
Small fixes
- Remove duplicate sub-expression when setting GitIndexWatcher.NotifyFilter (might be a bug?)
- Treat treeNode value as nullable
- Ran unit tests
- Compiled and ran the application
- GIT 2.38
- Windows 10
----
> Misc fixes

- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitVersion.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUIExtensions.cs
Use new feature in Git 2.38
A use case for the feature: Check differences from release/4.0 to master
range-diff is a great way to compare branches, but is too slow when there are many changes.
Displaying the diff requires a long time (I gave up after 6 minutes)
There are still few changes in source files.
To find where the changes occurs is very hard though.
Also the range-diff is likely to be huge here, just the different commit messages will be hard to filter manually.
Git 2.38 adds the possibility to filter by path.
(It is not possible to filter several paths in the GUI even if paths can be manually entered in the form - a separate feature in RevDiff).
If filtering for  FormManageWorktree.cs, range-diff displays within a second.
FormManageWorktree.cs has appeared in 5 "pairs" of …
> range-diff with path filter

- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Companion to #10295 
Allow multi select files in rev diff to filter multiple files. See #10295 for a use case.
It is possible to filter folders in file tree today, but no GUI way to select multiple files.
Multiple files can be added in the advanced filter form though.
The first file is visible in the title
All files are visible in the tool tip
This exposes the possibility to add several files in rev diff file status list.
I believe this covers the important use case, I have thought about some enhancements and rejected them:
- Possibility to add/remove files to the filter in any form. 
Adding would be simple, but not so easy to explain in the menu.
- Context menu to remove files in the filter in any form. 
Would require some data structure changes (files stored as string right now), easier …
> RevDiff: Allow path filter for several files

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
Fixes #10327
If nothing was selected (if branches/remotes/tags/submodules/stash), the context menu raised an exception.
The only required change is on line 213, the rest is cleanup for annotation.
A change like below is not really required as `isSingleSubmoduleSelected` is false (line 212 is not even required), but it limits the risk for future issues.
```diff
-            EnableMenuItems(isSingleSubmoduleSelected && !isBareRepository && submoduleNode.IsCurrent, mnubtnManageSubmodules, mnubtnSynchronizeSubmodules);
+            EnableMenuItems(isSingleSubmoduleSelected && !isBareRepository && submoduleNode?.IsCurrent is not null, mnubtnManageSubmodules, mnubtnSynchronizeSubmodules);
```
Manual
---- …
> SidePanel: Context menu at no selection

- GitCommands/Git/AheadBehindDataProvider.cs
- GitUI/BranchTreePanel/RemoteBranchTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
aheadBehindData is null when this info is not shown and the grouping of the data fails.
For some reason I only see this in Debug builds, but it should go into master and 4.0.1 as well (if only to not see this when debugging).
Some comments from a late review comment
https://github.com/gitextensions/gitextensions/pull/10258#discussion_r1004968924
Manual
----
> SidePanel: AheadBehind null check

- Plugins/GitFlow/GitFlowForm.cs
Fixes #10334
git-config returns exit code 1 if the key cannot be found.
#9056 requires all error exit to be explicitly suppressed to not raise the exception. 
As the result was empty in this situation this was handled (but if something was added to the error output, this would have failed...).
Started git-flow plugin without having git-flow init.
(the init button is the only available button).
----
> GitFlow: Do not throw if git-flow is not init

- GitExtensions/Properties/launchSettings.json
- GitUI/UserControls/BlameControl.cs
Fixes #10314
- BlameControl: Restore operation on line selection if used without RevisionGrid
(other usages of ``_revGrid` do not apply for the standalone blame window) 
N/A
- manual
- Build 1a72b10cd7da0df44f38fbaff9105ebfc75c724b
- .NET 6.0.9
----
> Fixup standalone blame

- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- contributors.txt
Fixes #10332
- Prevent exceptions from being thrown when switching languages.
- The CreateGroupHeader function in MenuCommand.cs does not expect different strings to be entered depending on the language. 
- Change it to enter a fixed string so that no exception occurs.
- ~~Displaying commands in the View menu in multiple languages probably requires another fix.~~
- Switch language, no exceptions(manual test)
- I ran automated tests and found no new errors with this fix.
- Git version 2.38.1.windows.1
- Windows 11 Pro 21H2 22000.1098
----
> Fixed an issue that caused an exception when switching languages.(#10332)

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
Fixes _(no prior issue created)_
I've taken a look at [PR where this feature was introduced](https://github.com/gitextensions/gitextensions/pull/9380) and haven't found anything which would support reversal during filtering. It seems this behavior was introduced by accident.
The effect is especially visible when using a filter which matches all of the repos, such as `\`
- Maintain recent repository order when filtering
**No filter** _(GE repo comes first)_
**With filter** _(GE repo comes **last**)_
**With filter** _(GE repo comes first)_
- Manually
----
> Keep recent repositories in the same order when filtering

- GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/FormMergeBranch.resx
- GitUI/Translation/English.xlf
Move merge strategies help tooltip to online documentation, open link on click
Fixes #9259
See proposed documentation changes here (and complete the doc PR prior to this PR):
https://github.com/gitextensions/GitExtensionsDoc/pull/144
- the help button next to the alternate merge strategies selector in the branch merge advanced options will now open the online documentation when clicked (rather than showing a length tooltip that fades in a relatively short amount of time)
There is no longer a tooltip and clicking the Help link brings us to https://git-extensions-documentation.readthedocs.io/en/main/branches.html#advanced-merge-options
- tested the link to see if it goes to an appropriate URL, verified it will bring us to the correct URL once the doc page update goes in
- Windows 10
I agree …
> Have alternate merge strategies help button point to online manual

- GitUI/CommandsDialogs/FormClone.cs
Alternative to #10344 
The core of that PR may be done anyway (suppressing throw for git-remote), but git-remote (and following commands) should not be executed if not giving a response anyway.
Fixes #10329
When opening the form, only try to access the current module if it is a valid directory to fill in reasonable defaults for a user. More specifically, the Module i normally invalid ff cloning from Explorer or the Dashboard.
Manual.
----
> FormClone: Check that current module is valid

- GitExtensions/Project.Publish.targets
- scripts/Patch-RuntimeConfigJsonFiles.ps1
Resolves #10337
SDK currently puts the lower level framework first (in runtimeconfig.json), so the hosts sees that first and if it's missing it fails - so that's why it produces the missing Microsoft.NETCore.App message - and the related URL points to that download.
If there are two frameworks listed in runtimeconfig.json with any of them missing, it's impossible for the host to determine which is lower level and which is higher level.
To avoid the issue, only retain the highest level framework - which is the WindowsDesktop, so users see correct message and get the correct link to download the required Runtime.
> Retain only Microsoft.WindowsDesktop.App in *.runtimeconfig.json

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Fixes _(none)_
- Select the first item when recent repository list gets focus
- Give focus to recent repository list when pressing ⬇️ arrow key in a filter search box
- Give focus to filter search box when pressing ⬆️ in a recent repository list when the top item (in any column) is selected
Notice how when pressing tab while in a filter search box it's not obvious which control gets focus
Full back and forth navigation between the list and the search box with arrow keys
- Manual
----
> Improve recent repository list keyboard navigation

- GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.Designer.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
instead of the currently checked out worktree
that probably contains information related to the branch checked out
The directory path  proposed for the new worktree is based on the current checked out worktree (so the path proposed could be strange if it contains the name of the branch in the path)
Whatever is the worktree checked out, the path proposed is based on the main git repo path
- manual
- Build 3b780b4e400c7d0f56805fbdbfcb862acb4e8a05 (Dirty)
- .NET 6.0.10
---- …
> FormCreateWorktree: Build potential worktree path using repository path

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
Improvement over #3923
- The user is able to add a direct access button for the fetch/pull actions he wants (because split button is painful to use on high resolution screens)
- By default, the button are not displayed, so nothing changed
Configuration:
Result (because I want a fetch button distinct of a pull button --like in all the other git GUIs--):
- Manual
- Build b5ec77dbdf12b00702b5212419a369e6a536bc9b
- .NET 6.0.10
----
> FormBrowse: let the user add fetch/pull custom icons in the toolbar

- GitCommands/Git/GitModule.cs
Fixes #10414
- fixup a wrongly inverted condition from #9059
- manual
- Build 4948ebac03dd135991428b786343385f8d9fd209 (Dirty)
- .NET 6.0.10
```
Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
:black_nib: I …
> Fixup "Derived from tag"

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Fixes #10347
When adding nullable reference types to this code, an incorrect assertion was added. The nullability of the cancellation object here is quite confusing, as setting IsRefreshing to true causes it to be created. It's also known as not-null if IsRefreshing is true. This commit updates the assertions to be correct, fixing the bug.
> Fix 'Delete obsolete branches' plugin

- appveyor.yml
- global.json
- scripts/RepoLayout.props
* Allow developers to use any SDK equal or above the specified.
* Do not demand a specific runtime during dev cycle
* Only demand the min runtime for AppVeyor builds
> Simplify devex

- GitCommands/Config/SettingKeyString.cs
- GitCommands/Git/Commands/GitCommandHelpers.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
- appveyor.yml
Fixes #10387 for tests.  Will reopen issue and tie to second pull request.
Closes #10394
- Add config to allow file protocol.
- Run tests and confirm tests succeed 
- GIT 
- Windows 
----
> Add config to allow file protocol to be used-Tests

- GitUI/CommitInfo/CommitInfo.cs
- GitUI/CommitInfo/CommitInfoHeader.cs
- ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Do not copy the following `CommitInfo` content to the clipboard any longer:
- tabulator(s) after the `:` 
- relative time
- child and parent hashes
- entire lower panel:
- related links
- "contained in branches / tags"
- "derives from tag"
```
Author:		Philippe Miossec <pmiossec@gmail.com>
Date:		1 day ago (16.11.2022 07:41:44)
Committer:	GitHub <noreply@github.com>
Commit hash:	6f9591c6ad0d0d4ab6970fa1c837560a9e743e3c
Children:	d10fc120 68d45919 4948ebac 87207d96
Parent:		9fd9895d
FormBrowse: let the user add fetch/pull custom icons in the toolbar (#10293)
Related links: View on GitHub, Issue 10293
Contained in branches:
feature/copy_commit_info
upstream/master
feature/7982_explorer_integration
fix/10414_derived_from_tag
upstream/HEAD
mstv/feature/7982_explorer_integration …
```
> CommitInfo: Copy only essential & stable data to clipboard

- Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
Fixes #10323
- Do not store the default value of a NumberSetting
because NumericUpDown cannot indicate a null value
(The binding was created in #9119.)
- Always display the default value if nothing is set (not only for "effective")
NRE
- manual
- Build 2d4c0f42c9cd0cdf0a856336d5e2b0eedbe8d4bc
- .NET 6.0.10
----
> Do not store the default value of a NumberSetting

- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Fixes #10424
Revert change to reset to All when changing repo
Note: This could be replaced with resetting Reflog->All instead, to be consistent
(Filtered branches should always be reset, more or less quering the repo twice needed to find if the filtered branches are available in the new repo.
Tests are not adapted - there are a lot of changes needed.
For 4.0.1 too
Manual
----
> Persist Current Branch setting

- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitSshHelpers.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/BrowseForPrivateKey.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
- GitUI/CommandsDialogs/FormPull.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormRemotes.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
- GitUI/HelperDialogs/FormRemoteProcess.cs
- GitUI/Infrastructure/Plink.cs
- GitUI/Infrastructure/PuttyHelpers.cs
- GitUI/Infrastructure/Telemetry/AppEnvironmentTelemetryInitializer.cs
- GitUI/MessageBoxes.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- UnitTests/GitUI.Tests/Infrastructure/PlinkTests.cs
Resolves #10321
Resolves #10352
Before invoking PuTTY we'll check for:
* PuTTY is configured as the default SSH agent (in selected scenarios),
* PuTTY executable is present,
* the supplied SSH key is located (if applicable).
Any "NO" response from the above will result in an `UserExternalOperationException`, which will ultimately show the "user-level error" dialog with "Ignore" and "Details" buttons (i.e., no "Report bug!" button).
> Verify utility's file exists before invoking it

- GitUI/CommandsDialogs/FormEditor.cs
- GitUI/NBugReports/BugReportInvoker.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
by presenting a user frendly popup
that allows the user to add a security exception
for the current repository
Fixes #9954
Display a user frendly popup that allows the user to add a security exception for the current repository
Without git output details:
With git output details:
Manual: 
- Clone a (small) repo (like `https://github.com/gitextensions/gitextensions.github.io`) in a console with Admin rights
- Open this repo into GitExtensions (without admin rights)
- See error
- Build 8b2f138ce975609f5ba6d513652b9bf4b221257b (Dirty)
- .NET 6.0.10
```
Microsoft.WindowsDesktop.App 5.0.15 [C:\Program …
```
> Better handle git security exception

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
It appears that WS_EX_COMPOSITED window extended style (0x02000000L) is causing the dashboard to enter into an endless repaint loop that burns CPU (~6-8% while the dashboard is open).
It also prevents the Settings dialog from closing, if it's opened while the dashboard is shown.
Resolves #10215
----
> Stop endless dashboard repaint loop

- Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
Avoid scanning thousands of assemblies while loading plugins.
> Reinstate dev build start-up optimisation reverted in 7bd205f23c

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPullTests.cs
Test fail if defaults for pull action is changed.
----
> Test for pullAction failed if defaults were changed

- GitCommands/Settings/ConfigFileSettings.cs
- UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
- contributors.txt
commitEncoding is case-insensitive, and the predefined UTF8 encoding is using lowercase key utf-8. Convert to lowercase to guarantee that it matches.
- `git config i18n.commitEncoding UTF-8`
- Commit using Git Extensions
- `git show` shows a leading space before the commit subject.
- GIT 2.38.1
- Windows 10
----
> Do not add BOM when commitEncoding is set to upcase UTF-8

- GitCommands/CustomDiffMergeToolCache.cs
Fixes #10435
If loading custom diff tools is cancelled, the list could be null and a null exception occur.
This has been around since custom difftools list (3.5?) so not urgent for 4.0.
Code review
----
> Set custom difftool list to empty if parsing is cancelled

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Resolves https://github.com/gitextensions/gitextensions/issues/10511
"RevisionFileTreeShowBlame" settings was introduced in #9424.
The issue with this setting is that whenever a file history is opened, blame is turned on for all open instances of the app, and affects the File Tree tab experience.
> Make "blame" setting non-sticky

- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/GitUICommands.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
Fixes the display of history for files which include a space in their path.
Manual testing - created a file with a space in its path, committed several changes and tried to view its history.
- Build 4afd375249ceede4e08a5aa49379e961409c09a7
- .NET 6.0.11
----
> Quote file name for the File History form

- GitUI/UserControls/FileStatusList.cs
Fixes #10469
- Do not expect that `ListViewItem.Index` would reflect the visible / chronological order:
Search the `Index` of the first diff because it can be different from 0
- Skip `StatusOnly` & `RangeDiff` items when searching diffs
- Expand the group on selection of an item in a collapsed group
GE not responding forever
"Text not found"
- manual (select commit 45f0291 or f6b46ad, search for not contained text)
- Build d792a68e08f0e9d4e37831b8c16fb829653bc381
- .NET 6.0.10
Please keep single commits
----
> Fixup text search in diffs (multiple groups)

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #10514
Provide the options as Git config options instead
If user hast set fetch.parallel or submodule.fetchJobs is set, do not set the options
Test updated
- GIT 2.38, 2.39
----
> Git 2.39 bugs out for fetch --jobs=0

- GitUI/GitUI.csproj
- GitUI/Themes/README.md
- Setup/Product.wxs
- UnitTests/GitUI.Tests/Theming/CssUrlResolverTests.cs
Fixes #10490
- Remove dark themes from setup or portable version to prevent the user to select them (until GE support dark themes again) when he does a fresh install
- Manual
- Build 0eaf625125e34f8f648ab28e5df0cb221688b1f1
- .NET 6.0.11
```
Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program …
```
> theme: remove dark themes from deliverables

- GitUI/NBugReports/BugReportInvoker.cs
Resolves #10483
Report git "fatal" errors as not app errors, that is, without links to raise issues on GitHub, because such issues are generally local-repo specific and should be addressable by the user.
Summary changes for Git errors:
* Do not add test "submit report for GE to investigate".
* Change *Report bug* to *View details*
It is still possible to report to GitHub with _View details_.
----
> Report git fatal errors as not app errors

- GitUI/Hotkey/HotkeySettingsManager.cs
Closes #10495
- Change default hotkey of `CheckoutBranch` to `Ctrl+.` of main keyboard instead of of numpad (which had changed somehow by the switch to .NET in v4)
- manual
- Build 35169a18e0f6e730cbd111dbe068ddd9bdd380fa
- .NET 6.0.10
```
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
> Change default hotkey of `CheckoutBranch` to `Ctrl+.`

- .github/workflows/git.yml
Fixes build failing as brownout warning of v18.04 deprecation
Switch to last LTS version of Ubunto used by the fixup check
- Triggered a PR that should failed and one that should succeed.
- GitHub PR
> Update version of Ubuntu for fix up check

- GitCommands/RevisionReader.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #10488
- RevisionReader: Wait for possible exceptions from the process, which has been started with `throwOnErrorExit: true`
- Do not wrap exceptions from revision reader (into `AggregateException` any longer) in order to show the appropriate exception dialog
empty repo
- manual (see issue)
- Build d61cc87112412440642619a12fae43c82a9740a2
- .NET 6.0.12
```
```
---- …
> Avoid losing git exception in background

- Packages.props
- Setup/Product.wxs
Microsoft.VisualStudio.Composition v16.9 depended on System.ComponentModel.Composition v4.5+; which led to us shipping v4.6.
The Plugin Manager 184 was built against [System.ComponentModel.Composition v6.0.0.](https://github.com/gitextensions/gitextensions.pluginmanager/blob/bbaafa6eda217877822d0993d1fbea57bc0239f1/src/GitExtensions.PluginManager/GitExtensions.PluginManager.csproj#L21) As a result, it would fail to load because the dependency was not satisfied.
* Add an explicit dependency on System.ComponentModel.Composition v6.0.
* Bump Microsoft.VisualStudio.Composition to v17.2, as it now depends on System.ComponentModel.Composition v6.0+.
Resolves #10529
> Bump Microsoft.VisualStudio.Composition version

- GitExtensions/Properties/launchSettings.json
- GitUI/GitUICommands.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
#10438 introduced a regression by double quoting file names passed to the File History dialog. However, it didn't take an account that the File History is now primarily shown in Form Browse dialog, where the argument is quoted when it is passed to the filter,
Quote the argument now only for the File History dialog.
Resolves #10537
> Avoid double quoting while showing File History dialog

- Directory.Build.props
- Directory.Build.targets
- Packages.props
that allows to have access to source code when debugging a released version by attaching to the process.
https://github.com/dotnet/sourcelink
Fixes https://github.com/gitextensions/gitextensions/issues/10529#issuecomment-1354358923
>Side question, would it be possible to create a debug build (including symbols) of GE on release that would permit attaching without overwriting any of the GE files? Would make it easier to debug issues like these.
- When debugging a release version by attaching to the process VisualStudio should fetch the source code directly from the GitHub repository
When a file content is retrieved
What is displayed in the file explorer:
- Debugged GE built in RELEASE and saw that the source code was retrieved from GitHub **when the local source path is not available** (so …
> Add support for SourceLink

- GitExtensionsShellEx/GitExtensionsShellEx.cpp
- GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.resx
- GitUI/Translation/English.xlf
Fixes #7863
- Being able to hide some menu items in the file explorer contextual menu
- Slight UI refactoring
When migrating from previous version:
When hiding some menu items:
Explanation of the 3 state checkox with a tooltip:
Result:
- Manual
- Build 65eb496535859a73bdd47f184bf7cc90098f53de
- .NET 6.0.11
```
Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] …
```
> Explorer integration hide menuitems

- Packages.props
https://conemu.github.io/blog/2022/12/18/Build-221218.html
Minor changes but tagged as 'stable', current is 'alpha'. It was used as the binaries were signed to avoid issue reports with virus scanners - need to check the reports on this before merging.
----
> ConEmu 221218

- GitCommands/RevisionReader.cs
Fixes #10597
- RevisionReader: Always append "--" after revision filter
- Build 6fa3adcf4020ff8645747cbc7011a49eec9c54b0 (Dirty)
- .NET 6.0.12
```
```
----
> Avoid ambiguity of branch filter

- Directory.Build.props
- Externals/Directory.Build.props
- Setup/Setup.wixproj
This PR improves developer productivity while working in the Git Extensions repo by speeding up build times considerably.
It does that with two changes:
1. Enable [Reference Assemblies](https://learn.microsoft.com/en-us/dotnet/standard/assembly/reference-assemblies)
2. Enable [Build Acceleration in Visual Studio](https://github.com/dotnet/project-system/blob/main/docs/build-acceleration.md)
For each of the following tests, a change was made in `GitExtUtils` then the whole solution was built.
- The change did not modify the public API. For example, altering a method body, reformatting code, adding a comment.
- That project was chosen as several other projects depend upon it.
- 39 succeeded, 4 up-to-date
- Elapsed times
- 23.750 seconds
- 24.710 seconds
- 23.196 seconds
- 25.509 seconds
- …
> Accelerate builds in Visual Studio

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/UITest.cs
Workaround for hanging `FormBrowseTests` regarding Left Panel
- Invalidate `RevisionGridControl` and call `DoEvents()` for 1 second after `WaitForRevisionsToBeLoaded()`
- `UITest.ProcessUntil()`: Double `maxIterations`
- existing testcases
- Build a4c7bbac4e6e978be75bf74862217a0e31716ea1
- .NET 6.0.12
```
```
----
> Stabilize FormBrowseTests regarding Left Panel

- .gitattributes
- GitExtensions.sln
- GitExtensions/Project.Loc.targets
- GitExtensions/Project.Publish.targets
- appveyor.yml
* Disable these:
* Simply build structure removing reset-commit steps that were responsible for setting original PR commit's hash. Override `$(GitCommit)` and `$(GitSha)` MSBuild properties instead.
For example: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/45871126
> Update build scripts

- GitUI/Shells/ConEmuControlExtensions.cs
ConEmu handling of new line should have changed
(and the cursor is now passing to the next line and no more run the command entered in the prompt) so now sending the "Enter" key so that the "cd" command is run
Fixes https://github.com/gitextensions/gitextensions/issues/9761#issuecomment-1312139285
For ConEmu macro keys: https://conemu.github.io/en/GuiMacro.html#Keys
- Manual with bash and cmd
- Build 88ccf3298246037f10992435997792fab50d7c96
- .NET 6.0.12
---- …
> Conemu: fix switch of repo folder in console tab

- appveyor.yml
- scripts/set_version_to.py
This is a partial reversal of https://github.com/gitextensions/gitextensions/pull/10618. The build warnings are back, but at least we're not failing the build because of those:
> Avoid "git : warning: in the working copy of '<file>', LF will be replaced by CRLF the next time Git touches it"

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Translation/English.xlf
Fixes https://github.com/gitextensions/gitextensions/issues/2260#issuecomment-1345702136 amongst others
- Add button text "Commit & force push" if amending and force push enabled in settings
- Fixup capitalization of `Amend commit` and `Reset author`
- Make mnemonic `Alt+T` unique: `Stash staged changes` vs. `Commit templates`
- Support Tab for buttons
Before|After
-|-
- manual
- Build 42e29f42c7704db04c1a9f8ffd9d111f9dfc95dd
- .NET 6.0.12
```
```
----
:black_nib: …
> FormCommit: Clearer button labels

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowse.resx
- GitUI/CommandsDialogs/FormBrowseController.cs
- GitUI/CommandsDialogs/Menus/HelpToolStripMenuItem.Designer.cs
- GitUI/CommandsDialogs/Menus/HelpToolStripMenuItem.cs
- GitUI/CommandsDialogs/Menus/SettingsChangedEventArgs.cs
- GitUI/CommandsDialogs/Menus/StartToolStripMenuItem.Designer.cs
- GitUI/CommandsDialogs/Menus/StartToolStripMenuItem.cs
- GitUI/CommandsDialogs/Menus/ToolStripMenuItemEx.cs
- GitUI/CommandsDialogs/Menus/ToolsToolStripMenuItem.Designer.cs
- GitUI/CommandsDialogs/Menus/ToolsToolStripMenuItem.cs
- GitUI/GitUI.csproj
- GitUI/RepositoryHistoryUIService.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormBrowseControllerTests.cs
- UnitTests/GitUI.Tests/RepositoryHistoryUIServiceTests.cs
Encapsulate "Start", "Tools" and "Help" menus, thus reducing the complexity of the `FormBrowse` dialog. 
Why? I'm currently working on a POC that introduces a shell form that hosts different UI - such as the dashboard, the repo browser or the repo history views, as well as introduces dependency injection and UI composition. That work is extremely complex, and having encapsulated "start menu" item helps to avoiding code duplication and significantly reduces associated complexity.
- manual tests to verify translations are correctly applied
----
> Encapsulate several top-level menus

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Remove a duplicated git delete command run that will always return an exit code different than 0 (because the 1st command already deleted the branch)
because the plugin doesn't handle well exception thrown when exit code is not zero (new development done in v4.0 where exception is thrown by default)
Fixes #10662
- Manually
- Build ca3100f5cedcac39a038eeb62cebbdce05e32841 (Dirty)
- .NET 6.0.13
----
> DeleteUnusedBranches plugin: Fix branch deletion

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Fixes #9293
In the "delete obsolete branches" plugin, when including unmerged branches, the list of branches was always empty.
Git command for listing of branches must not contain reference branch when including unmerged.
The command executed when including unmerged was `git branch --list HEAD` and had no results.
With this change it is now `git branch --list` for including unmerged branches and `git branch --list --merged HEAD` for only including branches merged into `HEAD`
- GIT git version 2.39.0.windows.1
- Windows 10 Pro 22H2
----
> Fix git command for unmerged obsolete branches

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesPlugin.cs
- Display an error message when one of the git command failed
- Fix bad branches found when opening the plugin form (search context still not loaded when initial search triggered)
- Refresh revision grid only when some branches has been deleted
- Slight UI improvements (increase a little more form height to display more than 2 branches lines,  better size columns)
Apparent stucked plugin (like in https://github.com/gitextensions/gitextensions/issues/10662#issuecomment-1398160549 ): 
The error is displayed to the user:
and after the display is refreshed (with branch list refreshed) to give show to the user that the plugin is not stucked:
- Manually
- Build a0d4a8892a9fd5dac6113f170058101369fa950f (Dirty)
- …
> Improve delete obsolete branches plugin

- GitUI/BranchTreePanel/ContextMenu/LocalBranchMenuItems.cs
- GitUI/BranchTreePanel/ContextMenu/MenuItemsStrings.cs
- GitUI/BranchTreePanel/ContextMenu/RemoteBranchMenuItems.cs
- GitUI/BranchTreePanel/ContextMenu/TagMenuItems.cs
Fixes #10660
- Add constructors `LocalBranchMenuItems`, `MenuItemsStrings`, `BranchMenuItemsStrings`, `RemoteBranchMenuItemsStrings`, `TagMenuItems`
which load the translations of contained strings
- manual
- Build 432ad7dee8533cb24fd1d0dd47761d11c6d956b7
- .NET 6.0.12
```
```
----
> Load translation for remaining Left Panel context menu items

- GitUI/CommandsDialogs/RememberFileContextMenuController.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Fixes #10666
- `FileTreeContextMenu_Opening`: Replace `Validates.NotNull(_revision)` with `null`-aware code
- `ShouldEnableFirstItemDiff` handle `null`
- Disable `filterFileInGridToolStripMenuItem`, too, if there is no selection
- Replace `var` by explicit types
NRE
- manual
- Build 450e4c061e6c4a393efd003001f2a411d9ce46f8
- .NET 6.0.12
```
```
----
> `FileTreeContextMenu_Opening`: Handle `null` revision

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #10672. Although not knowing C# or the code, I could not resist investigating.
- Move the periodic repaint routine to the grid's scroll handler. Message interception via WndProc() seems to happen before the grid even had a chance to handle the message (i.e. move rows up or down). The scroll handler on the other hand seems to be called after the grid handled the scroll event.
- Counting consecutive WM_CTLCOLORSCROLLBAR messages seems to be unreliable in the case of dragging the scroll bar, because even more messages (other than WM_CTLCOLORSCROLLBAR) are being sent to the grid than when scrolling with the mouse wheel. As a result, _consecutiveScrollMessageCnt is reset to 0 before exceeding 5 most of the time, preventing forced repaints. Fix this by using a time-based approach to …
> Fix visual glitch in the revision grid

- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitUI/CommandsDialogs/FormRebase.Designer.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/Translation/English.xlf
Rearrange commit apply order at a rebase.
I often like to change this in bigger rebases, for instance when realizing that a series of commits should be removed.
Note: Keyboard accelerator is in conflict with "Specific range", no other char is available.
I do not think range need an accelrator at all, but could change it to R if preferred.
* Avoid multiple calls to git-ls-files --unmerged
One instead of 4 calls, each requires 40 ms in my small test repo
(Could have been separate.)
Module.InTheMiddleOfRebase() is just file I/O
Adding `Edit todo...`
Manual
----
> FormRebase: edit-todo

- GitUI/BranchTreePanel/ContextMenu/MenuItemsStrings.cs
- GitUI/BranchTreePanel/ContextMenu/RemoteBranchMenuItems.cs
- GitUI/BranchTreePanel/ContextMenu/TagMenuItems.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/Translation/English.xlf
* Different menu entries depending on the type handled (local, remote and tag)
* Other tooltip fixes around "Fetch & ..." menu items
Fixes #10670
* Before
* After
* Before
* After
* After: 
- Manual
- Build d97d6df550ad7a983afbffdb40eb589cf16b1d9c (Dirty)
- .NET 6.0.13
```
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I agree that the maintainer squash merge this PR (if the commit message is …
> Left panel contextual menu: improve menu items labels and tooltips

- GitUI/Translation/English.xlf
- GitUI/UserControls/PatchGrid.Designer.cs
- GitUI/UserControls/PatchGrid.cs
Fixes #10704
- Call `PatchGrid.UpdateState()` on runtime only in order to make translation affect all columns
- Do not set `DataPropertyName` in Designer as for other columns (just for consistency)
not changed for English
- manual
- Build f173aa40d1f15b7b166d4b093e35d952c3a8dc1c
- .NET 6.0.12
```
```
----
> `PatchGrid`: Translate all columns

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/SplitterManager.cs
Fixes splitter position not being restored correctly if CommitInfo is displayed "left of graph".
- Do not apply the workaround in `FormBrowse.SetSplitterPositions` if not necessary, i.e. if CommitInfo is displayed "left of graph"
- `SplitterManager`: Also store `Panel2Collapsed` (generic issue)
- manual with CommitInfo both "left of graph" and "right of graph"
- Build adf518415a85e0f23dbc913f27213089559182ff
- .NET 6.0.12
```
```
---- …
> Fixup splitter settings

- GitUI/UserControls/FileStatusList.cs
Fixes #10694
- `FileStatusList`: Create a `ListViewGroup` for all commits including for orphan commits
because of consistency and mainly because the text search implementation is based on groups 
- manual
- Build 879bc4f5ef538872e75f8704ba60c3e63d764cd7
- .NET 6.0.12
```
```
----
> FileStatusList: Create group also for orphan commit

- GitUI/SpellChecker/EditNetSpell.cs
- Mark cursor key presses as handled if the `EditNetSpell`'s RichTextBox has not handled them
in order to suppress the unhandled-key sound ("ding")
primarily when editing the commit message
- manual
- Build ce37b9d9a9d2e3612688b4893d1c7a7a2f1f8180
- .NET 6.0.12
```
```
----
> EditNetSpell: Avoid unhandled-key sound for cursor keys

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.resx
- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/Editor/IFileViewer.cs
- GitUI/Translation/English.xlf
- Add option to toggle end-of-line markers between glyph and text
- Focus `Type to find` field on open of FormSettings
- manual
- Build 26a3cdb1d3e0f7ffc04158423e36b3357f85a279
- .NET 6.0.12
```
```
I agree that the maintainer **squash merge** this PR (if the commit message is clear).
----
> Optionally show EOL markers as glyph instead of textually

- GitCommands/Git/OsShellUtil.cs
- GitUI/CommandsDialogs/BrowseDialog/FormBrowseUtil.cs
- GitUI/CommandsDialogs/BrowseDialog/FormDonate.cs
- GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
- GitUI/GitExtensionsDialog.cs
- GitUI/UserControls/FolderBrowserButton.cs
- GitUI/UserControls/GotoUserManualControl.cs
- Plugins/Bitbucket/BitbucketPullRequestForm.cs
- Plugins/BuildServerIntegration/AzureDevOpsIntegration/Settings/SettingsUserControl.cs
- Plugins/GitFlow/GitFlowForm.cs
- Plugins/GitHub3/GitHub3Plugin.cs
- Plugins/Gource/GourceStart.cs
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
because the way to open url has changed since .net core
I had to move `OsShellUtil` to `GitCommands.csproj`
so that it is available in plugins
to prevent code duplication
Fixes  #10726 and #10728 (and similar bugs in other plugins)
- Manual
- Build f4ca8cfafac6d436200ac2edb7b74f8fc539a53a (Dirty)
- .NET 6.0.13
```
Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I agree that the maintainer squash …
> Fix url openings in plugins

- GitUI/CommitInfo/CommitInfo.cs
- Plugins/GitUIPluginInterfaces/GitRevision.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataBodyRendererTests.cs
Fixes #10736
- `Sha1HashShortRegex`: Do not match e-mail address
- CommitInfo: Parse commit hashes in commit message asynchronously, namely the call `commitDataBodyRenderer.Render()`
- improve and extend existing testcase
- Build 8f4b36162c134ceb0a493a000e5d3a400da40aa2
- Git 2.39.2.windows.1
- .NET 6.0.12
```
```
----
> CommitInfo: Do not try to parse commit-hash look-alike inside e-mail address

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- contributors.txt
- Fix: Replaced KeyUp event with KeyDown in order to handle commit action in FormCommit.cs
- Manual and I ran all tests:
- GIT git version 2.33.0.windows.2
- Windows 10 Pro 21H2 19044.2486
----
> Fix: "Ctrl+Enter" creates commit when Enter is released, not pressed

- GitUI/CommandsDialogs/FormBrowse.cs
- contributors.txt
Fixes #10479
Ensure we call `.ToPosixPath()` on the filename before calling `FormBrowse.InitMenusAndToolbars()` method.
- Manual run to check everything worked as expected in both WSL2 and non-WSL2 repos.
- GIT 2.39.2.windows.1 (Windows), 2.34.1 (Ubuntu in WSL2)
- Windows 11 (latest insider release)
- Squash merge (maintainer to decide merge message, PR submitter should cleanup commits/messages at PR approval).
----
> fix: use posix path on FormBrowse.InitMenusAndToolbars

- Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
- contributors.txt
Fixes #9643
- In `BackgroundFetchPlugin.RecreateObservable()`: Retrieve both standard output and standard error from the fetch command because on some configurations the detailed info are written into the error stream.
- I manually tested that the fix allow now the Periodic Background Fetch to automatically refresh the UI after a successful fetch.
- Git Extensions 4.0.2.16100
- Build 25100ec1f7c8da8f798613da74826038af81a50e
- Git 2.39.1.windows.1
- .NET 6.0.14
----
> FIX: Periodic Background Fetch was not automatically refreshing the UI after a successful fetch

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Fixes #10706
- Add a workaround to `RevisionGraph`: Retry `Array.Sort` if it stumbled upon rewritten `Node.Score`
N/A
- existing unit tests
- Build ad4f39aaeefd9757adeccdfc891d37b9672f8707 (Dirty)
- .NET 6.0.12
```
```
----
> `RevisionGraph`: Retry `Sort` if it stumbled upon rewritten `Score`

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/BlameControl.cs
Related to #9842 
Open the current line in the Blame viewer when switching to
RevDiff diff viewer and FileTree content instead of the
line active before the diff.
This is not important, but can be confusing as diff/view to blame selects the line in blame.
This increases the complexity some in FileViewer though, why this is not an obvious function.
(Can set this as draft or WIP, but it is ready to review.)
Also diff -> Tree, RevTree blame-view
Manual
----
> Blame: open current diff/view line

- GitCommands/Git/GitVersion.cs
Fixes #10345
- ~~Use regex to replace windows.#~~ Remove regex and just return Full.  See https://github.com/gitextensions/gitextensions/pull/10346#discussion_r1034426681
- Validated version replaced correctly
- GIT 
- Windows 
----
> Remove Brittle Version Replace

- GitCommands/Git/Executable.cs
- GitCommands/Git/ExecutableExtensions.cs
- Plugins/GitUIPluginInterfaces/IProcess.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
Fixes #10398
- Replace `IProcess.WaitForProcessExitAsync` with cancellable variant of `WaitForExitAsync` as proposed by @vjdw
N/A
- Build 70ebb97a824f4487ca5665630275859e51559dc2
- Git 2.39.2.windows.1
- .NET 6.0.14
```
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
> Replace IProcess.WaitForProcessExitAsync with WaitForExitAsync

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Interops/Messages.cs
- GitUI/Interops/User32/PostMessageW.cs
- GitUI/Interops/User32/RegisterWindowMessageW.cs
- GitUI/Translation/English.xlf
- GitUI/WindowsJumpListManager.cs
- GitUI/WindowsThumbnailToolbarButtons.cs
- Set taskbar overlay icon also if unchanged
because Windows removes the overlay when GE is unresponsive
- Close modal form on application close request, e.g. FormCommit
- Add `WindowsThumbnailToolbarButton` "Close all instances!"
- manual
- Build 4b18f73edfef5ef6bd438f5c127f3d2d08e94719
- Git 2.39.2.windows.1
- .NET 6.0.14
```
Microsoft.WindowsDesktop.App 6.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
Please **do not squash merge** this PR.
---- …
> Improve Taskbar integration (Close [all], status)

- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Fixes #10720
If stashes a are shown, the first stash to show requires explicit handling for the Git default "Show only current branch" to show stashes in the grid.
This is not possible in repos without a current branch.
Updated tests
----
> RefreshGrid without revisions

- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.cs
If AppSettings.ShowGitNotes is set, -cimmitInfo tests will try to fetch notes which will fail (with popup).
It happened to work mostly, but slight timing changes for #8741 causes the setting to active from earlier tests.
Updated tests.
----
> CommitInfoTests: Disable GitNotes

- GitUI/BranchTreePanel/BaseRevisionNode.cs
- GitUI/BranchTreePanel/NodeBase.cs
- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
The information for the selected commit was used instead of the right clicked stash.
An alternative is to get the data from the rightclicked revision, but the copy uses IScriptHostControl that gets the copy from the revision grid, so this is a much bigger task.
Sidenote: The primary reason I am changing this is to make it simpler to investigate why "git-log --reflog" occasionally hides branches that "git-log --all" shows. No info there, it is Git that delivers this info...
See Message matching the first stash
----
> SidePanel: Disallow copy context for not visible stashes

- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
- ResourceManager/Xliff/TranslationUtil.cs
Fixes #10717
Alternative to #10824 (Thanks for their efforts!)
- Manual
- Build 1a352606f72a94fba1914d8364554a27ccd47816 (Dirty)
- .NET 6.0.14
----
> Make tooltips set by using `.SetToolTip()` in designers translatable

- GitCommands/Git/GitModule.cs
- GitCommands/Settings/AppSettings.cs
Fixes #10274
WSL git command path is configurable in the settings file.
This allows using Git not in default path as the path (for instance if a newer version is installed separately, not replacing the default version). Changing the PATH is not trivial.
It also allows wrapping the command as asked for in #10274 (but in a different way).
WSL is still handled as experimental, manual change in the settings file required to change this.
Manual
----
> WslGit: Configurable path to Git executable

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #10819
- correctly split git output, i.e. only at line ends
- remove first two columns only if in expected format "* ", "+ " or "  "
n/a
- extended existing testcase
----
> Fixup GetAllBranchesWhichContainGivenCommit

- GitUI/CommandsDialogs/FormPull.Designer.cs
- GitUI/Translation/English.xlf
- ResourceManager/Xliff/TranslationUtil.cs
Last 2 points raised by PR #10824 (Thanks again to them!)
- Handle ToolTipTitle in tooltips translations
- Fix bad tooltip on local branch label (in Pull form)
* Before
* After (ToolTip Title translated)
* Before (same tooltip than remote label just below):
* AFter
- Manual
- Build d50fd6a135438b5e8c1332126ff5c2c8198bd2c5 (Dirty)
- .NET 6.0.14
----
> Improve tooltips translation

- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterToolBarTests.cs
Fixes #10830
Decouples --reflog from branch filters as --all
The options for e.g. AllBranches and RefLog can appear at the same time.
See also #10172 that decoupled other options
Some updates to be done in the doc too I assume.
Tests updated
----
> Decouple reflog from other branch filters

- GitUI/CommandsDialogs/FormPush.cs
- GitUI/Translation/English.xlf
Fixes #10405
The error message when pushing and no branch is checked out is quite confusing, partly due to GE presents nocheckout as "(no branch)". That name is illegal, but not obvious in commands.
Note: In addition to checking for the GE hardcoded name, the check could check for illegal characters (like space and parenthesis).
Note: Push could be suppressed in these situations (as was suggested in #10405), this improves the error message only.
Manual
----
> FormPush: Popup when no branch is checked out

- GitUI/CommitInfo/CommitInfo.cs
- ResourceManager/LinkFactory.cs
- UnitTests/GitUI.Tests/UserControls/CommitInfo/BranchComparerTests.cs
- UnitTests/ResourceManager.Tests/LinkFactoryTests.cs
Fixes #10317
- `LinkFactory`: Create working internal links for detached head
- `BranchComparer`: Recognize detached head as current branch
- extend tests
----
> CommitInfo: Fixup handling of detached head

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Fixes #9955
- GitStatusMonitor: Correctly handle cancellation
- There is no need to stop the monitor on OperationCanceledException.
- There is no more command running if cancelled.
- GitStatusMonitor: Stop only if retry fails, too
- E.g. I have seen the git index being locked perhaps due to VS Code getting the status.
- GitStatusMonitor: Call `InvalidateGitWorkingDirectoryStatus()`, too, on enter of `GitStatusMonitorState.Stopped`
- manual
- Build cf19d8dc7ec512991faf8fbf8bd01bc1f7459a9c
- Git 2.39.2.windows.1
- .NET 6.0.12
```
```
Please do **not squash merge** this …
> Improve robustness of GitStatusMonitor

- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/FilterToolBarTests.cs
Depends on #10831 - only last commit to be reviewed
There is no functional requirement, but it is easier to not have to resolve merge conflicts multiple times.
Fixes #10740
- Validate the contents in the filtered branches text box. If a revision is not valid, show a popup and ignore the revision.
- Handle multiple revisions (branches) was not properly none when handling options
There is no check in the Advanced filter form. This is partly due to that GitModule and the cached branches/refs are not available which require some more step, but also to allow use cases that may have been missed.
The data is not cleared in the box, so the user can edit. But no further feedback that the data is ignored.
The text box is still a mess, should be improved...
(since .net5 migration I believe.)
See …
> Filtered branches: Check validility of filter toolbar branch filter box

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/BlameControl.cs
- UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
Some small improvements on blame data generation:
* cache author lines instead of building it every times
(because it happens often that multiple lines belong to same commit)
* Use TryGetValue to get the commit and avatar image
* better heuristic for initial line capacity
- Manual
- Build 25c13145f0e10caa840621380f8cf1c2441819de (Dirty)
- .NET 6.0.14
Merge commit
----
> Improve blame performance

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Alternative to #10680
- Refactoring
* `RevisionGraph.GetSegmentsForRow`: Handle negative `row`
* Make `UpdateVisibleRowRangeInternalAsync` clearer
* Make `StraightenLanes` clearer (taken from #10778)
- Fixes
* Fixup incomplete condition for graph cache loaded
* Avoid unnecessary and incomplete lookahead for graph straightening
* Fixup endless graph loading loop
- Feature
* Preload next graph page
N/A
- manual
Please do *not squash merge* the commits!
----
> Refactor and fixup graph loading

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
Fixes https://github.com/gitextensions/gitextensions/issues/5492#issuecomment-1448460964
- FormCommit: Read committer info using git,
use `RunAsync` and
do not cache the git output in order to update on FormActivate (existing testcase)
unchanged
- manual
----
> FormCommit: Read committer info using git

- GitUI/BranchTreePanel/LocalBranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormFormatPatch.Designer.cs
- GitUI/Script/IScriptHostControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Module.GetSelectedBranch() requires about 1 ms (15000 ticks) also if no Git command is required.
This info is already calculated in the revision grid and can be made available in the IScriptHostControl interface.
(An alternative is to add this to the event like for FilteredGitRefsProvider.)
Adding this in side panel, could be added elsewhere.
In for instance CommitInfo the reference to IScriptHostControl  need to be provided after creation, so a few more steps.
Manual
----
> IScriptHostControl.CurrentBranch() to decrease overhead

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/InteractiveGitActionControl.cs
- ResourceManager/GitExtensionsFormBase.cs
Add an experimental setting to not run git-ls-files when the window is minimized on activation, as async commands when minimized seem to block the app from being restored.
Rename configuration added in #10119 to
deactivate at upgrade as this setting may give a negative experience after #10802 mostly fixes the problem.
--
The "restore from minimize" issue is occurring often for some users in 4.0
There has been occasional reports of similar issues in 2.x and 3.x too, so it is not exactly new though.
#10802 mostly fixes the problem but not completely.
It may be resolved by not running Git commands async while being minimized. I thought I had tested that, but am not sure anymore.
https://github.com/gitextensions/gitextensions/pull/10802#issuecomment-1481845774
further usage points that async …
> Restore from minimized: Configurable avoid async Git

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/UserControls/FilterToolBar.Designer.cs
[formbrowse_toolbar_visibility_](https://github.com/gitextensions/gitextensions/pull/10831#issuecomment-1496690268)
https://github.com/gitextensions/gitextensions/pull/10831#pullrequestreview-1358125079
Show reflog button first and by default
first-parents button last, after filter
Reflog is not visible by default, button activated
manual
----
> Filter toolbar: Show reflog first and default

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
because that's how it is named everywhere else (and it is misleading)
- Manual
- Build 32a99950b8e8ede897e844cc6a10fee321fa8513
- .NET 6.0.15
----
> Rename to "LeftPanel" in hotkeys

- GitCommands/Settings/AppSettings.cs
- GitExtUtils/GitUI/Theming/ColorHelper.cs
- GitUI/Avatars/AvatarDownloader.cs
- GitUI/Avatars/AvatarMemoryCache.cs
- GitUI/Avatars/AvatarService.cs
- GitUI/Avatars/FileSystemAvatarCache.cs
- GitUI/Avatars/GravatarProvider.cs
- GitUI/Avatars/InitialsAvatarProvider.cs
- Plugins/GitUIPluginInterfaces/ISettingsSource.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- UnitTests/GitExtUtils.Tests/ColorTransformationTests.cs
- UnitTests/GitUI.Tests/Avatars/AvatarPersistentCacheTests.cs
- UnitTests/GitUI.Tests/Avatars/InitialsAvatarGeneratorTests.cs
Improvements over #10020
Note: a lot easier to review commit by commit.
* perf: increase a lot perf to download avatars (ex on a blame display: from 1m30s to 6s)
* perf: fix serialization that was broken for some avatars
* Always obtain the same Author initials image between 2 GitExtensions session
* return more meaningful author initials
* Better set of colors for Author initials background colors
* perf: make that cache never expire for avatar that never changes
* Perf: slight optimization of GravatarProvider
* Perf: prevent requesting the same avatar multiple times
* saner performance default values
For choice of colors:
| Before  |  After |
|---|---|
| ![image](https://user-images.githubusercontent.com/460196/229131809-a53290da-24c6-4c71-bde0-a76fdc2d08eb.png)  | …
> Improve avatar handling

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
Depends on #10852 - no behavior dependency but (assumed in code comments, the behavior when resetting will be hard to describe without #10852 too.
~~Depends on #10853 - no behavior dependency but the same files are changed.~~
~~First commit is not be reviewed in this PR.~~
Set to draft due to dependency but reviewable.
Fixes #10423 (where both are modified)
Does not handle #10470 that relates to added/removed files
It was only possible to reset changes to the Index item, the error occurred when resetting the worktree file status item.
The reset must be done to HEAD.
Same behavior in worktree and index, separate implementations.
Manual
----
:black_nib: I contribute this code under [The Developer Certificate …
> Reset conflicted files

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUICommands.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
- Plugins/GitHub3/GitHub3Plugin.cs
like the other GitHub features
otherwise the user action is doing nothing
and the user can't understand why.
+ label in the settings saying that GitExtensions need to restart to take PAT into account.
- Manual. If the PAT is not filled, the GitHub plugin setting page is opened so that the user fill the PAT.
- 
- Build b8639a06a687113fd7eeb3318d56851be6c66bc9 (Dirty)
- .NET 6.0.15
----
> GitHub: Check that PAT is filled before trying to add upsteam remote

- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- Plugins/GitHub3/GitHub3Plugin.cs
- Plugins/GitHub3/GitHubRepo.cs
- Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs
as it is no more supported by GitHub
https://github.blog/2021-09-01-improving-git-protocol-security-github/#when-are-these-changes-effective
Use ssh instead...
Fixes #10867
Depends on https://github.com/gitextensions/Git.hub/pull/21
- Not tested 😢 (as I don't use ssh). Hope that @djc5166 will be able to test it...
- Build 7dc4416813cc2d37cbdfab7b3dca932b8e61fae2 (Dirty)
- .NET 6.0.15
----
> Remove use of git:// protocol in GitHub plugin

- GitUI/CommandsDialogs/SettingsDialog/Pages/SortingSettingsPage.Designer.cs
- Fixup `SortingSettingsPage` layout
----
> Fixup SortingSettingsPage layout

- GitUI/CommandsDialogs/FormRebase.cs
Improvement over #9686
- Hide stashes in revision grid when selecting commit range (now that we display all the stashes in the revision grid)
- Select first parent which is a better default selection. So if the user want to rebase only one commit (which is not so rare), he only has to validate the selection...
We see stashes and the selection is on the tip of the branch:
Stashes are not displayed and the 2nd commit of the branch is selected
- Manual
- Build 74ad45025d7877460d65b48ccfdab2fb8b779743
- .NET 6.0.15
Rebase merge.
----
> Improve rebase onto commit selection

- GitUI/BranchTreePanel/SubmoduleTree.cs
Fixes #10883
- Ignore exceptions from cancelled loading of submodule details in left panel when `SubmoduleTree.OnStatusUpdated` calls
- `LoadNodeDetailsAsync` 
- `LoadNodeToolTips`  
- manual (on slow machine)
----
> Ignore exceptions from cancelled loading of submodule details for left panel

- GitUI/CommandsDialogs/FormBrowse.cs
before launching the search by
* selecting the last selected when multiple commits are selected (otherwise we don't know on which commit we search)
* selecting HEAD if the selected commit is artificial
We can't launch the feature, start searching and discover that we end up nowhere
If on artificial commit, it switch to HEAD before searching
When multiselect, only the commit we are searching in stay selected so that we know which one is really used:
- Manual
- Build 9855deffe1093125ee7f6b1980fc88c667dc6ab8
- .NET 6.0.15
```
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App] …
```
> Improve commit selection for 'Find file' feature

- GitCommands/Settings/AppSettings.cs
Do not run git-ls-files by default when in minimized to not interfere with restoring.
The setting was added in
cccfbc967ce835dfd64452a4c08db478936499b6 (#10847)
but required explicit configuration.
--
I have used this on/off for some days and get quite consistent the problem with the default implementation. 
The drawback with activating the setting is that "is conflicted" is not always detected.
The drawback of making this hack permanent is that the core problem will not be fixed.
Manual
----
> No async when minimized

- GitUI/Avatars/FileSystemAvatarCache.cs
- GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
1. Avatar: prevent always rewrite of avatar file on disk (in FileSystemAvatarCache )
when the avatar has been loaded from file.
Consequences:
* fix (old time) bug where the avatar is **never** refreshed
if we open the repository enough often (i.e. < avatar cache period)
because the last `LastWriteTime` that we use to check
if the avatar has expired is always update when the avatar is written
* better perfs
2. Display Avatar and revision grid (slightly?) more efficiently
* Do all the other drawing things before letting more chance to the Task that fetch the avatar to complete
(reducing the number of redraw) => less generic avatar displayed before displaying the good avatar.
* Invalidate only the avatar region to redraw instead of the whole grid when getting the avatar
- Manual
- Git …
> Perf (and bugfix) avatars handling

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #10888
See issue
- Manual
- Build 4b51d89ffa985c6c6eff61b8083a3b7c6062b1b6
- .NET 6.0.16
----
> Fix "Commit info position" tooltip containing &

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
introduced in v2.44: 324be3750df39ac60febcfb3904079d30bc907df
lost in v3.0: a9b79574c11b038b6d1eed9df45e337d709999d8
but with some improvements:
* Allow rebase only when one commit is selected
* Allow rebase onto when 2 commits are selected but only through "advanced options..."
* Automatically check "Specific range" checkbox when rebase onto
* Improved logic when using "rebase onto" from the "Commands" menu
* 1st commit selected is the "from" parameter (that determine the range of commits that will be rebased)
* 2nd commit selected is the "onto" parameter (on which commit it will be rebased)
When more than one commit selected, we can' rebase (even if some dead code was there to handle it)
We can do a rebase onto from menu:
or from contextual menu:
- Manual
- …
> Reenable lost rebase onto feature from revision grid

- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusList.cs
- GitUI/VisualStudioIntegration.cs
Fixes #10856
- Do not check for a running Visual Studio on every open of the FileStatusList context menu
- Check for installed MSVS on startup in background
- Open a new instance if no running instance has opened a project with this file instead of error popup
unchanged
removed
- manual
----
> FileStatusList: Avoid blocking check for Visual Studio

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
because the github plugin was no more registered
- Manual
- Build 9ace4e28585b3582874b764c3af163fdaa52d1a9
- .NET 6.0.16
```
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
> Fix lost "Open github from blame" feature

- GitCommands/Git/GitModule.cs
- GitCommands/PathUtil.cs
- GitExtensions/Program.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Resolves #10025
Resolves #10815
- manual
- unit tests
----
> Intercept and convert \\wsl.localhost\ to \\wsl$\ paths

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
There has been related issues before, that has been addressed somehow.
I saw this issue after adding some repos to WSL and an USB stick,
Dashboard would require about 1:30 to open.
This could be included in 4.1, but I do not want to delay the release.
Add the repos to the lists without any I/O to check if the repo is invalid or not (to set the icon).
Perform the check if a repo has a valid Git dir async, together with branch name retrieval and set the invalid icon then instead.
Rendering of branch name failed if the item was rendered before the branch name was set.
This had a much higher probability to occur after the item creation was changed.
Menu item to remove invalid repos was only set from favorite repos, as _hasInvalidRepos was overwritten.
Manual.
I agree that the maintainer …
> Do not delay Dashboard start for invalid Git repos

- GitCommands/PathUtil.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
- contributors.txt
Fixes #10919
- Decode the part with the repository name for URLs but not local paths. Not quite sure though if `ssh://` and `git@` links are considered as URL-encoded (can't find info).
- Additional cases to the [unit test for PathUtil.GetRepositoryName](https://github.com/gitextensions/gitextensions/blob/d454fc79f668a59188d098ff9ff7fccc4ca2b7d2/UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs#L154)
- Git 2.40.1.windows.1
----
> Decode url-encoded repository folder's name

- GitExtensions/GitExtensions.csproj
- Packages.props
We have no use for it.
Closes #10425.
> Remove DotnetRuntimeBootstrapper

- GitCommands/Settings/SettingsCache.cs
- UnitTests/GitCommands.Tests/Settings/ConfigSectionTests.cs
Fixes #10917
- Remove `SettingsCache` entry when setting empty or `null` value 
N/A
- added unit test
----
> Remove SettingsCache entry when setting empty value

- GitUI/CommandsDialogs/FormCommit.cs
> Current selection can be null, if the dialog is empty

- GitCommands/CommitMessageManager.cs
- GitUI/Avatars/FileSystemAvatarCache.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/FormRevertCommit.cs
- Packages.props
- UnitTests/CommonTestUtils/ReferenceRepository.cs
- UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
- UnitTests/GitUI.Tests/Avatars/AvatarPersistentCacheTests.cs
Resolves #10926
The use of sync API leads to observable delays and locking
the application when working with repos located in WSL.
- manual
- unit tests
----
> Replace sync CommitMessageManager API with async

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormRevertCommit.cs
> Write info async on Commit dialog close

- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
Fixes #10933
- Round `AppSettings.ConEmuConsoleFont.Size` to `int`
N/A
- manual
----
> Bugfix: Always convert ConEmu font size to integer

- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Similar handling as #10832 for branch box
#10240 handles "--not ", "--exclude=" as options, this aligns with #10832
To be considered for 4.1
Tests updated.
----
> Handle all message filters starting with -- as git-log options

- GitCommands/DiffMergeTools/VsCode.cs
- GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs
Fixes #10942
- Add `--new-window` to Visual Studio Code command lines
I wasn't able to build the repository on my current machine due to dependencies, and I don't have time this evening to set it up. If it's too late to get this in, I understand. 😄 
- Manually added `--new-window` to existing commands to verify that VS Code accepts them. I tested the Edit command and the Diff command, but I didn't have a scenario handy to test the Merge command.
- GIT 
- Windows 
Merge commit preferred
----
> Open VS Code in a new window

- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Fixes #10939
I rather not merge this and close #10939 as not planned
If no branch checkout, the branch filter was handling ShowCurrentBranchOnly as ALBranches.
This is changed to work similar to before, where ShowCurrentBranchOnly filtered on the current commit instead.
A consequence is that the first stash is not added to the grid if there is no branch checked out.
first stash could be visible in some situations if current commit was added instead (rather than HEAD that may not exist), but there will still be some checks needed and this is fgar too complicated as it is.
The 'parallel implementation' tests were updated,
---- …
> ShowCurrentBranchOnly: Filter also if no branch checkout

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Translation/English.xlf
Commands are available in the context menu and buttons, where the user is expected to look for them.
The commands were not working correctly for renamed and conflicted files.
- For selected files (delete/rest) the context menu is the natural way to reset
- For Reset all/unstaged, the buttons make the same actions, and the visible/enable is set correctly
A number of similar issues have been reported in 4.0 (after Git errors were no longer ignored).
There are no report for this problem what I see, but some reported issues will build on this (remove a function).
This affects translations (removing strings), but I would like to include it in a 4.1.1 or so.
Buttons unchanged
manual
----
:black_nib: I contribute …
> Remove reset and delete from commit working dir menu

- Directory.Build.props
- GitExtSshAskPass/GitExtSshAskPass.sln
- GitExtSshAskPass/SshAskPass.vcxproj
- GitExtensions/Project.Publish.targets
- GitExtensionsShellEx/GitExtensionsShellEx.sln
- GitExtensionsShellEx/GitExtensionsShellEx.vcxproj
- contributors.txt
- scripts/native.proj
Resolves #10674 
With this PR, here are the commands to build GE on a Windows on Arm64 (WoA) platform:
- build the portable GE with the command:
```
> dotnet build
```
- build the shell extensions for WoA:
```
> dotnet build .\scripts\native_arm64.proj
```
The above command produces a `GitExtensionsShellEx64.dll` file for WoA, but GE also requires a `GitExtensionsShellEx32.dll` file to exist, so just make a copy of `GitExtensionsShellEx64.dll` to be `GitExtensionsShellEx32.dll` as well:
```
> copy artifacts\Debug\bin\GitExtensionsShellEx\GitExtensionsShellEx64.dll artifacts\Debug\bin\GitExtensionsShellEx\GitExtensionsShellEx32.dll
```
- package the GE distribution:
```
> dotnet publish
```
The last command would fail to produce a `.msi` distribution, due to it using the WiX library which …
> Add support to build GE for Windows on Arm64 (WoA)

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUICommands.cs
- GitUI/LeftPanel/SubmoduleTree.cs
Resolves #10899 
Resolves #10950 
Three parts:
* Refactoring to use common code to reset all changes (just git-reset is not sufficient to reset in all situations).
* Common code to reset file changes.
Note that FormCommit:ResetFilesClick() vs RevisionDiffControl:ResetSelectedItemsWithConfirmation() are not merged. They are slightly different (the first only handles reset to HEAD). They still may require alignment.
* GE command line reset [file] (and revert that really is an alias) raised warnings if new, renamed, conflicted files were selected and did not work at all if 'reset all changes' were used.
Note: This PR (together with #10956) should be included in a 4.1.1, it is one of the most common issues raised.
I thought this was fixed in other PRs, but this is a separate scenario.
(Most …
> Reset from command line

- GitUI/UserControls/BlameControl.cs
- select original line when blaming for "Blame this revision" to get the exact same behavior than when blaming a commit by double clicking on the line.
- try to select a better line (than the current behavior that return to the top) when using "Blame previous revision" by selecting the original line even if it is not the one of the commit we will blame because the probability that the lines are around is high.
It returns to the top of the file :(
It is located at the good line
It returns to the top of the file :(
It is located at a line that has a higher probability to be where the user want to end up
- Manual
- Build 37e812b77ba9b406b4b7e58cbe8db0d099c976cb
- Git 2.40.0.windows.1 (recommended: 2.40.1 or later)
- .NET 6.0.16
- …
> Select the good (or better) line when blaming from context menu

- GitExtensions.sln.DotSettings
results in better ide perf and better signal to noise when using inspections
> omit Externals from inspections

- BugReporter/ErrorReportUrlBuilder.cs
since Uri.EscapeDataString would throw if it was
> environmentInfo cant be null

- GitCommands/Git/EnvironmentConfiguration.cs
- GitCommands/Git/GitModule.cs
- GitCommands/PathUtil.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/ConfigFileSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
- GitUI/Translation/English.xlf
Relates to #10914
- `ConfigFileSettings.CreateSystemWide()`: use `AppSettings.GitCommand` instead of misleading `AppSettings.GitBinDir` 
- Rename `AppSettings.LinuxToolsDir` from `GitBinDir`
- Rename `GitSettingsPage.LinuxToolsDir` from `GitBinPath`
N/A
- manual
----
> Fixup path to system git config

- GitUI/CommandsDialogs/RevisionDiffControl.cs
First Index -> second WorkTree still reset to Index.
All other situations resetting to artificial commits will invisible menu items (and ignored).
Resetting from normal commit to Index does not mean anything
(files are already in Index).
Note: A previous version of this PR used HEAD instead of Index and WorkTreee/Combined reset to HEAD.
This introduced problems when resetting including files only in Index/Worktree, the added/removed status had to be evaluated a second time (possible but too complicated).
Related to #10960 (mentioned, separated to simplify review)
This will allow using common code in a follow up, to fix some reset issues that occur in 4.1 (so this is a candidate for 4.1.x)
Note 2: Resetting to Index is not handled correctly for Index files.
resetting in general is improved …
> RevDiff: Reset to HEAD for artificial

- GitCommands/RevisionReader.cs
- GitUI/SpellChecker/EditNetSpell.cs
- contributors.txt
Shift Enter is replace to normal enter in revision list.
Fixes https://github.com/gitextensions/gitextensions/issues/10724
- When using Shift+Enter in a commit message instead of Enter, it causes garbled characters to be displayed in the list. The simple solution to this problem is to replace Shift+Enter with Enter, which allows for proper visual rendering without altering the commit history.
> Treat vertical tab (Shift-Enter) as line feed

- GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Follow up to #11030 
These changes will occur over and over again at
for instance file access problems and can therefore not be dismissed.
Manual
----
> AutoComplete: Ignore Git exceptions for git-status by file

- GitCommands/Git/Commands/GitCommandHelpers.cs
- Plugins/GitUIPluginInterfaces/GitRefsOrder.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Fixes #11028
Sort references (tags, branches) by 'version:refname'.
Version added, also in Settings
Tests are adapted
----
>  Sort references by version

- GitUI/UserControls/FileStatusList.cs
Contributes to #10991
- FileStatusList: Always show diff groups if multiple groups although empty 
- manual
----
> FileStatusList: Always show diff groups if multiple groups although empty

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- FileStatusDiffCalculator: Do not attempt to detect artificial commit as base commit
- RevisionDiffControl: Fixup silent exceptions from `SetDiffsAsync`
- manual
----
> Fixup 3-revision diff with artificial

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/CommandsDialogs/BrowseDialog/FormBisect.cs
- GitUI/CommandsDialogs/FormBlame.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/IRevisionGridInfo.cs
- GitUI/CommandsDialogs/IRevisionGridUpdate.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/LeftPanel/LocalBranchTree.cs
- GitUI/LeftPanel/RepoObjectsTree.ContextActions.cs
- GitUI/LeftPanel/RepoObjectsTree.cs
- GitUI/Script/IScriptHostControl.cs
- GitUI/UserControls/BlameControl.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
Refactoring
Separate IRevisionGridInfo from IScriptHostControl
Wrap RevisionGrid access in IRevisionGrid/IRevisionGridUpdate
For 'sibling' forms like Blame that accesses and occasionally updates the
revision grid, use an interface to limit possible methods.
--
Follow-up may spread use of IRevisionGridInfo to more forms, to avoid some Git call.
More information in RevisionGrid could be cached too. One example is use of getRefs() that can take seconds. The revGrid info froom the initial grid load is distributed in GitUIEventArgs. For further updates the Git command must run again, could use the revGrid as cache. 
Manual
- To be decided later.
----
> Wrap RevisionGrid access in IRevisionGrid/IRevisionGridUpdate

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Calculate visibleRowCount correctly, considering partially visible rows at the bottom of the revision grid visible. This will make the way in which the grid adapts to the graph at the top and at the bottom consistent.
Empty space between revision graph and text. The revision graph adapts to a row below the visible region, because visibleRowCount is set too high:
<div style="float: left">
</div>
The revision graph adapts only to visible rows:
<div style="float: left">
</div>
- Scrolling and resizing the grid.
- .NET 6.0.16
- DPI 134dpi (140% scaling)
---- …
> Correctly calculate number of visible grid rows

- GitUI/Interops/LVGROUPW.cs
- GitUI/Interops/LVHITTESTINFO.cs
- GitUI/Interops/ListViewGroupMask.cs
- GitUI/Interops/NMHDR.cs
- GitUI/Theming/Renderers/ButtonRenderer.cs
- GitUI/Theming/Renderers/ComboBoxRenderer.cs
- GitUI/Theming/Renderers/EditRenderer.cs
- GitUI/Theming/Renderers/HeaderRenderer.cs
- GitUI/Theming/Renderers/ListViewRenderer.cs
- GitUI/Theming/Renderers/ScrollBarRenderer.cs
- GitUI/Theming/Renderers/SpinRenderer.cs
- GitUI/Theming/Renderers/TooltipRenderer.cs
Follow up to https://github.com/gitextensions/gitextensions/pull/11006
Credit to @SimonCropp , fork was removed though
Enclose unused classes and methods related to theming with the pragma SUPPORT_THEME_HOOKS
Build
----
> Theme pragma SUPPORT_THEME_HOOKS

- GitUI/UserControls/FileStatusDiffCalculator.cs
Fixes #10991
- FileStatusList: Do not create a group for diff to stash untracked
because it contains all(!) files of the repo as added files
with #11018
- manual
----
> FileStatusList: No group for diff to commit with untracked files of a stash

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/Lane.cs
- GitUI/UserControls/RevisionGrid/Graph/LaneSharing.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphRowTests.cs
Fixes https://github.com/gitextensions/gitextensions/pull/10778#discussion_r1155193582
- Do not straighten re-used graph lanes
- 
----
> Do not straighten re-used graph lanes

- GitCommands/Git/ExecutableExtensions.cs
- GitUI/NBugReports/BugReportInvoker.cs
to check if it's not due to security issue
Fixes #10816, Fixes #10975, Fixes #11027, Fixes #11039
Improvement on security issue over what has been already done in #10436
- Manual (For FormCommit and FormPull)
- Build bcbc3ddc814a2dd291a0ad200d240cb1f92198e7
- Git 2.40.0.windows.1 (recommended: 2.40.1 or later)
- .NET 6.0.16
```
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I agree that the maintainer …
> Check output of every git command when exit code is different than 0

- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUICommands.cs
- UnitTests/GitCommands.Tests/Git/ExecutableExtensionsTests.cs
~~Depends on #10980~~
~~First two commits are not to be removed in this PR~~
Return RunBatchCommand from RunBatchCommand(),
so CheckoutFiles() can return a combined error output.
Handle the error popup contents in GitModule.
Existed in FormCommit before, now also in RevDiff.
I do not get 'file in use' exceptions right now though.
Reset to Index in RevDiff:
Manual
----
> RevDiff: popup for failed reset

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- Utilize the OnMouseWheel() override to prevent the raising of redundant Scroll events and skip to the target row instantly while scrolling.
- Calculate the scrolling distance by adding up the mouse wheel Delta values, which leads to smoother scrolling with high-precision devices such as free-spinning mouse wheels or touchpads.
When rotating the mouse wheel by one unit, multiple Scroll events might be emitted simultaneously in accordance with SystemInformation.MouseWheelScrollLines. This leads to the revision grid being scrolled row by row with intermittent updates, which causes flickering and visual glitches.
This reduces flickering and visual glitches when scrolling the revision grid via mouse wheel, and also improves scrolling with high-precision scrolling devices.
This also …
> Improve revision grid scrolling

- UnitTests/CommonTestUtils/CommonTestUtils.csproj
Fixes #10986
https://developercommunity.visualstudio.com/t/Test-discovery-fails-with-MicrosoftVis/10372682?port=1025&fsid=708954cf-6ea4-4ac6-8735-dbf396aaba02&ref=native&refTime=1684952393560&refUserId=2a9334e3-6c08-64a6-9b8f-60d221b1cbab
- Mark `CommonTestUtils` as "not a test project / container" as proposed by Microsoft Support
- Open Test Explorer
- VS 17.6.4.
- Windows 10
----
> Fixup test discovery in Visual Studio

- GitExtensions/Program.cs
- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
- GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
Fixes #11045
- Auto-set GE as editor only in the environment of the current process (and its children)
and not in the global git config if unset
- manual
----
> Auto-set GE as editor only in current environment

- Plugins/GitFlow/GitFlowForm.cs
Fixes #11087
Avoid exception if no branch is checked out when initializing GitFlow.
Code review.
----
> GitFlow plugin exception if no head

- GitCommands/Settings/AppSettings.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.Designer.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Command.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.FilterInfo_ctor_expected.verified.txt
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.FilterInfo_ctor_with_Raw_expected.verified.txt
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Follow up to #11065 
This better reflects the Git defaults and changes the only option ticked by default, that adds filter by selection.
Supposedly, this was a confusion in #11065
Change default for --simplify-merges to false to match defaults. Anyway, the value is not used by default as --full-history is false and --simplify-merges depends on --full-history.
--
This handles a setting with negation in the name, which can be confusing. The cange could be done in the user facing part only.
However, it is normally easier if the code and UI matches. This also remove the special handlig for the setting, negating by default.
Tests updated
---- …
> Change ShowMergeCommits to HideMergeCommits

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUICommands.cs
Fixes [#11108](https://github.com/gitextensions/gitextensions/issues/11108)
- Creating a new branch using hotkeys `Ctrl + B` does not prompt `FromCreateBranch` while in bare repository, neither when artificial commit is selected.
- While selecting multiple commits, hotkey for creating new branch is disabled
- Rebasing current branch using hotkeys `Ctrl + Shift + E` is disabled while artificial commit is selected
- Creating a new tag using hotkeys `Ctrl + T` is disabled while artificial commit is selected
- Manual with GE repo
- Build https://github.com/gitextensions/gitextensions/commit/8b5eab531dcc849d00110df6f9797a096e68b500
- Git 2.30.0.windows.2 (recommended: 2.40.1 or later)
- .NET 6.0.14
> #11108 Disabled hotkeys in scenarios where their usage was not intended

- GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
Fixes [#10992](https://github.com/gitextensions/gitextensions/issues/10992)
- Selecting the `Always create a new merge commit` radio button in FormMergeBranch automatically disables the `Squash` checkbox.
- If the `Squash` checkbox is checked while disabling, it will be automatically unchecked.
- Manual with GE repo
- Build https://github.com/gitextensions/gitextensions/commit/f7e06a26f2959ac30f316ca576b9cc9640235c51
- Git 2.30.0.windows.2 (recommended: 2.41.0 or later)
- .NET 6.0.14
----
> #10992 noFastForward disabled in UI when Squash is checked

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/Rendering/GraphRenderer.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #11098
regressed in #10915
- Refactor: Simplify property `RevisionGraphColumnProvider.RevisionGraphDrawStyle`
- Avoid drawing the same graph curve twice only if unrelated branches are colored
- manual
----
> Fixup highlighted graph

- GitCommands/Config/ConfigFile.cs
- GitCommands/Config/ConfigSection.cs
- GitCommands/Git/GitConvert.cs
- GitCommands/Git/GitModule.cs
- GitCommands/PathUtil.cs
- GitCommands/StringExtensions.cs
- GitExtUtils/GitUI/ListViewExtensions.cs
- GitExtUtils/StringBuilderExtensions.cs
- GitUI/Avatars/InitialsAvatarProvider.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/LeftPanel/BaseRevisionNode.cs
- GitUI/LeftPanel/Nodes.cs
- GitUI/LeftPanel/SubmoduleNode.cs
- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
- GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/Statistics/GitImpact/ImpactControl.cs
- Plugins/Statistics/GitStatistics/PieChart/Quadrilateral.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormOpenDirectoryTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionFileTreeControllerTests.cs
Use C# 8.0 from-end-operator for index access.
Shorter code, easier to review (when you know about the feature).
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/operators/member-access-operators#index-from-end-operator-
```patch
diff --git a/GitCommands/Config/ConfigSection.cs b/GitCommands/Config/ConfigSection.cs
index 91a0e..7ee77e 100644
--- a/GitCommands/Config/ConfigSection.cs
+++ b/GitCommands/Config/ConfigSection.cs
@@ -99,7 +99,7 @@ public string GetValue(string key, string defaultValue)
{
if (list.Count > 0)
{
-                    return list[list.Count - 1];
+                    return list[^1];
}
}
```
Code review, refactoring
---- …
> IDE0056 index operator

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/BrowseDialog/FormBisect.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.cs
- GitUI/LeftPanel/RepoObjectsTree.SettingsContextMenu.cs
- GitUI/LeftPanel/RepoObjectsTree.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
- GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/GitRevision.cs
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- UnitTests/GitCommands.Tests/ExternalLinks/ExternalLinkRevisionParserTests.cs
- UnitTests/GitCommands.Tests/ExternalLinks/ExternalLinksManagerIntegrationTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitUI.Tests/LeftPanel/GitRefMenuItemsTest.cs
Use direct indexed access instead of LINQ access methods for efficiency.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1826
A few of the accesses are done quite often, I doubt that this is measurable though.
(Compare to using foreach() instead of LINQ, which is often requested in code reviews.)
The Visual Studio suggestion is handled by this, so it is not ignored where it could be relevant.
This PR has two commits, review by commit:
* First are changes mostly automated, simply changing `.First()` tp `[0]`. This should be simple to review, if incorrect access before, same now.
```patch
diff --git a/GitUI/CommandsDialogs/BrowseDialog/FormBisect.cs b/GitUI/CommandsDialogs/BrowseDialog/FormBisect.cs
index 7b06a..66ddb 100644
--- …
```
> CA1826: Use property instead of Linq

- Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerSettings.cs
The WebBrowser control uses IE11 and may give a bad experience. Disable it unless explicitly enabled.
Manual
----
> Hide build server status tab if not configured

- GitUI/CommandsDialogs/RevisionDiffController.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- Plugins/GitUIPluginInterfaces/Settings/ChoiceSetting.cs
- Plugins/Statistics/GitImpact/ImpactControl.cs
- UnitTests/GitUI.Tests/Editor/Diff/LinePrefixHelperFixture.cs
- UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs
addendum to #11131
- Replace more LINQ `First()` / `Last()` with indexer
N/A
----
> Replace more LINQ First/Last with indexer

- GitExtUtils/GitUI/TaskManager.cs
- GitExtUtils/GitUI/ThreadHelper.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/ThreadHelperTests.cs
- `TaskManager.FileAndForget()`: Remove argument `fileOnlyIf`, and replace its single usage
- Rename and refactor `TaskManager.FileAndForget()` to `RunAsyncAndForget()` in order to emphasize what it actually does,
and save an unnecessary second call of `JoinableTaskFactory.RunAsync()` by `TaskManager.RunAsyncAndForget(asyncAction)`
In a follow-up PR, I am going to replace all `JTF.RunAsync()` and `FileAndForget()` with `RunAsyncAndForget()` (background thread) or `Control.InvokeAsync()` (UI thread), respectively.
Then I will sort the methods of `ThreadHelper` alphabetically.
N/A
----
> Refactor TaskManager.FileAndForget

- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
- GitUI/CommandsDialogs/FormCleanupRepository.cs
- GitUI/Translation/English.xlf
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
- contributors.txt
Fixes #11099 
- Allow users to exclude certain file paths when cleaning repository
- Manually tested in local repository
- Added and ran relevant unit tests for new functionality
- GIT 2.41.0 windows.2
- Windows 10
----
> Clean working directory skip paths

- GitUI/NBugReports/BugReportInvoker.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
due to a Windows update
Workaround for #10367, #10368, #10376, #10381, #10392, #10412, #10413, #10528, #10551, #10624, #10625, #10734, #10738, #10771, #10772, #10803, #10804, #10813, #10874, #10875, #10876, #11047, #11047, #11066 (and possibly others).
User get the report tool popup
User get an error popup explaining the problem and encouraging them to restart instead of reporting the issue
- Manually (I have not been able to reproduce the exception so I throw the exception myself -- that does not 100% satisfy me but I hope it's enough--)
- GIT 
- Windows 
----
> More user friendly handling for "Could not load file or assembly" exceptions

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
Fixes #11156
- Disable `AppSettings.ProvideAutocompletion` for `FormCommitTests`
N/A
----
> FormCommitTests: Disable AppSettings.ProvideAutocompletion

- GitCommands/Settings/Setting.cs
- Do not try to invoke a `TypeConverter` for `null` in `Settings.GetValue()`
N/A
----
> Avoid always caught exception for unset settings

- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
Fixes regression from #11141: `System.ArgumentException: 'Accessed JArray values with invalid key value: ^1. Int32 array index expected.'`
- Use the correct interface `IList` implemented by `JContainer` in order to be able to use the new style of array indexing "[^1]"
more than one build result in grid again
- manually
----
> Use the correct interface of JContainer for indexer

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/SpellChecker/EditNetSpell.Designer.cs
- GitUI/SpellChecker/EditNetSpell.cs
Fixes [#11072](https://github.com/gitextensions/gitextensions/issues/11072)
- Pressing the menu key on the keyboard, will display the context menu with word-suggestions for the word where a caret is positioned (if the spelling is incorrect).
- Manual with GE repo
- Build 5fc8e6d
- Git 2.30.0.windows.2 (recommended: 2.41.0 or later)
- .NET 6.0.14
----
> Improved context menu detection when using keyboard

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.BackgroundUpdater.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #11166
Might fix #10957
- `BackgroundUpdater.WrappedOperationAsync()`: Avoid getting stuck on exception by adding `try finally`
- `RevisionGraph.IsRowCacheDirty()`: Safer detection by adding an additional check; rename for clarity
- Call `RevisionGraph.CacheTo()` from single context only
N/A
- extensive runs of existing tests
----
> Avoid and cope with exceptions on graph reload

- GitCommands/RevisionReader.cs
Avoid replace \v in email etc (not needed, performance).
Make revision reading slightly easier to read.
[IDE0008](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/ide0007-ide0008) in RevisionReader.cs
This originated as a review to see if it was possible to improve the performance, primarily to see if allocations could be eliminated, but it does not seem there is big difference.
Still, this is critical code when opening repos.
Manual
----
> Revision reader tweak

- GitCommands/CommitDataManager.cs
- GitCommands/Git/GitModule.cs
Follow up to #11020
Shift-return adds vertical tab in the message which may be rendered as an unknown char instead of as s return.
#11020 presented vertical tab for messages newer than six months (body is not saved for older). The vertical tab was not presented as a return for older commits, fetched when needed.
(#11020 also handles \vas \n when entering text.)
Seen when working with #11170 
As I have not found a commit with \v older than six months, this is a dummy commit and a a change to not save the commit body for older commits.
\t were not shown in CommitInfo
https://github.com/gerhardol/gitextensions/pull/new/tmp/i11020-vertical-tab-return
Manual
---- …
> Present vertical tab as return in commit message

- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitUI/GitUIExtensions.cs
Fixes #11164 (and probably a few more)
Present the error output from git-diff that fail in the diff viewer instead of starting NBug.
git-diff is expected to be Git or user error, no need to show NBug in this scenario.
The error is not suppressed, it can still be reported manually (this could still be a GE issue, as in my error insertion).
This is a hack, especially for the submodule status.
Inserted error by editing the code
NBug popup
manual
----
> Present git-diff errors in diffViewer

- BugReporter/BugReportForm.cs
- GitCommands/Git/Executable.cs
- GitCommands/Git/Status.cs
- GitUI/NBugReports/BugReportInvoker.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
Fixes #10543
Fixes #11165
Fixes https://github.com/gitextensions/gitextensions/pull/11074#issuecomment-1688928982
- Throw `OperationCanceledException` instead of plain `ExternalOperationException` on `Ctrl+C` exit code from external process in order to avoid (bug report) popup
- Fixup `ReportFailedToLoadAnAssembly`:
- only if the `FileNotFoundException` message starts with the specific "Could not load file or assembly"
- remove lengthy version info from displayed message
- handle `isTerminating`
- simplify (like other usages)
- use warning icon
- Add descriptions to `Ignore` / `Report` buttons and use warning icon in case of `ExternalOperationException`
- Disable `Send and quit` for `UserExternalOperationException` (The `Copy` button can be used.)
- Add exception text "External program …
> Improve exception reporting

- GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
that introduce some strange behavior
where it opens the choose directory dialog when "Enter" in pressed regardless from where the focus is.
Really strange if we are in one of the textareas because we can't create a new line...
- Manual
- Build 1758ddfcea7754b9828bac77b25fe51c94d5ee53 (Dirty)
- Git 2.40.0.windows.1 (recommended: 2.41.0 or later)
- .NET 6.0.21
```
Microsoft.WindowsDesktop.App 6.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program …
```
> FormCleanupRepository: unset form AcceptButton

- GitUI/CommandsDialogs/FormCherryPick.Designer.cs
- GitUI/CommandsDialogs/FormCherryPick.cs
- GitUI/CommandsDialogs/FormCherryPick.resx
- GitUI/Translation/English.xlf
- Inherit from `GitExtensionsDialog` and update the layout.
- Rename controls and few other chores.
- Add "Abort" button that breaks the "cherry-pick many commits" sequence. It's possible to break the sequence by closing the dialog with the "X" button, but it's rather unintuitive.
- Add "Help" button which opens https://git-extensions-documentation.readthedocs.io/en/main/modify_history.html#cherry-pick-commit.
Before | After
-- | --
----
> Update cherrypick dialog

- UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
- appveyor.yml
Save the `HangReporter` [dgml reports](https://learn.microsoft.com/visualstudio/modeling/directed-graph-markup-language-dgml-reference) so that those can be opened in VS for further investigations.
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/47948910/artifacts
For example,
----
> Better report test hangs

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
- GitUI/LeftPanel/LocalBranchNode.cs
- GitUI/LeftPanel/RemoteBranchNode.cs
- GitUI/MessageBoxes.cs
- GitUI/Translation/English.xlf
Fixes #11116
- In Settings / Advanced / Confirmations / section Branches added `Checkout branch using left panel` checkbox (disabled by default). 
- By checking it, every time a user double-clicks on a branch on left panel, a message box will prompt asking to confirm if the user wants to checkout branch.
- Manual with GE repo
- Tried closing and reopening the application. The selected option is saved after closing and reopening.
- Build 6a64d95
- Git 2.30.0.windows.2 (recommended: 2.41.0 or later)
- .NET 6.0.14
---- …
> Option - ask for confirmation on branch checkout

- GitUI/CommandsDialogs/FormFileHistory.Designer.cs
Fixes #11071 File History window: last commit is hidden under action bar
- Added padding to the revision grid in the the file history window. Now the latest commit is not under the action bar.
The File History window **without** checkbox `Show file history in the main window`:
The File History window **without** checkbox `Show file history in the main window`:
The File History window **with** checkbox `Show file history in the main window` (was not changed):
- Test this changes with checkbox `Show file history in the main window` and without that.
- Test that winforms designer of form `FormFileHistory` still works correct.
- GIT version 2.41.0.windows.1
- Windows 10 Pro
---- …
> Fixed padding of the revision grid in the file history window

- GitUI/CommandsDialogs/FormDiff.cs
Fixes #11200
- FormDiff: Let DiffFiles decide about the diff groups in order to be consistent with other FileStatusLists
- manual
----
> Diff window: Avoid duplicate diff group

- GitCommands/Git/EnvironmentConfiguration.cs
Minimalist alternative to #11182. This adds an environment variable that forces SSH_ASKPASS to be used even if a terminal is available. Requires OpenSSH 8.4 or higher. Has no effect on older versions of OpenSSH.
(The version that comes with Windows 10 is, unfortunately, 8.1. However, 9.2 is available via winget)
Inputting a password is done via the console emulator.
Inputting a password is done via the `GitExtSshAskPass.exe` popup.
- Performed fetch from a remote server
- Inputted the password in the popup
- GIT 2.41.0.windows.1
- Windows 10.0.19045
----
> Force OpenSSH to use SSH_ASKPASS if a password is requested

- GitCommands/Git/Executable.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitCommandRunner.cs
- GitCommands/Git/GitModule.cs
- GitCommands/RevisionReader.cs
- Plugins/GitUIPluginInterfaces/IExecutable.cs
- Plugins/GitUIPluginInterfaces/IGitCommandRunner.cs
- Plugins/GitUIPluginInterfaces/IProcess.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
- UnitTests/GitCommands.Tests/ExecutableTests.cs
- UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
Fixes #9818
Preparation for #9418
- `Executable`:
- Kill the process on disposal if cancellation was requested
- Factor out `HandleProcessExit` from `OnProcessExit`
- `GitCommandRunner`:
- `RunDetached` with and without cancellation
- log exit code
- Make cancellation of `ExecuteAsync(this IExecutable executable, ...)` work: await exit first, then await the output with cancellation
- `RevisionReader`: Start processes with cancellation
N/A
- add tests
----
> Make ExecuteAsync cancellable and kill canceled processes

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- IntegrationTests/UI.IntegrationTests/UITest.cs
I'm unable to run the LeftPanel-related tests (e.g., `RepoObjectTree_moving_first_up_and_last_down_does_nothing`) locally, they just lock up after the dialog is closed. My investigations suggest that there are outstanding async operations in `GitStatusMonitor`.
The sequence of event is something like the following:
- The form is closed disposing itself and `GitStatusMonitor` monitor (`FormBrowse.Dispose`).
- Despite of that `GitStatusMonitor` continues to execute `Update` operation, which continues making git calls and reschedules itself.
I was able to make the tests to pass to completion with the added early exits by checking the cancelled token and adding a `disposed` flag.
> Cancel pending GitStatusMonitor operations on form dispose

- GitCommands/Git/GitModule.cs
- GitCommands/RevisionReader.cs
by retrieving all the commits data with only one `git log` call instead of one by commit.
It is possible as when rebasing, all the commits belong to the same branch.
Kept a fall back to previous way to retrieve commit data for 1 commit if commit is not in the one loaded.
Results to show the rebase popup with 7448 commits rebased: 2s instead of 4m50 previously
Fixes #10698 and fixes #11196
- Manual
- Build acee8341dc4bb07b1a576d3ddf468ed0f459942b (Dirty)
- .NET 6.0.21
```
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program …
```
> Rebase: improve perfs when displaying list of commits

- GitCommands/Git/GitModule.cs
- GitUI/GitUICommands.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- Remove mostly unused and basically impossible result (due to detached execution) from all variants of OpenWithDifftool 
N/A
- adapted existing tests
----
> Remove impossible result from OpenWithDifftool

- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/Hotkey/KeysExtensions.cs
- Add hotkey `F8` (default) to ToolStripButton `Default Pull/Fetch`
- manual
----
> Add hotkey to ToolStripButton Default Pull/Fetch

- GitCommands/Logging/CommandLog.cs
- GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
- GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.resx
- GitUI/Translation/English.xlf
- Remove git configuration options from the displayed arguments of git processes in the ListView
in order to show the git verb first
- Increase column width for ProcessId
- Add mnemonics and shortcuts to the context menu
- Add context menu item `Copy full command line`
- manual
----
> Git Command Log: Show git verb; extend context menu

- GitCommands/Git/GitModule.cs
- IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
by using "done" file for commits already processed
and "git-rebase-todo" for what will be **really** done next.
because "git-rebase-todo.backup" content is not accurate
(it contains what was presented to user in interactive rebase
**before** user choose which actions to do on commits)
it fixes "action" column value that was not accurate
and commits that was reordered.
fixes #11179
See reporting issue #11179 
- Manual
- Build f0a4b7d360bbaae54b0d9ea7680e7866c85df53b
- .NET 6.0.21
```
Microsoft.WindowsDesktop.App 7.0.10 …
```
> Rebase: fix accuracy of data in list of commits displayed

- GitCommands/Git/GitModule.cs
- GitCommands/RevisionReader.cs
- Plugins/GitUIPluginInterfaces/ObjectId.cs
- UnitTests/GitCommands.Tests/Git/ObjectIdTests.cs
- UnitTests/GitCommands.Tests/GitRevisionInfoProviderTests.cs
Use optimized Utf8Parser(Span<>) methods to parse Git commit hashes.
Remove unused methods.
Benchmark for `TryParse(in ReadOnlySpan<byte> array)` that run in average 3.1 times for each commit (for linux repo).
To parse 100000 commits (default in GE) was before 290 ms, now it is 110 ms
The total load time therefore reduced with 550 ms. For GE this is about 160 ms.
There is a similar performance improvement for other methods but they are not performance critical.
I may add that reducing checks and additional method calls is critical in these scenarios.
Using a loop instead of five separate calls with fixed parameters was 160 ms.
Using multiple wrapper calls instead of calling the Span methods directly could add similar delay.
As the grid is displayed before all data is parsed, the visible …
> Optimize ObjectId parsing

- GitCommands/Git/GitDescribeProvider.cs
- Plugins/GitUIPluginInterfaces/ObjectId.cs
- UnitTests/GitCommands.Tests/Git/ObjectIdTests.cs
only one usage
This is adding some additional code when data structures are changed in a separate PR.
This can be optimized, but I do not feel it is worth it.
Only used in an async call to get CommitInfo where several Git commands are called.
This will cause one string allocation too.
Related to #11223 as this PR removes some additional changes there.
Manual
----
> Remove ObjectId.Equals(string)

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs
- Hide RevisionGrid tooltip on `Escape` keypress
N/A
- manual
----
> RevisionGridControl: Hide tooltip on Escape

- GitCommands/CommitMessageManager.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
- UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
Fixes self-delusion
Actually check the CommitMessageManager ctor argument `owner` for `null`, not its name
N/A
- adapted existing tests
----
> CommitMessageManager: Fixup ThrowIfNull

- GitCommands/RevisionReader.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test_testName=reflogselector_empty.verified.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitCommands.Tests/TestData/RevisionReader/reflogselector_empty.bin
Regression in #11225
Reflog selector identifies stashes and only listed with git-stash-list. However, the reflogselector can still be empty occasionally also in this situation for instance when Git Notes are displayed. These empty reflog selectors should not be presented as stashes.
For efficiency reasons the test is only for null values, i.e. empty reflog selectors must be presented as null. (In addition, a string should not be allocated even if string interning should eliminate the allocation need, there is still overhead).
https://github.com/gitextensions/gitextensions/blob/master/Plugins/GitUIPluginInterfaces/GitRevision.cs#L111
Test adjusted
----
:black_nib: I contribute this code under [The Developer …
> RevisionReader: No reflog for notes

- GitUI/CommandsDialogs/FormPush.cs
Check if a branch is selected only if the 1st tab is the selected one
and so allowing to push tags (from 2nd tab) or multiple branch (3rd tab) even if no branch is selected in 1st tab.
It's more likely to happen if you are in a submodule that has no branch checked out but you want to push something...
- Manual
- Build 8f017f6b0bc303f5fdb54aa5e61da791a8248da3
- .NET 6.0.21
```
Microsoft.WindowsDesktop.App 7.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
I agree that the maintainer squash merge this PR (if …
> FormPush: Allow push from other tabs even if no branch is selected in 1st tab

- GitExtensions/Properties/launchSettings.json
- GitUI/Editor/FileViewer.cs
by better handling of hotkeys in FileViewer
i.e. let a chance to the editor control to handle it if the feature with the associated hotkey is not available/enabled
+ add a Debug Launch profile to be able to test it
Integration of https://github.com/gitextensions/ICSharpCode.TextEditor/pull/33 in GitExtensions
None.
- Manual ( With the added Debug Launch profile)
- GIT 
- Windows 
----
> editor: Add feature to move line up/down with ALT + UP/DOWN

- GitCommands/Git/GitModule.cs
https://github.com/gitextensions/gitextensions/pull/11011#discussion_r1346540551
Used in FormCommit
Manual
----
> Add comment for skip worktree together with assume unchanged

- GitCommands/CommitDataManager.cs
- GitCommands/Git/GitModule.cs
- GitCommands/RevisionReader.cs
- GitExtUtils/Delimiters.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- ResourceManager/LocalizationHelpers.cs
- UnitTests/GitCommands.Tests/CommitDataManagerTest.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test_testName=notes_data.verified.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test_testName=notes_empty.verified.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test_testName=vertical_tab.verified.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitCommands.Tests/TestData/RevisionReader/notes_data.bin
- UnitTests/GitCommands.Tests/TestData/RevisionReader/notes_empty.bin
- UnitTests/GitCommands.Tests/TestData/RevisionReader/vertical_tab.bin
Do not allocate when replacing VerticalFeed.
Add vertical feed test.
Optionally read Git Notes in RevisionReader
Tests were added.
Use RevisionReader to parse revisions also in
CommitData and GitModule.
This require support of Notes.
Add LogOutputEncoding to IGitModule so RevisionReader can use the interface internally.
If showing Git Notes, read them when loading the grid so they are handled with the Body in the standard scenario.
Notes are then displayed in the rev grid tooltip also before the revision is selected.
--
This has minimal effect on performance. If Notes is not shown, there is one extra `if` and two more if Body is stored.
If Notes is shown, git-log may be slower, but the error of margin when measuring is larger than the possible slowdown.
(Some special handling in RevGrid …
> Use RevisionReader to read GitRevision with Notes

- GitUI/CommandsDialogs/SettingsDialog/Pages/HotkeysSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitModuleControl.cs
Resolves #11253
As reported in https://github.com/gitextensions/gitextensions/pull/11239#issuecomment-1751968802 (/cc: @SlugFiller)
> Correct IScriptsManager resolution in Settings dialog

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
HEAD may not be included in git-log in some scenarios. One example is an old checkout in the Linux repo where 100K commits is about a year. Another is when filtering.
In this scenario there is no HEAD the artificial commits cannot be inserted while loading.
The HEAD parents are then listed to find the first descendant in the grid, or first in the grid if no head parent is found.
Similar scenario for the revision to be reselected. When switching repo the HEAD is always selected.
Previously, a match was tried in all HEAD parents. This command requires 1.5 s in the linux repo,
delaying the the time until the spinner is dismissed. The number of parents to try is limited to around 50 ms instead.
In addition, the command ran a second time as the
result was not enumerated when trying to find the …
> Limit HEAD parents when inserting artificial in grid

- GitCommands/Git/GitModule.cs
- IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs
When trying to checkout a branch **with the same name than an existing folder** like 'scripts" in GitExtensions repository, git fails when running command line: git rev-list afe67a23d35300169ba539bb220be43e788dbfb0 ^scripts --count
with error:
fatal: ambiguous argument 'scripts': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Fix: replace by command line:line
git rev-list afe67a23d35300169ba539bb220be43e788dbfb0 ^scripts --count --
No error
- Manual (and command line)
- Build d1d0db08325987de1e2dc10a170a10e96f65292e (Dirty)
- .NET 6.0.21
``` …
```
> Checkout: fix git error when branch name is ambiguous

- GitExtUtils/DebugHelpers.cs
Follow-up to #11270
`DebugHelper`: Just call `Debug.Fail()` when running tests - instead of `Debugger.Launch()`.
The test runner catches debug assertions.
- run tests for debug build
----
> Do not launch debugger on Debug.Fail in test run

- GitUI/LeftPanel/RepoObjectsTree.cs
Fixes #11122 
Bypass hotkeys processing when the user is in branch search control. This should eliminate the possibility of unexpected behavior while editing. 
Manual
- GIT 2.41.0
----
> Bypass hotkeys processing when inside SearchControl

- Plugins/BuildServerIntegration/GitlabIntegration/GitlabAdapter.cs
GitLab occasionally raises exceptions when reloading bigger repos (like Linux).
The "pipeline loader" starts tasks that also access this specific Dictionary.
```
System.InvalidOperationException
HResult=0x80131509
Message=Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
Source=System.Private.CoreLib
StackTrace:
at System.ThrowHelper.ThrowInvalidOperationException_ConcurrentOperationsNotSupported()
at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
at GitExtensions.Plugins.GitlabIntegration.GitlabAdapter.ProcessLoadedBuilds(IEnumerable`1 items, IObserver`1 …
```
> GitLab exception with concurrent access

- .editorconfig
https://github.com/gitextensions/gitextensions/pull/11284#issuecomment-1767449502
Default values added by VS for new settings
Setting to error seem to only have effect for local builds, not for AppVeyor so changed to error
Manual
----
> Warning for IDE0008 Use explicit type instead of var

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Avoids #11292 but deactivates #10915
- Always assign `LaneSharing.ExclusiveOrPrimary` in order to avoid deep nested calls of `_previousRow.GetLaneForSegment()`
- open Linux repo
----
> Deactivate very slow handling of lane sharing

- GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/LaneInfo.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs
General changes to improve cpu execution and to
limit allocations. Some changes are very minor like
using for instead of foreach, other changes the data structures.
Separate storage of nodes that has no GitRevision.
This allows to remove a separate node storage and
to simplify the code.
Use ImmutableArray instead of array and list for the ordered caches
to improve allocations.
Force update data grid when revision graph nodes have been modified
The order of nodes in the revision graph may change if the commits are
listed out of order or if artificial commits are inserted.
The revision graph was (normally) invalidated but the data grid was only
refreshed if scrolling.
Use separate counter for revisions to limit
the lock time for _revisionByObjectId.Count
Rename variables and add comments …
> RevisionGraph: improve internal structures

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
When refreshing a repo, an attempt is done to preserve the selection.
This detection is done by resetting the selection if the checkedout commit changes, selecting HEAD if there is one, otherwise none.
The 'unselect' was only done if the new repo had a checkedout. So no checkedout tried to select a commit that no longer exists (unless it was an artificial commit).
There was an assert especially when opening an empty repo.
Some comments:
* The assert could be replaced with a Trace printout, the situation is handled
* Selection could be kept if there is at least one artificial.
* If no selection, artificial could be selected if shown.
* As commented in the code:
```
// This will assert if switching from one repo with no checkout but with a revision selected
// to a repo also without a …
```
> Reset selection when opening a repo without a checkout

- GitCommands/Git/GitDirectoryResolver.cs
- GitCommands/Git/GitModule.cs
- GitCommands/PathUtil.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- GitUI/CommandsDialogs/FormCleanupRepository.cs
- UnitTests/GitCommands.Tests/Git/GitDirectoryResolverTests.cs
Fixes #11303
Symbolic links in WSL cannot be accessed from Windows.
This adds some workarounds that makes it possible to open such repos,
that has been created for instance with Google's repo tool.
All access from Windows will fail, only access by WSL native like "wsl git" works.
At least the following do not work:
* Display of branch names for (mostly using .git/HEAD to get the name). wsl git can be used here.
* Git commands using Windows Git (like difftool from submenu with all tools) will fail. (Even listing of tools fail, for instance when closing settings).
* GE Settings cannot be read/write to local repo
* Commands using the local .git config will not work. This includes Commit, rebase etc
You can still view information and compare branches though
All issues will likely not be …
> Symbolic links to .git in WSL

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes https://github.com/gitextensions/gitextensions/pull/11273#discussion_r1361134225
Replaces the undesired #11278
Trigger the `IGitUICommands.RepoChangedNotifier` after the execution of scripts and plugins
instead of manually performing updates on `CommandStatus.NeedsGridRefresh`
N/A
----
> Trigger RepoChangedNotifier after script / plugin

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/Script/ScriptOptionsParser.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Fixes [this comment](https://github.com/gitextensions/gitextensions/issues/1826#issuecomment-1759308175)
- introduce a new option `{HEAD}` that contains the name of the currently checkout branch (and as a consequence avoid user branch selector when using {cLocalBranch}) or the hash of the commit if in detached head
- update the help text so that the user understand that the options are acting on a revision and so has a little more clue that {cLocalBranch} will not return the current checkout branch but let the user select a branch among all defined on the revision. Same for tags, remote, branch...
- Unit tests
- Manual
- Build af8e9e153708dc4f087d65f1c5726ae4a4a6cd5f (Dirty)
- .NET 6.0.21
- DPI 96dpi (no …
> Scripts: add new option {cHead}

- GitUI/GitUICommands.cs
- GitUI/LeftPanel/BaseBranchLeafNode.cs
- GitUI/LeftPanel/BaseRevisionNode.cs
- GitUI/LeftPanel/SubmoduleNode.cs
Replace `GitUICommands.Browse*` wrapper functions with direct calls `GitUICommands.BrowseRepo?.*` in order to
- reduce the size of `IGitUICommands`
- emphasize the optionality of those functions
N/A
----
> Remove GitUICommands functions wrapping BrowseRepo

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitModuleControl.cs
- GitUI/GitModuleForm.cs
- GitUI/ScriptsEngine/IScriptHostControl.cs
- GitUI/ScriptsEngine/IScriptsRunner.cs
- GitUI/ScriptsEngine/ScriptOptionsParser.cs
- GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- GitUI/ScriptsEngine/ScriptsManager.cs
- GitUI/UserControls/InteractiveGitActionControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/ScriptEngine/ScriptRunnerTests.cs
- Plugins/GitUIPluginInterfaces/IBrowseRepo.cs
- Plugins/GitUIPluginInterfaces/IGitUICommands.cs
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Fixes first part of https://github.com/gitextensions/gitextensions/pull/11321#discussion_r1380833106
- Move all current `IScriptHostControl` functions to `IBrowseRepo` because
- RevisionGridControl access is provided via `IGitUICommands.BrowseRepo`
- RevisionGridControl access is needed in addition to other script hosts in the future
That's why keep the empty `IScriptHostControl`.
- Provide `IWin32Window owner` to `FormQuickItemSelector.ShowDialog`
- Remove obsolete property `virtual RevisionGridControl? GitModuleForm.RevisionGridControl`
N/A
- adapt existing tests
- reactivate ignored test
----
> Move IScriptHostControl functions to IBrowseRepo

- GitUI/HelperDialogs/FormProcess.cs
- GitUI/HelperDialogs/FormStatus.cs
- GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
Fixes: preparation for git output / history control
- Ensure that `FormStatus` has a `GitUICommands` instance.
- Pass GitUICommands instance to FormStatus when running scripts by downcasting from IGitUICommands to GitUICommands
- Make GitUICommands instance mandatory for FormStatus & FormProcess
N/A
----
> Provide IServiceProvider to FormStatus

- GitCommands/Settings/AppSettings.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- Call the factory method `ISetting<T>.Create<T>()` only once, i.e. not every setting access
- Turn `AppSettings.ConfirmBranchCheckout` into a get-only property in order to be compatible with `AppSettingsTests`
N/A
- existing + added testcases
----
> Improve performance of AppSettings of type ISetting<T>

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
- GitUI/GitModuleControl.cs
- GitUI/GitModuleForm.cs
- GitUI/LeftPanel/RepoObjectsTree.ContextActions.cs
- GitUI/LeftPanel/RepoObjectsTree.cs
- GitUI/ScriptsEngine/IRunScript.cs
- GitUI/ScriptsEngine/IScriptHostControl.cs
- GitUI/ScriptsEngine/IScriptOptionsProvider.cs
- GitUI/ScriptsEngine/IScriptsRunner.cs
- GitUI/ScriptsEngine/ScriptOptionsParser.cs
- GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- GitUI/ScriptsEngine/ScriptsManager.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/ScriptEngine/ScriptRunnerTests.cs
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Supersedes #11321
- Remove IRunScript
- Turn empty `IScriptHostControl` into `IScriptOptionsProvider` with `string GetValue(string option)`
N/A
----
> Remove IRunScript & IScriptHostControl and prepare IScriptOptionsProvider

- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/BoolRuntimeSetting.cs
- GitCommands/Settings/EnumRuntimeSetting.cs
- GitCommands/Settings/IRuntimeSetting.cs
- GitCommands/Settings/ISetting.cs
- GitCommands/Settings/RuntimeSetting.cs
- GitCommands/Settings/Setting.cs
- GitCommands/Settings/SettingsPath.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SortingSettingsPage.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- UnitTests/GitCommands.Tests/Settings/RuntimeSettingTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterToolBarTests.cs
Fixes #10009
- Store the most important view settings on request only
(RefLog, CurrentBranchOnly, BranchFilterEnabled, RevisionSortOrder, FileViewer toolbar flags)
Before|After
-|-
- manual
- new tests for `RuntimeSetting<T>`
----
> Store view settings on request only

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/Editor/FileViewer.cs
- GitUI/LeftPanel/RepoObjectsTree.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #11329
- Always call `ReloadHotkeys` from `OnRuntimeLoad`
There is no need to call it from `OnUICommandsSourceSet` because the ServiceProvider shall not be exchanged during runtime.
In addition, `OnUICommandsSourceSet` is not always triggered as necessary.
- Call all `ReloadHotkeys` from `FormBrowse.HandleSettingsChanged`
- Call `LoadCustomDifftools` only once from `OnRuntimeLoad`, too
N/A
- manual
----
> Load hotkeys consistently

- GitCommands/Settings/AppSettings.cs
- GitExtensions/Program.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- UnitTests/GitUI.Tests/UserManual/StandardHtmlUserManualFixture.cs
Fixes #11338
Supersedes #11339
- Pass `AppSettings.ProductVersion` to `AppSettings.SetDocumentationBaseUrl` 
N/A
- adapted tests
----
> SetDocumentationBaseUrl using ProductVersion

- GitCommands/Git/Commands.Arguments.cs
- GitCommands/Git/Commands.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/Tag/GitTagController.cs
- GitCommands/PathUtil.cs
- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitUI/CommandsDialogs/FormApplyPatch.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- UnitTests/GitCommands.Tests/Git/CommandsTests.CreateTag.cs
- UnitTests/GitCommands.Tests/Git/CommandsTests.cs
- UnitTests/GitCommands.Tests/Git/Tag/GitTagControllerTest.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Fixes https://github.com/gitextensions/gitextensions/pull/11308/files#r1394980653
- Restore adapted path for `commit` command
- Rename `GetGitExecPath` to `GetPathForGitExecution` in order to avoid misleading abbreviation
- Force all callers to pass `GitModule.GetPathForGitExecution`
N/A
- adapted existing tests
- add testcase for the regression
----
> Fixup regression in Commands.Arguments.Commit

- GitUI/CommandsDialogs/FormCommit.cs
Addresses https://github.com/gitextensions/gitextensions/pull/11239#discussion_r1391544925
- FormCommit always has a `_currentFilesList`
N/A
- manual
----
> FormCommit always has a _currentFilesList

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- Plugins/GitUIPluginInterfaces/ExecutionResult.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
Fixes #11366
Fixes #11368
- Let git deny the commit if committer is not specified
- Let `GetEffectiveGitSetting` return ``null` if the setting is not set
- Remove `FormCommit.OnActivated` in order to avoid repeated exception popups from the only called function `UpdateAuthorInfo`
Exception (repeated exceptions unless repeating `Esc`)
- manual
- adapt affected testcase
----
> Let git deny the commit if committer is not specified

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs
- UnitTests/Plugins/DeleteUnusedBranches.Tests/GitBranchOutputCommandParserTests.cs
by parsing correctly the output of the command
`git branch --list --merged HEAD`
that contains "+ " prefix in front of branch names checked out in git worktrees
+ add support of some other edge cases
Fixes #11375
+ makes git log command a little more resilient by appending '--' like done in #11277 (if it will fail in the future, it will be with a little better error message)
- unit tests
- manual
- GIT 
- Windows 
----
> Delete unused branch plugin: Makes GetBranchNames() support worktrees

- GitExtSshAskPass/SshAskPass.cpp
because "By default, windows console does not process wide characters."
See https://stackoverflow.com/a/15450250/717372
& https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/setmode?view=msvc-170&redirectedfrom=MSDN
Fixes #11379
- Manual (and it's a pain!)
- Run `./GitExtSshAskPass.exe` **from git bash** (the others consoles don't display outputs or display it wrong!!)
- or run `.\GitExtSshAskPass.exe > output.txt` and check file content
- GIT 
- Windows 
----
> GitExtSshAskPass: Ensure chars are outputed as UTF8 chars

- GitCommands/UserRepositoryHistory/Legacy/RepositoryStorage.cs
- UnitTests/GitCommands.Tests/UserRepositoryHistory/Legacy/RepositoryStorageTests.cs
Fixes #11383
Do not migrate empty settings
manual edit the settings file
----
> Do not migrate empty settings

- GitCommands/Git/GitModule.cs
Fixes #11391
Avoid a popup when resetting worktree files
manual
----
> Avoid popup resetting new file to index

- GitUI/CommandsDialogs/FormBrowse.cs
and hide the tab
Fixes #11388
Crash
We don't see the tab anymore:
- Manual
- Build 6dd05e51f3540f6d9d0ee2c8b12e780230c8c1c6 (Dirty)
- .NET 6.0.25
----
> GPG: don't crash on artificial commits

- GitUI/Editor/Diff/CombinedDiffHighlightService.cs
- GitUI/Editor/Diff/DiffHighlightService.cs
- GitUI/Editor/Diff/ITextHighlightService.cs
- GitUI/Editor/Diff/RangeDiffHighlightService.cs
- GitUI/Editor/Diff/TextHighlightService.cs
- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/Editor/IFileViewer.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormEditorTests.cs
The primary intention with this PR is to prepare FileViewer for git-grep in #4912 
A separate PR will be opened for the actual changes, the UI is to be discussed.
However, these changes improves the structure regardless and is opened separatetly.
Add a base class for the highlight service primarily used for diff highlighting.
Rename AddPatchHighlighting() to AddTextHighlighting() as the method
also have other uses.
The DiffHighlightService also handles the format for patching etc,
used when copying patches and navigating next/previous.
Separate the unrelated HighlightLines() currently only used by Blame to
mark all kind of lines.
Remove unused HighlightLine()
Limit exposure of internal structure by moving some text handling
to FileViewerInternal.
Remove the unused functions from …
> Prepare FileViewer for git-grep

- GitUI/CommandsDialogs/FormBrowse.cs
- Manual
- Build 69d17129d78cefd5c98d5ada53ee7bc643c51456
- .NET 8.0.0
----
> Remove bad shortcut association (rebase on pull-rebase)

- GitCommands/Git/Tag/GitTagController.cs
- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/CommandsDialogs/FormReflog.cs
- GitUI/CommandsDialogs/FormSparseWorkingCopyViewModel.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
- GitUI/GitUICommands.cs
- GitUI/LeftPanel/RepoObjectsTree.ContextActions.cs
- GitUI/ScriptsEngine/ScriptOptionsParser.cs
- GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- GitUI/ScriptsEngine/ScriptsManager.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/ScriptEngine/ScriptRunnerTests.cs
- Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/GitHub3/GitHub3Plugin.cs
- Plugins/GitUIPluginInterfaces/GitUIEventArgs.cs
- Plugins/GitUIPluginInterfaces/IGitUICommands.cs
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- ResourceManager/GitPluginBase.cs
- UnitTests/GitCommands.Tests/Git/Tag/GitTagControllerTest.cs
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
- UnitTests/GitUI.Tests/Script/ScriptsManagerScriptRunnerTests.cs
> Remove redundant GitUICommands.GitModule

- Plugins/Statistics/GitImpact/ImpactControl.cs
- contributors.txt
Fixes #11409 
Add waiting cursor when mouse is over the form to be painted.
- 
- Built and ran.
- GIT 2.42windows2
- Windows 10 22H2
----
> UseWaitCursor when waiting for Impact Graph results (#11409)

- GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildInfo.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_master_build.verified.txt
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.verified.txt
Unknown and stopped are both grey
Status: Failure, Success, Unstable, Stopped, In progress, Unknown
- Manual
- Build 2bc70dbb9e9d797be7aa8c9a96cf5453786b38cf (Dirty)
- .NET 6.0.16
----
> CI: more meaningful icon instead of displaying a circle

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #11424
- Ignore fetch/push options in `GetRemotesAsync`
N/A
- extended testcase
----
> Ignore fetch/push options in configuration of remote repos

- GitUI/Plugin/FailedPluginWrapper.cs
- GitUI/Plugin/PluginRegistry.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
When a plugin fail to load and an exception is raised, no plugin was added to the `Plugins` collection
and so none was added to the menu in the UI.
Will mitigate the case where external plugins not (yet) compatible won't prevent internal plugins to load.
- Manual ( test a current `master` with #11397 )
- Build b98f9600d6dd6de04644191a64b2881fff057fd9 (Dirty)
- .NET 8.0.0
----
> Plugins: Fail to load a plugin no more prevent loading of all others

- GitUI/LeftPanel/TagNode.cs
Fixes #11427
- Open the `FormCheckoutRevision` using the `UICommands.StartCheckoutRevisionDialog`,
which wraps the call with `DoActionOnRepo`, runs pre/post scripts and notifies about the repo change 
N/A
- manual
----
> Refresh after checking out tag using Left Panel

- GitCommands/Settings/AppSettings.cs
- contributors.txt
I`m compiling (and happily running) GE for dotnet 8, using latest VS2022 Enterprise and R#. 
Unit tests fail one assertion, because the host exe is not on the short whitelist. 
This PR simply adds dotnet.exe to this list.
----
> Tests runnable under dotnet 8 and latest R# - allow dotnet.exe as host

- GitCommands/Git/Commands.Arguments.cs
to prevent a Debug failure to be raised (and opening a VS instance on debug builds)
Made useless following a refactoring of the api that now accept all path format and convert it in posix
No UI change
- Manual
- Build 403278735fbbfe378600e73b4c7e13e6b49957c9 (Dirty)
- .NET 8.0.0
----
> FormResetAnotherBranch: remove useless failing assert on posix path

- BugReporter/BugReportForm.cs
Theses usages have no effect as the value should be re-affected.
- Manual
- Build 286b49ba21e909d81c8399ffb3ad2745a611c22f
- .NET 6.0.21
----
> BugReportForm: Remove badly used `DpiUtil.Scale()`

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/LeftPanel/BaseRevisionNode.cs
- GitUI/LeftPanel/BaseRevisionTree.cs
- GitUI/LeftPanel/Node.cs
- GitUI/LeftPanel/RepoObjectsTree.SettingsContextMenu.cs
- GitUI/LeftPanel/Tree.cs
Improvement over https://github.com/gitextensions/gitextensions/discussions/11441#discussioncomment-7829262
- Improve performance when reloading left panel (with 20k refs in repository, treeview refresh block the UI now around 2.5s while it was around 6.5s before this fix). Note: the first loading is still slow but after it's much more usable.
- Fix a temporary bad state that is much more likely to occur when ahead/behind data are retrieved (which are slow)and now that treeview load quicker.
- Some other small performance improvements
- Manual
- Build 4c9e8a8f933d2ba5aab92569b5c53bc17069f253
- .NET 8.0.0
I agree that the maintainer *rebase* merge this PR (if the …
> Improve performance of left panel reload

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
As we try to retain selections when switching repos, this assert is often incorrect.
A more proper assert would require more logic and info from RevGrid, just complicating.
Manual removal.
----
> Remove assert in CalculateGraphIndices()

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Recommended in https://github.com/gitextensions/gitextensions/issues/11460#issuecomment-1865099903
- Correctly rethrow exception from revision reader with the original stack trace
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
at void GitUI.RevisionGridControl.PerformRefreshRevisions(Func<RefsFilter, IReadOnlyList<IGitRef>> getRefs, bool forceRefreshRefs)+() => { } in D:/Build/gitextensions3/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs:line 1352
at async Task GitUI.TaskManager.HandleExceptionsAsync(Func<Task> asyncAction, Func<Exception, Task> handleExceptionAsync) in …
```
> Correctly rethrow exception from revision reader

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.cs
- GitUI/Properties/Resources.Designer.cs
- GitUI/Properties/Resources.resx
- GitUI/Translation/English.xlf
- GitUI/UserControls/BlameControl.cs
- GitUI/UserControls/GitBlameParser.cs
- GitUI/UserControls/Settings/SettingsCheckBox.cs
- GitUI/UserControls/Settings/ToolTipIcon.cs
- IntegrationTests/UI.IntegrationTests/UserControls/GitBlameParserTest.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- better default value for "change move detection" setting (because the "break" blame)
- Add a warning that these "change move detection" options doesn't work well with blame feature
- improve blame option labels
- better line selection when switching revision from revision grid during a blame
- better estimate line number for "blame previous commit"
(better reviewed commit by commit)
return at the  begin of file:
stay at the same line:
Scenario: go to commit 7edc265403b54dd8ea2b8402f8790219d8d42077 and blame FormBrowse.cs
then blame "previous revision" on line 2281
( the commit 52476f30670ba5338756b606841fb0a346fd6460 add a lot of lines --89-- before this line 2281 )
(we end up at 89 lines of the right position and it's very difficult to find the good code --we need to search for some …
> Improve blame feature

- GitCommands/Git/AheadBehindData.cs
- GitCommands/Git/AheadBehindDataProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/ToolStripPushButton.cs
- UnitTests/GitUI.Tests/UserControls/ToolStripPushButtonTests.cs
Follow up to https://github.com/gitextensions/gitextensions/pull/11445#issuecomment-1861751454
Update after spinner is closed
Sidepanel calls are unchanged, FormBrowse is normally start first from what I see.
A second part could be to delay the start of the command until git-log delivers revisions.
Manual - inserted delay to the Git command
----
> Calculate ahead-behind on worker thread

- Plugins/Statistics/GitImpact/FormImpact.cs
- Plugins/Statistics/GitImpact/ImpactControl.cs
- Plugins/Statistics/GitImpact/ImpactLoader.cs
Fixes #11411
1. Rendering now takes less than 1s (whereas it was taking minutes on big repositories like GitExtensions --around 7min-- or Git --around 1h08min--ones).
So now the time to build the impact graph correspond only to the time to retrieve data from repo. 
I did one benchmark on git repository for the rendering:
* before: 1h8min
* after: 0.76s (around x5300 times quicker!!)
Retrieving data still takes around 30s, so overall process was before 1h9min and after 30s (x130 times quicker!)
GitExtensions repo: now total time 23s (200ms of rendering)
2. Submodule checkbox change doesn't cancel the long main data retrieve and data are put in a cache so that switch is immediate (instead of fetching the data again every times)
3. Display is done depending on 1st day of the week culture …
> Improve (hugely!) impact graph performance

- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormFileHistoryTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs
Fixes #10970.
- Added `-m` and `--all` options to `git log` operation in the `BuildPathFilter` method in order to get the file name for all displayed commits in the File History dialog
- Manual (tested the FH dialog in various repositories - the Diff and View tabs show correct content in all commits)
- GIT  2.42.0.windows.2
- Windows 10
----
> Follow file names in merge commits and all refs

- GitUI/CommandsDialogs/FormFileHistory.cs
- FormFileHistory: Do not refresh revision grid twice on load
which is ignored before #11205
Found with #11460
that both `RevisionGrid.SetAndApplyPathFilter` and `RevisionGrid.Load` call `PerformRefreshRevisions`:
```
public new void Load()
{
if (!DesignMode)
{
PerformRefreshRevisions();
}
}
```
N/A
- manual
----
> FormFileHistory: Do not refresh revision grid twice on load

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #11467
Another command to disable in bare repos
Manual
----
> Do not get stash count in bare repos

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Fixes https://github.com/gitextensions/gitextensions/pull/11470#discussion_r1436984453
- Restore the linefeeds used in the command line before #11470
- open plugin
----
> GetObsoleteBranches: Restore linefeed in arguments

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/DeleteUnusedBranches/GitBranchOutputCommandParser.cs
- UnitTests/Plugins/DeleteUnusedBranches.Tests/GitBranchOutputCommandParserTests.cs
Fixes #11357
Symbolic references were not parsed correctly
Added test case, as well as for trailing spaces
----
> DeleteObsoleteBranches: Parse symbolic references

- GitUI/CommandsDialogs/FormBrowse.BrowseArguments.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/GitUICommands.cs
Mentioned in #11440 
#9865/38e700fae4259e71ba2a2f8e8d03ed719abe4392 opened FileHistory tab with blame enabled to improve discoverability of blame. View (instead of blame) was set as default in
#10453/d9bd1c64e0aca88235006f7e2e5d371164ca26c9
The default tab should be Diff if Blame is not shown.
Left panel is still hidden in filehstory mode
#9865/edb2a5d2d1e729ffad6c1308d00cee9a4f018a38
Manual
----
> Browse FileHistory mode: Open diff by default

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
to be able to type the script name right away
- Manual
- Build 05af8bf761f7ab5a578266b439e225cd29fd8b6b
- .NET 8.0.0
----
> Scripts: Focus property grids when creating a new one

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Nothing
- Manual
- Build 3c3c8460a9d95508a188d5e3f415350c98eee676 (Dirty)
- .NET 8.0.0
----
> CI: allow click on status cell to open build report

- GitCommands/Git/GitDescribeProvider.cs
- GitCommands/Git/GitModule.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/LeftPanel/RepoObjectsTree.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
Discussed in https://github.com/gitextensions/gitextensions/pull/11472#discussion_r1439656333
Cancel longer Git operations when selecting a new commit in CommitInfo and left panel.
The commands were running to completion, using CPU (probably not blocking UI thread as discussed in #11472).
This PR adds the cancellationToken to the most common and long running commands in CommitInfo.
(git-describe and git-cat-file is normally quick but included as no refactoring was needed.)
There are a few other Git commands in CommitInfo that are not interrupted.
These are either fast or not executed often, some more refactoring would be required to handle the cancellation in invokes etc.
No diff for the user, just showing the command log when stepping in the linux repo.
One cancellation for the diff in …
> Cancellation token for Git commands in CommitInfo

- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/Editor/IFileViewer.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/Translation/English.xlf
Enable the existing Replace popup for files that are writable.
For multiple files (including context menu in  file status list), Ctrl-H is ignored
This functionality was already implemented in FindAndReplaceForm.cs
Find is unchanged for readonly (no replace) or when starting Find
Explicitly starting replace
Added to file context menu.
Manual
----
> FileViewer Replace

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/GitBlameParser.cs
- IntegrationTests/UI.IntegrationTests/UserControls/GitBlameParserTest.cs
GetOriginalLineInPreviousCommit() (to get line number in the previous commit)
must override the git diff option from git-config to follow the user preference
and to give predictable options for tests.
Similar, rename and whitespace options must be the same for git-diff
and git-blame.
* Include current section in checks
Better matching.
* BlameParserTest should not assume clone folder name
--
was
BlameParserTest should not assume clone folder
Follow up to #11434 Test fals if clonefolder is not gitextensions. I use various worktree folders with other names, so the test fails.
There is no reason to test the name of the clone folder.
Tests also fails locally due to matchingBlameLineNumber=2291, separate isue. (blame UI is OK, so are AppVeyor tests)
Removed incorrect test case
I agree that the …
> Blame: options to git-diff to get line in previous commit

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- Plugins/ProxySwitcher/ProxySwitcherForm.cs
fixes #11490
Do not raise errors if Git config setting http.proxy is not set.
* GetGitSetting() for scoped git-config
Make it possible to get get git-config with a scope, like "--global"
* GetEffectiveGitSetting() should not cache by default
Manual
----
> ProxySwitcher Do not fail if http.proxy is not set

- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Annoying resizing of the toolbar when git status updates
Not solved, but improved.
((The remaining flicker is after first update is done and before git-status reports changes.)
Explicit refresh
Manual
----
> FormBrowse: Avoid toolbar resize while refreshing

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Fixes #11292
Revert commit c621412b43f96686c230377abbb4a83c3ac91f3b
because (implicitly) calling `RevisionGraphRow.BuildSegmentLanes` for every revision is too much in the Linux repo f.i.
For vNext, I am going to make this limit configurable.
N/A
- manual: open Linux repo and go to the initial commit when "Loading..." disappears, wait for the graph
----
> Fixup graph performance

- GitExtUtils/GitUI/ImageListExtensions.cs
- GitExtUtils/GitUI/Interops/ComCtl32/ImageListSetBkColor.cs
- GitUI/CommandsDialogs/FormBrowse.InitCommitDetails.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
Fixes #11506
A root cause was found to be an incorrect setting of the image background during `ImageList` handle creation https://github.com/dotnet/winforms/issues/10462#issuecomment-1880068488
This also suggests a clear fix:
- Set ImageList background to a value used before this regression got introduced
- Add comment instructing to remove this workaround once the fix is implemented in .NET 9 (most likely) 
FormBrowse > Commit Info
FormFileHistory
- Manually
- Windows 11
- Squash merge (there is just a single commit but this maintains PR number in a commit message)
----
> Workaround ImageList transparent image regression introduced in .NET 8

- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.cs
Helps when there are lot of branches (like in #11441)
Most of the times, user open push form to push the current branch (and so don't change the dropdown values). So prevent to load all the branches when opening the form making the form opening immediately (instead of having to wait 16s for example when having 20k branches) by deferring loading:
- Load only the current branch in "Branch to push" combobox and load and fill  **all** local branches only when the user open it (opening time of 4s when 20k branches and less than 1s when 4k. Imperceptible otherwise)
- Don't add **all** local branches in the "to" combo box but prefer adding local branch in remote combobox on the fly when pushing a new branch.
- use `AddRange()` to add a big number of branches in remotes
- Manual
- Git Extensions …
> Improve performance of push form (when a lot of local branches)

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- Fixup violations of "A row index must be less than `RevisionGraph.Count`."
N/A
----
> Fixup limits by RevisionGraph.Count

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Simplify `RevisionDataGridView.LoadingCompleted`:
- remove pointless `srollTo`
- avoid repeated evaluation of `RowCount `
N/A
----
> Simplify RevisionDataGridView.LoadingCompleted

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #11460
- RevisionGridControl: Check for cancellation before accessing non-locals
N/A
----
> Check for cancellation before accessing non-locals

- GitUI/Editor/FileViewer.cs
Add shortcuts to fileviewer context menu where several items missed shortcuts.
Most do not have any by default,
manual
----
> FileViewer: Shortcuts missing in context menu

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes regression from #11463
Fixes #9223 (at least, it worked well a few times)
- Do not update graph cache if the row is unavailable yet
- Trigger refresh when loaded
- Set `DataGridViewCellPaintingEventArgs.Handled = true` if the cell has zero size (in order to avoid endless refreshes)
missing graph or some rows drawn from outdated cache
correct graph
- manual
----
> Do not update graph cache if row unavailable

- Plugins/GitUIPluginInterfaces/ObjectId.cs
- UnitTests/GitCommands.Tests/Git/ObjectIdTests.cs
by allocating and less processing when needed
and (later) using `.ToHexStringLower()` that will be provided by .net9 https://github.com/dotnet/runtime/pull/92483
- unit tests
- manual
- GIT 
- Windows 
----
> perfs: better perf for ObjectId.ToShortString()

- GitUI/CommandsDialogs/FormBrowse.cs
(Should) Fixes #11085
- None (because I don't have a crash). Looking at stacktrace.
- GIT 
- Windows 
----
> Splitters: Fix crash when restoring size

- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitUI/GitUIExtensions.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
Abort Git commands in Diff tab file viewer.
Git commands related to the Diff tab did not use cancellation tokens so there could be lingering commands running.
Related to #11494 but diff commands run much quicker so no major impact.
manual
----
> cancellationToken for Git patch commands

- GitUI/NBugReports/BugReportInvoker.cs
Fixes #11385
(workaround)
- Ignore exception from `ListViewGroup.get_AccessibilityObject` which occasionally occurs on `GetFocus` after `OnApplicationActivated` with .NET 8.0.1 yet
N/A
- manual
----
> Ignore ListViewGroup accessibility exception

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- Manual
- Build 2c067ca81a355d7358514cf6cde9933dd1778996
- .NET 8.0.1
```
```
----
> Scripts: Last column size fit content

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/UserControls/BranchSelector.cs
- GitUI/UserControls/CommitPickerSmallControl.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
Fixes #11562
Ahead/Behind are shown in branch picker for instance for Compare,, just for information. If an artificial command is compared, git-rev-list must use HEAD instead.
Manual
----
> CommitCount: Use HEAD for artificial

- GitCommands/PathUtil.cs
- GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs
Fixes #11556
- Try to find current user install of a text editor
- Remove "Atom" editor that is no more maintained ( https://github.blog/2022-06-08-sunsetting-atom/ )
- better support for text editor in the PATH
- Manual
- Build 6d2996f15652e8c4cc65f75661e275b3832368c0 (Dirty)
- .NET 8.0.1
I agree that the maintainer **rebase** merge this PR (if the commit message is clear).
----
> Improve editors detection

- GitCommands/Settings/AppSettings.cs
- GitCommands/UserRepositoryHistory/RemoteRepositoryManager.cs
- GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
- GitUI/CommandsDialogs/FormRemotes.cs
- GitUI/UserControls/FilterToolBar.cs
- increase size of opened dropdowns to be readable
- history should not be dependent of local repo history setting (which is absolutely not related). Hard code a value is enough.
- Manual
- Build 2c067ca81a355d7358514cf6cde9933dd1778996
- .NET 8.0.1
```
```
I agree that the maintainer rebase merge this PR (if the commit message is …
> Improve Form remotes UX

- GitCommands/CommitDataManager.cs
- GitCommands/Git/Commands.Arguments.cs
- GitCommands/Git/GitModule.cs
- GitCommands/RevisionReader.cs
- GitUI/CommandsDialogs/FormCommit.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/FindLargeFiles/FindLargeFilesForm.cs
- UnitTests/GitCommands.Tests/Git/CommandsTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #11567
Quote reference names for several commands handling Git references that has quite open rules for references, including quotes and parenthesis.
https://git-scm.com/docs/git-check-ref-format#_description
I scanned for some commands I could think of in addition to ls-tree, but there could be more. Most occurrences should be handled already.
ObjectId does not need quoting.
Minimal manual tests.
Note that tests did not have to be updated.
----
> Quote Git reference names

- Directory.Packages.props
Fixes #11574
In addition to #11575 that suppresses the warning so builds succeeds.
CVE-2024-24810
Build - not tested the installer myself
----
> WIX 3.14.0

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.BackgroundUpdater.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- Remove redundant call of `_revisionGraph.Clear`
- Separate `TriggerRowCountUpdate` from `UpdateVisibleRowRange`,
which will be really split in a follow up
- use C#'s unconditional logical operator `|=`
N/A
----
> Clarify revision loading

- GitUI/CommandsDialogs/FormCherryPick.Designer.cs
- GitUI/CommandsDialogs/FormCherryPick.cs
- GitUI/GitUI.csproj
FormCherryPick has at least two problems with high DPI screens. First, its default size hides one of the checkboxes and for merge-commits hides parent commit info. Second, parent commit info header width is not scaled.
- Fix form's height calculation to work with both 100% and other scaling factors.
- Scale column header width manually
https://github.com/gitextensions/gitextensions/assets/483659/fa51dbe7-d5e0-4130-962b-1c7d796c7805
https://github.com/gitextensions/gitextensions/assets/483659/7e681e59-92dd-4b08-bffe-c363104ad67b
- Manually with 100% 125% 150% 200% scaling factors
- Windows 11
- Scaling: 100% 125% 150% 200%
---- …
> Fix FormCherryPick sizing

- GitUI/CommandsDialogs/FormStash.Designer.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusList.Designer.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/FileStatusList.resx
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs
CancellationToken for diff calculation not only when
RevDiff updates.
Simplify internal handling with FilterVisible etc
Removed property for FilterVisible as it was always true, used in all lists.
Set property GroupByRevision to true only where needed
Revised taborder, tab to Filter box before list
(other sub controls are not tab enabled).
--
FileStatusList: Delay FileLoading label
Label appears as flickering.
~~Just clear the FileStatusList while calculating the data.~~
~~This is not required, but in most situations the FilesLoading... label is very quick, appears as flickering.~~
~~The change is in a separate commit, to simplify rejection.~~
~~The first commit hides the Filter Combobox too, maybe better to keep it visible if the FilesLoading label is kept~~
--
#11350 will require this …
> FileStatusList updates

- GitUI/Hotkey/HotkeySettingsManager.cs
(no shortcut)
- Manual
- Build ebc7f90a509b388f0939e8f6ecac6524fd036adb
- .NET 8.0.1
```
```
----
> Add a default shortcut for "CreateSquashCommit"

- GitExtUtils/GitUI/TaskManager.cs
- GitExtUtils/GitUI/ThreadHelper.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.BackgroundUpdater.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/SplitterPersistenceTests.cs
- UnitTests/CommonTestUtils/AsyncTestHelper.cs
- UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
- UnitTests/GitUI.Tests/RepositoryHistoryUIServiceTests.cs
- Await cancellation of RevisionGridControl tasks on close of FormBrowse
- Handle exceptions in UpdateGraphAsync
- Cancel SwitchToMainThreadAsync on AfterTest
- Move JoinPendingOperations to AsyncTestHelper and add timeout
- Tests: Avoid direct use of ThreadHelper.JoinPendingOperationsAsync
- TaskManager.JoinPendingOperations with timeout of 1 minute
- Catch exceptions in TaskManager.JoinPendingOperations[Async]
N/A
----
> Avoid test hangs due to grid background task

- GitCommands/Settings/AppSettings.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphConfig.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Contributes to #11292
#11451 for vNext with AppSetting 
- Do not straighten graph if it is too wide with configurable limit
N/A
----
> Do not straighten graph if it is too wide

- GitUI/UserControls/RevisionGrid/Columns/AuthorNameColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/DateColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Split `ColumnProvider.Refresh` into `ApplySettings` and `Clear`
because the former conglomerate resulted in redundancies with `RevisionGraphColumnProvider.OnVisibleRowsChanged`
- Extract `RevisionDataGridView.ApplySettings` from `Refresh`
because there is no need to re-apply all `ColumnProvider` settings on every graph loading update. (This saves lots of accesses to `AppSettings` and `GetEffectiveSettings`.)
N/A
----
> Refactor `ColumnProvider.Refresh`

- GitUI/CommandsDialogs/FormPush.cs
The question to track the new branch to push
was no more asked to the user
because `_NO_TRANSLATE_Branch.SelectedItem` is null when user have not interacted with the "Branch" dropdown due to lazy loading
In all likelihood introduced by #11489
- Manual
- Build aca9886154c925df44b6cb86c3afbeae8287d6fb (Dirty)
- .NET 8.0.1
```
```
I agree …
> fix(FormPush): fix tracking detection broken

- GitCommands/Logging/CommandLog.cs
- UnitTests/GitCommands.Tests/CommandLogTests.cs
- GitCommandLog: Detect git configuration options like '-c option="value with space"' and hide them in the list (as other configuration options, too)
- manual
----
> GitCommandLog: Hide '-c option="value with space"'

- GitUI/Avatars/AvatarDownloader.cs
- contributors.txt
Fixes https://github.com/gitextensions/gitextensions/issues/11595
- Use Default credentials for proxy access when loading avatars
- Testing before : no avatar displayed when behind corporate proxy
- Testing after : avatar displayed
- GitExtensions version: 4.2.1
- GIT version: 2.43.2
- OS version: Windows 10 22H2
- .NET version: .NET 6.0.27
- Squash merge (maintainer to decide merge message, PR submitter should cleanup commits/messages at PR approval).
> Fix avatars not loading behind a corporate proxy

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes https://ci.appveyor.com/project/gitextensions/gitextensions/builds/49243493#L234
- Explicitely handle `OperationCanceledException` in `OnRevisionRead` because `System.Reactive.Subjects.Subject.Subscribe` does not forward it to `onError` for whatever reason
N/A
----
> OnRevisionRead: Handle OperationCanceledException

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUICommands.cs
- GitUI/Plugin/PluginRegistry.cs
- GitUI/Translation/English.xlf
- Plugins/GitHub3/GitHub3Plugin.cs
- Plugins/GitUIPluginInterfaces/IGitPluginForCommit.cs
- Plugins/GitUIPluginInterfaces/RepositoryHosts/IRepositoryHostPlugin.cs
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- TranslationApp/Program.cs
Improve on "However, since the startup time of GitExtensions is so long, this feature is ruined for me." of https://github.com/gitextensions/gitextensions/issues/11518#issue-2081522202 (especially the first cold start)
- FormBrowse & Dashboard: Plugins start to be loaded a little later so that revision grid loading is not blocked anymore and is displayed more quickly (revision grid displayed around 4s earlier on a cold start)
- Dashboard: 
- Load only the git hosters plugin (and later the others) making that "Clone GitHub repository" feature appears much more quickly (for that plugins need to export also "IRepositoryHostPlugin" interface)
- fix state of GitHub menu items
- Form Commit **stand alone** (i.e. launched directly from file explorer): 
- fix registering of plugins (that never …
> Improve and fix plugins loading

- GitUI/UserControls/CommitPickerSmallControl.cs
when nothing is checked out
Fixes #11609
- Manual
- Build a6bfcb6dcff5447d313dab39dcab628fcb86b6a5
- .NET 8.0.1
----
> fix(CommitPickerSmallControl): fix commit count crash

- GitCommands/RevisionReader.cs
Commit could be empty for directories not yet added or removed submodule directories.
Regression in #11570 b82e637d37a3a467f083c0b320b05a7b74171e94
(to handle refs with characters that the shell may change).
I reviewed the other changes, did not see any more potential issues.
Manual 
----
> SubmoduleInfo: Do not quote empty ref

- GitUI/CommandsDialogs/FormDiff.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Translation/English.xlf
Find file (in list) was just displayed as "Find" with the preview icon, mostly related to searching.
(Find file is a variation to the filter.)
(To search the files in the commit Find in the FileViewer must be used, by default Ctrl-F will work too).
Similar change in Compare form.
Added the preview (magnifier) icon to FileViewer find.
RevDiff
Compare
FileViewer
(left is master, there has been other cleanups recently.)
FileTree
Manual
----
> RevDiff Find file clarification

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
Should avoid `OperationCanceledException` as https://ci.appveyor.com/project/gitextensions/gitextensions/builds/49289921#L341
- Just wait for finished submodule update triggered by left panel
- Correctly dispose the per-test provider instance
N/A
- run the test (on AppVeyor)
----
> Improve flaky LeftPanelTests.Submodules

- GitExtUtils/GitUI/DpiUtil.cs
- GitUI/CommandsDialogs/FormRebase.Designer.cs
- GitUI/UserControls/HelpImageDisplayUserControl.cs
- GitUI/UserControls/PatchGrid.Designer.cs
Fixes #11606
- Use `Font` scaling. Tests with .net framework 4.7.2, .net6 and .net8 have shown that `Dpi` scaling mode doesn't work properly for controls which are placed in container controls. This [SO question](https://stackoverflow.com/questions/22735174/how-to-write-winforms-code-that-auto-scales-to-system-font-and-dpi-settings) has helped a lot.
- Adjust `Commit hash` column to fit the header text without wrapping
- Fix Help image scaling.. And as for `FormMerge` it was sad to find out that even the text above the image turns out has always been clipped
100% scaling
200% scaling
100% scaling
200% scaling
- Checked `FormRebase` and `FormMerge` manually at 100% 150% and 200% scaling
200% scaling
200% scaling
- Windows 11
- 100% 150% and 200% scaling
I agree that the maintainer squash …
> Fix FormRebase DPI issues

- GitUI/CommandsDialogs/FormCommit.cs
- Take Dpi scaling into account when adjusting `FormCommit` horizontal splitter position
https://github.com/gitextensions/gitextensions/assets/483659/19173dfc-9d30-40af-93f8-4b5022f0b627
Sorry, didn't record after, but the splitter doesn't move down with this fix.
- Manually with 200% scaling
- Windows 11
- 200% scaling
----
> Fix FormCommit "splitRight" moving down on each FormCommit open

- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/AvatarProvider.cs
- GitUI/Avatars/AvatarDownloader.cs
- GitUI/Avatars/AvatarMemoryCache.cs
- GitUI/Avatars/AvatarService.cs
- GitUI/Avatars/ChainedAvatarProvider.cs
- GitUI/Avatars/CustomAvatarProvider.UriTemplateResolver.cs
- GitUI/Avatars/CustomAvatarProvider.cs
- GitUI/Avatars/FileSystemAvatarCache.cs
- GitUI/Avatars/GithubAvatarProvider.cs
- GitUI/Avatars/GravatarProvider.cs
- GitUI/Avatars/HotSwapAvatarProvider.cs
- GitUI/Avatars/IAvatarProvider.cs
- GitUI/Avatars/InitialsAvatarProvider.cs
- GitUI/Avatars/SafetynetAvatarProvider.cs
- GitUI/Avatars/StaticImageAvatarProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/UserControls/AvatarControl.cs
- GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
- UnitTests/GitUI.Tests/Avatars/AvatarPersistentCacheTests.cs
- UnitTests/GitUI.Tests/Avatars/AvatarTestBase.cs
- UnitTests/GitUI.Tests/Avatars/InitialsAvatarGeneratorTests.cs
- Improve quick scrolling avatar display (that could block UI when the avatar was not in cache due to some potential exceptions raised)
- Don't draw temporary placeholder avatar (less things to do and no visual blink)
- Fix "Clear image cache feature" (and remove double call to clear)
- Cache avatars in %LocalAppData% instead of %AppData% (no roaming for cache data)
- Bypass filesystem cache for initial avatar provider that is quicker that reading cache from filesystem (and so no need to write a file)
- Manual
- Build 5b7092d88f31ec36a53c000796a8cf2ddb813ab7
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 6.0.26 [C:\Program …
```
> Improve avatar handling perfs

- GitUI/Theming/ThemeRepository.cs
Fixup `MigrateColorSettings` by creating the user-themes directory in `ThemeRepository.Save`
exception on every start
`MigrateColorSettings` successfully executed once and not called any longer
- manual
----
> Fixup migration of color settings

- GitCommands/Git/GitModule.cs
- GitUI/GitUIExtensions.cs
When combined diff or range-diff Git command fails, display the Git error message in the viewer, as for most other diff commands since #11535.
For combined diffs, "Uninteresting diff hunks are omitted." were no longer displayed.
Follow up to #11535, not fully handled.
"Uninteresting diff hunks" is a minor regression.
This is slightly refactored in #11590 , merge conflict and viewer has "combined" knowledge.
See tmp/git-coloring a53943ebed2e0263dd70a05d8eee0b7715a7a1b2
Empty viewer
Few merge commits in GE repo (good thing), an example from mstv's test branch that also have diffs with changes in 9da998f1439426a73034bc4ffed96dd691f0336b
manual
----
:black_nib: I contribute this code under [The Developer …
> Combined diff error presentation

- GitCommands/Git/GetAllChangedFilesOutputParser.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Patches/PatchManager.cs
- GitExtUtils/Delimiters.cs
- GitUI/Avatars/InitialsAvatarProvider.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormVerify.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/HelperDialogs/FormProcess.cs
- GitUI/LeftPanel/BaseRefTree.cs
- GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
- GitUI/UserControls/TextBoxSilencer.cs
- Plugins/CreateLocalBranches/CreateLocalBranchesForm.cs
- Plugins/CreateLocalBranches/GitExtensions.Plugins.CreateLocalBranches.csproj
- Plugins/FindLargeFiles/FindLargeFilesForm.cs
- Plugins/GitFlow/GitExtensions.Plugins.GitFlow.csproj
- Plugins/GitFlow/GitFlowForm.cs
- ResourceManager/LocalizationHelpers.cs
- No behavior change, just refactoring.
- Unit tests & manual
- GIT 
- Windows 
----
> refactor: clean usage of delimiters

- Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
- contributors.txt
Add support F# files to the statistics plugin
----
> Support F# files

- GitCommands/Remotes/AzureDevOpsRemoteParser.cs
- GitCommands/Remotes/GitHostingRemoteParser.cs
- GitCommands/Remotes/GitHubRemoteParser.cs
- GitCommands/Remotes/RemoteParser.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormRemotes.Designer.cs
- GitUI/CommandsDialogs/FormRemotes.cs
- Plugins/BuildServerIntegration/GitlabIntegration/Settings/GitlabRemoteParser.cs
- UnitTests/GitCommands.Tests/Remote/GitHostingRemoteParserTests.cs
Improve over https://github.com/gitextensions/gitextensions/pull/11559#discussion_r1474581069 and https://github.com/gitextensions/gitextensions/pull/11559#discussion_r1475190622
* A little more clever remote url completion (instead of relying on history of url remote that we know will **never** contains the desired url ): Use existing remotes to propose urls that has a lot higher probability to be suited.
* Do the opposite: extract remote name from URL if Url entered first.
Also:
* convert git hosting regex to compiled regex
* add a new more generic git hosting regex that cover more providers (but not Azure DevOps one 😞 because the format is different and I don't know how to parse it)
When entering the url field, nothing happens and opening the dropdown just give an history of remotes: …
> Add remote a little more smarter completion

- GitCommands/Git/GitModule.cs
- GitExtUtils/DisplayWithSuffixUpdater.cs
- GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/FormResolveConflicts.resx
- GitUI/Translation/English.xlf
- ResourceManager/Hotkey/KeysExtensions.cs
- UnitTests/GitExtUtils.Tests/DisplayWithSuffixUpdaterTests.cs
When conflicts during merge/rebase, it is not always easy to what is "local" or "remote" ( See [here](https://jvns.ca/blog/2023/11/01/confusing-git-terminology/#ours-and-theirs-while-merging-or-rebasing) and [here](https://nitaym.github.io/ourstheirs/) )
- Add also terms "current"/"incoming" (that I found a little more explicit) and that user could be used to see if merging with "vscode"
- Add more explicit help as tooltips
* Merge:
* Rebase:
* Merge:
* Rebase:
- Manual
- Build 199b9935fa10cea107ffcff6d2d14c54d85cc2f4
- .NET 8.0.1
I agree that the maintainer **rebase** merge this PR (if the commit message is clear).
----
:black_nib: I contribute this code under …
> FormResolveConflicts: Improve help when merging/rebasing

- GitCommands/Git/GitModule.cs
Fixes #11627
- Call OpenWithDifftool with properly named arguments
in order to avoid passing `firstRevision` as `oldName` 
N/A
- manual
----
> Fixup dir-diff

- GitUI/LeftPanel/Node.cs
- GitUI/LeftPanel/RepoObjectsTree.cs
- GitUI/UserControls/NativeTreeView.cs
- Turn on `DoubleBuffered` in the `NativeTreeView` constructor to mitigate tree flicker during update
_I've also fixed some nullability and warnings/style issues around the code that I've explored while fixing this_
Video is slowed down 3x, notice how the repo objects tree is flickering when different commits are selected
https://github.com/gitextensions/gitextensions/assets/483659/166d33d2-d219-43b5-b7bb-76b2c38d155c
https://github.com/gitextensions/gitextensions/assets/483659/44f56a43-5731-4e7e-9863-5b9c23633394
- Manually over several months of GE usage
- Windows 11
- 200% Dpi
----
> Turn on DoubleBuffered mode for the NativeTreeView control to prevent flickering

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- Splitters in `FormCommit` are restored after layout is already done causing quite some visible re-drawing
- Since all controls are ready early in the layout cycle, restore splitters before performing initial form layout
- Remove the **splitter-drift** hack as it became unnecessary and the tests caught that! (haven't looked at who wrote these tests, but my hat is off to you! 🙇)
Notice the unstaged/staged controls getting resized during the loading of the form (video is slowed down 3x)
https://github.com/gitextensions/gitextensions/assets/483659/245e63e7-7eb3-479e-8f81-0579fc87ae4b
https://github.com/gitextensions/gitextensions/assets/483659/b069b8d5-da8c-4d4c-991d-a93b5c869745
- Manually for several days
- Windows 11
- DPI 200%
I agree that the maintainer squash merge this PR (if the …
> Restore splitter positions early in the layout process for FormCommit

- GitUI/GitUI.csproj
- Enable `ForceDesignerDpiUnaware` for the `GitUI` project to prevents sizes getting recalculated based on how many pixels controls take when viewed with non-100% Dpi
The link from the informational "gold bar" in VS leads to: https://aka.ms/winforms/designer/unaware-mode which is a redirect to https://github.com/dotnet/winforms/blob/main/docs/designer/designer-high-dpi-mode.md
Prevents this upon save:
- Manually
- Windows 11 200% Dpi
- Visual Studio 2022
----
> Set ForceDesignerDpiUnaware prop for the GitUI project

- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/ToolStripPushButton.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- ResourceManager/GitExtensionsControl.cs
- ResourceManager/Hotkey/KeysExtensions.cs
- ResourceManager/Hotkey/ShortcutHelper.cs
Follow-up to #11620
- Display shortcuts in tooltips of FileViewer toolbar
- Fixup xmldoc of `ShortcutHelper`
- Change default hotkey for `ShowGitWordColoring` to `Ctrl+D`
- less modifiers
- works from FileStatusList
- similar to "Show entire file (Ctrl+E)"
- Remove pointless call to `DiffFiles.ProcessHotkey` because FileStatusList does not support hotkeys at all
- Add `GitExtensionsControl.GetShortcutKeyDisplayString`
- Replace `KeysExtensions.UpdateTooltipWithShortcut` with direct call of `DisplayWithSuffixUpdater.UpdateSuffix`
- manual
----
> Improve hotkey display and handling

- GitCommands/Settings/AppSettings.cs
- Plugins/GitUIPluginInterfaces/SettingsSource.cs
- UnitTests/GitUI.Tests/Theming/AppColorDefaultsTests.cs
- contributors.txt
Fixes #11629
There is a problem in SettingsSource.GetColor. If the settings do not contain a value for the requested color, GetColor will return Color.Empty rather than the provided default color (because of how ColorTranslator.FromHtml handles empty input).
This causes the theme migration to think the colors have been updated from the default to a very goth all-black.
Fix SettingsSource.GetColor to return the default color instead of Color.Empty
- Added unit test for SettingsSource.GetColor
- Build 805cf4832e6e2ad5719c04bdc07607a87be4c7f5 (Dirty)
- .NET 8.0.3
----
:black_nib: I …
> Fix theme migration bug

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
Fixes https://ci.appveyor.com/project/gitextensions/gitextensions/builds/49461079#L339
- There is no need to invalidate RevisionGridControl
- Just be more patient until stashes are loaded
N/A
----
> Improve stability of show stashes test

- GitCommands/Patches/PatchProcessor.cs
- Plugins/GitUIPluginInterfaces/Patch.cs
- UnitTests/GitCommands.Tests/GitCommands.Tests.csproj
- UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.cs
- UnitTests/GitCommands.Tests/Patches/PatchTest.cs
- UnitTests/GitCommands.Tests/Patches/testdata/color-binary.diff
- UnitTests/GitCommands.Tests/Patches/testdata/color.diff
Fixes #11630
Add tests for escape sequences.
Add check for additional escape sequences in Debug builds, to monitor changes in Git.
Removed unused property IsCombinedDiff
Added tests
----
> Parse patch header with escape sequences

- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/Translation/English.xlf
fixes #11651
Introduced by 3a7e5d8bc16c2ba2f65eac3867e64ad89b9002e8 (#11619)
No changes for english version.
- Build and run
- Build 9c707d516b0fc5e42046550bba87cb0b2e49a1dd
- .NET 8.0.1
```
```
----
:black_nib: I contribute this code under [The Developer …
> FormResolveConflicts: Avoid fragmented translation strings

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormClone.Designer.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/FormVerify.cs
- GitUI/CommandsDialogs/Menus/ToolsToolStripMenuItem.Designer.cs
- GitUI/LeftPanel/BaseRevisionNode.cs
- GitUI/Plugin/GitPluginSettingsContainer.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/PatchGrid.cs
- Plugins/GitHub3/GitHub3Plugin.cs
(better reviewed commit by commit)
- FormResolveConflicts: don't reinit merge tools after each file conflict resolved
- FormClone: Add Browse icons
- Menus: Add missing '...' to menu entries that will open a popup
- perf(LeftPanel): cache forecolor used for invisible refs
- refactor(GitPluginSettingsContainer): simplify logic
- by putting the logic of backward compatibility when the container is created instead of every times a value is read
- perf(GitHub3Plugin): do less things
- instantiate GitHubRemoteParser only once (instead for each remote parsed)
- return an IEnumerable so that we could use a `.Any()` to stop earlier
- Hash column: remove ellipses
Browse icons added:
Example of "..." added:
Hash columns: Remove "..."  and reduce size (as user need room to display subject or diff, …
> Small refactoring or adjustments

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
accessible easily with `Ctrl+T` shortcut
Then first letter of keyword (like 'r' for 'refactor') allows quick selection
then followed by pressing ENTER key.
See https://www.conventionalcommits.org/
and some others useful git commit footers...
Contribute to #11662
Fixes #5903 (See https://github.com/gitextensions/gitextensions/issues/5903#issuecomment-1837623364 )
- Manual
- Build 9c00de36289e762d91125edea26c9fcc95b866e6 (Dirty)
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 7.0.15 [C:\Program …
```
> feat(FormCommit): Add Conventional Commit message support

- GitUI/HelperDialogs/FormResetAnotherBranch.cs
Fixes #11671
which is a regression in #11656
- Also ignore `Enter` in `Branches_KeyUp`
N/A
- manual
----
> fix(FormResetAnotherBranch): Do not open ComboBox drop down on Enter

- GitCommands/RevisionReader.cs
- GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.BackgroundUpdater.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Improvement over #11441
- RevisionGridControl: load revisions by batch (e.g. 1s gain over 2.5s when loading Git repo)
- RevisionReader: cache parent commit hash parsed (less memory usage: between 5 and 10MB on GE repo)
- RevisionGrid: Avoid looking at stash for each revision when possible (no stashes or all already displayed)
- RevisionDataGridView: cache resources and don't calculate same thing twice
- RevisionDataGridView: cache graphic resources between all the cells of the same row
- RevisionGrid): halve the number of short hash calculated on each display
no changes
- Manual
- GIT 
- Windows 
I agree that the maintainer **rebase** merge this PR (if the commit message is clear).
---- …
> Improve performance of revision grid

- GitUI/Editor/Diff/CombinedDiffHighlightService.cs
- GitUI/Editor/Diff/DiffHighlightService.cs
- GitUI/Editor/Diff/DiffLineNumAnalyzer.cs
- GitUI/Editor/Diff/DiffLineType.cs
- GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
- GitUI/Editor/Diff/GrepHighlightService.cs
- GitUI/Editor/Diff/ITextHighlightService.cs
- GitUI/Editor/Diff/PatchHighlightService.cs
- GitUI/Editor/Diff/RangeDiffHighlightService.cs
- GitUI/Editor/Diff/TextHighlightService.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- UnitTests/GitUI.Tests/Editor/Diff/DiffLineNumAnalyzerTests.cs
- UnitTests/GitUI.Tests/Editor/Diff/SampleGitWord.diff
- UnitTests/GitUI.Tests/Editor/FileViewerInternal.CurrentViewPositionCacheTests.cs
- UnitTests/GitUI.Tests/GitUI.Tests.csproj
Modification of #11628, approved but not yet merged.
First command is squash and rebase of the commit, not really to be reviewed
If this is approved, I plan to squash together wit the changes in #11628 as one commit.
Modification of the presentation in #11628 of GitWordDiff
- Show line number for removed, even if the info is unreliable
- Instead of the blueish line marker show removed line number (if changes detected) in red and new with green. Similar for when changes are only seen on one side, the other is then not colored. 
See #11628 also for the change in this PR
Tests are updated
----
> Display "mixed" diff as red/green

- GitUI/Editor/Diff/DiffHighlightService.cs
- GitUI/Editor/Diff/GrepHighlightService.cs
- GitUI/Editor/Diff/RangeDiffHighlightService.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/GitUIExtensions.cs
as well as range-diff and git-grep.
Use of Git coloring of command output was added in #11590. The patch view (default) is configurable, setting to keep the current GE coloring.
git word-diff requires Git coloring and is not enabled if not Git coloring is enabled.
This removes the GE coloring for some commands ans the GE coloring is very limited and is adding complexity.
* git-word-diff (#11590)
* git-grep (#11359)
* git-range-diff (very limited GE coloring).
It is possible that a user want to keep the GE color engine for patches but use it for these commands.
Related to #11673 (and is a merge conflict), ther is a rebased commit in tmp/git-coloring but I want this reviewed in parallel.
No changes in the default configuration,  the first image is for without GE coloring.
git word-diff, …
> Always use Git coloring for word-diff

- GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/DateColumnProvider.cs
- Enforce HashColumn max width to hash length
- Adjust DateColumn width to exact content when date is displayed in "absolute date" (because the length is constant)
* Before
* After (no more lost space)
* Before (column could take a lot too much width):
* After (column took only required width to display whole hash):
- Manual
- Build d0b8ca8a5c59d1086b7e19a38ca0b94ac25c0cd5
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 8.0.1 …
```
> feat(RevisionGrid): Column width adjustments

- GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs
- Scale HEAD ref's Arrow "padding"
- Manually at 100%, 150% and 200% scaling
- Windows 11
- 100%, 150% and 200% scaling
----
> Fix HEAD ref arrow scaling

- GitExtUtils/GitUI/ControlDpiExtensions.cs
- At the moment only the foreground image of the `PictureBox` is scaled but in some cases the image is set as background image and that has not been scaled up until now
(notice the tiny ℹ️ icon below the file list)
- Windows 11
- 100% and 200% scaling
----
> Scale PictureBox background images

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- Fix button scaling
- Manually with 100% and 200% scaling
- Windows 11
- 100% and 200% scaling
----
> Fix "Modify the commit message" button Dpi scaling

- GitUI/CommandsDialogs/FormClone.Designer.cs
- Set relevant `AutoSize` / `AutoScale` properties for form/controls to fix Dpi issues
- Adjust `groupBox1` size related props to make it look good in all DPIs
Notice how radio buttons are shifted down before resizing the form. Also... does anyone know why the heck the text is selected in the combo-boxes upon resize?
https://github.com/gitextensions/gitextensions/assets/483659/be7297fa-cf3d-43ac-bb7c-6dc0ebc242a3
- Manually at 100% 150% and 200% scaling
- Windows 11
- 100% 150% 200% Scaling
----
> Fix FormClone DPI issues

- GitUI/CommandsDialogs/FormDeleteRemoteBranch.Designer.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/BranchComboBox.Designer.cs
- GitUI/UserControls/BranchComboBox.cs
at the same time than a remote
Part of #11640 ( Following discussion)
When remote deleted successfully, local branch delete form opened automatically with good branch(es) selected:
- Manual
- Build fe059f5db67923fbb93efe2115223b97129e161d (Dirty)
- .NET 8.0.1
```
```
I agree that the maintainer squash merge this PR (if the commit …
> DeleteRemote: Add an option to delete a local tracking branch

- GitUI/UserControls/FileStatusList.cs
While looking into `FormCommit` slow load times I've come across this inefficiency. Not only is it calculated twice per form open but it's done on every form open!
- Initialize `ImageList` with relevant data once and store the result in a static field
- Manually. In debug mode I think it shaved off `~40ms` for the first open and `~80ms` for subsequent opens
- Windows 11
----
> perf(FileStatusList): Initialize ImageList data only once

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #11691
- Fix bool logic
- Manually
----
> Fix author highlighting background color

- GitExtensions.settings
- Provide revision link for the PR if the branch name starts with the PR number
e.g. created by `git fetch upstream pull/{UserInput}/head:{UserInput}`
no link
- manual
----
> GE internal revision links: Match PR starting with number

- GitUI/CommandsDialogs/FormRemotes.Designer.cs
- GitUI/CommandsDialogs/FormRemotes.resx
- Fix `FormRemotes` DPI scaling
- Adjust alignment/anchoring for more even layout
100% scaling
200% scaling (notice huge buttons)
100% scaling
200% scaling
- Windows 11
----
> Fix FormRemotes DPI scaling

- ResourceManager/Xliff/TranslationUtil.cs
- Suppress `Trace` output from `TranslationUtil` in release build
Though these traces might be a hint that something does not work properly. I think the number of such traces is not the same on every startup.
no output
- manual
----
> fix(TranslationUtil): Suppress Trace output

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
i.e there is no common ancestors.
"merge-base" command exit code is 1
which is not an error but more a "nothing found".
- Manual
- Build e8497aecf376488273c1ffc6293f9ac3b6318814
- .NET 8.0.1
```
```
---- …
> fix finding merge base when unrelated history

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Might fix #11700
- `RevisionDataGridView.Clear`: Cancel outdated update by `RevisionDataGridView.UpdateVisibleRowRangeInternalAsync`
N/A
- manual
----
> fix(RevisionDataGridView): Cancel outdated update

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphColumnTests.cs
- `RevisionGraphColumnProvider.PaintGraphCell`: Keep more lines in cache when scrolling forward
A different limit is needed for forward than for backward in order to not unnecessary throw away rendered lines.
N/A
- extended unit tests
----
> perf(graph): Keep more lines in cache when scrolling forward

- GitExtUtils/GitUI/PropertyGridExtensions.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.ScriptInfoProxy.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/Design/PropertySorter.cs
- GitUI/ScriptsEngine/ScriptInfo.cs
- In `Scripts` in addition to `Icon` property, add `IconPathName` in the property grid
- First, this will allow to pick any icon the user wishes for
- Second, this will allow picking high quality icons (built in ones are blurry)
- Change icon related property handling such that their values are reflected in the scripts list immediately on-value-change
- Fix DPI issues with script icons (see "before 200% scaling" screenshot)
- Default position of `PropertyGrid` is ridonculous. StackOverflow listed the only option of using reflection to read into internal control and adjusting its splitter position.. not pretty but no downsides even if underling API changes **and** it looks much better.
100% scaling
200% scaling
100% scaling
200% scaling
- Manually by adding empty paths, incorrect paths, …
> Allow selecting custom icons for user defined scripts

- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/HelperDialogs/FormChooseCommit.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
so that choice is not overwhelming
and user has less data to process to find commit he wants
All the git history is displayed and user has to search for the commit to select:
Only the commit that could be rebased are displayed and it's easier for user to find the good low bound one of commits to rebase:
- Manual
- Build 754b034fbe97b7e7973e5b43bfed7fc87cff1a3e
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 8.0.1 [C:\Program …
```
> FormChooseCommit & Rebase onto: Display only potential commits

- GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- GitUI/Editor/Diff/DiffHighlightService.cs
Tweak to #11674
git-diff detects moved blocks (with at least 20 chars) and colors adjacent blocks with alternate colors.
The alternative color profile will use dimmed colors for lines that are moved without changes so changed lines stand out better.
Border lines close to changes are marked (not always done by Git though...)
A better description: https://stackoverflow.com/questions/57817642/whats-the-purpose-of-dimmed-zebra
This PR changes to use dimmed-zebra instead (zebra is git default).
A bonus is that the GE colors are hard to see in the terminal. (such theme colors are hard to tune)
After feedback, colors are changed to be dimmed colors for moved and normal colors (but not reverse video) for border lines.
Need to be updated in the GE doc PR too.
block1 and block2 should have …
> Diff moved lines: Use dimmed-zebra algorithm

- GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/Translation/English.xlf
Update labels to be clear that:
- a remote **can't** be checked out and that the commit will be checked out in fact (and user will be end up in 'detached head' state).
- local branch will be given the *same* branch name
- Manual
- Build 453280d62575f353cd5d6b2d30a5e9cc08a21f2e
- .NET 8.0.1
```
```
I agree that the maintainer squash …
> Checkout *remote* branch: more helpful labels

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Just invalidate `_gridView` on author highlight instead of refreshing the entire `RevisionGridControl`
- Always explicitly refresh the `RevisionGridControl` in `OnRevisionReadCompleted` in order to apply settings and column widths
- Trigger graph update from `RevisionDataGridView.SetRowCount`
which fixes the regression from the improved author highlighting
N/A
- manual
----
> Refresh less on author highlighting

- GitCommands/Git/GitModule.cs
Fixes #11730
The superproject workingdir is occasionally null at least for WSL when restoring minimized windows and the command to add branches for the super project in the submodule cannot run.
No GUI change, just example of the superproject info
Manual
----
> fix(revgrid): SuperprojectModule has no workingdir

- GitCommands/RevisionReader.cs
Fixes #11732
Reviewed the code paths calling this and reverting the quoting added in #11570
Also make sure artificial commits are not cached
Manual
----
> fix(RevisionReader): do not quote GetRevision() hash

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.BackgroundUpdater.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- `RevisionDataGridView`: (Asynchronously) update `RowCount` also if `DisplayedRowCount` returns 0 yet
- `BackgroundUpdater`: Always cool down after performing the `_operation`
revision grid may stay empty until "Loading" is hidden
`RowCount` is updated every 300 milliseconds
- manual
----
> fix(RevisionDataGridView): Update RowCount while loading

- GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/Rendering/GraphCache.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphColumnTests.cs
Fixes #11700
Have clear chains of revision grid updates (one for graph loading affecting RowCount, one for visible row range).
Get rid of several workarounds and of the mix-up of revision loading and graph-only operations.
Avoid unnecessary blocking the UI thread.
- Do not render the graph in the UI thread but in a background task with double buffering
in order to avoid calling the potentially expensive `RevisionGraphRow.BuildSegmentLanes` from the UI thread
- Remove `RevisionDataGridView.UpdateGraphAsync`, just call `RevisionGraph.CacheTo` once with cancellation
because `CacheTo` is needed for graph rendering only
- Remove `UpdateVisibleRowRange` call on unhandled `OnCellPainting`
because there no need to for this additional trigger of graph update
- `RevisionDataGridView`: Remove …
> Render revision graph in the background

- GitUI/UserControls/FileStatusList.cs
when opening "FormLog"
even if it was set as not visible.
Fixes #11679
Reproduce step: double click on a revision in the revision grid
Regression introduced by f8c035302bba1351d88b5159e5ec93bfbbc5933d
/!\ Technical reason of the bug:
Previous code was:
FilterComboBox.Visible = filesPresent || (SearchComboBox.Visible && !string.IsNullOrEmpty(SearchComboBox.Text));
NoFiles.Visible = !FilterComboBox.Visible;
But as `FilterComboBox.Visible` is not just a property storing the value directly to a backed field
(it has a complex WinFoms internal logic),
the value retrieved by the getter ( to after set `NoFiles.Visible`) is sometimes wrong and not the one set to the property :(
The value is not "well" set due to complex internal logic and so a wrong value is used after.
Using a temporary variable …
> fix: label "No changes" no more hiding first file of the list

- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
- GitUI/CommandsDialogs/BrowseDialog/ReleaseType.cs
- GitUI/CommandsDialogs/BrowseDialog/ReleaseVersion.cs
Fixes #11742
- Open GitHub release page for portable apps instead of downloading msi
- Convert FormUpdates to use GitExtensionsDialog
* Installed
* Portable
----
> Open GitHub release page for portable apps instead of downloading msi

- GitCommands/Git/SubmoduleHelpers.cs
- GitCommands/Patches/PatchProcessor.cs
- UnitTests/GitCommands.Tests/Git/SubmoduleHelpersTest.cs
- UnitTests/GitCommands.Tests/GitCommands.Tests.csproj
- UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.cs
- UnitTests/GitCommands.Tests/Patches/testdata/color-prefix.diff
i.e. `diff.srcPrefix` and `diff.dstPrefix` settings introduced with git v2.45 https://git-scm.com/docs/git-diff/2.45.0#Documentation/git-diff.txt---default-prefix
Only (remaining) constraint is that the prefix end with '/' and doesn't contain a space.
Allowing something like (for terminals supporting hyperlinking to paths):
git config --global diff.srcPrefix "before:./"
git config --global diff.dstPrefix "after:./"
https://github.blog/2024-04-29-highlights-from-git-2-45/
No error diff displayed:
- Manual
- Build 9dd1ea113a519b0c40036d35f66c4d2f01b26423
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 6.0.26 [C:\Program …
```
> fix(diff): Don't fail if user customized git `diff.*Prefix` settings

- GitExtUtils/GitUI/Theming/AppColorDefaults.cs
- GitUI/Themes/invariant.css
* Selected revision (blue) => Same author (**light** blue)
* Selected text (mauve) => Same text (**light** mauve)
Note: I know that colors is a sensible subject and that everyone has it's own tastes but I hope I will not open the pandora's box.
I personally prefer not seeing the kind of yellow.
- Manual
- Build dd7687981074b2c7cad97c5e2cfeb41dc5811749
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 8.0.1 [C:\Program …
```
> More meaningful and (I hope) pleasant default colors

- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
Only show the script separator if there are items
diff tab context menu
manual
----
> fix(diff): Script separator only if items

- src/app/GitUI/Translation/English.Plugins.xlf
- src/plugins/Github3/GitHub3Plugin.cs
- src/plugins/Github3/GitHubHostedRemote.cs
- src/plugins/Github3/GitHubRepo.cs
no git issue menu item
Need to be enabled:
Issue template from GitHub assigned issues:
- Manual
- Build a32c590c1f00a2e918f68d0fe5b70d86bc54db48
- .NET 8.0.1
```
```
---- …
> feat(GitHub): Add commit message issue helper feature

- src/app/GitUI/Editor/FileViewer.cs
Always set the option to handle compatibility.
https://github.com/Wilfred/difftastic/releases/tag/0.58.0
manual
----
> fix(difftastic): default for --strip-cr changed in 0.58

- src/app/GitCommands/RevisionReader.cs
Fixes #11710
- RevisionReader: Load commit body in dependency on commit date instead of on author date
- manual
----
> fix(RevisionReader): Load body in dependency on commit date

- src/app/GitCommands/CommitDataManager.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/RevisionReader.cs
- tests/app/UnitTests/GitCommands.Tests/RevisionReaderTests.cs
Fixes NRE after calling `RevisionReader.GetRevision`
- Indicate that `RevisionReader.GetRevision` can return `null` and handle it
optionally by throwing an `ExternalOperationException`
N/A
- additional testcases
----
> Handle `RevisionReader.GetRevision` returning `null`

- src/app/GitUI/CommandsDialogs/FormVerify.Designer.cs
- src/app/GitUI/CommandsDialogs/FormVerify.LostObject.cs
- src/app/GitUI/CommandsDialogs/FormVerify.cs
- src/app/GitUI/HelperDialogs/FormEdit.cs
- src/app/GitUI/Translation/English.xlf
* display type of data for blob in grid
* perf: fetch ** dangling commit** metadata by batch (for my GE repo, for 1074 commits: 0.8s instead of 41.5s / only the long `git fsck` command --25s-- is now taking time. Overall: 1m5s before/ 25s after )
* syntax highlighting also when opening in popup viewer
* contextual shortcut are directly accessible (no need to open contextual menu first) & Ctrl-S added
* support more file types & magic numbers
* perf: don't do GUI costly processing twice
- Manual
- Build 3c8dd1972d260d7b0bcb613805a83e3988f96a87 (Dirty)
- .NET 8.0.1
I agree that the maintainer **rebase** merge this PR (if the commit message is clear).
---- …
> Improve recovery form

- src/app/GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes https://github.com/gitextensions/gitextensions/discussions/11441#discussioncomment-7921050
- `RevisionDataGridView`: Remove double invalidate from `CacheTo`
- `RevisionGraph`: Save masses of pointer copies by switching to a permanent instance of `List<RevisionGraphRow>`
`ImmutableArray` is not needed any longer as the `_orderedRowCache` is built and accessed from the same exclusive background task.
`_orderedRowCache = localOrderedRowCache.ToImmutable();` is very expensive and seems to even block the UI thread although executed in a background task. 
N/A
- manual (scroll down the Linux repo)
----
> Fixup hangs moving the RevisionGrid

- src/app/GitUI/NBugReports/BugReportInvoker.cs
Fixes #11767
- `ReportDubiousOwnership`: Replace single quotes with double quotes in proposed git command
see issue
- manual
----
> fix(ReportDubiousOwnership): Replace single quotes

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
Fixes #11774
- `AnsiEscapeUtilities.ParseEscape`: Limit error tracing
you don't want to see it
```
New start marker without end for grep (270, 308) in:
diff --git a/UnitTests/GitCommands.Tests/Patches/testdata/color.diff b/UnitTests/GitCommands.Tests/Patches/testdata/color.diff
new file mode 100644
index 000000000..0bfb32613
--- /dev/null
+++ b/UnitTests/GitCommands.Tests/Patches/testdata/color.diff
[36m@@ -0,0 +1,325 @@[m
[38;2;0;0;0;48;2;200;255;200m+[1mdiff --git a/GitCommands/Patches/PatchProcessor.cs b/GitCommands/Patches/PatchProcessor.cs[m[m
[38;2;0;0;0;48;2;200;255;200m+[1mindex 70b40..c1e6c 100644[m[m
[38;2;0;0;0;48;2;200;255;200m+[1m--- a/GitCommands/Patches/PatchProcessor.cs[m[m
[38;2;0;0;0;48;2;200;255;200m+[1m+++ b/GitCommands/Patches/PatchProcessor.cs[m[m …
```
> fix(AnsiEscapeUtilities): Limit error tracing

- src/app/GitUI/CommandsDialogs/FormVerify.Designer.cs
- src/app/GitUI/CommandsDialogs/FormVerify.resx
- src/app/GitUI/Translation/English.xlf
- Improve the 2 top labels
- Add 2 explaining tooltips
- Manual 
- Build c5d13dbac57836b91cbf65681f14bc7cab306eb1
- .NET 8.0.5
```
Microsoft.WindowsDesktop.App 6.0.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.19 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
:black_nib: I …
> FormVerify: Provide more help to user

- src/app/GitCommands/GitCommands.csproj
- src/app/GitCommands/RevisionReader.cs
Fixes https://github.com/gitextensions/gitextensions/pull/11621#discussion_r1532965374
- fix(RevisionReader): Update after at most 500 ms
- fix(RevisionReader): Define `TRACE_REVISIONREADER` for debug build only
- manual
----
> RevisionReader: Update after at most 500 ms

- src/app/GitCommands/Settings/FileSettingsCache.cs
- tests/app/UnitTests/GitCommands.Tests/Settings/FileSettingsCacheTests.cs
Fixes #11720
Cleanup `FileSettingsCache`:
- Always watch the settings file also if the checkout does not contain that file on startup (repo open) 
- Hence remove `_canEnableFileWatcher`
- React on deletion, too
- There is no need to distinguish the kind of file change because we just need to know whether to refresh the settings or not
- Use `FileChanged` instead of assigning `_lastFileModificationDate`
N/A
- manual
- Remove obsolete testcase `ctor_CanEnableFileWatcher_should_be_false_if_invalid_dir` which is redundant with the existing
`ctor_FileWatcher_EnableRaisingEvents_should_be_false_if_invalid_dir`
---- …
> fix(FileSettingsCache): Always watch repo-local settings

- src/app/GitCommands/Settings/AppSettings.cs
in preparation of upcoming release:
- Move `RenderGraphWithDiagonals` and `StraightenGraphDiagonals` to non-experimental settings
N/A
----
> Make graph settings non-experimental

- src/app/GitUI/CommandsDialogs/FormAddFiles.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/ShellExtension/ShellExtensionManager.cs
- src/app/GitUI/GitUICommands.cs
- src/native/GitExtensionsShellEx/GitExtensionsShellEx.cpp
- src/native/GitExtensionsShellEx/GitExtensionsShellEx.h
Fixes #11711
- fix(ShellEx): Support adding multiple files
- fix(ShellEx): Write `InstallDir` to registry on registration of the shell extension
- fix(ShellEx): Open GE with current dir as work dir
N/A
- manual
----
> fix(ShellEx): Support adding multiple files

- src/app/GitUI/SpellChecker/EditNetSpell.Designer.cs
- src/app/GitUI/UserControls/TextBoxSilencer.cs
Fixes #11784
and further regression from #10730
- `EditNetSpell`:
- disable `RichTextBox.WordWrap` in order to avoid issues with cursor position calculation (not made public by `RichTextBox`)
- `TextBoxSilencer`:
- do not suppress keypress if there is a selection
- evaluate position on `KeyDown` not on `SelectionChanged`
because `RichTextBox.Text` can be empty yet on `SelectionChanged` and the selection does not change on setting `Text`
N/A
- manual
- GIT 
- Windows 
----
> FormCommit: Fixup cursor movement in message editor

- contributors.txt
- src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
Fixes #11741
- treat `difftool.<tool>.path` as (absolute) executable path (see [difftool doc](https://git-scm.com/docs/git-difftool#Documentation/git-difftool.txt---toollttoolgt))
- add last resort fallback to avoid empty string as command path
- Verify the _empty path_ mentioned in #11741 is now set correctly
- GIT 2.45.2.windows.1
- Windows 10.0.19045.4529
----
:black_nib: I contribute this code under [The Developer Certificate of Origin](/gitextensions/gitextensions/blob/master/contributors.txt).
> fix(DiffMergeTools): path for diff/merge command

- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitCommands/UserRepositoryHistory/RecentRepoInfo.cs
- src/app/GitCommands/UserRepositoryHistory/Repository.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.cs
- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/Translation/English.xlf
- tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- tests/app/UnitTests/GitCommands.Tests/UserRepositoryHistory/RecentRepoSplitterTests.cs
- tests/app/UnitTests/GitCommands.Tests/UserRepositoryHistory/RepositoryStorageTests.cs
- tests/app/UnitTests/GitCommands.Tests/UserRepositoryHistory/RepositoryXmlSerialiserTests.cs
between "Top", "Recent" and "Anchored" repositories
Also:
* inverted the 2 top settings to be in the same order than list it is referring to.
* used similar label as 2 settings are referring the the same behavior for top and recent lists..
Discussed [here](https://github.com/gitextensions/gitextensions/pull/11779#issuecomment-2164942593)
- Manual
- GIT 
- Windows 
----
> RecentReposSettings: Streamline naming

- Directory.Build.props
- setup/installer/Product.wxs
- src/app/GitExtensions/Project.Publish.targets
- src/native/build.proj
Add new `TargetPlatform` property, to control the specific platform for the GE installer (.msi) package.
Currently the GE installer package is hard-coded to be built for the `x86` platform, with `C:\Program Files (x86)` as the default installation folder.  This makes sense to install it on the `x86` (i.e. 32-bit) Windows platform, but a bit weird on `x64` (i.e. 64-bit) Windows platform (as discussed in #11554), and really feels weird when building an `Arm64-specific` installer package for Windows on Arm64 platform.
This commit defines a new `TargetPlatform` property which can take the following values: `x64` (default), `x86`, or `arm64` (must be lower-case values, as required by Wix). This property is passed on to the `Platform` parameter for WiX to create relevant installer package …
> Add TargetPlatform property

- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- src/app/GitUI/CommandsDialogs/ScriptOptionsProvider.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- src/app/GitUI/Translation/English.xlf
Relates to https://github.com/gitextensions/gitextensions/pull/11734#issuecomment-2119243843
- Turn script option `{SelectedFiles}` into `{SelectedRelativePaths}` without resolving full paths
in order to emphasize that these paths are valid for the selected commit (and might not apply to the working directory)
- Always replace the provided options `{SelectedRelativePaths}` and `{LineNumber}` if an according `ScriptOptionsProvider` exists - at least with an empty string
Otherwise, "{SelectedRelativePaths}" was passed as is to the script, which f.i. makes VS Code open a new file with the option as name.
E.g. in order to open a file in VS Code, the following background script command can be used (if the file has not been renamed or deleted; works best with VS Code setting …
> feat(ScriptOptionsProvider): {SelectedRelativePaths}

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- src/app/GitUI/GitModuleControl.cs
<details>
<summary>Previous PR description before it got "rebranded"</summary>
Once I've noticed this PR https://github.com/gitextensions/gitextensions/pull/11239 I wanted to use `{SelectedFiles}` in my script but it didn't work, I got literal value of `{SelectedFiles}` as a result.
Question: Is it a bug to leave `{SelectedFiles}` unreplaced into say an empty string?
- Since Toolbar Event Scripts go through `FormBrowse` when looking for a `IScriptOptionsProvider`, `FormBrowse` conveniently has two potential sources for it
- Override `GetScriptOptionsProvider()` in `FormBrowse` to forward this request to `RevisionDiffControl` or `RevisionFileTreeControl` depending on which one is visible
----
</details>
Currently scripts using `toolbar` event type do not have access to …
> Expose ScriptOptionsProvider to toolbar event scripts

- src/app/GitUI/CommandsDialogs/FormBrowse.Designer.cs
- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/CommandsDialogs/InvalidRepositoryRemover.cs
- src/app/GitUI/CommandsDialogs/Menus/StartToolStripMenuItem.cs
- src/app/GitUI/CommandsDialogs/Menus/ToolStripMenuItemEx.cs
- src/app/GitUI/CommandsDialogs/Menus/WorkingDirectoryToolStripSplitButton.cs
- src/app/GitUI/RepositoryCurrentBranchNameProvider.cs
- src/app/GitUI/RepositoryHistoryUIService.cs
- src/app/GitUI/ServiceContainerRegistry.cs
- src/app/GitUI/Translation/English.xlf
- tests/app/IntegrationTests/UI.IntegrationTests/GlobalServiceContainer.cs
- Extract the working directory / recent repositories dropdown as a standalone component
- Add "Close (go to Dashboard) to repos dropdown
----
> Add "Close (go to Dashboard) to repos dropdown

- src/app/GitUI/LeftPanel/BaseRevisionTree.cs
- src/app/GitUI/LeftPanel/Tree.cs
Fixes #11796 
UpdateVisibility() (started when the grid is loaded) must run after all objects in the sidepanel is loaded.
Previously there could be a race condition, especially when reloading with "current branch only" filter.
An alternative could be to use SlimSemaphore.
Did a quick check for similar uses as in RevisionGrid, TaskCompletionSource is used in Executable.
Manual
----
> fix(sidepanel): Await reload before updating visibility

- src/app/GitUI/UserControls/RevisionGrid/QuickSearchProvider.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Enable cancelling of Quick Search via `Esc` key
- Allow pasting text as Quick Search value
- ~~While Quick Search is active, enable moving through the results using `up` / `down` arrow keys~~
I've personally found that these changes have greatly improved Quick Search usability.
In here I show how pasting could be useful (works great with pasting `sha` too); how `Esc` terminates quick search and how movement through results via `up` / `down` works
https://github.com/gitextensions/gitextensions/assets/483659/2924d532-9eb8-4dab-8f36-686b69e0494c
- Manually
- Windows 11
----
> Improve Quick Search keyboard interaction

- src/app/GitExtensions.Extensibility/Git/IGitRef.cs
- src/app/GitUI/ScriptsEngine/ScriptOptionsParser.cs
- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/RevisionGrid/FormQuickGitRefSelector.cs
- src/app/GitUI/UserControls/RevisionGrid/FormQuickItemSelector.cs
- src/app/GitUI/UserControls/RevisionGrid/FormQuickStringSelector.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Sort refs in the following order: local/remote/tags. Then sort by local ref name within each group.
- Add group separators for ease management.
- manual
- GIT 
- Windows 
----
> Improve sorting in quick git ref selector dialog

- src/app/GitUI/Avatars/InitialsAvatarProvider.cs
- tests/app/UnitTests/GitUI.Tests/Avatars/InitialsAvatarGeneratorTests.cs
when generating the initials
where none of the email and name starts by a letter
and add better fallback to always return a not empty string
- unit tests (I don't remember the repository where I encounter this case to manual test the case)
- GIT 
- Windows 
----
> fix(avatars/initials): fix a special case causing an exception

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
(https://github.com/gitextensions/gitextensions/issues/11634#issuecomment-1995477095)
This affects git-word-diff output. (Ctrl-D in diffviewer) 
Suggested by @mstv , I had been testing this some time too. Not convinced it is better but maybe easier to understand
As it is now, as much as possible commonalities are chown, so changed suffixes are listed.
However, the current could also show slightly chopped up if some chars matched.
The first diff is better after this change, I prefer the second occurrence
Manual
----
> Change diff.wordRegex to match words

- src/app/GitCommands/Settings/AppSettings.cs
- tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Fixes #11819
Migrate editor settings if GE was installed in 'Program Files (x86)' before 4.3.
Only check and update global Git settings in Windows, the only set by GE.
Guess previous, migrate to current path (i.e. the first usage).
When running in debug, migration is not automatic as the debug path is probably not what should be used.
Manual
----
> fix: Migrate core.editor settings from GE x86 path

- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Keep the current linenumber when switching to a new commit in file tree, instead of always resetting to first line.
This is a regression from 9bbd08ff2985e46df1a30edc94f1dddb3ba9d247 in 4.2
(The change in that commit is otherwise OK. cc @pmiossec)
This is useful when viewing a file in the file tree (possibly filtered the revision grid), then selecting various commits.
manual
----
> fix(file tree): Do not force line first line when changing commit

- src/app/GitCommands/StringExtensions.cs
- src/app/GitUI/CommandsDialogs/ScriptOptionsProvider.cs
- src/app/GitUI/ScriptsEngine/IScriptOptionsProvider.cs
- src/app/GitUI/ScriptsEngine/ScriptOptionsParser.cs
- src/app/GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- tests/app/UnitTests/GitCommands.Tests/StringExtensionTests.cs
- tests/app/UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Fixes #11794
- fix(scripts): Do not quote `{SelectedRelativePaths}`
- fix(scripts): Support multiple values in `IScriptOptionsProvider`
each value quoted for `{{SelectedRelativePaths}}`
N/A
- extended test
----
> fix(scripts): Do not quote {SelectedRelativePaths}

- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/Editor/FileViewerInternal.cs
- src/app/GitUI/GitUIExtensions.cs
- tests/app/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormEditorTests.cs
- tests/app/UnitTests/GitUI.Tests/Editor/FileViewerInternal.CurrentViewPositionCacheTests.cs
Related to https://github.com/gitextensions/gitextensions/pull/11832#issuecomment-2278328551
Try to keep the linenumber in the fileviewer if the identification for the contents is the same (using the filename as identification).
Previously the line was restored if the number of lines were the same or if it was a diff and the first line matched.
Some situations where this did not work:
* Switch diffviewer to/from difftastic (as header differs)
* Select a new commit for a file in the file tree, where the number of lines differed in the other commit.
Tests updated
----
> fix: Keep linenumber when switching viewer

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- src/app/GitUI/Editor/Diff/GrepHighlightService.cs
- src/app/GitUI/GitUIExtensions.cs
The intention was to allow the user to override the git-grep color, this was not implemented.
Also allows for removal of a routine.
Note: SetIfUnsetInGit() is used in DiffHighlightService too, but it is not worth it to share the method.
Manual
----
> fix: Allow user to override git-grep color

- src/app/GitUI/HelperDialogs/FormProcess.cs
Fixes #11839
Use the hidden read-only setting WslGitPath also in FormPath ("popup" commands like push and fetch) as all other Git commands executed in WSL (a few commands in WSL uses Windows Git).
manual
----
> fix: WslGitPath in FormProcess

- src/app/GitUI/CommandsDialogs/FormCherryPick.Designer.cs
- src/app/GitUI/CommandsDialogs/FormCherryPick.cs
- src/app/GitUI/CommandsDialogs/FormCherryPick.resx
- src/app/GitUI/CommandsDialogs/FormRevertCommit.Designer.cs
- src/app/GitUI/CommandsDialogs/FormRevertCommit.cs
- src/app/GitUI/CommandsDialogs/FormRevertCommit.resx
- src/app/GitUI/Translation/English.xlf
- Convert `FormRevertCommit` to `GitExtensionsDialog`
- Fix its DPI in a process
- Add Abort button
- Align designer/form-sizing code with `FormCherryPick`
- Align forms `FormCherryPick` code with `FormRevertCommit`, they are very similar
- Designer file mainly had controls moved around
- `label2` got a proper field and got renamed to `lblAnotherRev`
- Code file had an improvement for how to calculate controls size (mainly because previous approach for some reason didn't work with `FormRevertCommit`)
`FormRevertCommit` 100% 1 parent
`FormRevertCommit` 200% 3 parents (notice column width and button size)
`FormRevertCommit` 100% 1 parent
`FormRevertCommit` 100% 2 parents
`FormRevertCommit` 100% 3 parents
`FormRevertCommit` 200% 1 parent
`FormRevertCommit` 200% 2 parents
`FormRevertCommit` …
> Fix FormRevertCommit dpi

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
`DiffHighlightService.MarkDifference`:
- search the end of the diff back to `beginOffset` including
- avoid accessing characters out of range, i.e. before `beginOffset`
- manual
----
> fix(DiffHighlightService): Skip unchanged char after pure addition/removal

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
Always use black as foreground colors for moved lines. GE may calculate the color to be white, this is a an override to avoid the low contrast without risking breaking other scenarios.
This can be seen in https://github.com/gitextensions/gitextensions/issues/11843#issue-2473084897
even if that issue is about something related.
I cannot reproduce, this is a good enough default configuration as theming is limited anyway.
(and colors can be overridden with git-config)
Note that colors set as "black brightyellow" instead of "black yellow bold" as that has a separate meaning - a separate PR will clarify.
white foreground is configured in debugger, cannot reproduce.
manual
----
:black_nib: I contribute this code …
> fix: Force black foreground colors for bold in moved diff

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/AnsiEscapeUtilitiesTest.Get8bitColor.cs
Related to #11847 
The handling of ANSI escape sequences was probably not completely correct (there is no clear spec...).
All direct attributes applies to all colors specified.
So git colors "black bold red" and "black bold red" are translated to the sequence "1, 30, 41" which will render the same as  "brightblack brightred" ("90, 101"), but "black brightred" ("30, 101") is different.
Attributes should not be "persistent" if a "bright" color is set explicitly.
The implementation is slightly simplified too.
In reality, the implementation would not be a major issue as attributes are not often used in combination like this.
Tests are mostly unchanged.
---- …
> fix: bold attributes applies to both fore/back

- src/app/GitCommands/Git/CommandCache.cs
- src/app/GitCommands/Git/Executable.cs
- src/app/GitCommands/Git/ExecutableExtensions.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/RevisionReader.cs
- src/app/GitExtensions.Extensibility/ExecutionResult.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitExtensions.Extensibility/IExecutable.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/GitUIExtensions.cs
- tests/CommonTestUtils/MockExecutable.cs
- tests/app/UnitTests/GitCommands.Tests/Git/ExecutableExtensionsTests.cs
- tests/app/UnitTests/GitCommands.Tests/Git/GitCommandCacheTest.cs
Depends on #11848 
Git cache uses the command as the cache key. However a sha could
theoretically be duplicated in repos, so the path is added.
(This means that multiple clones (like worktrees) are no longer cached.)
Clean escape sequences before storing in the cache to speed up
fetching information from the cache.
Clean escape is also added to the cache key.
Cache DiffTastic commands, add environment variables as cache keys.
--
There is no strong requirement to include this PR in 5.0, but it improves DiffTastic usage in reviews. I switch the different mode several times per file and the delay to open difftastic is annoying.
The cache tests are updated - only the format of what is changed that is changed. …
> feat: GitCache: Add current directory to key

- src/app/GitCommands/Settings/FileSettingsCache.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- src/app/GitUI/UserControls/RevisionGrid/IndexWatcher.cs
Fixes #11854
Add try-catch for FileSystemWatcher, as this can raise FileNotFoundException. This addresses exceptions with interactive rebase editor for the FileSettingsCache in WSL.
Manual use
----
> fix: try-catch for FileSystemWatcher

- src/app/GitCommands/Git/ExecutableExtensions.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitUI/Infrastructure/PuttyHelpers.cs
Fixes #11869 
Some methods intend to check the Git output, but the command always throws at exit.
throwOnErrorExit need to be configurable for these methods.
Quotes were additionally quouted too (done in QuoteNE())
This occurs for instance when checking the characters in a branch name and staging files.
Note that the command still echoes the branchname to the console.
While Git allows quotes in branch names, Windows does not (this is a file) allow quotes in the name.
Note: There are a few calls of RunCommand() that could be supressed in addition to those thatactually check the output, but I left it at the checked calls.
This cannot be be too commonly occurring as the throwOnErrorExit checks were added in 4.1 or 4.0.
NBug
Manual
I agree that the maintainer squash merge this PR (if the …
> fix: RunCommand() should not throw when exit is checked

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/AnsiEscapeUtilitiesTest.ParseEscape.cs
Git often emits a separate sequence for the first +/-, merge this with the reminder of the line.
This is a minor performance improvement (probably not possible to detect),
for big files number of textmarkers slow down.
Also set the terminal backcolor to SystemColors.Window if unset (instead of hardcoding to White).
Tests adjusted
----
> fix: merge adjacent textmarkers

- src/app/GitUI/ScriptsEngine/ScriptOptionsParser.cs
- src/app/GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- src/app/GitUI/ScriptsEngine/SimplePrompt.cs
- src/app/GitUI/ScriptsEngine/SimplePromptCreator.cs
- tests/app/UnitTests/GitUI.Tests/Script/ScriptsManagerScriptRunnerTests.cs
Fixes #11892
Handle unset script arguments which result in an NRE when a script is invoked (before the Settings dialog is opened - this sets all unset arguments to `""`).
- manual
- unit tests
- GIT 
- Windows 
----
> Fix NRE in scripts if `arguments` unset

- src/app/GitUI/Editor/Diff/DiffLineNumAnalyzer.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffLineNumAnalyzerTests.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/SampleGitWord.diff
Tune the heuristics to get word-diff line numbers. If the diff only had added or removed chars, only added/removed line numbers were presented.
There are still many situations where the Git output is incomplete, the line numbers will be incorrect still.
Comments added to the code, trying to explain the issues.
File to compare is in a private branch, did not find a good example in recent commits
with #11868 
see line 20
tests updated
----
> fix: LineNumber presentation for Git word-diff

- GitExtensions.sln
- src/plugins/FindLargeFiles/FindLargeFilesForm.cs
- src/plugins/FindLargeFiles/FindLargeFilesPlugin.cs
- src/plugins/FindLargeFiles/Properties/AssemblyInfo.cs
- tests/plugins/UnitTests/FindLargeFiles.Tests/FindLargeFiles.Tests.csproj
- tests/plugins/UnitTests/FindLargeFiles.Tests/FindLargeFilesFormTests.GenerateCommand_with_deletions_should_return_expected.verified.txt
- tests/plugins/UnitTests/FindLargeFiles.Tests/FindLargeFilesFormTests.GenerateCommand_without_deletions_should_return_expected.verified.txt
- tests/plugins/UnitTests/FindLargeFiles.Tests/FindLargeFilesFormTests.cs
- tests/plugins/UnitTests/FindLargeFiles.Tests/Properties/AssemblyInfo.cs
Fixes #11896
Fixes #11897
- manual
- unit tests
- GIT 
- Windows 
----
> Correctly escape paths

- Directory.Build.props
- contributors.txt
- src/app/GitExtensions/GitExtensions.csproj
https://github.com/gitextensions/gitextensions/issues/11574 @RussKie 
- Instead of suppressing warning globally for the repo, suppress it on the single package reference where its needed.  This lets GitExtensions still see warnings for other vulnerable packages.
- Restore before change - works
- Remove NoWarn - fails with NU1903
- Add NoWarn to package reference - works again
Windows, dotnet 9.0 preview 7 SDK
- Squash merge (maintainer to decide merge message, PR submitter should cleanup commits/messages at PR approval).
> Move NoWarn=NU1903 to the Wix PackageReference

- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/UserControls/FileStatusList.cs
Fixes #11909
1. There are used different ContextMenuStrips for files and for submodules.
The menu items are added on menu open - and automatically removed from the other menu.
When re-adding them, the separators must not be created anew (as it is done for `_openInVisualStudioSeparator`).
2. Set the visibility of `FormCommit.toolStripSeparatorScript` as in https://github.com/gitextensions/gitextensions/commit/844050a9fd4a5d3a93a4888a2f6e5d424d7e1ac0 (done for all usages of `AddUserScripts`).
see issue
no multiple separators
- manual
----
> FileStatusList: Reuse context menu separators

- src/app/GitUI/CommandsDialogs/FormCommit.cs
Fixes #11894
- FormCommit: Disable ResetSoft if the git command will not be applicable, i.e. if "HEAD~1" does not exist
exception (refer to issue)
- manual
----
> FormCommit: Disable ResetSoft if command not applicable

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
https://github.com/gitextensions/gitextensions/pull/11847#issuecomment-2346101789
Git before 2.26 do not support the bright attribute for colors. As a workaround reverse bold is set, which has occasionally derived white foreground colors.
This doeos not change the appearance, except for the situations that #11847 addressed. The workaround for #11847 would have to be done for all Git users with < 2.26
Note: Adding the version to IGitVersion would require a change of all plugins to change this. Even if this is done for 5.0.1 I rather change this at this single usage.
An alternative is to raise LastVersionWithoutKnownLimitations from 2.15 to 2.26, which is a little steep.
I have whish to support 2.25 as that is the version in Ubuntu 20.04, not very important though.
Manual, faking version
I …
> fix: support Git < 2.26 with bright colors

- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
* Check that the folder exists
* Check that it is set to the currently running instance GE install path
Make GE config more reliable. Related to https://github.com/gitextensions/gitextensions.vsix/issues/33#issuecomment-2348488930
- Manual
- Build 5ac26f6ed7cd0d8da2f8fe1f629f4de3b77948fb (Dirty)
- Git 2.45.0.windows.1 (recommended: 2.46.0 or later)
- .NET 8.0.8
```
Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.20 [C:\Program …
```
> feat(settings): deeper checks for GitExtensions install directory

- Directory.Packages.props
- src/app/GitExtensions/GitExtensions.csproj
No more need to ignore warning NU1903 raised by Wix package <= v3.14.0
(better fix for #11574 than ones done in #11575 and #11911 )
https://wixtoolset.org/news/2024/02/06/wix-v4.0.4-available/
Fixes #11574
- Build successful in AppVeyor
- GIT 
- Windows 
----
> chore: Update wix to v3.14.1 (security update)

- src/app/GitUI/Editor/Diff/DiffLineNumAnalyzer.cs
Part of #11831, that PR reports on the Git behavior to insert the information rather than the GE presentation.
I do not want to manipulate the git-diff output here, which is what is requested in #11831.
Git may insert "\ No newline at end of file" in the end lines of a diff, this was not presented as Header unless last line.
(This printout may appear before last line in addition to the last line.)
Incorrect line numbers and not extra gray background.
Note that all printouts with '\' as first chars could be handled this way, the first position is special (+/-/@ after the header).
See 1e1b946b65669c232db8eef55efb378d41a44b82
A test is added in an upcoming PR, some restructuring is done to tests and I prefer to wait on that. 
(PR awaits #11851 and #11862).
I agree that the maintainer squash …
> fix: Always present git inserted as Header

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/AnsiEscapeUtilitiesTest.ParseEscape.cs
Follow up to #11887 
Adds tests, refactor a little, slightly more performant and merges some more text markers.
This was discussed with #11843 but is not strictly needed (but simplifies that PR too).
Number of text markers affect performance, merge with previous text marker if the new is directly following or only separated by newline.
* do not color empty \r
git-diff tries to color \r also if diff.colorMovedWS=no This has no visible effect and is just polluting the markers.
No change, \r\n are never colored.
Tests are added.
----
> fix: Merge git-diff textmarkers separated by newlines

- src/app/GitUI/UserControls/FilterToolBar.cs
- src/app/GitUI/UserControls/RevisionGrid/FilterInfo.cs
Fixes #](https://github.com/gitextensions/gitextensions/issues/3165#issuecomment-2352794359)
Allow ranges in Branches quick search
With this, it possible to search branches with ^ .. ... in the search box
Previously only arguments starting with -- was excluded from git-rev-parse checks if it was not a known branch/tag so the arguments were not allowed.
The check that there is a valid reference for ^branch is there, no such check for branch2..branch1 though.
Manual
----
> fix: Allow ^and .. in manual branch filters

- contributors.txt
- src/plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Fixes #3871
Use `git branch -D` instead of `git branch -d` when explicitly deleting unmerged branches.
- Manual test to check if deleting unmerged branches works instead of return an error message from git.
- GIT 2.46.0
- Windows 10 Enterprise 22H2
----
> Use "-D" instead of "-d" when deleting unmerged branches

- src/app/GitExtUtils/GitUI/Theming/ColorHelper.cs
- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
- src/app/GitUI/Editor/Diff/LinesMatcher.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffHighlightServiceTests.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/LinesMatcherTests.cs
- Detect indented lines
- Then match by common words
- Reduce the highlight (from git) for identical parts of the line - instead of marking the different part
- Remove highlighting of filenames in the diff header because their background highlighting was removed in f201220e8b77f5ab218277f60fd3e008c1ee5041
- Some refactoring into functions
`FormRevertCommit.cs` in 6a9f3c01b1c988d5a01369a5f54020115022a5cf
- some additional tests
----
> Diff View: Match similar lines in changed blocks

- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.cs
- src/app/GitUI/UserControls/FileStatusList.cs
`AppSettings` can be changed by another instance.
`AppSettings` are automatically updated in all other instance but are not applied to most of the UI.
Thus, the visibility of the `cboFindInCommitFilesGitGrep` can become out of sync with the checked state of `Show 'Find in commit files using git-grep'` - both in the git-grep form and in the context menu.
So, set the checked state of `Show 'Find in commit files using git-grep'` to the actual visibility of `cboFindInCommitFilesGitGrep` instead of `AppSettings.ShowFindInCommitFilesGitGrep`.
- manual
----
> fix(show git-grep): Sync and use actual visibility

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
Align with updated GE colors in #11851 and use normal/dim instead of bold/normal.
GE uses dim-dim for unchanged, but the difftastic default normal is not exactly the same and need better visibility.
the "bleeding of green" is due to incorrect vwesion used to take screenshot...
Manual
----
> fix: Align difftastic colors

- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
Fixes #11683
`FormGoToCommit`:
- limit number of loaded branches and tags to 20.000 entries each
- assign `DisplayMember` first!
- activate `TextChanged` last
- cancel loading on `FormClosed`
N/A
- manual
- simulate lots of tags
----
> fix(FormGoToCommit): Improve performance

- src/app/GitExtUtils/FileUtility.cs
- src/app/GitUI/CommandsDialogs/FormEditor.cs
- src/app/GitUI/Editor/FileViewer.cs
Fixes #11934
A bigger issue than originally mentioned in #11934 is that currently TextEditor provided/used by GitExtensions actually corrupts files 😬
- ICSharpCode.TextEditor has a helper which attempts to auto-detect the encoding, lets use it
- Depends on https://github.com/gitextensions/ICSharpCode.TextEditor/pull/42 because of this line [`FilePreamble = reader.CurrentEncoding.GetPreamble();`](https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/Editor/FileViewer.cs#L793)
- For good measure, lets avoid creating `MemoryStream` when not necessary and we can write straight to `FileStream`
Switching between UTF8 file without BOM and with BOM
https://github.com/user-attachments/assets/b746f341-b702-427d-9514-2e83874c6d98
After save using `fileeditor` (`F4` from within …
> Fix FileViewer's encoding bug when showing unstaged files

- src/app/GitUI/Editor/Diff/AnsiEscapeUtilities.cs
- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/AnsiEscapeUtilitiesTest.ParseEscape.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/AnsiEscapeUtilitiesTest.TryGetColors.cs
Fixes #11940
An empty ansi terminal sequence must be handled as an explicit reset.
This could cause that foreground colors were applied when black was to be used.
Adjust overridden colors for range-diff.
contextBold should not be reverse bold and
newDimmed/oldDimmed should be reverse.
(There is a minimal difference bold/normal black, but this context is
not very interesting.)
Slightly different behavior in 5.0 and master
Use mstv's branches repro/rangediff2-a and repro/rangediff2-b
5.0
master
after
Tests are updated
----
> fix: Reset current ansi terminal color

- src/app/GitUI/NBugReports/BugReportInvoker.cs
Fixes #11958
- `ReportDubiousOwnership`: Support normal paths (containing spaces), too, by replacing the first single quote instead of searching for `"'%(prefix)"`
- manual
----
> fix(ReportDubiousOwnership): Support normal paths, too

- src/app/GitCommands/Git/Commands.Arguments.cs
- src/app/GitUI/CommandsDialogs/FormCommit.Designer.cs
- src/app/GitUI/CommandsDialogs/FormCommit.cs
- tests/app/UnitTests/GitCommands.Tests/Git/CommandsTests.cs
Fixes #11931
Commit dialogue "Do not sign commit" should explicitly not set GPG key.
The default is set to "Git default", using the git-config settings.
Adding the first option in the dropdown
tests updated
----
> fix: commit gpgSign Git defaults

- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs
Fixes #11939
GitConfigAdvancedSettingsPage:
- display git config without value or with non-boolean value as indeterminate 
- do not overwrite such settings
- manual
----
> fix(settings): Ignore non-boolean advanced git config settings

- src/app/GitCommands/Git/Commands.Arguments.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitUI/CommandsDialogs/FormRenameBranch.cs
- src/app/GitUI/Translation/English.xlf
- tests/app/UnitTests/GitCommands.Tests/Git/CommandsTests.cs
- tests/app/UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #10375
- FormRenameBranch: Run git interactively instead of manually dealing with git output and silent tracing of exceptions
- dialog remains open on error in order to be able to fixup the entered name
nothing but an entry in the Git Command Log:
- manual
- adapt testcase
----
> fix(FormRenameBranch): Run git interactively

- src/app/GitExtensions/Program.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Fixes #11964
- `GitStatusMonitor`: Let the `BugReportInvoker` handle dubious repo ownership, and trace other exceptions
- `Main`: Register exception handlers as early as possible
empty FormBrowse
dubious ownership popup
- manual
----
> fix: Handle dubious repo ownership, too, if detected by GitStatusMonitor

- src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageHeader.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs
and so that settings file can't be saved in a "not existing" local repository.
Check that repo is valid and provide the information when creating pages
Fixes #11907 (at least prevent one way to reproduce it)
- Manual (Opening settings from dashboard i.e. while no repo opened)
- GIT 
- Windows 
(Will be squashed before merging)
----
> fix: Restrict settings to "global" when not in a repository

- src/app/GitUI/Editor/Diff/CombinedDiffHighlightService.cs
- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
- src/app/GitUI/Editor/Diff/DifftasticHighlightService.cs
- src/app/GitUI/Editor/Diff/GrepHighlightService.cs
- src/app/GitUI/Editor/Diff/PatchHighlightService.cs
- src/app/GitUI/Editor/Diff/RangeDiffHighlightService.cs
- src/app/GitUI/Editor/FileViewerInternal.cs
Depends on #11947
Split in two commits for review:
- GE diff highlighting, if Git coloring is not used (Git colors were cached already) 
- Inline processing to find common parts
Before this processing was done every time a marker was changed in the diff viewer.
(before #11947 the complete text was parsed every time too)
Refactoring only, tests exists
----
> feat: Cache the diff highlighting

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffHighlightServiceTests.cs
- in case of `AppSettings.ReverseGitColoring` set to `false`, dim the text and keep the window background
- manual
----
> fix(in-line diff): Support non-reversed git coloring

- src/app/GitUI/CommandsDialogs/FormPush.cs
when branch name contains brackets.
fixes #11997 and #11970
- Manual
- Build 2b8f800a9d26f1ba95c49516e677b0a4e387b4a7
- Git 2.45.0.windows.1 (recommended: 2.46.0 or later)
- .NET 8.0.8
```
Microsoft.WindowsDesktop.App 6.0.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 6.0.33 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 8.0.8 [C:\Program …
```
> fix(Push): fix false positive detection of "detached head" state

- src/app/GitUI/UserControls/FileStatusList.cs
Fixes #10976
- Also set `listItem.Text` in addition to the `FileStatusItem` instance in order to provide accessibility information
N/A
- manual
----
> fix(FileStatusList): Set `Text` for accessibility

- src/app/GitUI/CommandsDialogs/FormDiff.cs
Fixes #11980
- fix(`FormDiff`): Separate `CancellationTokenSequence`s of `PopulateDiffFiles` and `ShowSelectedFileDiff`
necessary because `ShowSelectedFileDiff` is called twice before `PopulateDiffFiles` finishes
exception
works
- manual (compare commit e283787912ca8b0af82461f3d1eec50f3f680242 with working dir)
----
> fix(FormDiff): Avoid "A task was canceled."

- src/app/GitUI/CommandsDialogs/FormCommit.cs
Fixes #11903
- fix(FormCommit): Restore correct condition in `RestoreSelectedFiles`, which was stupidly broken in #11363
first file selected
selected file restored
- manual
----
> fix(FormCommit): Restore file selection

- src/app/GitUI/UserControls/FilterToolBar.cs
Fixes #11942
- fix(FilterToolBar): Correctly resize branch dropdown and restore filter text
- manual
----
> fix(FilterToolBar): Correctly resize branch dropdown

- src/app/GitCommands/Git/Commands.Arguments.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/UserControls/GitBlameParser.cs
- tests/app/UnitTests/GitCommands.Tests/Git/CommandsTests.cs
Fixes #12006
- Add argument `--no-ext-diff` to all 6 found `git diff` commands in order to suppress a possibly configured `diff.external` tool
N/A
- adapt existing tests
----
> fix(git diff): Suppress `diff.external`

- src/app/GitUI/GitUICommands.cs
Fixes #11886
- fix(FileHistory): Do not change the capitalization of filename passed on the command line
because the filename filter of "git log" is case-sensitive
rather keep the existing path, which has the correct capitalization if the File History is invoked by GE
- manual
----
> fix(File History): Do not change capitalization of filename

- src/app/GitCommands/FileHelper.cs
GE uses the Git built-in patterns in .gitattributes to detect if a file is binary in certain situations to prune detection. Sync the list to recent Git versions to add newer formats.
https://git-scm.com/docs/gitattributes#_defining_a_custom_hunk_header
Very minor change seen together with #12007 
Code review
----
> fix: Add missing defaults to git attributes parser

- src/app/GitUI/UserControls/FileStatusList.cs
Fixes #12026
Fixup FileStatusList:
- Skip unnecessary git-grep box visibility handling (which called `BeginInvoke` too early)
- Clear search string on hide of git-grep box
N/A
- manual
----
> fix(Diff View): Avoid exception on open

- src/app/GitUI/UserControls/FileStatusList.cs
- Make `cboFindInCommitFilesGitGrep` the active control when it is shown
- manual
----
> feat(FileStatusList): Focus git-grep box on show

- src/app/GitUI/UserControls/FileStatusList.Designer.cs
- src/app/GitUI/UserControls/FileStatusList.cs
FileStatusList: Add two examples of regex for excluding files
1. `"^(?!.*NotThisWord)"`: self-explanatory with easy-to-delete placeholder
2. `"^(?!.*\bg?tests?/)"`: common test folders, singular & plural, optional prefix 'g' (for a common C++ test framework)
- manual
----
> feat(FileStatusList): Add examples of negative file filter

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffHighlightServiceTests.MarkInlineGap.verified.txt
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffHighlightServiceTests.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/gaps.diff
To improve inline marking of not interesting parts
Inline differences dims text that are not changed (and add markers where text were removed/added on a line)
Before only consecutive removed followed by consecutive added lines were compared.
Note: This allows gaps in the lines, but still requires removed followed by added lines, so the following is not handled
To expand on this it could be possible to match all lines within a section, but it could be confusing if matches are too far apart.
Tests added
----
> feat: skip gaps in blocks for mark inline

- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
Fixes #12038
- DiffHighlightService: Apply highlighting to the first 2000 characters only
stack overflow
- manual
----
> fix(inline-diff): Limit highlight length

- src/plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs
- src/plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
- src/plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildDurationFormatter.cs
- Display Azure DevOps PRs builds result in commit built (pipeline is building a merge commit
and so it is a little more tricky to get the original hash of the commit built)
- Add support to open Pull Request page from contextual menu
- improve a little the tooltip (to have all the information on one line --and prepare display of multiple build result in the tooltip--)
- display also PR id and build name
* The result for the PR is not available
* Build result on the commit & Tooltip (with PR information)
* Open the PR
- Manual 
- Build 5a7e3d88ee69ac359c3dcba8160c607959f85c97 (Dirty)
- Git 2.45.0.windows.1 (recommended: 2.46.0 or later)
- .NET 8.0.8
- Microsoft.WindowsDesktop.App …
> feat(CI/ADO): Add support for pull requests

- src/app/GitCommands/Git/GitGpgController.cs
Fixes #12048
- `GitGpgController`: Ignore exit code from "git verify-tag"
(Git does not document exit codes of this command. And the output is handled to a certain degree. If it fails for other reasons, users need to consult the Git Command Log.)
- manual
----
> fix(GPG): Ignore exit code from verify-tag

- src/app/GitUI/GitUICommands.cs
- src/plugins/BuildServerIntegration/GitlabIntegration/Settings/GitlabSettingsUserControl.cs
- Replace `ThreadHelper.JoinableTaskFactory.RunAsync(...).FileAndForget()` with `ThreadHelper.FileAndForget(...)` 
N/A
----
> chore: Convert remaining post-fix `FileAndForget`

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/UserControls/FileStatusList.cs
- fix(FileStatusList): Extract function `GetFileStatusListTop` and consider all additional boxes
in order to fixup the position of "Loading data..." - particularly on empty (artificial) commits, the just shown empty ComBox could be covered by the ListView
- fix(FileStatusList): Expand group of selected item
otherwise the selection of a diff file is not visible because all diff groups are collapsed for git-grep
- fix(GetGrepFileAsync): Quote filename
in order to support files with spaces in their name
- fix(git-grep): Go to first match if showing the entire file
Not really applicable
- manual
----
> Fix(git-grep)

- src/app/GitCommands/Git/CommandCache.cs
- src/app/GitCommands/Logging/CommandLog.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.resx
- src/app/GitUI/Translation/English.xlf
- Hide git configuration arguments in cache tab, too
- Add context menu item for clearing the cache
- manual
----
> feat(Git Command Log): Improve display of command cache

- src/app/GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
- src/app/GitUI/Hotkey/HotkeySettingsManager.cs
- src/app/GitUI/ScriptsEngine/ScriptInfo.cs
- src/app/GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- src/app/GitUI/ScriptsEngine/ScriptsManager.cs
- tests/app/IntegrationTests/UI.IntegrationTests/ScriptEngine/ScriptRunnerTests.cs
- Remove mnemonic ampersand in script name except for tool bar and menus 
Before | After
-|-
- adapt tests
----
> fix(Scripts): Do not display mnemonic ampersand

- src/app/GitCommands/Git/ExecutableExtensions.cs
- src/app/GitCommands/Utils/JsonSerializer.cs
- src/app/GitUI/Editor/FileViewer.cs
Fixes https://github.com/gitextensions/gitextensions/pull/12072#discussion_r1861390651 in all other occurrences
- `MemoryStream`: Add missing `using` statement 
- Remove unnecessary stream copy from `FileViewer.CreateImage`
N/A
- manually (view `.ico` and `.png` file of GE repo in diff and as new file)
----
> chore(MemoryStream): Add missing `using` statement

- src/app/GitUI/NBugReports/BugReportInvoker.cs
- src/app/GitUI/TranslatedStrings.cs
- src/app/GitUI/Translation/English.xlf
Closes #12053
- Remove "Trust all repositories" button from `BugReportInvoker.ReportDubiousOwnership`
- manual
----
> chore(dubious ownership): Remove "Trust all repositories" button

- src/app/GitCommands/Git/Commands.Arguments.cs
- src/app/GitUI/HelperDialogs/FormResetAnotherBranch.Designer.cs
- src/app/GitUI/HelperDialogs/FormResetAnotherBranch.cs
- tests/app/UnitTests/GitCommands.Tests/Git/CommandsTests.cs
Fixes #12035
- FormResetAnotherBranch: Use quicker command "update-ref"
- Enable the `OK` button using a dry-run of the previous command "push" 
N/A
- add testcase
----
> perf(FormResetAnotherBranch): Use quicker command

- src/app/GitUI/BuildServerIntegration/BuildServerWatcher.cs
Read() from a stream could obtain fewer characters than requested, the number of chars read was never checked.
This is a warning with .net9 and a potential issue in current master.
With this change all bytes reported to be in the stream are read, which should be the case anyway.
ReadExactly () was added in .net7. (I considered using that when optimizing the read of revisions for 4.x (that was for .net6, just testing an update.) If Git reported number of bytes for a commit the handling was slower than the current handling that searches for \0 in the stream).
Alternatives to this change:
- Suppress the warning in .net9 
- Assign Read() to _ to ack that the value is not used (there will likely be an exception below instead)
- Return with error if no of bytes are not read.
code review - …
> fix: ReadExactly from stream

- src/app/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #11782
- If no selection can be restored, select the first shown real commit or the first row
- Set `CurrentCell` accordingly, which works wonders!
(after scrolling down and up again)
- manual 
----
> fix(RevisionDataGridView): Always select a revision

- src/app/GitCommands/AsyncLoader.cs
- src/app/GitCommands/Git/Executable.cs
- src/app/GitCommands/Git/ExecutableExtensions.cs
- src/app/GitCommands/Git/GitCommandRunner.cs
- src/app/GitCommands/Logging/CommandLog.cs
- src/app/GitCommands/RevisionReader.cs
- src/app/GitExtensions.Extensibility/Git/IGitCommandRunner.cs
- src/app/GitExtensions.Extensibility/IProcess.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- src/app/GitUI/NBugReports/BugReportInvoker.cs
- src/app/GitUI/UserControls/BlameControl.cs
- tests/CommonTestUtils/MockExecutable.cs
- tests/app/UnitTests/GitCommands.Tests/AsyncLoaderTests.cs
- tests/app/UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
- tests/app/UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
- feat(Git Command Log): Log `StandardError`, too, unless not redirected (initial draft by @gerhardol)
- fix(`ProcessWrapper`): Provide git error message (if any) instead of "External program returned non-zero exit code."
- fix(`ExecutableExtensions.ExecuteAsync`): Remove check for `DubiousOwnershipSecurityConfigString` because that error message is provided by `ProcessWrapper` now 
- fix(`AsyncLoader`): Do not swallow unhandled exceptions
- fix(`BlameControl`): Show git error message and avoid outdated tooltips
- manual
- adapt existing tests
----
> fix(ProcessWrapper): Provide git error message instead of "External program returned non-zero exit code."

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/Patches/PatchProcessor.cs
- tests/app/UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.CreatePatchFromString_Text_ChangeFile_filesContentEncoding=System.Text.ASCIIEncoding+ASCIIEncodingSealed.verified.json
- tests/app/UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.CreatePatchFromString_Text_ChangeFile_filesContentEncoding=System.Text.Latin1Encoding+Latin1EncodingSealed.verified.json
- tests/app/UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.CreatePatchFromString_Text_ChangeFile_filesContentEncoding=System.Text.UTF8Encoding+UTF8EncodingSealed.verified.json
- tests/app/UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.cs
- tests/app/UnitTests/GitCommands.Tests/Patches/testdata/color-prefix.diff
- tests/app/UnitTests/GitCommands.Tests/Patches/testdata/color.diff
Fixes #12066
- `PatchProcessor.StartOfContentsRegex`: Move `'-'` to first position inside `"[ -+@]"` in order to avoid special meaning in regex.
This made `CreatePatchFromString` choose the wrong encoding for removed line.
- manual
----
> fix(PatchProcessor): Fixup encoding for diff text

- src/app/GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
Fixes UX issue
mentioned in https://github.com/gitextensions/gitextensions/issues/10946#issuecomment-2483313002
- `FormBrowse`: Set `FallbackFollowedFile` of "Diff" and "File tree" only if not empty
in order to not loose the file context ("last clicked file")
N/A
- manual
----
> fix(FormBrowse): Keep file context on deactivation of filter

- src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
- src/app/GitCommands/StringExtensions.cs
- src/app/GitUI/CommandsDialogs/FormFileHistory.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- tests/app/UnitTests/GitCommands.Tests/StringExtensionTests.cs
- tests/app/UnitTests/GitUI.Tests/UserControls/RevisionGrid/RevisionFileNameTests.cs
Fixes
part of #12088
- `FormFileHistory` and `RevisionGridControl`: Correctly quote filename
- Factor out `DiffMergeToolConfigurationManager.UnquoteString` to `StringExtensions.RemoveQuotes`
N/A
- manual: check Git Command Log
- add & adapt testcases
----
> fix(File History): Correctly quote filename

- src/app/GitUI/CommandsDialogs/FormFileHistory.cs
- src/app/GitUI/Translation/English.xlf
Improves UX on #12088, which is basically a git issue
`FormFileHistory`:
- Hide tabs "Diff", "View" and "Blame" if Git cannot identify the file blob, e.g. because it was deleted, or was renamed in an not merged branch 
- Show an error message in the "Commit" tab title, i.e. in the place where the tabs disappear
- Remove unused `FormFileHistoryController` instance
- manual
----
> fix(File History): Indicate not identifiable file

- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/BlameControl.Designer.cs
- src/app/GitUI/UserControls/BlameControl.cs
Fixes #10946
`BlameControl`
- Remove restriction to availibility of the actual revision
- Use visible previous revision instead
context menu item disabled
context menu item enabled if there is shown a (virtual) parent
- manual
----
> fix(blame previous): Remove restriction to availibility of the actual revision

- src/app/GitCommands/Git/GitModule.cs
- tests/app/UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #11241
- Use `Trim` instead of skipping the last line (as suggested by @toesus)
- Remove pointless support for Mac line end (git does not use it) 
- adapt exisiting tests
----
> fix(GetTagMessage): Do not truncate last line

- src/app/GitCommands/Git/SubmoduleHelpers.cs
- tests/app/UnitTests/GitCommands.Tests/Git/SubmoduleHelpersTest.cs
- tests/app/UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.CreatePatchFromString_with_spaces.verified.json
- tests/app/UnitTests/GitCommands.Tests/Patches/PatchProcessorTest.cs
Fixes #11891
- Fixup `SubmoduleHelpers.DiffCommandRegex` to support spaces in folder names of super repo
- Add test for `CreatePatchFromString` which uses a similar regex (not changed because it has a more generic scope)
- extend tests
----
> fix(Submodules): Allow spaces in folder name

- src/app/GitUI/CommandsDialogs/FormCommit.Designer.cs
Fixes #12099
- Set `toolStripGpgKeyTextBox.MaxLength` to 40
- to be tested manually
----
> fix(GPG): Remove max length of key id

- src/app/GitUI/Editor/FindAndReplaceForm.cs
Fixes #12084
- `Editor/FindAndReplaceForm`: Adapt selection length on replace
N/A
- manual
----
> fix(Editor): Adapt selection length on replace

- src/app/GitCommands/Git/GitFileStreamGetter.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- src/app/GitUI/Editor/FileViewer.cs
Fixes #6146
Finishes #6189
- Detect LFS pointer files and apply the LFS smudge filter in this case - in order to always get the plain file contents 
- test repo: https://github.com/mstv/test_lfs
with LFS-pointer-like files
- created an invalid pointer file, which cannot be pushed to GH
----
> feat: Support saving LFS files

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/WindowsJumpListManager.cs
Fixes #3128
- Disable Windows Jump List buttons if GE shows a modal dialog or has no valid wdir
- Bring GE to front on click of Windows Jump List button
- manual
- Windows 10
----
> fix(Jump List Buttons): Deactivate on modal dialog

- src/app/GitUI/GitExtensionsForm.cs
- src/app/GitUI/WindowPositionManager.cs
- tests/app/UnitTests/GitUI.Tests/GitExtensionsFormTests.cs
- tests/app/UnitTests/GitUI.Tests/WindowPositionManagerTests.cs
Fixes #11589 for maximized FormCommit
`WindowPositionManager`:
- Add vertical heuristic analogue to existing horizontal heuristic
- Default to top left of first screen as fallback
N/A
- manual
- adapt existing tests
----
> fix(WindowPositionManager): Add vertical heuristic

- src/app/GitUI/UserControls/FileStatusList.cs
Avoids double update of git-grep if search text matches a history entry
`FileStatusList`:
- Temporarily remove `cboFindInCommitFilesGitGrep_SelectedIndexChanged` in `AddToSearchFilter`
- Declare `sender` nullable for all event handlers
N/A
- manual
----
> fix(git-grep): Do not update on AddToSearchFilter

- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/Editor/FindAndReplaceForm.cs
- src/app/GitUI/UserControls/FileStatusDiffCalculator.cs
- src/app/GitUI/UserControls/FileStatusList.cs
- tests/app/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs
- tests/app/UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs
Remove `SelectedIndex` API from `FileStatusList`
- Add `HasSelection`
- `SelectedGitItems` takes `IReadOnlyList`
- Replace `GetNextIndex` with `SelectNextItem`
- Use `SelectFirstVisibleItem`
unchanged
----
> refactor(`FileStatusList`): Remove `SelectedIndex` API

- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardTheme.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Use SystemColors.Window for dashboard background theme, to be consistent with the normal app.
Some renaming to clarify color usage
Prepare the dark theme to be consistent with the app. The dark colors are not using the blue colors of the default light theme but greyish colors.
The theme does not look better, but is consistent with the .net9 dark mode (that cannot be tweaked much).
Recent repo background and searchbox background swapped.
Alternative light theme with system colors as for the dark theme
Note that the second header cannot be changed in the darktheme in .net9 (unless ListView is replaced)
Visual
- Windows 11 24H2
---- …
> feat: SystemColors.Window in Dashboard theme

- src/app/GitUI/CommandsDialogs/FormCherryPick.Designer.cs
- src/app/GitUI/CommandsDialogs/FormCherryPick.cs
- src/app/GitUI/CommandsDialogs/FormRevertCommit.Designer.cs
- src/app/GitUI/CommandsDialogs/FormRevertCommit.cs
- src/app/GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.Designer.cs
- src/app/GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
ListView table columns did not expand to the size of the table. This expands the most reasonable column like name to the size of the table.
To find the forms where this occurred, I looked for NativeListView that seem to have more than one column by searching for AddRange(). There may be more (and one form was ignored).
Note: There is a similar issue in GitHub Fork&Clone, not getting it to work now and ignore it
Visual
----
> fix: expand last column to ListView size

- src/app/GitUI/UserControls/FileStatusList.cs
Fixes regression caused by #12033
`FileStatusList`:
- Avoid setting `ActiveControl` on startup which makes `RevisionGrid` (sic!) get focused on `AppActivate`
`FileStatusList` loses focus when switching to another app and back
`FileStatusList` is still focused
- manual
----
> fix(FileStatusList): Avoid focus confusion on AppActivate

- src/app/GitUI/UserControls/FileStatusList.cs
Fixes #12128
- `SelectPreviousVisibleItem` / `SelectNextVisibleItem` shall not loop around to last / first item, e.g. when using (`Alt`+) mouse wheel
N/A
- manual
----
> fix(FileStatusList): Do not loop around with wheel

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitUI/Editor/Diff/GrepHighlightService.cs
- src/app/GitUI/GitUIExtensions.cs
- Pass argument `--show-function` to `git grep` 
first commit with
```
git config --global color.grep.matchSelected "yellow reverse"
```
second commit
second commit with additional git config
```
git config --global color.grep.function "white reverse"
```
- manual
----
> feat(git-grep): Show function name of matches

- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitExtUtils/AsyncStreamReader.cs
- src/app/GitExtUtils/IStreamReader.cs
- src/app/GitExtUtils/StreamReaderFacade.cs
- src/app/GitUI/HelperDialogs/FormProcess.cs
- src/app/GitUI/HelperDialogs/FormStatus.Designer.cs
- src/app/GitUI/HelperDialogs/FormStatus.cs
- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/ConsoleEmulatorOutputControl.cs
- src/app/GitUI/UserControls/ConsoleOutputControl.cs
- src/app/GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
- src/app/GitUI/UserControls/PasswordInput.Designer.cs
- src/app/GitUI/UserControls/PasswordInput.cs
- src/app/GitUI/UserControls/PasswordInput.resx
- tests/app/UnitTests/GitExtUtils.Tests/ArrayExtensionsTests.cs
- tests/app/UnitTests/GitExtUtils.Tests/AsyncStreamReaderTests.cs
Extends and supersedes #11182
- feat(FormStatus): Add password text box
- as `UserControl`
- Automatically show input field
- Show in all `FormStatus`, not only in `FormRemoteProcess`
- Focus the new control
- Cleanup unnecessary `FreeThreaded`
- fix(EditboxBasedConsoleOutputControl):
- Use `MonospaceFont` and `SystemColors.Info`
- Less delays
- Unblock UI
- Workaround for hang in `WaitForExit`
- Fixup dispose
- Log "Process killed"
- feat(EditboxBasedConsoleOutputControl): Add `AsyncStreamReader` in order to display prompts, i.e. output which has not been terminated with a line end (yet)
Thus, there is no need for console window for SSH any longer.
- add unit test for `AsyncStreamReader` (would have been easier if `System.IO.StreamReader` implemented an `interface`)
- manual
---- …
> feat(EditboxBasedConsoleOutputControl): Improve UX and add [password] input field

- src/app/GitExtUtils/GitUI/Theming/ColorHelper.cs
https://github.com/gitextensions/gitextensions/pull/12125#discussion_r1903343778
The check for the default theme must use the theme name, as the theme is a separate instance.
Unneeded processing and potential issues like https://github.com/gitextensions/gitextensions/pull/12125#discussion_r1903343778
Manual
----
> fix(theme): Check for default theme

- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/LeftPanel/RepoObjectsTree.cs
- tests/app/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
Preparation for #12111 
Simplify review of the theme update.
This PR does not change behavior for the invariant theme.
There may be tweaks required to the theme handling in #12111 when that is actively reviewed, that review should be based on this (and similar) PRs.
Will likely be merged together with similar preparing PRs.
System colors are already adapted to the Windows theme and should not be transformed.
.net9 dark mode does not allow tweaking system colors even, but also the old solution should not have tweaked the system colors.
review
----
> fix(theme): Do not adapt system colors

- src/app/GitUI/CommandsDialogs/FormBrowse.Designer.cs
- src/app/GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- src/app/GitUI/CommandsDialogs/FormCommit.Designer.cs
- src/app/GitUI/CommandsDialogs/FormEditor.Designer.cs
- src/app/GitUI/CommandsDialogs/FormFileHistory.Designer.cs
- src/app/GitUI/CommandsDialogs/FormStash.Designer.cs
- src/app/GitUI/CommandsDialogs/Menus/WorkingDirectoryToolStripSplitButton.cs
- src/app/GitUI/CommandsDialogs/SearchWindow.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
- src/app/GitUI/Editor/FileViewer.Designer.cs
- src/app/GitUI/LeftPanel/RepoObjectsTree.Designer.cs
- src/app/GitUI/UserControls/FilterToolBar.Designer.cs
Preparation for https://github.com/gitextensions/gitextensions/pull/12111
See #12123 for motivation.
This PR removes use of hardcoded colors so it is feasible to manually review that #12125 is handled, reducong hits to `Color`
The default Color.Transparent is used in the GE icons. When set, it was mostly Color.Magenta and that is not used by GE icons as well the few other colors.
Review
----
> chore: Remove ImageTransparentColor

- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs
- src/app/GitUI/LeftPanel/RepoObjectsTree.cs
- src/app/GitUI/LeftPanel/Tree.cs
- src/app/GitUI/UserControls/TreeViewExtensions.cs
- chore(`TreeViewExtensions`): Remove namespace block
- chore(`TreeViewExtensions`): Alpha-sort methods
- refactor(`TreeView`): Extract `EnsureVerticallyVisible` and `ScrollLeftMost` from `LeftPanel.Tree.ExpandPathToSelectedNode`
- replace all occurrences of `TreeNode.EnsureVisible`
- manual
----
> TreeView: Revert horizontal scroll

- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs
- tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Some repos include submodules with additional subfolders
- "super/submodule1/repo"
- "super/submodule2/repo"
Currently, these submodules cannot be distinguished in GE's title bar.
Add a regex for skipping uninformative repo names "repo" and "repository".
- manual
----
> feat: Avoid just "app" / "repo" / "repository" in app title

- tests/app/UnitTests/GitCommands.Tests/ExecutableTests.cs
Several CI builds failed because the testcase execution on AppVeyor took more than 3 seconds.
Relax the regarding timer.
----
> test(ExecutableTests): Relax timeout for slow AppVeyor

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/FormExtensions.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Patch files can be dropped onto the RevisionGrid. But the app stays in the background.
Force the window to the front using a factored out extension method.
N/A
- manual
----
> feat: Bring to front on drag drop of patch file(s)

- src/app/GitCommands/Git/AheadBehindDataProvider.cs
Fixes #12005
- `AheadBehindDataProvider`: Restrict debug output to debug build and never to Output tab
(The case is properly handled. So, there is no need to bother users with this output.)
N/A
- manual
----
> fix(AheadBehindDataProvider): Restrict debug output

- src/app/GitUI/Editor/FileViewerInternal.cs
for files without explicit highlighting
Note: I may want to have a separate color for the linenumber display, but it should be adapted for theming.
This override (including the ICSharpCode change) is required for consistent handling, so that is a separate PR.
This looks very weird in dark mode.
but explicit strategies are OK
Visual
----
> fix: remove override highlight linenumber control

- src/app/GitCommands/AsyncLoader.cs
- src/app/GitUI/CommandsDialogs/FormFileHistory.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- src/app/GitUI/UserControls/BlameControl.cs
- src/app/GitUI/UserControls/FileStatusList.cs
Fixes
- very occasionally not loaded blame
- disappearing context menu item "Show differences for all parents in browse dialog"
- `BlameControl`: Do not cancel loading if nothing changed; combine cancellation tokens; use safe init values for `_lastTooltipX/Y`
- `AsyncLoader`: Make clearer & enable `nullable`
- `RevisionDiffControl`: Convert `IEnumerable` to array in order to avoid possible multiple evaluation
- `FileStatusList`: Avoid one-way menu item "Show differences for all parents in browse dialog"
menu item disappeared when unchecked
- manual
----
> fix: Improve blame loading and other minor

- src/app/GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- `GitStatusMonitor`: Deactivate if bare repo
- `RevisionGridControl`: Skip `GetStashes` if bare repo
no error messages in Output tab
- manual
----
> fix(bare repo): Skip "git status" and "git stash list"

- src/app/GitCommands/Settings/AppSettings.cs
- tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Fixes #12170
- `AppSettings.ShowProcessDialogPasswordInput`: Default to `false` (since the input box is automatically shown if an output line is not terminated with LF within a timeout)
N/A
- added to testcase
----
> fix(ShowProcessDialogPasswordInput): Default to false

- Directory.Packages.props
- setup/installer/Product.wxs
- src/app/GitExtensions.Extensibility/Git/RelativePath.cs
- src/app/GitExtensions.Extensibility/GitExtensions.Extensibility.csproj
- src/app/GitUI/BuildServerIntegration/BuildServerWatcher.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormBisect.cs
- src/app/GitUI/CommandsDialogs/FormBlame.cs
- src/app/GitUI/CommandsDialogs/FormFileHistory.cs
- src/app/GitUI/CommandsDialogs/IRevisionGridFileUpdate.cs
- src/app/GitUI/CommandsDialogs/IRevisionGridInfo.cs
- src/app/GitUI/CommandsDialogs/IRevisionGridUpdate.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- src/app/GitUI/LeftPanel/LocalBranchTree.cs
- src/app/GitUI/LeftPanel/RepoObjectsTree.cs
- src/app/GitUI/UserControls/BlameControl.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- chore: Fixup typo in namespace `GitUI.CommandsDialogs`
- refactor(`RevisionDiffControl`): Use simpler types
- refactor(`BlameControl`): Clearly request `PathToBlame` by adding a dedicated interface `IRevisionGridFileUpdate` in favor of `IRevisionGridUpdate`
(Review commit by commit recommended.)
N/A
- manual
----
> refactor(BlameControl): Use clearer interface

- src/app/GitUI/CommandsDialogs/FormCommit.cs
FormCommit:
- Handle clicks in empty area of Unstaged & Staged lists
- Clear displayed diff if focused Unstaged / Staged list is empty
- manual
----
> fix(FormCommit): Improve selection handling

- src/app/GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
Whe conbemu is not used for longrunning commands like git-fetch
Links were previously detected but not clickable.
Similar handling in the output pane recently added and in CommitInfo (where also Git links are handled and translated to internal links).
The  "hand" appears as before, but something now happens when the link is clicked.
With dark mode and the background set to the theme EditorPanel, by default it is Control.
Manual
----
> feat: Clickable links in console output

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/UserControls/OutputHistoryPanelController.cs
Fixes regression from adding a second SplitControl
`OutputHistoryPanelController`:
- Hide Output History Panel with Left Panel (- 
- Show Left Panel on show of Output History Panel
- manual
----
> fix(Output History Panel): Hide with Left Panel

- src/app/GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- src/app/GitUI/LeftPanel/RepoObjectsTree.cs
- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
`RevisionGridControl`:
- Add context menu item "Select in left panel" for branches and tags
- manual
----
> feat: Add SelectInLeftPanel

- src/app/GitUI/BuildServerIntegration/BuildServerWatcher.cs
- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/CommandsDialogs/FormLog.cs
- src/app/GitUI/CommitInfo/CommitInfo.cs
- src/app/GitUI/CommitInfo/CommitInfoHeader.cs
- src/app/GitUI/UserControls/FileStatusList.cs
Fixes "unhandled exception" popup (repeatedly seen on `OperationCanceledException` in test execution)
- Wrap handler code with `TaskManager.HandleExceptions(..., Application.OnThreadException)`
N/A
- run the tests
----
> Handle exceptions

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
`SetGitModule` is already call in `StartToolStripMenuItem.repositoryHistoryUIService_GitModuleChanged()` registered with `FormBrowse.cs@770`:
`fileToolStripMenuItem.GitModuleChanged += new System.EventHandler<GitModuleEventArgs>(SetGitModule);`
- Manual
- GIT 
- Windows 
----
> fix: prevent double call to SetGitModule on repo change

- src/app/GitCommands/Git/GitModule.cs
Fixes #11391
- Manual
- Build 9e9082cc28af498ef4d3ce5ce314a7a53b0d626e (Dirty)
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.12
```
Microsoft.WindowsDesktop.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
----
> fix(reset):Fix reset unstaged changes of a new file already partly staged

- src/app/GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs
- src/app/GitUI/WindowsJumpListManager.cs
Fixes #10845
- `WindowsJumpListManager` / `RepositoryDescriptionProvider`: Use unique name for recent repos
descriptive name with full path appended
with
`repo.gitext` containing
`D:\Downloads\super\submodule2\repo\`
or
`D:\Downloads\super\submodule1\repo\`
with `.git/description` containing:
- "super_repo"
- "sm1_repo"
- "sm2_repo"
- manual 
----
> fix(Jump List): Use unique name for recent repos

- src/app/GitUI/Translation/English.Plugins.xlf
- src/plugins/BackgroundFetch/BackgroundFetchPlugin.cs
Fixes #6457
Note: the fetching is not "immediate" because the background fetch is waiting that no git process is running but should be triggered quickly enough so that user hardly noticed.
- Manual
- Build c16f47d4fbe4a8c415888267a013405c6b99465c (Dirty)
- Git 2.47.0.windows.1
- Microsoft Windows NT 10.0.26100.0
- .NET 8.0.12
```
Microsoft.WindowsDesktop.App 8.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 9.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
---- …
> feat(BackgroundFetchPlugin): Add option to fetch on repo opening

- src/app/GitCommands/Git/GitSshHelpers.cs
Fixes "error: cannot spawn : No such file or directory" e.g. on "git fetch" (with space in front of the second colon)
The behavior of `Environment.SetEnvironmentVariable` for empty string seems to have changed with .NET9.
It does not unset the environment variable, but creates "GIT_SSH=" in the environment.
This makes git attempt to run the empty string as SSH command (on some machines only).
So, explicitly unset "GIT_SSH" if an empty string was read from the registry.
N/A
- manual
----
> fix(GIT_SSH): Avoid "error: cannot spawn : No such file or directory" with .NET9

- Directory.Build.props
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- src/app/GitUI/GitUI.csproj
- src/app/GitUI/ScriptsEngine/ScriptInfo.cs
- tests/app/IntegrationTests/UI.IntegrationTests/ScriptEngine/ScriptManagerTests.Can_save_settings.verified.xml
- tests/app/UnitTests/GitUI.Tests/GitUI.Tests.csproj
Fixes slow opening of context menus in RevisionGrid and FileStatusList
- Cache script icons
- Load assembly icons only once
- Reset invalid script icon names
including wrong, arguable default icon "bug"
- Enable C#13+ syntax in order to enable the `field` keyword for properties
- manual
----
> perf(context menus): Cache script icons (for context menus)

- src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/ReleaseVersion.cs
- src/app/GitUI/Translation/English.xlf
- tests/app/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormUpdatesTests.cs
- tests/app/UnitTests/GitUI.Tests/CommandsDialogs/BrowseDialog/ReleaseVersionTests.cs
Resolves #12205
- Read required .NET desktop runtime version from https://github.com/gitextensions/gitextensions/blob/configdata/GitExtensions.releases. If the version is found it is shown in the dialog, otherwise the text is hidden. 
- Some QOL improvements.
Tested manually.
- A test config is currently available at https://github.com/gitextensions/gitextensions/blob/configdata_test/GitExtensions.releases.
- Local version is set to 4.2.0, so the updater can detect a newer version
```diff
diff --git a/src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs b/src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
index 832a36f79..4be587fb5 100644
--- a/src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
+++ b/src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
@@ -27,7 …
```
> FormUpdate: display .NET runtime requirements

- src/app/GitUI/CommandsDialogs/SettingsDialog/Plugins/PluginSettingsPage.cs
Some info to debug #12212 etc
The most common NBug after Windows update issues and Git reporting errors.
The exception does not even contain the plugin that fails right now.
More info can be added?
Added throw to see the message appeared.
----
> fix: catch plugin settings load exceptions

- src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/FormUpdates.resx
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs
- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/Settings/SettingsLinkLabel.Designer.cs
- src/app/GitUI/UserControls/Settings/SettingsLinkLabel.cs
- src/app/GitUI/UserEnvironmentInformation.cs
Follow-up to #12217
- Mention update of .NET runtime only if required
- Mention local install using new control `SettingsLinkLabel` pointing to new Wiki page
- Change ChangeLog link to https://github.com/gitextensions/gitextensions/releases (added link to `ChangeLog.md` there)
- `GitSettingsPage`: Clearer description of WSL git executable
- manual
BTW: after several tries
----
> feat: Clarify update & git exe path

- src/app/GitExtUtils/GitUI/Theming/OtherColors.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- src/app/GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
- src/app/GitUI/HelperDialogs/FormResetCurrentBranch.cs
Use the same colors in the settings check as in reset branch. These colors also look OK in dark mode.
Use a common definition of the bright colors.
Unchanged
Good enough for me in dark mode (can be tuned to be slightly darker but better than adapting current colors, there are less colors to customize if that is done).
As a reference, the adapted colors in dark mode
Manual
----
> fix: adjust settings check colors

- src/app/GitCommands/Settings/AppSettings.cs
Fixes that AppSettings continues to use the version of the previous git executable
- fix(AppSettings): Reset git version **after** storing 
- perf(AppSettings): Run "git --version" only if a different git executable has been set
N/A
----
> fix(AppSettings): Reset git version after storing

- src/app/GitExtensions/GitExtensions.csproj
- src/app/GitUI/AutoCompletion/AutoCompleteRegexes.cs
- src/app/GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
- tests/app/IntegrationTests/UI.IntegrationTests/UI.IntegrationTests.csproj
Fixes #12226
- Embed default `AutoCompleteRegexes.txt` as raw string literal instead of as resource file in order to be able to use them in tests, too
N/A
----
> build: Embed AutoCompleteRegexes as raw string literal

- src/app/GitUI/UserControls/BlameControl.cs
- tests/app/UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
Fixes #12242
- BlameControl: Avoid negative number of spaces appended to author line (in case length estimation was too low)
N/A
- manual
----
> fix(BlameControl): Avoid negative number of spaces

- src/app/GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Fixup for #12244
- `ReadOrInitializeAutoCompleteRegexes`: No need for `StreamReader` when using `AutoCompleteRegexes.Default`
<br>`StreamReader` interpreted the regexes as filename 
N/A
----
> fix(AutoCompletion): No need for StreamReader

- tests/CommonTestUtils/TestAppSettingsAttribute.cs
- tests/app/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormRebaseTests.cs
- tests/app/IntegrationTests/UI.IntegrationTests/GitCommands/GitModuleTests.cs
- tests/app/UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
- Dispose all `ReferenceRepository` instances
in `OneTimeTearDown`: better late than never (i.e. but does not resolve #12238)
otherwise, not all temp repos are deleted
- Dispose `AppSettings` cache on teardown of entire test suite
N/A
----
> fix(tests): Add missing Dispose calls to test teardown

- src/app/GitCommands/Settings/SettingsCache.cs
- tests/CommonTestUtils/TestAppSettingsAttribute.cs
Fixes #12252
`TestAppSettingsAttribute`:
- Serialize execution of test assembly by means of a named `Semaphore`
- Actually load & create a default `AppSettings` file
N/A
- run tests
----
> fix(tests): Serialize execution; Load and create default settings file

- src/app/GitCommands/Settings/FileSettingsCache.cs
If there are concurrent changes to the settings file (on disk vs. in app), the last action shall win.
That's why additionally check in `FileSettingsCache.NeedRefresh` whether the app has newer modifications in memory.
N/A
----
> fix(FileSettingsCache): The last change must win!

- Directory.Packages.props
- src/plugins/AutoCompileSubmodules/GitExtensions.Plugins.AutoCompileSubmodules.csproj
- tests/Directory.Build.props
error NU1510: Warning As Error: PackageReference X.Y.Z will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
related to https://github.com/gitextensions/gitextensions/pull/12111#issuecomment-2709403043
separated
By @RussKie (I just try to keep  #12111 with changes only affecting dark mode to keep it reviewable)
Build
----
> fix: Address NU1510 warning

- src/app/GitCommands/Git/GitItemStatusNameEqualityComparer.cs
- src/app/GitExtensions.Extensibility/Git/GitItemStatus.cs
- src/app/GitUI/UserControls/FileStatusDiffCalculator.cs
When comparing status for branches, the status compared to BASE is shown as Unequal/Same/A/B.
For renamed and copied files, the old name was not used when comparing, so status was not set correctly.
Comparing 8863b8b46fc42b416f7493eaad35138e8c80ce41 with my private branch tmp/test-modified
Note that the status A-B is not always the same as BASE-A/B
Manual
----
> fix(FileStatusList): status for renamed in branch diffs

- src/app/BugReporter/Info/GeneralInfo.cs
- src/app/BugReporter/UserEnvironmentInformation.cs
- src/app/GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
- src/app/GitCommands/Git/Executable.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/Git/GitVersion.cs
- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitExtensions.Extensibility/IExecutable.cs
- src/app/GitUI/CommandsDialogs/FormResolveConflicts.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs
- src/app/GitUI/Editor/Diff/DiffHighlightService.cs
- src/app/GitUI/Infrastructure/Telemetry/AppEnvironmentTelemetryInitializer.cs
- src/app/GitUI/UserEnvironmentInformation.cs
- tests/CommonTestUtils/MockExecutable.cs
- tests/app/UnitTests/BugReporter.Tests/UserEnvironmentInformationTests.cs
- tests/app/UnitTests/GitCommands.Tests/DiffMergeTools/DiffMergeToolConfigurationManagerTests.cs
- tests/app/UnitTests/GitUI.Tests/UserEnvironmentInformationTests.cs
Addresses https://github.com/gitextensions/gitextensions/pull/12185#issuecomment-2683482362
ChecklistSettingsPage:
- Check _used_ git version
- Display versions of used git (WSL) and of configured native git (if different)
GitVersion:
- Simplify by always identifying the `GitVersion` by means of `gitExecutable.Command + gitExecutable.PrefixArguments`
- Reduce dictionary lookups and handle exceptions
- Unindent namespace
- Exit early
- Apply code style
IExecutable:
- Add property `PrefixArguments`
- manual
- to be tested with real WSL, please
----
> feat(CheckListSettingsPage): Improve display of git version

- src/app/ResourceManager/LinkFactory.cs
Addresses https://github.com/gitextensions/gitextensions/discussions/12272#discussioncomment-12583313
- Use `OsShellUtil.OpenUrlInDefaultBrowser` wherever a URL is opened 
N/A
- manual
----
> refactor(LinkFactory.ExecuteLink): Use OsShellUtil

- .github/copilot-instructions.md
- src/app/GitCommands/Config/SettingKeyString.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/Remotes/ConfigFileRemote.cs
- src/app/GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/CommandsDialogs/FormRemotes.Designer.cs
- src/app/GitUI/CommandsDialogs/FormRemotes.cs
- src/app/GitUI/CommandsDialogs/FormRemotes.resx
- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/RevisionGrid/CellStyle.cs
- src/app/GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- tests/app/UnitTests/GitCommands.Tests/GitModuleTests.cs
- tests/app/UnitTests/GitCommands.Tests/GitModuleTests_Remotes.cs
- tests/app/UnitTests/GitCommands.Tests/Remote/ConfigFileRemoteSettingsManagerTests.cs
I generally work in repos where maintainers tend to use main trunks instead of own forks, which makes repos very busy. Those repos also tend to have several remotes, which often make finding the right branch a daunting task. 
Colouring the remotes makes finding the right remote easier.
- Allow customise colors of remotes
- Reorder name and URL rows in FormRemotes dialog
**Key points:**
- The color settings are persisted in \<repo>/.gitconfig, where "remote" information is stored.
- If/whenever the app's color theme is changed, the remotes' colours must be changed manually. No automatic colour adjustment is planned.
- The feature belongs to the "advanced" feature set, and it is only available when "Show advanced option" is enabled.
If the color is not set, then only "Set color" button is …
> Allow customise colors of remotes

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes #11391
GitModule:
- Do not rely on the (lazy) `postUnstageStatus` for deleted files, because they may be deleted after its evaluation
RevisionDiffControl:
- Evaluate `DiffFiles.SelectedItems` (plural) instead of `DiffFiles.SelectedItem` (singular) also when checking the validity in `DeleteSelectedFiles`
- Use arrays instead of lists in `ResetSelectedItemsTo` and `ResetSelectedItemsWithConfirmation`
error popup on reset multiple new files
no reaction on delete multiple files (with #12149)
reset & delete multiple new files work silently
- manual
----
> fix(delete files): Avoid wrong popup and actually support deleting multiple files

- src/app/GitUI/Editor/FileViewer.cs
Fixes #12269
FileViewer: Render only the first frame of an animated image in order to avoid exception in `PictureBox.WndProc` 
first frame, then red frame and cross
first frame
- manual
----
> fix(FileViewer): Avoid crash on animated image file

- src/app/GitExtensions.Extensibility/DebugHelpers.cs
- src/app/GitUI/ServiceContainerRegistry.cs
- Add `DebugHelpers.Trace` and `.TraceIf` with the name of the calling method prepended to the traced message
- Show such output in the Output History tab / panel, too
Benefit: Ease debugging. Short identical/similar code lines can be added in order to trace function calls and current values.
N/A
- manual
----
> feat: Add DebugHelpers.Trace[If]

- .github/PULL_REQUEST_TEMPLATE.md
It's understandable that there may be (are!) dialogs, form elements which are broken under higher DPI / scaling, that were developed long ago. But for this to keep happening recently is mildly put _unfortunate_.
This is a bug that triggered this PR https://github.com/gitextensions/gitextensions/issues/12302 but there's also this https://github.com/gitextensions/gitextensions/issues/12303 (although the screenshots seem to be made at higher DPI although under a different theme)
- Add instructions to PR template to include higher scaling factors
----
> Add instructions asking for higher scaling screenshots

- src/app/GitUI/UserControls/FileStatusList.Designer.cs
Fixes -
- Fix overflowing label at higher DPIs
At 200%
At 200%
At 100%
- Windows 11
----
> Fix file list regex watermark label overflow

- src/app/GitUI/CommandsDialogs/FormRemotes.cs
- When editing selected color it's often the case that the color itself is fine but should be darker/lighter thus it's desired that previously selected value would be reflected in a color picker when attempting to update the color
- Manually
- Windows 11
----
> Initialize color picker with remote's color

- src/app/GitUI/CommandsDialogs/FormRemotes.Designer.cs
- src/app/GitUI/CommandsDialogs/FormRemotes.cs
Fixes #12303
- `AutoSize = true` for labels
- Prevent `btnRemoteColorReset` from blinking out part of a second after being shown
At 200%
At 200%
At 100%
- Manully at 100% and 200% scaling
- Windows 11
----
> Fix FormRemotes color label size

- src/app/GitUI/UserControls/FileStatusList.DelayedExpansion.cs
- src/app/GitUI/UserControls/FileStatusList.Designer.cs
- src/app/GitUI/UserControls/FileStatusList.FileIcons.cs
- src/app/GitUI/UserControls/FileStatusList.MissingIcon.cs
- src/app/GitUI/UserControls/FileStatusList.TreeContextMenu.cs
- src/app/GitUI/UserControls/FileStatusList.cs
- src/app/GitUI/UserControls/MultiSelectTreeView.cs
- src/app/GitUI/UserControls/TreeViewExtensions.cs
FileStatusList:
- Display file icons for git-grep and if grouped by file extension
- Add git-grep subfolder content on expand
- manual
----
> feat(FileStatusList): Display file icons for git-grep and if grouped by file extension

- src/app/GitUI/CommandsDialogs/FormStash.cs
Fixes #12302
- Revert changes to `Stashes` drop-down size calculation introduced in #12149
At 200%
At 200%
At 100%
- Windows 11
----
> Fix Stashes drop-down size calculation

- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/Editor/FileViewerInternal.cs
`FileViewer`: Set caret to first change line
in order to open editor, VS, etc. at a meaningful line but not view line off.
- manual
----
> feat(diff viewer): Set caret to first change line

- src/app/GitUI/Editor/FormFindInCommitFilesGitGrep.Designer.cs
Fixes #12310
- Fix Find button scaling
- Fix watermark placement
At 200%
At 100%
At 200%
At 150%
At 100%
- Manually at 100% 150% and 200% scaling
- Windows 11
----
> Fix Find button scaling in git-grep dialog

- src/app/GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/Editor/FileViewerInternal.cs
- src/app/GitUI/Theming/ThemeModule.cs
- src/app/GitUI/UserControls/BlameControl.cs
Depends on https://github.com/gitextensions/ICSharpCode.TextEditor/pull/51
Use WindowsText color to mark the line for the caret/cursor line, keeping gray text for others.
Especially in dark mode, the cursor can be hard to see, also when marking. This makes it easier to se the cursor line.
This is implemented for all editors with some kind of cursors, including read-only.
The kind of exception is Blame control where the left (author) part may have a line number panel (better to hide it).
Note: I implemented and discarded the left line no following the right (with the cursor), but it is no real improvement, the left lineno is not following info in the author panel anyway.
(Before that I implemented that clicking in author panel controlled the cursor, which was just annoying.
In the same …
> feat: mark current line in editor

- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitUI/HelperDialogs/FormResetAnotherBranch.Designer.cs
- src/app/GitUI/HelperDialogs/FormResetAnotherBranch.cs
- src/app/GitUI/Translation/English.xlf
- tests/app/UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
I constantly finding myself continue on the wrong branch after resetting another branch to the ~current~ desired commit. This change allows starting automatically the branch checkout sequence
The checkbox is set (and the flow is enabled) by default; can be opt-ed out by unchecking the checkbox. The user choice is remembered.
I didn't want to force checkout, as it's possible to end up in a situation where a user has pending changes, and those could get lost. This way, the user can make a conscious decision to proceed or not.
----
> Checkout "other" branch after reset

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/Logging/CommandLog.cs
- src/app/GitExtensions.Extensibility/ExecutionResult.cs
- src/app/GitUI/GitUIExtensions.cs
- src/app/GitUI/NBugReports/BugReportInvoker.cs
Display larger `ExitCode` values (beyond +/-128) as hexadecimal number (in addition to decimal) in
- BugReporterInvoker
- GitCommandLog
- GetSingleDifftoolAsync & ViewChangesAsync on error
- manual
----
> feat(ExitCode): Display larger values hexadecimal

- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/Editor/FileViewerInternal.cs
Fixes regression by #12317
- `FileViewer`: Actually go to first change if no line number is passed
- `RevisionDiffControl`: Keep line number when switching extra diff arguments
N/A
1. move to next change on every toggle of "Show entire file"
2. second git-grep match selected if first was in first line
1. stay at current change
2. first git-grep match selected
- manual
----
> fix(FileViewer): Actually go to first change

- src/app/GitUI/SpellChecker/EditNetSpell.Designer.cs
Fixes #12340
`EditNetSpell`: Disable `TextBox.DetectUrls` in general.
It is not used: None of the four usages has a `LinkClicked` handler.
- manually
----
> fix(message editor): Disable URL detection

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- `LeftSplitContainer.Panel2` (Output panel): Account for shift by 2px as for `RevisionsSplitContainer`
- manual with different scaling
----
> fix(LeftSplitContainer): Workaround shift on load

- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/UserControls/FileStatusList.ContextMenu.cs
- src/app/GitUI/UserControls/FileStatusList.cs
- src/app/GitUI/UserControls/MultiSelectTreeView.cs
Requested in https://github.com/gitextensions/gitextensions/pull/12312#issuecomment-2816865516
- Enable git-grep for file-tree, too
- manual
----
> feat(file tree): Provide git-grep

- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
- src/app/GitUI/NBugReports/BugReportInvoker.cs
- `GitConfigSettingsPage`: Adapt paths of suggested editor commands in case of WSL repo
- `BugReportInvoker.ReportDubiousOwnership`:
- Do not popup twice at a time
- Support WSL (use WSL git for WSL repo)
- (Try to) open the newly trusted repo (instead of the Dashboard)
- manually
----
> feat(WSL, dubious ownership): Improve first use of WSL repo

- src/app/GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs
- src/app/GitUI/CommandsDialogs/FormClone.Designer.cs
- src/app/GitUI/CommandsDialogs/FormPull.Designer.cs
- src/app/GitUI/CommandsDialogs/FormPull.cs
- src/app/GitUI/CommandsDialogs/FormPush.Designer.cs
- src/app/GitUI/CommandsDialogs/FormRemotes.Designer.cs
- src/app/GitUI/CommandsDialogs/FormRemotes.cs
- src/app/GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.Designer.cs
- src/app/GitUI/LeftPanel/RepoObjectsTree.Designer.cs
- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/FolderBrowserButton.Designer.cs
- src/app/GitUI/UserControls/FolderBrowserButton.cs
Hello! I’m back with more keyboard mnemonics:
* All elements in “Remote Repositories” dialog
* The “Fetch and Prune” command in the remote right-click menu
* “Load SSH key” in “Push” dialog
```
E	Separate Push Url (checkbox; R tab)
F	Default merge with (textbox/dropdown; D tab)
K	Private key file (textbox; R tab)
L	Load SSH key (button; R tab)
L	Local branch name (textbox; D tab)
N	Name (textbox; R tab)
P	Push Url (textbox; R tab)
R	Remote repository (textbox/dropdown; D tab)
S	Save changes (button)
T	Test connection (button; R tab)
U	Url/Fetch Url (textbox; R tab)
```
> Add more keyboard mnemonics

- src/app/GitCommands/Utils/WslUtil.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- `LaunchRebase`: Forward env var `GIT_SEQUENCE_EDITOR` to WSL in order to make "edit / reword commit" work
by setting env var `WSLENV`, which controls which env vars are synchronized between Windows and WSL
editor pops up with `git-rebase-todo` file
works as expected without the need to edit `git-rebase-todo`
- manually
----
> fix(WSL): Make "edit commit" & "reword commit" work

- src/app/GitUI/WindowsJumpListManager.cs
- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffHighlightServiceTests.MarkInlineGap.verified.txt
Remove the redundant __wsl$_ in the unique path, to maybe get something interesting in the path
I considered hardcoding Ubuntu too, but there are other distros...
manual
----
> fix: jumplist ignore \\wsl$\

- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
- src/app/GitUI/Translation/English.xlf
- Add `credential.helper` to git config settings page (with matching suggestions from git folder) (https://git-scm.com/docs/git-config#Documentation/git-config.txt-credentialhelper)
- Add `rerere.enabled` and `rerere.autoupdate` to advanced git settings page (https://git-scm.com/docs/git-config#Documentation/git-config.txt-rerereautoUpdate)
- manually
----
> feat(git config): Add credential.helper and "reuse recorded resolution of conflicted merges"

- src/app/GitUI/Editor/FindAndReplaceForm.cs
Fixes #12380
`FindAndReplaceForm`: Cancel multi-file search if the form has been closed
(`btnCancel_Click` just closes the form.)
N/A
- manually
----
> fix(FindAndReplaceForm): Make multi-file search cancelable

- src/app/GitCommands/Settings/GitConfigSettingsBase.cs
Fixes occasionally failing testcase `TestFetchArguments`
`GitConfigSettingsBase`: Fixup race condition between Invalidate and Update. Both need locking.
N/A
- GIT 
- Windows 
----
> fix(GitConfigSettingsBase): Fixup race condition

- src/app/GitCommands/Git/GitRef.cs
Fixes #12387
- `GitRef.ParseName`: Use `SubstringAfter` instead of `SubstringAfterLast` for removing prefixes "remotes/", "tags/", "heads/"
(from one of the huge refactorings by Drew Noakes)
- manually
----
> fix(GitRef): Do not remove too much when removing prefix

- src/app/GitUI/UserControls/MultiSelectTreeView.cs
`MultiSelectTreeView`:
- Select block using `Shift` + arrow keys
- Rework multi-selection by mouse (replace misuse of `FocusedNode` as `_multiselectionStartNode`)
- Remove unused function `AddToSelection`
Result after `Shift+click` (focused node has highlighted icon):
- manually & existing tests
----
> feat(MultiSelectTreeView): Select block using keys

- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes empty file selection e.g. in case the previously selected file has been renamed
- `RevisionDiffControl.RefreshArtificial`: Tell `FileStatusList.SelectStoredNextItem` to select the first file if stored item cannot be found
- manually
----
> fix(refresh artificial commit): Avoid no selection

- contributors.txt
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/Logging/CommandLog.cs
- src/app/GitCommands/Settings/AppSettings.cs
- src/app/GitUI/HelperDialogs/FormProcess.cs
- src/app/GitUI/NBugReports/BugReportInvoker.cs
- tests/app/UnitTests/GitCommands.Tests/CommandLogTests.cs
Fixes [issue #12381](https://github.com/gitextensions/gitextensions/issues/12381)
Resolves [issue #12400](https://github.com/gitextensions/gitextensions/issues/12400)
- Adds the `--cd` argument with the current working directory to the `wsl` command
- Fixes correct display of commands that access remotes (fetch, pull, etc...) 
- Changes how `git` commands executed on WSL are logged. "wsl" --> "~git"
- Rename the setting "WslGitCommand" to "WslCommand" and "WslGitPath" to "WslGitCommand"
- Empirical (i.e.: it fixes the error on my machine). I have no way of testing in any other environment but it should be a transparent change for anyone else.
- GIT 2.49.0
- WSL version: 2.5.7.0
- Kernel version: 6.6.87.1-1
- WSLg version: 1.0.66
- MSRDC version: 1.2.6074
- Direct3D version: …
> Enforce WSL working directory, fix Git Command Log display

- src/app/GitUI/CommandsDialogs/FormCommit.cs
Finishes @mdonatas' 493a2f4d2377e9bf269c999c29f062d0ad444fcc
`FormCommit`:
- `Unstaged_Enter` / `Staged_Enter`: Explicitly call `UnstagedSelectionChanged` / `StagedSelectionChanged` only if selection is empty or if selection has not changed
- Replace `ViewFirstStagedFile` with what is done in `Staged_Enter`
before visible flicker mainly of bold current line number
- manual (with debug output)
----
> fix(FormCommit): Prevent double diff loading

- src/app/GitUI/MessageBoxes.cs
- src/app/GitUI/Translation/English.xlf
Added a keyboard mnemonic for the “Remember choice” checkbox in confirmation dialogs.
Unfortunately I couldn’t get it to happen again, even after checking all of the options in Settings→Confirmations and restarting the app. :(
----
> Keyboard mnemonic for “Remember choice”

- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
- src/app/GitUI/UserControls/MultiSelectTreeView.cs
- tests/app/IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
`MultiSelectTreeView`:
- Restore explicit click: Emit `SelectionChanged` also if the clicked item has already been selected (regression)
- Restrict focus workaround (`_toBeFocusedNode `) to be used for expand / collapse on root icon click only again and do not change the selection
`RevisionDiffControl`:
- Do not discard nor store selection info during loading diffs (bug)
because it might be canceled before the stored selection is applied again
- Just clear the diff view if there are no diff items instead of calling `ShowSelectedFile` (bug)
N/A
- add `FileSelection_should_be_restored_after_refresh`
----
> Fixup restore of file selection

- src/app/GitUI/RepositoryHistoryUIService.cs
- tests/app/UnitTests/GitUI.Tests/RepositoryHistoryUIServiceTests.cs
- The “Recent repositories” submenu now has “1.”, “2.”, etc. in front of the repo names.
- The first 10 of those numbers get the keyboard mnemonics 1–9 and 0.
Before on left, after on right.
Test fixes are included. I did run `dotnet test` and it succeeded.
----
> Add numbers and mnemonics in the “Recent repositories” menu

- src/app/GitUI/Translation/English.xlf
- src/app/GitUI/UserControls/FileStatusList.ContextMenu.cs
- src/app/GitUI/UserControls/FileStatusList.TreeContextMenu.cs
`FileStatusList.TreeContextMenu`:
Since "Stage" and "Sort and group by" do not apply to the file-tree only "Collapse root folders", 'S' can be  used as mnemonic
in order to not interfere with "Show "Find in commit fi&les".
- manual
- review
----
> fix(file tree context menu): Unique mnemonic for "Collapse root folders"

- src/app/GitCommands/Settings/GitConfigSettings.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
Fixes #12422
Fixes regression from switch to `GitConfigSettings`
- `GitConfigSettings.GetValues`: Also return single value instead of empty list
- `GitConfigSettings.SetValue`: Fixup exception message in case of multi-value
- `credential.helper`:
- Display multi-value config and disable edit
- Hide in effective settings (because it is not worth running an additional git command for this single usecase)
----
> fix(multi-value git config): "credential.helper"

- src/app/GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs
- src/app/GitUI/Translation/English.xlf
Fixes #12433
Broken by #12282
`FormOpenDirectory.folderBrowserButton`: Restore button label
Using `FolderBrowserButton` here would be too intrusive.
no label, refer to bug report
----
> fix(FormOpenDirectory): Restore button label

- src/app/GitUI/CommandsDialogs/FormPush.Designer.cs
- `FormPush`: Align labels "to" and "Recursive submodules"
----
> fix(FormPush): Align labels with fields

- src/app/GitUI/UserControls/FileStatusList.ContextMenu.cs
remove menu item without effect
As well as on files, now removed
----
> fix(filetree): Hide "Show in File tree"

- src/app/GitExtUtils/GitUI/Theming/ThemeAwareAttribute.cs
- src/app/GitExtUtils/GitUI/Theming/ThemeFix.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
https://github.com/gitextensions/gitextensions/pull/12454#discussion_r2217962198
No longer needed to theme the Dashboard
Follow up (kindof) to removing old theming in #21111
Manual
----
> fix: Remove attribute ThemeAware

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/Git/GitTreeParser.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitUI/UserControls/FileStatusDiffCalculator.cs
- src/app/GitUI/UserControls/FileStatusList.cs
- tests/app/UnitTests/GitCommands.Tests/Git/GitTreeParserTests.cs
fixes #12413 
fixes #12464 
Improve performance (especially for lfs files) to display the file tree if no grep filter is active.
See the issue for the reduced time to run the command.
This could be moved to GitModule instead.
GitModule is a better place for checking that 
Note: ls-tree cannot be used for artificial commits, but ls-files could be used
That is a separate optimization
view manual git log
----
> fix(file tree): ls-tree if no grep

- src/app/GitCommands/Git/GitItem.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitExtensions.Extensibility/Git/GitObjectType.cs
- src/app/GitExtensions.Extensibility/Git/GitSubmoduleStatus.cs
- src/app/GitExtensions.Extensibility/Git/IGitModule.cs
- src/app/GitExtensions.Extensibility/Git/IObjectGitItem.cs
- src/app/GitExtensions.Extensibility/Git/SubmoduleStatus.cs
- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/UserControls/FileStatusList.cs
- src/app/ResourceManager/LocalizationHelpers.cs
- tests/app/UnitTests/GitCommands.Tests/Git/GitTreeParserTests.cs
- tests/app/UnitTests/GitCommands.Tests/GitRevisionInfoProviderTests.cs
Follow up to https://github.com/gitextensions/gitextensions/pull/12421#issuecomment-3014378138
Based on #12421
present removed submodules
- Submodule presentation in the file tree and diff did not
present removed submodules.
- In diffs, detect if the path is a submodule also if the path
does not exist.
To present submodules as diff or in file tree the submodule must be present.
By default is only the path and the commit sha known.
Previously these paths were in some scenarios presented as files, which raised error messages.
see also See #12421 for prev
removed submodule in commit, folder not available in worktree, .gitmodule contains the file
removed submodule, folder exists
added submodule, not in worktree
remove submodule is still like
manual
I agree that the maintainer squash merge …
> fix: present removed submodules

- src/app/GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #12484 
In revgrid->compare-Compare branches...
Show popupif no baseid found, if non existing branch written or the branches have no common ancestor.
Manual
----
> fix: compare branch check revgrid

- src/app/GitCommands/CommitDataManager.cs
- src/app/GitCommands/Git/GitModule.cs
- src/app/GitCommands/RevisionReader.cs
- src/app/GitUI/Editor/FileViewer.cs
- src/app/ResourceManager/LocalizationHelpers.cs
- tests/app/UnitTests/GitCommands.Tests/RevisionReaderTests.cs
The  ICommitDataManager interface was incorrectly documenting the 'includeNotes' parameter as 'cache'.
Commands for submodules summary was therefore not cached.
Check that the git-log is cached only if it is a full parsable sha
(branches etc should not be cached).
Fail artificial commits explicitly (should not be an issue)
Note: There are currently no usage of Notes with this code path in CommitDataManager.
I choose to document the usage (and where Notes are ignored) instead of removing.
This is related to a caching change in #11245, that was not fully effective.
There are some tests related to commitmanager.
Check in GitLog that the commands for 
Manual review of usage.
---- …
> fix: GetCommitData is includeNotes, not cache

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitExtensions.Extensibility/Git/GitSubmoduleStatus.cs
- src/app/ResourceManager/LocalizationHelpers.cs
align added/removed output with ahead/behind,
also for e.g. CreateBranch
fix some output formatting for submodules
Show "dirty" file icon if a submodule is changed but no specific icon exists.
added
removed
submodule diff
submodule current
Visual, UI presentation
----
> fix: format submodule status

- src/app/GitUI/Editor/FileViewer.cs
- src/app/GitUI/GitUIExtensions.cs
- src/app/GitUI/UserControls/BlameControl.cs
Fixes #8997 
There may be issues (at least discussions) about this), have not really looked
Check cancellation before viewing contents in the fileviewer. As getting the data is async and can require longer time (like range-diff and difftastic), the completed operation must not update if the old selection was cancelled.
Recreating is a lttle difficult, no screenshots.
Note: Most of the core problem can be fixed with about three check for cancellations in GitUIExtension.
However, this is not handling the case when git-cat-file takes time. The implementation is consistent.
Not critical.
Manually selecting large diffs with difftastic.
---- …
> fix: check cancellation before viewing text

- contributors.txt
- src/app/GitCommands/UserRepositoryHistory/Repository.cs
- src/app/GitUI/CommandsDialogs/FormClone.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
Fixes #11760
- When showing the clone window, fill the destination path combo box with the parent directories of the recent repository destination's
- Use the same logic as on the general settings page's default location combo box
- Manual testing only
- GIT 2.51
- Windows 11 24H2
----
> fix: show recent destination directories on clone

- src/app/GitUI/CommandsDialogs/FormCommit.cs
- src/app/GitUI/UserControls/FileStatusList.cs
Fixes #12432 
in FileStatusList.
compare to name in gitmodule config will fail.
The compare for name due to the added / fails in at least
https://github.com/gitextensions/gitextensions/blob/master/src/app/GitUI/CommandsDialogs/FormCommit.cs#L2047
I see no no reason to add the / to the name, it seem to have been added in the FileStatusList refactor.
Manual use.
----
> fix: do not add / to submodule names

- tests/app/UnitTests/GitUI.Tests/Editor/Diff/DiffHighlightServiceTests.cs
On a fresh clone, the test DiffHighlightServiceTests.MarkInlineGap was failing. This turned out to have been caused by the default configuration of Git on my Windows workstation: the configuration setting `core.autocrlf` is `true`. As a result, the file `gaps.diff`, which the test loads in as a known starting point for analysis by the test subject, has `\r\n` newlines, but the known-good data has byte ranges computed from the same file with `\n` newlines.
This PR makes the test work whether `core.autocrlf` is enabled or not by the simple expedience of replacing all `"\r\n"` sequences with `"\n"` before the file gets analyzed.
The subject of this PR is itself an automated test. It passes with the change in this PR. 🙂 
- GIT version 2.43.0.windows.1
- `core.autocrlf` is set to `true`
- …
> Test robustness: Account for core.autocrlf in DiffHighlightServiceTests.MarkInlineGap

- src/app/GitCommands/Git/GitModule.cs
- src/app/GitUI/UserControls/FileStatusDiffCalculator.cs
Regression with the updated ls-tree implementation in  6.0
For the initial commit the files are just listed,
must explicitly be set.
manual
----
> fix(FileStatusList): set files as new for initial commit
