- GitPlugin/Commands/ItemCommandBase.cs
> NullRefernceException in GitPlugin. Fix for #2591

- GitPlugin/Commands/Commit.cs
- GitPlugin/Connect.cs
- GitPlugin/Plugin.cs
Fix issues with VS Plugin:
Fix #2587
Fix #2601
Fix #2559
Fix #2560
Possible not best solution, because I am newbie in VS Addins, but at least it works
Checked on VS 2005, 2008, 2010, 2012, 2013
> Fix 2601, 2587, 2559, 2560

- Plugins/Stash/StashRequestBase.cs
I tried to compile with monodevelop, and It was compiled after this fix
> Compilation error fixed

- Setup/DownloadExternals.cmd
- Setup/Product.wxs
- Setup/UI/RequiredSoftwareDlg.wxs
> MSysGit updated to version 1.9.5-preview20141217

- .gitignore
Ignore Kdiff and MsysGit install files downloaded during build.
> Ignore downloaded files in build

- Plugins/Gource/Gource.cs
- Plugins/Gource/GourceStart.cs
Change gource download to use new github location and update settings code.
> Fix Gource URL and settings

- GitCommands/RevisionGraph.cs
> Fix filtering by branch name

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/FilterBranchHelper.cs
Improvement over #2543.
In fact, I think it's better to have a new menu item to display only tags
because we could have a lot....
> Add a new menu item to display tags in branch list

- Build/build.generic.cmd
- CONTRIBUTING.md
> Update documentation to mention VS2012 and VS2013

- GitUI/GitUI.csproj
> Fix GitUI output path

- GitExtensions.releases
> Remove 2.46 and 2.47 releases from config file as bugfix branches don't exist anymore

- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Resources/ChangeLog.md
> Intermittent error "cannot access a disposed object" on launch

- GitUI/UserControls/RevisionGridClasses/FormRevisionFilter.cs
Revert fix for #2700 in release/2.48
There is no easy way to fix it in release/2.48. I'll submit another PR for fix in master.
Closes #2822, #2854
> Fix quick filter

- ResourceManager/LinkFactory.cs
> Fix escaping & in Revision Link URIs

- GitUI/SpellChecker/SpellCheckEditControl.cs
Applied hint from a 6-years old comment :)
Fixes #2566
Doesn't fix occasional crashes on Main, Stash and Commit windows related to different errors.
> Linux: fixed crash after closing commit window

- GitCommands/PathUtil.cs
- GitExtensionsTest/GitCommands/Helpers/PathUtilTest.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs
Fixed the issue and added some tests for the new function.
> Fix a problem with the directory name detected for certain url. Closes #2614.

- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
> Fix bug where unable to locate plugins folder on Linux

- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
Adds handling for 403 Forbidden responses from Jenkins servers.
> Request Jenkins credentials for 403 Forbidden responses #2887

- Plugins/GitFlow/GitFlowForm.Designer.cs
Git Flow plugin: Fix some combo boxes overlap with labels
> Git Flow plugin: Fix some combo boxes overlap with labels

- GitExtensionsTest/GitExtensionsTest.csproj
- GitExtensionsTest/packages.config
by installing the nunit test adapter
> Being able to run the Nunit tests in Visual Studio

- GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
Hi, I've decided to add a template (preset) to use visual studio as a diff and merge tool. I think it's necessary for the project as it integrates to visual studio and it would be gerat to use it to the full extent. Personally I always use vsdiffmerge for work.
see #3033
> added vsdiffmerge tool

- Plugins/Statistics/GitStatistics/FormGitStatistics.cs
- Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
- Plugins/Statistics/GitStatistics/LineCounter.cs
Improved the statistics to count only files that under source control.
> Improve statistics plugin to only count files under source control 

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
> Exclude current branch for the Delete Obsoleted Branch Plugin

- GitUI/UserControls/RevisionGrid.cs
https://github.com/gitextensions/gitextensions/issues/2790
> additional not null check for issue 2790

- GitCommands/Settings/AppSettings.cs
This improves the UI on Linux, but does NOT affect the Windows version.
> Change the default application font

- GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs
otherwise it will get cropped.
Fixes #3181
> Auto size the ConEmu settings row

- GitCommands/Git/GitCommandHelpers.cs
- GitUI/UserControls/CommitPickerSmallControl.cs
> Able to Create Branch for Empty Repo

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
> Able to reenter credential if it was created by another user

- Plugins/BuildServerIntegration/TfsIntegration/ITfsHelper.cs
- Plugins/BuildServerIntegration/TfsIntegration/Settings/TfsSettingsUserControl.Designer.cs
- Plugins/BuildServerIntegration/TfsIntegration/Settings/TfsSettingsUserControl.cs
- Plugins/BuildServerIntegration/TfsIntegration/Settings/TfsSettingsUserControl.resx
- Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs
- Plugins/BuildServerIntegration/TfsInterop.Common/TfsHelper.cs
Support for using Regex to set Builds used to report statuses of the builds on TFS.
Business Case example:
Build Definitions are created per Branch.
> Multiple tfs build defs

- GitUI/CommandsDialogs/FormPull.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/HelpImageDisplayUserControl.cs
- ResourceManager/CommitDataExt.cs
- ResourceManager/TranslationUtils.cs
- ResourceManager/Xliff/TranslationFile.cs
Small fixes for bugs found with static analysis
> Small fixes

- Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.Designer.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
and not being able to log in or click on "log as guest"
if everyone could see the report!
> TeamCity: Add an option to try to display build report logged as a guest

- GitUI/CommandsDialogs/FormBrowse.cs
> Pull Menu Items Should Honor the Don't Set As Default Option

- GitUI/CommandsDialogs/FormCommit.cs
> No need to popup the NotOnBranch dialog while rebasing

- GitExtensions/Program.cs
- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
> Resolve git path from app data and fix the crash on startup when using git2.5

- GitCommands/Git/GitModule.cs
- GitCommands/Patch/PatchManager.cs
- GitCommands/Settings/CommonSettingsTypes.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
- GitUI/Editor/FileViewer.cs
> Fix bad case 'autocrlf' git settings saved

- GitCommands/Git/GitModule.cs
- GitCommands/Patch/PatchManager.cs
- GitCommands/Settings/CommonSettingsTypes.cs
- GitUI/CommandsDialogs/FormRemotes.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
- GitUI/Editor/FileViewer.cs
* longer textfields and combobox (better support of form resize)
* higher remotes list
> Fix layout form remotes

- GitUI/CommandsDialogs/BrowseDialog/FormBisect.Designer.cs
Because there is no constraints with this form...
Fix #2813
> Make 'Bisect form' resizable horizontally

- GitUI/GitUI.csproj
- GitUI/packages.config
This update permit to select text in the console and copy it, now...
> Update ConEmu.Core to fix problem that selection was unable

- GitUI/UserControls/ToolStripGitStatus.cs
The global ignore file isn't watched for changes, as described in #3054. This means that
when the file changes, we have to wait for the catchup timer to trigger (up to 5 minutes)
to have the commit strip updated.
Nothing fancy here, just a new FileWatcher and some plumbing to trigger a refresh when
needed.
> ToolStripGitStatus: Handle changes in the global ignore file.

- GitUI/Translation/Czech.xlf
- GitUI/Translation/Dutch.xlf
- GitUI/Translation/French.xlf
- GitUI/Translation/German.xlf
- GitUI/Translation/Italian.xlf
- GitUI/Translation/Japanese.xlf
- GitUI/Translation/Korean.xlf
- GitUI/Translation/Polish.xlf
- GitUI/Translation/Portuguese (Brazil).xlf
- GitUI/Translation/Portuguese (Portugal).xlf
- GitUI/Translation/Romanian.xlf
- GitUI/Translation/Russian.xlf
- GitUI/Translation/Simplified Chinese.xlf
- GitUI/Translation/Spanish.xlf
- GitUI/Translation/Traditional Chinese.xlf
- GitUI/UserControls/RevisionGrid.Designer.cs
- GitUI/UserControls/RevisionGrid.cs
Changes acted on issue #3256
* Change the labels
* Add some docs on modifying git history
* Add a contextual menu item to open the manual at the right place
> Improve fixup commits

- GitUI/CommandsDialogs/FormCreateBranch.cs
> Dont close create branch dialog when failed

- GitUI/CommandsDialogs/FormPush.cs
> No tracking when autoSetupMerge is false from git config

- GitCommands/Git/GitModule.cs
- GitCommands/Patch/PatchManager.cs
- GitExtensionsTest/GitUI/Editor/Diff/DiffLineNumAnalyzerFixture.cs
- GitUI/Editor/Diff/DiffLineNumAnalyzer.cs
- GitUI/Editor/Diff/DiffViewerLineNumberCtrl.cs
- GitUI/Editor/FileViewerInternal.cs
fix #3269, fix #3255
Moved to UI Thread
@jbialobr
> Diff line number fixes

- GitUI/CommandsDialogs/FormGitIgnore.Designer.cs
- GitUI/CommandsDialogs/FormGitIgnore.cs
* Add a link toward https://www.gitignore.io/ to help generate a custom .gitignore
* Update a little the default .gitgnore template
> Some changes around .gitignore

- GitCommands/Config/ConfigSection.cs
- GitCommands/PathUtil.cs
- GitCommands/Repository/Repositories.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGridClasses/FormRevisionFilter.cs
- Plugins/Gerrit/FormGerritDownload.cs
> Update code to use Linux aware paths

- GitExtensionsVSIX/GitExtensionsPackage.vsct
- GitPlugin/Connect.cs
Added menu entries:
- (F)ile History
- (R)eset File Changes
In order to have more useful mnemonics, I ...
- Removed shortcut for "Format Patch" completely
- Changed "Clone repository" to have the same as "Create repository" (being "y")
> Menu entries for improved accessibility.

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Settings can be accessed over the "Tools" menu
> Remove duplicate settings toolstrip item from "Tools" menu

- GitUI/CommandsDialogs/FormCreateBranch.Designer.cs
- GitUI/CommandsDialogs/FormCreateBranch.cs
* Labels are not left aligned to match the rest of the app
* Orphan group is re-flown
Fixes #3302
> fix: FormCreateBranch label alignment

- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.resx
> fix: Settings SSH layout broken

- GitUI/CommandsDialogs/FormCommit.cs
> focus commit box

- Setup/DownloadExternals.cmd
- Setup/Product.wxs
- Setup/UI/RequiredSoftwareDlg.wxs
To celebrate release 2.49.RC1  :tada:
I think that we should update to the last version for the release ;)
- Git to 2.10.1
- KDiff to 0.9.98
> Update required software

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormRebase.cs
As suggested in https://github.com/gitextensions/gitextensions/pull/3368#issuecomment-254676715
> [FormRebase] save state of the autostash checkbox

- Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCityBuildChooser.Designer.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCityBuildChooser.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.cs
- better naming in the treeview
- order the projects and builds alphabetically
- reselect the previously selected build when teamcity build chooser is reopened
- some refactoring (better naming)
> Improve teamcity build chooser

- GitCommands/Annotations.cs
- GitCommands/FileHelper.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Settings/RepoDistSettings.cs
- GitUI/Editor/FindAndReplaceForm.cs
- GitUI/GitModuleControl.cs
- GitUI/GitModuleForm.cs
- GitUI/GitUICommands.cs
- NetSpell.SpellChecker/Dictionary/WordDictionary.cs
- Plugins/Statistics/GitStatistics/PieChart/GraphicsUtil.cs
- Plugins/Statistics/GitStatistics/PieChart/PieChartControl.cs
- Plugins/Statistics/GitStatistics/PieChart/Quadrilateral.cs
List of words:
- method
- installer
- committer
- overridden
- initialized
- necessary
- relative
- describing
> Fix typos in comments

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCreateBranch.cs
- GitUI/CommandsDialogs/FormReflog.Designer.cs
- GitUI/CommandsDialogs/FormReflog.cs
- GitUI/CommandsDialogs/FormReflog.resx
- GitUI/GitUI.csproj
- Plugins/GitUIPluginInterfaces/IGitModule.cs
To show advancement and gather feedback....
> Add `reflog` support in `command` menu

- GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
The local branch with custom name should be auto normalised (if the feature enabled) at the checkout
Fixes #3450
> feat: Autonormalise local branch at checkout

- GitUI/CommandsDialogs/FormDiff.cs
> Fix issue where the comparing branch form didn't honor the toolbar buttons

- GitCommands/Git/GitModule.cs
> Respect core.commentChar setting

- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
Also rearrange the code to match control order.
Fixes #3539
> Fix (#3539) tab order on ConfirmationsSettingsPage

- GitUI/Translation/English.Plugins.xlf
- Plugins/Stash/StashPlugin.cs
- Plugins/Stash/StashPullRequestForm.cs
The commit deals with just renaming the strings in the UI. I am not sure if #3334 asks for more than that.
> Rename Stash to Bitbucket

- GitUI/BuildServerIntegration/BuildInfoDrawingLogic.cs
- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/GitUI.csproj
- GitUI/UserControls/RevisionGrid.Designer.cs
- GitUI/UserControls/RevisionGrid.cs
- GitUI/UserControls/RevisionGridUtils.cs
> Improve UX of RevisionGrid columns and fix visibility of SHA1 cell

- GitUI/CommandsDialogs/FormRebase.cs
> fix: Rebase specific range no more select the good 'to' branch

- GitUI/SpellChecker/EditNetSpell.cs
Fix defect #2926
Any of `Clipboard.Clear();` and `wait cycle` fix problem, but I add both for assurance
> Fix of #2926 (Cannot paste into commit window)

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.resx
- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUI.csproj
- GitUI/Translation/Czech.xlf
- GitUI/Translation/Dutch.xlf
- GitUI/Translation/English.xlf
- GitUI/Translation/French.xlf
- GitUI/Translation/German.xlf
- GitUI/Translation/Italian.xlf
- GitUI/Translation/Japanese.xlf
- GitUI/Translation/Korean.xlf
- GitUI/Translation/Polish.xlf
- GitUI/Translation/Portuguese (Brazil).xlf
- GitUI/Translation/Portuguese (Portugal).xlf
- GitUI/Translation/Romanian.xlf
- GitUI/Translation/Russian.xlf
- GitUI/Translation/Simplified Chinese.xlf
- GitUI/Translation/Spanish.xlf
- GitUI/Translation/Traditional Chinese.xlf
- GitUI/Translation/en_pseudo.Plugins.xlf
- GitUI/Translation/en_pseudo.xlf
- Settings moved from AdvancedSettings to Detailed
- Added some other options as requested by #3566
- Added a settings button to the diffviewer's toolbar as a quick access to the settings
- Defaulted the `rememberIgnoreWhiteSpacePreference` to true as I found most of my colleagues want to remember this option.
Fix #3566
> Remember diff viewer settings

- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/Editor/FileViewer.cs
To help pinpoint the issue in #3552.
As a developer using GitExtensions, I don't mind seeing the Stacktrace in the UI
> Display full exception message

- GitUI/CommandsDialogs/FormStash.cs
Show stash message in the dropdown (check the screenshot in issue #3401)
> Feature #3401 - named stashes

- GitExtensions.settings
since 'codebetter' has moved...
See: http://teamcity.codebetter.com/
> Update GitExtensions Teamcity settings

- GitExtensions.VS2013.sln
- GitExtensions.VS2015.sln
- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/UserControls/RevisionGrid.Designer.cs
- GitUI/UserControls/RevisionGrid.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorIntegration.csproj
- Plugins/BuildServerIntegration/AppVeyorIntegration/Properties/AssemblyInfo.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.Designer.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.resx
- Plugins/BuildServerIntegration/AppVeyorIntegration/app.config
- Plugins/BuildServerIntegration/AppVeyorIntegration/packages.config
- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
- Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerAdapter.cs
> AppVeyor CI plugin

- GitCommands/Settings/AppSettings.cs
> Use Path.Combine on GravatarCachePath

- GitExtensionsMono.sln
conemu-inside only has a "Default|Any CPU" configuration
> Fix mono build on linux

- GitCommands/Git/GitModule.cs
> Order branches

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/UserControls/FileStatusList.cs
> fix #3073 Need staged file count

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/GitUI.csproj
- GitUI/Script/PowerShellHelper.cs
- GitUI/Script/ScriptInfo.cs
- GitUI/Script/ScriptRunner.cs
If checked "Is Powershell", command is started through powershell.exe process.
If Run In Background checked, powershell is closed after finishing. If not,
powershell console is leaved for user to close manually or use the console for
running other powershell cmdlets and check the output of the powershell.
> Support for powershell scripts.

- .gitignore
- .travis.yml
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormPull.Designer.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
- Fixed mono build on Travis CI
- https://travis-ci.org/m08pvv/gitextensions
> Travis ci fixes

- GitExtensionsTest/GitUI/Objects/GitRemoteControllerTests.cs
As mentioned at #3615 
@m08pvv @jbialobr
> fix Travis CI build

- Setup/DownloadExternals.cmd
- Setup/Product.wxs
- Setup/UI/RequiredSoftwareDlg.wxs
Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)
- Update to Git 2.12.2
- GIT 2.12.2
- Windows 7
> Update to Git 2.12.2

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
>  	Feature #2460: Option to disable prompt when committing without a branch

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/FileStatusList.cs
Added setting that is off by default to open submodules with double click.
Added ability to open browse window to a specific commit message selected so that submodules open to the relevant commit.
> Issue 2706 Open submodules with double click in file lists

- GitUI/GitUIEventArgs.cs
- GitUI/Script/ScriptRunner.cs
- Plugins/GitUIPluginInterfaces/GitUIBaseEventArgs.cs
*)Allow to run a plugin with arguments from a script. This allows to add an menu item for a plugin to the revision grid its context menu.
*)Allow passing arguments to the plugin its Execute method. (So the script arguments can reach the plugin)
> Feature: Run plugin from scripts

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/SpellChecker/EditNetSpell.cs
> update the AutoComplete words while rescanning the changes

- GitUI/CommandsDialogs/FormRemotes.cs
- GitUI/Translation/English.xlf
Change labels:
- Enabled -> Active
- Disabled -> Inactive
Also update tooltips for toggle state button to provide better explanations.
> tweak labels and tooltips for FormRemotes

- GitCommands/Git/GitCommandHelpers.cs
- GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/Translation/English.xlf
- GitUI/Translation/French.xlf
- Add the possibility to change the merge message
- Add the possibility to automatically add the one line description from merged commit
I also would like to be able to save those settings, but i don't really know where :
- Add log : should be saved, in EffectiveSettings ?
- Nb log : the config setting merge.log can be used to change this value, but i don't know how to access it
- Add merge message : i don't think this option should be saved
> Allow to change merge message

- Setup/Product.wxs
> Remove unsupported VS  versions from installer.

- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
AppVeyorIntegration fails with several exceptions when working with no network connectivity.
> fix exceptions

- GitUI/Resources/ChangeLog.md
Reverts gitextensions/gitextensions#3614
> Revert "Make issue numbers in changelog hyperlinks"

- GitCommands/GitCommands.csproj
- GitCommands/packages.config
- GitExtensions/GitExtensions.Mono.csproj
- GitExtensions/GitExtensions.csproj
- GitExtensions/copy_plugins.sh
- GitExtensions/packages.config
- GitExtensionsTest/GitExtensionsTest.csproj
- GitExtensionsTest/packages.config
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorIntegration.csproj
- Plugins/BuildServerIntegration/AppVeyorIntegration/app.config
- Plugins/BuildServerIntegration/AppVeyorIntegration/packages.config
- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsIntegration.csproj
- Plugins/BuildServerIntegration/JenkinsIntegration/packages.config
- Plugins/BuildServerIntegration/TfsInterop.Vs2012/TfsInterop.Vs2012.csproj
- Plugins/BuildServerIntegration/TfsInterop.Vs2012/packages.config
- Plugins/BuildServerIntegration/TfsInterop.Vs2013/TfsInterop.Vs2013.csproj
- Plugins/BuildServerIntegration/TfsInterop.Vs2013/packages.config
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsHelper2015.cs
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/app.config
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/packages.config
- Plugins/Gerrit/Gerrit.csproj
- Plugins/Gerrit/packages.config
- Plugins/Stash/Stash.csproj
- Plugins/Stash/StashRequestBase.cs
- Plugins/Stash/packages.config
- ResourceManager/ResourceManager.csproj
- ResourceManager/packages.config
- Setup/Product.wxs
- Updates Several Dependencies(Except for NUnit & System.IdentityModel.Tokens.Jwt, Compatibility Issues)
- Tested by Running in a Normal Environment (Git Extensions is my Main Tool for GitHub)
- .Net Framework 4.6.2 and Above
Related PRs:
- Externals/Git.Hub - PR Will be Available Soon
> Updates Dependencies (REUPLOAD)

- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.resx
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.resx
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.resx
* ChecklistSettingsPage
* GitConfigSettingsPage
* SshSettingsPage
Addresses some of the issues raised in #3673
--------
**ChecklistSettingsPage** 
* current at 150% scaling with font size +2
* fixed at 150% scaling with font size +2
* fixed at 100%
------
**GitConfigSettingsPage**
* current at 150% scaling with font size +2
* fixed at 150% scaling with font size +2
* fixed at 100%
-----
**SshSettingsPage**
* current at 150% scaling with font size +2
* fixed at 150% scaling with font size +2
* fixed at 100%
> fix: Layout for various settings pages

- GitPlugin/Connect.cs
@jbialobr  Just fixed the build failure
> Build failure due to moving of AllowCaptionUpdate to PluginHelpers

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardCategory.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.cs
- Applying docks so category title won't get cut on high dpi and image will be centrally aligned. 
- Stretching an image, so it won't get smaller with higher dpi. 
- Hovering while over entire DashboardItem and avoid flickering.
http://imgur.com/TaC0f6M
http://imgur.com/7PdhRTc
> Better high dpi support and some niceifications

- Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/app.config
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/packages.config
Signed-off-by: CDAGaming <cstack2011@yahoo.com>
> Updates Dependencies & TfsInterop.Vs2015 to .Net Framework 4.5.2

- Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
- Plugins/BuildServerIntegration/TfsInterop.Vs2015/packages.config
Signed-off-by: CDAGaming <cstack2011@yahoo.com>
> Update WindowsAzure.ServiceBus to v4.1.1

- GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
... using the menu or shortcut "Ctrl+O" (and not the link in the dashboard)
> fix crash when opening repository from dashboard

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
- GitUI/CommandsDialogs/FormBrowse.cs
> Open Transifex website for translation

- GitUI/CommitInfo/CommitInfo.cs
Fixes #3729
@l-inc could you please verify that it works for you
> fix mono crash on an attempt to "Copy commit info"

- GitUI/CommandsDialogs/AboutBox.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
- GitUI/CommandsDialogs/BrowseDialog/FormDonate.cs
Just code clean up. no functionality change.
> Code clean up for the donate url

- appveyor.yml
> fix WiX version

- Setup/Product.wxs
> fix: Missing Newtonsoft.Json

- Setup/README.md
This should resolve #2259.
Original work was done by @mindw in https://github.com/gitextensions/gitextensions/pull/2782
@KindDragon @jbialobr is there anything else worth adding?
> Update Setup/README.md with more accurate build instructions

- GitUI/CommandsDialogs/FormBrowse.cs
> Delete index.lock in submodules

- GitUI/CommandsDialogs/FormReflog.Designer.cs
- GitUI/CommandsDialogs/FormReflog.cs
to be able to revert a `--force-with-lease` more easily, if needed...
> Reflog: display also reflog for remotes

- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
> fix: NRE when jira plugin not configured

- GitExtensions/Program.cs
> Removed incorrectly parsed ". 

- .github/ISSUE_TEMPLATE.md
Fixes # .
- Fixed space issue in MD
> Editor removed spaces after -

- GitUI/CommandsDialogs/FormCommit.cs
Creating new branch through "Create Branch" from commit window is now reflected in the window's title.
Fixes #3982
> fix: Commit window title reflect new branch

- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
> fix: Make 'Check for update' form topmost

- GitUI/FilterBranchHelper.cs
> Replaced contains with IndexOf fixing the issue #4014

- GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
"Merge Branch" form now behaves the same way on Linux as on Windows.
Fixes #3725
Screenshots:
- Ubuntu 17.04
> fix: "Merge Branch" Mono layout

- .travis.yml
Attempt to run tests on travis
> Tests on travis

- .travis.yml
https://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI
> Imitate a display.

- UnitTests/GitCommandsTests/Git/GitBranchNameNormaliserTest.cs
- UnitTests/GravatarTests/DirectoryImageCacheTests.cs
> fix selected unit tests under Mono

- GitCommands/FullPathResolver.cs
- GitCommands/GitCommands.csproj
- UnitTests/GitCommandsTests/FullPathResolverTests.cs
- UnitTests/GitCommandsTests/GitCommandsTests.csproj
Resolves the provided path (folder or file) against the current working directory.
> feat: Extract full path resolution

- TranslationApp/TranslationHelpers.cs
- Simplify translated value check
- GIT 2.14.2
- Windows 10
> Simplify translated value check

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- Fix potential copy-paste bug
Not really sure about this as I don't use this feature, but it looks like copy-paste bug.
> Fix potential copy-paste bug

- Plugins/Statistics/GitStatistics/CodeFile.cs
- basic support for Matlab `*.m` files
#3956 partially implemented
> added *.m for Matlab files

- GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs
- GitUI/UserControls/FolderBrowserButton.Designer.cs
> fix: Invisible "Browse" button in "Open repository" dialog

- GitUI/UserControls/RevisionGrid.cs
> Tasks should use the instance of GitModule captured while being created.

- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.csproj
- Plugins/JiraCommitHintPlugin/app.config
- Plugins/JiraCommitHintPlugin/packages.config
@ierof do you see any dramas with the upgrade?
> chore: Consolidate Newtonsoft.Json versions

- README.md
> chore: Reformat readme

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
> chore: FormBrowse code cleanup

- GitUI/Editor/FileViewer.cs
Fixes #4160
Manually performed the repro steps provided in the fixed issue.
> Unbind PostSettings on disposing. 

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/UserControls/FileStatusList.cs
As requested in https://github.com/gitextensions/gitextensions/commit/79276996ef15776def1ff443d0f758407d09d9b3
- Verified that staged count renders properly.
> Minor improvements

- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildDurationFormatter.cs
**Changes proposed in this pull request:**
- The project name is removed
- The build status is last for it is already indicated by color and icon.
- The build duration added
**Screenshots before and after (if PR changes UI):**
Before
After
> Jenkins integration - show more interesting data first.

- Setup/MakeMonoArchive.cmd
Fixes #3839
Has been tested locally
> fix: Add GitFlow to Mono setup

- Plugins/ReleaseNotesGenerator/GitLogLineParser.cs
- Plugins/ReleaseNotesGenerator/LogLine.cs
- Plugins/ReleaseNotesGenerator/ReleaseNotesGenerator.csproj
- Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.Designer.cs
- Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.cs
- UnitTests/Plugins/ReleaseNotesGeneratorTests/GitLogLineParserTests.cs
- UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj
Rework how the git log data is parsed to produce release notes.
Fixes #4028
> fix: Release Notes Generator hash length bug

- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
> chore: Fix layout and naming in AppearanceSettingsPage

- GitUI/CommandsDialogs/RevisionDiff.cs
- GitUI/UserControls/RevisionGrid.cs
- ResourceManager/GitExtensionsUserControl.cs
> Remove duplicate hotkeys code

- GitCommands/CommitData.cs
- GitCommands/CommitDataManager.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitSubmoduleStatus.cs
- GitCommands/GitCommands.csproj
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/UserControls/RevisionGrid.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- ResourceManager/CommitInformation.cs
- ResourceManager/LocalizationHelpers.cs
- UnitTests/GitCommandsTests/CommitDataManagerTest.cs
- UnitTests/GitCommandsTests/CommitInformationTest.cs
- UnitTests/GitCommandsTests/GitCommandsTests.csproj
One of several refactor iterations before fulfilling #4237
> refactor: Split state and behavior of CommitData

- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
I've looked through the diff and it seems to be expected
> Update English translations for v2.51

- GitUI/CommandsDialogs/FormDeleteRemoteBranch.resx
- GitUI/CommandsDialogs/FormPull.cs
- Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.cs
https://www.transifex.com/git-extensions/git-extensions/translate/#nl/ui-master/129793268
https://www.transifex.com/git-extensions/git-extensions/translate/#de/plugins-master/129793089
https://www.transifex.com/git-extensions/git-extensions/translate/#de/plugins-master/129793096
> Issues reported on transifex.

- GitUI/CommitInfo/CommitInfo.cs
Fixes #4255
How did I test this code: manual
> fix: Intermittent NRE for _commitInformationProvider

- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
> Update English translations for v2.51 Rev #1

- GitUI/CommandsDialogs/FormClone.cs
Clone will now not proceed if destination path is either:
- not supplied, or
- not absolute, or
- anyhow not valid for the target platform
Closes #1605
What did I do to test the code and ensure quality: ran it locally with various inputs. Unit tests necessitate a refactor, TBD. 
- GIT 2.12 and above
- Windows 10
- Ubuntu 17.04
> fix: Show error if clone destination invalid

- GitUI/CommandsDialogs/FormBrowse.cs
> Hide Panel2 for toggleSplitViewLayout action. 

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs
- GitUI/GitUICommands.cs
Closes #4296.
The Commit & Push button is rendered in red when it will push forced with lease.
> Push forced with lease when Commit & Push action is performed with Amend option checked.

- UnitTests/GitCommandsTests/GitCommandsTests.csproj
- UnitTests/GitCommandsTests/GitExtLinks/ExternalLinksParserTests.cs
- UnitTests/GitCommandsTests/GitExtLinks/MockData/level1_GitExtensions.settings.xml
- UnitTests/GitCommandsTests/GitExtLinks/MockData/level2_GitExtensions.settings.xml
- UnitTests/GitCommandsTests/GitExtLinks/MockData/level3_GitExtensions.settings.xml
In preparations for a refactor test the existing functionality
> Add tests for ExternalLinksParser

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/UserControls/RevisionGrid.cs
* create tag (ctrl+ t)
* create branch (ctrl + b)
* close repository (ctrl + w)
> Display some missing shortcuts in Browse form menus

- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
Closes #4202
This is rewrite of how the plugin works
Previously the builds in a job were fetched first, then each individual build. Due to the implementation, the same info were retrieved many times. The stability were not good, not showing information often for bigger setups.
This has been changed to retrieve all builds with one request. If there are InProgress builds, all builds are fetched again, otherwise there is a check if there are new builds started on the server.
- More efficient retrieval of build data
* Get all builds in one request
* More efficient way to check if there has been new builds
* More efficient caching when switching between repos
- Avoid requesting the same info several times (made worse by the 2.51 changes) 
- Multibranch …
> Jenkins multibranch pipeline support, cleanup

- GitUI/FilterBranchHelper.cs
The "Branches" drop down combo box does not work when more than one branch is listed (separated with spaces).
The error occured while attempting to read the text from the dropdown when it had no items in the list.
Fixes #4370
- ran it manually in various scenarios comparing with 2.50 version
Steps to reproduce:
* type "master" and hit Enter - this filters the branch list to master branch only
* add one or two spaces after "master" -> "master  " and hit Enter - at this stage I typically get AOORE because the dropdown has no items in it (all filtered out) and we are accessing `dropdown.Text` property which throws the exception
- Windows 8.1
> fix: Branch filtering not working

- Plugins/Bitbucket/BitbucketPullRequestForm.Designer.cs
- Plugins/Bitbucket/BitbucketPullRequestForm.cs
- Plugins/Bitbucket/GetUserRequest.cs
Review comment for #4433. The user/reviewer handling is not implemented. This PR removes the code, including hidden UI elements.
No functionality changes
- Windows 10
> Remove unused user handling code

- Plugins/Bitbucket/BitbucketPullRequestForm.Designer.cs
- Plugins/Bitbucket/BitbucketPullRequestForm.cs
Comment for #4433
No functionality change
- Windows 10
> Rename labels etc with anonymous names

- GitUI/CommandsDialogs/FormRemotes.cs
Since 2.50 user remotes are no longer persisted in the config.
The regression was introduced during the refactor of the `FormRemotes` in 613335552bf0735080e442629da1b71b99551d53
Restore the ability to save new or changed remotes by ensuring they are added to the collection whenever 'Save' button is clicked.
This will allow saving remotes for new and currently configured remotes.
Deletion of remotes is still absent and requires further thoughts.
Deleting a remote from the history list may be undesirable as it would hinder user's ability to *quickly* clone the remote repository.
The flipside is that the history list may grow long without a UI to manage it.
Fixes #4441
> fix: Remotes not persisted

- Setup/MakePortableArchive.cmd
Resolves #4462
- Manual build
- Windows 10
> Portable archive referenced removed Mono file from #4430

- GitCommands/SynchronizedProcessReader.cs
- Replace creation of two new threads for each external process, instead scheduling lightweight `Task`s on the thread pool. Creating threads is a relatively costly operation and they serve no purpose here that cannot be served by tasks.
- Use `StreamReader.ReadToEndAsync` and `Stream.CopyToAsync` to take advantage of async IO (completion ports, etc) provided by the underlying platform.
- Document changed API methods.
- Reduce the amount of code.
- Contain the changes to one class, allowing for easier review. There should be no visible change outside of this class, other than things running faster and using fewer kernel resources.
- Windows 10
> Improve SynchronizedProcessReader performance

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
> Don't try to resize null images. 

- GitCommands/SynchronizedProcessReader.cs
Reverts gitextensions/gitextensions#4474
> Revert "Improve SynchronizedProcessReader performance"

- Setup/MakePortableArchive.cmd
Resolves #4466
Tfs plugin is not included
- Include missing pluginsin archive
- Build the portable archive.
No tests with the portable zip
- Windows 10
> Add missing plugin files to the portable archive

- GitUI/CommandsDialogs/FormSubmodules.Designer.cs
(cherry picked from commit 5666b31d092f4320d1738a323427c3710a952744)
Fixes #1858
Cherry-picked fro 2.51 branch
> Align submodule details. Fixes #1858 (#4506)

- GitUI/CommandsDialogs/RevisionDiff.cs
Fixes #4485
Regression in 2.51
- Manual tests
- Windows 10
> Find in files is not finding all occurrences

- GitUI/CommandsDialogs/RevisionFileTree.cs
cherry picked from commit 4f560a54c8c7d2cdfd4ca5d76c5757a3982ef100, #4538
Fixes #4535 
- Manual tests
- GIT 2.16
- Windows 10
> Reset folder in file tree regression in 2.51

- GitUI/CommandsDialogs/RevisionDiff.cs
- GitUI/Editor/FindAndReplaceForm.cs
> Handle OperationCanceledException. 

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
Regression from #4390
Fixes #4390
- Manual tests
> No Opening EventHandler called for Commit Unstaged Menu

- GitCommands/ExceptionUtils.cs
- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormAddFiles.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RepoHosting/DiscussionHtmlCreator.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/Editor/FileViewer.cs
- GitUI/FormStatus.cs
- GitUI/GitUICommands.cs
- GitUI/ProcessOutputTimer.cs
- GitUI/UserControls/RevisionGrid.cs
- NetSpell.SpellChecker/Spelling.cs
- Plugins/Gerrit/FormGerritDownload.cs
- Plugins/Gerrit/GerritPlugin.cs
- Plugins/ReleaseNotesGenerator/HtmlFragment.cs
Single commit extracted from PR #4615 on request of @sharwell for separate review.
- Reduce the number of method overloads by using default parameter values
- Manual review of changes (largely automated)
- Unit tests
- GIT 2.16
- Windows 10
> Merge overloads via default parameter values

- GitUI/CommandsDialogs/FormCreateTag.Designer.cs
- GitUI/CommandsDialogs/FormCreateTag.cs
Fixes #2515
- GIT 2.16.1.2 and above
- Windows 10
- Ubuntu 17.04
> fix: FormCreateTag tab order

- GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs
Code has the same behaviour, but will allocate a lot less memory. It's ~60% faster too, but was already quite snappy.
Previous implementation allocated a new `List<string>` for every control in the tree.
- Replace recursion with iteration
- GIT 2.16
- Windows 10
> Replace recursion with iteration

- GitUI/CommandsDialogs/BrowseDialog/FormGitLog.cs
- Pass the currently-unused `IWin32Window owner` parameter to `Show`
- Convert set/read/set to just set for a control's Text property (set causes layout)
- GIT 2.16
- Windows 10
> FormGitLog tweaks

- GitUI/CommandsDialogs/FormCommit.cs
> Fix enum numbering. 

- GitCommands/Git/GitItemStatus.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/ConfigFileSettingsCache.cs
- GitCommands/Settings/GitExtSettingsCache.cs
- GitPluginShared/Commands/Commit.cs
- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/CommandsDialogs/BrowseDialog/MenuCommandsBase.cs
- GitUI/CommandsDialogs/FormCreateTag.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- GitUI/CommandsDialogs/SettingsDialog/SettingsPageHeader.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitExtensionsForm.cs
- GitUI/Script/SplitButton.cs
- GitUI/SpellChecker/SpellCheckEditControl.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGrid.cs
- Plugins/Bitbucket/BitbucketRequestBase.cs
- Plugins/CreateLocalBranches/CreateLocalBranchesPlugin.cs
- Plugins/Statistics/GitStatistics/LineCounter.cs
- Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs
- Plugins/Statistics/GitStatistics/PieChart/PieSlice.cs
- ResourceManager/GitExtensionsFormBase.cs
- ResourceManager/GitExtensionsUserControl.cs
- ResourceManager/Xliff/TranslationUtl.cs
- UnitTests/GitCommandsTests/FileAssociatedIconProviderTests.cs
- UnitTests/GravatarTests/DirectoryImageCacheTests.cs
Clearing up some old branches from my repo...
- A `Graphics` object was not being disposed when measuring text
- Various syntactical simplifications
- Removed some redundancies (assignments, directives, specifiers)
- Use `EventArgs.Empty` over `new EventArgs()`
- Replace `ArrayList` with `List<T>`
- `TimeSpan.FromSeconds(2)` over `new TimeSpan(0, 0, 0, 2)`
- Unit tests
- GIT 2.16
- Windows 10
> Misc tidying

- CommonAssemblyInfo.cs
- GitExtSshAskPass/SshAskPass.rc2
- GitExtensionsShellEx/GitExtensionsShellEx.rc
- GitUI/Properties/Resources.resx
- GitUI/Resources/ChangeLog.md
- Setup/DownloadExternals.cmd
- Setup/Generate-Changelog.ps1
- Setup/MakeInstallers.cmd
- Setup/MakeMonoArchive.cmd
- Setup/Product.wxs
* Update versions
* Update changelog
* Update contributors
> Update to 2.51.01

- GitCommands/Git/GitBlame.cs
- GitCommands/Repository/Repository.cs
- GitUI/CommandsDialogs/AboutBox.Designer.cs
- GitUI/CommandsDialogs/AboutBox.cs
- GitUI/CommandsDialogs/BrowseDialog/FormCommitCount.cs
- GitUI/CommandsDialogs/FormApplyPatch.Designer.cs
- GitUI/CommandsDialogs/FormApplyPatch.cs
- GitUI/CommandsDialogs/FormCheckoutRevision.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutRevision.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/FormViewPatch.Designer.cs
- GitUI/CommandsDialogs/FormViewPatch.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/CommandsDialogs/SettingsDialog/RepoDistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs
- GitUI/Editor/FindAndReplaceForm.cs
- GitUI/Editor/FormGoToLine.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/RevisionGridClasses/DvcsGraph.Graph.cs
- GitUI/UserControls/RevisionGridClasses/DvcsGraph.Lanes.cs
- ResourceManager/GitPluginBase.cs
- UnitTests/GitCommandsTests/Git/GitBlameHeaderTest.cs
- Delete empty event handlers
- Delete unused private code
- Remove redundant ToString calls
- Add some annotations that help R# understand dynamic type loading
- Unit tests
- GIT 2.16
- Windows 10
> Delete unused code

- Setup/Product.wxs
> Add Microsoft.VisualStudio.Threading dependencies to installer

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
> [WIP] Update submodules to use vs-threading

- GitCommands/ArgumentBuilder.cs
- GitCommands/ArgumentBuilderExtensions.cs
- GitCommands/Git/GitCommandHelpers.cs
- GitCommands/Git/GitModule.cs
- GitCommands/GitCommands.csproj
- GitCommands/PathUtil.cs
- GitUI/CommandsDialogs/FormApplyPatch.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/GitUICommands.cs
- UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs
- UnitTests/GitCommandsTests/ArgumentBuilderTests.cs
- UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
- UnitTests/GitCommandsTests/GitCommandsTests.csproj
- UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes #4661.
- Add new `ArgumentBuilder` class, with API docs and tests
- Use new class in places where argument construction logic was non-trivial
- Added unit tests for `ArgumentBuilder`
- Unit tests
- Manual tests
The unified diff makes 33f483c a bit hard to read. Easiest to review in the side-by-side view if you have a wide enough screen.
- GIT 2.16
- Windows 10
> Introduce ArgumentBuilder

- GitCommands/GitCommands.csproj
- GitExtUtils/GitExtUtils.csproj
- GitExtensions/GitExtensions.csproj
- GitExtensionsVSIX/GitExtensionsVSIX.csproj
- GitPlugin/GitPlugin.csproj
- GitPluginShared/GitPluginShared.csproj
- GitUI/GitUI.csproj
- Gravatar/Gravatar.csproj
- NetSpell.SpellChecker/SpellChecker.csproj
- Plugins/AutoCompileSubmodules/AutoCompileSubmodules.csproj
- Plugins/BackgroundFetch/BackgroundFetch.csproj
- Plugins/CreateLocalBranches/CreateLocalBranches.csproj
- Plugins/DeleteUnusedBranches/DeleteUnusedBranches.csproj
- Plugins/FindLargeFiles/FindLargeFiles.csproj
- Plugins/GitFlow/GitFlow.csproj
- Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
- Plugins/Gource/Gource.csproj
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.csproj
- Plugins/ProxySwitcher/ProxySwitcher.csproj
- Plugins/ReleaseNotesGenerator/ReleaseNotesGenerator.csproj
- Plugins/Statistics/GitImpact/GitImpact.csproj
- Plugins/Statistics/GitStatistics/GitStatistics.csproj
- ResourceManager/ResourceManager.csproj
- TranslationApp/TranslationApp.csproj
- UnitTests/GitUITests/GitUITests.csproj
- UnitTests/GravatarTests/GravatarTests.csproj
Remove many items and properties from project files which are no longer used.
> Cleanup project files

- UnitTests/GitUITests/CancellationTokenSequenceTests.cs
Increase the number of runs, even if there is only one core, the test can fail if the ThreadMethod's ifs are incorrect.
> Move Inconclusive to the end in order to let the test be run on CI.

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/FormProcess.cs
- GitUI/FormStatus.cs
- GitUI/UserControls/RevisionGrid.cs
- Plugins/Bitbucket/BitbucketPullRequestForm.cs
- Plugins/Bitbucket/BitbucketRequestBase.cs
- Plugins/FindLargeFiles/FindLargeFiles.csproj
- Plugins/FindLargeFiles/FindLargeFilesForm.cs
* Use `JoinableTaskFactory` instead of `QueueUserWorkItem`
* Use `JoinableTaskFactory.Run` instead of `Control.Invoke`
* Use `JoinableTaskFactory.RunAsync` instead of `Control.BeginInvoke`
> Prefer JoinableTaskFactory to other Invoke styles

- GitExtUtils/GitUI/ControlThreadingExtensions.cs
- GitUI/CommandsDialogs/BrowseDialog/FormCommitCount.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/SpellChecker/EditNetSpell.cs
- UnitTests/GitUITests/ControlThreadingExtensionsTests.cs
@drewnoakes This addresses the limitation you observed in the past
> Allow a CancellationToken for SwitchToMainThreadAsync

- UnitTests/GitUITests/CancellationTokenSequenceTests.cs
Threads accessed the barrier after its disposal causing ODE.
As requested in #4763.
> Test should wait for background activity to finish

- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
- Tested manually a happy path.
- GIT 2.15
- Windows 10
> Convert continuations to async/await in JenkinsAdapter

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Apply vs-threading.
Fixes #4819.
- GIT 2.15
- Windows 10
> Cancel background tasks on disposing. 

- Setup/MakePortableArchive.cmd
> fix Appveyor artifacts

- GitUI/CommandsDialogs/FormBrowse.cs
- If ROT panel is hidden, it does not make sense to reload ROT. 
> Reload ROT only when visible.

- GitCommands/Git/GitModule.cs
- GitCommands/Patches/PatchProcessor.cs
- UnitTests/GitCommandsTests/Patches/PatchProcessorTest.cs
Fixes #4827 
- Correctly identify a combined diff
- Add some more contract annotations
- Improve parsing logic for clarity, reliability and perf
- GIT 2.16.2
- Windows 10
> Fix patch header parse bug

- GitUI/CommandsDialogs/FormCommit.cs
- Setup/BuildInstallers.cmd
- Setup/MakePortableArchive.cmd
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
- UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
- UnitTests/GitUITests/GitUITests.csproj
- UnitTests/GitUITests/UITest.cs
I added some notes to the review which are relevant to how this expands from testing a single form to testing many.
> Initial FormCommit tests

- GitCommands/Git/GitVersion.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
- GitUI/Translation/Czech.xlf
- GitUI/Translation/Dutch.xlf
- GitUI/Translation/English.xlf
- GitUI/Translation/French.xlf
- GitUI/Translation/German.xlf
- GitUI/Translation/Italian.xlf
- GitUI/Translation/Japanese.xlf
- GitUI/Translation/Korean.xlf
- GitUI/Translation/Polish.xlf
- GitUI/Translation/Portuguese (Brazil).xlf
- GitUI/Translation/Portuguese (Portugal).xlf
- GitUI/Translation/Romanian.xlf
- GitUI/Translation/Russian.xlf
- GitUI/Translation/Simplified Chinese.xlf
- GitUI/Translation/Spanish.xlf
- GitUI/Translation/Traditional Chinese.xlf
- GitUI/Translation/en_pseudo.Plugins.xlf
- GitUI/Translation/en_pseudo.xlf
Check for recommended Git version
(cherry picked from commit 9e7808f60ead6c3b9861fb56a6e06caa0eda8dc1)
See #4929, no changes for 2.51
> Check for recommended Git version 2.51

- GitUI/GitUI.csproj
- GitUI/UserControls/ExListView.cs
- GitUI/UserControls/ListViewGroupMouseEventArgs.cs
Allow raising events whenever a listview group is clicked.
> Enhance ExListView allow group right click

- GitExtensionsVSIX/Commands/CommandBase.cs
- GitExtensionsVSIX/Commands/Commit.cs
- GitExtensionsVSIX/Commands/FindFile.cs
- GitExtensionsVSIX/Commands/ItemCommandBase.cs
- GitExtensionsVSIX/Commands/ToolbarCommand.cs
- GitExtensionsVSIX/Commands/VsixCommandBase.cs
- GitExtensionsVSIX/GitExtCommands.cs
- GitExtensionsVSIX/GitExtensionsPackage.cs
- GitExtensionsVSIX/GitExtensionsVSIX.csproj
- GitExtensionsVSIX/PluginHelpers.cs
> Transition to AsyncPackage

- GitUI/UserControls/RevisionGridClasses/DvcsGraph.Graph.cs
Fixes #4971
- Replace recursion on the stack with iteration over a queue
- Windows 10
> Replace recursion with iteration for branch highlight

- GitCommands/Git/GitModule.cs
Fixes #5013
Set as wip, this could be solved in other ways.
- Manual test, see issue
- Windows 10
> Nullexception for empty diff

- GitCommands/RevisionReader.cs
Fixes #5018.
This was a regression that stopped the the multi-line indicator appearing in the revision grid, for those users who have the setting enabled. It would also have broken certain kinds of revision filtering.
- Fix code that failed to read the git revision's body
- Avoid double-allocation of string when commit message is single line (subject only) by re-using string object for both properties
- Windows 10
> Fix calculation of HasMultiLineMessage

- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
- ResourceManager/GitExtensionsUserControl.cs
Part of #5038
- Minor changes to Jenkins plugin, checks
-n/a
- Manual tests, Mono or builds.apache.org has public Jenkins servers (also multibranch pipeline)
> Jenkins minor tweaks

- Plugins/Gerrit/GerritPlugin.cs
Fixes #3512
- Try to create the .git/hooks folder if missing. Should any problems occur during folder creation, display a message and exit the installation flow.
- gave variables explicit names
- extracted constants
- simulated exception being thrown upon folder creation to visualize message and ensure flow exit
- GIT 3.00
- Windows 10
> Try to create .git/hooks folder if missing

- Plugins/BuildServerIntegration/VstsAndTfsIntegration/Settings/VstsAndTfsSettingsUserControl.Designer.cs
- Plugins/BuildServerIntegration/VstsAndTfsIntegration/TfsApiHelper.cs
- Plugins/BuildServerIntegration/VstsAndTfsIntegration/VstsAndTfsAdapter.cs
Next step after #4974
- Perfs: Use provided BuildDefinition Api filtering and fallback on pure regex if no build definitions found
- refactoring/cleaning
Info: review will be easier if done commit by commit
/cc @afabre
> Improve Vsts tfs rest plugin

- GitCommands/Git/GitVersion.cs
Fixes #
- Set recommended Git version to the latest released that has some security fixes
Wiki to be updated too
- Some manual use of release/2.51 branch, used in master since release 
- GIT 2.17.1
> Set recommended version Git version to 2.17.1

- GitCommands/Git/GitDeleteRemoteBranchesCmd.cs
Fixes #5119 
- Git 2.17.1
- Windows 10
> Fix remote branch delete error

- GitCommands/StringPool.cs
Relates to #5088
- See discussion in #5088.
- GIT 2.18.0.windows.1
- Windows 10
> Fix bug in StringPool

- GitUI/CommandsDialogs/FormBrowse.cs
Add plugin menu entries only if they are missing.
Fixes #5112
- manual tests that involves opening, closing and changing repositories
> fix: Plugin menu entries are repeated many times

- Setup/MakePortableArchive.cmd
Fixes #5165
- Include `System.ValueTuple` in archive
- Manual review. Will test build output once available.
> Include System.ValueTuple in portable archive

- GitUI/Resources/ChangeLog.md
> Update the master changelog with 2.51.03 and 2.51.04

- GitCommands/Git/GitModule.cs
Fixes #5179
- Add --no-show-signature option to log calls
- Signed a commit and made sure it showed in revision grid.  
- Verified log calls were not broken
- GIT 2.18 and above
> Provide capability to generate git -c calls in git commands

- GitUI/CommandsDialogs/FormBrowse.cs
Attempting to launch an app located outside a git repository failed.
Fixes #5244
- manual tests running the app from a folder without a .git folder
- manual tests running the app from a folder with a .git folder
> fix: Unable to start the app

- GitCommands/Git/GitModule.cs
- GitCommands/GitRevisionInfoProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormMergeSubmodule.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/SuperProjectInfo.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- Plugins/Statistics/GitStatistics/FormGitStatistics.cs
- UnitTests/GitCommandsTests/GitRevisionInfoProviderTests.cs
Part two from #5234
- Wider use of ObjectId
- Manual tests
- GIT 2.18
- Windows 10
> 5234 part 2

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormMergeSubmodule.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/FormStatus.cs
Part five from #5234
- Change FormStatus.ctor to fit usage
- Manual tests
- GIT 2.18
- Windows 10
> 5234 part 5

- GitUI/CommandsDialogs/FormCommit.cs
> fix: Unable to stage in empty repo

- GitUI/CommandsDialogs/FormSubmodules.Designer.cs
Fixes #5280
- Fix a broken data binding path
- Manual tests
- GIT 2.18
- Windows 10
> Fix broken data binding path

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- Change a single word in a user-facing message. 
> Tweak message about removing recent repo

- GitCommands/Git/GitModule.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowse.resx
- GitUI/CommandsDialogs/FormPull.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/GitUICommands.cs
- Centralise pull behavior and remove per-repository pull behavior
- Reorder pull menu
- Rename `FormPullAction` to `DefaultPullAction`
- before
- after
- manually
> Next selection as default

- README.md
- update Visual Studio version in README.md according to #5286
- n/a
- GitHub with Firefox
> Updated Visual Studio version in README.md

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
1. Whenever a repository opened the graph would refresh **3 times**
- First the graph would be refreshed via `_greidView.ClearSelection` call that would trigger `DataGridView.OnSelectionChanged` event handler
- Second time the graph would be refreshed via `_gridView.Refresh()` call
- Third time around it would be refreshed whenever revisions data finished loading (`OnRevisionReadCompleted`) and set the initial revision, that would trigger `DataGridView.OnSelectionChanged` event handler
2. Whenever a different repository was opened the graph would refresh **4 times**
- The graph would be refreshed in response to `UICommands_PostRepositoryChanged`
- Then the graph would be refreshed via `_greidView.ClearSelection` call that would trigger `DataGridView.OnSelectionChanged` event handler
- …
> Reduce number of graph refreshes

- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitSubmoduleStatus.cs
Resolves #5366
- Eliminates exception
- See issue for exception
- See issue for testing instructions
- Windows 10
> A removed submodule raised an Exception

- UnitTests/GitCommandsTests/UserRepositoryHistory/RemoteRepositoryManagerTests.cs
Copied from the LocalRepositoryManagerTests
> Make the test independent on the user's settings.

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
Fixes #5330
- Add tooltips to Pull button Fetch actions
> Set tooltips for Fetch options under Pull button

- GitUI/CommandsDialogs/FormPull.cs
Fixes #5411
- See issue
- see issue
-
- Open FormPull
- Windows 10
> FormPull: Set fetch as default

- GitUI/UserControls/MainThreadScheduler.cs
> Avoid throwing a cancellation exception in MainThreadScheduler

- GitCommands/GitCommands.csproj
- GitCommands/Submodules/DetailedSubmoduleInfo.cs
- GitCommands/Submodules/SubmoduleInfo.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #5386.
- Tested manually.
- GIT 2.18
- Windows 10
> Wait for collecting submodules info to be finished.

- GitUI/FormProcess.cs
> fix: Console window cannot be closed with the Escape key

- GitCommands/Git/GitCommandHelpers.cs
It causes a failure of the assert inside of GitItemStatus.Staged.
> StagedStatus.Unknown is an invalid status.

- UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Fixes #5496
- Set `Environment.CurrentDirectory` to a defined state. To be exact: the Assembly location will be used.
- Ran all the automatic tests again
- Windows 10 1803 64 Bit
> Fix issue  #5496

- GitCommands/Submodules/SubmoduleStatusProvider.cs
Follow up to https://github.com/gitextensions/gitextensions/pull/5375#issuecomment-418643960
- Throttle submodule update due to background changes ("commit status updates")
This limits the maximum load from the submodule updates, that could be a regression to #5375 in some situations when Browse was always the window with focus (#5375 is generally a big improvement though) _and_ you repeatedly click the submodule dropdown. This changes the maximum update frequency from 3s to 15s.
The implementation to get submodule status in #5430 is smooth, so the submodule update should not have a big impact, but this is at least annoying when debugging.
Note: As the status is updated at explicit changes in GE, it would not be a major limitation to increase the …
> Browse: Throttle submodule status updates

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
fixes #5439
fixes #4256
partly based on #5429
The handling was improved in #4327, #4328, fixing the regression
Those PRs limited the max load for git-status
Changes:
React faster on changing directory (1.0s->0.2s)
Some tweaks to the checks, do not check if update is required if an update is already scheduled
Do not read ignored files due to two problems:
* Reading ignored can takes significant time. Since this was done the first time, the first update was delayed.
(Reading ignored could be done later, but this will still delay the next update).
* Saving all seen ignored files require substantial memory, see #4256.
The list could be limited (see the issue), but that will increase the test time for ignored files
As ignored files will now always trigger git-status may cause some more runs. …
> GitStatusMonitor tweaks

- GitUI/CommitInfo/CommitInfo.cs
- Use CancellationTokenSequence to ensure the data loaded asynchronously is still relevant.
> Prevent showing async loaded data for a revision it was not loaded for.

- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewer.resx
- GitUI/Editor/FileViewerInternal.cs
- GitUI/Editor/IFileViewer.cs
- GitUI/GitUIExtensions.cs
- Add `FileViewerInternal` to designer view - this will allow changes to the `FileViewer` to be made easier
> Add file viewer internal to designer view

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Translation/Czech.xlf
- GitUI/Translation/Dutch.xlf
- GitUI/Translation/English.xlf
- GitUI/Translation/French.xlf
- GitUI/Translation/German.xlf
- GitUI/Translation/Italian.xlf
- GitUI/Translation/Japanese.xlf
- GitUI/Translation/Korean.xlf
- GitUI/Translation/Polish.xlf
- GitUI/Translation/Portuguese (Brazil).xlf
- GitUI/Translation/Portuguese (Portugal).xlf
- GitUI/Translation/Romanian.xlf
- GitUI/Translation/Russian.xlf
- GitUI/Translation/Simplified Chinese.xlf
- GitUI/Translation/Spanish.xlf
- GitUI/Translation/Traditional Chinese.xlf
- GitUI/Translation/en_pseudo.Plugins.xlf
- GitUI/Translation/en_pseudo.xlf
because they are not pulls and that could be confusing...
> Remove "Pull - " in tooltips for fetch actions

- GitUI/CommandsDialogs/FormCommit.cs
> Reflect the fact that the diff is reloaded in the form state.

- GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
> Fix branches and tags copying.

- GitUI/CommandsDialogs/FormDiff.cs
fixes #5598 
However, there are likely more issues
n/a
- Manual test 
- Windows 10
> FormDiff: Check for Artificial commits before calling merge-base

- GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
- ResourceManager/Strings.cs
- UnitTests/GitUITests/GitUITests.csproj
- UnitTests/GitUITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
> fix: Reinstate CopyContextMenuItem shortcuts

- .github/ISSUE_TEMPLATE.md
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
- GitUI/CommandsDialogs/EnvironmentInfo.Designer.cs
- GitUI/CommandsDialogs/EnvironmentInfo.cs
- GitUI/CommandsDialogs/EnvironmentInfo.resx
- GitUI/CommandsDialogs/FormAbout.Designer.cs
- GitUI/CommandsDialogs/FormAbout.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUI.csproj
- GitUI/UserEnvironmentInformation.cs
- Setup/Product.wxs
Fixes #5419 
Closes #5456 
- Add issue environment info to about screen
- Allow user to copy this info
- Copy the info when raising an issue
- Manual test.  Click copy and then paste to verify output
> Issue environment info

- GitCommands/GitCommands.csproj
- GitExtUtils/GitExtUtils.csproj
- Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
- UnitTests/GitCommandsTests/GitCommandsTests.csproj
- UnitTests/GitExtUtils/GitExtUtilsTests.csproj
Fixes #5646 
https://github.com/gitextensions/NBug/pull/13 is also required. 
- Consolidate nuget packages
Ran tests 
> Consolidate nuget packages

- GitUI/GitExtensionsForm.cs
- GitUI/GitUI.csproj
- GitUI/WindowPositionManager.cs
- UnitTests/GitUITests/GitUITests.csproj
- UnitTests/GitUITests/WindowPositionManagerTests.cs
Fixes #5627
- Extract windows position related logic to `WindowPositionManager`
- Refactor API
- crafted a unit test to replicate the issue
- fixed the issue
> Fix 5627 crash due to window positions.xml

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Fixes #5672 
- The caches can be reset, make sure to use the same instance
- GIT 2.19
- Windows 10
> Fix issue 5672: The caches can be reset, make sure to use the same instance

- GitCommands/Git/GitVersion.cs
- Update recommended Git version to 2.19.1
Wiki updated already
- n/a
Note: no effect due to #5695
> Update recommended Git version to 2.19.1

- GitUI/UserControls/FileStatusList.cs
> File status list width

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
- Plugins/Bitbucket/BitbucketPullRequestForm.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Issues raised at Transifex
- Eliminate some untranslatable strings.
TranslationApp not run, await other possible changes
- n/a
- Built
> Remove untranslatable strings

- GitUI/UserEnvironmentInformation.cs
Fixes #5732
- Add dpi scale to environment info
- Ran the program
> Add DPI scale  to environment info

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUITests/GitUITests.csproj
- UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs
Fixes #5703 
- Added a brute-force multithreading unit test. It has parameters that can set to larger numbers to run locally. On the normal testruns it will do some smoke-tests.
- Fixed some threading issues. I added comments in the code where threading issues appeared and what the fix is.
- Unit testing
- GIT 2.18
- Windows 10
> Added multithreading test and fixed issues

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #5684
Credit to @crypto-rsa for finding this [here](https://github.com/gitextensions/gitextensions/commit/a688346a21bd0ba9f22d0294c3547703e5a2ea20#r31261071).
- Fix copy/paste bug
> Fix commit dialog not refreshing on focus

- GitUI/CommandsDialogs/FormAbout.cs
Fixes #5731
- Make sure ALL contributors are shown
- Make sure only one contributor at a time is shown in label
- Changed code to get Philip Daniels entry (143) and made sure it didn't bounce and include Sam.
> About layout

- GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.resx
- GitUI/UserControls/CommitSummaryUserControl.Designer.cs
- GitUI/UserControls/CommitSummaryUserControl.cs
- GitUI/UserControls/CommitSummaryUserControl.resx
- update `FormResetCurrentBranch` layout 
- before:
- after:
> Refresh reset current branch layout

- GitUI/CommandsDialogs/FormPush.cs
> Invoke pull dialog with autoPullAction when push is rejected.

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5811
- Fixed strange resize of build status column
- Clicking on columns
- Build 4450d3e1b8a2bd8fc25121dc273ec03cc58b4186 (Dirty)
- Git 2.19.2.windows.1
> Fixed #5811: strange resize of the description column when selecting lines with mouse click

- GitUI/Editor/FileViewerInternal.cs
- appveyor.yml
Fixes #5781 
- Refresh texteditor more often. It will hurt performance a little, but will maybe fix the scrollbar issue.
What did I do to test?
- Manual testing (click files, move splitters, observer scrollbars, repeat)
> 5781: Attempt to fix disappearing scrollbar

- CommonAssemblyInfo.cs
- CommonAssemblyInfoExternals.cs
- GitExtSshAskPass/SshAskPass.rc2
- GitExtensionsShellEx/GitExtensionsShellEx.rc
- GitExtensionsVSIX/source.extension.vsixmanifest
- GitUI/GitUI.csproj
- GitUI/Resources/ChangeLog.md
- GitUI/SpellChecker/WordAtCursorExtractor.cs
- Setup/MakeInstallers.cmd
- UnitTests/GitUITests/SpellChecker/WordAtCursorExtractorTests.cs
Fixes #5890
- Prevent invalid selection range by returning 0,0 instead of -1, 0 for any value where start is negative. 
- Ran code and debugged.  
- Tested with no content, and some content.
> Return a valid selection range

- Plugins/GitFlow/GitFlowForm.cs
Fixes #5893 
- fixes issue #5893 
- Open a feature
- Commit a change
- Finish the feature
> Fix issue #5893

- GitUI/SpellChecker/EditNetSpell.cs
Fixes #5770
1. Do not open the auto-completion list when moving in the commit message editor (both by keyboard and by mouse). The auto-completion list pops up only when typing a word or on request (Ctrl+Space).
2. Make auto-completion popup when typing a word at a line end.
1. n/a
2. before: no popup at line end
after:
- Build 876903cf464aebd11d09a01a9849ea87043d4803
> EditNetSpell: Don't open auto-complete when moving

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #5935
- added saving left side splitter location 
- manual build and test
- Windows 7
> Fixes: 5935. added saving left side splitter location in commit window

- GitUI/Translation/Czech.Plugins.xlf
- GitUI/Translation/Dutch.Plugins.xlf
- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/French.Plugins.xlf
- GitUI/Translation/German.Plugins.xlf
- GitUI/Translation/Indonesian.Plugins.xlf
- GitUI/Translation/Italian.Plugins.xlf
- GitUI/Translation/Japanese.Plugins.xlf
- GitUI/Translation/Korean.Plugins.xlf
- GitUI/Translation/Polish.Plugins.xlf
- GitUI/Translation/Portuguese (Brazil).Plugins.xlf
- GitUI/Translation/Romanian.Plugins.xlf
- GitUI/Translation/Russian.Plugins.xlf
- GitUI/Translation/Simplified Chinese.Plugins.xlf
- GitUI/Translation/Spanish.Plugins.xlf
- GitUI/Translation/Traditional Chinese.Plugins.xlf
- Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.Designer.cs
Just some minor enhancements for the AppVeyor configuration. I made the tab order natural (top to bottom) and also fixed a grammatical mistake in the process. I didn't update the translations because I assume they don't include the same mistake in that language.
> AppVeyor settings enhancements

- GitCommands/PathUtil.cs
Fixes #5836
- Remove TryGetExactPath
- Compile
- GIT 2.19.1
- Windows 10
> Delete TryGetExactPath, to remove performance penalty

- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
Fixes #5960
- Don't try to launch non-existant program. Go to wiki instead.
- Untested 😨
> Fix broken link

- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- Plugins/GitHub3/GitHubRepo.cs
- Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs
Fixes #5418
- Add a string[] property to IHostedRepository to indicate supported Protocols
- Add a string property  to IHostedRepository that allows getting/setting the protocol to be used
- Modified GitHubRepo (IHostedRepository) to implement theinterface changes and alter the url of CloneReadWriteUrl depending on which protocol was selected.
- Added a Protocol Dropdown populated by the IHostedRepository (and a label) to ForkAndCloneForm (only available when the selected repository supports more than 1 protocol) to selecting the protocol to use.
- Added a bool parameter (defaults to true) to UpdateCloneInfo to prevent resetting the protocol selection every time the cloneinfotext was updated.
- Extracted the logic that set the cloneInfoTxt label to a …
> Multiple Protocol Support for Cloning in ForkAndCloneForm

- GitExtensions/GitExtensions.csproj
- GitUI/Plugin/PluginRegistry.cs
- Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
Updates the extensibility code to use vs-mef.
I have not done much testing of this. It should be tested against the latest plugin manager to ensure everything works properly.
> Update ManagedExtensibility to vs-mef

- GitCommands/Settings/FileSettingsCache.cs
Fixes #3929
- Don't crash the app if unable to read settings
- manual tests
> Don't crash the app if unable to read settings

- GitCommands/ArgumentBuilderExtensions.cs
- GitCommands/Git/GitCommandHelpers.cs
- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
- GitUI/CommandsDialogs/FormCleanupRepository.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUICommands.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.cs
- Plugins/Gerrit/FormGerritDownload.cs
- UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
- UnitTests/GitCommandsTests/GitModuleTest.cs
A cherrypick of #6002 for v3.0.0 branch
> Fix 6002 submodule reset delete new files

- GitUI/CommandsDialogs/FormBrowse.cs
- UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.cs
- UnitTests/GitUITests/GitUITests.csproj
Fixes https://github.com/gitextensions/gitextensions/issues/5511#issuecomment-449323349
- fix favourite repo ordering in the recent dropdown
- manual
- unit tests
> Fix recent repo dropdown favourites ordering

- CommonAssemblyInfo.cs
- CommonAssemblyInfoExternals.cs
- GitExtSshAskPass/SshAskPass.rc2
- GitExtensionsShellEx/GitExtensionsShellEx.rc
- GitExtensionsVSIX/source.extension.vsixmanifest
- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
- Setup/MakeInstallers.cmd
fixup for version update to 3.1.0
@RussKie
> Cleanup for updating versions to 3.1.0

- GitUI/SpellChecker/EditNetSpell.cs
- Add context menu to toggle auto completion
- manually as per the animation
----
> Toggle autocomplete commit textbox

- GitUI/CommitInfo/CommitInfo.cs
- GitUI/UserControls/AvatarControl.Designer.cs
- GitUI/UserControls/AvatarControl.cs
Closes #6172
- Ensure cancellation token sequences get disposed when their hosts get disposed
- many manual tests, time will tell
----
> Fix tests hang

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Translation/English.xlf
Ran the translation app and updated the local EN translations.
> Update local translations

- contributors.txt
> Sign off the project's Contributors Certification of Origin and Rights

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Fixes #6192
- Now able to delete both recent and categorised repositories
- manual
----
> fix: Unable to delete favourited repository

- contributors.txt
> Glen Nicol signed contributors.txt

- Setup/Mark-RepoClean.ps1
- appveyor.yml
Mark all files that we inject version number into as clean
> Mark all files that we inject version number into as clean

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #6200
- Bind <kbd>CTRL</kbd>+<kbd>SHIFT</kbd>+<kbd>P</kbd> the the "pull - merge"
- manual
----
> fix: QuickPull menu hotkey not working

- contributors.txt
> Sign developer certifciate of origin

- contributors.txt
> Signed off the project's Contributors Certification of Origin and Rights

- README.md
Partly fix #6252
* pointing towards the last release (not draft). /cc @RussKie 😉 
* going directly to the bottom of the page (a little hacky :( )
> README: Improve download links

- UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
- UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
to try to avoid race conditions
Fixes unit test failing in AppVeyor
> Tests: run tests in their own repositories

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #6117
- restore the resizable state of the resize victim column before selecting a new resize victim column
- do this before refreshing the columns because they might change their resizable state themselves
- replace the unreliable function `_gridView.Columns.GetLastColumn()` with a LINQ expression
- manual tests (tried many combinations of visible columns, especially all invisible and build status columns)
- Build cdb5f4cbe9d69a6326e215f8a6d7ce5633a52090
----
> Fix resizing of revision grid columns

- CONTRIBUTING.md
- GitCommands/Git/SystemEncodingReader.cs
- GitExtUtils/ClipboardUtil.cs
- GitExtensions.ruleset
- GitExtensions/Program.cs
- GitExtensionsVSIX/Git/GitCommands.cs
- GitUI/Avatars/AvatarDownloader.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/FormRemoteProcess.cs
- Plugins/Gerrit/FormPluginInformation.resx
- contributors.txt
Regarding  gitextensions/GitExtensionsDoc#95
> GitExtensions -> Git Extensions

- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.Designer.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- Plugins/GitHub3/GitHubPullRequest.cs
- Plugins/GitHub3/GitHubPullRequestDiscussion.cs
- Plugins/GitUIPluginInterfaces/RepositoryHosts/IPullRequestInformation.cs
* Better resize column strategy to fit content
* Add a column to know into which branch it will be fetched (See last column) + naming as changed (using the original name instead of the user login, that I found more useable to work on it...)
* Display the missing message of the PR created
- manual 
- Build b733339c3aa10ec778c3d4b7c7505ce395239d0b
> Improve GitHub integration

- contributors.txt
> Add contributor information

- GitCommands/Git/GitModule.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
* Remove unnecessary pass-by-reference
* Remove undesirable caching in test accessors
> Minor cleanup

- contributors.txt
this is my signing of contributors.txt
> sign contributors.txt

- contributors.txt
> Sign Developer Certificate of Origin

- GitUI/CommandsDialogs/FormRemotes.cs
Fixes #6347
- Ran all unit tests
- GIT version 2.19.1.windows.1
- Windows 10
----
> Fix not being able to save changes to an existing remote

- README.md
- contributors.txt
Adds the plugin I was talking about in #6360 to the README.
> Add "Git Extensions for VS Code"

- contributors.txt
Signing the _developer certificate of origin_ as specified in [`CONTRIBUTING.md`](https://github.com/gitextensions/gitextensions/blob/master/CONTRIBUTING.md), since I'm making my first contribution to the project with code that attempts to fix #6147.
> [#6147] Sign developer certificate of origin

- GitUI/UserControls/CommitDiff.cs
Fixes #5815
The artificial commit for combined difference must be specially handled in diffs.
This was not done for FileHistory CommitInfo
See issue for the exception
Manual, see the issue for an explanation
----
> Exception for combined diff in CommitInfo

- GitUI/Editor/FileViewer.cs
- minor refactoring of #6397, as discussed in https://github.com/gitextensions/gitextensions/pull/6366#discussion_r271707444: Simplified implementation of some methods in TestAccessor. No functional changes.
- manual tests, in particular checking that the relevant unit tests still run
- Build 269f4780b0bb671a9ac07e9de3cb026a7e2e519e
----
> Refactor: simplified some methods in the TestAccessor

- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- Build 3122a3f6fc58c74b331501bcc2568ecac8bdbebb (Dirty)
- Git 2.19.0.windows.1
----
> fix: JiraCommitHintPlugin hidpi layout issues

- UnitTests/GitCommandsTests/GitModuleTest.cs
Adds tests for #6451
- add tests
- NUnit tests
- Build 3a3430ce54636ddb5a6c9d558ca06ba756571c80
----
> Add tests for GitModule.GetSortedRefs()

- GitUI/CommitInfo/CommitInfo.cs
Fixes #6319
- Combine all async calls that load commit information into a single background call that reduces the number of used threads.
Overall the app feels snappier. I made a number of tests but couldn't replicate hung up or blocked threads anymore.
- manual
----
> fix: Thread exhaustion by commit info data load

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommandsTests/GitCommandsTests.csproj
- UnitTests/GitCommandsTests/GitModuleTests.cs
Fixes #6288
- Ignore any revision expression that are either null, whitespace or longer than 260 chars.
- added unit tests
----
> fix: Application crashes when selecting "Go to commit" and having big contents in clipboard

- UnitTests/GitCommandsTests/GitModuleTests.cs
> Add tests follow up on #6474

- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
Closes #5787
- As per discussion on GH, clarify the label.
----
> fix: Console tab setting requires restart

- GitCommands/Git/GitModule.cs
- GitCommands/PathUtil.cs
- UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Fixes #6343
- It was possible to add a working directory that contains double slashes, and this breaks certain functionality, such as viewing file history.
To prevent this, a working directory path is normalised when a new instance of `GitModule` is created.
- manual tests - added a repo with duplicated slashes, ensured the path is normalised and file history is operational
- unit tests
- Build e04fa438f3745f5d60a5fdf808a114081c2b93ff (Dirty)
- Git 2.19.0.windows.1
----
> fix: This repository does not yet contain any commits

- GitUI/UserControls/FileStatusList.cs
- UnitTests/GitUITests/CommandsDialogs/FileStatusListTests.cs
Fixes #6449
- indicate active filter of FileStatusList
- indicate regex error in filter of FileStatusList
regex valid
regex error
unfiltered
- manual tests
- NUnit test for the changes to `FileStatusList.FilterFiles()` factored out as a new method
- Build 0e96050c7ea1bdddf7c98d50ec80529f25e27368
----
> FileStatusList: Indicate active file filter and regex error

- GitUI/Editor/FileViewer.cs
Fixes #6434
- Use binary git-tree-ish blobdata to display binary files (already available, just ignored), do not access the file system contents
- Display header immediately, do not wait for the complete array to be formatted
- Display the complete binary file, do not truncate at 4096 bytes. Big files (like NuGet.exe) is a little slow, but you do get feedback quickly and if the user requests to see the file, it should not be limited
Note: ViewTextAsync() could be changed to not async with this change since no I/O is done. However, this will require changes to all callers.
Manual:
- FileTree, select binary file like .nuget/NuGet.exe
- See that the hex dump is displayed
- Possibly select another commit with a different version of the binary file and verify that contents/file changes
- Open …
> Use binary git-tree-ish blobdata to display binary files

- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
Updated English translation resources by running the following:
```
PS c:\gitextensions>& ./Setup/Build.cmd
PS c:\gitextensions>./GitUI/Translation/UpdateLocalEnglishTranslations.ps1
```
----
> Update english translations

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
- GitUI/Translation/English.xlf
Fixes #5527
- Changed the GPG tab setting to show by default.
- Added a description that a restart is required for the change to take place.
----
> Changed GPG tab setting to show by default

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
+ Add Separator in 'Checkout branch' sub menu (like done in 'Delete branch' one)
+ refactor: create a `AddBranchMenuItem()` local method to prevent some duplication
Same for Checkout, Merge, Rename and delete sub menus:
- Maual
- Build a17ced09094b0ece87cff21a9a5fbc0c53216f7f (Dirty)
> RevisionGrid: Add branch icons in contextual menu

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCreateBranch.cs
- GitUI/CommandsDialogs/FormCreateTag.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
> Create branch or tag: Not for artificial commits

- contributors.txt
I signed contributors.txt 
----
> signed contributors.txt

- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
Fixes #6648
- Improve error check for Jenkins responses in first phase when checking if full update is needed.
Manual, on a repo with a lot of builds.
----
> Jenkins: Improved response checking for latest update

- .gitattributes
- Setup/Build.cmd
- Setup/BuildGitExtNative.cmd
- Setup/MakeInstallers.cmd
- Setup/hMSBuild.bat
Prepare to build with VS2019
Build from commandline
VS2019 installed in addition to VS2017
----
> VS2019 msbuild

- contributors.txt
Added my details to the contributors text file
----
> Added myself to contributors

- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- Plugins/GitHub3/GitHubRepo.cs
Note: better reviewable and merged after #6514
Fixes error when using the feature "GitHub" > "View pull request" :
* "Fetch to pr/ branch" 
* "Add remote and fetch"
when you are not using ssh.
The git command failed because it can't fetch
- Auto detect the protocol that should be used
When using "Fetch to pr/ branch" 
When using "Add remote and fetch"
When using "Fetch to pr/ branch" 
When using "Add remote and fetch"
- Manual
- Build e1485dd7b8252277c01234a9c32df31a3c3b0e7d
----
> Fix GitHub PR protocol

- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.resx
- GitUI/Translation/English.xlf
Fixes #6404
* Order results in the lists (My repositories & Search for repositories). Fixes #6404
* Improve column sizing and resizing
* Add option to easily call an upstream remote "upstream" (and update the label to be clearer)
See:
* results sorted
* column width is better
* Editable dropdown to be able to select "upstream" + update on label
- Manual
- Build 8cc5933320a245b19c4fc7ff5a2285d319ac0d9e
> Improve GitHub clone/fork form

- GitUI/Avatars/AvatarDownloader.cs
- contributors.txt
Fixes #6751
- Retrieve avatar info asynchronously
- GIT 2.21
- Windows 10
> Make GE scrolling performance smoother when the avatar column is shown

- GitUI/WindowsJumpListManager.cs
Closes #6767
- Ignore UnauthorizedAccessException adding JumpList item
- empirical
----
> fix: Ignore UnauthorizedAccessException adding JumpList item

- GitUI/GitUICommands.cs
- Plugins/GitHub3/GitHub3Plugin.cs
That will open the web browser window to generate the token if needed.
+ fix a duplicate string
Fixes #6757 now that github api will return the good data instead of a 403
- manual
> Requires OAuthToken set to use GitHub3Plugin features

- GitCommands/Submodules/SubmoduleStatusProvider.cs
Fixes #6599
Path.GetDirectoryName() raises System.ArgumentException if the directory contains illegal characters. The reason for illegal characters in the path is unknown (especially as this is for topModule), but this should not crash GE regardless, especially just to get a printable name.
To avoid the exception, the method is not used if the directory does not exist.
An alternative to checking if the directory exists could be to use the GE method PathUtil.GetDirectoryName()
Manual
----
> Path must be well formatted for Path.GetDirectoryName()

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Fixes #6732
Based on #6834 
GitStatusMonitor should only run more than one command when a refresh is requested.
The cancelled command should not schedule a new command though.
The PR also adds lock() to _commandIsRunning, this should not have any real world effect.
Manual, refresh in linux repo repeatedly, only one git-status for the commit status at a time
----
> GitStatusMonitor: CancelToken to limit multiple commands

- GitUI/NBugReports/BugReportForm.Designer.cs
- GitUI/NBugReports/BugReportForm.cs
- GitUI/NBugReports/BugReportForm.resx
- GitUI/Translation/English.xlf
- UnitTests/GitUITests/GitUITests.csproj
- UnitTests/GitUITests/NBugReports/BugReportFormTests.cs
Fixes #6607
- Make repro steps textbox compulsory before a report can be submitted
- General layout update of the submission form
- Update translations
- manual
- added few unit tests
----
> Request more information via NBug submission form

- GitUI/CommandsDialogs/FormDeleteTag.cs
> fix Delete tag not working

- contributors.txt
Adding myself to contributors.txt due to pull request #6945
> Adding myself to contributors.txt

- README.md
Codescene.io doesn't require any build programming, 
just a free account and an integration button click at codescene.io.
This may be a perfect fit for codecov analysis already in place.
> Add codescene.io analysis results

- GitUI/CommandsDialogs/FormClone.cs
Fixes #6983
- Restore saving a successfully cloned repository to the list of recent remotes.
- manual
----
> fix: Remote Repositories List Empty

- contributors.txt
Update due to github id change
> Updated changed github id

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- contributors.txt
Fixes #7011 
- When right clicking on a row that has been removed from selection force the row to be selected
- 
- 
- 
- GIT 
- Windows 
----
> should fix: [NBug] Sequence contains no elements #7011

- contributors.txt
> Add me (KvanTTT) to contributors.txt

- GitUI/CommandsDialogs/FormStash.Designer.cs
Fixes #7043
- Reallow multi-selection of files in FormStash
This change was done after the following comment:
https://github.com/gitextensions/gitextensions/pull/6907#issuecomment-509835959
This has some impact on the cherry-picking of changes.
Manual
----
> Allow multi-select of files in FormStash

- GitCommands/PathUtil.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Fixes #7059
If the file has no extension but the directory path has a period the suffix will include the complete path.
Manual with repo in #7059 
----
> File suffix incorrectly detected

- UnitTests/GitCommandsTests/RevisionReaderTests.cs
- UnitTests/GitCommandsTests/StreamExtensionsTests.cs
- UnitTests/GitUITests/CommandsDialogs/FormInitTests.cs
A few duplicate tests, not run
(I got printouts about them in Output, but they do not appear now. However, the number of tests do not match TestCase.)
Remove/Update the duplicate test cases
Check number of tests before/after
----
> Fix duplicate ignored tests

- GitCommands/Git/GitVersion.cs
Update the recommended Git version to 2.23 released three weeks ago
I see no specific changes that are needed, but should be tested by usage for 3.3
Manual
----
> Set recommended Git version to 2.23.0

- Plugins/GitHub3/GitHubCredentialsPrompt.cs
Fixes #7157
- fix incorrect user-agent
- manual
----
> fix incorrect user-agent

- UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs
addendum to PR #6877
- add more test cases for empty lines in commit messages
N/A
- NUnit tests
- Build 8a76ea014d5892f7cea3a8903b5ed6a15597b80f
----
> Add more test cases for empty lines in commit msgs

- GitCommands/RevisionReader.cs
- UnitTests/GitCommandsTests/RevisionReaderTests.cs
Fixes #7126
- consider the end-of-body marker everywhere in the detection of single-line commit messages
- Build fac68fef6c8b41f779e68b965936d9baca94198c
----
> No more "..." indicator for revisions with single-line commit message

- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Plugins/PluginSettingsPage.cs
- Plugins/AutoCompileSubmodules/AutoCompileSubModulesPlugin.cs
- Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
- Plugins/Bitbucket/BitbucketPlugin.cs
- Plugins/CreateLocalBranches/CreateLocalBranchesPlugin.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesPlugin.cs
- Plugins/FindLargeFiles/FindLargeFilesPlugin.cs
- Plugins/Gerrit/GerritPlugin.cs
- Plugins/GitFlow/GitFlowPlugin.cs
- Plugins/GitHub3/GitHub3Plugin.cs
- Plugins/GitUIPluginInterfaces/IGitPlugin.cs
- Plugins/Gource/GourcePlugin.cs
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- Plugins/ProxySwitcher/ProxySwitcherPlugin.cs
- Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorPlugin.cs
- Plugins/Statistics/GitImpact/GitImpactPlugin.cs
- Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
- ResourceManager/GitPluginBase.cs
Fixes #7154
Null check to avoid exception
I do not really have access to the PC that saw this error, but have got the user to test this fix.
While it would be interesting to see why it occurred at all, it is not really feasible.
----
> FormSettings exception if plugin has no setting

- GitUI/Translation/English.Plugins.xlf
- Plugins/Gerrit/FormGerritPublish.Designer.cs
- Plugins/Gerrit/FormGerritPublish.cs
- contributors.txt
Should apply only one % and then comma separated parameters for publish. Example:
%wip,topic=test
Added CC and Hashtag for Gerrit Publish dialog.
See details here: https://gerrit-review.googlesource.com/Documentation/user-upload.html#_git_push
> Gerrit Plugin fixes/improvements

- Plugins/GitHub3/GitHub3Plugin.cs
A try just to get the build artifact...
> Try fix #7205, #7193

- Plugins/Gerrit/FormGerritBase.cs
- Plugins/Gerrit/FormGerritPublish.cs
Fixes #7200
- Request Gerrit API version and store it at Base class
- Change sending parameters regarding Gerrit Version
- Manual for Gerrit 3.0.0
- If somebody has Gerrit <= 2.15 - please test it more
- GIT 2.23.0.windows.1
- Windows 10 Enterprise 1809 (OS Build 17763.737)
----
> Support older Gerrit API

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Fixes #7183 
* Always compare timer diff (to handle timer wraparound after 25 days)
to avoid missing updates while command is running
* Increase min update time 3s -> 5s at changes in the file system
* Use locks consistently
* Start interactive update only once to avoid race where two commands started
See issue for how to provoke the problem
----
> GitStatusMonitor: Improve logic for timer 25 days wrap

- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
- Reordered option
- Refactored code to be in harmony with the UI (in the sense of the ordering)
Manual
- Build 429a4f06e30478c41bdfaf1f501de175b82b8126
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
----
> Reordering of Appearance Options

- UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
- UnitTests/GitCommandsTests/CommitDataManagerTest.cs
- UnitTests/GitExtUtils/ArgumentBuilderTests.cs
- UnitTests/Plugins/GitUIPluginInterfacesTests/ManagedExtensibilityTests.cs
- UnitTests/Plugins/GitUIPluginInterfacesTests/PluginsPathScannerTests.cs
Bugfix unit test that doesn't work on my danish windows
cleaning up unused usings
----
> Unittest fix and cleaning

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommandsTests/GitModuleTests.cs
Reverts gitextensions/gitextensions#7280
> Revert "Implement quotePath-like codepoint escaping"

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/CommandsDialogs/FormCreateBranch.cs
- GitUI/GitUICommands.cs
- GitUI/Translation/English.xlf
Implements #7013
- A new context menu item that allows to create a new branch in the selected "folder".
- Revision to create a branch from will be "Current Revision" (FormCreateBranch's default behavior).
- Unit tests run
- GIT 2.23 
- Windows 10 
- Scale: 100%
----
> Allow branch creation in folder context menu (#7013)

- GitExtensions/GitExtensions.csproj
- contributors.txt
- update GitInfo to 2.0.21
Fixes #7331 
- update GitInfo to version 2.0.21
- built GitExtensions in Release, did not try to reinstall and run the application, however
----
> Fix #7331: Update GitInfo dependency to get bug fix

- GitUI/Editor/FileViewer.cs
Fixes #7322
Well, does not fix what #7322 was reported about, but the scenario why #7322 was reported.
If a file is detected as binary from gitattributes or filename, the contents should be displayed as a hexdump similar to files detected as binary from file contents. This affects the FileTree, edit file etc.
(editing binary files will still be an issue, it will save the data as displayed...)
Ignore the dark theme, just see that the file contents are not displayed.
I setup the following repo for testing, the GE binary files did not have the "correct" attributes set
https://github.com/gerhardol/tmp_test.git
----
> Consistent display of binary files

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #7263
This depends on #7237
- Initialize progress bar value/max value when reseting files.
- Optimize enumeration when unstaging files. 
- Do not unstage file when there's no selected files.
Reset files now OK, with progress bar visible
- Manual test
- GIT 
- Windows 
----
> Fix #7263: Progress bar value/max value not initialized when reseting files.

- GitCommands/ArgumentBuilderExtensions.cs
- GitCommands/Git/GitCommandHelpers.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.cs
- GitUI/Translation/English.xlf
- UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
Fixes #7358
- Add git-reset --merge and --keep options to the reset dialog
- Added appropriate test cases to GitCommandHelpersTest
- Manually tested the new options and confirmed they generate the expected commands
- GIT 2.14.1
- Windows 10
----
> Implement git-reset --merge and --keep options

- GitUI/Translation/English.Plugins.xlf
- Plugins/GitFlow/GitFlowForm.Designer.cs
- Plugins/GitFlow/GitFlowForm.cs
Extends squash feature to all supported types. (previuosly enabled only for feature branch type on Pull Request #7268 )
- Build 5b0f5e202845e5ed529eff3e3cfc60f200a2212b (Dirty)
- Git 2.24.0.windows.2
> Extends Squash feature to all supported types

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
depending if some builds are running (refresh interval is 10s)
or not (interval is 120s)
... to reduce calls to the CI server when not needed.
- Manual
- Build 1d62d64ab33e9ce45b898542facff3f9a50caf6e (Dirty)
> BuildServerIntegration: Adjust polling interval for running builds

- GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
Fixes #7481
Manual adjustment of tab order and tab stop
Manual - see issue
----
> ResetCurrentBranch: Correct tab order

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
Fix regression introduced in 3fcb4788b42d9b485880eb756e4bdc0af47d321b (#7452)
where application is frozen during a long time
after a revision grid refresh (`Thread.Sleep()` was made in the UI thread :( ).
Introduce an observable that produce a 'OnComplete' after a variable delay
depending if a build running was found.
Manual: 
- Open a repository that have a CI enabled
- Refresh revision grid
- Verify that there is no froze of the application
- Build c765121993ac3577334208db90bd9d1d5e8859a2 (Dirty)
> BuildServerIntegration: Fix freeze due to polling interval adjustment

- Bin/gitex.cmd
Fixes #7542
#7547 for 3.3
----
> gitex: If no argument start browse in current workdir

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
Makes GitExtensions more CI server friendly by doing less api calls:
=> prevent 1 (most of the time) useless api call / minutes
These calls are most of the times useless because finished builds that will be found will correspond to commits not in the revision grid.
The only case where it is useful is when there was running builds the last time the revision grid was refreshed and so, to display the state of these builds once finished. 
That's why this PR makes that the calls to find newly finished builds to be made only when running builds were previously found.
Contribute to fix too intensive call of CI api. Follow up of #7477 (For issue https://github.com/gitextensions/gitextensions/pull/7452#issuecomment-559084273 )
- Manual
- Build …
> CI: Only look for newly finished builds if previously running build found

- contributors.txt
Signing-off my contribution after PR #7591
> Sign-off contribution

- GitUI/UserControls/FileStatusList.cs
Part of #4154
If two revisions are selected, show the difference from the first to the BASE revision for the first-selected
This could be achieved by selecting the revisions in the grid, Navigate->Go to common ancestor (remember it), reselect revisions and finding and selecting the BASE commit again. (The last part is the most inconvenient).
Functionality is what I want, but set to WIP:
Based on #7560. 
The setting should be clarified, currently reusing AppSettings.ShowDiffForAllParents. This what I prefer, just updating the documentation.
Another reason to WIP is to get comments from @mdonatas that has implemented a solution that also includes A-BASE and B-BASE, affects a lot more code though.
Manual
---- …
> RevisionDiff: Show BASE diff

- GitUI/CommandsDialogs/BrowseDialog/MenuCommandsBase.cs
- ResourceManager/GitPluginBase.cs
- ResourceManager/ITranslate.cs
- ResourceManager/Translate.cs
- UnitTests/GitUITests/TranslationTest.cs
- Dispose objects created by TranslationTest
----
> Dispose objects created by TranslationTest

- GitUI/Editor/FileViewerInternal.cs
- GitUI/UserControls/AvatarControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- dispose dangling `_findAndReplaceForm`
- dispose `_cancellationTokenSequence` also if `components` are `null`
- add `_loadingControlAsync` and `_loadingControlSync` only once to `Controls`
- consider every field in `RevisionGridControl.Dispose`
- dispose dangling `_revisionFilter`
----
> More complete Dispose

- GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes #7546 
Check that no parent revision is a combined commit.
Previously, reset to parent was blocked only if no other than the combined diff was selected.
It was also possible to reset to multiple parent revisions.
While resetting multiple files to the same revision is expected, there is no check that a file is not included more than once, which gives undefined behavior. It is reasonable to disallow multiple parent revisions completely.
Reset to Combined is not blocked
Multiple reset is not blocked
Manual
----
> RevisionDiff: No reset to CombinedDiff

- GitExtUtils/GitUI/ThreadHelper.cs
- IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs
- IntegrationTests/UITests/CommandsDialogs/FormCommitTests.cs
- UnitTests/CommonTestUtils/AsyncTestHelper.cs
- UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
- UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
- UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
- UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
- UnitTests/GitUITests/ThreadHelperTests.cs
> Join pending operations asynchronously

- Bin/gitex.cmd
Fixes #7709
Correct check for empty variable
Batch/DOS is weird
https://stackoverflow.com/a/51502846
Test be replacing test with echo in the batch file
----
> gitex.cmd: handle quotes in commands

- contributors.txt
Updated list of contributors with my entry
> Contributor list updated

- contributors.txt
Fixes #
- Provide consent to MIT license
----
> Provide consent to MIT license

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.ReorderNodes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs
Fixes one source of hangs observed in #7742.
> Avoid deleting test directories while operations may be in progress

- GitCommands/Utils/EnvUtils.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/TaskbarProgress.cs
- GitUI/WindowsJumpListManager.cs
Fixes an exception observed during debugging #7742
> Avoid attempting to update non-existent UI

- contributors.txt
> Provide consent to MIT license (#7758)

- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
Improve ScriptRunnerTests
- use `AsyncTestHelper.WaitForPendingOperations`
- assert that no error is displayed by the tested function
- use `formBrowse` as owner for potential subdialogs
- AppVeyor
- Windows 10
----
> Improve ScriptRunnerTests

- GitCommands/CommitMessageManager.cs
Fixes #6908
Popup instead of NBug if the COMMITMESSAGE cannot be accessed
NBug
Test by patching code only, not reproduced the problem.
----
> FormCommit: Unaccessible COMMITMESSAGE

- Build/Build.ps1
- Build/tools/Build.proj
- Build/tools/RepoLayout.props
- Directory.Build.props
- Externals/Directory.Build.props
- GitExtensions/GitExtensions.csproj
- GitExtensions/Project.Build.targets
- GitExtensions/Project.Publish.targets
- GitExtensionsVSIX/Directory.Build.props
- GitUI/Theming/ThemeRepository.cs
- appveyor.yml
- Effectively revert a606467bb23721313b211b004b3456ce30572969, and publish a portable build
NB: the plugins are not included in the portable build right now
----
> Publish portable build

- GitCommands/PathUtil.cs
- GitExtensions/Program.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
- GitUI/GitUICommands.cs
- GitUI/Strings.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Fixes #7679
Fixes #7579
Fixes #7170
Fixes #6630
- Centralise how folders get deleted, and make the deletion process safer.
- unit tests
----
> Make folder removal safer

- GitUI/Translation/English.xlf
Fixes #7714
- update `English.xlf` in order to make the CI build succeed
----
> Fixup translation (last master merge)

- GitCommands/PathUtil.cs
- GitUI/CommandsDialogs/FormClone.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Fixes #7839
- check for a few more git protocols (all I found at the current https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols)
- check for existing git folders, too
- manual tests
- Build 9070a525b78e1f1fec9f6b839dafb948673dfd25
----
> More complete CanBeGitURL

- appveyor.experimental.yml
- appveyor.yml
- scripts/tools/NUnit/NUnit.targets
> Enhance tests output

- contributors.txt
- As requested in https://github.com/gitextensions/gitextensions/pull/7883 added myself as contributor
----
> Modify contributors.txt

- .tools/transifex/DownloadTransifexTranslations.ps1
- GitExtensions/Project.Build.targets
- GitExtensions/Project.Publish.targets
- GitExtensions/app.config
- Plugins/BuildServerIntegration/TfsIntegration/TfsIntegration.csproj
- scripts/Mark-RepoClean.ps1
- scripts/tools/Imports.targets
- scripts/tools/Localisation.targets
- scripts/tools/Publish.targets
Follow up for #7910
* Fix how translations are copied
* Fix how plugins are copied
----
> Fix portable artifact generation.

- GitUI/UserControls/FileStatusList.cs
Seen with #7902
- No flags set should have an FileStatusUnknown icon
If a file has no flag set at all, the status should be unknown too.
If an empty ststus is created like with https://github.com/gitextensions/gitextensions/commit/75a70a9921011e76ddc86028a076cd86aec70a4c
the icon was set to FileModified instead.
The flags is not accessible but either IsTracked or IsNew must be set, so it sufficient to check those
- Separate icon for Conflict
- FileStatusList submodule temporary icon
When fixing this, also addressing something that has always bothered me:
The Submodule icon is set to FileModified until the statatus is updated (run async). Normally it is quick so you hardly see it,
but at work the virus known as Symantec slows down Git 10 times in the normal use case and much more …
> FileStatus icon: submodule before status updated

- GitExtensions.settings
- GE internal: detect GH issues like ".../i1111"
- manual
----
> Revision Links: Detect GH issues like ".../i1111"

- GitCommands/AppTitleGenerator.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormAbout.cs
- GitUI/CommandsDialogs/SettingsDialog/SettingsGroupPages.cs
- GitUI/Infrastructure/Telemetry/DiagnosticsClient.cs
- GitUI/NBugReports/Info/GeneralInfo.cs
- UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
- Unify the use of "Git Extensions"
> Unify the use of "Git Extensions"

- GitCommands/AppTitleGenerator.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/CommandsDialogs/FormAbout.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowseController.cs
- GitUI/CommandsDialogs/SettingsDialog/SettingsGroupPages.cs
- GitUI/Infrastructure/Telemetry/DiagnosticsClient.cs
- GitUI/NBugReports/Info/GeneralInfo.cs
- GitUI/RepositoryCurrentBranchNameProvider.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
- UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormBrowseControllerTests.cs
Addendum to #7882
- Unify the use of "Git Extensions"
- Unify branch rendering in recent repo dropdown
- Unify repository binding
- GIT 
- Windows 
----
> Fix branch rendering

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowseController.cs
- GitUI/CommandsDialogs/GpgInfo.cs
- GitUI/CommandsDialogs/InvalidRepositoryRemover.cs
- GitUI/RepositoryCurrentBranchNameProvider.cs
- GitUI/Translation/English.xlf
- UnitTests/GitUI.Tests/CommandsDialogs/FormBrowseControllerTests.cs
- use the same mechanics to prompt to remove invalid repositories in the `FormBrowse` and the dashboard.
* Before
* After
----
> Centralise removal of invalid repositories

- scripts/tools/NUnit/NUnit.targets
> Reinstate codecov reporting

- GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
> fix: Error while executing user script from RevisionGrid

- appveyor.experimental.yml
- appveyor.yml
- Adapt artifacts path to tests (addendum to #7975)
- Keep experimental test artifacts before they are overwritten by the next test run
- AppVeyor
- AppVeyor
- Windows 10
----
> Fix up appveyor test artifacts

- GitExtUtils/GitUI/Theming/ThemeFix.cs
Fix naming issue pointed here: https://github.com/gitextensions/gitextensions/pull/7962#issuecomment-612050073
----
> Fix naming issue in ThemeFix.cs

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- GitUI/Translation/English.xlf
- ResourceManager/Strings.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Fixes #7637
- Add possibility to delete multiple files
- Add possibility to delete file even if a submodule is selected
- 
"Detele File" not shown is Diff window if multiple file was selected;
It's possible to delete multiple files like SUPPR keyboard allow it.
> Delete multiple files at a same time with popup menu

- GitCommands/FullPathResolver.cs
- GitCommands/PathUtil.cs
- GitUI/CommandsDialogs/FormClone.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
- contributors.txt
Fixes #7438
(This is fixed pull request of #8002 in separated feature branch without merges)
- Fix compatibility with WSL (\\\\wsl$\\) network resource
- Unit tests
- GIT 2.20.1
- Windows 10
----
> Fix compatibility with WSL (\\wsl$\) network resource

- GitUI/WindowsJumpListManager.cs
Resolves #6760
Resolves #7755
Resolves #7783
Resolves #7843
Resolves #8029
Relates to #6762
> Ignore Microsoft.WindowsAPICodePack.Shell.ShellException

- GitUI/UserControls/FileStatusList.cs
> fix app crash due System.Reactive x-thread access

- GitUI/UserControls/FileStatusList.cs
Fixes #8097
Avoid creating the revisions instead of shrinking the list
Manual
----
> Limit number of diff revisions

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
- GitUI/Script/ScriptInfo.cs
Clone of #8111 for the `release/3.4` branch
----
> Fix up user scripts without icon

- GitCommands/Config/ConfigFile.cs
- GitCommands/Config/GitConfigurationException.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormSubmodules.cs
- GitUI/MessageBoxes.cs
- GitUI/Translation/English.xlf
- Plugins/Statistics/GitStatistics/FormGitStatistics.cs
- ResourceManager/Strings.cs
- UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Fixes #7097
Catch exceptions related to invalid configs and present them to user in a better way, giving the user an opportunity to correct it rather than crashing the app.
- manual
----
> Fix 7097 crash invalid escape character in .gitmodule

- contributors.txt
Fixes #
- 
- 
- 
- 
- 
- 
- GIT 
- Windows 
----
> Add myself as contributor

- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
> Hide extra separator in context menu for folder item

- GitExtensions/app.config
- Plugins/Bitbucket/BitbucketRequestBase.cs
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.csproj
- Plugins/JiraCommitHintPlugin/app.config
- Solution.Versions.props
- contributors.txt
Fixes #8122 
Fixes #8089
- Updated Atlassian.SDK package to latest version
- some Jira issues could not be deserialized
- updated Atlassian.SDK dependency fixes problem
- tested manualy in commit window (before change it didn't work, after change it is OK)
Before
After
----
> Fix 8122 Update Atlassian.SDK package to latest version

- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
https://github.com/gitextensions/gitextensions/issues/8150#issuecomment-637951555
Uncoditionally use last value instead of throwing
Manually
----
> AppVeyor Exception at init

- GitExtensions/GitExtensions.csproj
Fixes #8208
Tested manually with `C:\Program Files\Git` renamed to Git2
Windows 10
----
> fix ignoring app.manifest

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Script/ScriptRunner.cs
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
Addendum to #8182
Resolves #8221
- Centrally handle user script errors
> Centrally handle user script errors

- GitUI/CommandsDialogs/FormBrowse.cs
to make it more visible.
Improvement on https://github.com/gitextensions/GitExtensions.GerritPlugin/issues/13#issuecomment-644720345
- Manual 
- Build f2d6c3a8bc1899389911fc6b1a8e8440945ba428
> Display 'Plugin Manager" next to "Plugin settings" in the menu

- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
Fixes #8255 
Should disable buttons too...
Use correct index for diff/merge
Manual
----
> MergeTool Setting: Exception if mergetool is not set

- README.md
- add hint to `README.md`
Feel free to tinker / move the text how and where you like it better!
----
> Add a hint regarding updates of portable builds

- contributors.txt
Fixes #
- 
- 
- 
- 
- 
- 
- GIT 
- Windows 
----
> Sign CLA #8296

- .github/ISSUE_TEMPLATE/config.yml
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> Customise GitHub issue templates

- GitUI/CommandsDialogs/FileStatusListContextMenuController.cs
- GitUI/CommandsDialogs/FormDiff.Designer.cs
- GitUI/CommandsDialogs/FormDiff.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUICommands.cs
- GitUI/RevisionDiffInfoProvider.cs
- GitUI/RevisionDiffKind.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffContextMenuControllerTests.cs
- UnitTests/GitUI.Tests/Helpers/DiffKindRevisionTests.cs
Fixes #8253 
Remove diff to parent of first/second revision
Removed code, including tests
----
> RevDiff: Remove parent diff

- GitUI/Themes/darksilver.css
- Setup/Product.wxs
Minor changes in darksilver theme [(#8323)](https://github.com/gitextensions/gitextensions/pull/8323)
> Darksilver theme update.

- GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/CommandsDialogs/FormClone.Designer.cs
- GitUI/CommandsDialogs/FormInit.Designer.cs
- GitUI/GitExtensionsDialog.cs
- GitUI/HelperDialogs/FormStatus.Designer.cs
Contributes to to #6183
- Update `FormCreateBranch` layout - this is a truly nasty dialog to lay out 🤯 
- Aligned buttons sizes in other dialogs
- Lighten up the controls panel slightly
Verified at 100% and 150% scale factor, both light and dark versions.
----
> Dialogs layout alignment `FormCreateBranch`

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormPull.Designer.cs
- GitUI/CommandsDialogs/FormPull.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPullTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #8430 
Manual
- .NET Framework 4.8.4200.0
----
> Add checkbox to prune tags

- GitUI/CommandsDialogs/FormBrowse.cs
- Reset filter when switch repos
- manual
----
> Reset filter when switch repos

- GitCommands/Settings/AppSettings.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- Less magic values
- More tests
- Manual
- Automation
----
> Add tests for AppSettings

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.ReorderNodes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
Relates to #8427
- Ensure correct placement of sort-related menus - occasionally the menu would be placed at a wrong index.
- manual
- tests
> Correct Sort context menu placement

- contributors.txt
Added myself as a contributor.
----
> Added myself as a contributor.

- contributors.txt
This is the separate pull for The Developer Certificate of Origin. for my pull requests.
> Agree to The Developer Certificate of Origin.

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #8327 
This PR is related to closed one #8513. All related PR description can be found there.
> Fixes #8327 push commit does clear commit message

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs
- GitUI/Script/IRunScript.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #6307
- Manually
- Git 2.23.0.windows.1 (recommended: 2.25.1 or later)
- .NET Framework 4.8.4200.0
----
> Add 'Run script' command to branches pane context menu

- GitUI/CommandsDialogs/FormPush.cs
Fixes #8520 broken by #8573
- Manual
- Build ac4147c6cf9465dac7c3026e373a64287ea50b75
> FormPush: fix tracked branches selection

- GitUI/Editor/FindAndReplaceForm.cs
Fixes #8605 
Avoid NBug for NRE when shutting down GE
Tested shutting down the PC a few times with GE running
----
> Exception closing GE when shutting down Windows

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
> Don't persist or restore the state of the main menu

- ResourceManager/Xliff/TranslationUtil.cs
#8682 adds use of "AccessibleName" which should be translated.
(No such properties right now).
Manual
----
> TranslationApp: Include "AccessibleName"

- GitUI/CommandsDialogs/FormResolveConflicts.cs
Fixes #8666
Allow opening of FormResolveConflicts also if the mergetool cmd and path is not set.
The explicit button and menu item for GE "enhanced" mergetool handling is disabled if cmd or path is not set.
The popup warning about the configuration was previously shown if path did not exist. It is now shown when the path is set but does not exist (but the form is still shown).
It is allowed to start the form without cmd being set (but path must be set and exist in 3.4).
If cmd or path does not exist, GE falls back to using Git mergetool since 3.4, see 2436c6a64dcad34e06ba9ee62f78f5f5f052b710
Note that git-mergetool has fallback handling if the mergetool, does not exist, see the screenshot.
In next version it is possible to explicitly use a specific mergetool too.
Explicitly disabling the …
> FormResolveConflict: Allow open without cmd/path

- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.resx
- GitUI/CommandsDialogs/SearchControl.Designer.cs
- GitUI/CommandsDialogs/SearchControl.cs
- GitUI/Interops/Messages.cs
- GitUI/Interops/User32/GetWindowDC.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/TextBoxEx.cs
ref #8557
- Add textbox with ability to change border color
- Add toolbar to the left panel
Maybe replace the button too.
- manually
- visually
----
> Left panel enhancement

- contributors.txt
Agree to The Developer Certificate of Origin
----
> Agree to The Developer Certificate of Origin

- GitCommands/Git/GitVersion.cs
Git recommended version upgrade
No known incompatibilities
A few features added, nothing critical
(using features is not dependent on recommending 2.30)
Manual
----
> Git 2.30.0

- GitUI/CommitInfo/CommitInfo.cs
Fixes #8811
sort main branch first as master
Manual
----
> Prioritize main as master in CommitInfo

- GitUI/BranchTreePanel/RepoObjectsTree.cs
> Incorrect colors for left panel icons

- GitExtensions/Program.cs
- GitUI/Theming/Renderers/ThemeRenderer.cs
- GitUI/Theming/ThemeModule.cs
- GitUI/Theming/Win32ThemeHooks.cs
Resolves #8798
- manually change scaling factor back and forth.
----
> Fix dark theme visually corrupt after dpi change

- GitCommands/CustomDiffMergeTool.cs
- GitCommands/CustomDiffMergeToolCache.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormFileHistory.Designer.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
- GitUI/CustomDiffMergeToolProvider.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- ResourceManager/Strings.cs
- UnitTests/GitCommands.Tests/CustomDiffMergeToolCacheTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
#8700 for 3.5
If not included, some special adaptions must be done to 3.5 (part of this PR)
----
> 3.5 Custom difftool in RevDiff, FileHistory, Commit, RevGrid

- GitExtUtils/Linq/LinqExtensions.cs
- GitUI/NBugReports/BugReporter.cs
- GitUI/NBugReports/UserExternalOperationException.cs
- GitUI/Shells/BashShell.cs
- GitUI/Shells/CmdShell.cs
- GitUI/Shells/ConEmuControlExtensions.cs
- GitUI/Shells/IShellDescriptor.cs
- GitUI/Shells/PowerShellShell.cs
- GitUI/Shells/PwshShell.cs
- GitUI/Shells/ShellDescriptor.cs
Remove redundant `#nullable directives` for files which are already in project-wide nullable contexts.
- Checked it compiles.
----
> Remove redundant #nullable directives

- .gitmodules
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/GitExtensionsDialog.cs
- GitUI/UserManual/StandardHtmlUserManual.cs
- README.md
- UnitTests/GitCommands.Tests/TestData/README.blame
- UnitTests/GitUI.Tests/UserManual/StandardHtmlUserManualFixture.cs
- scripts/set_version_to.py
Requests are directed to / anyway
See discussion in https://github.com/gitextensions/GitExtensionsDoc/issues/131
PR will be updated when submodule is merged
review
----
> Remove /en/latest from Doc links

- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
> Submodule status updated too often 3.5

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/CommandsDialogs/SettingsDialog/SettingsPageWithHeader.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/UserControls/BranchSelector.cs
- Plugins/GitHub3/GitHubHostedRemote.cs
- Plugins/GitHub3/GitHubPullRequest.cs
- UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs
- Use the null coalescing assignment operator (`??=`) to simplify code when lazy assignment occurs.
---
> Use null coalescing assignment

- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeController.cs
- GitUI/MouseWheelRedirector.cs
- Merge sequential checks into pattern matching expressions
---
> Merge sequential checks into pattern matching expressions

- GitExtensions.sln
- Add missing solution items. These files exist in the repo and are useful to have in the solution, so that they may contribute results to search operations.
- It compiles.
----
> Add missing solution items

- GitExtensions.sln
- Remove solution items for files that no longer exist in the repo.
- It compiles.
----
> Remove invalid solution items

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/CommitInfo/CommitInfoHeader.cs
- Use C# 9 pattern matching in a few places
- Manual testing and review
----
> Use pattern matching

- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- ResourceManager/Xliff/TranslationUtil.cs
- UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
- Use null propagation
- Manual review. It compiles. CI will run tests.
----
> Use null propagation

- GitExtUtils/GitUI/ControlDpiExtensions.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/SplitterManager.cs
- UnitTests/GitUI.Tests/SplitterManagerTest.cs
Fixes #8712
- Add bordes
- Set splitter width like in VS
- Manually
- Visually
- Build aabe00bb81fba440c57170f601384418a882a06d (Dirty)
- Git 2.30.0.windows.2
----
> Add borders in Commit Form and set splitter width like in VS

- GitUI/Editor/FileViewer.cs
- Remove redundant await where is no needed
- Manually
- Build 22f3b681ffff7beec4a789bda7e9fa915cd62d45
----
> Remove redundant await

- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
- Plugins/GitUIPluginInterfaces/PluginsPathScanner.cs
Fixes #8966
- Fix incorrect nullability assertion and annotations.
- Manual review.
----
> Fix invalid null value assertion in plugin code

- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitCommands/Settings/AutoCRLFType.cs
- GitCommands/Settings/FileSettingsCache.cs
- GitExtUtils/GitUI/ControlThreadingExtensions.cs
- GitExtUtils/GitUI/HighDpiMouseCursors.cs
- GitExtUtils/GitUI/ThreadHelper.cs
- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/CommandsDialogs/FullBleedTabControl.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitModuleForm.cs
- GitUI/GitUICommands.cs
- GitUI/MouseWheelRedirector.cs
- GitUI/UserControls/MainThreadScheduler.cs
- GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
- ResourceManager/Strings.cs
- UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
- UnitTests/GitCommands.Tests/Git/ObjectIdTests.cs
- UnitTests/GitUI.Tests/CancellationTokenSequenceTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionFileTreeControllerTests.cs
- UnitTests/GitUI.Tests/ControlThreadingExtensionsTests.cs
- Remove redundant diagnostic suppressions
- It compiles. These have no impact on code generation.
----
> Remove redundant suppressions

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
> range-diff: Incorrect limit when selecting four commits 3.5

- GitExtensions.sln
- Plugins/Statistics/GitImpact/FormImpact.Designer.cs
- Plugins/Statistics/GitImpact/FormImpact.cs
- Plugins/Statistics/GitImpact/GitExtensions.Plugins.GitImpact.csproj
- Plugins/Statistics/GitImpact/GitImpactPlugin.cs
- Plugins/Statistics/GitImpact/ImpactControl.cs
- Plugins/Statistics/GitImpact/Properties/Resources.Designer.cs
- Plugins/Statistics/GitStatistics/GitExtensions.Plugins.GitStatistics.csproj
- Plugins/Statistics/GitStatistics/Properties/Resources.Designer.cs
- Setup/Product.wxs
- Move all plugins to "GitExtensions.Plugins" namespace
- Manually
- Build 11d61bfcc3394beaa50eca4d395a8ac12b778489 (Dirty)
----
> Move GitImpact plugin to "GitExtensions.Plugins" namespace

- GitExtensions/Project.Publish.targets
> Include spelling dictionaries

- contributors.txt
> Add contributor

- GitUI/Editor/BlameAuthorMargin.cs
Cherry pick of #8987 for 3.5 branch
> #8684 Avatars are misaligned in blame form

- contributors.txt
Just updated contributors.txt as suggested in [9044](https://github.com/gitextensions/gitextensions/pull/9044#issuecomment-811025998)
----
> Updated contributors.txt

- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
repeat #9053 in release branch
> Color settings page events (#9053)

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/SplitterManager.cs
- UnitTests/GitUI.Tests/SplitterManagerTest.cs
Resolves #8745
Resolves #9000
Resolves #9089
----
> Restore splitter persistence

- Bin/set-telemetry.ps1
Fixes #8228
for main branch
see #9114
----
> Let installer not activate disabled telemetry

- contributors.txt
> sign off from @MrJithil

- contributors.txt
Fixes #
-Sign Off
- GIT 
- Windows 
----
> sign cla | change email

- GitUI/Editor/FileViewer.cs
Part of #9213
Refactor: Use existing FullPathResolve instead of multiple invocations.
This removes a File.Exists() that is resolved incorrectly.
If opening GE with openrepo arg (and more?), open another and viewing a new file in Worktree commit that exist in the first repo, the file in the existing repo was shown.
Manual
----
> Use fullPathResolver for viewing local files

- GitExtensions/Program.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormPull.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/InvalidRepositoryRemover.cs
- GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/MessageBoxes.cs
- GitUI/NBugReports/BugReportInvoker.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
Fixes #9151
- use `System.Windows.Forms.TaskDialog` instead of `Microsoft.WindowsAPICodePack.Dialogs.TaskDialog`
- Almost all dialogs are tested manually
| Old | New |
| :---: | :---: |
- Windows 7 SP1, DPI Scaling 125%
----
> Use System.Windows.Forms.TaskDialog

- GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/Translation/English.xlf
> FormCheckoutBranch add mnemonics

- GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/Translation/English.xlf
Fixes #9271
and #9251
#9265 for release/3.5 (affecting translations)
- Fixup `AcceptButton` of `FormCheckoutBranch`
- Add mnemonics
- manual
- Build 64dc82b84224dfbb14f7ed8eb637fc79e1194b85
----
> Fixup `AcceptButton` of `FormCheckoutBranch`

- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Follow-up to #9286
- remove the failing assertion (failing only on AppVeyor) because it is not really part of what the test shall verify
----
> Increase test robustness

- GitUI/Plugin/PluginRegistry.cs
- GitUI/Translation/English.xlf
- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
- ResourceManager/Xliff/TranslationUtil.cs
- scripts/RepoLayout.props
- Restore plugins loading, disabled in #8522
NB: https://github.com/gitextensions/gitextensions/issues/9135 is still broken, suspect the regression is introduced in https://github.com/gitextensions/gitextensions/pull/9082.
----
> Load plugins

- GitUI/Script/PowerShellHelper.cs
Fixes #9347
- Tell `Executable.Start` to create a window for user scripts which shall run PS in the foreground
- manual
- Build e5583961130d5ad7060c9f0397d983cbd6aedecf
----
> Fixup user scripts running PS in foreground

- GitCommands/AppTitleGenerator.cs
- GitCommands/Git/GitDirectoryResolver.cs
- GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs
- GitExtensions/Program.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Script/ScriptOptionsParser.cs
- GitUI/WindowsJumpListManager.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.ReorderNodes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockAppTitleGenerator.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockRepositoryDescriptionProvider.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockWindowsJumpListManager.cs
- Packages.props
- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
- UnitTests/CommonTestUtils/CommonTestUtils.csproj
- UnitTests/CommonTestUtils/MEF/ExportProviderCache.Scope.cs
- UnitTests/CommonTestUtils/MEF/ExportProviderCache.SimpleAssemblyLoader.cs
- UnitTests/CommonTestUtils/MEF/ExportProviderCache.SingleExportProviderFactory.cs
- UnitTests/CommonTestUtils/MEF/ExportProviderCache.cs
- UnitTests/CommonTestUtils/MEF/TestComposition.Hash.cs
- UnitTests/CommonTestUtils/MEF/TestComposition.cs
- UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Use MEF tp compose and reference the following types:
- `AppTitleGenerator`
- `RepositoryDescriptionProvider`
- `WindowsJumpListManager`
- manual
- unit tests
----
> Start using MEF

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.resx
- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
- GitUI/Translation/English.xlf
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- Add subheadings
- Group related settings
- Invert wording - from "don't" to "do", which is easier to grasp.
----
> Update layout of ConfirmationsSettingsPage

- GitCommands/Settings/AppSettings.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Kudos to @mstv for persisting.
> Addendum to #9372

- contributors.txt
Adding my name to the contributors document.
----
> Sign contributors document

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
The commit count handles the GitStatusMonitor that updates the commit count.
This is done in a number of situations, also when refreshing the grid.
RevGrid loading commits could be finished after the git status is finished
and should not reset the commit count.
This probably very seldom a problem in 3.5 or master before #9393, git-status is slightly delayed after the request, so the artificial commit that normally is added very early should be affected.
If you check out the first commit in a repo, it would be more common.
It occurs more often with #9393 that inserts the artificial commits after all other commits if HEAD is filtered out.
(Before #9393 the artificial commits were not displayed at all if HEAD was filtered, so the functionality did not exist.)
Note: Commit-count on the button …
> RevGrid commit count: Do not reset when creating artificial commits

- Packages.props
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_master_build.approved.txt
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.approved.txt
- Updated NuGet packages for all projects.
- Fixed failing AppVeyor integration tests.
- Fixed failing tests.
- Used existing tests to ensure quality.
GIT 2.21.0.windows.1
Windows 10
----
> Updated Nuget packages for all projects

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5636
Closes #5654
- manual
> Don't show delete dialog on CTRL+ALT+DEL

- GitUI/Editor/FileViewer.cs
Fixes #9319
Previously, when performing line patches and Git reported a message, GE displayed it.
With more recent Git versions, there are messages also when the lines were applied without problems.
This PR only raises the popup when Git exists with an error.
Note: Git has several strategies applying patches so if one method fails, it tries another.
So the Git message may include "error: " or "warning: " also when patching was OK.
I have not found if any of these situations should be presented anyway.
This PR will not present them.
To be able to debug this also in production releases, a Trace message was added.
Maybe this should be available as a status message somehow.
That is fine tuning, I personally see no need for that.
The examples line patches a file that already have the changes, …
> Avoid popup at successful FileViewer patching

- GitExtUtils/GitUI/Theming/BrushScope.cs
- GitExtUtils/GitUI/Theming/TabControlPaintContext.cs
- GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
- GitUI/Interops/Gdi32/DeleteObject.cs
- GitUI/Theming/Renderers/EditRenderer.cs
- GitUI/Theming/SystemBrushesCache.cs
- GitUI/Theming/Win32ThemeHooks.cs
repeat #9566 in master
Tested manually in Win10, builds and runs successfully
----
> Fix leaking brushes

- GitCommands/RevisionReader.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Command.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
- contributors.txt
> Allow hiding stash references on revision grid

- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/ConfigFileSettings.cs
- GitCommands/Settings/RepoDistSettings.cs
- GitCommands/Settings/Setting.cs
- GitCommands/Settings/SettingsCache.cs
- GitCommands/Settings/SettingsContainer.cs
- GitCommands/Settings/SettingsPath.cs
- GitUI/Plugin/GitPluginSettingsContainer.cs
- Plugins/GitUIPluginInterfaces/ISettingsSource.cs
- Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
- Plugins/Gource/GourcePlugin.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- Prevent forwarding defaults and "decode", "encode" functions through the implementation
- unit tests
- mannualy
- Build 7cc873184ae101937b39a788d7a7915f59e712e0
- .NET 5.0.9
----
> Simplify the ISettingsSource class

- GitUI/BranchTreePanel/ContextMenu/MenuItemsStrings.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs
- GitUI/Translation/English.xlf
- contributors.txt
Added a few keyboard hotkeys to one menu and one dialog.
----
> Add keyboard hotkeys to one menu and one dialog

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Fixes #9615
Draft, will be updated with master sha if approved
One intention with this PR is to explain the minimal changes needed for #9700
If the monitor was inactivated while a status command was running
(minimizing/restoring the app, start a modal dialog) the current command
is canceled to give the latest data.
lock() will ensure that more than one "active" command is not running.
However, one control variable was reset also if the command was canceled
which allowed the canceled command to be followed by another.
Also changed to not request a new status command if a command is already
running. (current status should be good enough, if there are pending
changes they will be requested later).
Cherry picked changes from #9700.
Manual
I agree that the maintainer squash merge this PR (if …
> GitStatusMonitor could start multiple commands

- GitUI/UserControls/FileStatusList.cs
Cleanup from #9720/562aa41fff947436101b64f9193ecb62675493b2
Manual
----
> Simplify FileStatus list image

- contributors.txt
> signed CLA

- Packages.props
https://github.com/Maximus5/ConEmu/releases
210912 is listed as stable and no recent releases, should be used in next release.
Manual
----
> Conemu 210912

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Translation/English.xlf
Fixes #9776
- Standardize capitalization and use US English in main menu
- manual
- Build 17b4dc2519a80017845fa3e9797b5d44e7814472
- .NET 5.0.12
----
> Main menu: Standardize capitalization and use US English

- GitUI/CommandsDialogs/RevisionDiffControl.cs
Part of #9796
#9424 added Blame to RevDiff
The intention was that the Blame should be short term and diff be shown at every change as that is the intention of the Diff tab.
(Longer term in FileTree.)
However @pmiossec (as well as @RussKie somehow in the review) commented on the behavior to be to short, that you cannot follow the file.
The behavior is changed to end Blame view when the selected file is changed.
It does not matter if a file is explicitly selected or if it cannot be "followed" when changing a commit (explicitly or "blame this revision").
Manual
----
> RevDiff: Persist Blame until another file is selected

- Setup/Product.wxs
> Package missing assemblies

- Directory.Build.props
- Externals/NetSpell.SpellChecker/SpellChecker.csproj
- GitCommands/PathUtil.cs
- GitExtensions.sln
- GitExtensions/Program.cs
- GitExtensions/app.manifest
- GitUI/Avatars/AvatarDownloader.cs
- GitUI/Avatars/CustomAvatarProvider.UriTemplateData.cs
- GitUI/Avatars/GravatarProvider.cs
- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
- GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/VisualStudioIntegration.cs
- IntegrationTests/UI.IntegrationTests/Properties/AssemblyInfo.cs
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
- IntegrationTests/UI.IntegrationTests/UITest.cs
- Packages.props
- Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
- Plugins/GitHub3/GitHubPullRequest.cs
- Plugins/Gource/GourcePlugin.cs
- ResourceManager/Xliff/TranslationSerializer.cs
- Setup/Product.wxs
- appveyor.yml
- global.json
- scripts/RepoLayout.props
- scripts/native.proj
.NET 5 is nearing EOL, and .NET 6 is LTS.
> Bump to .NET 6.0

- GitUI/CommandsDialogs/FormVerify.LostObject.cs
to handle commit subjects (i.e first line) that contains ', '
Instead, use of a non printing ASCII character ('Unit Separator' 1F --made for this purpose--)  as delimiter
to highly decrease the probability to find the delimiter chosen in a commit message.
Example that will fail the regex: WIP on null_fix_github_plugin: f77395162 Try fix #Issue1, #Issue2
- Manual (Create a dangling commit with the first line of the commit message contains 1 or more ', '
- Build fbc60746e3e67fe7057f390ad7d7d38ba0704d1e
- Git 2.34.0.windows.1
- .NET 5.0.13
> LostObjects: better `log` command and regex

- GitCommands/Settings/AppSettings.cs
- contributors.txt
Fixes #8717
Register CodePagesEncodingProvider to support more encodings.
- GIT 2.35.1.windows.2
- Windows  11 Preview Build 22581.200
----
> Register CodePagesEncodingProvider to support more encodings

- GitUI/CommandsDialogs/FormClone.Designer.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormCreateBranch.Designer.cs
- GitUI/CommandsDialogs/FormCreateBranch.cs
- GitUI/CommandsDialogs/FormDeleteBranch.Designer.cs
- GitUI/CommandsDialogs/FormDeleteBranch.cs
- GitUI/GitExtensionsDialog.cs
Resolves #9491
* 150%
* 150%
- Manual at various scale factors in range of 100-200%
----
> Fix FormCreateBranch layout

- GitUI/UserControls/FileStatusDiffCalculator.cs
This affects when there are three or four selected revisions in the graph.
If no HEAD it is not possible to show the range-diff and conflict markers.
However, it is possible to see multi-diff, the diff from the (last) selected to the other revisions (not just the first).
Not important change, just simplifies testing #9935 to see that order is unchanged (and to decrease confusion).
manual
----
> Show multi revision diff also with no HEAD

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
If a repo is empty, an information banner is currently shown.
If artificial commits are shown, it would be more helpful to show them, to be able to see worktree/index files in the diff tab.
(If artificial is not shown a completely empty view is hard to differentiate to *incomplete* and the current view is kept.
Still if artificial is not shown
Manual
----
> Enable artificial commits for empty repos

- Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
- contributors.txt
Add code statistics for 1C Enterprise and 1Script files
none
----
> Add statistics for 1C Enterprise and 1Script files

- GitCommands/Git/GitVersion.cs
Updated recommended Git version to the latest release.
Manual use
----
> Git 2.37.1

- Packages.props
Updates to the latest released version
Not much changes, I see nothing that I believe affect GE.
Updating just for support
https://conemu.github.io/blog/2022/04/18/Build-220418.html
https://conemu.github.io/blog/2022/03/08/Build-220308.html
Some minor manual use myself
Considered setting this as a draft, but believe it is better if other use too
----
> ConEmu 220418

- GitUI/UserControls/FileStatusDiffCalculator.cs
Allow parents to the actual merge base be used as the
base when selecting three revisions in the grid.
Previously, multi revision diff was shown instead.
Discussed in https://github.com/gitextensions/gitextensions/discussions/10081#discussioncomment-3208979
Multi revision diff
FileStatus diff with range-diff
Manual
----
> Allow merge base to parent with three selected

- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
Fixes #10143 
Fixes #9872
(Partial) Regression in #10136 
Show dropdown when clicking rather than at focus
also in 4.0
manual
----
> Branch filter dropdown shown too often

- .vscode/extensions.json
- Suggest [Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) vscode extension  [docs](https://shd101wyy.github.io/markdown-preview-enhanced/#/). 
- Suggest markdownlint vscode extension
- Suggest Markdown Theme Kit
----
> Suggest Markdown Preview Enhanced extension

- Packages.props
https://conemu.github.io/blog/2022/08/07/Build-220807.html
Reason to update is signing of executables, which could be important later
Depends on ClamAV being green https://www.virustotal.com/gui/file/894f7b2d08ea386ed3c84e5378a6e1b8d21acdf88c0250ce99b0beb9e67f5566/detection
Manual
----
> ConEmu 220807

- Setup/Product.wxs
- contributors.txt
Fixes [#10017](https://github.com/gitextensions/gitextensions/issues/10017)
- Adjust setup config to disable installer interacting with restart manager.
- Manual
- Start firefox and multiple explorer windows.
- Install package.
- Uninstall package.
- GIT 2.37.3.windows.1
- Windows 10
----
> Disable reloading of Explorer when uninstalling.

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #10211
Path was not checked, causing recursive calls and stack overflow
Manual
----
> Ignore .gitmodules without path

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/HelperDialogs/FormBuildServerCredentials.Designer.cs
- GitUI/HelperDialogs/FormBuildServerCredentials.cs
- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildServerCredentials.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildServerCredentialsType.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerCredentials.cs
Some TeamCity instance don't have username/password auth enabled and only support oAuth. In such cases it's not possible to configure TeamCity build integration as there is no username and password to provide.
- Change `BuildServerCredentials.UseGuestAccess` from `bool` to a more flexible `BuildServerCredentials.BuildServerCredentialsType` `enum`
- Add `BearerToken` auth option
- Keep backwards compatibility with `UseGuestAccess` setting: try to read its value for initial value of `BuildServerCredentialsType`
- Handle `BearerToken` credentials type in TeamCity build server adapter
- Manual testing with TeamCity requiring Bearer token
----
:black_nib: I contribute this code under [The Developer Certificate …
> Add support for bearer-token auth type in build server adapters

- global.json
- scripts/RepoLayout.props
Update to latest version for next release.
Also a way to test the prompts to update...
Manual
- Build a2f795eac8fe7b82b8906ff07581999431bead20
- .NET 6.0.10
----
> .NET 6.0.10

- GitUI/Resources/ChangeLog.md
Fixes https://github.com/gitextensions/gitextensions/discussions/10310#discussioncomment-4096195
> Update changelog for the auto-updater.

- GitUI/UserEnvironmentInformation.cs
- Add dotnet version info to the copy output
- Git Extensions 4.0.0.15569
- Build cba315df5366fca01240d93b6e5a5077fd5e6630
- .NET 6.0.11
- Build 1401bc1c797431b64b4ce85be5b9ae79d8161be0
- .NET 6.0.11
```
Microsoft.WindowsDesktop.App 3.1.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.30 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 5.0.4 [C:\Program …
```
> Get installed dotnet runtimes

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Ignore all failing tests until  #10387 is addressed.
/cc: @vbjay
> Disable tests that fail after git v2.38.1 disabled file protocol

- GitCommands/Settings/ConfigFileSettings.cs
Fixes #10434
- First, check encodingName for null
N/A
- 👀
----
> Fixup null check for #10434

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
Closes #10478
A test only run in Debug was not changed in #10431
Manual
----
> Filters_should_behave_as_expected: Current branch is persisted

- Plugins/Gource/GourceStart.cs
- contributors.txt
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX180kdKwuRHPRJMRElRcsHtIXiKQZZY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=2x-D5oH)
Fixes https://github.com/gitextensions/gitextensions/issues/10429
- url is now a 404. Now point to https://github.com/acaudwell/Gource#readme now.
[NBug] An error occurred trying to start process
Resolved the issue by replacing old link
- GIT 
- Windows 
----
> [NBug] An error occurred trying to start process

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
Fixes #10444
- Create new user script in enabled state
- manual
- Build 3a6ebd4080da70af1ee3c83bae2fa9dcac0280d2
- .NET 6.0.10
----
> Create new user script in enabled state

- GitCommands/Settings/AppSettings.cs
Fixes not being able to run some integration test with Resharper
- being able to run integration tests from Resharper
- Launch integration tests with resharper
- Visual Studio with Resharper
----
> ﻿test: being able to run integration tests from Resharper

- GitUI/Infrastructure/PuttyHelpers.cs
- IntegrationTests/UI.IntegrationTests/Infrastructure/PuttyHelpersTests.cs
Resolves #10530
Resolves #10555
Resolves #10562
Resolves #10565
Resolves #10569
Resolves #9588
Restore the behaviour that was changed in https://github.com/gitextensions/gitextensions/pull/10357
> Do not throw if SSH key is missing

- GitUI/Themes/highcontrast_dark.css
- Setup/Product.wxs
Include a copy of dark.css as highcontrast_dark.css, see #10570
Follow up to #10516
to be included in 4.0
See #10570 
Manual
----
> Add high contrast theme file

- GitUI/CommandsDialogs/FormBrowse.cs
Resolves https://github.com/gitextensions/gitextensions/pull/10647#issuecomment-1399353345
> Add missing handler responsible for changing repos via the dropdown

- Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
Fixes #10700
Avoid exception if the Git command is not set.
Manual
----
> Set default command for BackgroundFetch

- appveyor.yml
- scripts/set_version_to.py
Fixes https://github.com/gitextensions/gitextensions/pull/10712#issuecomment-1426430168
- Cherry-pick #10648 to release/4.0 branch
----
> Avoid git warnings in CI builds

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/Translation/English.xlf
Fixes #10780
- FormBrowse: Remove "&" from `ToolTipText`
----
> Toolbar: Remove "&" from ToolTipText

- IntegrationTests/BugReporter.IntegrationTests/Properties/AssemblyInfo.cs
- IntegrationTests/UI.IntegrationTests/Properties/AssemblyInfo.cs
- UnitTests/BugReporter.Tests/Properties/AssemblyInfo.cs
- UnitTests/CommonTestUtils/Properties/AssemblyInfo.cs
- UnitTests/GitCommands.Tests/Properties/AssemblyInfo.cs
- UnitTests/GitExtUtils.Tests/Properties/AssemblyInfo.cs
- UnitTests/GitUI.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegration.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/DeleteUnusedBranches.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/GitUIPluginInterfaces.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/ReleaseNotesGenerator.Tests/Properties/AssemblyInfo.cs
- UnitTests/ResourceManager.Tests/Properties/AssemblyInfo.cs
to be able to run them more easily in VS Test Explorer
- Test Explorer in VS
N/A
----
> Tests: Add a trait/category to all the tests ('Unit' or 'Integration')

- GitCommands/Git/GitVersion.cs
Prepare for release
Manual
----
> Git 2.40.0

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes #10468
Renamed files in index requires special handling, unstaging and deleting the GitItem before resetting to the old name.
FormCommit and RevisionDiff has separate implementations. This handles the common cases selecting the Index files, but not all compare situations in RevDiff.
This is fixing an old issue that was reported when Git error exit were no longer suppressed by default.
Manual
----
> Reset renamed index files

- GitCommands/Settings/AppSettings.cs
- GitUI/BranchTreePanel/BaseRefTree.cs
- GitUI/BranchTreePanel/LocalBranchTree.cs
- GitUI/BranchTreePanel/RemoteBranchTree.cs
- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.ScriptInfoProxy.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SortingSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SortingSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SortingSettingsPage.resx
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/Translation/English.Plugins.xlf
- GitUI/Translation/English.xlf
- Plugins/AutoCompileSubmodules/AutoCompileSubModulesPlugin.cs
- UnitTests/GitUI.Tests/UserControls/CommitInfo/BranchComparerTests.cs
- appveyor.yml
A few headings were using title case
Remove experimental from "Follow renames in file history (experimental)". While the functionality could be improved, this is how Git is implemented.
Seen when updating the doc for 4.1 (would like to update the doc with this also if this is not included in 4.1).
Manual
----
> Settings: Adjust to sentence case

- appveyor.yml
Introduced in bf2b22e16cec6eb20093d5e11de24a12c79770b3
Code review
----
> Revert version update

- GitExtensions/Program.cs
- GitUI/CommandsDialogs/FormCommit.cs
> Update UI elements on the UI thread

- GitUI/UserEnvironmentInformation.cs
For trouble shooting issues like access rights, load error etc.
Included in telemetry.
Could be included in the copied info nly, like .Net versions installed
View form
----
> Portable information in EnvironmentInfo

- GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Resolves #10499 
Resolves #10600
Retry once if failure to get the list with autocomplete files.
No popup to user if fails a second time.
Candidate for 4.1, there has been 4 reported occurrences
Manual
----
> CommitAutoComplete: Retry if first attempt fail

- README.md
Fixes #10965
- adjust links to SignPath
- manual test of links
----
> update Links to SignPath

- GitUI/CommandsDialogs/Menus/CopyPathsToolStripMenuItem.cs
> Don't NRE on copy in Diff dialog

- Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
> Search only for GitExtensions.Plugins.*.dll

- Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
> Restrict search to GitExtensions.Plugins.* only to the inbox plugins

- GitUI/CommandsDialogs/FormPush.cs
Fixes #11002
Addendum to #10834
- Suppress the popup "no branch selected" on Push All
N/A
- manual
----
> FormPush: No popup on Push All

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
- Allow to save multiple files at once
- manual
- unit tests
----
> Allow "save as..." multiple files

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes https://github.com/gitextensions/gitextensions/issues/11065#issuecomment-1599591171
Fixes https://github.com/gitextensions/gitextensions/pull/11046#issuecomment-1595355058
- Always set `RevisionGrid.RowCount` to `graph.Count` on `LoadingCompleted`
- manual (reproducible with a private repo)
----
> Always set RevisionGrid RowCount on LoadingCompleted

- GitCommands/Git/GitVersion.cs
Bump recommended version for next release
https://git-scm.com/downloads
Manual
----
> Git 2.41.0

- Packages.props
Very minor changes, just keep updated
https://conemu.github.io/en/Whats_New.html
Manual use
----
> ConEmu 230724

- README.md
Replace Appget with Winget as first one is no longer maintained
> Add winget

- GitUI/UserControls/FileStatusList.cs
Fixes #11143
- Run VsIntegration only on runtime load
----
> Prevent from breaking FormCommit designer

- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.resx
- GitUI/Translation/English.xlf
- Fixup TabIndex
- Add mnemonics to GroupBox 
- Fixup RowStyles
- manual
----
> AppearanceSettingsPage: Improve keyboard navigation

- Plugins/GitUIPluginInterfaces/ObjectId.cs
using Convert.ToHexString()
Does not make a big difference, converting 100K times decreases from 18 ms to 13 ms.
However, the code is simplified, especially with #11223 (this should be merged first).
Tests exist
----
> Optimize ObjectId.ToString()

- Plugins/GitUIPluginInterfaces/ObjectId.cs
Store ObjectId in 2*uint64+1*uint32 instead of uint32 
This reduces the number of calls handling ObjectId and improves the performance slightly.
In my tests I parsed 100K references in 87ms instead of 110 ms, so loading a repo with the default 100K setting is about 70 ms faster.
See also #11222 that removes `bool Equals(string? other)` that adds duplicated calls for uint32/uint64
Further optimizations will follow, for instance for `string ToShortString(int length = 8)` reduce the code some.
(In general, the code size is reduced by this PR, only for these two methods that adds code)
Tests exists already
---- …
> ObjectId use uint64 to reduce calls

- GitCommands/Git/GitModule.cs
- GitCommands/GitCommands.csproj
- GitCommands/RevisionReader.cs
- GitCommands/StreamExtensions.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitCommands.Tests/StreamExtensionsTests.cs
- UnitTests/GitCommands.Tests/TestData/RevisionReader/reflogselector.bin
Avoid allocations, do not allocate a string when decoding Git data
Some minor cleanup, very minor improvements
Tests exists
----
> Decode revision reader directly to Span

- GitUI/CommandsDialogs/FormCheckoutRevision.Designer.cs
- GitUI/CommandsDialogs/FormCheckoutRevision.cs
Contributes to #6183
- Modernise FormCheckoutRevision
----
> Modernise FormCheckoutRevision

- GitUI/CommandsDialogs/FormCheckoutRevision.Designer.cs
> Set FormCheckoutRevision default button

- GitCommands/ServiceContainerRegistry.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitExtensions/ServiceContainerRegistry.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/LeftPanel/SubmoduleTree.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
- IntegrationTests/UI.IntegrationTests/GlobalServiceContainer.cs
Remove the static singleton and access `SubmoduleStatusProvider` via the DI
> Make `SubmoduleStatusProvider` DI-friendly

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/GitUICommands.cs
- GitUI/Translation/English.xlf
> Correctly reset unstaged changes without affecting staged

- GitCommands/Git/GitVersion.cs
> Git 2.42.0

- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Fixes: The underlying property type of `ISetting<T>` was not considered when trying to match the values.
- Do not allege to test the `AppSettings` implemented using `ISettings<T>`, test them actually!
- execute the prepared testcases
----
> Fixup ISettings<T> tests

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/ScriptsEngine/FilePromptCreator.cs
- GitUI/ScriptsEngine/FormFilePrompt.cs
- GitUI/ScriptsEngine/IUserInputPrompt.cs
- GitUI/ScriptsEngine/ScriptOptionsParser.cs
- GitUI/ScriptsEngine/ScriptsManager.ScriptRunner.cs
- GitUI/ScriptsEngine/SimplePrompt.Designer.cs
- GitUI/ScriptsEngine/SimplePrompt.cs
- GitUI/ScriptsEngine/SimplePrompt.resx
- GitUI/ScriptsEngine/SimplePromptCreator.cs
- GitUI/ServiceContainerRegistry.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
- UnitTests/GitUI.Tests/Script/ScriptsManagerScriptRunnerTests.cs
In scripts command line arguments, the user is allows to:
* specify multiple user inputs
* specify a label as a reminder of what is requested (that will appear in the title of the input popup)
* specify or build a default value (that the user could modify before validating)
Example: `bundle create {{UserInput:Bundle filename|{cLocalBranch}.bundle|}} -{UserInput:Nb commits||} {cLocalBranch}`
2 inputs will be requested.
- Unit tests
- Manual
- Build d735064e042defdc43432bcf68246cc392cc165f (Dirty)
- .NET 6.0.21
``` …
```
> Script user input improvement

- GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/Rendering/GraphCache.cs
- just refactoring and cleanup of RevisionGraphColumnProvider
N/A
----
> Cleanup RevisionGraphColumnProvider

- GitCommands/Git/GitModule.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Fixes #11469
'%' arguments gives problems in WSL with zsh
manual
----
> Quote git-log --pretty options

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
Fixes missing graph after double refresh within 200-500 ms.
Might fix #9223
- Invalidate graph column on width change
graph column with one lane (often empty)
full graph visible
- manual
----
> Fixup missing graph

- contributors.txt
> Agreed to CONTRIBUTING.md and signed contributors.txt

- GitUI/CommandsDialogs/FormCheckoutBranch.cs
Fixes #11498
- FormCheckoutBranch: Handle no current checkout
N/A
- manual
----
> FormCheckoutBranch: Handle no current checkout

- GitUI/CommandsDialogs/FormAddToGitIgnore.cs
- GitUI/CommandsDialogs/FormGitIgnore.cs
> Create .git/info/ before creating exclude file

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Translation/English.Plugins.xlf
- Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- fix(FormCommit): better manage commit template separators (to prevent adding one where not needed and see duplicate separators with nothing in between)
-JiraCommitHintPlugin: display an error message if configuration is incomplete
* Menu separators:
* Jira commit hint message:
- Manual
- Build ebc7f90a509b388f0939e8f6ecac6524fd036adb
- .NET 8.0.1
```
Microsoft.WindowsDesktop.App 8.0.1 [C:\Program …
```
> Form commit: Improve commit templates menu

- GitCommands/PathUtil.cs
- GitCommands/UserRepositoryHistory/RecentRepoInfo.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
- GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/RepositoryHistoryUIService.cs
- UnitTests/GitCommands.Tests/UserRepositoryHistory/RecentRepoSplitterTests.cs
- Sort shortening strategy in a logical way (from longer to shorter)
- Better display of "replace middle part with dots" paths when repos are in user folder
- Some refactorings
- Manual
- GIT 
- Windows 
----
> Recent repos adjustments

- GitUI/HelperDialogs/FormResetAnotherBranch.Designer.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.resx
Fixes #11644
- Do not open dropdown on special keys (`Alt` = `Menu` and `Escape`) 
- Preserve text and selection
- Open dropdown in `KeyUp` instead of `KeyDown`
- Fixup `TabIndex` and `TabStop` in order to make mnemonics work
N/A
- manual
----
> Fixup FormResetAnotherBranch ComboBox handling

- GitUI/CommandsDialogs/FormClone.Designer.cs
- GitUI/CommandsDialogs/FormInit.Designer.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FolderBrowserButton.Designer.cs
- Fix FormInit DPI issues by wrapping the radio buttons in a `GroupBox` and placing it into a `TableLayoutPanel`
- Align anchoring for buttons and labels between two forms
- Align button sizes between two forms
- Remove unused Button controls from `FormClone`
100% scaling
200% scaling (notice the radio buttons)
100% scaling
200% scaling
----
200% scaling
200% scaling
- Windows 11
----
> Fix FormInit DPI issues; align with FormClone

- GitUI/CommandsDialogs/FormVerify.cs
- Display tag as patch (to benefit diff syntax hihlighting)
- improve recovery file format detection and saving
* improve heuristic to determine file type
* better default name for recovered files (by using the file type found)
* allow user to more easily save as another (similar) file type
* tag:
* File recovery:
* tag:
* better detection of file type and better saving UX:
- Manual
- GIT 
- Windows 
----
> Improve recovery of files UX

- GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.Designer.cs
- GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.cs
- GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.resx
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Translation/English.xlf
Fixes #11343
- Convert `FormCommitTemplateSettings` to `GitExtensionsDialog`
- Fix `TabIndex` for controls in the second tab
- Adjust grammar
**At 100% scale**
**At 200% scale**
**At 100% scale**
**At 200% scale**
- Manually
- Windows 11
- 100% and 200% scaling
----
> Convert FormCommitTemplateSettings to GitExtensionsDialog; fix Dpi issues

- update-loc.cmd
Fixes[ #](https://github.com/gitextensions/gitextensions/pull/11744#issuecomment-2131204692)
> chore: fix update-loc.cmd script (following repo restructure)

- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
Fixes #
PR #11744 moved the location of the `PrivacyPolicy.md` file. This PR adjusts sources to changes.
- 
- 
- 
- GIT 
- Windows 
----
> Update privacy policy reference

- src/app/GitUI/CommandsDialogs/FormBrowse.Designer.cs
- src/app/GitUI/Translation/English.xlf
Follow up to #11571 
Just a tooltip clarification
manual
----
> fix: Clarify prune is for branches

- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
- src/app/GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.resx
- Fix DPI
- Align `Links` label to the `left`
This "bug" has made me both sad and angry.. look at the _200% before_ screenshot.. "drowners-donut" icon is not clickable. In order to get the link, I had to make a screenshot and use OneNote's OCR to copy the text! I honestly thought this was an incarnation of the most evil UX I've ever encountered....... turns out it's a DPI issue 😡
100%
200%
100%
200%
- Manually with 100% and 200% scaling
- Windows 11 4K 200% scaling
----
> Fix Revision Links settings page DPI

- src/app/GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
To simplify debugging of parsing of GE processing
of Git output.
Related to discussions in #11843, #11831
manual
----
> feat: Unprintable chars in cache viewer

- src/app/GitCommands/Git/GitVersion.cs
Recommend the latest release version
manual use
----
> feat: Recommend Git 2.46.0

- src/app/GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- src/app/GitUI/GitUICommands.cs
Resolves #11906
- manually
- GIT 
- Windows 
----
> Use "real" GitUICommands instance

- src/app/GitUI/CommandsDialogs/FormPush.cs
by retrieving the gitref corresponding to local branch combobox
fixes #11899
- Manual
- GIT 
- Windows 
----
> fix(push): fix tracking reference not well selected

- contributors.txt
Fixes #
- 
- 
- 
- 
- 
- 
- GIT 
- Windows 
----
> Singed for contributing 

- Directory.Packages.props
- eng/Publish.targets
- src/app/GitExtensions/GitExtensions.csproj
- tests/Directory.Build.props
See https://github.com/advisories/GHSA-cmhx-cq75-c4mj
----
> Address  CVE-2019-0820

- Directory.Packages.props
No specific reason to update, just preparing for .net9 and c#13 that potentially need updates
We had a beta before, this beta is a year old so it should be considered "stable".
Build
----
> chore(stylecop): update to 1.2.0-beta.556

- src/app/GitCommands/RevisionReader.cs
Fixes #12055
- fix(`RevisionReader.GetRevision`): Avoid hang in `StandardError.ReadToEnd` on lengthy `StandardOutput`
- The other usages of `GitCommandRunner.RunDetached` are not affected as they do not read `StandardError` at all.
- Extract `GetRevisionAsync` as proposed by Roslyn analyzer
N/A
- manual
https://github.com/mstv/test_lfs/tree/test_long_commit_body
----
> fix(RevisionReader): Avoid hang on lengthy StandardOutput

- src/app/GitUI/CommandsDialogs/FormFileHistory.cs
Fixes #12107
- `FormFileHistory`: Do not call `GetFileBlobHash` for artificial revisions, use `File.Exists` insteads
N/A
- manual
----
> fix(File History): Handle artificial commits

- src/app/GitUI/UserControls/FileStatusList.cs
- `FileStatusList`: Enable `nullable` except for comparers (which will be removed in a follow-up anyway)
----
> chore(FileStatusList): Enable `nullable` decoration

- src/app/GitExtUtils/GitUI/Theming/ColorHelper.cs
- src/app/GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
Preparation for https://github.com/gitextensions/gitextensions/pull/12111
Simplify review of the theme update.
This PR does not change behavior for the invariant theme.
There may be tweaks required to the theme handling in https://github.com/gitextensions/gitextensions/pull/12111 when that is actively reviewed, that review should be based on this (and similar) PRs.
Will likely be merged together with similar preparing PRs.
This is related to the change in #12123
Review
----
> fix: MakeBackgroundDarkerBy on current theme

- src/app/GitExtUtils/GitUI/Theming/AppColor.cs
- src/app/GitExtUtils/GitUI/Theming/AppColorDefaults.cs
- src/app/GitExtUtils/GitUI/Theming/OtherColors.cs
- src/app/GitUI/Themes/invariant.css
- src/app/GitUI/UserControls/FileStatusList.cs
- src/app/GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
- src/app/GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Change OtherColors.InactiveSelectionHighlightColor to a themeable color.
It requires tweaking for dark mode.
This PR has no change for the default theme.
Review/Visual
----
> fix: InactiveSelectionHighlight in theme

- src/app/GitUI/Editor/FileViewer.Designer.cs
> fix(diff): fix switch back to "Patch" diff appearence

- src/plugins/BackgroundFetch/BackgroundFetchPlugin.cs
followup of 2a4f80a07072f4e16ff84eba537e9f83549d03eb / #12192
Fixes #6457
(fix of a bad last minute refactoring made in #12192 )
- Manual
- GIT 
- Windows 
----
> fix(BackgroundFetchPlugin): Fetch on repo opening when periodic fetch enabled

- src/app/GitUI/UserControls/FileStatusList.cs
Addresses https://github.com/gitextensions/gitextensions/pull/12312#issuecomment-2826882118
- `FileStatusList`: Expand file tree if filtered to less than 100 files
- manual
----
> feat(file tree): Expand if filtered to less than 100 files

- src/app/GitUI/HelperDialogs/FormResetCurrentBranch.cs
- `FormResetCurrentBranch`: Update submodules if not disabled
same as for checkout branch / commit
N/A
- manual
----
> feat(reset current branch): Update submodules if not disabled

- .github/PULL_REQUEST_TEMPLATE.md
- .github/copilot-instructions.md
- .markdownlint.json
- .vscode/settings.json
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- setup/assets/Logo/README.md
- setup/assets/PrivacyPolicy.md
- setup/installer/README.md
Add .markdownlint config with exclusions and fix obvious style. html and generated pages ignored
The extension in VS Code is optional. It could be added to a VS Code workspace file as recommended
update versions for latest version in README
add VS Code default solution
manual
----
> doc: markdownlint

- src/app/GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes occasional no or double diff loading and not working "go to line number"
e.g. when going from commit ec0334245ca507ce6459fbcdffd981a61d50a447 to eebca9cf9c4a5de92fbb3e3e2edd91252a6f612f
`RevisionDiffControl`:
- Resolve race condition between throttled `SelectedIndexChanged` notification and direct call of `ShowSelectedFile` after selection with suppressed notification
- `ShowSelectedFileDiffAsync`: Do not evaluate `DiffFiles.SelectedItem` twice
N/A
- manually with debug instrumentation
----
> fix(file selection): Resolve race condition

- src/app/GitUI/CommitInfo/CommitInfo.cs
Fixes #12385
`CommitInfo`: Avoid NRE by cancellation before re-assigning `_revision`
N/A
----
> fix(CommitInfo): Avoid NRE

- src/app/GitCommands/Git/GitModule.cs
Fixes #12355.
- Manual
- GIT 2.47.0.windows.2
- Windows 10
----
> Consider non-existent config setting for remote branch

- src/app/GitUI/UserControls/PatchGrid.cs
Fixes #12456
Add debug assert, avoid exception
----
> fix: assert in patch grid

- GitExtensions.sln
- contributors.txt
Fixes #
Paths in sln
- Loaded in VS 2022
----
> Fix GitExtensions.sln

- eng/GitExtensions.ruleset
- src/app/GitCommands/Remotes/AzureDevOpsRemoteParser.cs
- src/app/GitUI/CommandsDialogs/FormBrowse.cs
- src/app/GitUI/CommandsDialogs/FormSparseWorkingCopy.cs
- src/app/GitUI/CommandsDialogs/FormSubmodules.cs
- src/app/GitUI/GitUI.csproj
- src/plugins/Bitbucket/BitbucketRequestBase.cs
- src/plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
- src/plugins/Statistics/GitImpact/FormImpact.cs
Fix obsolete code for .net10
Reenable some code analyzers disabled in .net9 update
Manual
----
> fix: prepare for .net10
