GitPlugin/Commands/Commit.cs, GitPlugin/Commands/CreateBranch.cs, GitPlugin/Commands/GitIgnore.cs, GitPlugin/Commands/Merge.cs, GitPlugin/Commands/Pull.cs, GitPlugin/Commands/Push.cs, GitPlugin/Commands/Rebase.cs, GitPlugin/Commands/Remotes.cs, GitPlugin/Commands/Stash.cs, GitPlugin/Commands/SwitchBranch.cs
By some reason many commands enabled on subset of solution item types.
In this PR I swicth _some_ commands to be enabled always: Commit, Create Branch, Git Ignore, Merge, Pull, Push, Rebase, Remotes, Stash, Checkout Branch.
I am not sure - is it bug or by design. But seems pretty weird to allow create branch when file selected and disable when selected folder.
Some other commands, like Apply Patch need to be reviewed to be sure if it is really valuable to disable them when folder selected or nothing selected.
=> VS Plugin: Allow some commands on all targets. Closes #2590

GitUI/UserControls/RevisionGrid.cs
When node not found - filtredCurrentCheckout == null. This raise NullReferenceException in Revisions.IsRevisionRelative and HighlightBranch.
=> Don't try highlight node when it is not found. Closes #2597

Plugins/Statistics/GitStatistics/CodeFile.cs
Added additional support for recognition of markup language comments.
Added aspx and cshtml comment detection support (see above).
Changed string trimming and comparisons for performance gain on line processing.
=> Fixes in GitStatistics Plugin

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitExtensionsTest/GitCommands/Git/GitCommandHelpersTest.cs, GitUI/CommandsDialogs/FormRemotes.cs, GitUI/FormRemoteProcess.cs
When fetching, etc. from a remote repository via a ``ssh://user@host/path`` url, that is not a known host, plink can cause "Host does not exist" errors. This has already been fixed for the connection test.
This can be reproduced with ssh repository links for sourceforge.
I extracted the url fixing code from FormRemote into it's own method and added calls to it in the FormRemoteProcess.
=> Fixed calls of plink for host key caching with invalid urls

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.cs, GitUI/UserControls/RevisionGridClasses/FollowParentRewriter.cs
This contains a new setting to follow only exact renames, which should satisfy use cases in #2329 and #2589.
I also noticed that with "follow renames" disabled "--follow" was still being passed to git, and fixed that.
=> Follow only exact renames setting added

GitExtensions/GitExtensions.csproj, GitExtensions/copy_plugins.cmd
This PR fixes handling of whitespaces in the *copy_plugins.cmd* build script (issue #2657).
When the Git Extensions repo is cloned (on Windows) to a local path containing whitespaces (e.g. C:\Temporary Files\Git Extensions) the build script copy_plugins.cmd fails because the path ends up malformed (e.g. as C:\Temporary).
=> Fixed issue #2657: Build script handling of whitespace characters

GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
Minor enhancements:
1. I didn't like the very curvy lines in the graph.  This commit smoothes them significantly.
2. The inner loop recalculates the end points and control points.  The commit precalculates what's needed for  slightly better performance, and readability.
Before and after:
=> Draw smoother Bezier curves; Cache points outside loop

GitUI/SpellChecker/EditNetSpell.cs
If IME is starting composition, input is canceled by AutoCompleteTimer_Tick method calls.
=> Fixed issue #2301: Fix IME error.

GitUI/CommandsDialogs/FormAddToGitIgnore.cs, GitUI/Translation/English.xlf, GitUI/Translation/Russian.xlf
In dialog FormAddToGitIgnore exists preview list of ignored files which updated on every edited symbol in pattern edit box.
On big repositories it can take relatively long time for update preview list, so editing pattern become annoing.
Implemented retrieve ignored list in background in separate thread.
Added translations to Russian language.
=> Enhancement: update preview list of ignored files in background

GitUI/CommandsDialogs/FormGitIgnore.cs, GitUI/CommandsDialogs/FormGitIgnore.resx, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf
Makes capitalisation consistent, and replaces _build_ with _built_.
This change was applied across translations as well.
=> Fix typos in .gitignore template text

GitCommands/Config/SettingKeyString.cs, GitCommands/Git/AuthorEmailEqualityComparer.cs, GitCommands/GitCommands.csproj, GitCommands/Settings/AppSettings.cs, GitExtensionsTest/GitExtensionsTest.csproj, GitExtensionsTest/GitUI/AuthorEmailBasedRevisionHighlightingFixture.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormFormatPatch.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs, GitUI/GitUI.csproj, GitUI/Script/ScriptRunner.cs, GitUI/UserControls/AuthorEmailBasedRevisionHighlighting.cs, GitUI/UserControls/RevisionGrid.Designer.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
Adds highlighting of user's commits. This feature comes in handy (at least for me) when you are skimming through the commits while looking for something related to your work.
Commits are matched with current user's email address. The feature is enabled by default and can be configured in the 'Settings' dialog on the 'Colors' page. Commits are highlighted with LighYellow color by default.
=> Highlighting of authored commits

GitUI/GitUICommands.cs
Fixes #2493.
Checks whether the current thread has a message loop, then choose Show instead Application.Run.
=> Fixes #2493 StartBrowseDialog failed after clone.

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs, GitUI/Script/ScriptRunner.cs
{sHashes} is expanded to hashes of all the selected commits separated by space.
Hashes are ordered in selection order: first selected commit hash goes first.
Plus fix for "Specify 'Current Revision Branch':" window when no "current branch" argument is given. Closes #2302.
=> Ability to run scripts with several selected commits: {sHashes} argument

Plugins/Statistics/GitStatistics/FormGitStatistics.Designer.cs, Plugins/Statistics/GitStatistics/FormGitStatistics.cs
Resized split containers to be of equal sizes on all tabs:
> Before:
> ![before1](https://cloud.githubusercontent.com/assets/11020536/6657992/f3ce86ec-cb63-11e4-9808-5f5dd116ef2a.gif)
After:
> ![after1](https://cloud.githubusercontent.com/assets/11020536/6657993/f707bdba-cb63-11e4-832f-b850bdbec6d2.gif)
Reduce pie chart flickering on window resizing:
> Before:
> ![before2](https://cloud.githubusercontent.com/assets/11020536/6658030/591ef094-cb65-11e4-84e1-1b6603e52080.gif)
After:
> ![after2](https://cloud.githubusercontent.com/assets/11020536/6658032/5d2c0eba-cb65-11e4-9f7c-9fc5948dce23.gif)
Set minSize for split container panels and form to prevent pie chart overlapping the text on window resizing:
> Before:
After:
=> Statistics plugin improvements

GitCommands/Git/GitCommandHelpers.cs, GitExtensionsTest/GitCommands/Git/GitCommandHelpersTest.cs, GitUI/CommandsDialogs/FormRemotes.cs, GitUI/FormRemoteProcess.cs
fix ssh:// with port not working with Putty
Previous pull request is with bug and wrong test expect result. It's now  fixed.
=> fix ssh:// with port not working with Putty

GitUI/CommandsDialogs/FormCommit.cs
Fixes #2666 
NOTE: This pull request repeats #2668 but targets 2.48 explicitly. #2668 supposed to target 2.46 but there is no a **release/2.46** branch anymore.
=> Make CommitForm title refreshable

GitUI/CommandsDialogs/FormResolveConflicts.cs
Fixed https://github.com/gitextensions/gitextensions/issues/2761 issue
=> Fixed 'ArgumentOutOfRangeException when right clicking of the the table header of 'Resolve merge conflicts' dialog

GitUI/CommandsDialogs/FormClone.cs
The more common use-case (one should expect) is to copy the repo URL from a website or an online host (f.e. GitHub) and clone in GitExt. This should be more common than typing in the URL manually.
This PR is to automatically detect if the clipboard holds a Git URL and use that for the "Repository to clone" field in the Clone dialogue. If no URL is detect, the default is left as-is (which is the destination directory).
=> Use the repository URL from the clipboard if available.

GitUI/CommandsDialogs/FormCreateBranch.Designer.cs, GitUI/CommandsDialogs/FormCreateBranch.cs
Use Shown event to set focus on branch name textbox in Create Branch form.
For some reason Load event is fired too early and it's effects are negated so Shown event is used instead.
=> Use Shown event to set focus on branch name textbox in Create Branch form

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf
I've helped multiple teams learn to use git using Git Extensions. The "Merge", "Rebase" and "Pull" menu items continue to be a source of confusion as the text is too generic. Reword to clarify the actual functionality of each menu item.
- "Merge" is now "Pull - merge"
- "Rebase" is now "Pull - rebase"
- "Pull" is now "Open pull dialog..."
Before:
After:
=> Clarified wording for Pull dropdown menu, now matches tooltips.

GitUI/SpellChecker/EditNetSpell.cs
Clipboard.SetText throws exception when the text is null or empty. See https://msdn.microsoft.com/en-us/library/ydby206k.aspx
=> Application crashes when an empty string is pasted as a commit message

GitCommands/RevisionGraph.cs, GitUI/UserControls/RevisionGridClasses/FormRevisionFilter.cs
The problem was in double `--` in the command line. The first one was added before file filter
if it's enabled, the second one was always added to the end of command line (#2700).
The problem reproduced only with `--follow` option in the command line
("Detect and follow renames"check box in Git Extensions).
The fix is to always add `--` before file filter (it doesn't matter if it's enabled or not).
=> Fix empty blame and file history dialogs #2822

GitUI/CommandsDialogs/FormCommit.cs, GitUI/Hotkey/HotkeySettingsManager.cs
This change set adds a hotkey for showing the file history to the Commit Dialog for a selected files in the staged and unstaged area.
=> fixes issue #2821 additional hotkeys in Commit Dialog

GitUI/FilterBranchHelper.cs, GitUI/Resources/ChangeLog.md
Disable the branch filter when no repository selected. 
Fixes #2786
=> Branch filter throws null reference exception when no repository selected

GitCommands/RevisionGraph.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/FilterRevisionsHelper.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/FormRevisionFilter.cs
The problem was in double '--' in the 'git log' command line (again :)
We have three sources for 'git log' command line:
1. FormRevisionFilter that can add '-- filename' filter
2. Quick filter that cannot filter by file name
3. FixedFilter set by FormFileHistory always adds file name
All that sources were simple concatenated in RevisionGrid to get resulting filter for 'git log' command line.
But if the first filter contained '-- filename' options, all the following options were treaded as file names.
After my last fix the first filter always added '--', so other filters didn't work.
In this commit I split one Filter string into two strings: RevisionFilter and PathFilter.
RevisionFilter contains 'git log' arguments that filter commits (--grep, --author, --since, etc.)
PathFilter contains …
=> Fix quick filter and wrong graph in File History

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.cs, GitUI/Translation/English.xlf
After migrating from svn to git we still use our old commit message guidelines. Therefore the second line is not always blank. I understand that this is convention in git, but it should not be enforced by gitextensions.
=> Removed adding of newline after first line in commit message

GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
Leave it for the `GC` to collect since there's no particular reason that the form needs to be disposed manually.
This is an additional pull request to #2858 to fix the problem where the `FormUpdates` closes when no updates found.
See @jbialobr 's comment on #2858.
Fixes #2692
=> Remove the dispose so the dialog keeps open when no updates found.

GitUI/CommandsDialogs/FormCommit.cs, GitUI/SpellChecker/EditNetSpell.cs
If Undo (Ctrl-Z) was used to undo a line that was created due to
auto-wrapping, the result was an infinite loop.
UndoHighlighting() invokes Undo() repeatedly, but if that undo removes
a line break introduced by auto-wrap, Message_TextChanged() runs
immediately and re-wraps it, causing UndoHighlighting() to continue
trying to undo forever.
This fixed the issue by not performing auto formatting during an undo
operation. This should not affect the resulting functionality  because
those undo operations should only restore text that has already
been auto-formatted anyway.
=> Fix infinite loop bug during undo with auto-wrap

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormCherryPick.Designer.cs, GitUI/CommandsDialogs/FormCherryPick.cs
States of the checkboxes are persisted before the form closes.
Fixes #2846.
=> States of checkboxes in the Cherry-pick dialog are persisted to settings

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitItemStatus.cs, GitCommands/Git/GitModule.cs, GitCommands/System.cs, GitExtensions.VS2013.sln, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
Fixes #2889 
:memo: The visibility of the context menu commands are not updated according to the current selection status. However, the **Do not assume unchanged** command only shows when the user has selected **Show assume unchanged files**.
:memo: A diff does not show for files that are assumed unchanged, even if they changed. This doesn't seem to be a problem and I wasn't sure the right way to fix it, so I left it for another time.
=> Implement support for --assume-unchanged

GitCommands/Settings/AppSettings.cs, GitUI/Editor/FileViewer.cs
Needed for people working with files in DOS codepage for Latin 2 languages (Central and Eastern Europe)
=> DOS Codepage 852 added into supported encodings

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs, GitUI/Script/ScriptRunner.cs
{WorkingDir} Parameter could be used even in the script path to be able to call the scripts saved in the repository folder (needed for relative path) or pass the folder as parameter to scripts.
=> {WorkingDir} Parameter for Scripts 

README.md
On http://gitextensions.github.io/ the download release points at https://github.com/gitextensions/gitextensions/releases/latest not SourceForge.
=> Point downloads to the same place as homepage does

GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
Setting CurrentCell through its callback calls ShowRevisionGraph(),
which calls _backgroundEvent.Set()
Assume locking _backgroundEvent should be done earlier like
in other functions
Fixes: https://github.com/gitextensions/gitextensions/issues/2977
=> Avoid deadlock by the "ordered locking" approach

GitExtensions/GitExtensions.Mono.csproj, GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
This PR closes #2712 
The file was missing from mono project version.
Because of this app could crash on typing commit message. 
Fix was extracted from @ArsenShnurkov's bigger PR: https://github.com/gitextensions/gitextensions/pull/2716
=> Linux: embedded AutoCompleteRegex.txt into GitExtensionsMono.csproj

GitUI/CommandsDialogs/FormCommit.Designer.cs
Panel with textbox was put in the wrong column.
Before:
After:
=> Linux: fixed commit message textbox not being resizable

GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
On Windows when user closes dialog, its DialogResult is set to Cancel. But on Linux/Mono it remains None for some reason.
And we were using DialogResult.None as an indicator for an attempt to load non-existing directory => so we didn't allow dialog to close.
Simplified code to not use DialogResult checks.
=> Linux: fixed Open repository form not closable

GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs, GitUI/CommandsDialogs/FormCheckoutBranch.cs
I rearranged some layout code so Linux version doesn't go crazy while dealing with docking properties.
Before fix:
After fix:
=> Linux: fixed checkout branch dialog layout

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.cs
Fixes #1713 
There were tiny layout issues that led to inconsistent behavior between Windows and Linux versions.
=> Linux dashboard fix

GitCommands/Git/GitModule.cs
which is now returned by the `git branch` command output:
"(HEAD detached at c299581)"
See https://github.com/git/git/commit/4b06318664638d306cad920fd86eb63b69739310
=> Manage new format to detect detached HEAD (Git >v2.4)

GitUI/CommandsDialogs/SettingsDialog/Plugins/PluginSettingsPage.cs
Attempting to view the settings for the background fetch plugin causes a nullref in the code, as decribed in #2860.
The fix attemps to ensure that `GetControl()` is called on the form settings elements before using the `UserControl` property, so that it does not throw when `_control` is null (because it was not initialized).
I'm not exactly sure if this is the proper fix, but doing that solved the issue for me.
=> Fix for nullref when displaying settings for the Periodic Background Fetch plugin

GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
Added unquoting.
Added ignoring of certain exceptions which might result from invalid %PATH% while checking for file existence, assuming it does not exist.
#2924
=> "Illegal Characters in Path" if %PATH% Contains Quotes #2924

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/Resources/ChangeLog.md
It seems the calling of `Process.WaitForExit` on the UI thread blocks the message queue. Moving the `InTheMiddleOfConflictedMerge` (which calls `RunGitCmd` and subsequently `Process.WaitForExit`) to background thread solves the problem.
It works for me perfectly on window7 64 bits and windows8.1 64 bits
Fixes #2797, Fixes #2570
=> Fix bug where unable to restore the window if minimized by win+d.

GitCommands/CommitData.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitRevision.cs, GitCommands/RevisionGraph.cs, GitUI/CommandsDialogs/FormArchive.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCherryPick.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormRevertCommit.cs, GitUI/Script/ScriptRunner.cs, GitUI/UserControls/CommitSummaryUserControl.cs, GitUI/UserControls/RevisionGrid.cs
PR #1477 added ability to find a commit by SHA hash in quick filter.
If the value in quick filter looks like a SHA hash, Git Extensions removes
--grep command line option and adds _MessageFilter and _ShaFilter
to RevisionGridInMemFilter. RevisionGridInMemFilter filters revisions
with the required SHA hash and revisions that contain the SHA hash
in the commit message (GitRevision.Message). So, it should not have
break anything. But the problem is that GitRevision.Message contains
only commit subject, not the full commit message.
In the first commit I renamed GitRevision.Message to
GitRevision.Subject to avoid such mistakes in the future.
In the second commit I added filling of GitRevision.Body (it was null) and using it
for filtering in RevisionGridInMemFilter. It's removed after filtering …
=> Fix search for commit hash or large number in commit messages

Setup/Product.wxs
Building installer from a clean working copy failed to find the
Newtonsoft.Json assembly in the Release folder.
=> Let WiX grap Newtonsoft.Json from package folder

GitExtensionsShellEx/GitExtensionsShellEx.cpp, GitExtensionsShellEx/GitExtensionsShellEx.h
The Git Extensions shell extension was caught leaking GDI objects on my Windows 7 computer, eventually leading to the explorer.exe process dying an untimely death.
I fixed this leak and also cleaned up other code in the shell extension, fixing other undefined behavior and leaked resources as I found them.
=> Fix Shell Extension leaks and general cleanup

GitUI/UserControls/RevisionGrid.cs
Allow users to select tags when using 'Merge with current branch...' from the context menu of a commit.
=> Fix Issue #2458 Allow merging with tags

GitUI/UserControls/RevisionGrid.cs
`selectedIndexChangeSubscription.Dispose();` in `FileStatusList.DisposeCustomResources` throws an `InvalidOperationException`,
saying that `Invoke or BeginInvoke cannot be called on a control until the window handle has been created.`
Steps to reproduce:
* Double click a commit, it pops up the commit diff dialog
* Close the dialog
* Close the application.
* An `InvalidOperationException` occurs.
=> Fixed an exception when closing the application after closed FormCommitDiff

GitCommands/Git/GitModule.cs
Since v2.5 git supports worktrees whose gitdirs are located under the same .git as submodules,
so submodule detection string should be more specific to distinguish them.
=> #2929 Fixed submodule's gitdir detection to avoid false positives for worktree gitdirs

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormSparseWorkingCopy.cs, GitUI/CommandsDialogs/FormSparseWorkingCopyViewModel.cs, GitUI/GitModuleControl.cs, GitUI/GitUI.csproj, GitUI/GitUICommands.cs, Plugins/GitUIPluginInterfaces/IGitUICommands.cs
Initial support for sparse working copies (#2289).
This implementation adds a single main menu command which shows a dialog to control three aspects of sparse working copies:
* Enable/disable sparse for this repo in git config.
* Edit the pass filter.
* Refresh working copy against the current set of the rules.
Tried to make it self-explanatory somewhat.
Dialog view when sparse not enabled:
Dialog view when sparse is enabled (enable/disable toggles between these views):
=> Feature #2289 – Sparse Checkout

GitUI/CommitInfo/CommitInfo.cs
Mono has some problems with GetPreferredSize so just let calculate the stuff
on our own.
Since System.Windows.Forms is mostly abandoned on Mono this probably
the only way to address this problem.
=> Fix height calculation for RevisionHeader in the CommitInfo panel on Linux

GitExtensions/app.config, GitUI/BuildServerIntegration/BuildServerWatcher.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs, Plugins/BuildServerIntegration/TfsInterop.Vs2012/TfsInterop.Vs2012.csproj, Plugins/BuildServerIntegration/TfsInterop.Vs2012/packages.config, Plugins/BuildServerIntegration/TfsInterop.Vs2013/TfsInterop.Vs2013.csproj, Plugins/BuildServerIntegration/TfsInterop.Vs2013/packages.config, Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs
Fix #2984 and #3041
- Added a binding redirect to 6.0 version of newton json, in case any dll is referencing  v4.5, for example `System.Http.Format.dll`
- Changed the MEF to load plugins into individual containers: the build server adapters were failed to be loaded because the MEF container tries to load all dlls from the Plugins folder in one go, the whole loading will be cancelled if one of the plugins failed. And the MEF also tries to load non-plugin dlls(more specifically, `System.Net.Http.dll`, `Microsoft.TeamFoundation.Build.Client.dll`). If any of these dlls failed to find their reference, no plugin can be loaded.
=> Mistery Newton Json Version 4.5

GitUI/CommandsDialogs/FormBrowse.Designer.cs
If you copy the changed lines to notepad++, you will see a `?` at the end, hence failed to build.
Fixes #3185
=> Invalid Character in FormBrowse.Designer.cs

GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
If an attempt is made to enter a message in the commit dialog
when one of the changed files is not readable, GitExtensions
terminates with an unhandled exception.
Catch the exception thrown during the failed read operation,
and ignore it.
=> Fix 3042: crash on commit dialog during autocomplete

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Statistics/ImpactLoader.cs, GitUI/CommandsDialogs/BrowseDialog/FormCommitCount.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/Translation/English.xlf, Plugins/GitUIPluginInterfaces/IGitModule.cs
FormBrowse enumerates the status of its submodules whenever the form is
activated or when the submodule drop-down arrow on the toolbar is clicked.
If there are many submodules (e.g. > 100), it slows down Git Extensions to a
crawl such that Git Extensions is practically unusable.  Three causes of this
extreme sluggishness have been identified via profiling:
* Code that gathers the list of submodules and initiates asynchronous image
gathering is slow (roughly 0.5 to 1.0 seconds for > 100 submodules).  This
causes the UI to hang; the hang is exacerbated by background image
gathering as the UI must compete with the background threads.  We fix
this problem by offloading this job to a background task, and show a
placeholder "Loading..." menu item while this takes place.
* Code that adds …
=> Moved submodule enumeration on FormBrowse to a background task.  Fixes #2769

GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
The fix is to try `/bin` before `/usr/bin`. Both Git bash and reading system config work fine with the fix.
I'm not sure if we need `/usr/bin` at all because `/usr` is invalid prefix for `/etc/gitconfig`. But it was added in 5f8e660be5c913f26b59822530956478a8b58579 for some reason.
Closes #2950.
=> Fix automatically configured path to linux tools

GitCommands/RevisionGraph.cs
GitUI.FileStatusList.SetDiff(GitRevision) expected GitRevision.ParentGuids to be null or empty,
but it had one element with empty string. The fix is to make ParentGuids empty for root commits.
Closes #3067.
=> Fix diff for the root commit

Setup/packages.config
=> Fix missing 7-Zip binary when building Mono archive

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormPush.cs, GitUI/GitUI.csproj, GitUI/UserControls/ComboBoxHelper.cs
should solve #3207, with a min-width of 300 and a max-width of 600
__before with 2.48.05__
__after__
=> dynamic combobox-width calculated based on combobox containing items

Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.Designer.cs, Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.cs, Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs, Plugins/BuildServerIntegration/TfsIntegration/Settings/TfsSettingsUserControl.Designer.cs, Plugins/BuildServerIntegration/TfsIntegration/Settings/TfsSettingsUserControl.cs, Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs, Plugins/GitUIPluginInterfaces/BuildServerIntegration/BuildServerSettingsHelper.cs, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj
For Tfs and TeamCity server integration plugin, that accept Regex to follow
build results of multiple projects, a crash could occur if the regex saved was not
a valid regex.
This commit:
* prevent the saving of a not valid regex
* alert the user that the regex is not valid
* disable the build server integration plugin if a not valid regex was already saved
=> Prevent crash due to invalid Build CI project name regex saved

GitCommands/AsyncLoader.cs, GitUI/CommandsDialogs/FormAddToGitIgnore.Designer.cs, GitUI/CommandsDialogs/FormAddToGitIgnore.cs, GitUI/FilterBranchHelper.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/UserControls/RevisionGrid.cs, Plugins/Github3/GithubRepo.cs
Fixed the problem behind #3063 (null reference exception in the revision grid).
Fixed another null reference problem when opening the pull request dialog.
Fixed two compiler warnings (CA2213 - disposable object not being disposed in Dispose)
Fixed a typo in the git ignore dialog.
=> Fix a couple of compiler warnings and nullrefs, including #3063

GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/Script/ScriptInfo.cs
The `AfterCheckout` event can be useful to update a local search index upon branch switching.
=> Add script events: BeforeCheckout, AfterCheckout

GitUI/CommandsDialogs/FormPull.Designer.cs, GitUI/CommandsDialogs/FormPush.Designer.cs
Both "pull" and "push" user controls feature branch controls, however those controls weren't resized when the user controls were resized.
The branch controls on "push" control are placed into table layout panel control so they take same amount of space.
No functional changes, just pure UX.
=> fix: Responsive UI for branches controls

GitUI/CommandsDialogs/FormBrowse.cs
Reverts gitextensions/gitextensions#3238
Actions are not set as default, but when DonSetAsLastPullAction is checked, then always the LastPullAction is preformed, regardless of chosen menu item.
=> Revert "Pull Menu Items Should Honor the Don't Set As Default Option"

GitUI/UserControls/RevisionGrid.cs
Not perfect but should be enough.
Ideally the indicator should be part of the commit message and right aligned. But it looks overkilled to change a lot of code to fix such a trivial bug.
Fixes #3079
=> Disable the Ability to Resize the MultilineMessageIndicator

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
The diff tool for p4merge was not working and the settings remained empty.
=> Fix p4merge diff settings

GitCommands/PathUtil.cs, GitUI/CommandsDialogs/FormBrowse.cs
Now, the working directory in the console tab follow the
repository working directory when we change from repository.
Remaining in the first repository opened made no sense...
=> Add console change directory when changing repository

GitCommands/Git/GitModule.cs
Should fix #3057
Looking for (in order):
1. git-bash.exe (because manage itself "--login -i" and support mouse selection!)
2. bash.exe
3. sh.exe
Looking in different places:
1. C:\Program Files\Git
2. Git directory
3. All the folders in the PATH env variable
If we fail to find it, open a normal `cmd.exe` displaying an error message.
=> Find out in more places where is the bash shell

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormPush.Designer.cs, GitUI/CommandsDialogs/FormPush.cs, GitUI/CommandsDialogs/FormPush.resx, GitUI/Translation/English.xlf
=> Add force with lease to the advanced push options

GitCommands/Utils/EnvUtils.cs, GitUI/CommandsDialogs/FormApplyPatch.cs, GitUI/CommandsDialogs/FormClone.cs, GitUI/CommandsDialogs/FormFormatPatch.cs, GitUI/CommandsDialogs/FormInit.cs, GitUI/CommandsDialogs/FormSvnClone.cs, GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs, GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs, GitUI/GitUI.csproj, GitUI/OsShellUtil.cs, GitUI/UserControls/FolderBrowserButton.cs
FolderBrowserDialog in Windows Forms still calls the XP-era dialog instead of the much nicer Common Item Dialog seen in Windows Vista and newer (see #2787).
=> Using Common Item Dialog to select folders

GitCommands/Git/GitBranchNameNormaliser.cs, GitCommands/Git/GitBranchNameOptions.cs, GitCommands/GitCommands.csproj, GitCommands/Properties/AssemblyInfo.cs, GitCommands/Settings/AppSettings.cs, GitExtensionsTest/GitCommands/Git/GitBranchNameNormaliserTest.cs, GitExtensionsTest/GitCommands/Git/GitBranchNameOptionsTest.cs, GitExtensionsTest/GitExtensionsTest.csproj, GitUI/CommandsDialogs/FormCreateBranch.Designer.cs, GitUI/CommandsDialogs/FormCreateBranch.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.resx
Git spec imposes a number of rules on how branches are named.
The rules can be found at https://www.git-scm.com/docs/git-check-ref-format/1.8.2
The feature allows to automatically check for compliance when the user
creates a new branch (by typing in or inserting from the clipboard).
The FormCreateBranch UI is reworked to provide a toggle for the option.
------------
**Existing dialog:**
**New dialog:**
Attempting to create a branch with name `[BUG-1234] some long description located [//test/*/dir?/.lock]{3,} and <foo:bar\\can>...` yeilds the following result:
=> feature: Allow auto-normalisation of branch name

GitUI/BuildServerIntegration/BuildServerWatcher.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
Previous implementation used O(n) linear lookup with tons of memory garbage
for locating grid row index by corresponding commit's hash.
When build server integration is turned on, applying build results took enormous O(n*m),
where “n” is commit graph rows count and “m” is build results count.
Dictionary gives O(1) complexity regardless of rows count
and at the same time is lightweight from linq and GC overhead point of view
I have a huge repo with ~100K commits, where ~600-700 of them have recent build results on the CI server. In my case this optimization improved performance more than 1000 times (94 ms vs 0,07 ms per CI build). Previously I had to wait for about a minute after almost each GE operation (change repo, make a commit, pull/push, just refresh, etc). It was very annoying. Now …
=> Search graph row index by commit hash using dictionary

GitUI/CommandsDialogs/FormCreateBranch.Designer.cs, GitUI/CommandsDialogs/FormCreateBranch.cs
The branch name textbox's change event auto replaces trailing '.' and '/' chars while the user is typing.
The normalisation is now invoked only when the textbox loses focus.
Fixes #3297
=> fix: Unable to use '/' or '.' in branch name

GitCommands/Git/GitBranchNameNormaliser.cs, GitExtensionsTest/GitCommands/Git/GitBranchNameNormaliserTest.cs
Branch name normalisation now allows valid Unicode letters.
Fixes #3301
=> fix: Branch name normalisation is too restrictive

GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.resx
Also:
* adjusted alignment of all checkboxes on the page
* adjusted layout of the section to dock=fill to match the rest of the
option pages
Fixes #3307
=> fix: chkAutoNormaliseBranchName.ToolTip is wrong

GitExtensionsTest/GitCommands/Git/GitBranchNameOptionsTest.cs
Force the unit tests to run with `CultureInfo.InvariantCulture` and thus not localise exception messages
Fixes #3306
=> fix: GitBranchNameOptionsTest fail due to localized exception message

GitUI/GitUI.csproj
Running `nuget restore GitExtensionsMono.sln` creates `packages\ConEmu.Core.16.9.14.0\Build` directory (Build starts with uppercase)
There was another build error in `GitExtensionsTest/GitCommands/Helpers/PathUtilTest.cs` because of treating warnings as errors. I do not know what the intended behavior of that test is so I left out fixing it here.
Fixes #3335
=> Fix build on case-sensitive filesystems

GitUI/CommandsDialogs/FormBrowse.cs
...which should work from wherever we change of current repository.
It was only working if we open from the menu of 'recent repositories'
=> fix change of current folder in the console

GitCommands/Git/GitStash.cs, Plugins/GitUIPluginInterfaces/ISetting.cs
When the stash was made by autostash, we can't find the branch name in the stash name
Add the support for this new format (Branch name is not provided but that's not a problem
because we use it nowhere...)
* fix swallowed exception when retrieving the number of stash (so it is not displayed)
* fix crash that prevent to use the stash form once there is an autostash and to delete the stash
=> Fix crash when one of the stash is an autostash

GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
This just adjusts the verbiage on the window so that the controls more closely match the description of the operation.
Original:
Revised:
=> Adjust merge form UI as described in issue 3208.

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
As some people noted, it is sometimes useful to be able to bypass git commit hooks #1982. This is how user interface looks like:
Please consider accepting this PR.
=> Added no verify option to allow to bypass git hooks #1982

GitCommands/Config/SettingKeyString.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitRef.cs, GitUI/CommandsDialogs/FormClone.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormPush.cs, GitUI/Script/ScriptRunner.cs
Both Pull and Push forms fail to correctly select the remote, if one set, and instead default to the 1st item in the list.
Reported by @jbialobr after #3291 was merged.
=> Fix form pull incorrect selected remote

GitUI/FormRemoteProcess.cs
When using Plink and pulling or pushing to/from a remote with an untrusted host fingerprint GitExtensions offers to open plink in a new command prompt window so the user can interactively press Y to trust the fingerprint.
However, this currently does not work correctly for clone. plink is called with an emptry string instead of the remote URL. This commit fixes that.
=> Fix "Host Fingerprint not registered" Plink handling on clone

GitUI/CommandsDialogs/FormRenameBranch.Designer.cs, GitUI/CommandsDialogs/FormRenameBranch.cs
Branch renaming now auto normalises the branch name the same way as whenever a new branch is created.
Fixes #3424
=> fix: Branch rename does not auto normalise

GitCommands/Git/GitCommandHelpers.cs, GitExtensionsTest/GitCommands/Git/GitCommandHelpersTest.cs
Regular expressions used to fetch the submodule names assumed the names not to contain white-spaces. The issue #2679 shows the problem.
The fixed expressions now work correctly. Also added a test method for ensuring future changes not break support for white spaces in submodule names.
=> Fixed "Unsupported file" error with submodules. Fixes #2679

GitUI/CommandsDialogs/FormMergeBranch.cs
Pass offerCommit=false to MergeConflictHandler.HandleMergeConflicts() if "Do not commit" is checked.
Closes #3441.
=> Don't offer the user to commit after merge conflict resolution if "Do not commit" was checked before merge

GitUI/CommandsDialogs/FormCreateTag.cs
Use Control.Select() instead of low-level Control.Focus().
Closes #3372.
=> Set focus to the tag name edit control when the create tag dialog is opened

Plugins/Stash/Settings.cs
Currently it is not possible to use stash URLs with subfolders (virtual directory)
For instance this URL is not working: https://user@stash.domain.com/subfolder/scm/projec-t1/project-1.git
=> fixes stash plugin to allow subfolders in stash URL

GitUI/UserControls/RevisionGrid.cs
Show error if base commit was not selected.
Include Russian translation.
Not sure if English translation correct.
=> Fix #3534 (Ctrl+R lead to NullReferenceException)

GitCommands/Git/GitBranchNameNormaliser.cs, GitExtensionsTest/GitCommands/Git/GitBranchNameNormaliserTest.cs
Characters with decimal values between 32 and 40 are now allowed in branch names.
Fixes issue #3507.
=> Fix valid character range for branch names

GitUI/CommandsDialogs/FormPush.Designer.cs
Push dialog, Push multiple branches tab
'Delete' checkbox and branch name are not close enough to be sure that checked checkbox in the same row with desired branch. This is especially true on big display.
With 'full row select' it is more clear.
=> Full row select in Push dialog / Push multiple branches

GitCommands/Settings/AppSettings.cs
My previous pull request #2367 added the `GITEXT_PUTTY` environment variable, allowing you to set the default PuTTY directory offered in the settings dialog.
This adds the ability to override the individual paths for `plink`, `puttygen` and `pageant` using additional `GITEXT_*` environment variables.
=> Specify plink, puttygen and pageant locations with with environment variables

Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
If fetch interval is relatively big (30 minutes) then accidentally running git.exe can delay update from 30 minutes to 60 or even more (depends on you luck).
Proposed solution - retry every 5 seconds if interval started but blocked by running git.exe
=> Improvement for #3464 (Background fetch plugin - Not working)

GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
Make RichEditBox visible before insert text solves problem
=> Fix #3567 (Console Output sometime hide long text until click scroller)

GitUI/CommandsDialogs/FormPush.cs
Situation:
Branch name contains word `push` (for example `pr/fix-cmdline-in-retry-push-with-force`)
and remote reject push due to non-fast-forward
and user select `retry with force`
then word `push` in branch name was replaced with 'push --force-with-lease' by `.Replace("push", "push --force-with-lease")`
=> Fix problem with incorrect building command line arguments

GitExtensions/app.manifest
Hopefully there won't be a Windows 11.
This should be enough to fix #3569, although it mentioned there might be a problem on Windows 8, but I think it was just a guess. GitExtensions shouldn't have a problem on Windows 8 according to the `app.manifest`. BTW, who cares about Windows 8?
=> Fix bug where Windows OS version string is incorrect for Windows 10

GitUI/CommandsDialogs/FormBrowse.cs
Don't want to change the infrastructure too much, so just save the settings before logoff.
Fix #3576
=> Save the AppSetting before logoff

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
Here is no sense it insert formatted text and sometime it can break inserted text.
Use case: wiki (mediawiki engine) contains some instructions one of with contains link
User copy this snippet from Internet Explorer (no problem with Firefox) browser to 'arguments' edit box, but it is mangled by formatting
Saved text incorrect - it contains extra `<>` in URL.
=> Settings / Scripts: Do not paste formatted text to 'arguments' edit box

GitUI/CommandsDialogs/FormPush.cs
=> Fix crash of the push form when there is no remote defined

GitUI/HelperDialogs/FormRunScriptSpecify.cs
If nothing is selected in the dialog,
clicking the OK button will do nothing.
One possible fix for #3542
=> Fix #3542: Do nothing if no selection in FormRunScriptSpecify

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitVersion.cs, GitUI/CommandsDialogs/FormMergeBranch.Designer.cs, GitUI/CommandsDialogs/FormMergeBranch.cs
Signed-off-by: Kevin <kmoens@lakeco.com>
Enhanced FormMergeBranch to include 2.9.0 version requirement of --allow-unrelated-histories
added new checkbox visible if 2.9.0 or higher.
=> Enhancement to work with Git Merge --allow-unrelated-histories

.gitmodules
Enables reaching them when git protocol is blocked by firewall.
=> Use relative paths for submodules

GitCommands/Git/GitModule.cs
Fixes #3587
I've fixed this issue by adding `--no-color` to all `git diff` calls from `GitModule` class.
=> Fix 3587 - Diff view is blank if git configuration is diff.color=always

GitUI/SpellChecker/EditNetSpell.Designer.cs, GitUI/SpellChecker/EditNetSpell.cs
The Enter/Leave handlers are not called when the focus returns to the text box
after another focused window is closed.
=> Toggle the watermark in GotFocus/LostFocus event handlers (fixes #3491)

GitUI/HelperDialogs/FormCommitDiff.cs, GitUI/UserControls/RevisionGrid.cs
Do not open commit diff form as modal anymore
Otherwise, that prevent to come back to the main browse history form and use it navigate to another commit (sometime useful...)
I have also add the feature to display some data of the commit opened in the title of the form to navigate more easily between opend forms.
=> Open diff form not in modal

GitUI/UserControls/RevisionGrid.Designer.cs
Fixes build warning introduced in PR #3573.
=> Dispose the _fontOfSHAColumn field

GitCommands/Git/GitModule.cs
Strip ANSI escape codes from all git output.
Previous attempts to set environment variables to tell git not to output these do not always work. On my installation using git with msys2, git continues to emit the color codes and breaks GitExtensions' diff output and other things.  This commit fixes the issue cleanly.
=> Strip any ANSI escape codes from git command output

GitUI/CommandsDialogs/FormRebase.cs
Rollback incorrect copy-paste
Fixes a bug introduced in #3478.
=> fix: Incorrect GetRefs tags

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormPull.Designer.cs, GitUI/CommandsDialogs/FormPull.cs
Adds a checkbox to the pull form which when selected will append --prune to the command line:
When Merge is selected, the prune checkbox is still enabled:
When Rebase is selected, the prune checkbox is disabled and --prune will not be appended:
=> 2141 simplify calling prune remote branches

GitUI/Resources/ChangeLog.md
Whenever I read the changelog I want to navigate through to the referenced issues.
=> Make issue numbers in changelog hyperlinks

Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
TeamCityAdapter uses basic http authentication or ntlm with CredentialCache.DefaultCredentials
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**
It should be able to use provided credentials for ntlm authentication
**What is the expected behavior?**
Ntlm authentication should use provided credentials (if present) and successfully authorize
(this PR works well with all TeamCity instances that we have)
**Which versions of GIT and which versions of Windows are affected by this issue? Did this work in previous versions of our tool?**
Probably all versions, never worked
=> TeamCityAdapter should be able to use provided credentials

GitUI/CommandsDialogs/FormDeleteBranch.Designer.cs, GitUI/CommandsDialogs/FormDeleteTag.Designer.cs, GitUI/CommandsDialogs/FormMergeSubmodule.Designer.cs, GitUI/CommandsDialogs/FormRenameBranch.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.Designer.cs, GitUI/Editor/ColorHelper.cs, GitUI/HelperDialogs/FormResetCurrentBranch.Designer.cs, GitUI/UserControls/RevisionGrid.cs
Partially Fixes #1947 ?
(NB: Have limited time to contribute, but this seems to fix the worst of the issue)
- Change main listview background to use system colours
- Various changes to control text to use system colours
- Change system-colour to hard-coded colour for various items which have hard-coded background colours
- TODO: More colour fixes
- Before (NB: previously used a different dark theme which made the text completely invisible, as per the original bug report):
-After:
Default Windows 10 theme:
Dark Windows 10 theme:
- Tried new code on Windows 10 with borth standard and dark theme installed.
- TODO: Test on Linux/other platforms
Has been tested on (remove any that …
=> Some work to sanitise colours for dark operating system themes.

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
When the 'Console' tab is selected for the very first time the terminal initialises and receives focus. Switching to another tab and coming back to the 'Console' tab will keep the terminal focused.
Fixes #3631
=> fix: Console terminal lose focus

GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
Fix the layout stretching beyond client rectangle caused by long remote branches.
Fixes #3490, #3498
=> fix: Checkout branch layout for long remote branch

GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs
Increased the width for 'Open local repository' dialog because long paths are hard to visualize. Now it has same width as the 'Create new repository' dialog.
Before
After
Run GitExtensions from VS 2015. In GitExtensions > Start menu > click Open...
- GIT 2.10
- Windows 7 x64
=> Increased width for 'Open local repository' dialog.

GitExtensionsVSIX/GitExtCommandTable.cs, GitExtensionsVSIX/GitExtCommandTable.vsct, GitExtensionsVSIX/GitExtCommands.cs, GitPluginShared/Commands/Blame.cs, GitPluginShared/Commands/CommandBase.cs, GitPluginShared/Git/GitCommands.cs, GitPluginShared/GitPluginShared.csproj, GitUI/CommandsDialogs/FormBlame.cs, GitUI/GitUICommands.cs, GitUI/UserControls/BlameControl.cs
Fixes #2839.
- the Blame control can be started at the specified line
- commands can be started with additional arguments
- the Blame command is added to VS extension
- GIT 2.10.1
- Windows 10
=> Add Blame command to VS extension

GitUI/GitUI.csproj, GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/FormQuickGitRefSelector.Designer.cs, GitUI/UserControls/RevisionGridClasses/FormQuickGitRefSelector.cs, GitUI/UserControls/RevisionGridClasses/FormQuickGitRefSelector.resx, GitUI/UserControls/RevisionGridClasses/GitRefListsForRevision.cs
Allow to rename and delete branches and tags from keyboard.
Actions:
* F2 - rename
* DEL - delete
If there is...
* no valid branch or tag to rename or delete the action is ignored
* a single branch or tag - the respective action dialog is launched
* multiple branches or tags then a quick select dialog is launched to specify the exact ref to perform action on.
Addresses #3503
Rename (F2)
Very long branch names/tags gets constrained to 100 symbols, to reduce the risk of not fitting on user's screen.
Delete (DEL)
The quick selector shows upto 8 items without scroll. This is again to reduce the risk of not fitting on user's monitor:
=> feat: Ref rename and delete from keyboard

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.cs, GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.resx, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUI.csproj
- 
Create new form for choosing encoding.
Added support all available encodings .NET in file viewer.
-
- Git 2.12 
- Windows 10
=> Encodings in fileviewer

GitUI/CommandsDialogs/FormCommit.cs
Hello, 
This is first time when I use GitHub to contribute to somebody's else project, also I have practically 0 experience with C#; so please forgive me if I do something patently wrong.  My small contribution tries to add feature described in https://github.com/gitextensions/gitextensions/issues/1872.
=> Commit dialog honors value of `status.showUntrackedFiles'  git config.

Plugins/Statistics/GitStatistics/FormGitStatistics.cs
Fixed issue where "Lines of code" was allocated too much space on the statistics plugin pie chart.
Fixes issue #2530.
=> Fixed issue with statistics plugin.

GitUI/CommitInfo/CommitInfo.Designer.cs, GitUI/CommitInfo/CommitInfo.cs
Fix proposal for #2670: Revision header too short if Japanese font is used
It seems to be fixed:
=> Fixed issue #2670: Revision header too short if Japanese font is used

GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs
Hi 
It allows multi select and enables and disables some commands in menus based on whether single or multiple rows are selected.. as per https://github.com/gitextensions/gitextensions/issues/1845
It includes the progress bar feedback too..
This pull request has the same content of the earlier one that I canned https://github.com/gitextensions/gitextensions/pull/2832.
thanks.. rasane
=> allow multi-select in resolve conflict window #1845

GitCommands/CommitHelper.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs
- save amend checkbox state when closing form
- disable commit form minimize button when open from browse window (because that's absolutely not ergonomic)
=> Better ergonomic around commit form

GitUI/CommandsDialogs/FormAddToGitIgnore.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormGitIgnore.cs, GitUI/GitUICommands.cs, GitUI/UserControls/RevisionGrid.cs, Plugins/GitUIPluginInterfaces/IGitUICommands.cs
Fixes #2194
> :warning: This is totally untested, but I figured I could at least push a branch with a working start for this feature.
=> Implement support for .git/info/exclude

.gitignore, GitExtensionsShellEx/GitExtensionsShellEx.vcxproj, Setup/BuildInstallers.VS2017.cmd
- Able to build the installer using msbuild15/vs2017
- Run the buildinstaller.vs2017.cmd in the setup folder. 
- Install the complete_setup with the explore integration ticked
- Right click a repo and verify the gitextensions menu items are still working.
- Push a branch to a repo of a new host e.g. bitbucket, make sure the openssh will ask for password
i'm not able to test the buildinstaller.vs2015.cmd, can someone verify that buildinstaller.vs2015.cmd is still working
- Windows 10 64-bit
=> Able to build the installer in Visual Studio 2017 MSBuild15 environment

GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid.Designer.cs, GitUI/UserControls/RevisionGrid.cs
Add Reword functionality in Advanced menu.
By clicking it, it will :
- launch a git rebase interactive on one of the commit parent.
- replace automatically the first "pick" by "r".
=> Add Reword functionality in Advanced menu 

GitUI/BuildServerIntegration/BuildInfoDrawingLogic.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/Properties/Resources.Designer.cs, GitUI/Properties/Resources.resx
77.png was referenced under both "Settings" and "Icon_77".
=> fix: Remove duplicate resource reference

GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.cs, GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.resx, GitUI/Translation/English.xlf
The existing layout prevented the dialog from being resized to accommodate for longer repository names.
Also fix tab stops and set dialog results.
=> fix: Layout issues with FormRecentReposSettings

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
Fixes #1064. This is almost five year old feature-request but I still find it useful to have.
I've kept this to minimum, nothing fancy.
- _Clear List_ menu item was added into _Start_ > _Recent Repositories_;
- The _Recent Repositories_ menu item is disabled if the list is empty (VLC-like behavior).
**Before**
**After**
- Test scenario 1
1) Open several repositories to populate the list in _Recent Repositories_;
2) While dashboard is visible go to _Start_ > _Recent Repositories_ > _Clear List_;
3) Check that the _Recent Repositories_ list in the dashboard is cleared and _Recent Repositories_ menu item is disabled;
4) Close and reopen GitExtensions; Re-check step 3).
- Test …
=> Add Clear List menu item into Recent Repositories items list. Fixes #1064.

GitUI/CommandsDialogs/FormStash.Designer.cs
Fixes #3564 .
- Stretch stash file list and auto-size stash message, rather than filling space with message
- Before
- After
- Manual
- GIT 2.10.1
- Windows 10
=> Stretch stash file list rather than message

GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs, GitUI/Translation/English.xlf
Fixes #3499 .
- Changed the description of the first setting in the Git Extensions /Git Extensions page.
- Before: 
- After: 
- I built the project and took the above screenshots.
- I needed to change the English.xlf file for the change to actually appear in the UI.
- GIT 2.10
- Windows 10
=> Improve setting description in UI (issue #3499)

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
Fixes #1975.
- Adds Meld as a merge tool.
- Fixes issue with finding meld.exe.
- Verified the command starts Meld.
- GIT 2.12
- Windows 10
=> Add Meld as a merge tool

GitUI/CommandsDialogs/FormGitIgnore.Designer.cs, GitUI/CommandsDialogs/FormGitIgnore.cs, GitUI/CommandsDialogs/FormGitIgnore.resx
* GitIgnore form now has scrollbars when editing the list of ignores.
* Form layout update
=> fix FormGitIgnore layout and scroll

GitCommands/Git/GitModule.cs, GitCommands/Git/GitVersion.cs
GitExtensions recodes commit messages that differ from
`i18n.logOutputEncoding` as Git before v1.8.4 did not do this because of a
a bug. Since v1.8.4 (see commit [ecaee80 (pretty: --format output should honor logOutputEncoding, 2013-06-26)](https://github.com/git/git/commit/ecaee80) in Git repository) Git does not
have this issue anymore, but GitExtensions still relies on its buggy
behaviour.
Today we know the version of Git with no bug. Let's rely on this
knowledge.
Fixes #3707.
- Test Git version. If its version >= 1.8.4 then do not recode commit message as Git already does it
- screenshots the same as attached in #3707:
before:
When `git config i18n.logOutputEncoding = Windows-1251`
When `git config …
=> Fix commit messages that are displayed incorrectly

GitCommands/Git/GitModule.cs, GitCommands/Settings/ConfigFileSettings.cs, GitCommands/Settings/RepoDistSettings.cs, GitUI/CommandsDialogs/FormAddToGitIgnore.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormGitIgnore.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormSparseWorkingCopyViewModel.cs, GitUI/UserControls/RevisionGridClasses/IndexWatcher.cs, Plugins/FindLargeFiles/FindLargeFilesForm.cs, Plugins/Gerrit/GerritPlugin.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs
For worktrees .git subfolders are spread between $GIT_DIR and $GIT_COMMON_DIR
I worked with submodules and worktrees
- GIT 2.13
- Windows 10
=> GitDirectory location depends on the repository kind.

GitUI/SpellChecker/EditNetSpell.cs
Fixes #2301
- korean language ime patch.
- previous screenshot :
- after screenshot : 
- typing korean ime.
- GIT 2.12.2
- Windows 10
=> IME Patch for Commit message EditBox

.gitignore, GitExtensions/GitExtensions.Mono.csproj, GitUI/Editor/FileViewerInternal.cs, GitUI/GitUI.csproj
Fixes #3728
- Mono 5.0.1.1
- Mac OSX
=> fix: Mono crash on closing the "File History" window

Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCityBuildChooser.cs
the Id of the project should be used in the rest url to fetch builds
=> fix Teamcity build chooser

GitUI/CommandsDialogs/FormCommit.cs, GitUI/Editor/FileViewer.cs
Fixes #
- Only renamed a Property, did not change the code semantically.
I don't know if these kinds of commits are welcome in this project. I am planning on fixing 'real issues' too in the future, I'm just new to GitExtensions yet!
PS: I used Resharper, so it was a 'clean rename' for sure!
=> Fix a spelling mistake in code (FilePreabmle -> FilePreamble).

GitPlugin/Connect.cs, GitUI/CommandsDialogs/FormApplyPatch.Designer.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormRebase.Designer.cs, GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/ResolveConflictsDialog/FormModifiedDeletedCreated.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/Translation/en_pseudo.xlf
I am not a native English speaker, but I believe 'mergeconflict' is not an English word (even GitHub underlines it). I think it should be 'merge conflict' in UI strings and localized strings.
- updated all .xlf files in GitUI/Translation
- updated all the occurrences I've found in the code, except:
1: the command name in GitUICommands (and related occurrences)
2: in ChangeLog.md.
- Ran a 'Build solution' in VS2015: No build errors. No generated files changed (so I probably did not miss any UI string)
=> Fix spelling in UI: "mergeconflict*" -> "merge conflict*"

GitExtensions/app.config
Additional fix to #3704 #3771
- Fixed NewtonSoft.Json.Dll v6 and v8 could not be found issue when loading the TFS plugin
- No, I didn't test TFS, hope someone using TFS can test it
- I just made sure the exception is gone during debugging
=> Fixed plugin loading issue due to lower version of newton json dll was missing

GitUI/Editor/FileViewer.cs
Issue: [Exception shown instead of error message for locked file in commit dialog](https://github.com/gitextensions/gitextensions/issues/3759)
Using **FileShare.ReadWrite** lets us read the file even if it's locked.
Yes the locker program(s) might write to the file and the file content shown might become outdated but then the user presses 'Refresh'. It's still a better UX than 'not reading' the file content and 'not showing' it, right?
- Added a .dwg file to one my repos, and opened it in AutoCAD which always puts a write-lock on opened files. Then I checked the same file in the commit dialog.
- GIT 2.13.0
- Windows 7
=> Fix for issue #3759:

GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs, GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.resx
Most of the time the path selected when opening the form is the one of the current open repository.
It could be very convenient to be able to go to the parent directory that has a high probability to contains
a lot of git repostories (and open the "AutoComplete" list that show the available folders to select one of them easily).
=> FormOpenDirectory: Add a button to go (easily) to the parent directory

GitUI/CommandsDialogs/FormMergeBranch.Designer.cs
Fixes #3782, I believe the accept button was removed inadvertently.
- Added back the ability to confirm the merge form using Enter key
- Open the merge form and type the Enter key
- Git 2.12.2
- Windows 10
=> Set the OK button as accept button so we can use Enter key to confirm the merge

GitUI/BuildServerIntegration/BuildServerWatcher.cs
- Ask user for credentials for CI if there were no credentials in IsolatedStorage
=> Ask user for credentials if there were no credentials in IsolatedStorage

GitUI/CommandsDialogs/FormPush.cs
Fixes #3794  .
- Fixed crash when pushing with no remote configured
- Create a new repo locally without adding any remote
- Make a commit and try to push
- GIT 2.12.2
- Windows 10
=> Fix crash when pushing with no remote configured

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormClone.Designer.cs, GitUI/CommandsDialogs/FormClone.cs, GitUI/CommandsDialogs/FormClone.resx
This is a first step towards #2968. It enables convenient and fast cloning of LFS repositories.
The cloned repository will also have the LFS hooks installed, which will reduce the probability of pushing LFS link files without having pushed the binary blobs to LFS first.
I left the option disabled by default, mostly because of the LFS hooks (they're harmless when LFS is not used, but people may not expect this so it's opt-in). Also, the checkbox will be disabled if the git-lfs extension is not installed.
- Adds a "Use LFS extension" checkbox to the clone dialog
- Rearranges the checkboxes, as they would use a lot of vertical space otherwise
- I ran an LFS-enabled clone on a big …
=> Add an option to clone a repository using git-lfs

GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs
Having a clean repository history, when trying to Browse a local git repository, GitExtension will crash if "directories" list is empty.
This fix will add two directory (recent working dir and git home dir) to the list to avoid the crash.
Fixes #3817  .
- add two directory to avoid using an empty list
- repeat the steps inside the issue, it will not crash
=> Fix a crash after clicking on "Browse..."

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
Currently the button for setting an icon for a script is only visible when the *OnEvent* is set to *ShowInUserMenuBar*. However, the icon is also visible when placed in the context menu of the revision grid, but the setting button is not visible for such scripts.
- The button for script icon is visible for scripts which are to be shown in the user menu bar OR in the revision grid context menu
- GIT 2.13
- Windows 10
=> Show the icon for relevant scripts

GitUI/CommandsDialogs/FormBrowse.cs
The ability to do so from the RevisionGrid context menu has been added in commit b3e79447928051cfb3494c9c0ef1a1d0ecde56a8.
A followup fix for #2396.
- Cherry-picking uses the same code regardless of whether it is run from the `RevisionGrid` context menu or `FormBrowse` window menu.
- Selected some commits from a different branch (not necessarily in chronological order)
- Clicked *Commands* - *Cherry pick...*
- The Cherry-pick form appeared sequentially for each of the selected commits (this time in chronological order)
- GIT 2.13
- Windows 10
=> Allow cherry-picking multiple commits from FormBrowse menu

Plugins/GitFlow/GitFlowForm.cs
Fixes #3830  .
- `git flow publish` and `git flow pull` command will use the branch type, not fixed to feature
- related button and panel will be disabled when `support` branch is selected
- Open GitFlow panel, select `support` branch -> Pull panel and Publish button are disabled
- select other kind of branch, if branch exists the same panel will be enabled
- Push `Publish` button and see the command execution log, it's not fixed to `feature publish` but depends on the branch type selected above.
- GIT 2.132.windows.1
- Windows 7
=> GitFlow Publish and Pull button can be used for all kind of branch

Plugins/GitFlow/GitFlowForm.cs
Feature #3811 
- Added "bugfix" as branch type for gitflow dialog
- Open GitFlow dialog on an gitflow initialized repository 
- Check that the branch type combobox lists "bugfix"
=> Added "bugfix" kind of branch

GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs, GitUI/CommandsDialogs/FormCheckoutBranch.cs
Fixes #3725 (partial)
- Mono 5.0.1.1 
- Windows 10 100% scaling
Mono doesn't have any way to autosize or constrain the size of the form, so it is sizeable unlike the Windows version. 
I consider it to be minor issue.
@l-inc could you please verify that it works for you
=> fix: FormCheckoutBranch layout on Mono

GitUI/CommandsDialogs/FormRemotes.cs
The remotes management screen will now select the first available active remote. If none active, the first inactive remote is selected.
Fixes #3861
=> fix: Incorrect selection of inactive remotes

GitUI/CommandsDialogs/FormApplyPatch.cs, GitUI/CommandsDialogs/FormViewPatch.cs
Fixes #3867.
Should all the UI text be modified to read `*.patch` instead `*.Patch` too?
Has been tested on Ubuntu 16.04.
=> lowercase the patch file search filter

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
Fixes #3832
- Avoid `ToolStripSplitButton` menu to close unexpectedly
- Click on `Superproject`, `Stash` of `Pull` button (the small black triangle)
- Move the mouse 1 pixel out of the button or the left or on the right of the button
- The context menu that just opened should close
- The fix prevent the menu to close in such situation
- Windows 10 Pro
=> Fixed superproject, stash and pull ToolStripSplitButton closing issue

GitUI/SpellChecker/EditNetSpell.Designer.cs, GitUI/SpellChecker/EditNetSpell.cs
In some circumstances SpellCheckEditControl could be initialised and start raising events before EditNetSpell control completed instantiation sequence. This would lead to NRE.
The initialisation sequence adjusted to initialise SpellCheckEditControl after EditNetSpell control has loaded.
Fixes #3827
- Windows 10
=> fix: Clicking Commit causes a crash

GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.Designer.cs
Fixes #3892 .
- Change maximum commit message preview from 10 to 999
- None needed
- Tested with value set to 100 and it displayed nicely. 999 works as well but it is significantly slower
- Git version 2.7.0.windows.1
=> #3892 - Raised the previous messages limit from 10 to 999

GitUI/SpellChecker/EditNetSpell.Designer.cs, GitUI/SpellChecker/EditNetSpell.cs
In some conditions the timer would fire before the form init completed, which would lead to NRE.
Relates to #3827
=> fix: NRE in EditNetSpell control

GitExtensions/app.config, GitUI/GitUI.csproj, GitUI/app.config, GitUI/packages.config, Plugins/BackgroundFetch/BackgroundFetch.csproj, Plugins/BackgroundFetch/app.config, Plugins/BackgroundFetch/packages.config, Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorIntegration.csproj, Plugins/BuildServerIntegration/AppVeyorIntegration/app.config, Plugins/BuildServerIntegration/AppVeyorIntegration/packages.config, Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsIntegration.csproj, Plugins/BuildServerIntegration/JenkinsIntegration/app.config, Plugins/BuildServerIntegration/JenkinsIntegration/packages.config, Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityIntegration.csproj, Plugins/BuildServerIntegration/TeamCityIntegration/app.config, Plugins/BuildServerIntegration/TeamCityIntegration/packages.config, Plugins/BuildServerIntegration/TfsIntegration/TfsIntegration.csproj, Plugins/BuildServerIntegration/TfsIntegration/app.config, Plugins/BuildServerIntegration/TfsIntegration/packages.config, Plugins/BuildServerIntegration/TfsInterop.Vs2012/app.config, Plugins/BuildServerIntegration/TfsInterop.Vs2013/app.config, Plugins/BuildServerIntegration/TfsInterop.Vs2015/app.config, Plugins/Gerrit/app.config, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/packages.config, TranslationApp/app.config, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/app.config
Update Reactive Extensions to 3.1
- Removing Reactive Extensions 2.2.5
- Adding Reactive Extensions 3.1.1
- Everything starts normally 
=> Update Reactive Extensions to 3.1

GitUI/CommandsDialogs/FormBrowse.cs
If the same working directory opened in multiple git processes (i.e. in GitExtensions and VSCode) attempt to delete index.lock may result in IOException and termination of GE.
Fixes #3902
=> fix: Can't delete index.lock

GitUI/CommandsDialogs/FormPull.Designer.cs
Help images for helpImageDisplayUserControl1 are set whenever merge options are changed - e.g. merge/rebase/don't merge.
The designer defaults to the first option (merge) after that the user settings are applied. If the user settings were set to 'merge' as well the change event would not be triggered and images would not be set.
The designer default is unset, now the change event is triggered as expected.
Fixes #3829
=> fix: Pull dialog help picture disappear

GitCommands/GitCommands.csproj, GitCommands/Settings/AppSettings.cs, GitCommands/Settings/ConfigFileSettingsCache.cs, GitCommands/Settings/GitExtSettingsCache.cs, GitCommands/Settings/MemorySettings.cs, GitCommands/Settings/MemorySettingsCache.cs, GitCommands/Settings/SettingsCache.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/GitUI.csproj, GitUI/SplitterManager.cs, Plugins/GitUIPluginInterfaces/ISettingsSource.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/SplitterManagerTest.cs
The current restoring algorithm based on DeviceDPI does not work if font size or window size changes.
Every time the GitExt starts, the MainSplitContainer.SplitterDistance increases by 12 due to statusStrip being shown. Connecting with remote desktop decreases my screen size and all the splitters are messed up.
Proposed changes:
Currently window size and position are scaled to the current DPI. That means the window size will change if the current DPI differs from the stored one. After that splitter position will be scaled based on the new window size and the current font size. The scaling algorithm respects FixedPanel property:
- When splitter size differs from the stored one then resizes the non fixed panel or both if there is no fixed panel.
- When splitter font size differs from the …
=> Restoring splitters based on SplitContainer size and font size.

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/UserControls/FileStatusList.cs
Improve form commit workflow to remove most of the pain explained in #3805 .
- Improve tab navigation to be able to do : 1. Unstaged file list, 2. Staged file list, 3. Amend Checkbox, 4. Commit Message box
- Automatically select the stage file when entering the commit message box (to help write the message looking at the code)
- Add key shortcuts (ctrl+n & ctrl+p) to navigate to the next/previous file. In the message box, it's done in the 'staged files' list to be able to review the files without leaving the message box \o/
- Add a shortcut ctrl+enter to go directly to the commit message box from everywhere in the form (inspired by the same to create the commit once in the message box)
- Automatically display the diff of the files when entering the …
=> Form commit workflow improvements

Setup/Product.wxs
Got a crash after installing latest master branch build. It turns out System.IO.Abstractions.dll was missing from setup package. It's been recently added as a dependency for Gravatar.
=> Include recently added System.IO.Abstractions in setup package

GitUI/CommandsDialogs/FormCommit.cs
Ctrl+enter to commit is now not working from Commit form as Message.Focused gives wrong indication for whether Message text box is currently focused.
=> Property Message.Focused is always false use Message.ContainsFocus instead

GitUI/UserControls/FileStatusList.Designer.cs
to prevent passing in the filter combobox when pressing tab
follow #3920
=> Fix tab order in the FileStatusList component

GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs, GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
- Add Visual Studio Code as Editor (because it add highlighting on rebase interactive file), Diff and Merge tools
- Fix the way to get 'vsdiffmerge.exe' with VS>=2017 because Microsoft changed the way to find VisualStudio path making it harder :( (should work for the default install and for the future ;) )
- Add missing config as diff tool for 'DiffMerge'
- multiple refactoring to remove a lot of code duplication 
PS: The review should be a lot easier if done reading diffs of commits one by one....
- GIT 2.13.2 (but should be of no importance)
=> Add (and refactor) diff and merge tools

GitUI/OsShellUtil.cs
In a rare case when the user's browser of choice points to non-existent executable attempts to launch the help will result in Win32Exception "the system cannot find the file specified".
The old implementation was also looking at the now-defunct registry key to determine the browser of choice.
Since Win8 the registry key containing the user's choice is encrypted and thus no longer usable by thrid-party applications.
The code is simplified to launch the help URL via `Process.Start`.
Fixes #3011
- Ubuntu 17.04
=> fix: Help in Branch dialog exception

GitUI/CommandsDialogs/FormPush.Designer.cs, GitUI/CommandsDialogs/FormPush.cs
An attempt to push when no remote defined would result in NRE.
Check for remotes before pushing. If no remotes available, show an error message and a prompt to
configure remotes.
Fixes #3862.
Before:
After:
- Ubuntu 17.04
=> fix: NRE when trying to push

GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs, GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
Fixes #3849
- Fix "Manage worktree" form
- Fix creation of the worktree when putting a space in the path
- GIT 2.13
=> handle worktrees with spaces in the path

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/Editor/FileViewer.cs
Fixes #3933.
- the hotkeys for the diff viewer and file viewer in the _Browse_ dialog are reloaded each time the _Settings_ form is closed (similarly to the revision grid).
- GIT 2.13.2
- Windows 10
=> Reload file viewer hotkeys when the settings form is closed

GitCommands/Repository/Repositories.cs, GitCommands/Repository/RepositoryHistory.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.cs, GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.resx
Recent repositories history size is set to 30 without any ability to change. The "recent repositories settings" form provides the ability to set "Maximum number of most recent repositories" which does
not have any effect on the history size and it is not used anywhere else.
The fix deprecates "MaxMostRecentRepositories" setting and consolidates the use of "history size" setting.
Fixes #3908
=> fix: Recent repositories history size not respected

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.Designer.cs, GitUI/Translation/English.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Spanish.xlf
Fixes #3970.
- Change all menu entries from "Pull..." to "Pull/Fetch..."
- Update Pull dialog title according to "Fetch" checkbox setting
Screenshots before and after:
- Commands menu before 
- Commands menu with Pull/Fetch 
- Pull dialog with "Fetch" activated before
- Pull dialog with "Fetch" activated after
- Manual tests, running from Visual Studio 2015
- GIT 2.14.1.windows.1
- Windows 7 x64
- Visual Studio 2015 Community Edition
=> Change pull caption to pull/fetch

GitCommands/Git/GitCommandHelpers.cs
Fixes #3948
- modified the regular expression 
- modified content of a submodule => diff view works fine
- commited changed content of submodule => submodule is staged => diff view works fine
- tested both with  diff.mnemonicprefix=[true|false]
- git version 2.13.3.windows.1
- Windows 7 Enterprise SP1
=> Fixed DiffView for Submodules with diff.mnemonicprefix=true

GitExtensions/Program.cs
fix for #3947
When run `browse` command from command line with relative path as argument gitextensions show that relative path in recent repositories list. 
Relative path may be meaningless (e.g. `.\..\..`).
- convert relative path to absolute at the moment of parsing arguments
=> Convert relative path command line argument to absolute path

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/Hotkey/HotkeySettingsManager.cs
Sometimes there are changes to the files that should not be commited (i.g. temp changes to config) and those files need to be constantly stashed/popped during branch change, etc. thus having a keybindings for these actions might help a lot.
=> Add Hotkeys for Stash and Stash Pop commands

GitUI/CommandsDialogs/FormPull.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/Translation/en_pseudo.xlf
Fixes # .
Fix typo in warning message
Compile and test on local machine
=> Typo fix for deleting stale remote-tracking branches

GitUI/CommandsDialogs/FormPush.Designer.cs
=> fix FormPush illogical tab order

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RevisionFileTree.Designer.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/CommandsDialogs/RevisionFileTree.resx, GitUI/GitUI.csproj
No functional changes.
- Windows 10
=> Extract "File Tree" control from FormBrowse

GitCommands/Repository/Repositories.cs, GitCommands/Repository/RepositoryCategory.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardCategory.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardEditor.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardEditor.cs
- RSS feeds are retired
As agreed https://github.com/gitextensions/gitextensions/pull/3693#issuecomment-329390056
=> Remove RSS feeds functionality

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
Fixes #3585  .
- Add a "File Explorer" shortcut in the toolbar (next to "Git bash")
- 
**How did I test this code:**
- Make sure the button appears correctly
- If it is a valid working directory, the file explorer is enabled and behaves as expected
- If it is not a valid working directory, the file explorer button is disabled
=> Added toolStripFileExplorer to complete the feature-request

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs
Fixes #4016 .
- Applied the same behavior to the FormFileHistory as requested by @RussKie 
-
=> Applied the same behavior to FormFileHistory

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormPull.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
This was done in eb3fce806cb76d328b669adf8de9a04244436172.
Passing +refs/heads/remote-branch:refs/remotes/origin/local-branch is
plain wrong. It creates a local ref for a remote branch which doesn't
really exist (origin/local-branch).
We don't really need a persistent ref for the remote branch. Just
passing it as a raw argument is fine. It is fetched into FETCH_HEAD,
then the local branch is merged/rebased on top of it.
=> GitCommands: Avoid creating a fake remote ref on pull

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormPull.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
This was done for pull in d7dbd16e45ad3512ccd1921f6575ae560ef49fc2.
The same should be done for fetch. Unless the user specifies a local
branch, there is no point in creating one.
=> GitCommands: Avoid creating a fake remote ref on fetch

GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
Fixes # .
- 
- 
- 
-
-
-
- 
- 
- 
=> Cancelling checking if shell extension is registered crashes GitExtensions

GitCommands/Git/GitCheckoutBranchCmd.cs, GitCommands/Git/GitCommand.cs, GitCommands/Git/GitCreateTagCmd.cs, GitCommands/Git/GitDeleteBranchCmd.cs, GitCommands/Git/GitTagController.cs, GitCommands/GitCommands.csproj, GitCommands/packages.config, GitUI/CommandsDialogs/FormCreateTag.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/GitUICommands.cs, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/IGitCommand.cs, Plugins/GitUIPluginInterfaces/IGitUICommands.cs, UnitTests/GitCommandsTests/Git/GitCheckoutBranchCmdTest.cs, UnitTests/GitCommandsTests/Git/GitTagControllerTest.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
The ProcessDialog provides to the user a full command, output (warnings especially) and error messages.
It returns also the exit code, so FormCreateTag does not have to parse the output for execution status.
The parsing got obsolete after the recent changes.
=> Create tag using the standard ProcessDialog.

GitCommands/FileAssociatedIconProvider.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/RevisionFileTree.Designer.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, UnitTests/GitCommandsTests/FileAssociatedIconProviderTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/packages.config
- Optimise revision file drag-out and drop
- Expand "File Tree" folders on click
- GIT 2.13 and above
- Windows 10
- Ubuntu 17.04
=> Enhance file tree control

GitUI/CommandsDialogs/FormPull.cs
CheckedChange is called for both the disabled button and the
newly enabled button. We only care about the latter.
=> Pull: Only activate relevant controls when really checked

GitUI/CommandsDialogs/FormGitIgnore.Designer.cs, GitUI/CommandsDialogs/FormGitIgnore.cs, GitUI/CommandsDialogs/GitIgnoreDialog/GitIgnoreModel.cs, GitUI/CommandsDialogs/GitIgnoreDialog/GitLocalExcludeModel.cs, GitUI/CommandsDialogs/GitIgnoreDialog/IGitIgnoreDialogModel.cs, GitUI/GitUI.csproj, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/Translation/en_pseudo.xlf
Fixes #3860.
- Introduce `GitIgnoreModel` and `GitLocalExcludeModel` to use polymorphism instead of `if` checks.
- Extract strings from `FormGitIgnore` to those files.
- Change resources for the links.
- This fix loses some of translated strings, since they are moved to other files.
- before
- after (updated image)
I have tested it manually.
=> Fix strings in .git/info/exclude

GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/PathFormatter.cs
Useless horizontal scrollbar has been removed in FileStatusList control for compact, trimstart and fileNameOnly modes.
- Windows 10
P.S. You can notice that in fileNameOnly mode all list-items are processed the same way as in OnDraw method. I tested 100k items and they took only 65 ms on mobile i5 in debug. So it should be ok if I'm right.
=> FileStatusList had useless horizontal scrollbar

GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, GitCommands/PathEqualityComparer.cs, GitCommands/PathUtil.cs, GitUI/CommandsDialogs/FormPull.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs, UnitTests/GitCommandsTests/PathEqualityComparerTests.cs
As discussed in https://github.com/gitextensions/gitextensions/pull/4032#issuecomment-333517989
* Deprecate PathUtil.DirectoryExists
* Deprecate PathUtil.PathExists
* Move PathEqualityComparer to outer scope
=> Path utils refactor

GitUI/CommandsDialogs/RevisionFileTree.Designer.cs, GitUI/UserControls/FileStatusList.cs
Use GitExt icon for menu items that open a new instance for Submodule Status
This was used for an icon recently added in Commit form
Seen as part of #4031 .
- Consistently use GitExt icon to open new Browse window
- 
- ![image](https://user-images.githubusercontent.com/6248932/31861588-68a63298-b730-11e7-8a2e-35c3806d69d6.png)
- open UI
- GIT 2.14 (not Git related)
- Windows 7 and Win10
=> Use GitExt icon for menu items that open a new instance for Submodule

GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/Translation/en_pseudo.xlf
Also changed all translations
No change in Transifex, the translated files could be uploaded
Original: Show current working directory changes in revision graph (slow!)
The setting is slower when switching tabs etc because git commands are not cached, but nothing going on in the background
The text should be changed, this is temporary change until the functionality has settled (will the commit move completely to Browse)
Suggestion: Show staged and unstaged as artificial commits in revision graph
A later step is to enable this functionality by default
Discussed in #4031
- Rewording in setting
- 
- 
- 
- View
- GIT 2.14
- Windows …
=> Remove "(slow!)" for showing stageged/unstaged as commits in Settings

GitCommands/Repository/Repositories.cs, GitUI/CommandsDialogs/FormCommit.cs
Seen when working with #4031 
Visual Studio (at least 2017) raises 2 warnings for me.
One is correct, the other incorrectly detected.
Rather change them then to go and check that the warning is not in my changes every time.
- Code refactoring
- None
- Debugger, manual test
- GIT 2.14
- Windows 10
=> CA2202 CA2213 suppression

GitUI/CommandsDialogs/FormFileHistory.Designer.cs
Some relevant icons were missing in FileHistory menu
Related to #4031 
- Add some relevant icons
- Add icons
- View FileHistory menu
- GIT 2.14 (not Git related)
- Windows 10
=> FileHistory: Icons for menu

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
This is attempt2 for #4081, after #4079 is merged
Seen in #4031 .
- The menu items for FormCommit Staged submodules has several irrelevant options that has odd or no effect. If no file is displayed, those options are not displayed.
Old: 
New:
- Stage changes to a submodule
- View menu alternatives
- GIT 2.14 (not Git related)
- Windows 7 and Win10
=> Commit: Do not show menu items irrelevant for submodules

GitCommands/Git/GitCommandHelpers.cs, GitCommands/GitCommands.csproj, GitCommands/Settings/AppSettings.cs, GitCommands/SshPathLocator.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs, Plugins/Gerrit/GerritUtil.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/SshPathLocatorTest.cs
- GIT_SSH environment variable is not always set. As a result, ssh is not found,
resulting in various failures. On of them is that the gerrit plugin fails to
install the commit-msg hook, with a very unuseful message.
- Of course, there is still a possibility to set this environemnt variable, but
this is an extra step.
- The change adds a try to retrieve ssh.exe from git installation directory,
when no environment variable is found. 
- Desktop with no GIT_SSH environment variable
- putty or openSSH configured for SSH
- Install Hook was failing (was not finding ssh.exe)
- After PR, hook installs correctly.
- GIT 2.10.2, GIT 2.13.3
- Windows 7 & Windows 10
=> Try to find ssh.exe in git installation directory

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/IFileViewer.cs
Implements #2868
- Add DiffVerticalRulerPosition to settings and to Diff page
- Expose VRulerPosition in IFileViewer interface
- after changing the settings file viewer is updated
=> Feature 2868

GitUI/GitUI.csproj, GitUI/SpellChecker/EditNetSpell.cs, GitUI/SpellChecker/SpellCheckerHelper.cs, GitUI/SpellChecker/WordAtCursorExtractor.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/SpellChecker/WordAtCursorExtractorTests.cs
Fixes # 3760.
- GetWordAtCursor() includes dot into a word if the dot is leading.
before: 
after:
I tested it manually.
=> Introduce auto complete for words starting with dot.

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RevisionDiff.Designer.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiff.resx, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/GitUI.csproj, GitUI/GitUIExtensions.cs, ResourceManager/GitExtensionsUserControl.cs
The source moved almost verbatim from FormBrowse to the new control.
Minimal changes to facilitate the plumbing. It is something to revisit at a later stage.
=> Extract "Revision Diff" control from FormBrowse

GitUI/CommandsDialogs/FormFormatPatch.cs, GitUI/CommandsDialogs/FormPush.cs, GitUI/SpellChecker/EditNetSpell.cs, GitUI/UserControls/FileStatusList.cs
I'm a member of the [Pinguem.ru](https://pinguem.ru) competition on finding errors in open source projects. All issues were found with [PVS-Studio](https://www.viva64.com/en/pvs-studio/):
V3022 Expression 'FileStatusListView.Items.Count > 0' is always true. FileStatusList.cs 861
V3022 Expression '(lineLength > 0)' is always true. EditNetSpell.cs 795
V3022 Expression 'revisions.Count > 2' is always true. FormFormatPatch.cs 141
V3022 Expression 'PushToRemote.Checked' is always true. FormPush.cs 470
=> Remove redundant parts of conditional expressions

GitUI/CommandsDialogs/RevisionDiff.cs
Was part of #4084, resubmitted after refactoring in master
Part of #4031.
This is not a complete correction of available menu items, specific issues are handled in other pull requests as well as future PRs. 
- Disable and hide irrelevant menu items
- See Browse Diff screenshots in #4084
- Menu items for various combinations in the Diff panel
- Windows 7 and Win10
=> Browse Diff: Disable and hide irrelevant menu items

GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/GitUICommands.cs
If you open FileHistory, you are likely more interested in seeing the diff than the file contents
Order of tabs preserved (I would have preferred to set DiffTab first instead but change as little as possible)
- Tab selected when opening FileHistory
- None
- Open FileHistory, for instance by double-clicking in TreeTab
- Make sure the DiffTab is selected
- Windows 10
=> FileHistory: Show DiffTab when opening, not ViewFile

GitCommands/Git/GitRevision.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/GitUIExtensions.cs, GitUI/HelperDialogs/FormChooseCommit.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid.cs
Requested by @RussKie in https://github.com/gerhardol/gitextensions/commit/7234d28588cad4b22f3dbc6ad58d8542449904c7#diff-320265b67fc16a7d7a11a99771f9e1a4L121
Converted to use of GetParentGuid where applicable
Part of #4031 
- Refactoring
- None
- Review, manually
- Windows 7 and Win10
=> GitRevision: Make HasParent a property

GitCommands/Git/GitModule.cs
- Simplify editor string comparison (if editor contains "notepad" it also contains "notepad++" and other notepads)
- GIT 2.14.2
- Windows 10
=> Simplify editor string comparison

GitUI/UserControls/FileStatusList.cs
Right now in the master branch if you open FormCommit and with unstaged files in the filter type character 's' the files will get staged. This is because even in the textbox keypresses trigger the hotkeys.
I am scared to ever hit 'r' while in the filter box :)
This got introduced with [fd37574819] Merge pull request #3920 from pmiossec/form_commit_workflow_improvements
Reverting this change didn't seem to break anything so maybe @pmiossec could chip in why this change has been made.
=> Fix FormCommit file list filter input getting treated as hotkeys

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Issue #4049
I was checking out mergetools, and could as well fix this when testing DiffMerge
Low priority, the alternative is to remove DiffMerge from defaults
- Default values and parameters to setup SourceGear DiffMerge
- Setup DiffMerge as Merge and/or diff tool
- Verify that it works
- Windows 10
=> DiffMerge parameters and executable name

GitCommands/Git/GitItem.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitRef.cs, GitCommands/Git/GitRevision.cs, GitCommands/Git/GitTreeParser.cs, GitCommands/GitCommands.csproj, GitCommands/GitRevisionInfoProvider.cs, GitUI/CommandsDialogs/BrowseDialog/FormBrowseUtil.cs, GitUI/CommandsDialogs/BrowseDialog/GitFileTreeComparer.cs, GitUI/CommandsDialogs/FormFormatPatch.Designer.cs, GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs, GitUI/CommandsDialogs/FormResolveConflicts.resx, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/CommandsDialogs/RevisionFileTreeController.cs, Plugins/GitUIPluginInterfaces/IGitItem.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs, UnitTests/GitCommandsTests/Git/GitTreeParserTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/GitRevisionInfoProviderTests.cs, UnitTests/GitUITests/CommandsDialogs/RevisionFileTreeControllerTests.cs
* Remove `SubItems` property as it was only used by GitItem class in a single use-case in RevisionFileTree control. All other implementations of the interface had no use for this property.
* Functionality of loading item's children moved to `GitRevisionInfoProvider`.
* The `RevisionFileTreeController` maintains the cache of retrieved items' children for a given revision.
* Remove redundant properties
* Extract raw data parsing to `GitTreeParser`
* Convert `IsBlob`/`IsTree`/`IsCommit` to enum
=> Refactor IGitItem

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/Translation/English.xlf
It has no information for staged/unstaged, just blank
It _should_ later be used for commit without a popup as discussed in #4031 etc
Discussed in #4031
- Make sure the commit info panel is collapsed for artificial commits
- Only before - the blank window is removed for artificial commits with this PR
- Manual
- Windows 10
=> Hide CommitInfo panel for virtual commits

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/DashboardItem.cs, GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormMergeBranch.Designer.cs, GitUI/CommandsDialogs/FormSparseWorkingCopy.cs, GitUI/UserControls/FileStatusList.Designer.cs
Mono expects tooltip's AutomaticDelay to be greater than 0. Otherwise it throws:
`System.ArgumentOutOfRangeException: '0' is not a valid value for Interval. Interval must be greater than 0.`
Set all AutomaticDelay across the codebase to 100ms.
Fixes #4126
=> fix: AOORE in "Open local repository" dialog under Mono

GitCommands/Git/GitModule.cs
GE GUI should not fail if the user has this setting, the Git output format must be formatted so it can be parsed
Fixes #4130.
- Override config for diff.submodule so the git-diff command can be parsed regardless of user configuration
- See issue for the problem, no change for normal configuration
- Set the configuration to log, short, unset agaimn an browse diff submodules.
- GIT 2.15 Independent of Git "diff --submodule" have been around since at least 1.7, further options (diff) added in 2.x. As the change only overrides the config, it is version independent.
- Windows 10
=> diff.submodule=log raises exception

GitCommands/Git/GitRevision.cs, GitUI/GitUIExtensions.cs
#4107 has no negative effect of what I see, but if the FirstParentGuid is used in a different way it could
The change to "always" create FirstParentGuid was useful in some difftool scenarios, created explicitly instead
- Revert handling to before #4107
- None
- Manually
- Windows 10
=> Regression of #4107, FirstParentGuid always returned a parent

UnitTests/GitCommandsTests/GitModuleTestHelper.cs
Although this exception doesn't actually break the tests, it is visually
annoying, and could possibly be related to leaked temporary folders.
It has been pointed at in #4121.
=> Get rid of Exception message box when running tests

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Patch/PatchProcessor.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommandsTests/Patch/PatchManagerTest.cs
Reverse order of compare, required to diff from working-dir "commit" to other commits
This is a part of #4031. 
Currently, the -R option is not used, so this commit in itself does not make any change.
Unit tests as requested by @RussKie https://github.com/gerhardol/gitextensions/commit/7234d28588cad4b22f3dbc6ad58d8542449904c7#commitcomment-25122598
- Handle diff with -R option
- No change now. When remaining of #4031 is merged, "b" may be listed first like below:
- Unit tests, in other branches
- GIT 2.15 - no change in this commit
- Windows 10
=> Support git-diff with -R option

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RevisionDiff.cs
Part of 3. in https://github.com/gitextensions/gitextensions/issues/4031#issuecomment-342005174
This is likely not a complete update, all changes related to #4031 need to be merged to get an overview...
- Refresh the diff filelist in Browse for artificial commits for the commands that may update files or the index
- None
- Make sure there are files in the index and or working tree (so the artificial commits are available, proposal to change in #4086)  
- Modify the files outside GE, like from the file system. The index is not updated (discussion in #4031 how to improve). The lists are updated though when selecting the artificial indexes
- Modify files from GE that affect the …
=> Refresh Browse Diff filelist when actions (may) update the index

GitUI/CommandsDialogs/RevisionDiff.cs
This is a follow-up to #4092. When submitted, this action worked but after a refactoring to RevisionDiff.cs (much needed though) this action was commented out when refactoring as it required slightly more changes.
The master issue is #4031
This is part of 3. in https://github.com/gitextensions/gitextensions/issues/4031#issuecomment-342005174
- See original PR for the Update Submodule menu item, missing in merged version of #4092
- Change version for a submodule
- View artificial commits
- Verify that the option is is available and update submodule version
- GIT 2.15
- Windows 10
=> Update Submodule for unstaged commits Browse diff

GitCommands/GitRevisionInfoProvider.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/CommandsDialogs/RevisionFileTreeController.cs, UnitTests/GitCommandsTests/GitRevisionInfoProviderTests.cs, UnitTests/GitUITests/CommandsDialogs/RevisionFileTreeControllerTests.cs
Whenever repositories changed new GitModule instance was not correctly
reflected in RevisionFileTreeController and GitRevisionInfoProvider.
Fixes #4151
=> fix: Blank RevisionFileTree

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormBrowse.resx
WIP, enabler for toolbar customisation
No visual changes.
- Windows, Ubuntu
=> feat: Replace top-level SplitContainer with ToolStripContainer

GitUI/UserControls/RevisionGrid.cs
Also limit count of changes to the Browse window (does not really make sense in FileHistory)
This is #4031 item 2., discussed in #4086
The RevisionGrid is only updated at explicit commands as normal commits are not changed.
Artificial commits are dynamic and will have contents/no contents from many commands. However, they always "exist".
Now you have to refresh the the complete revision grid to see when staged or unstaged appear. As the diff lists are not cached for artificial commands, the content will be updated just by selecting the artificial commit in question.
(The count is not updated dynamically yet).
- Artificial commits with 0 was not shown before
- 
- Open Browse, make sure that there are no …
=> Always show artificial commits in RevisionGrid

GitCommands/Git/RevisionDiffProvider.cs, GitCommands/GitCommands.csproj, UnitTests/GitCommandsTests/Git/RevisionDiffProviderTest.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
Translate the artificial commits to diff options: index -> --cached, work-dir -> empty
Reverse diff in some situations is required to preserve the order like diff from index to any other commit
Part of #4031.
This code is not used yet. I believe the opdate is easiest to handle if this PR is reviewed and merged separetly, even if some dead code is briefly (?) added.
- Separate class for commit -> diff option handling
- None
- Unit tests
- Other branches
- GIT 2.15
- Windows 10
=> Separate handling of artificial commits diff options

GitUI/UserControls/RevisionGrid.cs
Fixes #3730.
- Update checked state in "Show remote branches" ToolStripMenuItem when it is clicked.
I tested this code manually:
1. Click on View >> Show remote branches. 
2. It it was checked, it should become unchecked, and the remote branches in the commit list should not be shown. 
3. And vice-versa :)
- GIT 2.14
- Windows 10
=> Update checked state in "Show remote branches" ToolStripMenuItem

GitPlugin/GitPlugin.csproj
Not sure what has changed in the recent months (maybe framework upgrade to 4.6.1?) but I couldn't build the setup any more because `resgen.exe` was not found.
It was expected under WindowsSdk 8 path but I had WindowsSdk 10 instead which should be just fine for `resgen.exe`
This change uses `GetFrameworkSdkPath` msbuild task to resolve the Sdk path automatically and provide it to the `GenerateResource` task.
=> Auto-pick SdkToolsPath

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
Reported in #4098, related to #4031
This could occur also in other situations than reported, for example:
* make sure at least one file is unstaged
* select the file
* right click outside of the file, select edit
* an exception would occur
It was harder to provoke the error for staged though, the menu did not appear if you left clicked outside the file first before right clicking.
- Manually, see above
- GIT 2.15
- Windows 10
=> Commit menus raised exceptions if no items were Selected

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiffController.cs
From #4031 
The actions did not cause any exceptions, but were confusing to the user, it seemed like they had selected files
Reproduce by right clicking in the open space in a Diff panel with at least one file
- 
- 
- Manually
- Windows 10
=> Browse Diff Menu Items should be disabled when no item is SelectedDiff

GitUI/CommandsDialogs/RevisionFileTree.cs
Similar to #4098, related to #4031
Most easily seen by right clicking in the FileTree and selecting
The core change is in FileTreeContextMenu_Opening, disabling irrelevant items
Correction for open folder, clean to handle null selections too
The pattern to check for no selection was broken in most of the file. This was changed too. Probably not required after the menu change, could have been separated but easily reviewed.
- GIT 2.15
- Windows 10
=> RevisionFileTree context menu gave exceptions if no items were Selected

GitCommands/GitCommands.csproj, GitCommands/Settings/AppSettings.cs, GitCommands/Settings/BranchOrdering.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ToolbarSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ToolbarSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ToolbarSettingsPage.resx, GitUI/GitUI.csproj
Remark: this is work in progress, the location of the setting is under discussion, it should be moved somewhere else.
Fixes #3907.
- Add a configuration setting to choose the ordering criteria of the branches in the dropdown: by date (default) or alphabetically. 
Manually: 
1. Select branches in some order other than alphabetical
2. Verify that the dropdown shows the branches by selection date, from more recently to less recently selected.
3. Change the configuration from "Last access date" to "Alphabetically".
4. Verify that the dropdown shows the branches alphabetically
5. Change the configuration from "Alphabetically" to "Last access date".
6. Verify that the branches are …
=> Allow to choose branch order between alphabetical and by date

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Hotkey/HotkeySettingsManager.cs
Part of #4031
Some reimplementation needed after the split to RevisionDiff
Currently only used to delete files, should be added for at least stage/unstage and reset too.
- Windows 10
=> BrowseDiff Hotkey support: DEL to delete unstaged files

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/FormSettings.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Editor/FileViewer.cs, GitUI/UserControls/RevisionGrid.cs
Review comment in #4168
There a few other 'public const string' still remaining.
- Windows 10
=> Change hotkey settings names from const to static readonly

GitCommands/Git/GitStash.cs, GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/GitUI.csproj, GitUI/UserControls/ComboBoxHelper.cs
Fixes #4120 .
The existing implementation set the size of the combobox to the minimum of 200 and the available size (should probably have been max)
The width for the drop down was the same as for the combobox, may as well use the complete form
Some minor refactoring as well. 
- 
- Manually resizing
- GIT 2.15
- Windows 10
No mono tests. container sizes cannot be dynamically changed, not sure if the init function run, setting the size
=> Stash name size

GitCommands/Git/GitModule.cs, GitCommands/Git/GitRevision.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/UserControls/RevisionGrid.cs
Reset to Unstaged commits does not make sense at all and should be hidden in the GUI
Reset to Staged will require special handling of GitRevision. IndexGuid (Compare to RevisionDiffProvider, options to git-diff)
Part of #4031 
This is a reworked part of #4157 applicable to master too. This commit slightly changes the behavior and will be modified.
I did consider "reset to HEAD" for Unstaged commit to be always available, but that would be inconsistent behavior as well as when #4157 is merged selecting HEAD-Unstaged will give two options in the menu (not easily to find when this occurs).
- Select Unstaged commit (with changes)
- Verify that there is an option to reset to Index only
- Select Index Commit (with changes)
- Verify that there are options to reset to …
=> Reset to artificial commits require special handling

GitUI/CommandsDialogs/FormArchive.cs
by adding the name of the folder in the archive name
- Right click on a file or directory on the filtree
- Select "Archive"
- In the Archive form, click on "Save as..."
- The save dialog open with the new filename containing the name of the selected item at the end of the filename. 
- Not dependent of a specific git version
- Windows 10
=> Better naming of archives done through a filetree directory

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/RevisionFileTree.Designer.cs, GitUI/CommandsDialogs/RevisionFileTree.cs
* Like I said [here](https://github.com/gitextensions/gitextensions/pull/3921#issue-251483595), the filetree is the best place to add the feature "Assume unchanged". So, here is the PR!
* While I was at it, I also added the feature "Stop tracking" that is not easy to do in GitExtensions...
=> (A lot of) filetree improvements

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/GitUIExtensions.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/Helpers/DiffKindRevisionTests.cs
and add unit tests
This is a part of #4031 and rewrite/unittests were requested by @RussKie in
https://github.com/gerhardol/gitextensions/commit/7234d28588cad4b22f3dbc6ad58d8542449904c7#diff-95349e407fef1a99246ba82fa6aa7ba0
A small cleanup to handle order of revisions too, more to come in a later update.
That may also contain certain tweaks to the logic too.
This is a part of the solution, broken out so it can be reviewed.
- OpenWithDifftool()  rewrite
- None
- Unit tests added
- Manual tests
- GIT 2.15
- Windows 10
=> Restructure OpenWithDifftool() so it can handle artificial diff 

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiffController.cs
similar issue as fixed in f561501c7 (but GitModule not directly needed)
Module is not updated when git repo is changed
No functionality change
Module info can be transferred in ContextMenuSelectionInfo etc
- Compile
- Windows 10
=> Remove const GitModule

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/Editor/FileViewer.cs, GitUI/HelperDialogs/FormChooseCommit.cs, GitUI/UserControls/RevisionGrid.cs
In some situations (like difftool to local) it made sense to check if local files existed instead
Cleanup related to #4031
This was mentioned in a comment from @KindDragon for #4166 
A few of the items caused exceptions, moste just exited with warnings
The functionality may not be perfect after this, but better
There are no test cases related to this handling, it does not make much sense to add any either
(I consider adding test cases for RevisionDiffController that could touch upon this but will not add general testcases.)
This PR should have low importance (I do not see a a use case for GE with bare repos), but it should be relative simple to review.
- Happy testing both with empty bare repos and bare repos with info
Has been tested on (remove any that don't …
=> Some menu and command suppressions related to bare repositories

Plugins/Stash/StashPullRequestForm.cs
The Bitbucket plugin always made an exception when creating or approving pull requests
The core reason is that nothing is loaded (also with a configuration), but that is separate.
In #4204
- Open Bitbucket plugin
- Press Create, Approve, Merge
- Windows 10
=> Bitbucket plugin: Exception if not initialized

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiffController.cs
From #4031
The diff parent of a/b to local menu options should be visible in more situations
Refactoring of the calculations of options
-
- Manually
- Windows 10
=> Browse Difftool Menu Items cleanup

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs, GitUI/UserControls/RevisionGrid.cs
Fixes #3810.
- alternate back color (zebra) can be turned off, if desired
How did I test this code: manualy
- Windows 8.1
=> 3810 turn off zebra striping

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitItemStatus.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
Add the 'skip-worktree' feature next to the 'assume-unchanged' one in the commit form.
Works quite similary to the existing 'assume-unchanged' one.
In fact, the person that made the PR for 'assume-unchanged' do not really understand the differences or didn't know that 'skip-worktree' exists (To understand the differences, see: https://stackoverflow.com/a/13631525/717372 ). Consequently, proposing this feature in the commit form *make no sense* :(
'Assume-unchanged' should only be used for big files *that don't change* and that is costly to get status.
'Skip-Worktree' should be used for files the developer knows they have changed but don't want to commit and so don't want to see them in the unchanged file list.
'Assume-unchanged' is for files that don't change, so can't appear in the …
=> Skip worktree feature

UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/packages.config, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/packages.config, UnitTests/GravatarTests/GravatarTests.csproj, UnitTests/GravatarTests/packages.config, UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj, UnitTests/Plugins/ReleaseNotesGeneratorTests/packages.config, UnitTests/ResourceManagerTests/ResourceManagerTests.csproj, UnitTests/ResourceManagerTests/packages.config
Allow running tests in VS Test Explorer.
Useful when Resharper is not available
=> feat: Use VS Test Explorer

GitUI/CommandsDialogs/FormCheckoutRevision.cs
Scripts "AfterCheckout" or "BeforeCheckout" are now run on revision checkout
Fixes #4006
- GIT 2.13 and above
- Windows 8
=> fix: Activate scripts on revision checkout

GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/UIExtensions.cs, GitUI/CommitInfo/CommitInfo.cs, ResourceManager/CommitDataExt.cs, UnitTests/GitCommandsTests/CommitInformationTest.cs
* Mono didn't implement SelectionTabs for RichTextBox, so tabs aren't an option
* Monospaced font has to be used for the text, otherwise the padding won't work
Credits go to @Carbenium, originally proposed in https://github.com/gitextensions/gitextensions/pull/3099
- Windows 10
- Ubuntu 17.04
=> Pad fields in RevisionHeader with spaces instead of tabs

GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/CommandsDialogs/FormCheckoutRevision.cs, GitUI/CommandsDialogs/FormCreateBranch.cs, GitUI/HelperDialogs/FormResetCurrentBranch.cs
Create or checkout branch or revision for the already checked out revision no longer triggers submodule update.
Fixes #3899
How did I test this code: manuallly
- GIT 2.13 and above
- Windows 8
=> fix: Creating new local branch triggers updating submodules

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitDeleteRemoteBranchCmd.cs, GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/FormDeleteRemoteBranch.Designer.cs, GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs, GitUI/CommandsDialogs/FormDeleteRemoteBranch.resx, GitUI/GitUI.csproj, GitUI/GitUICommands.cs, GitUI/UserControls/RevisionGrid.cs
Introduces a new form to delete remote branches from a FormBrowse commit context menu.
This PR is suggested solution for issue #1583
(sorry for diff noise, there is a separate commit dealing with some style/formatting issues)
- List remote branches in a commit context menu under local branches.
Screenshots:
This is I guess the most complex demo, deleting several (3) remote branches from two different remotes.
Considerations:
- Maybe we don't need support for multiple remotes at the same time? That would simplify code a little.
=> Delete remote branch

Plugins/Bitbucket/BitbucketPlugin.cs
Use the product name instead of a description on one of the tasks is does (that is translated)
Clarify that the plugin is for Bitbucket Server only, a completely different API from Bitbucket Cloud
Part of #4204 
- Screenshot before #4210 was merged, sorted earlier in the list now
-
-
=> Change the display name for Bitbucket Server plugin

GitCommands/Git/GitCommandHelpers.cs
Fixes #4213
- GIT 2.14
- Windows 8
=> fix: Commands are duplicated in GE Gitcommand log

GitUI/CommandsDialogs/FormCommit.Designer.cs
Fixes #4057 .
- Insert emptyLabel between Commit buttons and Reset buttons. Move Reset buttons below checkboxes.
- before:
- after:
- I have tested it manually
- Windows 10
=> Separate Reset buttons from Commit buttons in FormCommit dialog

Plugins/Bitbucket/BitbucketPullRequestForm.Designer.cs, Plugins/Bitbucket/BitbucketPullRequestForm.cs, Plugins/Bitbucket/Settings.cs
The Bitbucket plugin had no functionality, because the load functions were never called. I have not tested old versions, but do not see when this last could have worked
The functionality is quite OK. The plugin can especially be used to see what branches to compare. Most reviewing should probably still be done in the Bitbucket web UI
I have done a few other tweaks:
* Sort the branches in the same way as Browse branches. Default by last usage, possibly by name (previously the default)
* Hidden the Reviewers form. The form was never filled with users or used (should have the default reviewers by default)
- 
- Bitbucket server required
- Created pull request
- Viewed existing PRs
- Approved PRs …
=> Bitbucket basic functionality #4204

GitUI/UserControls/PatchGrid.cs
Fixes #4233  .
Scroll patch grid so the next to apply patch is visible, when possible in the middle of the view so previous and next patches are visible
- GIT 2.15
- Windows 10
=> Patch grid: scroll to next to apply line

GitUI/CommandsDialogs/FormClone.cs
Fixes #4235 .
- Currently specifying a putty key file during cloning it it not saved to the .git/config of the clone repostory. This PR changes this.
- Cloned a repository from github using a putty key file from the gitextensions browse form
- Not sure how to test Explorer shell extension path
- GIT 2.14
- Windows 10
=> Save putty key during clone

GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs, GitUI/Translation/English.xlf
Part of #4031
(Only #4209 remains)
- Change settings text to better explain the functionality
- 
=> Change text in settings for artificial commits

GitCommands/Settings/FileSettingsCache.cs
Whenever <repo>/.gitconfig file gets updated there is a chance that the update would fail.
The issue is intermittent and may only happen on I/O-incapacitated systems (i.e. virtualised environment with McAfee AV).
The problem seems to be caused by `File.Replace` API. The code is refactored not to use it.
Fixes #4250
- GIT 2.12 and above
- Windows 8.1
=> 4250 fix unable to remove the file to be replaced

GitUI/CommandsDialogs/FormPull.cs
Whenever FormPull was loaded it applied user settings, which triggered
UI control events. These events caused NRE when the form was instantiated
by the TranslationApp.
Added guards against NRE.
Fixes #4258
=> fix: NRE in FormPull when running TranslationApp

GitUI/CommandsDialogs/FormBrowse.cs
Seen in #4242
No major impact
Also moved the feature check to the"Fill" function, as for other tabs
No change
- Manual
- Windows 10
=> GpgInfo was drawn also if tab was not selected

GitCommands/Git/GitStash.cs, GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/FormStash.cs, UnitTests/GitCommandsTests/Git/GitStashTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
As reported Eclipse does not follow the traditional git stash naming conventions and may use something like the following:
stash@{2}: classpathModify
This caused GE to fail with ArgumentOutOfRange exception while trying to parse the branch information.
* GitStash.Branch property removed as it is not being used anywhere.
* Added basic tests
Fixes #4263
=> fix: "View Stash" throws AOORE

.github/PULL_REQUEST_TEMPLATE.md
The original `How did I test this code` encourages the pull request author to answer the way how the tests were done, for example `Manually`, which doesn't provide value.
Feel free to reword as I'm not a native speaker.
=> Amend issue template to require WHAT instead of HOW tests were done

GitUI/GitUICommands.cs, Setup/Product.wxs
Fixes #4276.
- Add support for `github-mac://`
- Ran installer, and used github "Open in Desktop" link.
- Windows 8.1 and above
=> Support github-mac:// url scheme

GitUI/UserControls/RemotesComboboxControl.cs
Fixes #4283
- Fix the exception
- Fill the remotes dropdown
- 
- Before
- After
- Create a tag with a repo that has multiple remotes
- Make sure the dropdown list has the remotes when trying to delete the tag
- GIT 2.15
- Windows 10
=> Exception when trying to load the delete tag form

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/RevisionGrid.cs, ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Dynamically added/hidden tabs added implementation complexity, reduced UX and caused regressions under Mono.
Tabs now remain visible for artificial commits and provide minimal information.
Closes #4242 
Obsoletes #4254 #4273 
=> fix: Do not hide tabs for artificial commits

GitUI/CommandsDialogs/FormBrowse.cs
After #4275 weird logic to show the Diff tab at the first position stopped working. 
Move LayoutRevisionInfo from the constructor to OnLoad event.
=> TreeTabPage is not visible when ShowRevisionInfoNextToRevisionGrid is enabled.

GitUI/FormProcess.cs, GitUI/FormRemoteProcess.cs
Inspired by https://github.com/hiroponz/gitextensions/commit/e7c853c689bf925b3104141b62b7d07dd2e40848
Closes #1307
=> fix: Remove index.lock when abort git operations

GitUI/Script/ScriptManager.cs, GitUI/Script/ScriptRunner.cs
Previously only event scripts, if configured, asked for confirmation. Non event script would ignore the setting.
The confirmation logic has been moved so it applies to all types of scripts.
Fixes #1608
What did I do to test the code and ensure quality: run the app before and after the fix to verify that the confirmation is asked.
- GIT 2.13 and above
- Windows 8
=> fix: Non event script do not ask for confirmations

GitUI/CommandsDialogs/FormBrowse.cs
Reported in #4295 
Regression of #4208
https://github.com/gitextensions/gitextensions/pull/4208/files#diff-6d931ecb996aeb8676180da98e3f6861R185
- Enable Commit Count
- Start GE without loading a normal repository. This can be to load a bare repo before closing GE or untick "start with last directory on startup"
- Open normal repo with some staged and/or unstaged files
- Commit count should be visible
- Windows 10
=> Start Commit Count also if not starting with a normal repository

GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
Fixes #4322
- try-catch around invoking WebBrowserCtrl Navigate
- None
code review
- Windows 10/7
=> BuildReport exception displaying the report

GitCommands/RevisionGraph.cs, GitCommands/Settings/AppSettings.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/RevisionGridMenuCommands.cs
(A more graphical way to retrieve lost commits)
Screenshots:
- Add a new option:
- that permit to show lost commits logged in the reflogs (here an amended commit)
This feature was previously achievable, as a trick, by adding `--reflog` to the `branches` combobox but it was a too much hidden feature ;)
- manual test
- GIT 2.14.3 and above
- Windows 10
=> FormBrowse: Add option to display reflog references

GitUI/UserControls/RevisionGrid.cs
Having all the branches and remotes of the commit line corresponfing to the checked out branch/revision is misleading and bring confusion to developper (and not reflect how git works).
This PR is here to improve the highlighting of the current branch checked out (because no one understand or look at these little triangles!!!)
* before:
* after (only the good branch is in bold):
* before:
* after (no branch is in bold because we are on a commit revision):
* before:
* after (better because a submodule point toward a commit):
* Manual test
- GIT 2.14.3 (but should have no effect on the change) 
- Windows 10
=> Display branch name in bold only when it is the one checked out

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormFileHistory.cs
To be consistent with handling in #4275
The Blame tab is not adding anything to FileHistory, just dummy information as in the Browse Commit tab, but the behavior should be consistent.
(This was a review comment to #4275)
- Always show Blame tab also for artificial commits, no dynamic removal/add
- 
- 
- View artificial commits (enable in settings)
- Show file history for a file
- Select artificial commit
- Verify that Blame tab is visible, with dummy information
This PR just removes code, so this simple test is sufficient
- Windows 10
=> FileHistory: Show Blame tab also for artificial commits

GitCommands/AppTitleGenerator.cs, GitCommands/GitCommands.csproj, GitCommands/Repository/RepositoryDescriptionProvider.cs, GitUI/CommandsDialogs/FormBrowse.cs, UnitTests/GitCommandsTests/AppTitleGeneratorTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
* Extract the application title generation from FormBrowse into `AppTitleGenerator`.
* Move functionality dealing with repository description from FormBrowse into `RepositoryDescriptionProvider`
=> Refactor app version to the main title

GitCommands/Git/GitModule.cs, GitCommands/Git/RevisionDiffProvider.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, UnitTests/GitCommandsTests/Git/RevisionDiffProviderTest.cs
Reported in #4301, some explanations there as well as screenshots
This mostly drops some special checks, a few lines to handle untracked with git-diff --no-index
* "if (parentRevision == null)" in ViewChanges() were never taken. If so, it would have displayed the untracked similar to FormCommit.
Using ViewFile as done in FormCommit would have been cleaner and better presentation than current but not presenting as diff. For instance,  FileReader.ReadFileContent(fullPath, diffViewer.Encoding) will not check for binary files and will present garbage or give exceptions.
* IsItemUntracked() was slightly incorrect (should have used file.IsTracked)
- See #4301 
- Enable view of artificial commits, …
=> Browse Diff presentation of Untracked files

GitExtensions.VS2015.sln, GitExtensionsMono.sln, UnitTests/CommonTestUtils/CommonTestUtils.csproj, UnitTests/CommonTestUtils/EmbeddedResourceLoader.cs, UnitTests/CommonTestUtils/GitModuleTestHelper.cs, UnitTests/CommonTestUtils/Properties/AssemblyInfo.cs, UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs, UnitTests/GitCommandsTests/Git/GitDirectoryResolverTests.cs, UnitTests/GitCommandsTests/Git/IndexLockManagerTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
Extract utils common to all unit tests as a separate project so it can be references by any unit test project requiring it.
=> Add common unit test utils as a separate project

GitCommands/SynchronizedProcessReader.cs
I've come by this code when I was doing some random benchmarking, started investigating and learned about native stream CopyTo implementation available since .NET 4.0
Been using this implementation for several months and haven't noticed any side effects.
=> Use built-in stream.CopyTo method in SynchronizedProcessReader

GitUI/CommandsDialogs/FormRemotes.cs
In the remote form a user couldn't add a new remote if a deactivated remote was selected - the management panel stayed disabled.
Enable the management panel when no remote is selected.
Fixes #4349
- run the code manually to ensure the issue is fixed
=> fix: Unable to add remote having selected deactivated item

Plugins/Bitbucket/BitbucketRequestBase.cs
Closes #4345
https://confluence.atlassian.com/cloudkb/xsrf-check-failed-when-calling-cloud-apis-826874382.html
See the issue for an explanation of the status of the plugin in GE in 2.50 and earlier.
- Add header to Bitbucket requests
- Manual testing in the plugin. Verified that PRs could be approved and merged as well as existing functionality is working as before.
=> Bitbucket server: XSRF error when approving or merging pull requests

GitUI/CommandsDialogs/FormFileHistory.cs
Regression in #4308 9f5fe413
Fixes #4315
bug, regression in 2.51.RC1
Introduced in 9f5fe41
- FormFileHistory, enable diff-to-local when local file exists
- Context menu in revision grid
- DiffToLocal isenabled when a local file exists
- Windows 10
=> FormFileHistory: DiffToLocal hidden also when relevant

GitUI/CommandsDialogs/RevisionDiff.cs
New functionality in 2.50.02 #4031, regression from #4208 9f5fe413
Fixes #4316
- Functionality enabled in 2.51 #4031 is not enabled due to an incorrect check introduced in #4208 9f5fe41
- after
-   View Unstaged commits
-   Edit and Delete menu items are available
=> Browse Diff Untracked: Delete and Edit menu items are not enabled

GitUI/CommandsDialogs/FormCreateBranch.cs
Mono failed to correctly size and layout the groupbox pushing all controls below it beyond the client rectangle.
Fixes #4319
- before
- after
- run it manually before and after
- Windows 10
- Ubuntu 17.04
=> fix: FormCreateBranch layout under Mono

GitCommands/Git/GitModule.cs
Related to #4374, seen in code review and tests related to #4385 
Command line has no arguments at all which is interpreted as two "working directory" revisions, where the result is undefined.
The combination raises Debug.Assert, but gives the diff from staged to unstaged
This diff changes the defaults to the values used
- Set default arguments corresponding to the expected use for difftool. All other usages set the parameters
- None
- Manual test
- Debug build
- Run from command line: "GE executable" difftool "existing-file-with-changes"
- Code review
- Windows 10
=> Commandline difftool raised Assert

GitUI/HelperDialogs/FormCommitDiff.cs
Fixes #4374
Regression from #4313 when argument order was cleaned up
Previously, the order was occasionally first..second, other time it was second..first so changes were difficult. This place was missed in the review
- View FormCommitDiff for changed files
- Check for similar usage
- Windows 10
=> FormCommitDiff: diff was reversed

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormStash.cs
Part of #4373
GitItemStatus.IsTracked should be set for all file-revisions handled by Git, i.e. all but working file directory files
This was not set for GetTreeFiles(). This is called for revisions without parents: First/detached commit and stash-untracked.
These files were therefore presented as the difference to the local file if local exists.
In addition, stash-diff was displayed inverted. This was a regression from #4157 (This would have been a separate PR if not the same line was changed as for this PR)
- Set IsTracked for files in commits without parents
- Diff and presentation incorrect for commits without parents in browse-diff and view-stash …
=> Git treefiles were not set as tracked, stash diff was inverted

GitUI/UserControls/RevisionGrid.cs
Fixes #3935.
- after _Edit commit_ or _Reword commit_ command is run, the revision grid is refreshed.
- ran both commands and checked that the revision grid is properly refreshed
- for the _Edit commit_ command, I also tried amending the commit and finishing the rebase outside of GE, so that no GE dialogs were opened which would cause the refresh themselves
- GIT 2.15.1
- Windows 10
=> Refresh the UI after the interactive rebase command

GitUI/AutoCompletion/CommitAutoCompleteProvider.cs, GitUI/CommandsDialogs/BrowseDialog/FormBrowseUtil.cs, GitUI/CommandsDialogs/FormAddToGitIgnore.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormGitAttributes.cs, GitUI/CommandsDialogs/FormMailMap.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/GitIgnoreDialog/GitIgnoreModel.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUICommands.cs, GitUI/UserControls/FileStatusList.cs
Part of review for #4318, done in the occurrences where it seemed natural
Fixes #4316
- Consistently use IFullPathResolver to resolve paths to files
- None
- Code review, partial tests
- Windows 10
=> Refactor: Use IFullPathResolver to resolve paths

GitUI/CommitInfo/CommitInfo.cs
Fixes #4361
- Prune commit info retrieval for artificial commits
- assert for empty guid. this should never occur, but changes could cause this to happen and the coder should be notified
-none
- View artificial commits
- Verify no artificial commits in the log
- Windows 10
=> Do not call git-log etc for artificial commands in commit info

GitUI/Editor/FindAndReplaceForm.Designer.cs, GitUI/Editor/FindAndReplaceForm.cs
Always display the dialog near the top left corner of the parent form.
That prevent the dialog to be displayed on the 1st screen while
GitExtensions is displayed on the 3rd screen!
- tested manually
- GIT 2.15 (but not important)
- Windows 10
=> Better display of "Find and replace" dialog on multiple screens computer

GitUI/CommandsDialogs/FormMergeBranch.cs, GitUI/Script/ScriptInfo.cs
Fixes #4380 .
- Add two ScriptEvents,  BeforeMerge, AfterMerge
- Manual
- Windows 10
=> Add ScriptEvent BeforeMerge, AfterMerge

GitUI/CommandsDialogs/FormCommit.cs, Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- (improve perf) Don't block FormCommit opening during http request to jira (the plugin made the commit form slow to open :( ). Introduce some async (remove a `.Result`)
- Fix display of multiline text in multiline setting textbox ( of jira setting panel "Message template" textbox )
- (minor) Better display of the preview message
- manual test
- GIT 2.16
- Windows 10
=> Fixes on jira commit hint plugin

GitCommands/Git/GitRevision.cs, GitUI/CommandsDialogs/FormArchive.cs, GitUI/HelperDialogs/FormChooseCommit.cs, GitUI/HelperDialogs/FormCommitDiff.cs, GitUI/UserControls/CommitPickerSmallControl.cs, GitUI/UserControls/CommitSummaryUserControl.cs, ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs, ResourceManager/LinkFactory.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererIntegrationTests.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs
There were couple of places using the `SubString(0, 10)` to get the short SHA, this pull request refactored them to use the same function.
The only UI change is the length of the SHA changed from 8 to 10 when checking out a branch with reset pending changes ticked.
- Verified that the SHAs of the children and parents are displayed correctly as hyper links when a commit is selected.
- Verified the SHAs of the children and parents are displayed correctly as normal text on the commit detail form (via double clicking a commit)
- Verified the SHA is displayed correctly when checking out branch with reset local changes is ticked.
- Didn't test Mono, but I believe no regression
- GIT 2.15
- Windows 10
=> Refactoring to use same function to get the short sha

GitCommands/Git/GitCommandHelpers.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/GitUICommands.cs
by selecting the files to add.
- Renamed "View stash" to "Manage stashes..."
- Add an item to open the stash form directly on the working directory changes to be able to create the stash more easily 
- being able to select the files to stash (and not imperatively all!)
- GIT 2.15
- Windows 10
=> Add feature to be able to do a partial stash

GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Reported in #4069
Should be reviewed together with #4328 
GE can in some situations  use a lot of CPU and disk load, as it runs "git status --untracked-files" at changes in the filesystem
If a status command is not done before next update is detected, the next start immediately after. "git status" can therefore run continuously.
(This is more visible with certain viruses like Symantec and McAfee.)
This PR limits the checks in two ways:
* First run is started after 1000ms + timer (fires every 500ms so adds on average 250ms) instead of 500ms +timer, to collect more changes (probably not essential)
* Next command is started minimum 3000ms after the previous command. If 3*time to run the status update is longer than 3000ms, the interval time is dynamically increased.
So normal one shot …
=> Limit how often GitStatus polls for changes

Setup/BuildGitExtNative.cmd, Setup/BuildInstallers.Mono.cmd, Setup/BuildInstallers.VS2015.cmd, Setup/BuildInstallers.VS2017.cmd, Setup/MakeInstallers.cmd, Setup/MakeMonoArchive.cmd, Setup/Product.wxs, Setup/Setup.wixproj, Setup/hMSBuild.bat, appveyor.yml
The current build scripts have a number of hardcoding and requires a number of manual updates.
This is a step to simplify the build process and make it easier for users to test creating Setup
* Download and build the binaries when building wix project
* Use variables in product.wxs, no Mono in VS*cmd, use Configuration variables, remove c++ projects. It is now possible to build setup in Debug
* Use hMSBuild to build, common 2017/2015 detection of msbuild
Second step of #4069 
This is not making much difference in itself, it is a preparation for future changes
- Build on Appveyor
- Manual builds
- Windows 10
=> Installation scripts should allow for IDE build, also in Debug

Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
* Move "jira fields" help just near the template field where it's useful
* Add a link toward the jira query helper 
- "jira fields" moved
- Link introduced
- the page reached with the query validation
- manual test
- GIT 2.15
- Windows 10
=> Improve jira plugin again

GitUI/Translation/English.Plugins.xlf, Plugins/Bitbucket/BitbucketPullRequestForm.Designer.cs, Plugins/Bitbucket/BitbucketPullRequestForm.cs, Plugins/Bitbucket/BitbucketPullRequestForm.resx, Plugins/Bitbucket/GetPullRequest.cs
Issue #4229
A few of the improvements in the issue implemented.
* A link to copy the URL to the web interface
* View PRs as first tab, Create as second (as create is very limited)
* Sort PRs so the newest is on top
PRs are not shown, not connected to BB server
- 
- 
- Manual tests
=> Bitbucket Server tweaks

Setup/DownloadExternals.cmd, Setup/Product.wxs, Setup/UI/RequiredSoftwareDlg.wxs
Issue #4312
- Set the Git version bundled with GE to be the latest available 2.16.1 (works for me, 2.16.0 had issues with reset)
I would prefer to drop Git bundling completely, just offer a download link at installation, but that is a separate discussion.
There will likely be updates to Git until next major release too, so Git should maybe updated again. This commit could be used in a GE 2.51.x release.
- Build the installer
- Use 2.16.1.1 since release, 2.16.1.2 for a day
- GIT 2.16.1.2
=> Update bundled Git version to 2.16.1-windows.2

.travis.yml
Temporary workaround after #4430 removed Mono and thereby Travis builds
The proper solution is to remove the requirement for successful builds
=> workaround for Travis build requirement

GitUI/CommandsDialogs/FormClone.cs
This should at least partly fix #2313.
In the Clone Repository dialog set the Destination directory to the parent of the current working directory, rather than the working directory itself. It makes no sense to clone into the working directory itself, but the user is likely to want to the new working directory to be a sibling of the current one.
Tested on git 2.15, Windows 7 x64
=> Smarter default for Clone Destination directory

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitItemStatus.cs, GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Should be reviewed together with #4327, this PR is based on #4327 even if the changes can be separated.
Issue #4256
Listing ignored files with a separate "ls-files -o -i --exclude-standard" seem to never exit in some situations, see #4256
This reuses the git-status call with --ignored as an option to get the ignored files. (The option is only added when ls-files were called previously.) This call did not seem to hang with many ignored files and the command runtime does not increase much.
The solution is not optional though. It still lists all ignored files in memory. The time to find ignored files is faster, but a lot of memory is needed. #4256 has some discussions.
Also, processing all output to GitStatusItem first before creating the HashSet will require some more memory (temporary) …
=> Commit count: Listing ignored files could hang GE

GitExtensions/app.config, Plugins/Bitbucket/Bitbucket.csproj, Plugins/Bitbucket/packages.config, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.csproj, Plugins/JiraCommitHintPlugin/app.config, Plugins/JiraCommitHintPlugin/packages.config
* ConEmu
* Git.hub
Also consolidate RestSharp dependency.
Atlassian.SDK had to be updated too, because the older version was bound to an old version of Restsharp which was not signed. This made it impossible to set a binding redirect.
Relates to #4426 #4427 #4428
- run locally to ensure no binding errors
- run Assembly Binding Log Viewer to ensure no binding errors
=> Update submodules after package updates

GitExtensionsVSIX/GitExtensionsVSIX.csproj, GitPlugin/GitPlugin.csproj, GitPlugin/Plugin.cs, GitPluginShared/GitPluginShared.csproj
Unable to build current master in VS2017 on a computer which has only VS2017 installed.
Fixes: #4458
- Windows 10 with VS2017
=> fix: Unable to solution build in VS2017

Gravatar/Gravatar.csproj, Gravatar/GravatarService.cs
Fixes #3770.
- When the user's email adress is <username>@users.noreply.github.com, use Github API to retrieve avatar instead of Gravatar
- Before:
- After:
- GIT 2.13.0
- Windows 10 (FCU)
=> Add support for Github avatar

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Patch/PatchManager.cs, GitCommands/Remote/GitRemoteManager.cs, GitCommands/Repository/RecentRepoInfo.cs, GitCommands/Settings/AppSettings.cs, ResourceManager/Xliff/TranslationUtl.cs, UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs
Local functions offer some performance benefits, as well as looking a bit nicer (see the example in `GitCommandHelper.cs` where the `null` assignment can be removed in favour of a single declaration).
The main performance improvement is the compiler's ability to avoid heap allocation when closing over state.
For more information, see https://stackoverflow.com/a/40949214/24874
- GIT 2.16
- Windows 10
=> Replace some lambdas with local functions

GitCommands/Git/GitModule.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/UserControls/BlameControl.cs
In some cases blame show incorrect history. 
Closes #2342.
How reproduce:
1) Create and commit file with this content:
`1`
`#if (defined(WIN32) || defined(WIN64)) && defined(RELEASE)`
`2`
`#endif`
`3`
`#if (defined(WIN32) || defined(WIN64)) && (defined(RELEASE) || !defined(DEBUG))`
`4`
`#endif`
`5`
2) Modify file to this:
`1`
`#if (defined(WIN32) || defined(WIN64)) && (defined(RELEASE) || !defined(DEBUG))`
`2`
`#endif`
`3`
`#if (defined(WIN32) || defined(WIN64)) && (defined(RELEASE) || !defined(DEBUG))`
`4`
`#endif`
`5`
3) Show blame.
I expect to see that second line changed in second commit, but blame show another.
- Remove -M parameter from blame command. It make git don't try detect copy or move lines in file. Furthermore i don't sure that …
=> Make blame options -w -M -C switchable #2342

GitCommands/Git/GitModule.cs, GitCommands/Git/GitRevision.cs, GitCommands/Git/GitRevisionProvider.cs, GitCommands/GitCommands.csproj, GitCommands/RevisionGraph.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormReflog.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/HelperDialogs/FormChooseCommit.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/RevisionGridMenuCommands.cs, UnitTests/GitCommandsTests/ExternalLinks/ExternalLinkRevisionParserTests.cs, UnitTests/GitCommandsTests/Git/GitRevisionProviderTests.cs, UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitUITests/Helpers/DiffKindRevisionTests.cs, UnitTests/GitUITests/UserControls/AuthorEmailBasedRevisionHighlightingFixture.cs
`GitRevision` is a DTO yet it contains behavioural components.
`GitRevision.CreateForShortSha1` functionality moved into `GitRevisionProvider`.
The functionality is moved as is.
Added unit tests
=> Refactor GitRevision

GitCommands/Git/Extensions/GitRevisionExtensions.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitRevision.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/RevisionGrid.cs, ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs, UnitTests/GitCommandsTests/Git/Extensions/GitRevisionExtensionsTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
GitRevision is a DTO yet it contains behavioural components.
Check for artificial commit is not a function of GitRevision.
Any revision inherently knows whether it is artificial or not. However checking an arbitrary hash for being artificial is not a function of GitRevision.
For now, the functionality moved into an extension method. This way it can be tested and used universally.
=> refactor: Extract IsArtificial functionality from GitRevision

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
- And a feature to undo last commit of the current branch
- GIT 2.15
- Windows 10
=> Add "undo last commit" feature

GitCommands/Git/LongShaProvider.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/HelperDialogs/FormChooseCommit.cs, GitUI/UserControls/RevisionGrid.cs, UnitTests/GitCommandsTests/Git/LongShaProviderTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
No functionality change.
The `GitRevisionProvider` returns a `GitRevision` object but only sets the `Guid/Sha` property, everything else in this object is null.
- Compile the solution
- Run the unit tests
- FormBrowser: Select a commit in the revision grid, F5 to refresh, make sure selection of the commit is kept
- FormChooseCommit: Right click a commit -> select the check out menu -> press the choose a commit button -> make sure the commit is selected by default.
- FormFileHistory: find two commits that changed the same file -> select the older commit in the revision grid -> select the file in the diff and view its history -> make sure in the popup the older commit is selected. …
=> Refactor the GitRevisionProvider to LongShaProvider as it only sets the Sha property of the GitRevision object

GitUI/CommandsDialogs/FormSubmodules.Designer.cs
Fixes #1858 Submodule dialog: "Name" textbox too small for long names.
"Name" column in the list view could be amended as part of #4366 
- Align submodule details by right side
- before:
- after:
=> Align submodule details. Fixes #1858

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormRebase.cs, GitUI/CommandsDialogs/MergeConflictHandler.cs, GitUI/GitUICommands.cs, GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid.Designer.cs, GitUI/UserControls/RevisionGrid.cs, Plugins/GitUIPluginInterfaces/IGitUICommands.cs
Fixes #3853 .
**What is the problem?**
- When rebasing, unlike merging, which branch is selected doesn't matter as long as the branches are pointing to the same commit.
- A lot of people don't know there is interactive rebase feature in GitExtensions as the option is an advanced option which is hidden by default.
- The popup dialog is not necessary, usually can be skipped.
**What is proposed?**
- Remove the branches from the sub context menu
- Add a rebase menu item (rebase straightway without the rebase dialog popup)
- Add an interactive rebase menu item(rebase straightway without the rebase dialog popup)
- Add a rebase with advanced options menu item(rebase with the rebase dialog popup)
**Before** …
=> Added menu to perform immediate rebase and interactively rebase without the rebase dialog

GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
During a profiling pass I observed a few cases of extreme contention locking `_graphData` causing the scrolling operation to be slow (in two cases producing a hang on the UI thread of more than 10 seconds). Hoisting the lock outside the loop substantially reduced the number of times the lock is acquired by the background thread, eliminating the primary source of the problem.
=> Fix contention during scrolling

GitCommands/RevisionGraph.cs
Fixes #4516.
- Fix the git log command argument construction bug
- Remove temporary strings during argument construction
- Tested that string output was the same before/after
- Manual tests
- Unit tests
- GIT 2.16
- Windows 10
=> Fix git log command arguments and reduce allocations

GitUI/CommandsDialogs/FormFileHistory.cs
Fixes #4524
Although #4525 has also fixed the same issue, it might be safer to add the null check to keep the original behavior unchanged.
- Fixed crash when double click to open File History Form
- Double click the file in the File Tree tab to open the its history
- Double click the file in the Diff tab to open the its history
- Right click and select the `View History` menu of the file in the File Tree tab to open the its history
- Right click and select the `View History` menu of the file in the Diff tab to open the its history
- GIT 2.16
- Windows 10
=> Fixed crash when double click to open File History Form

Setup/DownloadExternals.cmd, Setup/Product.wxs, Setup/UI/RequiredSoftwareDlg.wxs
Part of #4515 an a few other issues
Resolves #4523 
This is a preparation if unbundling of Git is not done for next GE 2.51 release
Note: master has 2.16.1.2, this has the currently latest 2.16.2.1 version
- Update Git package
- Running 2.16.2.1 manually
- GIT 2.16.2.1
- Windows 7 / 10
=> Update the bundled Git version to latest version 2.16.2.1

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionFileTree.cs
from 'file tree' and 'diff' tabs
Fixes #4524
=> Fix crash when double click to open `FileHistory` form

GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/FindFilePredicateProvider.cs, GitUI/GitUI.csproj, GitUI/GitUICommands.cs, UnitTests/GitUITests/FindFilePredicateProviderTest.cs, UnitTests/GitUITests/GitUITests.csproj
Fixed: #4472 Find file dialog doesn't work with backslash ('\\') and full file path.
- Replace backslash(\\) by slash(/) in filename;
- Skip repository path if filename start with it;
- After changes:
- ![1](https://user-images.githubusercontent.com/5438647/36096880-52b1e7de-1009-11e8-8d1d-364133260459.png)
- Test file search from File Tree tab (Ctrl+Shift+F);
- Test file search from Diff tab (Ctrl+F);
- Test command 'searchfile' using for VS plugin;
=> Improve find file dialog

GitCommands/Git/Tag/GitTagController.cs, GitUI/CommandsDialogs/FormCreateTag.cs, GitUI/CommandsDialogs/FormVerify.cs, UnitTests/GitCommandsTests/Git/Tag/GitTagControllerTest.cs
Fixes #4358
- Move the UI and command execution into the GitTagController where it can then cleanup the temporary file.
- Added 3 testcases for annotated tags.
- Throw if the exceution function is null
- Deletes the temporary tag regardless of the execution result.
- Windows 10
=> Delete TAGMESSAGE after tag command completes

GitUI/CommandsDialogs/RevisionFileTree.cs
Fixes #4535
Reset folder was not visible after #4165 and other PRs. In 2.50 it was possible to get various exceptions and irrelevant menu items.
Also, some other menu items were cleaned up in this PR
- 
- Manual tests
- GIT 2.16
- Windows 10
=> #4535 Reset folder in file tree regression in 2.51

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/FindAndReplaceForm.cs, GitUI/Editor/IFileViewer.cs, GitUI/GitUIExtensions.cs, GitUI/UserControls/FileStatusList.cs
Keep only one path of loading diff into fileviewer control.
Fixes #4485.
(cherry picked from commit 7c99be9f0a80975826256b10dcdbadea2e8b54f5)
=> Await for diff being loaded.

GitUI/GitUI.csproj.DotSettings
No code and behavior change. Just remove the settings so that ReSharper can detect the currently language version instead of being restricted to 6.0
=> Remove settings that restricted ReSharper to C# 6.0 syntax

GitCommands/Git/GitRevision.cs, GitCommands/Git/GitRevisionTester.cs, GitCommands/GitCommands.csproj, GitUI/UserControls/RevisionGrid.cs, UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
GitRevision is a DTO yet it contains behavioural components.
Checking that GitRevision contains an arbitrary piece of information is not a responsibility of GitRevision.
GitRevisionTester is introduced which is responsible to checking whether a given GitRevision matches
the given criteria.
Added tests
=> refactor: Extract MatchesSearchString functionality from GitRevision

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Editor/FindAndReplaceForm.cs
(cherry picked from commit eb075dd374b6af027b99f89e556a5f68bcabcdf8)
Fixes #4570 
Same as #4572
=> Handle OperationCanceledException. Fixes #4570.

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormLog.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/HelperDialogs/FormCommitDiff.cs, GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Resolves #4561
Refactoring to consistently use Revision and Parents in FileStatusList
FileStatusList forms should use that instead of assuming parents from RevisionGrid.GetSelectedRevisions().
The changes will remove code too.
Note: This commits enables corrections for #4387 and #4396 etc too.
- Refactoring
- GIT 2.16
- Windows 10
=> FileStatusList handling of parents and selected revision

GitCommands/Git/GitCommandHelpers.cs, GitUI/CommandsDialogs/RevisionDiff.cs
Part of #4564
- Commands for submodules in Browse Difftab was added to 2.51 were only applicable for single submodules. This makes them work with multi selection too, limiting popups when possible.
Note: Multiselection will be enabled in a later PR, the screenshot is for future reference.
- 
- 
- Manual tests - menu tests in later PRs
- Windows 10
=> Browse Diff: Submodule commands should operate on multiple submodules

GitUI/CommandsDialogs/FormMergeBranch.cs
Fixes #4464 
- Fixing the issue with the 'Branches' drop-down not being focused.
- Tested it.
=> Force branch selection when opening 'Merge branch' dialog (Ctrl + M)

GitUI/HelperDialogs/FormCommitDiff.cs, GitUI/UserControls/FileStatusList.cs
Fixes #4579, introduced in ab8d864 (PR #4562)
Launching `FormCommitDiff` from the revision grid showed an empty form.
Bug has two parts:
- calling an overload of `SetDiffs` that doesn't load revision data
- not setting `CommitInfo.Revision`
@gerhardol please review this for correctness.
Screenshots:
_before_
_after_
- Windows 10
=> Fix recent bug in FormCommitDiff

.editorconfig
Updates .editorconfig to fix the indent size when working in .props and/or .targets files.
=> Fix the indent size for *.props and *.targets

GitExtensions/GitExtensions.csproj, TranslationApp/TranslationApp.csproj
I was observing substantial build time in the `AddPluginBinaries` target in Visual Studio 2017 version 15.6. This pull request updates the code to avoid the use of `**` in this target, which *should* still work the same as before but is about 60x faster on my machine.
:memo: If accepted, please do not rebase or squash this pull request during the merge.
=> Improve performance of AddPluginBinaries target

GitUI/CommandsDialogs/FormRebase.Designer.cs, GitUI/CommandsDialogs/FormRebase.cs
Fixes #4588.
- a Commit button has been added to the Rebase dialog
Before:
After:
- interactively rebased a branch and when the process stopped at a commit, tried clicking the button and amending the last commit (both content and commit message)
- Git 2.16.2
- Windows 10
=> Add the Commit button to Rebase dialog

.travis.yml
Fixes #4430
Travis was removed in #4434 and readded in #4438, but requirement is now removed so it can be removed in 3.00 again
- Windows 10
=> Remove Travis build

appveyor.yml
Fixes #4602
This was verified by submitting a test commit to #4601, which contained a failing test at the time. AppVeyor build [3.00.00.1862](https://ci.appveyor.com/project/gitextensions/gitextensions/build/3.00.00.1862) failed as expected.
=> Fix AppVeyor ignoring test outcome

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, GitUI/HelperDialogs/FormCommitDiff.cs
Fixes #4580
Regression from #4313
Non-existing commits are handled with the "revision" null which is mostly handled as a working directory file.
The compare options for working directory files were limited in 2.50. In 2.51 the changes are presented with git-diff if possible and the non-existing parent were incorrectly handled.
- 
- 
- Manual tests of initial commits and to compare to/from working directory for changed/new/deleted files
- GIT 2.16
- Windows 10
=> Diff for initial commit of a file were presented as a diff to local

GitExtensionsShellEx/GitExtensionsShellEx.vcxproj, GitExtensionsShellEx/StdAfx.h, UnitTests/GitCommandsTests/Git/RevisionDiffProviderTest.cs
Also:
LNK4075 when building in Debug
SA1005 for test cases only run in Release builds
Fixes #4594
- Suppress and remove compile/link warnings
Annoying to see in AppVeyor builds
n/a
- Build only - no changes to code
- Windows 10
=> Compile warning #4091 in shlobj.h

GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/GitUIExtensions.cs
For merge commits, the difftool compare was always done for the primary parent
This is also required to support feature #4564
Part of #4564, requires #4562
Submitted to show allow review of the change for this and following PRs
- Correct revisions for difftool invocations
- n/a
- Manual test open difftool
- Windows 10
=> Browse Diff: Incorrect comparision for multiple parents

GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/GitUI.csproj, GitUI/HelperDialogs/FormCommitDiff.Designer.cs, GitUI/HelperDialogs/FormCommitDiff.cs, GitUI/UserControls/CommitDiff.Designer.cs, GitUI/UserControls/CommitDiff.cs, GitUI/UserControls/CommitDiff.resx
Very often when viewing file history I feel the need to see commit info / context when a specific change was made. Opening a commit from a context menu is too slow (too many context switches from UX perspective).
- Extract CommitDiff user control from FormCommitDiff
- Add Commit tab in FormFileHistory and use CommitDiff in it
- Remove Open Commit context menu item
- UX bliss :)
- Before
- After. Notice commit tab in file history
- GIT 2.16.1
- Windows 10
=> Commit info in history form

Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
This is a simple and obvious fix, identified by @sharwell while reviewing StyleCop.Analyzer changes in #4587. To be clear, SCA didn't introduce the bug, it simply made it obvious.
https://github.com/gitextensions/gitextensions/pull/4587#pullrequestreview-102869547
=> Fix precedence bug in logical expression

Directory.Build.props
As recommended by @sharwell at https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/2630
=> Ignore CS1712 warning

GitCommands/Git/GitGpgController.cs, GitUI/UserControls/RevisionGrid.cs
If the fact that a string matches a regex is needed, there's no need to construct the entire `Match` objects. This PR addresses the places where `Match` was called but this full allocation could have been avoided via `IsMatch` instead.
Apologies for the formatting change in the second commit (1f29cea). The change from `Match` to `IsMatch` happens in 06e478e. I am massaging local commits into separate pull requests and this was the only way I could avoid conflicts and maintain separate PRs.
- Manual review of change
- Unit tests
- GIT 2.16
- Windows 10
=> Use Regex.IsMatch over Regex.Match().Success

GitCommands/Git/GitRevision.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/GitRevisionTests.cs
Method previously accepted any string that contained a SHA-1 anywhere in its body. With this change, the string must be exactly 40 characters in length and contain only lower-case hex characters.
Added unit test and XML documentation.
- Add failing unit test then make it pass
- Review usages of this method to ensure they won't break
- Add API documentation
=> Fix bug in GitRevision.IsFullSha1Hash

GitCommands/Settings/FileSettingsCache.cs
This ensures an unique file name among processes that save settings at the same time.
Fixes a possible root cause of #3929.
Tested manually.
- GIT 2.15
- Windows 10
=> Add the current process id to the tmpFile name.

GitCommands/Git/GitModule.cs, GitUI/Editor/FileViewer.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/NavigationHistory.cs
Following [this comment](https://github.com/gitextensions/gitextensions/pull/4615#discussion_r173673944) from @sharwell, this PR inverts a few if/else statements in order to return early from methods and reduce nesting.
- Manual review of automated changes
- Unit tests
- GIT 2.16
- Windows 10
=> Invert if/else to bring precondition early and reduce nesting

GitUI/CommandsDialogs/FormFileHistory.cs
Regression from #4554
- Incorrect tab icons
-                 imageList.Images.Add(Properties.Resources.IconViewFile);
- 
- View form
- Windows 10
=> #4554 added a new Commit tab but did not adjust the tab icons

GitExtUtils/Linq/LinqExtensions.cs, Plugins/Gerrit/GerritPlugin.cs
Pretty simple change. Will annotate the diff with descriptions.
=> Fix invalid usages of ArgumentNullException

Plugins/Gerrit/FormGerritPublish.Designer.cs, Plugins/Gerrit/FormGerritPublish.cs, Plugins/Gerrit/FormGerritPublish.resx
Fixes #4571 .
- Add a reviewers field to Gerrit Push which takes space-separated user IDs
- Tested with latest Gerrit, validated format with https://gerrit-review.googlesource.com/Documentation/user-upload.html#reviewers
- GIT 2.15.1.windows.2
- Windows 10
- Gerrit 2.14.6
=> Added reviewers field to gerrit push form. Fixes #4571.

GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
Dictionary.DropDownStyle became DropDownList in commit 310a55c3c2 so Dictionary.Items must contain what we want to set in Dictionary.Text.
Fixes #4443.
- Preload Dictionary.Items with the current AppSettings.Dictionary if that current dic file exists so that Dictionary.Text will accept the current dictionary.
- Retain the current dictionary selection during Dictionary_DropDown where previously Dictionary.Items.Clear did make Dictionary.Text invalid and therefore automatically clear the current choice.
I intentionally chose to retain the existing behaviour of loading of the list at the time the drop-down button is clicked rather than loading it as a fixed list at the time the form is created. This enables a user to copy in a new dic file then choose …
=> Fix Dictionary.Text not accepting AppSettings.Dictionary

GitCommands/GitCommands.csproj, GitCommands/Remote/RepoNameExtractor.cs, GitUI/BuildServerIntegration/BuildServerWatcher.cs, Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs, Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs, Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs, Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs, Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerWatcher.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/RepoNameExtractorTest.cs
%REPO_SHORTNAME%
From #4202
Allow us of variables for the name of projects for build server integration. That makes it possible to have one global setup for many git repos.
- None
- Together with #4279, mostly with the Jenkins plugin.
- For logging-log4net repo, set the Jenkins project name to %REPO_SHORTNAME%
=> Support build integration support for variables 

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/MergeConflictHandler.cs, GitUI/GitUICommands.cs
Fixes #4593
- Fix the excessive rebase command when continue rebase.
- do an interactive rebase, edit one of the commit, and stop in middle
- press the `you are in middle of a rebase` at the bottom right
- make sure it only pops up the continue rebase dialog and no rebase has been performed.
- GIT 2.16
- Windows 10
=> Fix issue that excess rebase command being performed when continue rebase

GitCommands/System.cs, GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/CopyToClipboardMenuHelper.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/StringExtensionTests.cs
- Consolidate all string shortening methods into one (`ShortenTo`)
- Annotate `StringExtensions` and `BoolExtension` methods
- Remove some unused methods
- Unit testing
- GIT 2.16
- Windows 10
=> String extensions

GitExtensions/Program.cs
The JIT must load all types used in a method when the method is loaded.
`Program.Main` attempts to hook type initialisation exceptions via NBug.
Loading fewer types in `Main` increases the chance of catching such exceptions.
Other than that, there is no change to program behaviour.
- GIT 2.16
- Windows 10
=> Defer JIT compile of bulk of Program.Main

GitCommands/Config/ConfigFile.cs, GitCommands/ExternalLinks/ExternalLinksLoader.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/UserControls/RevisionGrid.cs, Plugins/GitFlow/GitFlowForm.cs, Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs, Plugins/Github3/GithubRepo.cs, ResourceManager/GitPluginBase.cs, ResourceManager/Translator.cs, UnitTests/GitUITests/UserControls/AuthorEmailBasedRevisionHighlightingFixture.cs, UnitTests/GitUITests/UserControls/ToolStripClasses/CommitIconProviderTests.cs
`Enumerable.Empty` and `Array.Empty` return singleton instances, so reduce overall allocations.
Also use `new [] { ... }` over `new List<T> { ... }` in a few places, for lesser allocations. The latter allocates an over-sized array (capacity 16) as well as the overhead of `List<T>`.
In a few places I substitute in `IReadOnlyList<T>`. I feel like GE could use this interface more broadly, though understand the interface itself is newer than much of the codebase. I will use it more in future.
- Manual review of straightforward changes. The compiler does the checking here.
=> Use Enumerable.Empty and Array.Empty

GitCommands/Git/GitModule.cs
This method exists in the framework as `Stream.CopyTo`.
https://docs.microsoft.com/en-us/dotnet/api/system.io.stream.copyto?view=netframework-4.7.1
=> Remove GitModule.StreamCopy

GitCommands/Git/GitItem.cs, GitCommands/Git/GitTreeParser.cs, UnitTests/GitCommandsTests/Git/GitTreeParserTests.cs, UnitTests/GitCommandsTests/GitRevisionInfoProviderTests.cs, UnitTests/GitUITests/CommandsDialogs/RevisionFileTreeControllerTests.cs
- Use Regex for clearer and more robust parsing of ls-tree output
- GitItem class uses `int` to store `mode` for reduced allocation
- GitItem no longer parses type string in ctor
- Annotate `IGitItemParser` interface
- Unit tests (added more tests)
- GIT 2.16
- Windows 10
=> Use Regex in GitItemParser

Plugins/GitFlow/GitFlowForm.cs
Fixes #2838
- the branch type parameter for **publish** and **pull** commands on the GitFlow dialog were changed to make them use the currently selected value of the combo box in the "Manage existing branches" section (`cbManageType`, instead of `cbType` ).
- also fixed the incorrect command formatting in pull
- Created a minimal test repository, initialized git flow, created, published, pulled a `hotfix` branch while `feature` was selected in cbType combo box
- GIT 2.16.1
- Windows 10
=> Issue 2838

GitUI/UserControls/RevisionGrid.cs
Fixes #4495.
- Stopped RevisionGrid::CreateTagToolStripMenuItemClick calling RefreshRevisions itself as this will happen when the create tag form is disposed of. Running RefreshRevisions twice loses the last selected revision.
- Made running FormCreateTag instead use DoActionOnRepo, which is now consistent with other forms (e.g. FormCreateBranch) and consistent with how it's run from the main menu.
- created a tag and observed that the selected revision did not change after the create tag dialog was closed.
- observed that the tag was created and appeared in GitExtensions UI.
- ensured that a tag could be created on a different revision by changing the option "Create tag at this revision", yet the …
=> Fix double call to RefreshRevisions after creating a tag. Fixes #4495

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitExtensionsSettingsPage.cs, GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid.cs, ResourceManager/Strings.cs
As #4031 is more or less merged, I suggest this setting is enabled by default
Only affects new installations
- Setting default value for "Show current working directory changes as an artificial commit" to be enabled by default  
- 
=> Activate artificial commits by default #4033

GitExtensions.sln.DotSettings
- Format collection initialisers correctly
- Format 'while' onto new line
- Exclude lower-case "bug" from TODO items (it appears in several places in sentences)
- Spaces around *, / operators
Some of these settings are required to comply with StyleCop.Analysers rules.
This change has no impact on non-ReSharper users
=> Update ReSharper configuration

GitCommands/CommitData.cs, GitCommands/CommitDataManager.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/RevisionGrid.cs, ResourceManager/LocalizationHelpers.cs, UnitTests/GitCommandsTests/CommitDataManagerTest.cs
Review of `CommitData` and `CommitDataManager` classes.
- Introduce `GitModule.IsGitErrorMessage` method for standard detection of error messages in output strings
- Extract common code into helper methods
- Fix git response validation
- Annotate API
- Minor perf and style fixes
- Remove redundant parameter
- Use 'out' over 'ref'
- Reorder members
- Unit testing
- GIT 2.16
- Windows 10
=> Commit data

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, GitUI/HelperDialogs/FormCommitDiff.cs
Difference for initial commit of a file were presented as a diff to the working directory (#4585)
Fixes #4580
Regression from #4313
Non-existing commits are handled with the "revision" null which is mostly handled as a working directory file.
The compare options for working directory files were limited in 2.50. In 2.51 the changes are presented with git-diff if possible and the non-existing parent were incorrectly handled.
Also some async/await changes
Don't indicate "in progress" async actions with WaitCursor.
If needed, the "awaiting" status should be displayed by the control that is awaiting the async action.
This should be done only if the load time is significant.
Cherry-pick of 7f7b26499bce424864ada3c05d15bd9ab6534581 from #4585  with one change: Suppress exception for patch release …
=> Difference for initial commit of a file were presented as a diff to the working directory

GitCommands/Config/ConfigFile.cs, GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs, GitCommands/Git/GitModule.cs, GitCommands/Patch/Patch.cs, GitCommands/Repository/RecentRepoInfo.cs, GitCommands/Repository/Repositories.cs, GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/Editor/FileViewer.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs, Plugins/Statistics/GitStatistics/LineCounter.cs, Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs, Plugins/Statistics/GitStatistics/PieChart/PieChartControl.cs, TranslationApp/FormTranslate.cs, UnitTests/GitUITests/Editor/Diff/LinePrefixHelperFixture.cs
Various linq-related improvements
- Simplify `Where`/`First` style expressions
- Simplify `SelectMany`/`Count` expression (potentially much fewer iterations required)
- Don't use `Count()` if `Count`/`Length` available
- Replace loops with linq expressions
- Careful review
- 
- GIT 2.16
- Windows 10
=> Linq tweaks

GitCommands/AsyncLoader.cs, GitCommands/RevisionGraph.cs, GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs, GitUI/CommandsDialogs/FormAddToGitIgnore.Designer.cs, GitUI/CommandsDialogs/FormAddToGitIgnore.cs, GitUI/CommandsDialogs/FormClone.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/SearchWindow.Designer.cs, GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs, UnitTests/GitCommandsTests/AsyncLoaderTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/Helpers/AsyncLoaderTests.cs, UnitTests/GitCommandsTests/Helpers/SingleThreadTaskScheduler.cs
This PR fixes #4517.
Following #4501 I started looking at the behaviour of `AsyncLoader`
and adding some tests. This flagged up a mismatch between the intention
and behaviour of the class. My longer term goal is to implement a similar class that supports `Func<Task>` for use in #4501.
This PR adds thorough tests to `AsyncLoader`, and fixes the bug around
cancellation during disposal.
It also allows more than one thread to specify `DefaultContinuationTaskScheduler`
via the use of `ThreadLocal`.
Added more documentation as my understanding grew.
Also prevents use-after-dispose via `ObjectDisposedException`.
- GIT 2.16
- Windows 10
=> Test and fix AsyncLoader

GitCommands/Git/GitModule.cs, GitCommands/Git/GitSubmoduleInfo.cs, GitUI/CommandsDialogs/FormCommit.cs, Plugins/GitUIPluginInterfaces/IGitSubmoduleInfo.cs
After a comment by @gerhardol about the performance impact of submodule scanning, I started looking at some of that code. This PR makes a modest step towards improving things in that area.
Easiest to review commit-by-commit, where changes are small, focussed and described. Reviewing the whole is more complex. Making any kind of meaningful change to the code base here via tiny PRs is tough, and slow. Feedback welcomed.
- Reduce the number of times the `.gitmodules` file is read from disk
- Make GitSubmoduleInfo immutable (or more SOLID, for @RussKie)
- Add more documentation around submodules
- Extract some common code
- Remove unused methods
- Unit tests
- Lots of testing via the UI
- Review and cite …
=> Submodule method review

.editorconfig, GitCommands/Git/GitModule.cs, GitCommands/Patch/Patch.cs, GitCommands/Patch/PatchManager.cs, GitCommands/Patch/PatchProcessor.cs, GitCommands/Utils/EncodingHelper.cs, GitExtUtils/Linq/LinqExtensions.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormViewPatch.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, UnitTests/GitCommandsTests/Patch/PatchManagerTest.cs, UnitTests/GitCommandsTests/Patch/PatchTest.cs
This PR contains the first third of the commits from my `patches` branch, which ultimately makes `Patch` immutable, `PatchProcessor`/`PatchManager` stateless, and reduces the amount of string manipulation in the handling of patches.
I've squashed some of the commits and can squash more. Right now it's pretty easy to follow each commit. The first 7 commits are all related to patch unit tests and could be squashed.
- Make `PatchManager` stateless
- Remove unused code (~300 LOC)
- Fix conflict between type and namespace names
- Miscellaneous tidying and admin
- Unit tests
- GIT 2.16
- Windows 10
=> Patches 1/3

GitUI/UserControls/FileStatusList.cs
Fixes #4683
Regression from #4562
- Type in the filter
- focus outside the combo box
- Verify that the label does not cover the text
- Windows 10
=> "Filter files..." label was visible when combobox lost Focus

appveyor.yml
Excludes a few third-party libraries from code coverage that are producing noise during the CI build due to missing source files.
=> Exclude FluentAssertions and SmartFormat assemblies from code coverage

GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Fixes https://github.com/gitextensions/gitextensions/issues/4683#issuecomment-375118791
- Hide watermark label when clicked on it.
- Focus FilterComboBox.
- Tested manually.
- Windows 10
=> Hide watermark label when clicked on it.

GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
Prevents the background thread from starting when launched in the designer.
=> Fix Visual Studio crash when opening FormBrowse in the designer

GitUI/GitUIExtensions.cs, GitUI/Plugin/LoadPlugins.cs
- Replace two instance of tail-call recursion with iteration
- Manual review and testing
- GIT 2.16
- Windows 10
=> Replace tail call recursion with loop

GitCommands/Git/GitModule.cs, GitCommands/Remote/GitRemoteManager.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs
- Merge overloads via default parameter value
- Ask question about utility of parameter at all
- GIT 2.16
- Windows 10
=> Get remotes

GitCommands/Git/GitModule.cs, GitCommands/Git/GitStash.cs, GitUI/CommandsDialogs/FormStash.cs, UnitTests/GitCommandsTests/Git/GitStashTests.cs
- `GitStash` has fewer fields
- Parsing is more robust, via regex
- Add more test cases
- Added tests
- GIT 2.16
- Windows 10
=> Make GitStash immutable and use regex parsing

GitCommands/Git/GitModule.cs
- Document what's going on.
- Do fewer string allocations.
- GIT 2.16
- Windows 10
=> Review GitModule.GetSelectedBranchFast

UnitTests/GitCommandsTests/AsyncLoaderTests.cs
Just documenting the existing behavior because it surprised me.
=> AsyncLoader does not fault the task if no error handler is installed.

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RevisionDiff.cs
Fixes the missing word observed in #4691.
QUESTION: Does the translation system rely on this string? Does this change require something more for translation to continue to work? I took a look through the code and decided it didn't, but it'd be good to confirm.
=> Add missing word to dialog text (#4691)

GitExtSshAskPass/SshAskPass.vcxproj, GitExtensionsShellEx/GitExtensionsShellEx.vcxproj
GitExtensions uses .NET 4.6.1, which doesn't support Windows XP. This change removes the requirement that the special XP-supporting compiler features are installed to build GitExtensions.
=> Build native projects using the default platform toolset

GitUI/CommandsDialogs/FormApplyPatch.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormLog.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormRebase.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/FormSettings.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs, GitUI/GitUI.csproj, GitUI/GitUICommands.cs, GitUI/WaitCursorScope.cs, TranslationApp/Program.cs
`WaitCursorScope` allows setting the current mouse cursor as 'busy' within a given scope, and having it automatically restore at the end of that scope.
```c#
using (new WaitCursorScope())
{
// ...
}
```
- Nests properly. If one scope exists within another, exiting the enclosed scope doesn't reset the cursor back to 'normal'. Exiting a scope restores the cursor to whatever it was when the scope was entered. A nested scope sets the wait cursor on both entry and exit, which makes sense as the outer scope is 'busy' throughout.
- Exception safe. No matter what happens within the `using` block, the (global, singleton) cursor will be restored properly.
- Refactor safe. No need to be mindful of two unrelated commands located potentially some distance apart. Introducing a return within the block …
=> Introduce WaitCursorScope

UnitTests/CommonTestUtils/CommonTestUtils.csproj, UnitTests/CommonTestUtils/packages.config, UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs, UnitTests/GitCommandsTests/ExternalLinks/ConfiguredLinkDefinitionsProviderTests.cs, UnitTests/GitCommandsTests/FullPathResolverTests.cs, UnitTests/GitCommandsTests/Git/GitBranchNameOptionsTest.cs, UnitTests/GitCommandsTests/Git/GitDirectoryResolverTests.cs, UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs, UnitTests/GitCommandsTests/Git/LongShaProviderTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/GitRevisionInfoProviderTests.cs, UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs, UnitTests/GitCommandsTests/packages.config, UnitTests/GitUITests/FindFilePredicateProviderTest.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/packages.config, UnitTests/GravatarTests/DirectoryImageCacheTests.cs, UnitTests/GravatarTests/GravatarTests.csproj, UnitTests/GravatarTests/packages.config, UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj, UnitTests/Plugins/ReleaseNotesGeneratorTests/packages.config, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataBodyRendererTests.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs, UnitTests/ResourceManagerTests/ResourceManagerTests.csproj, UnitTests/ResourceManagerTests/packages.config
Relates to #4426.
This PR updates NuGet packages used in unit test projects only.
- NUnit 3.9.0 -> 3.10.1
- FluentAssertions 4.19.3 -> 5.2.0
- NSubstitute 2.0.3 -> 3.1.0
`ShouldThrow` and `ShouldNotThrow` were removed. They are replaced by `Should().Throw` and `Should().NotThrow` respectively.
- Verified tests still passed
=> Update unit test packages

Setup/MakePortableArchive.cmd
=> Include Microsoft.VisualStudio.Threading.dll in portable archive.

GitUI/DpiUtil.cs, GitUI/GitExtensionsForm.cs, GitUI/GitUI.csproj, GitUI/UserControls/GravatarControl.cs, ResourceManager/GitExtensionsUserControl.cs
Relates to #4099.
- Introduce `DpiUtil` for DPI related operations
- Update `GraavatarControl` to scale such that it looks correct at high DPI (see screenshot)
- Lots of testing
- Code defensively, so any issue obtaining the DPI setting falls back to the old behaviour
- GIT 2.16
- Windows 10
=> Fix avatar under high DPI

GitCommands/AsyncLoader.cs, GitExtUtils/GitUI/ControlThreadingExtensions.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/FilterBranchHelper.cs
The two-argument form of `DoAsync<T>` didn't seem to provide substantial advantages over JTF. This pull request converts the few uses to a more direct JTF approach and requires `DoAsync<T>` users pass the third argument.
=> Remove the two-argument form of AsyncLoader.DoAsync<T>

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormPull.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
Fixes #4754
Should be a similar problem for other situations where the command is used to
This also fixes a problem that would occur if a user have set config option status.submoduleSummary, the output would not be the desired
The default for git-status is --ignore-submodules=none so using this as default is not a change for other commands
- Set git command default as default option
- See issue
- Test case for default of --ignore-submodules=none
- Windows 10
=> Set git-status default to --ignore-submodules=none

GitCommands/CommitDataManager.cs
commitId may be a branch or tag name but the output from git-log will contain only the commit's sha1, thus it cannot verify that it found the commit simply by checking for the commitId.
Fixes #4745.
- When finding a commit using CommitDataManager.TryGetCommit, cease checking if git-log output contains commitId
The code in v2.51.01 attempted to make the same check but was failing, thus letting it use the output from ``git log`` even though the original commitId was not found in the output. 
By removing the check from the post-2.51 code, I have restored the original functionality with no loss in protection from invalid data returned from ``git log``.
- Tested manually clicking on branch and tag links …
=> Cease checking if git-log output contains commitId - fixes #4745

GitExtensions/GitExtensions.csproj, GitExtensions/Program.cs
Resolves #4739
- Show dashboard also when starting with debugger
(see issue for a longer explanation)
- Start with/without setting 
- Test vsix plugin
- Test shell extension - browse
- Windows 10
=> Start with dashboard also if started from valid Git repo

GitCommands/Git/GitDeleteBranchCmd.cs, GitCommands/Git/GitModule.cs, GitCommands/Repository/RecentRepoInfo.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs, GitUI/UserControls/BlameControl.cs
Fixes #4698.
- Fix duplicate entry in commit message drop down list
- Fix truncation of commit message drop down labels
- Fix position of separator in commit templates drop down list
- Remove margin from these two drop down lists
- Misc tidying
- Lots of manual testing and code review
- GIT 2.16
- Windows 10
=> Fix commit drop downs (#4698)

GitUI/CommandsDialogs/BrowseDialog/FormCommitCount.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormCommitCount.cs
Wanted to make a simple conversion using the new VS Threading stuff. It's nothing too exciting, but was satisfying to see how straightforward such a change was.
I actually did this a while back and it was the precursor to the ideas in #4735. 
- Query statistics and compose text on a background thread
- Optimise string composition (many fewer allocations)
- Lots of manual testing
- GIT 2.16
- Windows 10
=> FormCommitCount doesn't block UI thread

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitPushAction.cs, GitCommands/Git/GitRef.cs, GitCommands/Git/GitRefName.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/UserControls/RevisionGrid.cs, Plugins/Gerrit/FormGerritPublish.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommandsTests/Git/GitRefNameTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/GitModuleTest.cs
- Add faster overload of `GetRemoteName` (used O(N) from `GitModule.GetTreeRefs`) which avoids additional git process execution to obtain remote names (`git remote show`)
- Add tests for `GitModule.GetTreeRefs`
- Use regex in `GitModule.GetTreeRefs` and reduce allocations
- Make `GitRef.Name` immutable
- Create `RefName` class for all utilities relating to ref names (i.e. `refs/remotes/origin/master` etc), moving several existing methods/constants to it, and adding unit tests
- Added unit tests to modified code
- GIT 2.16
- Windows 10
=> Parsing improvements

GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.Designer.cs
Relates to #4099
150% scaling (before / after)
- run it manually at various scaling
- Windows 10
- 34" 4K monitor
=> fix: FormFixHome is messed up HiDPI

GitUI/CommandsDialogs/FormRemotes.cs
Relates to #4099
100% scaling
150% scaling
- run it manually at various scaling
- Windows 10
- 34" 4K monitor
=> fix: FormRemotes is messed up on HiDPI

UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs, UnitTests/GitUITests/ThreadHelperTests.cs
* Make sure `ThreadHelper.JoinableTaskFactory` is usable in tests not marked with `STA`, provided `SwitchToMainThreadAsync` is not used
* Make sure thread exceptions (e.g. from `FileAndForget`) cause tests to fail
:memo: This pull request is the first two commits originally from #4757, but was updated to avoid the need to use `IDisposable` or `SemaphoreSlim`.
=> JTF testing update

GitUI/CommandsDialogs/FormFileHistory.cs
Following generalization of use of IFullPathResolver, the separator used in the
File History form ends up as the native one, while it should be the posix '/'
for later git commands to work properly (via right-click command for instance).
=> Fix separator in file name within File History form

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormFileHistory.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes #4793.
- Fix cause of bug in 4793
- As bug was null-related, annotate some methods in this area
- Replace custom tuple type with `ValueTuple`
The bug was caused when we modified `UnescapeOctalCodePoints` to promote `null` to `""`. This caused a loop in `FormFileHistory` to never terminate:
```c#
string line;
do
{
line = p.StandardOutput.ReadLine();
line = GitModule.ReEncodeFileNameFromLossless(line); // null converted to ""
// ...
}
while (line != null); // this condition never met
```
That loop was being run via `AsyncLoader` in the background, which is why the UI remained responsive, however we would have had one core pinned at 100%.
- GIT 2.16
- Windows 10
=> Fix for blank file history

GitUI/CommandsDialogs/FormViewPatch.Designer.cs, GitUI/CommandsDialogs/FormViewPatch.cs
- Fixes a binding issue in `FormViewPatch` where `DataPropertyName` ended up with an incorrect string after a refactor
- Use `nameof(...)` to prevent this happening again
=> Fix bug in FormViewPatch

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs, GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs, GitUI/GitUICommands.cs, Plugins/Gerrit/FormGerritDownload.cs, Plugins/Gerrit/Gerrit.csproj, Plugins/Gerrit/GerritPlugin.cs, Plugins/Gerrit/GerritUtil.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs, Plugins/GitUIPluginInterfaces/IGitUICommands.cs
This pull request incrementally changes GitCommands methods to use JTF. In each iteration, a "primary" method was selected for conversion, and then additional methods were selected when a caller was not used in a large number of places.
* `GitModule.RunCmd`
* ~~`GitModule.RunBash`~~ (removed from this PR)
* ~~`SynchronizedProcessReader`~~ (removed from this PR)
* ~~`GitModule.RunCacheableCmdAsync`~~ (removed from this PR)
:memo: The rule in #4751 was established early in this work, and should be followed at each step.
=> [WIP] Make a few GitCommands methods asynchronous

GitUI/BuildServerIntegration/BuildServerWatcher.cs, GitUI/UserControls/RevisionGrid.cs, Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerWatcher.cs
- Move most of the LaunchBuildServerInfoFetchOperation logic to the background
- Use CancellationTokenSequence to cancel previously scheduled LaunchBuildServerInfoFetchOperationAsync
- Manual tests with AppVeyor and Jenkins plugins.
=> Make LaunchBuildServerInfoFetchOperation async

GitUI/CommandsDialogs/FormDiff.cs
- Show what commit git has chosen as a merge base.
Before
After
- GIT 2.15
- Windows 10
=> Show the computed merge base commit sha.

README.md
This PR adds the SVG logo at the top of the README. The SVG version will be crisp on high-DPI displays.
Should be merged after #4785 to work in Firefox/Chrome/Edge (and possibly other browsers).
Once that is merged you can see the result at:
https://github.com/drewnoakes/gitextensions/blob/add-logo-to-readme/README.md
Note that the https://cdn.rawgit.com host may cache the old, broken SVG for a while so it might not be possible to review the change visually until the cache expires.
Unfortunately GitHub uses the wrong MIME type when serving raw SVG files, so we have to go via the CDN. I've done this on several projects before without issue.
- See above
=> Add SVG logo to README

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, GitExtensions.sln
Following the discussion in #4783...
The [current CONTRIBUTING.md](https://github.com/gitextensions/gitextensions/blob/master/CONTRIBUTING.md) file doesn't directly tell contributors what's required of them. I typed out some notes that I think should make that a bit clearer. My goal is to be inclusive and welcoming, yet to lay out the ground rules and set appropriate expectations.
The wiki also has some contributor guidelines which overlap with the below. It's the norm on GitHub at least for contributor guidelines to go in `CONTRIBUTING.md`, which is linked to in a banner for first-time contributors.
It also turns out that GitHub flavoured markdown allows HTML-style comments, so we can put the notes reminding issue creators to search for existing issues there.
I moved the information …
=> Provide more information to contributors

GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/GitUICommands.cs, GitUI/GitUIExtensions.cs, GitUI/UserControls/RevisionGrid.cs
- Manual tests. 
- GIT 2.15
- Windows 10
=> Show FormDiff modeless.

GitExtensions.sln, codecov.yml
Fixes #4802.
- Ignore some patterns from test coverage
- ~~`UnitTests/*`~~
- ~~`Externals/*`~~
- `*.Designer.cs`
- Make PR comments from codecov bot much shorter on screen/email
- ~~Don't comment at all if coverage is unchanged (eg. changes to non-source files)~~
- Fix the solution reference to `codecov.yml`
- I don't know how to test these without committing them to master. It's possible that these changes will flag a need for further changes. I did read their documentation thoroughly and believe the changes will achieve the goals I had.
---
I find the comments from the bot way too long. They separate the PR's description from its discussion. The key info is whether coverage went up or down, and by …
=> Coverage tweaks

codecov.yml
This exclusion is aleady covered during coverage collection via an argument to OpenCover.
Implements the change requested in https://github.com/gitextensions/gitextensions/pull/4803#discussion_r180220633.
=> Remove duplicate exclusion from codecov.yml

GitUI/BranchTreePanel/RepoObjectsTree.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/CommandsDialogs/SearchControl.cs, GitUI/CommandsDialogs/SearchWindow.cs, GitUI/GitUICommands.cs
- SearchControl  consumes only the first 20 elements.
There is no need to apply search predicate to the all elements.
- GIT 2.15
- Windows 10
=> Back SearchControl with IEnumerable instead of IList.

GitCommands/Remote/GitRemoteManager.cs, GitCommands/StringExtensions.cs, UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs, UnitTests/GitCommandsTests/StringExtensionTests.cs
Fixes #4453 .
It came to my attention that after the commit:
[Fixed "automatically configure the default push..." feature when adding remote](https://github.com/gitextensions/gitextensions/commit/4cb98fe33467426212d2616e62f2cfc5223a00cf)
it broke the use of the double loop that existed by changing the Line:95
//  From
localHead.MergeWith = remoteHead.Name;
//  To
localHead.MergeWith = localHead.Name;
So could someone validate that this is the correct behavior?
Also there is no Unit Test for this function.  
Should we create  Unit Test for this ?
- Refactored `GitRemoteManager.ConfigureRemotes` to use only one  loop
- Run all unit tests
- Run the app and check the affected part. …
=> Issue 4453

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs
Fixes #4828.
- Collect filter candidates on demand. All the data is already loaded into the memory, collecting it from the tree nodes is fast enough to not precompute them at ROT reloading.
- GIT 2.15
- Windows 10
=> Compute filter candidates on demand.

GitUI/BranchTreePanel/RepoObjectsTree.cs
- Await for all the fired tasks to propagate errors and let the caller await for ROT reload completion.
@sharwell A candidate for analyzers?
=> Await tasks in order to propagate errors to the caller.

CONTRIBUTING.md
- fix "bugs" link in CONTRIBUTING.md to point to the correct label
- before: 
- after: 
- manual verification
- n/a
=> fix "bugs" link in CONTRIBUTING.md

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormPush.cs, GitUI/WaitCursorScope.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
To reproduce this bug, ensure you have this option checked:
- Fixes a regression in the parsing of ref lists. `GitModule.GetTreeRefs` expects the column separator to be a space. `git ls-remote` uses tab separators. This change expands the parsing regex to accept space or tab. This works in 2.51.01, so it's a regression and I probably caused it during a conversion to regex.
- Add another use of `WaitCursorScope` with alternative cursor (`Cursors.AppStarting`)
- Nest some private functions with only one using method
- Lists of refs were referred to as trees, but a git tree is something different. Rename a few things.
- Refactor `LoadMultiBranchViewData`
I tried squashing the nested function commits and they all conflict with intermediary changes.
- GIT …
=> Bug in push multiple refs

GitUI/BranchTreePanel/RepoObjectsTree.cs
Fixes icon sizes in `RepoObjectsTree` on high DPI displays.
- Windows 10
- Scaling 200%
=> Fix RepoObjectsTree icon sizes at high DPI

GitUI/CommandsDialogs/FormBrowse.cs
It appears at times Module.WorkingDir path is an empty string, which
tripped AE in Locals.AddAsMostRecentAsync.
All other uses of the API are verified to have guards in place.
Fixes #4874
- run unit tests
- run manually
- checked all other call sites to verify there are checks and guards from similar issues re-occurring.
=> fix: Randomly crash adding local as most recent

GitCommands/Git/GitDescribeProvider.cs, GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, GitCommands/Settings/AppSettings.cs, GitUI/CommitInfo/CommitInfo.Designer.cs, GitUI/CommitInfo/CommitInfo.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs, UnitTests/GitCommandsTests/Git/GitDescribeProviderTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj
Implements feature request #84
- Show the output of "git describe --tags --first-parent" in the commit pane as per issue #84. 
git describe returns the first tag found in the history of the specified commit and also displays the number of commits since that tag and a shortened sha1 of the specified commit.
I have re-formatted the output text from the raw git output.
I chose to use the --tags option to show both annotated and lightweight tags.
I chose to use the --first-parent option because to me it seemed more useful to show the last tag on the first parent line rather than other merge parents.
Note the last line of the commit info now shows "Derives from tag: v2.51 + 211 commits".
What did I do to …
=> Add git describe info to commit header - #84

GitUI/CommandsDialogs/FormVerify.Designer.cs, GitUI/CommandsDialogs/FormVerify.LostObject.cs, GitUI/CommandsDialogs/FormVerify.cs
- Display creation time of the blob objects and not only commit objects as it is done at the moment (taken from file creation time) to give a good clue to the user
- Open the viewer on press on 'Enter' (to let the user use its beloved keyboard for easy navigation)
- Better initial sizing of "Hash" column (because that's a lot easier to reduce the last column than enlarge it!)
- Disable creation tag and branch for not "Commit" objects in contextual menu (because that's not possible and we have an error message if we try to do it...)
- Display objects sorted by date (because a sort is better than none...)
- Add context menu item to be able to easily copy the hash
- manual test
- GIT …
=> Improve FormVerify (Recover lost objects form)

GitUI/CommandsDialogs/FormVerify.Designer.cs, GitUI/CommandsDialogs/FormVerify.LostObject.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/CommandsDialogs/FormVerify.resx, GitUI/GitModuleControl.cs, GitUI/HelperDialogs/FormEdit.cs
* Display also hash(s) of parent commit(s)
* Add checkbox to display only other objects than commits
* Content in the View form should be displayed in readonly (to not be able to edit)
* Fix: prevent displaying bad object (the one of the next line :( ) when pressing 'Enter' key
* fix exception when trying to copy a text when viewing a dangling object
* Handle display of tags with its data
* Display tags in the same time than commits (make more sense)
* Hide columns that has no sense when displaying only blobs
* Restore annotated tags with a name similar to the original one
* Add a "Save as..." action in blob contextual menu
Screenshot of some improvments:
=> Some other improvements/fixs in formverify (Recover lost objects form)

UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Fixes #4854 
- fix compile error in FormCommitTests.cs because afc7fa0984068d617b3e95dcb3c0fa5e57392e40 removed the parameterless overload of StartCommitDialog
- build
- n/a
=> fix compile error in FormCommitTests.cs

GitUI/CommandsDialogs/FormClone.cs
When launched from Windows explorer, the clone destination was set to the parent of the current folder. If the folder was at the root of the drive, the destination would be blank.
The fix sets the parent of the current directory unless the current directory is the root, or the current directory is not a git repository.
Fixes #4855
=> fix: Init wrong folder

GitUI/GitExtensionsForm.cs
Forms get resized by .NET runtime automatically.
Because most of forms track own size, manual resize doubled up and caused the form grow overtime.
Fixes #3828
- opened FormCleanupRepository multiple time to ensure its dimensions remained constant
- opened numerous other forms to ensure no unexpected resizes (NB: not exhaustive check)
- Windows 10
- 34" with 200% scaling
=> fix: Clean working directory constant grow

ResourceManager/TranslationString.cs
Fixes #4922 
- restore TranslationString.Text property setter which was lost in a code cleanup (see commit ed2ae7bdcfa09029a4ce75166f65371c201a3f2c)
- add a comment that may help future code reviews not to remove it again
- before 
- after 
- manual verification
- GIT 2.16.1
- Windows 8.1
=> Fix broken TranslationString [3.0 branch]

GitCommands/UserRepositoryHistory/Legacy/RepositoryHistoryMigrator.cs, GitCommands/UserRepositoryHistory/LocalRepositoryManager.cs, UnitTests/GitCommandsTests/UserRepositoryHistory/Legacy/RepositoryHistoryMigratorTests.cs, UnitTests/GitCommandsTests/UserRepositoryHistory/LocalRepositoryManagerTests.cs
In some scenarios, if the app crashes before the migrated legacy settings have been persisted, the categorised repositories would not be available to the user on following runs.
To address this, persist the migrated settings immediately after the migration.
Follow up on #4899
=> Persist migrated user's repository settings

UnitTests/GitCommandsTests/UserRepositoryHistory/LocalRepositoryManagerTests.cs
`AddAsMostRecentAsync_should_add_new_path_as_top_entry` could have failed if user has configured `AppSettings.RecentRepositoriesHistorySize` to be less than 5.
=> fix AddAsMostRecentAsync_should_add_new_path_as_top_entry tests

GitCommands/Git/GitModule.cs
Fixes #4392 (same as #4927, but for v2.51)
- added `-c diff.noprefix=false` to the standard git diff args (this was the simplest solution, supported from git v1.7.2)
- there was a [comment](https://github.com/gitextensions/gitextensions/issues/4392#issuecomment-362044980) below the original issue, but I think that this simple solution is enough, and is not a big risk for the future yet
- before 
- after 
- 
- manual verification 
- GIT 2.16.1
- Windows 8.1
=> fix Git config diff.noprefix true option breaks most of GitExtensions functionality [2.51 branch]

GitCommands/Git/GitModule.cs
Fixes #4392 
- added `-c diff.noprefix=false` to the standard git diff args (this was the simplest solution, supported from git v1.7.2)
- there was a [comment](https://github.com/gitextensions/gitextensions/issues/4392#issuecomment-362044980) below the original issue, but I think that this simple solution is enough, and is not a big risk for the future yet
- before 
- after 
- 
- manual verification 
- GIT 2.16.1
- Windows 8.1
=> fix Git config diff.noprefix true option breaks most of GitExtensions functionality

GitUI/CommandsDialogs/FormClone.Designer.cs, GitUI/CommandsDialogs/FormClone.cs
Fixes to #4776 
- before
- after 
Win10 scale 100%
Win10 scale 150%
- manual runs in 100% and 150% scaling
=> fix: FormClone is messed up in HiDPI

GitUI/UserControls/CommitPickerSmallControl.Designer.cs, GitUI/UserControls/CommitPickerSmallControl.resx
The controls messes layout any form that host it, e.g. `FormCreateBranch` or `FormCreateTag`.
Fixes to #4862
- before
- after 
Win10 scale 100%
Win10 scale 200%
- manual runs in 100% and 200% scaling
=> fix: CommitPickerSmallControl is messed up in HiDPI

GitUI/FilterRevisionsHelper.cs
- Fix filter commit label which was displayed  like "Commit..." instead of "Commit" because the transation was the one of the "commands" menu due to the same control name (a real problem in french translation for example).
- Use of a much detailed label to better tell what the filter do (I, myself, never know that the filter was also used to search in sha1)
- before:
- after:
=> Fix filter commit label

GitCommands/Git/GitVersion.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs, GitUI/Translation/English.xlf
Part of #4515
- Raise (officially) supported version from 1.7.0 to 2.9.0. (There is no big reason to set 2.9, could be newer version). Support for older versions have not been removed, it is just that older versions are listed as red in settings.
- Set recommended Git version to 2.16.3 (latest is 2.17.0, could use that instead). Open to other colors...
- Change download link to GE wiki instead of "msysgit" (Git for Windows).
- (patched code to set the future version 2.18.3 as minimal version)
- Manual tests
- GIT 2.17.0
- Windows 10
=> Check for recommended Git version

GitExtensionsVSIX/GitExtensionsPackage.cs, GitExtensionsVSIX/GitExtensionsVSIX.csproj
* Update to the VS SDK from NuGet
* Add `[ProvideBindingPath]` so Visual Studio can always load **GitPluginShared**
:memo: This is a safe subset of the changes in #4747
=> Updated VSIX build

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/HelperDialogs/FormEdit.cs
Fixes #4937 - part 2 of 3
- modify `FormEdit` to accept `GitUICommands` in its constructor (it requires the git module because it applies autocrlf setting to the copied text fragment)
- note: commit a2e1251477d8faa04b5ec1c27a2ca606a3ea8013 added a workaround for this bug in `SearchForUICommandsSource`, this PR is an independent fix for the form which makes it possible to work correctly without the workaround so that the workaround can be safely removed
- before 
- after: no exception window
- open Repository->Git maintenance->Recover lost objects..., right click a row in the table, click View, select and copy a part of the text …
=> fix missing UI command source in FormEdit

GitExtensionsVSIX/GitExtensionsVSIX.csproj
Fixes #4458
- Removed and re-added the reference to VisualStudio.CommandBars and found that this fixed the build error that was seen previously by @RussKie in #4458 and still seen by me. More specifically in my references I chose the item "Microsoft Visual Studio Command Bars 8.0". There was no other version appearing in my list.
- Has NOT been tested.
Currently I do not have a full build of Setup but this fixed the build error with CommandBars. 
I've created this pull request for maintainers and others to decide if this is a valid change to make.
=> Change VisualStudio.CommandBars ref to compile in VS2017 Community

GitUI/CommandsDialogs/FormCommit.cs
Fixes #4907 (same as #4934, but for v2.51)
- bypass the form activated event handler for Reset all changes/Reset unstaged changes buttons in the Commit dialog
- Commit and Commit & push buttons do the same to avoid reloading
- (could not produce a reasonable screenshot)
- manual verification
- GIT 2.16.1
- Windows 8.1
=> fix "Reset all changes" not working when "Refresh dialog on form focus" true [2.51 branch]

GitUI/GitModuleControl.cs
This reverts commit a2e1251477d8faa04b5ec1c27a2ca606a3ea8013.
Fixes #4937 - part 3 of 3
- commit a2e1251477d8faa04b5ec1c27a2ca606a3ea8013 added a workaround in `SearchForUICommandsSource` for a bug where an exception happened in the "Recover lost objects" dialog when copying text from a file in the viewer
- the reverted change change caused Visual Studio to become unresponsive when opening the form designer
- after PR #4940 this workaround is no longer necessary
- before 
- after 
- form designer: find `RevisionGpgInfo.cs`, then open it in form designer in VS
- exception on copying text: open Repository->Git maintenance->Recover lost objects..., right …
=> fix Visual Studio form designer - revert previous workaround in SearchForUICommandsSource

GitUI/GitModuleControl.cs
Fixes #4937 - part 1 of 3
- make `GitModuleControl` non-abstract again
- before 
- after 
- open form designer in VS
- Windows 8.1
- Visual Studio 15.7
=> fix Visual Studio form designer - GitModuleControl must not be abstract

GitUI/CommandsDialogs/FormBrowse.cs
Whenever the app is closed, an empty repository is opened which causes the dashboard to be shown before the app is finally closed.
This creates an unwelcome flickering.
The original code was introduced in 466deca55dc22c7f70f6510894721cc76738bf3d citing that plugins must be given a chance to unload before the app closes.
Replace the existing flow that opens an empty repository with a call to unregister plugins, that essentially should cause them to unload.
@PombeirP do you have any recollection of the original issue?
=> fix: Dahsboard is shown when app is closed

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RevisionFileTree.cs
Closes #4955
Diff tab was lost if Commit info was shown in RevisionTree
The DiffTab is lost when inserted to the left.
This is related to the Dashboard changes that seem to restructure loading, the handle to the tabcontrol must be created to inserting:
https://social.msdn.microsoft.com/Forums/windows/en-US/5d10fd0c-1aa6-4092-922e-1fd7af979663/tabpagesinsert-bug?forum=winforms
- No tab lost
- Manual
- Windows 10
=> Browse Diff lost: Handle must be created prior to insertion

GitUI/UserControls/RevisionGrid.cs
Fixes #4963
- Use the same color for artificial refs as the one used for stash ref
Before:
After:
=> Change artificial refs color to "Color other label" setting

GitExtensions/Program.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUICommands.cs
This is an update of #4870 See that PR for original motivation and why this is opened as a separate PR.
Fixes #4860 
The first commit tried to always resolve the current working directory when starting GE.
That broke the Dashboard handling, that was set to start if there were no directory supplied and GE was configured to not use last used repo. The dashboard must be explicitly handled for the change to work.
- Manual tests
- Windows 10
=> Handle start with dashboard explicitly

GitCommands/Git/GitModule.cs, GitExtensions/Program.cs, GitUI/GitUICommands.cs
(This PR created as [requested in #4809](https://github.com/gitextensions/gitextensions/pull/4809#discussion_r180905799))
When running commands from the command line, and if no working directory argument is passed, use the `Environment.CurrentDirectory` to find a valid git working directory, if possible.
This is important for #4809 where we need values from the config file. Without this change, the editor does cannot read config and therefore does not know git's `core.commentChar` value.
@RussKie pointed out that this change seems to be related to #4740 and asked for it to be pulled out to its own PR. Let's work out what is required here and document it in the code to prevent future flip-flops.
- GIT …
=> Add current working dir as fallback for GitModule

GitCommands/CommitData.cs, GitCommands/System.cs
Some users to the west of GM experience AOORE when navigating to the artificial commits.
Artificial commits are constructed using `DateTime.MaxValue`, and for users with timezones to the west of GM the MaxValue falls outside `DateTimeOffset.MaxValue`.
The `DateTimeOffset` constructor first converts any `DateTime` that is not of Kind 'UTC' to the equivalent UTC time. It will then check whether the UTC-equivalent DateTime falls outside of the bounds of `DateTimeOffset.MinValue` and `DateTimeOffset.MaxValue`, and if it does, will throw an
`ArgumentOutOfRangeException`.
Fixes #4956
=> fix: Crash when you click on the Commit tab

GitUI/CommandsDialogs/FormSettings.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.resx
* Render the treeview consistently with the other treeviews
* Align the search textbox with the treeview
Fixes #4949
before:
after:
- manual tests at 250%
=> Fix 4949 settings rendering tweaks

Bin/gitext.sh
Fixes #4975 
- Add shell start script's directory to start GitExtensions with absolute path
- Uses well-known bash snippet from https://stackoverflow.com/q/59895/
- Ubuntu 16.04 LTS
=> Fix gitext.sh if ran from different directory

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormLog.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/RevisionDiff.Designer.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionFileTree.Designer.cs, GitUI/CommandsDialogs/RevisionFileTree.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/IFileViewer.cs, GitUI/GitUIExtensions.cs, GitUI/Hotkey/HotkeySettingsManager.cs, GitUI/UserControls/CommitDiff.cs
Fixes #4500: F3 should open the external diff viewer instead of showing "No string specified to look for!"
- added getter for FileViewer's FindAndReplaceForm.LookFor
- added Action FileViewerInternal._openWithDifftool to be invoked on F3 when LookFor is not set
- adapted all sources of diffs to be displayed in FileViewer with/without such an action
- KeyPreview = true in forms to react on F3, too, when the diff is visible but not focused
- affects only keypress handling
- hit F3 with different focused controls in FormCommit, FormBrowse, File History with & without search text
- reviewed changes multiple times before committing …
=> F3 opens the external diff viewer unless searching text.

GitCommands/CommitDataManager.cs, GitCommands/Git/GitRevision.cs, GitExtUtils/GitUI/ThreadHelper.cs, GitExtUtils/Linq/LinqExtensions.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormFormatPatch.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.Graph.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.Junction.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs
This PR contains small commits I've cherry-picked out of another PR related to revision loading performance. Probably easiest to review commit-by-commit as the overall diff is a tad confusing in places.
- Several small screws tightened, such as:
- Reduce allocations
- Remove unused code
- Use `IReadOnlyList<T>`
- Reduce visibilities
- Add left/right padding to the graph UI (see screenshots below)
The only visual change is the padding around the graph. Notice how the 'margin' on the left/right matches that at the top afterwards.
- Lots of manual testing
I'd prefer this not to be squashed, as any problems will be easier to identify via bisect with small commits.
- GIT 2.16.02
- …
=> DVCS Graph tweaks

GitCommands/Git/GitDirectoryResolver.cs, GitUI/CommandsDialogs/FormEditor.cs, GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs, GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs, GitUI/Editor/CommitMessageHighlightingStrategy.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/GitHighlightingStrategyBase.cs, GitUI/Editor/IFileViewer.cs, GitUI/Editor/RebaseTodoHighlightingStrategy.cs, GitUI/GitModuleForm.cs, GitUI/GitUI.csproj, GitUI/GitUICommands.cs, ResourceManager/GitExtensionsFormBase.cs
Closes #3516
- Add editor syntax highlighting for commit messages
- Summary line bold
- Summary line beyond 50 characters is flagged
- Non-blank line after summary is flagged
- Description lines beyond 72 characters are flagged
- Comments are highlighted
- Add editor syntax highlighting for (interactive) rebase todo
- Commands are bold, and coloured
- Comments are highlighted
- Lots of manual testing
- Review feedback on @azarkevich's work on #3516 and address or avoid many concerns
Specific differences to #3516:
- Add support for commit messages
- Add support for `core.commentChar` setting
- Avoid need to modify argument processing (the file name indicates the highlight type needed)
- Avoid scanning …
=> Editor syntax highlighting for commit and interactive rebase

GitUI/UserControls/FileStatusList.cs
=> Recheck filter against displayed file name when working in the fileNameOnlyMode mode.

GitUI/CommandsDialogs/FormBrowse.cs
Fix for a alleged regression in Windows 10.0.16299 (1709):
```
"The process cannot access the file 'C:\Users\[me]\AppData\Roaming\GitExtensions\GitExtensions\Recent\[my repository].gitext' because it is  being used by another process."
```
Fixes #4549
=> fix: Crash on opening repository in Recent list

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUI.csproj, GitUI/WindowsJumpListManager.cs, GitUI/WindowsThumbnailToolbarButton.cs, GitUI/WindowsThumbnailToolbarButtons.cs
Fix for a alleged regression in Windows 10.0.16299 (1709):
"The process cannot access the file 'C:\Users\[me]\AppData\Roaming\GitExtensions\GitExtensions\Recent\[my repository].gitext' because it is  being used by another process."
Fixes #4549
-  Fix the bug by adding trapping `IOException`
- Move the code related to Windows jumplists and thumbnail toolbars out of `FormBrowse` into own set of classes. The underlying functionality remains for the most part the same.
For the ease of use added an abstraction that represents a thumbnail toolbar button; and a class that aggregate all available buttons.
- manual
- Windows 8.1 and 10
=> Refactor JumpList and thumbnail toolbars management

GitUI/UserControls/RevisionGrid.cs
fixes #4483
The count was cleared when refreshing the index (recreating all commits) but the commit count was not forced to be updated.
This change caches the count (similar to the commit button).
- Enable artificial commits
- Refresh the index
- Verify that count (may be 0) is still visible
=> Artificial commit count was cleared when manually refreshing the index

GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, GitCommands/Settings/AppSettings.cs, GitCommands/Settings/BranchOrdering.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ToolbarSettingsPage.cs, Plugins/Bitbucket/BitbucketPullRequestForm.cs, Plugins/GitUIPluginInterfaces/GitRefsOrder.cs, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/IGitModule.cs
The user can specify whether branches are sorted in A-Z or by date order. The left panel now uses the same ordering techniques.
At the same time git ref sorting has been centralised:
* Incorporate git ref sorting into `IGitModule.GetRefs` method so it is universally and uniformly available across the app.
* Rename `BranchOrdering` to `GitRefsOrder` to align with the purpose.
Fixes #4830
Relates to #4814
before:
- ![image](https://user-images.githubusercontent.com/4403806/38706935-7aee475c-3ef2-11e8-9990-26b177f0bb7a.png)
after:
- ![image](https://user-images.githubusercontent.com/4403806/40918290-37fbee60-6849-11e8-939f-e41295bf167c.png)
- ![image](https://user-images.githubusercontent.com/4403806/40918345-60be40a0-6849-11e8-91ab-19147290c6b …
=> Fix 4830 inconsistent branch ordering

GitUI/UserControls/RevisionGrid.cs
Fixes #5029
- Move the initialisation of `BuildServerWatcher` to the constructor of `RevisionGrid` so that a NRE is not possible. There appears to be no reason to defer this construction as it doesn't do anything that depends upon later activity.
- GitExtensions version: master (observed as far back as 
- GIT version: 2.17.1.windows.2
- OS version: Windows 10 1803 (OS build 17134.81)
=> Initialise BuildServerWatcher earlier

GitCommands/Git/Extensions/GitRevisionExtensions.cs, GitCommands/Git/GitRevision.cs, GitCommands/Git/RevisionDiffProvider.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/UserControls/FileStatusList.cs, Plugins/GitUIPluginInterfaces/ObjectId.cs, UnitTests/GitCommandsTests/Git/Extensions/GitRevisionExtensionsTests.cs, UnitTests/GitCommandsTests/Git/ObjectIdTests.cs, UnitTests/GitCommandsTests/Git/RevisionDiffProviderTest.cs
Handling of CombinedDiffGuid was kept in FileStatusList.
When GUIDs for other artificial GUIDs were changed, the CombinedDiffGuid was not changed
Fixes #5015
- Move CombinedDiffGuid  to GitRevision
- Manual tests
- Windows 10
=> GUID conflict for IndexGuid and CombinedDiffGuid

GitUI/BuildServerIntegration/BuildInfoDrawingLogic.cs, GitUI/UserControls/RevisionGrid.Designer.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/RevisionGridClasses/DvcsGraph.cs, GitUI/UserControls/RevisionGridUtils.cs
Show lane information in tooltip for RevisionGrid.GraphDataGridViewColumn.
Show tooltips for RevisionGrid *always* if text has been truncated.
Fixes #4990.
- see issue, please
- manual testing with several repositories
- found that the **IsMessageMultilineDataGridViewColumn** has been **broken** during the last week (didn't have time to investigate it yet, but I'm going to) 
- GIT 2.17.1.2
- Windows 7
=> RevisionGrid: Show more informative tooltips

GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs, GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
The functionality adds a nice touch, however it can be extremely harmful, if used carelessly. It also introduces an inconsistent UX, because other parts of application do no allow deletion of refs without prior confirmation.
The functionality can be re-instated with an introduction of a user controller setting (explicit opt in, placed on the Advanced tab), that would enable force deletion of refs universally all across the app.
This includes branch and tag deletion dialogs.
Relates to #4814
/cc: @EbenZhang
=> Remove 'Force Delete' functionality

GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs, GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs, GitUI/BranchTreePanel/RepoObjectsTree.resx, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUI.csproj
Fixes a number of issues reported in #4814
There are a few tweaks, probably the easiest to go over each commit.
The most notable changes proposed in this pull request:
- Automatically select and expand to the current branch
- Do no allow checkout the current branch
- Do not allow delete the current branch
- Add context menu spacers to various menus
- Add expand/collapse all to almost all nodes
- a lot of manual checks
/cc: @EbenZhang
=> Left panel tweaks

GitUI/UserControls/RevisionGrid.cs
Fixes #4360
Revert commit in revision grid only reverted the last selected commit.
The behavior is changed to be analog with cherry-pck commit, revert all selected starting with the newest (selection order is ignored, larger refactoring should be done with interactive rebasing).
- n/a
- Select two (or more) commits 
- Revert the commits 
- Verify that reversion is done with the newest first
- Windows10
=> RevisionGrid: Multiselection of revert commit

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Logging/CommandLogEntry.cs, GitCommands/Logging/CommandLogger.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/BrowseDialog/FormGitLog.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormGitLog.cs, GitUI/CommandsDialogs/BrowseDialog/FormGitLog.resx, GitUI/Script/PowerShellHelper.cs, GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
part of #4213 and #4753
- Save command log to file
- Add "id" to commands, log start and stop
- Windows 10
=> Enhanced logging: Save log to file, log start of CommandsChanged

GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs, GitUI/CommandsDialogs/FormCleanupRepository.cs, GitUI/GitExtensionsForm.cs
Reverting the change (#4891, cbb66f4a739642f47bc26d63a378fcee72126ce4) that caused the regression.
The underlying original issue seems to be due to the form not using DPI auto scale mode.
Fixes #5021
- manually run to ensure forms retain their sizes and positions across re-launches
- Windows 10 with 200% scaling
=> fix: Windows size not restored

GitUI/CommandsDialogs/FormBrowse.cs
Fixes #4985. This gives the user some feedback in case the operation takes a long time.
- Show a wait cursor during `RevisionGrid.GoToRef` on `FormBrowse` 
- Windows 10
=> Selecting branch in tree shows wait cursor

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormDiff.cs
Regression from #4988
A few similar adjustments that will cause argument exception instead.
- Manual test with incorrectly removed submodule (giving strange messages also on command prompt)
- Other changes by code review.
- Windows 10
=> Nullexception when no submodule status

Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs, Plugins/BuildServerIntegration/JenkinsIntegration/Settings/JenkinsSettingsUserControl.Designer.cs, Plugins/BuildServerIntegration/JenkinsIntegration/Settings/JenkinsSettingsUserControl.cs
Fixes #5054
- Configureable ignore build events for certain branch names
n/a
- Manually - Jenkins setup with multiple build events for one branch required to see the benefits, but logging-log4net on builds.apache.org can be used to suppress certain branches.
=> Jenkins: Ignore build events for certain branches

GitUI/UserControls/RevisionGrid.cs
=> Show branches before tags in the revision grid. 

GitCommands/Settings/AppSettings.cs
A beginning following the discussion in #5030
- In revision grid, "Show SHA-1" and "Show indicator for multiline message" are enabled by default
- In commit form, "Mark ill formed lines" is enabled by default
- I removed the folder `%APPDATA%\GitExtensions` to restart with the default settings
- Launch the application
- Verify that the 3 settings are enabled by default
- GIT 2.17
- Windows 10
=> Change some default settings values

GitUI/CommandsDialogs/FormCommit.cs
Fixes #5044 
- Apply font setting for commit message in commit dialog when using git commit template
I intentionally set the commit font to a big size at 20
- Before<br><img src="https://user-images.githubusercontent.com/11786151/41055617-5f252fe0-69f4-11e8-8c34-47a73af55394.png" width=500>
- After<br><img src="https://user-images.githubusercontent.com/11786151/41055712-90eedf08-69f4-11e8-83a8-011758746580.png" width=500>
- Deploy the beta version on my computer and keep using it. It seems good to me.
- GIT 2.17.1 and above
=> Apply font setting when using git commit template

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitVersion.cs, GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
Fixes #5066
To be submitted for 2.51 too.
- Use --no-optional-locks for git-status related to the commit count to avoid blocking interactive commands
- n/a
- Manual tests
- GIT 2.17.1
- Windows 10
=> Avoid obtaining locks for git-status in the background

GitUI/UserControls/RevisionGridClasses/RevisionGridMenuCommands.cs
Fixes #5052 
- Fixed a bug where "Toggle Branch Tree Panel" menu item command had no icon.
- Before:
- After:
=> Fixed "Toggle branch tree panel" menu item icon

GitUI/CommandsDialogs/FormResetChanges.Designer.cs
- Add Alt+N as a hotkey for the checkbox 'Also delete new files and/or directories' in the reset dialog
- Nothing
- Nothing
=> Better accessibility for reset dialog

GitExtUtils/GitUI/ControlDpiExtensions.cs, GitExtUtils/GitUI/DpiUtil.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs
It looks like a bug in WinForms - NumericUpDown and TextBox controls' margins seems to get scaled beyond expectations when Windows is set to scale.
For example, if the design was done at 100% and Windows is set to scale to 200%, NUD's margins get set to (96, 96, 96, 96) and TB's margins get set to (12, 12, 12, 12).
Fixes #5098
- refer to the original issue
- manual runs, opened various forms and dialogs to check for visual regressions
=> Fix 5098 margin adjustments

GitUI/UserControls/ExListView.cs
Relates to #5084
before:
after:
- manually
- Windows 10
=> fix: Dashboard categories can't collapse

GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/UserControls/FileStatusList.cs, ResourceManager/GitExtensionsUserControl.cs
Fixes #5065, fixes #5083.
- ignore the hotkey if the DiffFiles.FilterComboBox is focused and the hotkey is a normal character
- ignore the hotkey if no item is selected in DiffFiles
N/A
- Windows 7
=> Bugfix for #5065 and #5083: hotkeys 'B' and 'H' in RevisionDiff.

GitUI/CommandsDialogs/SettingsDialog/EditorHelper.cs, GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Fixes #2507
- Added Atom editor to editors list in Git Config.
- Set Atom editor as the global editor and opened the "Reword commit" dialog, to see it opens Atom.
- Windows 10
=> Add Atom to editors list

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
Winmerge since 2.15.2 supports 3-way merge and should be available as an (auto) configured merge tool. ([Changelog](https://bitbucket.org/winmerge/winmerge/src/7d1863b8c6867aef0407702f6d19cfbe608375f4/Docs/Users/ChangeLog.txt?fileviewer=file-view-default) for Winmerge.)
Fixes #3163.
- Adding Winmerge as merge tool
- Fixing merge command for Winmerge
- Fixing sorting of diff tools.
- No UI changes.
- Compiled and tested that it worked. 
- GIT 2.17
- Windows 10
=> Adding Winmerge as (auto) merge tool

GitUI/CommandsDialogs/FormInit.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormInitTests.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/app.config
Fixes #5107
- reset `ComboBox.SelectedIndex` before assigning a free form text to `ComboBox.Text` to display the current folder
- add UI tests to ensure the correct behavior
- manual
- automated tests
=> Fix create new repository does not use current folder

GitCommands/StringPool.cs
- Increase the initial capacity of StringPool. An average repository of 10000+ commits needs about 1000 buckets. I propose to start with 2000 buckets to lower the number of collisions and leave some free buckets for larger repos. Avoiding unnecessary rehash operations decreases parsing time of ~100ms on my laptop.
=> Increase the initial capacity of StringPool in order to avoid frequet rehashing.

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs, GitUI/GitUICommands.cs
- Additional changes to #4309 to provide an option to show the rebase dialog.
Added the last checkbox
- Rebase on selected commit and interactively, the dialog doesn't show
- Rebase with adv options, the dialog shows this time.
- Rebase from Commands menu, the dialog shows
- turn off the settings and repeat the above steps, the dialog shows always
- GIT 2.16 32 bits
- Windows 10 64 bits
=> Option to always show rebase dialog

GitCommands/Git/GitCommandHelpers.cs
Fixes #5127 
The previous commit of this file introduced the bug that the status command was omitted from the command string if the --no-optional-locks option was added. This resulted in wrong counts of "Current unstaged changes" and "Commit index" (always 1).
=> Fix "Current unstaged changes" and "Commit index"

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitItemStatus.cs, GitCommands/Git/GitModule.cs, GitUI/AutoCompletion/CommitAutoCompleteProvider.cs, GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, GitUI/CommandsDialogs/FormArchive.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/RevisionDiff.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, GitUI/Editor/FileViewer.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid.cs, GitUI/UserControls/ToolStripClasses/CommitIconProvider.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitUITests/CommandsDialogs/RevisionDiffControllerTests.cs, UnitTests/GitUITests/UserControls/ToolStripClasses/CommitIconProviderTests.cs
Part of #4281 
Required for wip #5104 and #5116 (will rebase on top of this)
There is a common parsing method for git-status and git-diff. The output formats are mostly the same but not identical and do not carry the same information:
- Unmerged (conflict) are duplicated for git-diff when comparing Index->WorkTree (see #5104)
- Information about Staged status is not always available so GitItemStatus .IsStaged can be unknown. The PR will throw exception if unknown status is 
This PR documents the parsing (preparing for #5116 too) and clean up the use of staged.
Some limitations when Staged status was guessed was removed in RevisionDiff.
- Added tests
- Manual testing - mostly on top of drew's v3 …
=> git-diff parsing of unmerged and staged

GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/Translation/English.xlf
Also extended CommonLogic with Diff utility functions similar to Merge.
- The translation text _mergeToolXConfigured was wrong and hence the (auto) configured merge tool was never reported.
- Simplified the code for diff tool reporting by extending CommonLogic so diff and merge is treated similarly. 
NB! I only updated the English XLF file (so I could verify that the fix was correct) since I imagine that you have some batch tool to update all the XLF files.
- No UI changes.
- Compiled and verified that the merge tool was reported correctly.
- GIT 2.17
- Windows 10
=> Fixing mergetool (setting) status message

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitVersion.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
GE uses a common routine to parse git-status porcelain v1 and git-diff output.
The routine is hard to maintain.
git-status added porcelain v2 format in Git 2.11. This PR enables this format to simplify the parsing of git-status, as well as providing more information. Git outputs more data but parsing of v2 is more efficient. This information will make it possible to find if submodules are changed (commit updated) or dirty without an explicit query of the submodule (used in #5104).
Note: Git older than 2.11 can still be used but will not provide the changed/dirty information. GetAllChangedFilesFromString_v1() can be simplified when older than 2.11 is dropped (hard limit).
- The porcelain v2 format used
- Rename GetAllChangedFilesFromString() to …
=> Enable git-status porcelain v2 format

GitCommands/Config/SettingKeyString.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
Check whether the user has an outdated setting pointing to git-credential-winstore.exe and, if so, notify the user and point to our GitHub wiki with more information:
https://github.com/gitextensions/gitextensions/wiki/How-To:-fix-GitCredentialWinStore-missing
Fixes #3511
Fixes #3732
Fixes #4179
* `credential.helper` is set to git-credential-winstore.exe (100% scale)
* `credential.helper` is set to git-credential-winstore.exe (250% scale)
* `credential.helper` is set to something else
- manual runs to verify the UI setting and unsetting `credentials.helper` setting
- Windows 10
=> fix: GitCredentialWinStore missing

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/Translation/English.xlf, GitUI/Translation/German.xlf
- The tool strip button `Stash` does *not* stash changes at once, it just opens the stash dialog.
- That's why the tooltip should be "Manage stashes" instead of "Stash changes".
- The same applies to the main menu `Commands` | `Stash changes...`.
- Adapted the German translation, too.
- before:
- after:
- switched between English and German
- GIT: 2.17.1.windows.2-x64
- Windows 7
=> Distinguish between "Stash changes" and "Manage stashes"

GitUI/HelperDialogs/FormChooseCommit.cs
`Tag` was badly casted as `ObjectId` but contains the sha1 as string...
=> FormChooseCommit: fix crash when click on parent commit link

Plugins/DeleteUnusedBranches/CheckBoxHeaderCellEventArgs.cs, Plugins/DeleteUnusedBranches/DataGridViewCheckBoxHeaderCell.cs, Plugins/DeleteUnusedBranches/DeleteUnusedBranches.csproj, Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.Designer.cs, Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Fixes #3522
- Added "Select All" feature to Delete Unused Branches plugin
- Before:
- After:
- Pressed the button and made sure it selects all branches.
- Windows 10
=> Added "Select All" feature to Delete Unused Branches plugin

Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
Fixes invalid `Version` attribute casting. Otherwise, Rider is unable to parse that value and complains about missing types 😖 
Don't create an issue as change is very tiny.
=> Fix invalid `version` attribute casting

GitUI/CommandsDialogs/FormPush.cs
Fixes #4205
- Pass the correct window owner, so pop-up appears on the same screen as the parent
Should I also create a PR for `release/2.51` branch to ensure that change goes to the next release? I want to see it released soon.
=> Fix "Do you want to add a tracking reference?" dialog appears on different screen

GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/TaskExtensions.cs, GitUI/UserControls/MainThreadScheduler.cs
Fixes #5134
📝 If the underlying cause of the bug was an *infinite* recursive loop in code, this pull request will avoid a Stack Overflow but may not correct the source of the problem. The implementation change here is similar to tail call elimination, and assumes the sequence is finite but can be larger that what fits in a stack.
=> Force MainThreadScheduler to yield even when called from the main thread

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Fix for #5187 
programFilesPath === null can't be used with Path.Combine.
I've added additional condition here.
mono -V
Mono JIT compiler version 5.12.0.226 (tarball Thu May  3 09:42:09 UTC 2018)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
TLS:           __thread
SIGSEGV:       altstack
Notifications: epoll
Architecture:  amd64
Disabled:      none
Misc:          softdebug 
Interpreter:   yes
LLVM:          supported, not enabled.
GC:            sgen (concurrent by default)
=> fix for #5187: can't open settings

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
master branch PR
Conflict:	GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Fix for #5187
programFilesPath === null can't be used with Path.Combine.
=> fix for #5187: can't open settings (master branch)

Plugins/GitFlow/GitFlowForm.Designer.cs, Plugins/GitFlow/GitFlowForm.cs
- added checkbox for push Buxfixes and Releases after finished it.
- add parameter -P to git flow finish command
resolves #5157 
Git flow panel before changes
Git flow panel after changes
It can be useful?
- GIT 2.51 and above
- Windows 8.5 and above
=> Add checkbox Push After Finish in GitFlow plugin panel

GitCommands/Git/GitModule.cs, GitCommands/Git/GitSubmoduleStatus.cs, GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/CommandsDialogs/FormDiff.cs, ResourceManager/LocalizationHelpers.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
Fixes #5200.
- Partially reverts argument restriction
- Adds unit test for the case where the old commit can be null
- GIT 2.18.0
- Windows 10
=> [WIP] Fix ANE in submodule status

GitCommands/ArgumentBuilderExtensions.cs, GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs
Regression from ObjectId handling in #5087
Fixes #5193
Note: The only other command with special handling for ObjectId.InndexId is GetFileBlobHash(), OK special handling there.
- Exception when resetting to Index
- n/a
- manual test resetting worktree file
- Windows 10
=> Reset file to index failed due to ObjectId handling

Plugins/Bitbucket/BitbucketPlugin.cs, Plugins/Bitbucket/BitbucketPullRequestForm.cs, Plugins/Bitbucket/Settings.cs
Fixes #5147 
- Fixed Bitbucket plugin server error on non-Bitbucket repo.
The error was trying to use BitbucketPullRequestForm after it was disposed.
- Run the scenario and made sure the bug does not reproduce.
=> Fixed Bitbucket plugin error on non-Bitbucket repo

GitUI/CommandsDialogs/FormBrowse.cs
It is better to show the exception to users than hiding it
and showing a partially loaded state.
=> Don't swallow exceptions.

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs, GitUI/Script/ScriptInfo.cs
fix for #5219 
regression introduced by refactoring done in #5087
where icons are now in another resource file
Fix:
- icon menu was no more filled with the icons
- icons in the toolbar was no more displayed
- (additional improvement) the icons are now alphabetically sorted
=> fix display of script icons

GitUI/CommandsDialogs/FormCommit.cs
- Fixes an internal NRE when attempting to restore previously selected files
Repro:
- run in debugger with 'break on all exceptions'
- have a clean workspace
- load commit form
- create unstaged change
- refresh form
- GIT 2.18
- Windows 10
=> Prevent NRE in FormCommit

GitUI/CommandsDialogs/FormCommit.cs, GitUI/SpellChecker/EditNetSpell.cs, GitUI/SpellChecker/SpellCheckEditControl.cs, GitUI/SpellChecker/TextBoxHelper.cs
Fixes #5024
- Scale the spelling mistake underline wave
- Scale the line-too-long highlight
- Some code formatting
Screenshots:
Before
After
- Windows 10 at 200% scaling
=> Fix commit message adorners under high DPI

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/CommandsDialogs/FormCheckoutRevision.cs, GitUI/CommandsDialogs/FormCreateBranch.cs, GitUI/CommandsDialogs/FormCreateTag.cs, GitUI/CommandsDialogs/FormMergeSubmodule.cs, GitUI/HelperDialogs/FormResetCurrentBranch.cs, GitUI/Script/ScriptRunner.cs, GitUI/UserControls/BranchSelector.cs, GitUI/UserControls/CommitPickerSmallControl.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Follows on from #5210. There are at least two scenarios where the checked out commit ID cannot be obtained:
- It is a bare repo with no work dir
- The repository has no commits
This change makes `GitModule.GetCurrentCheckout` return `null` in either of these cases, and updates callers to handle null values where necessary.
- GIT 2.18
- Windows 10
=> Fix bug loading empty repo

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Logging/CommandLog.cs, GitUI/Script/PowerShellHelper.cs, GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
Motivated by issue reported in #4256. Relates to #4753.
- Keep record of the PID of processes and display in command log
Screenshots:
- GIT 2.18
- Windows 10
=> Include process ID in command log

GitUI/UserControls/RevisionGrid/EmptyRepoControl.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Prior to this change, the UI would show "Edit .gitignore" and "Commit" buttons when detecting an empty repo, even if bare. These buttons have no utility for bare repos, and are now hidden under such conditions.
Clicking the buttons on such repos had no effect. The edit button showed a warning dialog. The commit button did nothing at all.
- Manual testing with a variety of test repos
- GIT 2.18
- Windows 10
=> Hide useless buttons for empty bare repo

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes #5232
- Fix incorrect assumption in Regex that remote URL cannot contain a space
- Manual testing (thanks to @pmme for clear repro steps)
- GIT 2.18
- Windows 10
=> Fix parsing of remote URLs that contain spaces

.github/PULL_REQUEST_TEMPLATE.md, GitCommands/Git/GitVersion.cs
Fixes #5106
- Raise minimum Git version 2.11 (no hard limit enforced, just warning when starting up)
- Raise recommended version 2.18.0 
Note: There are some soft limits, for instance will older than 2.11 provide less information for #5104 .
- n/a
- Using 2.18 for a month
=> Raise Git minimum, recommended version

GitCommands/UserRepositoryHistory/LocalRepositoryManager.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs, UnitTests/GitCommandsTests/UserRepositoryHistory/LocalRepositoryManagerTests.cs
Resolves #5143 
- Added 'Remove Missing Projects from the list' feature to dashboard, removes all missing repositories.
Before:
After:
=> Add 'Remove Missing Projects' feature to dashboard

GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Relates to #5236. Can't validate that it fixes the issue, as I cannot reproduce it.
- Ensure the bounds width & height are both greater than zero before painting
- Can't test this as cannot repro original bug. It seems like this would fix the problem, and the change is benign.
- GIT 2.18
- Windows 10
=> Validate bounds width/height before paint

GitExtUtils/Properties/AssemblyInfo.cs, GitUI/Translation/UpdateLocalEnglishTranslations.ps1, Plugins/Bitbucket/BitbucketPullRequestForm.cs, ResourceManager/Xliff/TranslationUtil.cs, TranslationApp/Program.cs, TranslationApp/TranslationApp.csproj, TranslationApp/app.config
The app could not be run due to missing binding redirects and JTC.
While fixing I observed an interesting problem - some of the translations get rendered with the runtime context, e.g.
https://github.com/gitextensions/gitextensions/blob/3689f62beac05299d71a87f36b5b9a1848613802/GitUI/CommandsDialogs/FormClone.cs#L18
https://github.com/gitextensions/gitextensions/blob/3689f62beac05299d71a87f36b5b9a1848613802/GitUI/CommandsDialogs/FormClone.cs#L376
gets recorded as:
```diff
@@ -2808,6 +2834,11 @@ revision:</source>
<source>&amp;Browse</source>
<target />
</trans-unit>
+      <trans-unit id="Info.Text">
+        <source>The repository will be cloned to a new directory located here:
+D:\Development\gitextensions\gitextensions\ (None)\[&amp;Subdirectory to create:]</source>
+        <target /> …
```
=> Fix the TranslationApp

GitExtUtils/Linq/LinqExtensions.cs, Plugins/Statistics/GitStatistics/CodeFile.cs, Plugins/Statistics/GitStatistics/FormGitStatistics.cs, Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs, Plugins/Statistics/GitStatistics/LineCounter.cs
Fixes #5190
- Include `*.ts` files in statistics
- Refactor statistics generation for performance
- Manual testing on repositories containing TypeScript files
- GIT 2.18
- Windows 10
=> Stats support TypeScript, and some perf work

GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
Fixes
"C:\Program Files\Git\bin\git.exe" fetch --progress "origin"
System.InvalidOperationException: Z tym obiektem nie jest skojarzony żaden proces.
w System.Diagnostics.Process.EnsureState(State state)
w System.Diagnostics.Process.EnsureState(State state)
w System.Diagnostics.Process.get_Id()
w GitUI.UserControls.EditboxBasedConsoleOutputControl.StartProcess(String command, String arguments, String workdir, Dictionary`2 envVariables) w D:\projekty\GitExt\GitUI\UserControls\EditboxBasedConsoleOutputControl.cs:wiersz 140
w GitUI.FormProcess.ProcessStart(FormStatus form) w D:\projekty\GitExt\GitUI\FormProcess.cs:wiersz 148
command = C:\Program Files\Git\bin\git.exe
arguments = fetch --progress "origin"
=> The process id can not be read before the process is started.

.gitattributes, CommonAssemblyInfo.cs, GitExtSshAskPass/SshAskPass.rc2, GitExtensionsShellEx/GitExtensionsShellEx.rc, GitExtensionsVSIX/source.extension.vsixmanifest, Setup/MakeInstallers.cmd, Setup/set_version_to.py
As next version is called "v3" or 3.0, the version in master should reflect that. AppVeyor version is already updated.
Also, increasing the version from 2.51 will avoid the popup "Do you want to update to the latest 2.51?"
Numeric version set to 2.99.90, display to 3.00.a1 similar to before.
Personally, I would have preferred to have a more Continuous Delivery naming and set 3.00.00 and just increase for every release. Then we decide that 3.00.22 is rc1, 3.00.34 is first release etc.
=>  Update version for GE in master to v3

GitCommands/Git/Extensions/GitRevisionExtensions.cs, GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitRevision.cs, GitCommands/Git/RevisionDiffProvider.cs, GitCommands/Patches/PatchManager.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FileStatusListContextMenuController.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUICommands.cs, GitUI/UserControls/RepoStateVisualiser.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, Plugins/GitUIPluginInterfaces/ObjectId.cs, ResourceManager/LinkFactory.cs, UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs, UnitTests/GitCommandsTests/Git/Extensions/GitRevisionExtensionsTests.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommandsTests/Git/GitRevisionTesterTests.cs, UnitTests/GitCommandsTests/Git/ObjectIdTests.cs, UnitTests/GitCommandsTests/Git/RevisionDiffProviderTest.cs, UnitTests/GitUITests/CommandsDialogs/RevisionDiffContextMenuControllerTests.cs, UnitTests/GitUITests/CommandsDialogs/RevisionDiffControllerTests.cs, UnitTests/GitUITests/UserControls/RepoStateVisualiserTests.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Fixes #5230 
- Internal renaming in the code:
WorkTree/Index should be used rather than Unstaged/Staged
- n/a
- no changes
=> Cleanup: WorkTree/Index should be used rather than Unstaged/Staged

GitCommands/ArgumentBuilder.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormBlame.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/BranchSelector.cs, GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
- `GitModule.EditNotes` accepts `ObjectId`
- `GitModule.GetRevision` only accepts `ObjectId` (removing overload that accepts string in favour of allowing a `null` `ObjectId` to represent `HEAD`, as is done elsewhere)
- Use of local functions, `ArgumentBuilder`
- GIT 2.18
- Windows 10
=> GitModule uses ObjectId in a few more places

Plugins/Statistics/GitImpact/ImpactControl.cs
Part four from #5234
Code still generates a random colour based upon the author string, it just uses the hash code rather than string manipulation.
- Simplify colour selection
- Manual tests
- GIT 2.18
- Windows 10
=> 5234 part 4

GitCommands/Config/ConfigSection.cs, GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitDirectoryResolver.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitRef.cs, GitCommands/StringExtensions.cs, GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/Hotkey/KeysExtensions.cs, GitUI/Script/ScriptRunner.cs, Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs, Plugins/Gerrit/FormGerritPublish.cs, Plugins/GitFlow/GitFlowForm.cs, UnitTests/GitCommandsTests/StringExtensionTests.cs
Part three from #5234
We do a lot of string manipulation. Finding indexes and obtaining
substrings can lead to verbose and confusing code, and bugs.
This change introduces a few extension methods for working with
strings that leads to clearer code in several places.
- RemovePrefix
- RemoveSuffix
- SubstringUntil
- SubstringUntilLast
- SubstringAfter
- SubstringAfterLast
It replaces some older versions of these (SkipStr, SubstringUntil) with
versions that don't special case null values.
- Substring review and extension methods
- Manual tests
- Unit tests
- GIT 2.18
- Windows 10
=> 5234 part 3

GitUI/CommandsDialogs/FormAbout.Designer.cs, GitUI/CommandsDialogs/FormAbout.cs
Closes #5201
- before 
- after
=> fix FormAbout layout

Plugins/Statistics/GitStatistics/GitStatisticsPlugin.cs
Fixes #2155
- Add syntax highlighting for `.jsm` files
- ~~~Make the loading of `AutoCompleteRegexes.txt` use async IO (this occurs during the first load of `FormCommit`)~~~
- GIT 2.18
- Windows 10
=> Syntax highlighting for JSM

GitUI/CommandsDialogs/FormBrowse.cs
Fix the initialisation sequence to correctly set/restore spliters, layouts and menus.
Fixes #5247
Fixes #5262
- manual runs
=> fix: `FormBrowse` layout incorrect

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
The dashboard control got its `Parent` assigned before the form was actually opened,
this caused the main menu not available.
Fixes #5265
- before
- after
=> fix: Dashboard menu items are missing

GitCommands/Git/GitCommandHelpers.cs, GitCommands/PathUtil.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Part seven from #5234
- Move `GitCommandHelpers.GetFileExtension` to `PathUtil` and add tests
- Manual tests
- Unit tests
- GIT 2.18
- Windows 10
=> 5234 part 7

GitCommands/Patches/PatchManager.cs
Part eight from #5234
- Refactor `PatchManager` string usage
- Manual tests
- GIT 2.18
- Windows 10
=> 5234 part 8

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
Followup of the "Stop tracking" feature in the file tree (#4093) added to the Commit Form...
- Add "Stop tracking file" feature to the Commit Form
- Fix "Stop tracking" command that fail when there is a space in the path (existing bug in master :( )
- Fix state of file displayed in "unstaged changes" list after unstaging a delete change (after using the "stop tracking" feature)
- GIT 2.18
- Windows 10
=> Add "Stop tracking file" feature to the Commit Form

GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Fixes #5272
- Bypass operation for artificial commit IDs, avoiding exception later on
- GIT 2.18
- Windows 10
=> Don't pass artificial ObjectId to GitModule.GetTree

GitCommands/RevisionReader.cs
`git log -z --name-only` returns multiple consecutive null bytes. This may be a bug in git, or may not, but it causes parsing to fail.
This change works around the issue.
- Skip zero length chunks in git log output
- Asked question on git mailing list to see whether this is a bug or signal of something else
- GIT 2.18.0.windows.1
- Windows 10
=> Workaround consecutive null bytes from git log

GitExtensions.sln
(Follows research into #2272 and #2253)
The debug configuration of that project includes a DATACONSISTENCYTEST symbol that causes very slow assertion logic to run.
We used to take this dependency via NuGet, using release builds.
This change means we use the release build even during debugging, as we would have before making the project a source submodule.
Note that this results in a prompt after the first debug run in the IDE, so long as you select "continue and don't ask again".
- GIT 2.18
- Windows 10
=> Debug config uses release mode ICSharp.TextEditor

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/Editor/FileViewer.Designer.cs, GitUI/Editor/FileViewer.cs
Fixes #2272
- Move UI for deferring display of large files to `FileViewer` from `FormBrowse` so that it appears in all places we show diffs.
- Display the actual file size in the link label text.
(also applies to file tree)
- GIT 2.18
- Windows 10
=> Move large file warning from FormCommit to FileViewer

GitExtensions/AutoCompleteRegexes.txt
This adds auto-complete/dictionary entries for the commit message text box based on `new` and `using` patterns.
As an example, in a recent commit message:
> Use ArgumentBuilder and move SmartFormat reference
Before this change, both ArgumentBuilder and SmartFormat were flagged as spelling mistakes. These symbols were present in code resembling `new ArgumentBuilder` and `using SmartFormat;`.
- GIT 2.18
- Windows 10
=> Add two patterns to C# AutoCompleteRegexes

GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, ResourceManager/ResourceManager.csproj
SmartFormat is used by the ResourceManager project, and with this
change it's no longer needed in GitCommands. We can move the
PackageReference accordingly.
Manual testing.
=> Use ArgumentBuilder and move SmartFormat package reference

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
Fixes #5252
- Hide "File Tree" tab for artificial commits
- Reorder fields in `FormBrowse.Designer.cs` for readability
- GIT 2.18
- Windows 10
=> Hide "File Tree" tab for artificial commits

Setup/Product.wxs
Fixes #5293
- Add the System.ValueTuple.dll to the installer
N/A
- Make the installer
- Install the application and run it.
- GIT 2.18
- Windows 10
=> Fix: Unable to run app due to missing of System.ValueTuple.dll

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5166
Refactor in ef2e4794cad2b755a984c6bb592027c17b6cf966 broke this. There was a missing `!`. This change reuses an existing extension method to keep things simple.
- GIT 2.18
- Windows 10
=> Fix blocking UI when drawing superproject refs

GitCommands/ArgumentBuilderExtensions.cs, GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitTreeParser.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs, GitUI/CommandsDialogs/BrowseDialog/FormBisect.cs, GitUI/CommandsDialogs/FormCherryPick.cs, GitUI/CommandsDialogs/FormRevertCommit.cs, GitUI/CommandsDialogs/FormVerify.LostObject.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs, Plugins/GitUIPluginInterfaces/ObjectId.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommandsTests/Git/ObjectIdTests.cs
- `ArgumentBuilder` extension for `IEnumerable<ObjectId>`
- Bisect operations accept `ObjectId`
- Revert operations accept `ObjectId`
- Cherry pick operations accept `ObjectId`
- `AppVeyorBuildInfo` uses `ObjectId`
- Method and test for parsing `ObjectId` from a regex capture without allocating temporary string, and update usages
- Some formatting
- GIT 2.18
- Windows 10
=> More uses of ObjectId

GitCommands/Git/GitModule.cs, GitCommands/PathUtil.cs, GitCommands/Settings/AppSettings.cs, GitUI/UserControls/PathFormatter.cs, UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
- `GitModule` eagerly loads submodule properties. Prevents race conditions.
- Move path separator from `AppSettings` to `PathUtil` (it's a constant, not a setting).
- Add `PathUtil.RemoveTrailingSeparator` and unit tests, to complement `PathUtil.EnsureTrailingPathSeparator`.
` Add `PathUtil.FindAncestors` and unit tests.
- Annotate and document the three properties in question, `SuperprojectModule`, `SubmodulePath`, `SubmoduleName`.
This simplifies `GitModule` a bit. Testing shows that the laziness is not used as nearly every instance of `GitModule` initialises these fields after construction. Those that don't test to have a `WorkingDir` of `""` which short circuits the initialisation anyway.
Future work would bring in the `IFileSystem` abstraction …
=> GitModule eagerly loads submodule properties

GitUI/CommandsDialogs/FormReflog.Designer.cs, GitUI/CommandsDialogs/FormReflog.cs, GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/Translation/en_pseudo.Plugins.xlf, GitUI/Translation/en_pseudo.xlf
Relates to #5305 (possibly fixes it).
- Remove all references to `ImageScalingSize`, changing `FormReflog` and `FormStash` (#5305)
- Fix vertically compressed reflog grid rows at high scaling
- Add icons to reflog context menu
- Suffix reflog context menu items with "..." as they prompt the user
- Fix flickering in reflog grid during mouse move
I don't include screenshots of `FormStash` because the icons look identical before/after. My theory is that they'll look better at 100% scaling though. My docking station (and hence external 96dpi monitor) is still kaput so it's hard for me to test at 100% scaling right now without rebooting a bunch of times. These changes are benign in the worst case. If merged could someone please verify against #5305?
- Manual testing at 200%
- 200% scaling
- …
=> DPI and other tweaks to FormReflog and FormStash

GitCommands/Git/GitModule.cs
Mentioned in #5281
- gitk would not start if Git path was set to "git root"/cmd/git.exe
- Manual test
- Windows 10
=> gitk would not start if Git path was set to cmd/git.exe

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormDiff.Designer.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs, GitUI/Hotkey/HotkeySettingsManager.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Looking for feedback on the below changes - I don't think they are ready to merge in, but looking for early advice (or taking over ownership, if there is an eager maintainer).
The dir-diff support is in relation to https://github.com/gitextensions/gitextensions/issues/1647
The diff modes are improvements I wanted while working on the dir-diff support.
Fixes #
- Add support for diff-tool, in the settings page
- Add two new compare modes 
- Compare to Working Directory
- Compare Selected Commits (use CTRL + click to select two commits, compare them in the order selected)
- Local testing with my setup
- …
=> Add dir-diff support and various diff options

GitCommands/Logging/CommandLog.cs, GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs, GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs, GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Follows #5281.
- Add option to the Git Command Log form that allows capturing call stacks for process launches in order to aid debugging
- Tidy some argument lists
- Use local function and simplify code a little
Screenshots:
- GIT 2.18
- Windows 10
=> Command log call stacks

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, GitCommands/RevisionReader.cs, GitExtUtils/ArgumentBuilder.cs, GitExtUtils/ArrayExtensions.cs, GitExtUtils/GitArgumentBuilder.cs, GitExtUtils/GitExtUtils.csproj, GitExtUtils/Linq/LinqExtensions.cs, GitExtUtils/StringBuilderExtensions.cs, GitExtensions.sln.DotSettings, GitUI/CommandsDialogs/FormFileHistory.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitExtUtils/ArrayExtensionsTests.cs, UnitTests/GitExtUtils/GitArgumentBuilderTests.cs, UnitTests/GitExtUtils/GitExtUtilsTests.csproj, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/LinqExtensionsTests.cs, UnitTests/GitUITests/StringBuilderExtensionsTests.cs
Follows #5281.
This PR was co-authored with @vbjay in drewnoakes/gitextensions#6 as an alternative approach to #5182, while waiting for #5281 to merge.
Fixes #5179.
Also fixes untracked issue relating to `rebase.autoSquash` setting overriding the checkbox in the UI.
- Introduce `GitArgumentBuilder` as a means of having default configuration in git command line arguments in a standard way, based upon the particular command in use
`GitArgumentBuilder` derives from `ArgumentBuilder` and so leverages existing extension methods for building arguments. It may be used anywhere `ArgumentBuilder` was used, allowing introduction as needed throughout the codebase. 
- Unit tests
- Manual tests
Has been tested …
=> Add GitArgumentBuilder for baseline command configuration

GitUI/CommandsDialogs/SettingsDialog/SettingsPageHeader.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsPageHeader.cs
Fixes #5311 #5187
For some reason tableLayoutPanel1 gets Width==int.MaxValue after InitializeComponent()
Probably it's due to some inconsistency in AutoSize behavor.
Width==int.MaxValue leads to an unhandled System.Exception with "Generic GDI exception" message  when tableLayoutPanel1 paints its background.
As tableLayoutPanel1 was used as simple auto-sized container for a sequence of controls, it was replaced
with a more proper FlowLayoutPanel, which also happens to be not having the issue with AutoSize.
- Ubuntu 18.04.1
- Mono
=> issue #5187 crash opening settings page in Ubuntu 18

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Fixes #5343
Modify MergeToolsHelper.cs to check `%LocalAppData%\Programs` for possible candidates.
non-UI change
I'd love to test the change but i'm not allowed to install the required software on the computer supplied by my company.
=> Check %LocalAppData%\Programs for editors/merge programs

GitUI/BranchTreePanel/RepoObjectsTree.cs
Whenever the left panel is opened for the first time it would remain empty until refreshed. It appears the loading sequence would be cancelled due to an incorrect order of events.
Whenever the left panel is refreshed a new cancellation token is obtained.
Few lines later, while attempting to determine the current local branch a new cancellation token would be provisioned cancelling the previously issued one.
The fix reorders the sequence, getting the local branch before obtaining a cancellation token for the left panel data loading.
Fixes #5326
=> fix: Branch Tree Panel initially empty

GitExtensions.sln.DotSettings
ReSharper complained about using enum as a generic constraint because its language version was set to too low.
=> Change ReSharper C# language version to 7.3

GitUI/UserControls/RevisionGrid/Graph/GraphModel.cs
Fixes #5167
Whenever we refresh we trigger clear sequence that clears the model and all claculated information about rows edges.
Without this information we are unable to correctly render the graph...
The recalculation is typically done on a background thread by the `RevisionDataGridView`, however here for us it is too late, and as a work around we must kick off the recalculation manually.
This feels dirty but it addresses a major regression.
The method seems to be pretty snappy, when measured in Debug build with `StopWatch` the timings were typically in vicinity of ns:
```
Loaded GitExtensions repo (timing : row index):
00:00:00.0005014 : 1
00:00:00.0016211 : 6
00:00:00.0000095 : 7
00:00:00.0000079 : 8
00:00:00.0000167 : 9
00:00:00.0001133 : 10
00:00:00.0000553 : 11
00:00:00.0000402 : 12 …
```
=> fix: Graph column width appears too narrow

GitUI/UserControls/RevisionGrid/Columns/AuthorNameColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/DateColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5337
- make the commit message column fill the remaining width
- suppress the non-working resizing of the last visible column
which is resized by resizing the message column
(Microsoft states, it was by design)
- after
- before
- switch on/off the visibility of other columns
- resize columns
- GIT: (2.17.1.w.2-x64)
- Windows 7
=> Add setting to maximize the commit message column

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs
The LeftPanel would override the user's commit selection whenever its content would get refreshed. The tree is handling `AfterSelect` event and that causes the user's selection to change to whatever branch or tag is being selected in the LeftPanel's tree.
Stop this from happening by ignoring the event handling sequence whenever the tree is reloaded.
Fixes #5144.
=> fix: Prevent LeftPanel from changing commit selection

GitUI/Editor/FileViewer.Designer.cs
Fixes #4978
Tested on 
- Ubuntu 18.04
- Mono 5.10: issue was reproduced and fixed
- Mono 5.14: issue did not reproduce before & after the fix
=> #4978 Diff view options are positioned wrong, cannot be selected
