GitUI/CommandsDialogs/FormDeleteTag.Designer.cs, GitUI/CommandsDialogs/FormDeleteTag.cs
=> fix: FormDeleteTag incorrect height in HiDPI

GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/PathFormatter.cs
Fixes #5206, fixes #4104
Used `System.Windows.Forms.TextRenderer` to measure and draw strings
To observe the difference
- set Application Font Tahoma 8
- open gitextensions commit 2e3afdac6b2b1d0a161be82d00176b2df2fdf48d
Before
After
Before
After
Windows 7 with default DPI 96
=> #5206 FileList: Space between path and file

GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs
Colors settings get "squished" when opening settings with Colors node selected because of the different order in which layout event fire.
The fix ensures that data is loaded to the page before layout calculations take place.
Fixes #5364
=> fix: Colors settings get "squished"

GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Fixes #5331
**Screenshots**
Selection rendering change when focused
Selection rendering change when non-focused
**Tested**
on Windows 7
=> #5331 FileStatusList: highlighted file name is too pale

GitUI/FilterRevisionsHelper.cs
Right now FormBrowse filter box doesn't apply the filter on Enter. Some googling has revealed that ToolStripTextBox.KeyPress doesn't work with Enter and suggestion is to use KeyUp thus this PR.
=> Apply FormBrowse filter textbox filter on Enter

UnitTests/GitCommandsTests/Git/GitBranchNameOptionsTest.cs, UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs, UnitTests/GitExtUtils/TableLayoutPanelExtensionsTests.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererIntegrationTests.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs
On my machine the exception messages are written in Polish. That causes a failure for tests that verify the exact messages.
=> Localized exception message.

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/Translation/English.xlf
Fixes #5374
- Instead of having a checkbox indicating that next pull button action would be set as default, allow the user to make this selection from a sub-menu
Screenshots before:
=> Change default Pull button action using a submenu

UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Test TryGetExactPathName failed:
Message:   String lengths are both 69. Strings differ at index 0.
Expected: "f:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community..."
But was:  "F:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community..."
-----------^
- Lowercase driveletters when comparing files on local should be set to lowercase
- fixed the test
- Windows 10
=> test failed for local drive letter

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/Hotkey/HotkeySettingsManager.cs
- GoToSuperproject hotkey - changes the current repo to the superproject repo
- GoToSubmodule  hotkey - opens submodules drop down list
=> GoToSuperproject and GoToSubmodule hotkeys

GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs
Changing the case of the path segment of a URL changes its meaning
Fixes #5409
- Remove `.toLower()`
- N/A
- Nothing
- Nothing
=> Don't lowercase URLs

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.cs, GitUI/GitUI.csproj, GitUI/UserControls/RevisionGrid/CellStyle.cs, GitUI/UserControls/RevisionGrid/Columns/AuthorNameColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/DateColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/GraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
2.5 release uses monospace font for Sha column. Not sure if this has been removed by accident or intentionally but at least to me Sha Ids look better in monospace font. At least with monospace the column looks tidy.
Before (notice non-uniform width of Sha column values):
After:
As for code changes. `RevisionDataGridView` holds `NormalFont` and so it might seem a good idea to have a monospace font defined here but `CommitIdColumnProvider` which needs this font is instantiated in `RevisionGridControl` and doesn't have access to `RevisionDataGridView` so I settled with having this font defined in `CommitIdColumnProvider` itself.
=> Use monospace font for Commit Id column

GitUI/GitUI.csproj, GitUI/UserControls/ExListView.cs, GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/ListViewGroupHitInfo.cs, GitUI/UserControls/ListViewGroupMouseEventArgs.cs
Fixes #5427
Fixes #5332 (not clickable part)
Fixes #4886
- Windows 7
=> fix ExListView group header collapse-expand button

GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs, GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/CommandsDialogs/FormCheckoutBranch.resx
Reverts #5184
Prevents invalid branch names from being used and allows user to type to filter combobox.
Fixes #5415 
- Allow typing in branch combobox
- prevent user from using a value that is a partial branch name
Ran it. Verified user can't type a branch name that does not exist and try to check it out.  
=> Allow typing to filter Branches

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Searching for `Foo Bar` would execute:
```
git log "-SFoo Bar"
```
That argument list should be:
```
git log -S "Foo Bar"
```
- Adds a space between `-S` and the filter text
- Fix the quotes so they enclose only the filter text
No UI change, but fixing this allows searching by content to work properly, so you see more result rows.
Note, to get this to work you must use this option:
- Manual testing and reviewing in the command log
- GIT 2.19
- Windows 10
=> Fix broken revision grid content filter

GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs
Fixes #5341
- expand the settings tree so that all search hits are shown
- before
- after
- GIT: (2.18.0.w.x64)
- Windows 7
=> Expand settings tree to show found nodes

GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Fixes #5437
Fixes #5438
- Remove `SizeChanged` handler
The current implementation of the `SizeChanged` handler causes a bad distortion to the UI and renders the listview unusable.
The handler is removed and the column is resized at the time of bindings items to the list.
This adds a small artifact that if the list was resized after items have been bound, the column may no longer be of the full width of the list.
- Add separator between the dropdown and the list
- manual
=> File status list tweaks

GitUI/CommandsDialogs/FormFileHistory.cs
Fixes #5485 Fix blame options mismatch name and function
- Make option "Detect move and copy in **this** file" use -M insted -C
- Make option "Detect move and copy in **all** file" use -C insted -M
- GIT 2.18 and above
=> Fix blame options mismatch name and function

GitUI/CommandsDialogs/FormBrowse.cs
Fixes #4370 Branch filter not working (fix only crash)
- Fix GE crash when there is no branch name contains branch filter text.
- GIT 2.18
=> Fix branch filter crash

Bin/gitext.sh
In case gitext.sh is symlinked (e.g. into $HOME/bin directory) on Linux the DIR variable currently resolves to the directory where the symlink is placed. We need it, however, to resolve to the directory where the actual script is placed, together with the actual executable. This minor change fixes it.
=> Resolve DIR properly when gitext.sh is symlinked on Linux

GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, GitUI/CommandsDialogs/FormBrowse.cs
-  Refresh button should force a recalculation of the git-status count
One scenario is that if the update time is very long (the time is dynamic based on update time), the user expects the count to update by explicit refresh.
- n/a
- Open Git Command Log
- Refresh button
- Verify that git-status runs in about a second, can be longer if git-status has run recently (will be improved with #5487) 
- GIT 2.19
- Windows 10
=> Browse: refresh git status count

GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Fixes #5432
- Add icon to Compare menu item in revision grid context menu
**Before**
**After**
- Manually tested by building the app and using the browse dialog
- GIT 2.11 and above (2.18)
- Windows 7 and above (Win 10)
=> Compare item in revision grid context menu now uses Diff icon

GitExtensions/Program.cs, TranslationApp/Program.cs
Fixes #5507 Swallow the exceptions in UI thread under VS debugger
- Make behaviour under VS debugger and without it the same.
- Manual testing 
- GIT 2.18
=> Fix an exception swallowing in UI thread under debugger #5507

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormRebase.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AdvancedSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs, GitUI/GitUICommands.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Problem
With addition of this advanced option (which is off by default!):
These two menu items both open rebase dialog with the only difference of `Interactive Rebase` being checked or not. This seems sub-optimal and also three menu items for the same action with different params is overcomplicated.
- Leave only two rebase options in RevisionGridControl
- `Selected commit` starting simple rebase immediately
- `Selected commit with advanced options...` opening rebase dialog with `Interactive rebase` checked based on Advanced option
- Replace current advanced option with a new one showing whether Rebase dialog has Interactive checked by default or not
=> Leave only two rebase options in RevisionGridControl

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
- Add some missing icons in the menu
- GIT 2.17
- Windows 10
=> FormBrowse: Add some missing icons in menus

GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
for the ones that don't have one
Follow up of #5495
- Icons used are the same than the ones used in the settings to keep consistency
- GIT 2.17
- Windows 10
=> RevisionGrid: Add icons in contextual menu

GitUI/CommandsDialogs/FormCommit.cs
- fix display of the icon that was no more visible in hdpi
- GIT 2.17 and above
- Windows 10 (hdpi)
=> FormCommit: fix icon branch display in status bar

GitUI/Editor/FileViewer.Designer.cs, GitUI/Editor/FileViewer.cs, GitUI/Translation/Czech.xlf, GitUI/Translation/Dutch.xlf, GitUI/Translation/English.xlf, GitUI/Translation/French.xlf, GitUI/Translation/German.xlf, GitUI/Translation/Italian.xlf, GitUI/Translation/Japanese.xlf, GitUI/Translation/Korean.xlf, GitUI/Translation/Polish.xlf, GitUI/Translation/Portuguese (Brazil).xlf, GitUI/Translation/Portuguese (Portugal).xlf, GitUI/Translation/Romanian.xlf, GitUI/Translation/Russian.xlf, GitUI/Translation/Simplified Chinese.xlf, GitUI/Translation/Spanish.xlf, GitUI/Translation/Traditional Chinese.xlf, GitUI/Translation/en_pseudo.Plugins.xlf, GitUI/Translation/en_pseudo.xlf
- Better labels for the lines of context (see screenshot). Talking about "lines of context" which is consistent with variables names and is also the wording used by the diff documentation. It's better to use the name used by everyone... 
- Disable context buttons when showing all the file content (see screenshot)
- rename control to be consistent with others.
- button increase/decrease the number of lines of context is disabled when showing all the file content.
- GIT 2.17
- Windows 10
=> Diff options improvements

GitUI/CommandsDialogs/FormBrowse.cs
Regression from #5491 , cherry picked from #5473
If commit count was not activated at all, Null exception when pressing Refresh
- null check
- n/a
- Deactivate count
- Restart GE 
- Refresh
n/a
=> Fixed null reference exception

GitUI/CommandsDialogs/FormSettings.cs
- Show only plugins with settings in the settings  tree view (the others are not displayed)
- GIT 2.17
- Windows 10
=> Settings: display in the tree only the plugins having settings to set

GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs
Fixes the application to crash occasionally when rendering tooltip. Tooltips are nice, but it isn't worth crashing the application for.
- The DataGridView of .Net is not threadsafe. This sometimes causes the exceptions when the indexer property on Rows or Cells are used. Added a try/catch.
- I got various exceptions before (null reference, index of of bounds, argument exception). After this change, the exceptions are no longer there.
- GIT 2.19
- Windows 10
=> Ignore exception when fetching tooltip. It's not worth crashing for.

Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
Deleting branches one at the time is slower, but sometimes a branch cannot be deleted for some reason. The entire process will then stop. Since there is no proper error handling showing what went wrong, this makes the plugin unusable.
- Delete branches 1 at the time instead of 1 command.
- I expect this plugin to be used occasionally. That the performance is not top-notch is ok. I use this once every 6 months, to clean up not-deleted feature branches. Usually I delete ~1500 branches in 1 batch.
- I used the plugin. Before, the process stopped. I needed to debug the code to see what went wrong.
Could it be improved?
- It would be nice if there is some kind of progress indicator
- It would be nice to …
=> Delete unused branches one at the time.

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Fixes #5084 item 2
Hovered dashboard items were not redrawn if user quickly moved mouse out of the list.
As a result user could see incorrectly hovered item, and multiple items hovered at once.
=> #5084 mouse hover artifacts in dashboard

GitUI/CommandsDialogs/FormBrowse.cs
If the app is configured to open the most recent repository, but it no longer exists, the app will fail.
Ensure the most recent repository path is a valid working dir, and if not - show the dashboard instead.
Fixes #5515
- manual
=> fix: Open fails if recent repository doesn't exists

Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs, Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.Designer.cs, Plugins/BuildServerIntegration/AppVeyorIntegration/Settings/AppVeyorSettingsUserControl.cs
Fixes #
- Remove code that query GitHub for displaying build result of Pull Requests
now that AppVeyor provide the hash of the commit build when doing a pull request.
So everyone could see PR build result by default on opensource project \o/
(no need of GitHub token anymore!)
- AppVeyor Build result for PR are displayed:
- GIT 2.17
- Windows 10
=> AppVeyor: No more need to query GitHub to support pull requests

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Closes #5084
> Each repo in a category has a third line with a gray label (green light arrow) repeating the category name (green thick arrow)...
This is redudant, it doesn't add information and it is space consuming.
=> fix: Remove 3rd line of text in Dashboard

GitCommands/Settings/SettingsCache.cs
Fixes random lockups when rendering the revision graph. Profiling showed a lot of (waiting) time on the locks in the settingscache. During cell rendering, the setting 'ShowRevisionGridGraphColumn' is called extreme often. In some occasions this caused the application to freeze and not recover (waited few minutes). This also improves the scrolling speed a bit, when revision graph is visible.
- All the locks in the settingscache are removed
- The dictionary used for caching is replaced with a concurrent dictionary
- Profiling
- GIT 2.18
- Windows 10
=> Improved graph rendering performance by reducing locks in settingscache

GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/GitUI.csproj, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/GitItemStatusWithParent.cs
No functional changes
* Reorder `FileStatusList` members
* Extracted `GitItemStatusWithParent` into own file
* Renamed `AlwaysRevisionGroups` to `GroupByRevision`, added getter
=> Tidy FileStatusList up

GitUI/CommandsDialogs/BrowseDialog/MenuCommand.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
of the current checked out commit and the current selected revision
- Add a new navigate option that allows to find the last common ancestor between the current checked out branch and the currently selected commit.
- GIT 2.18
- Windows 10
=> Add navigate towards "last common ancestor"

GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs
Users could experience random ArgumentException exceptions, and visual artifacts in the RevisionGrid when scrolling.
It appears that under certain circumstances a rectangle for rendering refs may be of zero width or height, that would lead to the exception.
Add safe guards to prevent rendering in such cases.
Addresses https://github.com/gitextensions/gitextensions/issues/5396#issuecomment-427799141
- none, looked at writing some tests but couldn't find a meaningful way without a refactor
=> fix: ArgumentException when scrolling revision grid

GitCommands/RevisionReader.cs, GitCommands/Settings/AppSettings.cs, GitUI/GitUI.csproj, GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/GraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/Graph/GraphModel.cs, GitUI/UserControls/RevisionGrid/Graph/LaneJunctionDetail.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/UserControls/RevisionGrid/VisibleRowRange.cs
This is an experimental branch with an attempt to improve performance. It is not stable/finished yet. I mainly want to discuss the changes made so far. The code has not been cleaned, some commented code is still there. The changes where initially done in the 2.51 version, then ported to the 3.00.01 version.
For comparison the Linux repository loads in < 1 second, compared to ~10 seconds (https://github.com/torvalds/linux.git).
Fixes #
- Do not use topo-order when loading revision log. Its performance is equal to date-order and a lot slower then let git return the log in the order it is in the index.
- Remove locks in the revision graph to improve responsiveness
- Draw revisions as soon as the first commits are loaded, do not wait untill everything is …
=> Performance fixes for large repos (responsive grid during loading)

GitUI/UserControls/RevisionGrid/Columns/GraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Optimizes the code to initially select the correct selected revision. This was done after the complete revision log is loaded. This change selects the commit as soon as the commit to select is loaded. Also, it optimizes the code that searches for the fist parent of the current checkout, if the current checkout is not visible (e.g. in file history).
This Pull Request is on top of pr5473. Seperate pr, because I do not wanted to block the main performance fixes for this. Hope you like this change! On small repo's you probably won't notice any difference/
- The 'SearchRevision' function is a lot faster. In the linux repo from 6 seconds to 0.3 seconds (depending on how far it needs to search in history). This is only visible when filtering, or in the file …
=> Optimize performance of selecting current revision

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixed crash when disable artificial commit when it was selected.
To reproduce:
- Enable 'show current working directory changes as an artificial commit'
- Select this commit in the browse dialog
- Disable 'show current working directory changes as an artificial commit'
- Boom
- Add guard to not attempt to find parents of artificial commit
- I was trying to reproduce #5167
- GIT 2.19.1
- Windows 10
=> Fixed crash when disable artificial commit when it was selected.

GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
Part of #4775
- before
- after
- run with 100% and 200% scaling
=> fix: Confirmations settings layout

GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.resx
Part of #4775
- before
- after
- run with 100% and 200% scaling
=> Fix shell extensions settings layout

GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Resolve the regression introduced in #5422
The initial work is done by @mstv in 768e6457e2fb882f7a867bae18c7120d5a5fa598
This PR closes #5444
- add shortcuts (`&`) to the menu items provided by `CopyContextMenuItem`
- before
- after
- manually
=> Add shortcuts to CopyContextMenuItem

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/Editor/Diff/DiffLineInfo.cs, GitUI/Editor/Diff/DiffLineNumAnalyzer.cs, GitUI/Editor/Diff/DiffLineType.cs, GitUI/Editor/Diff/DiffLinesInfo.cs, GitUI/Editor/Diff/DiffViewerLineNumberControl.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/IFileViewer.cs, GitUI/GitUI.csproj, UnitTests/GitUITests/Editor/Diff/DiffLineNumAnalyzerFixture.cs, UnitTests/GitUITests/Editor/Diff/DiffLineNumAnalyzerTests.cs, UnitTests/GitUITests/Editor/FileViewerInternal.CurrentViewPositionCacheTests.cs, UnitTests/GitUITests/GitUITests.csproj
The initial work is done by @mstv in #5474. 
Fixes #5327, base functionality for #5328
Supersedes and closes #5474
- manual testing see checklist above
- added some integration tests for `FileViewerInternal.CurrentViewPositionCache`
- GIT 2.18.0.w.x64
- Windows 7
=> 5327 retain diff view position

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUICommands.cs
Fixes #5564
- Pass the latest selected revision to `GitUICommands.StartCreateTagDialog` when initializing `FormCreateTag` from `FormBrowse`
- Pressed Ctrl+T on commit other than current HEAD and saw commit picker have commit's hash
=> FormCreateTag should prefill commit picker with latest selected revision

GitUI/CommitInfo/CommitInfo.Designer.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs, GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Fixes #5558
- Include e-mail address in RevisionGrid Copy -> Author context menu
- Override Ctrl-c handling in Commit tab RichText areas, to only copy plain text
- Before
- After
- Manual UI testing
- GIT 2.13
- Windows 10
=> Correctly copy e-mail address with author

GitUI/Editor/FileViewerInternal.cs
Force the internal file viewer to re-render the content.
The fix is a courtesy of @NikolayXHD.
Fixes #5568
- selected commit 1792cf9
- reproduced the bug
- applied the fix
- checked that the diff is displayed correctly
=> fix: Diff viewer not redrawing correctly

GitUI/CommandsDialogs/RevisionGpgInfoControl.cs
Part of #4775 
- before
- after
- Windows 10 scale 200%
=> fix: GPG tab icons not scaled

GitUI/CommandsDialogs/FormFormatPatch.cs
git-format-patch do not handle worktree/index commits
part of #5557
- Do not show artificial commits in FormFormatPatch as they cannot be handled by git-format-patch
- Enable artificial commits
- FormBrowse, commands, Format Patch. This form is not operating on a specific revision and should open regardless of the currently selected revision.
- Artificial commands are not shown
=> FormFormatPatch: Do not show artificial commits

GitUI/CommandsDialogs/FormCommit.cs
- Fix width of branch icon in `FormCommit` status bar.
Screenshots before and after:
Here shown at 150%.
- Windows 10
=> Fix FormCommit status branch icon width at high DPI

GitUI/CommandsDialogs/FormBrowse.cs
When launched for the first time, the object tree appears very narrow.
This size was chosen as it results in the search box appearing without any clipping.
- Increase initial object tree width
- Make field readonly
- Windows 10
- 150% UI scaling
=> Increase initial object tree width

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs
Fixes:
- The object tree is rendered 3 times, causing a flicker
- The object tree was very slow to load (2 remotes/6000 branches/800 tags)
- Added beginupdate/endupdate around the rootnodes instead inside the rootnodes
- Do not set font on every node, set on tree instead
- Performance profiling with Ants
- GIT 2.19
- Windows 10
=> Performance improvements for object tree rendering

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes a crash in the odd case the log is read faster then clearing the old graphmodel
- Clear graphmodel before starting async log reader
- Analysed the call stack when the crash occurred
- Some manual testing after the change
- GIT 2.19
- Windows 10
=> Clear revisiongrid before start reading log

GitCommands/RevisionReader.cs
Fixes #5594 
- Arguments topo-order and date-order should not be applied at the same tima
- GIT 2.19
- Windows 10
=> Fixed issue #5594: Setting order revisions by date has no effect

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
Fixes #5451
Only shows tooltip "Go to superproject" if there are superproject to the current repo
- Manual test
n/a
=> Browse: Change icon for submodule menu

GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Based on follow-up discussion in #5538 I propose to change menu `Go to merge base commit` to **`Go to common ancestor (merge base)`**.
If not for fear of PR rejection, I'd loose the `(merge base)` part altogether and only mention `merge base` in the tooltip. Please consider this too. It would actually be closer to how we name menus/buttons today.
Completely agree with @drewnoakes 
> The trend among git UIs is towards making things easier and friendlier. We should be no different.
We also have quite a few labels which are friendly and clear and don't confuse neither novices nor pros.
`Undo last commit` instead of `Reset HEAD~1`
`Stage` instead of `Add`
`Unstage` instead of `Reset`
and so on..
=> Clarify "Go to merge base commit" menu option text

Setup/Build.cmd, Setup/BuildInstallers.cmd, appveyor.yml
* Separate build, test and package phases
We want to run tests before attempting to package, e.g. https://ci.appveyor.com/project/gitextensions/gitextensions/builds/19659516
* Publish msi only for release branches.
for example: https://ci.appveyor.com/project/gitextensions/gitextensions/builds/19659448/artifacts
msi doesn't get publish if a user's branch contains "release" in its name, e.g. https://ci.appveyor.com/project/gitextensions/gitextensions/builds/19659439/artifacts
=> Tweak the build script

GitUI/CommandsDialogs/FormBrowse.cs
Some updates for bare repo too
Hiding irrelevant commands
Fixes #5557
- Hide irrelevant items in the Command menu
- Artificial
- Bare repo (unchanged)
- Manual test - visual
Tests are not relevant here, 
=> FormBrowse: Command menu incorrect for artificial commits

GitCommands/RevisionReader.cs
When ordering revs by date use "topo-order" to prevent parents showing before all of their children are shown
Reverting parts of 20fada493bf8b59e9c2fe9e06710ec187abad9c4 `Revision grid should be responsive before entire graph is loaded...`
Fixes #5593
- Revert parts of optimization in 20fada493bf8b59e9c2fe9e06710ec187abad9c4 The nature of the rev-graph is such that commits must be ordered so that parents can't be shown before their children or you get weird results.
Screenshots before:
- Manual testing when ordering by date and not
- Latest master
=> When ordering is unspecified use "topo-order" to prevent parents showing before all of their children are shown

GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
Fixes #5488
- Expose chkConfirmStashDrop setting in Confirmations Settings page. It seems this was missed by a mistake.
Screenshots before:
- Created and dropped stashes with and without confirmation ON
- Tabbed through controls to verify correct tabbing order
=> Expose chkConfirmStashDrop in Confirmations Settings page

GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/IFileViewer.cs
Fixes #5618
- `Find next/previous change` must not use GoToLine() anymore.
- It must set the caret line directly.
- N/A
- GIT (2.18.0.w.x64)
- Windows 7
=> Fix #5618 FileViewer: Find next/previous change

GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/ListViewExtensions.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/UserControls/FileStatusList.cs
Fixes #3510
Purpose:
> Expected Behavior
The more desirable behavior is that the last clicked file will always be the file that is shown in the right diff view pane.
- show the focused item if it is selected
- show any other selected item otherwise
=> Show diff for last selected file

Plugins/GitUIPluginInterfaces/IGitModule.cs, Plugins/Statistics/GitStatistics/FormGitStatistics.cs
Running 'git ls-tree -z -r ' fails to return anything
Fixes #5605 
- Pass in ObjectID that represents head
Ran program and looked at line tabs
- GIT 2.19.1 and above
=> Fix #5605 Statistics plugin line stats broken

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormDiff.Designer.cs, GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs, GitUI/Translation/English.xlf, GitUI/Translation/en_pseudo.xlf
instead of "Open containing folder"
Discussion from #5523
The name were aligned to "Open containing folder" in https://github.com/gitextensions/gitextensions/pull/5523#issuecomment-427840592, some reviewers did not find that the best name. "Show in folder" (used for instance in Chrome download) was considered better.
- 
- 
- Manual test 
- Windows 10
=> Txt change: "Show in folder"

.gitattributes, .gitignore, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.MacLines.false.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.MacLines.input.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.MacLines.true.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.UnixLines.false.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.UnixLines.input.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.UnixLines.true.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.WindowsLines.false.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.WindowsLines.input.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.DoAutoCRLF_should_not_unnecessarily_duplicate_line_ending.ForScenario.WindowsLines.true.approved.txt, UnitTests/GitUITests/Editor/FileViewerTextTests.cs, UnitTests/GitUITests/Editor/MockData/MacLines.bin, UnitTests/GitUITests/Editor/MockData/UnixLines.bin, UnitTests/GitUITests/Editor/MockData/WindowsLines.bin, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/Properties/AssemblyInfo.cs
Fixes #5440
Sometimes, somehow the repository (or the text that is displayed in the UI) contains Windows line endings while AutoCRLF is set to true.
- Fix the annoying bug that sometimes line breaks are duplicated if a text is copy'pasted
- Used the test repo from the issue to reproduce the bug and made sure that the change fixes the bug
- Tried copy&paste at a repo where the bug didn't occur (the GitExtensions repo actually) - no change in behavior
- GIT 2.18.0
- Windows 10 1803 64 Bit
Questions:
- Should the fix also be applied to the 2.51 branch? If yes, what would be the best way? Cherry-pick of this commit? Who should do this?
- Is it possible to …
=> Fix duplicate CRLF when copying

GitUI/ColorHelper.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommitInfo/CommitInfo.Designer.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/CommitInfo/CommitInfo.resx, GitUI/CommitInfo/CommitInfoHeader.Designer.cs, GitUI/CommitInfo/CommitInfoHeader.cs, GitUI/CommitInfo/CommitInfoHeader.resx, GitUI/GitUI.csproj, GitUI/UserControls/BlameControl.cs, GitUI/UserControls/DoubleBufferedTableLayoutPanel.cs, ResourceManager/CommitDataRenders/CommitDataBodyRenderer.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataBodyRendererTests.cs
* Move header into own control
* Do not display commit info unless commit supplied
* Rename CommandClick event to CommandClicked
* Fixed scrolling issues
Screenshots:
* 100%
* 200%
Other layouts (at 200%):
* left:
* right:
Scrolling (at 100%):
There is a caveat, revision info may need to be reloaded after layout change.
* center:
* left:
* right:
- Windows 10 100% and 200%
=> Update commit info panel layout

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Fixes #5625 
- Include icon width when calculating tile size
- Add ellipsis when truncating branch names/repo paths
Screenshots:
Before:
After:
- Ran the tests
- Ran the linter
- GIT 2.19
- Windows 7
=> Fix bug where long branch names overflow list view

GitCommands/Git/GitModule.cs, GitCommands/RevisionReader.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDeleteBranch.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFormatPatch.cs, GitUI/CommandsDialogs/FormRemotes.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/FormSparseWorkingCopyViewModel.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ControlHotkeys.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/TextboxHotkey.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsTreeViewUserControl.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/Editor/Diff/DiffViewerLineNumberControl.cs, GitUI/Hotkey/KeysExtensions.cs, GitUI/Script/ScriptRunner.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/UserControls/WaitSpinner.cs, Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs, Plugins/Statistics/GitImpact/ImpactControl.cs, Plugins/Statistics/GitStatistics/LineCounter.cs, ResourceManager/LocalizationHelpers.cs, UnitTests/GitCommandsTests/Git/Gpg/GitGpgControllerTests.cs, UnitTests/GitCommandsTests/StringPoolTests.cs
Fixes #5604
Static analysis of code with PVS Studio.
See the issue for a discussion.
This is done with the demo license, so I am running out of clicks (how demo is licensed) and evaluation time eventually.
n/a
- Manual tests - most changes cannot be provoked though
Code review should be sufficient
Note: Similar PRs for submodules. None of those should be critical, but they decrease the noise when analyzing the solution if someone else tries out PVS Studio.
- GIT 2.19.1 and above
- Windows 10
=> Static code analysis with PVS studio

GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
If selected commit contains only in one branch, then click on menu item "Rename branch" acted like click on the one sub item
Fixes #5630
- added default action for "Rename branch" context menu item when only one branch selected
- select the branch in revision grid that has no other branches for this commit
- open context menu
- choose "Rename branch"
- the "Rename branch" dialog appears for the branch
=> Add default action for "Rename branch" context menu item when only one branch selected

GitExtUtils/BinarySearch.cs, GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/ListViewExtensions.cs, GitUI/UserControls/ExListView.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/PathFormatter.cs
Fixes #5642
- `FileStatusList` does not use `ColumnHeaderAutoResizeStyle.ColumnContent`
anymore, instead column width is determined by visible content only and
is updated on vertical scroll
- Path formatter uses binary search to choose how many characters to
truncate from path
- Tested on Windows 7
- Observed acceptable performance with linux repository with all `Truncate long filenames` settings
=> #5642 fix performance issue when selecting large diff

GitUI/CommandsDialogs/FormBrowse.cs
Fixes #5624 
- Force CommitInfo to clear on module change.
- Opened GE Repo.
- Created a new repo by using start menu in GE.
- Verified the commit info from GE did not show in the new repo.
=> Force commit info to clear on module change

GitExtensions/GitExtensions.csproj, GitExtensions/Program.cs, GitUI/GitUI.csproj, GitUI/UserEnvironmentInformation.cs, UnitTests/GitUITests/TranslationTest.cs
Prevents environment data from getting stale by a commit but GitGUI not being rebuilt
Fixes Issue noted in https://github.com/gitextensions/gitextensions/pull/5640#issuecomment-434284350
- Make GitExtensions project authority of Git info.  Any time  GitExtensions is built git info is recalculated.  
- Ran project and made sure info was still current. 
=> Make GitExtensions project authority of GIT info

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommitInfo/CommitInfo.Designer.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/CommitInfo/CommitInfoHeader.Designer.cs, GitUI/CommitInfo/CommitInfoHeader.cs, GitUI/MouseWheelRedirector.cs
Fixes not working scroll on mouse wheel in `CommitInfo` control, hhe issue was reported in #5611.
- `CommitInfoHeader` is resized to fit content. Prior to this change, scrolling `CommitInfo` horizontally to the rightmost position did not guarantee seeng the rightmost edge of `CommitInfoHeader` text
- MouseWheelRedirector skips RichTextBox with hidden Scrollbar
=> Fix commitInfo scroll on mouse wheel

GitUI/Script/ScriptRunner.cs
Fixes #5615.
Introduced new user script prefix `navigateTo:`. The script (minus the prefix) is executed normally (and synchronously). The first line of its output (if any) is used as a target revision to navigate to in the revision grid. The grid is **not** refreshed after that (it is assumed the script has no side effects).
Manual testing with various scripts (both valid and invalid).
- git version 2.19.1.windows.1
- Windows 10
=> Add script prefix for navigation in the revision grid

GitUI/CommitInfo/CommitInfo.Designer.cs
Fixes #5657
- before:
- after:
=> fix: Commit info context menu is scrambled

GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
Fixes #5633 
File now looks similar to the following:
```
19:47:37.078    85ms 13124 UI  1 git config --get ą
19:47:37.200    42ms 11044 UI  0 git --version
19:47:37.932   311ms  9568     0 git for-each-ref --sort=-committerdate refs/heads/ --format="%(objectname) %(refname)"
19:47:38.449   107ms 17280     0 git ls-files -z --unmerged
19:47:39.201    56ms 10884 UI  0 git rev-parse HEAD
19:47:39.335   185ms   932 UI  0 git rev-parse --git-common-dir
19:47:39.559    79ms 13824 UI  0 git rev-parse HEAD
19:47:39.657   458ms  6064 UI  0 git show-ref --dereference
19:47:40.276   263ms 14244     0 git for-each-ref --sort=-committerdate refs/heads/ --format="%(objectname) %(refname)"
19:47:40.335  1456ms 12420       git -c log.showSignature=false log -z …
```
=> fix: Saving command log to file broken

GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Rebuilding the graph is expensive, and is usually not needed. Minor fix. I did not refactor the cache to minimize impact of this PR.
Fixes #5658
- Split the reordering and rebuilding of the graph. (reordering is fast, rebuilding is slow)
- Because the graph rows are rebuild less often, this results in better performance while the revisions are still being loaded. There was some flickering I wanted to solve.
- GIT 2.19
- Windows 10
=> Split the reordering and rebuilding of the graph.

GitUI/CommandsDialogs/FormBrowse.cs
- Pop up a dialog that asks the user if they want to remove all X invalid repositories whenever the user agrees to removing one invalid repository from the recent repositories drop-down list
Fixes Issue #5616 
- when the user agrees to remove an invalid repository from the recent repositories drop-down list, pop up a second dialog notifying them the existence of multiple invalid repositories (if they exist).
- if multiple repositories exist, offer the user to remove all of them, in addition to the one that was originally going to be removed from the list
- Before:
- After:
followed by:
- I did interactive testing to ensure that:
- - If the user …
=> Issue 5616: Provide a way to remove all invalid recent repositories.

GitUI/CommandsDialogs/FormCommit.cs
Undo default button setting in FormCommit.
Reverting changes introduced in
* 4449536319ee86c8ceb159a61abba0c87c6274ce
* a688346a21bd0ba9f22d0294c3547703e5a2ea20
Closes #5644
=> fix: FormCommit default button

GitCommands/Git/GitRevisionTester.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #5658
- update the node cache to ensure that the quick search *gets* the revisions
- match the quick search string anywhere in the `revision.Author`
- n/a
- 9ba3f7c
- Git 2.18.0.windows.1
=> #5658 Update node cache to fix quick search

GitUI/GitExtensionsForm.cs, GitUI/WindowPositionManager.cs, UnitTests/GitUITests/GitExtensionsFormTests.cs, UnitTests/GitUITests/GitUITests.csproj
- If a user had a secondary monitor above the primary monitor, the main windows was opened on the secondary monitor, windows that persist their locations would get opened on the primary monitor.
The fix places new windows at the center of their parent.
- refactored the code so it can be tested
- added tests
- fixed the code
=> Fix incorrect v-position for parent centered windows

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Text for no common ancestors
Follow up to #5638 
- 
- 
- Manual tests
=> Text when no common ancestors assumed 2 commits

GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
This allows to specify several files/directories as filter values.
If someone has spaces in the path/file names, then the quotes must be already added in the filter dialog.
Fixes #5623 
- Removed automatic quotes around the filter value entered in the dialog.
- Makes it possible to specify not only one, but several different directories/files in the filter dialog.
- E.g. specify the following value ' "*TortoiseSVN License.txt" "*Traditional Chin*.gif" ' in filter dialog.
- GIT 2.18
- Windows 10
=> Avoid automatic quotes on FileFilter value.

GitUI/CommandsDialogs/EnvironmentInfo.cs, GitUI/CommandsDialogs/FormAbout.Designer.cs, GitUI/UserEnvironmentInformation.cs
Fixes #5666 
- Removed exception because it blocked designer
- Added default info that fakes a sha and dirty status
- Resized form to not clip with sha and dirty status
- Ran program and made sure Dirty status with a sha would not wrap which caused clipping
=> Prevent clipping of environment info

GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
- increase the contrast between the blue branch graph lanes and the selected revision row
- before
- intermediate replaced commit
- after
- just run GE
- 4f3829a 
- Git 2.18.0.windows.1
=> Increase contrast of blue branch and selected row

GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
Fixes #5673
Use `PixelOffsetMode.HighQuality`
before:
after:
Tested on Windows 7 
with 100% DPI
=> Revision graph distorted #5673

GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
Fixes #5695
- Restore Git version check in settings
- ![image](https://user-images.githubusercontent.com/6248932/47969260-36ccff80-e075-11e8-9f5b-83cf6c19b67c.png)
- 
- 
- Manual tests
- GIT 2.19.1
- Windows 10
=> Git Version check was removed from settings

GitUI/CommitInfo/CommitInfo.cs
Fixes #5707
- Include the commit message when copy commitinfo in commitinfo panel
- GIT 2.19
- Windows 10
=> Copy commit message when copy commit info is used

GitUI/CommitInfo/CommitInfo.cs
- Apply the `AppSettings.CommitFont` to `CommitInfo.rtbxCommitMessage`
Using a monospace font is quite useful for detailed commit messages in the Subversion style.
- before
- after with the default font
- after with a monospace font
- 6d5a3c66a4fc89bc41d101a1d453dbed6d7a22ab  (Dirty)
=> Apply AppSettings.CommitFont to rtbxCommitMessage

GitUI/CommandsDialogs/FormCommit.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs
- <kbd>Esc</kbd> dismisses `FormCommit` if diff view focussed
Previously, pressing <kbd>Esc</kbd> in either file list of the message box would dismiss `FormCommit`. However if focus was in the diff view, escape would not.
This commit fixes this behaviour. It also ensures if text is selected, the first keypress clears the selection, as previously happened.
This event is currently only used in FormCommit but may be useful elsewhere.
- Windows 10
=> Allow esc key in commit diff to close FormCommit

GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Fixes 5703
- Do not use collection that might be reset in another thread
- This will make future refactor a little easier
- None (could repro the issue..:( )
- GIT 2.19
- Windows 10
=> 5703: Fix System.ArgumentException when loading graph

GitUI/CommandsDialogs/FormCommit.cs
- Don't duplicate prefixes
When creating a fixup or squash commit on top of an existing `fixup!` or `squash!` commit, you could end up with doubled prefixes.
Git performs a stable reordering of commits during autosquash, so there's no need to double these prefixes.
- Windows 10
=> Prevent duplicate fixup!/squash! prefix

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
Fixes RemoteObjectTree sometimes resulting in font bolding for branch path nodes upon switching repo. 
This is what can happen:
Note that "amaiorano" should not be bolded. This happened because the previous repo's 2 root nodes had the second node bolded, not the first; upon switching to this repo, it recycled the 2nd node for the branch path "amaiorano", but left it bold. This happened because the font reset for all nodes was removed as an optimization in cd68a511068cd2c0095793d27b2f4c50efb955a6. This change brings it back, but in an optimal way.
- Tested opening different repos, and in particular the one that caused this problem to show up. …
=> Fix RemoteObjectTree branch folder nodes sometimes becoming bold

GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
Fixes a bug introduced in https://github.com/gitextensions/gitextensions/commit/c9b4e25536c8031ba761ba1d8a8c85d8157310bb
`new Executable("git")` executes git command with the GE working directory. The git command should be executed with the current repo directory. I think that Executable should always require passing to it a workingDir. It has to be verified if the mentioned commit did not introduce more regressions like this.
=> Retrieve worktrees for the current module.

GitUI/UserControls/ExListView.cs
- Reduce allocations
Allocating a Lazy<T> for every message is wasteful. There can be a _lot_ of messages passing through this `WndProc`.
- Windows 10
@NikolayXHD could you review this please?
=> Don't allocate for every Windows message

GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, UnitTests/GitCommandsTests/Git/ObjectIdTests.cs
I wanted to work on #5353. Couldn't simulate it. The current code for choosing what rows to select in the revision grid, after a refresh/commit/initial loading/etc is too complex. I attempted to clean up unused code and simplified the current code a little.
- Simplify selection code and cleanup
- Added a unit test to test == operator on ObjectId. And it works.
- No UI changes
- GIT 2.19
- Windows 10
=> Cleanup selection code

GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
Fixes null reference when hovering over a lane that continues beyond the limit of the graph. For example, see the screenprint below. The linux repo has over 600.000 commits. Its limited by default on 100.000 commits. Go to the last commit and hover over the lanes in the graph. A null reference is thrown. The application doesn't crash, the exception is eaten somewhere. Still, its better to prevent.
- Added null check
- GIT 2.19
- Windows 10
=> Fixed null reference when hovering over lane in graph

GitExtensions/Program.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUICommands.cs
Fixes #5629 
Fixes issue that was posted on Gitter. Its a minor issue, but easy to fix.
Description:
> I don't have time to open an issue, but I noticed that at current upstream/master (b4a57cf503d846553ae1b5106618b6004a1735b5), if you try to run GitExtensions.exe out of the Debug or Release folder (without passing a "browse") arg, it starts up and there's an infinite spinner in the repo graph control. If you hit F5, it refreshes and works. Quick debugging, I noticed that when this happens, we never enter the "if (keepRunning || _backgroundEvent.WaitOne(200))" branch in RevisionDataGridView.BackgroundThreadEntry.
> In fact, easy repro, just remove the "browse "E:\DATA\code\active\gitextensions\GitExtensions.."" Command line arguments in the Debug settings for GitExtensions in Visual …
=> Fixed issue that Dashboard is not shown when it should. Loading indicator keeps spinning

GitCommands/RevisionReader.cs, GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/RevisionReaderTests.cs
Fixes issue posted on gitter:
`Hey all, there's something that I've often wondered about GE. When "Show first parents" is enabled, it only seems to do what I want when "Show current branch only" (Ctrl+Shift+U) is used. Otherwise, it seems to present an odd looking graph (to me) that isn't very useful.`
Seems that 'Show first parent' only works when 'Current branch only' is also enabled. This is not user friendly.
- Make 'Show first parent' always work. Especially since the button is very prominent in the toolbar.
- Make the rendering work. It showed a strange narrow line with broken branches.
- Make the rendering not crash. The broken lines where actually branches that never stopt. Meaning: 
100.000 revisions = 100.000 lanes wide at the bottom = not …
=> Fixed issue that 'Show first parent' only works when 'Current branch only' is also enabled

GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs, UnitTests/GitUITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
Fixes #5735
- Remove the hotkey ctrl-c from the context menu. It breaks more then it fixes.
- GIT 2.19
- Windows 10
=> Copy SHA via Ctrl+C broken

GitUI/CommandsDialogs/FormBrowse.cs
Two separate implementations of the behavior
- Consistent behavior. Both refreshed the revisions/graph
- Button refreshed commit count
- F5/Menu refreshed submodule status and stash count
- n/a
- Manual test
=> Browse: Inconsistent behavior for Refresh button and F5/Repository-menu

GitUI/SpellChecker/EditNetSpell.cs, GitUI/SpellChecker/SpellCheckerHelper.cs, GitUI/SpellChecker/WordAtCursorExtractor.cs, UnitTests/GitUITests/SpellChecker/WordAtCursorExtractorTests.cs
- `EditNetSpell`, which is used e.g. for entering the commit message, marks the whole word (including underscores) on double click.
- before/after:
- added test cases
- 9fe58242d44ca3d312dd9a76ec5164b897ed073d 
=> EditNetSpell: Double click marks the whole word (including underscores)

Setup/MakePortableArchive.cmd
Fixes #5750 
- Added missing file to portable build script 
- Build portable and make sure file was in zip
=> Include missing assembly in portable build

GitUI/UserControls/FileStatusList.cs
Fixes #5744
- Renamed files with identical content keep the current icon, "Aa".
- Renamed and modified files get the modified icon(pen).
- Both LICENSE and README are renamed
- Only README is modified
Before:
After:
- Commit a 25MB large text document
- Changed one character.
- Made sure this small change still generated a non 100 similarity, it was 99
=> Differentiate rename between identical and modified

GitCommands/Settings/AppSettings.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/CommandsDialogs/FormSettings.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
Fixes #5733
- Submodule Status in the Browse submodule menu is made configurable (default off). The structure is still displayed, just not the status by default.
- Increase size of the Settings form as the lower part was already clipped. (The proper fix should be to split the page).
- 
-
-
- Manual testing on a repo with GE duplicated 3*9
- GIT 2.19
- Windows 7/10
=> submodule status configurable

GitUI/GitUI.csproj, GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs, GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs, GitUI/UserControls/RevisionGrid/Graph/LaneNodeLocator.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs, GitUI/UserControls/RevisionGrid/RevisionGridToolTipProvider.cs, ResourceManager/Strings.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneNodeLocatorTests.cs
- Factor out LaneInfoProvider and LaneNodeLocator
- Extract new interfaces IRevisionGraphRowProvider and IRevisionGraphRow
- Solve regression in LaneNodeLocator
- Show the hash for every lane, prepend "*" for the node's lane
- Make hint on not yet loaded Body translatable
- Limit tooltips to 30 lines
- Add tests
- tooltip at an head node: before
- after
- hash: before
- after
- not loaded body: before
- after
- parent not loaded: before
no tooltip
- after
- long body: before
- after
- added tests
- manual test with the Linux repo
- 4cce7856c2d5341ca8e4d0b21f4141ebdf115efe 
- Git …
=> Show correct tooltips for graph lanes

Setup/MakePortableArchive.cmd
Fixes #5500
- add missing assembly to the portable build
- verified the portable archive contains the necessary assembly
- opened the settings without observing the exception
=> Jira Commit Hint plugin can't load

GitExtensions/GitExtensions.csproj, GitExtensions/Program.cs, GitExtensions/app.manifest, GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs, GitUI/CommandsDialogs/SettingsDialog/CommonLogic.cs, ResourceManager/Strings.cs, UnitTests/GitCommandsTests/MockExecutable.cs
Fixes #5562
The settings dialog has a lot of logic to find git.exe or git.cmd. It even has a download link and an option to manually select the proper path. This code is never reached. A lot of refactoring is done that makes almost all code depend on git.exe to be set to the correct path. I did not change this existing code. Didn't remove or cleanup anything. Not sure how to handle this, but for now I wanted a solution for the 3.00 release.
I looked at the PR @RussKie did earlier and could not get this to work properly. The code is not tested on hidpi settings.
- Do not crash when git.exe is not found
- Try to locate git.exe (this is also done in the settings dialog, but this code is never reached)
- Offer a download link and manual locate button …
=> Do not crash if git.exe is not found

GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
- Flush after the process exited but keep throttling until ProcessExited is handled.
=> Show the output produced in ProcessExited event handlers.

GitExtUtils/ClipboardUtil.cs, GitExtUtils/GitExtUtils.csproj, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormReflog.cs, GitUI/CommandsDialogs/FormVerify.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/CommitInfo/CommitInfoHeader.cs, GitUI/Editor/FileViewer.cs, GitUI/UserControls/BlameControl.cs, GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserEnvironmentInformation.cs, Plugins/Bitbucket/BitbucketPullRequestForm.cs, Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.cs
Fixes #4542
- Applications can lock the clipboard, in which case `Clipboard.SetText` throws. This commit introduces `ClipboardUtil.TrySetText` which uses retry-with-wait logic in an attempt to recover from problems. If retrying N times doesn't work, it returns false rather than throwing.
- Windows 10
---
@RussKie previously asked if I could make this injectable/testable. It'd be easy to create an `IClipboardOperations` interface, but it's not clear how to make it accessible other than via a replaceable singleton. I'm open to suggestions, though anything adventurous would probably be a better fit for after 3.0.
=> Improve clipboard set-text operations

Setup/MakePortableArchive.cmd, Setup/Prepare-Release.ps1, Setup/Set-Portable.ps1, appveyor.yml
Fixes #5758
- Make Portable Build store IsPortable: True in GitExtensions.exe.config
- Ran Prepare-Release and opened zip
=> Make portable build use portable config

GitExtensions/Program.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
I've renamed and updated the wiki page to talk about the application's dependencies - https://github.com/gitextensions/gitextensions/wiki/Application-Dependencies.
The code is updated to reflect the change.
=> Update links to application dependencies wiki page

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs, GitUI/CommandsDialogs/FormBrowse.cs, README.md
Fixes #5766
- Link translations to a new wiki page
The wiki page itself should be refined, more or less just a placeholder right now
- n/a
- Manual test, code search
- Windows 10
=> Link Translations to wiki page

CommonAssemblyInfo.cs, GitUI/CommandsDialogs/EnvironmentInfo.Designer.cs, GitUI/CommandsDialogs/EnvironmentInfo.cs, GitUI/CommandsDialogs/FormAbout.Designer.cs, GitUI/CommandsDialogs/FormAbout.cs, GitUI/UserEnvironmentInformation.cs, UnitTests/GitUITests/TranslationTest.cs
Follows https://github.com/gitextensions/gitextensions/pull/5737#pullrequestreview-173691187
- Tweak environment info output
```text
- Build 22c1cfd7e (Dirty)
- .NET Framework 4.7.3190.0
```
```text
- 5b18fe38e0c12c3ca8b85bb16d2f576
- .NET Framework 4.7.3190.0
```
- GIT 2.19.1
- Windows 10
=> Tweak presentation of DPI info on the "About" form

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
=> #5764 Crash when pressing F5 while hovering item in dashboard

GitUI/CommitInfo/CommitInfo.cs
The complexity was O(n), which is not acceptable for a method
that is used to compare elements in a sorting algorithm.
The new time complexity is O(1).
=> Improve time complexity of IndexOf.

GitUI/CommandsDialogs/FormClone.cs
Fixes #5590
- use the clone command's argument as destination folder unless it describes a repo
- N/A
- Windows 7
=> Fix clone dialog doesn't pick up destination

.gitignore, Setup/Download-PluginManager.ps1, Setup/MakePortableArchive.cmd, Setup/PluginManager.wxs, Setup/Prepare-Release.ps1, Setup/Product.wxs, Setup/Setup.wixproj
This pull integrates download and inclusion of a latest PluginManager from its releases in GitHub repository.
Downloaded content is stored in Plugins\GitExtensions.PluginManager and is excluded from git.
New download is executed only when a new PluginManager release is found.
HeatDirectory build task is used for integration into Setup.wixproj.
=> Issue 4885 - Integration of PluginManager

GitUI/CommandsDialogs/FormBrowse.cs
A splitter distance below 0 is invalid and throws, and this operation is capable of resulting in less than 0.
Fixes #5806 
- Math.Max on setting splitter distance to ensure it is not invalidly below 0.
- Ran it. Looking at the test project it seemed this kind of thing is not tested for. I would be happy to add tests if you can point me in the right direction. 
- GIT 2.17
- Windows 8.1
=> Limits RevisionsSplitContainer.SplitterDistance to a min of 0

GitCommands/Git/GitModule.cs
It crashes when trying to detect git.exe, causing this code to fail.
I got a new laptop. I wanted to install gitextensions, and I failed because of this. Needed to debug to fix this. This is not acceptable for new users.
- Do not crash during auto-resolve git command. Not the best solution, but did not want to refactor gitmodule close before the release.
- Build 7931098b5468ff0bae5abed2767f47c11435c921 (Dirty)
- Git 2.19.2.windows.1
=> Add try catch around method to guess system encoding.

GitExtUtils/GitUI/ListViewExtensions.cs, GitUI/UserControls/FileStatusList.cs
Fixes #5683
Alternative for PR #5802
`ListViewItem.BoundsOrEmpty()` extension method to workaround `ArgumentException` when calling `ListViewItem.Bounds` on an item from a collapsed `ListViewGroup`
- Manually tested on Windows 7:
- select any commit in Revision grid, wait until `FileStatusList` populates the data
- collapse the top group in `FileStatusList`
- change `FileStatusList` width using splitter
=> Fix ArgumentException on collapsed file list items,

GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs, GitUI/CommandsDialogs/FormBrowse.cs
Part of #5693
- Fix link to old git-rev-parse documentation 
- Link documentation to 3.00
Note: release/3.00 must be created in GitExtensionsDoc by someone with privileges too.
(only one change compared to 2.51 documentation so far, update tracked in #5693)
- n/a
- manual
=> Links pointing to GE 2.51 documentation

GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
Fixes #4971.
Method `RevisionGraphRevision.MakeRelative` now uses a stack of revisions instead of being recursive.
Manually tried highlighting the current branch on large-ish repositories. Works instantly.
- Git 2.19.2.windows.1
=> Use stack instead of recursion in MakeRelative

GitUI/CommandsDialogs/FormCommit.cs
Fixes #5840 Crash when try open GitExtensions.settings
- Handle the exception and force "open with" dialog when can't open file with command "open"
Manual testing
- GIT 2.19
- Windows 10
=> Fix crash when open file with ".settings" extension

Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs
Fixes #5842 Crash when open Jira commit hint settings 
- Only fix crash when open project setting in Jira commit hint plugin
Before:
After:
Manual testing
- GIT 2.19
=> Fix crash when open project setting in Jira commit hint plugin

GitCommands/RevisionReader.cs
by adding the name of the branch in the `git log` command arguments
that was accidentally removed during the refactoring to use ArgumentBuilder
fix #5278
Original code (notice the `{2}`):
https://github.com/gitextensions/gitextensions/blob/cd45f12f6356ae4127b962a91b8d6fc45885a32f/GitCommands/RevisionGraph.cs#L195
PS: @RussKie  with the release to come, I don't know if this fix should be done in master or release/3.00
=> fix filter branch filter

GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
Fixes #5853
- Avoid recursion to fix stackoverflow
- GIT 2.19.1
- Windows 10
=> Use stack instead of recursion in EnsureScoreIsAbove

GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
Fixes endless loop in the linux repo. The method is not entered very often, so it should hurt performance. 
- Added guard for EnsureScoreIsAbove. It happens that the same revision has multiple Children. This could cause an endless loop. Happens in the linux repo
- GIT 2.19.2
- Windows 10
=> Added guard for EnsureScoreIsAbove.

GitUI/CommitInfo/CommitInfo.Designer.cs
Fixes  #5870
- Set `rtbxCommitMessage.ReadOnly` to `true`
No visual change.
- Manually tested the commit info tab in the main view.
- Manually tested the commit message in the diff window.
- Windows 1809
I separated this into two commits. The real change happens in the second one.
=> Fix non-readonly commit message

CommonAssemblyInfo.cs, CommonAssemblyInfoExternals.cs, GitExtSshAskPass/SshAskPass.rc2, GitExtensionsShellEx/GitExtensionsShellEx.rc, GitExtensionsVSIX/source.extension.vsixmanifest, Setup/MakeInstallers.cmd
- Update version to AppVeyor release builds, so manual builds matches the release
Note: master should be updated with a 3.01.00.0 version, no merge
- n/a
- n/a
=> Update release version to AppVeyor release build

GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs
Fixes #5880
- Make EnsureScoreIsAbove method not rely on order of execution
- Do not solely rely on maxscore, since it drivers the score up fast, overflowing int32
- Extended existing unit test
- No manual testing done
- GIT 2.19.1
- Windows 10
=> Fixes 5880: Reorder nodes correct

GitUI/Avatars/AvatarDownloader.cs, GitUI/UserControls/AvatarControl.cs, Plugins/Gource/GourceStart.cs
Fixes #5859.
Follows and replaces #5868.
- `WebClient.OpenReadTaskAsync` can block synchronously, so move calls to thread pool
- Limit number of concurrent downloads to prevent thread pool exhaustion.
- Manual testing, and the UI does seem more responsive during scrolling after clearing the avatar cache.
- Windows 10
=> Avoid blocking UI via WebClient.OpenReadTaskAsync

CommonAssemblyInfo.cs, CommonAssemblyInfoExternals.cs, GitExtSshAskPass/SshAskPass.rc2, GitExtensionsShellEx/GitExtensionsShellEx.rc, GitExtensionsVSIX/source.extension.vsixmanifest, Setup/MakeInstallers.cmd, appveyor.yml
- Clarify that master is used for next feature release (critical issues off the release/3.00 branch). Set version higher than in release
- n/a
- n/a 
=> Update build version 2.99.90 -> 3.01.00.0

CommonAssemblyInfo.cs, CommonAssemblyInfoExternals.cs, GitExtensionsVSIX/source.extension.vsixmanifest, Setup/MakeInstallers.cmd
fixup for #5881  ca8cda58f070c300ff0c082d881e2d53dc246e76
- Changes was done with editor which removed file format
=> Correct version number format changes

GitUI/CommandsDialogs/FormBrowse.cs, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
Plugins were sorted in Settings (in 3.0) but not in the Plugins menu.
Jira plugin was not init correctly (name was not set).
- before
- after
- Manual test
=> Browse: Sort the Plugin list in alphabetic order

GitExtensions.settings
- detect GH issues without `#`, especially in branch names, e.g.
- feature/98765
- feat-98765
- fix/98765
- fix_98765
- before:
- after:
- Build 876903cf464aebd11d09a01a9849ea87043d4803
=> Revision Links: Detect GH issues without #

GitUI/CommandsDialogs/FormGitIgnore.Designer.cs
- Help text is not wrapped
Removing WordWrap sets the default to true, as for similar controls.
- before
- after
- Open the form
=> Help text for Edit .gitignore not wrapped

Plugins/Statistics/GitStatistics/CodeFile.cs
-  Adds assembly style comments calculation in files with extensions .asm, .s and .inc.
-  Change is small and follows the rest of the code. Built and tested manually on my repository to make sure it works.
=> Plugin GitStatistics: Added calculation of comment lines for assembler files

GitCommands/Logging/CommandLog.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, GitUI/CommandsDialogs/FormBrowse.cs
Part of #5733
- Command logging tweaks
Part of logging other info, currently cut from the PR but helping me to analyze
- Delay commit-count initiation when switching repo (from 0-100ms to 200-300ms)
- Delay stash-count initiation from directly to 500 ms
- Delay calculating submodule structure from directly to 100 ms
Delays are introduced to at least start the GUI related before the background jobs. They could (at least the stash count) be started after GUI is updated.
Moved the following to #5756 
~~- Removed dynamic calculation of submodule status. (Temporary hack, commenting out).
This requires a large number of git commands, delaying other commands. This should not cause the GUI to hang, there is likely some resource conflict too. (Discussions in …
=> Browse: Delay status updates when opening/refreshing repos

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormReflog.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5812
- Avoid exception when comparing
- 
-
- 
- Manual tests
=> NullException comparing when no HEAD

GitUI/GitUI.csproj, GitUI/Script/ScriptOptionsParser.cs, GitUI/Script/ScriptRunner.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
`{cDefaultRemotePathFromUrl}` script variable now resolves correctly.
Fixes #5932
Also added tests for script options parser
* Extract script options parser into a separate class
* Extract the actual option reslution into a separate method
* Add tests confirming the correct resolution of `{cDefaultRemotePathFromUrl}` script option
NB: I will cherrypick only the first commit on to v3.0.1 branch.
=> Fix incorrect resolution of {cDefaultRemotePathFromUrl} script variable

GitUI/CommandsDialogs/FormBrowse.cs
Fixes #5916
- populate console tab after translation
- assign console tab to own field
- register image via standard approach
- Windows 10
=> Console tab doesn't require translation strings

GitUI/UserControls/PatchGrid.cs
Fixes #
#5959
- Use 0-based index for FirstDisplayedScrollingRowIndex instead of 1-based in accordance with the [specification](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridview.firstdisplayedscrollingrowindex?view=netframework-4.6.1).
=> Fix scrolling index in PatchGrid for one skipped patch

GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/Win32ApiUtil.cs, GitUI/MouseWheelRedirector.cs, GitUI/UserControls/ExListView.cs, UnitTests/GitExtUtils/GitExtUtilsTests.csproj, UnitTests/GitExtUtils/Win32ApiTests.cs
Fixes #5621
Convert `LParam` to `Point` in a more robust way, which supports negative `y` coordinate.
Use the new approach in `ICSharpCode.TextEditor` project as well for consistency.
- Added UnitTests verifying the correctness of both `ToPoint` extension method copies, one for all `gitextensions` projects, another one for `ICShaprCode.TextEditor` project.
- Tested scrolling by mouse wheel, especially near control boundaries.
=> fix OverflowException on mousewheel with negative Cursor.Y

GitCommands/Settings/AppSettings.cs, GitUI/Editor/FileViewerInternal.Designer.cs
This reenables the vertical ruler introduced in #4095 (2.51) by @freza-tm, disabled in #5087 (3.00) 3871f6bcaebe4289cee3541eacf59a5544c9f9a1 by @drewnoakes 
#5927 proposed to remove the dead code as 2.51 (also in the documentation).
This PR changes the defaults to 0 instead, so it is not visible by default.
- Reenable the vertical ruler with default 0
If enabled
- Manual test
=> Reenable vertical ruler

GitUI/BranchTreePanel/RepoObjectsTree.cs
Fixes #5907 
Disable treeview scrolling during refresh when EnsureVisible is called by setting treeview as not scrollable. This is kind of a hack, but I found this as only way to prevent horizontal scrolling without using P/Invoke.
-before 
-after
- Windows 10
=> Prevent treeview scrolling during reload

GitUI/CommandsDialogs/FormCommit.cs, GitUI/Editor/FileViewer.cs
addendum to PR #4848 for issue #4500
- Commit Dialog: handle the hotkey F3 for image file (.png), too
- before *and* after
=> Implement F3 to open difftool for .png

GitUI/CommandsDialogs/FormBrowse.cs
- QuickPull shortcut action should behave the same way as the toolbar button. 
- Look at surrounding code. 
- GIT 2.20
- Windows 10
=> QuickPull should behave the same as the default toolbar does.

GitUI/CommandsDialogs/FormStash.cs
Fixes #5958
- close the dialog on Escape keypress unless some text is selected or a combobox is dropped down
- do the DPI scaling in the default constructor, too
It does not work without KeyPreview = true. Though the modal Form must not react on Escape itself. It would close it too early. That's why ComboBoxes must be handled manually. (It was no fun to find a working solution.)
N/A
- Build 136697dee2cd176894ebf0f2a09835608aa950fc
=> Close the Stash Manager on Esc keypress

GitUI/CommandsDialogs/FormBrowse.cs, Setup/set_version_to.py, appveyor.yml
Point to 'master' for the doc subrepo
For the doc link in the app (FormBrowse), point to 'master' build of the doc repo
Update set_version_to.py to set the doc version link in FormBrowse, so it is not forgotten
Note: When merging release branches or running set_version_to.py on master, the explicit 'master' pointer will be lost.
This should not be critical
Closes #5693 
- n/a
- no code changes
=> GitExtensionsDoc for 3.00

GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/UserControls/BlameControl.cs, GitUI/UserControls/CommitDiff.cs
Fixes #5957
- handle Esc in all FileViewers of FormFileHistory, too, to close the window
- add event EscapePressed to BlameControl and CommitDiff
- avoid NRE in ICSharpCode.TextEditor on close
N/A
- Build b78af86a6d0fbe08ec677308ca35a8fbf986ebd5
=> Handle Esc in all FileViewers of FormFileHistory to close the window

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
Fixes #5984
Fix empty commit detail and exception when reseting to a remote branch, complaining about the Commit Date < min UTC DateTime
- Tried to reset to the remote branch, the information now shows correctly
=> Fix empty commit detail and exception when reseting to a remote branch, complaining about the Commit Date < min UTC DateTime

appveyor.yml
The original script was searching for test assemblies located at a depth of one level under UnitTests folder.
Plugin-related tests are located at two levels deep and thus weren't picked up by the build pipeline.
=> Add missing test assemblies

GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.Designer.cs
Fixes tab order of Add Submodule form
* I think from left to right, from top to bottom should be the standard tab order
=> Fix tab order of Add Submodule form

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs, GitUI/UserControls/RevisionGrid/AuthorRevisionHighlighting.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/UserControls/AuthorRevisionHighlightingTests.cs
Closes #5197
- Restore highlighting by author changed/removed as part of #5087. Currently instead of highlighting the whole commit row, only author's name is rendered in bold.
- Restore configuration
- Add highlight colour configuration
- Add tests
- manual
- added few unit tests
NB: I don't think it should have a significant effect on performance, however I haven't test it.
=> Fix 5197 highlight by author

GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
This is a follow up to #5747 after discussions with @amaiorano 
This is part 1 of #5769 - should maybe be considered for 3.0
This is based on #5747 minus last commit, submitted for @amaiorano to give feedback
SubmoduleStatus: Update only when commit-count reports changes to submodules
Update submodule status at changes directly (async)
when changes detected, do not wait for dropdown or form reactivation
Submodule status setting is now dependent on the status updates
There are two special cases:
* If submodule status changes to None, the status must be cleared
* Changes are only triggered on submodule changes, supermodule changes are not detected, If a module has supermodules, the status is always calculated when opening the module (but not triggered …
=> only update submodule status at changes

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
Removed in #5087 
Not sure what the setting really did, but it was separate from "Hilight authored revisions" and "Draw alternate background"
- Remove unused setting
Doc separate cleanup
Should be included in 3.0.1 too
- compile
=> Remove unused setting "Striped branch change"

GitCommands/CommitDataManager.cs
Fixes #5873
Add a check for parsing information for submodules in Diff (Commit or RevisionDiff)
Check if parent is not null or empty before parsing.
Parent will be null if a submodule is new and the submodule has no history
See test case in the issue
- GIT 2.20.1
=> Diff window exception when adding a submodule without history

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Seen in #5873
If navigating to current revision (Ctrl-Shift-C) and there is no current revision, GE will fail with an exception
Manual
Create a new orphan branch, then Ctrl-Shift-C
=> Exception if no current checkout when selecting current revision

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Part of #5769
Run some Git commands with less importance with --no-optional-locks, to avoid they lock out commands important for interactivity.
This includes:
- Sub submodule status (in submodule menu)
- stash count (in Browse)
- superproject tag/branch info (in revision grid)
- branch menu dropdown
- side panel dropdown
When "--no-optional-locks" was added, only git-status was improved, but further commands could be improved eventually.
The intention with the change is to decrease "random" lockups, it is not expected that noticeable changes are seen also if i.e. git-diff has been implemented.
Manual for functionality (no changes)
Added command output format tests
=> use --no-optional-locks for submodule status and stash list

GitExtUtils/GitExtUtils.csproj, GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs, GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs, GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Concurrent collections are optimized for a small number of collections with a large number of accessors. The collections are often large, so higher fixed collection overhead is acceptable to improve performance at scale.
The RevisionGraph has a different pattern: a large number of small collections with read operations dominating. The concurrent collections are replaced with immutable collections chosen to optimize the primary use cases.
=> Replace ConcurrentBag in RevisionGraph

GitCommands/Git/GitCommandHelpers.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
fix custom stash message broken
Fixes #6016 
- code kindly provided by Jay Asbury, user vbjay
stash custom message broken
not broken, and added a check for empty message
- I didn't write any tests
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Microsoft Windows NT 10.0.15063.0
=> Fix broken custom stash message

GitCommands/ArgumentBuilderExtensions.cs, GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs, GitUI/CommandsDialogs/FormCleanupRepository.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/GitUICommands.cs, GitUI/HelperDialogs/FormResetCurrentBranch.cs, Plugins/Gerrit/FormGerritDownload.cs, UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes #5937
closes #5849
This includes #6001 (require the changes there, the discussions were mixed up anyway)
- Refactor Reset arguments, use mode instead of separate arguments 
- Resolve #5937 by using git-reset instead of internal handling (similar change in FormCommit in 2012 or so).
- Simplified usage and tests for the refactoring 
- Manual tests for delete
- GIT 2.20.1
=> Submodule reset: Delete new files

GitUI/UserControls/RevisionGrid/Graph/LaneInfoProvider.cs, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/LaneInfoProviderTests.cs
Fixes #5125.
Fixes #4450.
Supersedes #5436 (adapted to new Revision Graph model).
- Show nearest branch in tooltip of Revision Graph
- before
- after
- Add NUnit tests
- 15258628f2415e635a998f32489bb44b9759b258 
- DPI X:100,00% Y:100,00%
=> #5125 RevisionGrid Graph: Nearest branch in tooltip

GitCommands/Git/GitVersion.cs, GitUI/CommandsDialogs/FormClone.cs
Fixes #5905 
Closes #5972
- Hide lfs-clone if the option is depreciated
Also solves layout in i.e. Russian
- Open dialog and check that the correct option appears
- GIT 2.20.1
=> Hide depreciated lfs-clone option

GitCommands/Git/GitModule.cs, GitCommands/Git/GitRevision.cs, GitCommands/RevisionReader.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5653
GE supports adding Git Notes in the commit info view, shown as a part of 
In 2.x GE always fetched CommitInfo separately for each commit.
In 3.0 the full commit message is saved for commits newer than 6 months and information if multiline existed is stored with each commit. Git Notes is not fetched at this stage.
Git Notes were therefore just shown for multiline messages older than six months.
This PR will fetch the Git Notes if not done already for each commit similar to 2.x.
Manual
=> Git Notes not displayed in Commit info

GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
No issue - seen when refreshing the documentation
- Link to Help changed in 3.0.0 documentation
- Form background inconsitent to others
The darker line is the divisor, usually kept dark.
Manual
=> revision link fixes

GitUI/CommitInfo/CommitInfo.cs, GitUI/CommitInfo/CommitInfoHeader.cs, GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
Fixes #6045
- restore symmetry, i.e. do not touch `rtb.HideSelection` at all
- invalidate RichTextBox after `EndUpdate`
- assign context menu to CommitInfoHeader, too
- Build 4d1f476ec202a5a2ee08ce4a96b5bb3daf83a05f
=> Fix copying RichTextBox text and restore context menu for CommitInfoHeader

GitExtUtils/GitUI/ControlHotkeyExtensions.cs
Fixes #6029
Handle missing `Ctrl`+`Backspace` hotkey by emulating `Ctrl`+`Shift`+`Left`, `Backspace` key sequence.
This approach works fine for both single-line and multiline textbox.
There is a  visual downside, one can see how the word becomes selected and then removed one moment after.
Manually tested by editing multiline & single-line inputs in commit template window.
Windows 7 SP1
=> #6029 fix broken multiline textboxes

GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
This ensures that Pageant is started automatically, if desired, etc.
Fixes #6047
- Generated SSH key with Putty, added to my GitHub, etc.
- Setup my remote to use SSH, and to auto-launch Pageant with private key file
- Closed Pageant, then fetched using the left panel remote node, making sure it works like when fetching from the toolbar.
- GIT 2.19.1.windows.1
- Windows 10
=> Make left panel remote fetch use the same function as FormBrowse

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs, GitUI/CommandsDialogs/FormBrowse.cs, Plugins/Gerrit/FormGitReview.cs, Plugins/Gerrit/FormPluginInformation.cs
Closes #6075
- Direct users to GH issues page where they can click "New Issue" button.
This is necessary to simplify our management of issue and feature templates that are no provided via a new link such as: `https://github.com/gitextensions/gitextensions/issues/new/choose`
=> Fix 6075 update gh issues link

GitUI/CommandsDialogs/FormBrowse.cs
bug fix for PR #6020
- do not enter the GitStatusMonitor's state Running in the constructor -- as before PR #6020 -- to avoid an ArgumentException which was thrown under some conditions (reported in [#6005](https://github.com/gitextensions/gitextensions/pull/6005#issuecomment-452557155))
- manual testing, thanks to @vbjay
- Build 5da362915f3b82abfbf18c67fbc32c5ffd6ccb21
=> Fix possible ArgumentException on startup

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/CommandsDialogs/FormDeleteBranch.cs
FormDeleteBranch expects a space-separated list of branches, not comma-separated.
Also opportunistically modified call to UICommands.StartDeleteBranchDialog to use overload that takes a single branch.
Fixes #6068
- Made sure Delete All, then Delete and Select multiple branches functionality in FormDeleteBranch work as expected.
- GIT 2.19.1.windows.1
- Windows 10
=> Fix "Delete all" context action on branch folder in left panel

GitUI/CommitInfo/CommitInfo.Designer.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs, UnitTests/GitUITests/Editor/RichTextBoxXhtmlSupportExtensionTests.cs, UnitTests/GitUITests/GitUITests.csproj
Fixes #6088
- add a context menu item `Copy link` to the Commit Info which copies the link under the mouse to the Clipboard
- add shortcuts to other menu items which trigger actions
- remove the unused function and its overload `RichTextBoxXhtmlSupportExtension.AddLink()`
- NUnit test for `RichTextBoxXhtmlSupportExtension.GetLink()`
- Build 6c16ec5a9a04632859ec2d1f882f36eb9bce5959
=> Add context menu item "Copy link" to Commit Info

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormFileHistory.resx
Fixes #6066
- Convert ToolStripButton 'Show Full History' to the dropdown button with two flags: show full history and simplify merges.
- Add 'Simplify Merges' button to the context menu
- Add 'SimplifyMergesInFileHistory' property to the settings
- Manual test on the test repository
- Manual test on the internal repository
- Manual test on the GitExtensions repository
GIT version:	2.19.1.windows.1
OS Name:	Microsoft Windows 10 Pro
Version:		10.0.17134 Build 17134
Scaling: 		96 DPI (no scaling, 100%)
=> Allow toggle 'simplify-merges'

GitCommands/Git/GitModule.cs
Fixes #5804
FormFileHistory and FormCommitDiff Displayed "Notes:" also when there were none due to a newline being added to the git-log output.
Manual
Double-click in the revision graph or check file history
=> Avoid adding newline at the end of formatted output

GitCommands/Git/GitVersion.cs
Fixes #6038
Update the recommended Git version 2.19.1 -> 2.20.1
2.21 just released (not git-for-windows yet), not many changes there
Usage of Git since release 21 days ago (and 2.10 before that).
No major changes in 2.20
- GIT 2.20.1
=> Update Git recommended version to 2.20.1

GitUI/CommandsDialogs/FormPush.cs
Fixes #4853 
- Populate remotes combobox in Push dialog after user modified available remotes
Manual testing
- Build 4695d0e12c5ba1697b7901eed0e82691e18a7517 (Dirty)
=> FormPush: populate available remotes on changes

GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Part of #6076
AutoComplete (in at least FormCommit) uses git-status to get changed files for suggestions. This call must not lock the git-status call to get differences or any manipulations to the index (stage, unstage, refresh, commit).
Git-status can take several seconds for big repos.
Git Command Log, add stacktrace
Open FormCommit, close
Verify that one of the calls (normally the second) to git-status:
```
git --no-optional-locks status --porcelain=2 -z --untracked-files --ignore-submodules=none
```
contains
```
vid GitUI.AutoCompletion.CommitAutoCompleteProvider.<GetAutoCompleteWordsAsync>d__3.MoveNext()
```
=> AutoCompleteWord git-status must not lock git

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Refresh revision grid when superproject branch/tag is completed
(cherry picked from commit 1c1359cfd29c841c3bf278224877b529bc7c6da9)
see #5981
=> #5981 superproject-refs for 3.0

GitUI/UserControls/ExListView.cs, GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Fixes #5917
Turns out the problem was caused by setting `Dock.Fill` to `ListView` control.
After figuring that out there is no need in hack with resizing column after a small delay.
Manual
Windows 7 SP1
=> Solved column size problem in FileStatusList

GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/HighDpiMouseCursors.cs, GitExtensions/Program.cs
Relates to #4775.
- Replace some 96-dpi .cur files provided by the framework with high-DPI system cursors
Full disclaimer: this uses private reflection, which is generally a no-no, but in doing so it catches any exception and continues with no negative effects that I can see.
An equivalent change is being made to dotnet/winforms, but until we move to .NET Core we are stuck with this approach.
- Windows 10
- UI Scaling: 150%
=> Use high DPI mouse cursors

GitCommands/Remotes/GitRemoteManager.cs, GitUI/CommandsDialogs/FormRemotes.cs, UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs, UnitTests/GitCommandsTests/Remote/GitRemoteManagerTests.cs
Discovered while adding UI tests in #6100
Use case:
- a user has added a remote
- then deactivated the remote via GE
- then added a remote with the same name from a command line or via UI
- then attempted to deactivate the new remote
Application then crash with:
System.ArgumentException : Can not add a section that already exists: -remote
at GitCommands.Config.ConfigFile.AddConfigSection(IConfigSection configSection) in C:\Development\gitextensions\GitCommands\Config\ConfigFile.cs:line 253
at GitCommands.Settings.ConfigFileSettingsCache.<>c__DisplayClass9_0.<AddConfigSection>b__0() in C:\Development\gitextensions\GitCommands\Settings\ConfigFileSettingsCache.cs:line 79
at GitCommands.SettingsCache.<>c__DisplayClass3_0.<LockedAction>b__0() in …
=> Fix AE: Can not add a section that already exists: -remote

contributors.txt
- sign off
- remove trailing whitespace (automatically by my editor)
=> Signed off the project's Contributors Certification of Origin and Rights

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, contributors.txt
"Show relative date", "Show author date", and "Show remote branches"
in the View menu are now correctly checked or unchecked when they are
toggled.
Fixes #6086
Add MenuCommands.TriggerMenuChanged() call to procedures ToggleShowAuthorDate, ToggleShowRemoteBranches, and ToggleShowRelativeDate.
- Observe that the View menu status for options "Show remote branches", "Show author date",  and "Show relative date" have toggled after clicking them and then returning to the View menu. 
- Confirm that the displayed status of the View menu option matches the current display in the main view (e.g., if "Show relative date" is checked, relative dates are being shown.)
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
- Microsoft Windows NT …
=> Update View menu items when toggled

UnitTests/GitExtUtils/Win32ApiTests.cs, contributors.txt
Fix faling Win32ApiTests tests when run against x86 platform, issue was discovered
and reported https://github.com/gitextensions/gitextensions/pull/6111#issuecomment-456175161 by @vbjay 
- Windows 7 SP1
Win32Api tests were successfully run against x86 and x64 platforms
=> fix Win32ApiTests against x86 platform

GitUI/CommandsDialogs/FormCommit.cs, ResourceManager/GitExtensionsFormBase.cs, ResourceManager/NativeMethods.cs, ResourceManager/ResourceManager.csproj
Fixes #6076
- avoid refresh after own pop-ups in Commit dialog by refreshing only on `Application.Activate` instead of on `Form.Activate`
- Build 67643416568784aa1f59e14864b64b8a7335ec30
=> Fix reset selected lines

GitUI/CommandsDialogs/FormPull.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormPullTests.cs, contributors.txt
Fixes #6144
- It should treat `AppSettings.PullAction.None` as `AppSettings.DefaultPullAction` instead of `AppSettings.PullAction.Fetch`.
Reason: https://github.com/gitextensions/gitextensions/blob/1be9b2a4c1a84d33ae011705b9b1076465696ee3/GitUI/GitUICommands.cs#L1716
https://github.com/gitextensions/gitextensions/blob/1be9b2a4c1a84d33ae011705b9b1076465696ee3/GitUI/GitUICommands.cs#L1736-L1757
When there's args for pull passed in the command, the default pull action is changed.
https://github.com/gitextensions/gitextensions/blob/1be9b2a4c1a84d33ae011705b9b1076465696ee3/GitUI/GitUICommands.cs#L1732
https://github.com/gitextensions/gitextensions/blob/1be9b2a4c1a84d33ae011705b9b1076465696ee3/GitUI/GitUICommands.cs#L493
But it opens the window with `pullAction` parameter default value to …
=> Fix #6144, it should treat none as default.

GitUI/CommandsDialogs/FormBrowse.cs
Fix a regression of #6020
- create the Task Bar Jump List in the constructor already in order to the use initial Commit icon there
- Build 5a313988bf4ab8e0c37bdf1f2c658c9469e1e257
=> Restore green Commit icon in Task Bar Jump List

GitCommands/PathUtil.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormFileHistoryController.cs, GitUI/GitUI.csproj, GitUI/Native.cs, UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs, UnitTests/GitUITests/CommandsDialogs/FormFileHistoryControllerTests.cs, UnitTests/GitUITests/GitUITests.csproj
Fixes #5963
- Use native methods (from FileHistory code) to find proper casing for path.
- The method is not used for recentrepositories. This PR only merges the 2 existing methods for resolving path casing.
- Unit tests
- No manual testing done
- Git Extensions 3.00.00.4429
- Build c15bad2784fbfc0261427b371fda07348acc52c5
- Git 2.19.2.windows.1
=> Use native methods instead of recursion for resolving correct path casing

Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj
due to a bad version of "Newtonsoft.Json"
PS: the binding redirect was already there
Fixes https://github.com/gitextensions/gitextensions/issues/6140#issuecomment-456101158
Other projects use v10.0.3 and a dependency of "TfsInterop.Vs2015" use
a v8 that could end up in the output directory.
So the plugins fails to load because can find "Newtonsoft.Json" in v10
When building locally (and perhaps on AppVeyor ?), sometimes, the plugins requiring "Newtonsoft.Json" as dependency failed to load
The plugins could load.
=> Fix loading of some plugins that failed

GitCommands/Settings/RepoDistSettings.cs, GitUI/CommandsDialogs/BuildReportTabPageExtension.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs, contributors.txt
Fixes #6063 Introduce option to disable build result tab
- In Tools/Options/Build server integration add new option "Show build result page". By default this option enabled. If you disable this option the build results tab will not be loaded. These changes affect the main window and the history window.
-  Manual testing
- GIT 2.20.1 
=> Introduce option to disable build result tab #6063

GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Fixes #6149
Manually update `ListView.Top` to emulate `Dock.Fill` with present `Dock.Top` siblings.
- visually inspected Diff tab in `FormBrowse`'s bottom panel to make sure `ListView` is still correctly laid out below the filter.
- visually inspected commit form to make sure `ListView` takes all available height when filter is invisible.
- Windows 7 SP1
=> fix FileStatusList layout after replacing Dock.Fill by Anchor

GitCommands/Git/AheadBehindDataProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs, GitUI/CommandsDialogs/ToolStripPushButton.cs, UnitTests/GitUITests/UserControls/ToolStripPushButtonTests.cs
Moved ownership of the AheadBehindDataProvider to BranchTree, which represents the "Branches" top node in the panel. Also allows us to avoid having to recurse the entire tree to update the AheadBehind string as we now set it as soon as we construct the BranchTree node.
- This refactors some code introduced in https://github.com/gitextensions/gitextensions/pull/5994 recently.
- This localizes the AheadBehind code to the right place for the left panel, and allows us to optimize the setting of the AheadBehind string, as described in the commit comment.
- This also simplifies the rework I have to do in my left panel pubsub change (https://github.com/gitextensions/gitextensions/pull/5669)
- Although I didn't change any of that code, I made sure the AheadBehind unit and integration tests still …
=> Refactor and optimize AheadBehind code in left panel

GitCommands/CommitTemplateManager.cs, UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs
Fixes #
- Jira commit templates may be ordered by JQL and this sorting have to be saved on UI. ConcurrentDictionary is not ordered class and must not be used to store ordered data.
Incorrect sorting (have to be ordered by updateDate)
Sorting fixed
- Setup Jira plugin with sorting
- Open commit form and template popup
- Templates are ordered
- Close commit form
- Open commit form again and check templates
- GIT 
- Windows 
----
=> Fix sorting of commit templates.

GitUI/CommandsDialogs/FormCommit.cs, GitUI/Editor/FileViewer.cs, GitUI/Hotkey/HotkeySettingsManager.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Fixes #6115
- add a context menu item to the Commit dialog's FileViewer in order to
copy the selected text directly to the current position of the commit message (without using the clipboard).
- add the hotkey `C` for this function which is only available when the FileViewer has the focus
- added NUnit tests for the function `AddSelectionToCommitMessage()`
- Build 7c93bcc80237e9fde6bf5f87267a06a8606bd21b
=> Copy selected diff text to commit message

GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.Designer.cs
- The panel could grow depending on its content
We can't see all the fields, just the first one:
We could see all the fields :
- Launching GE and using my own eyes 😉 
- Build 5ec1507ab077027c3508f4429d8d7e0e2210839d (Dirty)
----
=> fix build server settings page that could be clipped

GitUI/CommandsDialogs/FormCommit.cs, UnitTests/CommonTestUtils/GitModuleTestHelper.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
The regression is caused by changes in #6134
Fixes #6201
- manual
- unit tests
/cc: @pmiossec could you confirm the fix please
----
=> FormCommit no longer show the committer info

GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Fixes #6210
- Support nodes in the graph that do not have parent or child.
- Unit test
- Git Extensions 3.00.00.4433
- Build 3fb70f85257aa59bf35537d079e51605d5e1077d (Dirty)
=> Fixes 6210: support single detached commits without segment

GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Fixes #6193 
- Add bounds checking
- Unit test
- No manual testing, since I cannot simulate in UI
=> Fixes 6193: ArgumentOutOfRangeException could occur in graph

GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Fixes #
- whenever a context menu would get opened, the item that was right clicked would lose the highlighting. This PR addresses the issue
- manually
----
=> fix missing dashboard highlighting on right click

GitCommands/Submodules/SubmoduleInfoResult.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/CommandsDialogs/FormBrowse.cs, UnitTests/CommonTestUtils/GitModuleTestHelper.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
Prior to this change, SubmoduleStatusProvider would only set TopProject if current module's SuperProject was not the TopProject. In other words, when the current module was at least 2 submodules deep from the top module. With this change, we always set the TopProject to the top module. This means that SuperProject == TopProject when current module is 1 submodule deep from the top module. This change makes it easier to retrieve the top project when needed at no extra runtime cost.
This change is extracted from my left panel submodules work. In particular, I need this so that I can always display the top module in the left pane. I figured it would be better to introduce this as a small change separately. I'm simply changing the API contract on the SubmoduleInfoResult that the …
=> SubmoduleStatusProvider always sets TopProject

GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Somewhat related to #5433 (which I still cannot reproduce)
Very few commands of FormBrowse have shortcuts assigned in the designer, i.e. which cannot be altered using the Hotkey manager.
Display their shortcuts in the context menu, too. 
(I *copied* them from the `FormBrowse.Designer.cs` to the `RevisionGridControl.Designer.cs`. Else these private context menu items needed to be made accessible for FormBrowse.)
- manual
- Build c84fffcb6f94c07130974152fa472a94b2312f25
----
=> Show fixed shortcuts in context menu, too

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUICommands.cs, GitUI/Plugin/PluginRegistry.cs, TranslationApp/Program.cs
This is WIP on #3320.
I need plugins to be registered even when GitExtensions are started with arguments to start other dialog than browse.
If this approach is ok, I will extend this PR also for other dialogs.
Yet I'm considering moving original plugin registration from FormBrowse into GitUICommands and let only menu items binding there. Thoughts?
=> Issue 3320 - Plugin registration phase

GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
Fixes #5786
- standardize revision grid context menu:
- "*this* commit"
- "Create branch/tag *here...*"
- "commit" instead of "revision"
- add ellipsis "..." where a dialog will be opened
- move "Compare" below "Create/Delete tag...", right above "Navigate"
- Build aa2e8fc3e20a340b9a1e366dde127dcb537ff9e4
----
=> Standardize revision grid context menu

GitUI/CommandsDialogs/FormCommit.cs
Fixes #4826 (partially)
- - The `SelectedDiff` is not cleared immediately when user hits `DEL`, but only if the confirmation dialog is actually confirmed (fixes reproduction method 2)
- ran unit tests
- Git Extensions 3.00.00.4433
- Build fca7cf228b481ee8c1b779cf7b882ccdfbdcd1bc
----
=> #4826: Commit form should have a selection whenever possible

GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
Fixes #6240
- just set the title in the designer
- manual
- Build d92e7749c714efa04c19899025e59d36e6feff19
----
=> Set the title of the ColorsSettingsPage

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs
Fixes #6246
- right clicking in the staged file viewer does not open the context menu, unless the user clicked on an item
- the context menu has two options grayed out when the file is new: `View file history` and `Open with difftool`
- manual tests
- ran unit tests
- Build c661fcb9e9719387a5c4da1e7590016270eb6c3a (Dirty)
----
=> #6246: NullReferenceException in commit dialog

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormRemotes.cs, GitUI/GitUICommands.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs, UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Update with some fixes of PR #6158 ( intended to fix issue #6118) 
- Added remote branch to status bar item branchNameLabel
- Added click event to open "Default pull behavior" for current branch
- Manual
- Build 595c2b99ca427defe82894e3b22e286ebdfdeeb8
----
=> Show remote branch in Commit dialog

UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs, UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Test failing: FormCommitTests.Should_display_branch_and_no_remote_info_in_statusbar()
=> Fix unit test that fails only on CI server

appveyor.yml, codecov.yml
Fixes Unit test coverage calculated by CodeCov. It excludes `/UnitTests/` sources recursively.
**Before**: https://codecov.io/gh/gitextensions/gitextensions (44.61% overall)
**Now**: https://codecov.io/gh/wachulski/gitextensions/tree/06a679fa84b0adc4a48ab763e5b7af2d6a4a206f (34.05% overall)
=> Fix CodeCov coverage - exclude unit test files

GitCommands/CommandStatus.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/Editor/FileViewer.cs, GitUI/GitModuleControl.cs, GitUI/GitModuleForm.cs, GitUI/Script/ScriptManager.cs, GitUI/Script/ScriptRunner.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, ResourceManager/GitExtensionsControl.cs, ResourceManager/GitExtensionsFormBase.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs
Fixes #5834.
- methods executing a command now return a new `struct CommandStatus` instead of a simple bool. Besides specifying whether the command was actually executed, it also contains a flag indicating whether the revision grid should be refreshed.
- navigational scripts no longer cause the grid refresh
- Manual testing (running commands both from context menu and using a hotkey)
- git version 2.20.1.windows.1
- Windows 10
----
=> Skip grid refresh after running a navigational script

GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
Fix for gitextensions/gitextensions/issues/6277
=> Existing branch combobox could be empty

GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs, GitUI/CommandsDialogs/FormCleanupRepository.cs
- Being able to open a dialog to select a directory inside the working directory
No button. We have to type or copy/paste the path from explorer
We could open a directory chooser to select a path
- Manually
- Build 04710c19a5d0fd1bbfbc56890a21dbd53ec2fe79 (Dirty)
=> FormCleanupRepository: Add a button to easily add a path to clean up

Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
Follow up to #6116
- Remove sometimes empty line in tooltip
- Display duration in the same format in all CI plugins
- other small tweaks
I will try to do it later... (if needed)
Appveyor:
=> Clean and unify build status label and tooltip

Setup/Product.wxs, appveyor.yml
Upload vsix as a separate artifact to Appveyor
Fixes #5979
- Remove .vsix from Wix installer. It was included in the bundle, ticking installation only unpacked the file to the GE install dir.
- Upload vsix as a separate artifact to Appveyor
The current handling is a remain from when the old VS addin ran from the GE installer.
The vsix can be installed from the marketplace, but the current version should be offered for PR/master builds and I see no reason to not offer the vsix for releases too.
- Manual iinstall
=> Remove .vsix from Wix installer

GitUI/Avatars/AvatarDownloader.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.resx, GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs, GitUI/GitUI.csproj, GitUI/Native.cs
Fixes #5828
Fixes #6223
- Check whether a client is connected to Internet before attempting to
fetch avatars.
- Add tooltip to clarify purpose of "No image" dropdown
- Add a setting to show author's avatar column
- manual
----
=> Don't load avatars, if network is not available

GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs, GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs, GitUI/CommandsDialogs/FormRemotes.Designer.cs, GitUI/CommandsDialogs/FormRemotes.cs
Fixes #6284
- Add "prune remote" in contextual menu of a remote in left panel (moved from FormRemote)
- Add "Update all remotes" in contextual menu of remotes in left panel (moved from FormRemote)
- Add "Update and prune all remotes" in contextual menu of remote in left panel (because just "prune all" like requested in #6284  is not something provided by git and I don't want to do it myself)
- Remove "Prune remote branches" and "Update all remote branch info" from FormRemotes
Left panel (enabled only) remote:
Left panel remotes:
- Manual 
- Build debc4f89828705b57937e7a11e8f65ac3517f8c0 (Dirty)
=> Move prune/prune all/update in Leftpanel remotes contextual menu

GitCommands/Settings/DefaultImageType.cs, GitUI/Avatars/AvatarDownloader.cs, contributors.txt
Fixes #6311
- Add [Robohash][1] as a  `No image service` option under `Author Images` in `Appearance` settings.
- Manually
- Build 5a3c150acb55848b0716417b7c6d76f8fa105cde
----
[1]: https://robohash.org/
=> Add support for Robohash no image service

GitUI/CommandsDialogs/FormRemotes.Designer.cs, GitUI/CommandsDialogs/FormRemotes.cs
Fixes #5028
Before:
After:
- Windows 10 hdpi
=> fix "Remote repositories" popup for high dpi UI

GitUI/CommandsDialogs/FormCommit.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormCommitTests.cs, UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs, UnitTests/GitUITests/UITest.cs
Builds on work started by @RussKie, but simplified in the end.
Supersedes #6273
Fixes #6320
Closes #6298 
📝 I tested this by updating `ControlThreadingExtensions.ControlMainThreadAwaiter.OnCompleted` to delay switches:
```csharp
public void OnCompleted(Action continuation)
{
var awaiter = _awaiter;
Task.Delay(250).GetAwaiter().OnCompleted(() => awaiter.OnCompleted(continuation));
}
```
=> Fix flaky form commit tests

UnitTests/GitUITests/Editor/FileViewerTextTests.cs
Observed this test as flaky in a few builds and tracked it down to a race condition in the configuration file.
Fixes #6329
=> Fix test dependent on file watcher delay

GitExtUtils/GitUI/CancellationTokenSequence.cs, UnitTests/GitUITests/CancellationTokenSequenceTests.cs
CancellationTokenSequence is written in a thread-safe manner but it can not be accessed when it is disposed. To properly deal with this, any async call that can access cts would have to be tracked and awaited before disposing cts. 
I propose to throw OperationCanceledException instead of ObjectDisposedException
so it is possible to access cts from a Task without worrying of cts being disposed or not.
The problem occurred in https://github.com/gitextensions/gitextensions/pull/5617
=> Throw OperationCanceledException on cts.Next() when cts is disposed.

GitUI/CommitInfo/CommitInfo.cs
- After the repo has changed, we have to load refs for the current repo. 
- Manual tests. 
----
=> Sorted refs needs to be refreshed after the repository has changed.

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTest.cs, contributors.txt
Quote SubmodulePath in GetSuperProjectCurrentCheckout to handle paths with spaces
Related to #6268 #6243 #6082 
- Quote SubmodulePath in GetSuperProjectCurrentCheckout to handle paths with spaces
- Manual tests
- Unit tests
- GIT  2.20.1.windows.1 
- Windows 10 (1709 / 16299.967) 
----
=> Quote submodule path to avoid black screen issue

GitUI/UserControls/FileStatusList.cs, UnitTests/GitUITests/CommandsDialogs/FileStatusListTests.cs, UnitTests/GitUITests/GitUITests.csproj
Fixes #6336
- never show the hint "Filter files..." if focused or if filter is active
- Build a8093a5192f572f9a552b836e69f94838897fd33
----
=> FileStatusList: Show the hint "Filter files..." only when applicable

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs
Also opportunistically set each root node's Name so that if we ever decide to modify the Text, it will play nicely with Get/RestoreExpandedNodesState.
Fixes #6313
- Remove counters on Branches and Tags nodes in left panel
- Ran unit tests
- GIT version 2.19.1.windows.1
- Windows 10
----
=> Remove count on Branches and Tags

GitCommands/Settings/AppSettings.cs, GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs, GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs, GitUI/BranchTreePanel/RepoObjectsTree.SettingsContextMenu.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.ReorderNodes.cs, UnitTests/GitUITests/GitUITests.csproj
- Add the ability to reorder root Tree nodes in left panel: Branches, Remotes, Tags, and Submodules.
- This is done by right-clicking the root node and selecting from "Move Up" or "Move Down" context actions.
- The "Show" menu items in the left panel settings menu are also reordered to match.
Context menu action, note that because it's the top-most node, "Move Up" is disabled:
Similarly, if bottom-most node is selected, "Move Down" is disabled. And there's only one node (because the other three are hidden), then both are disabled:
The settings menu where you can show/hide Trees matches the order:
If Trees are hidden, reordering still works as expected. For instance, say Tags and Branches is hidden like so:
If we right-click Submodules and move it down:
It will swap it with Remotes, but …
=> Left pane reorder trees

GitCommands/Git/GitCommandHelpers.cs
Resolves #6322
Fix the options for Git prior to 2.11
Note that Git prior to 2.11 is not officially supported, this patch will not change that.
However, the error messages will be less confusing and the code can be used as an example.
This do not need to be included in Release Notes.
Primarily: Test that Git 2.21.0 works
Also debugging in the code, viewing the command line argument
- GIT 2.21.0
=> Support Git pre 2.11 for status

GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes #6297
- Reset to first function will now work for copied files too
- GIT 2.16.1.windows.4
- Windows 10
----
=> Fix reset function for copied files

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Patches/PatchProcessor.cs, GitUI/AutoCompletion/CommitAutoCompleteProvider.cs, GitUI/CommandsDialogs/FormViewPatch.cs, UnitTests/GitCommandsTests/GitModuleTest.cs, UnitTests/GitCommandsTests/Patches/PatchProcessorTest.cs
Part of #6357 
- Lazy evaluation of GitModule.FileEncoding 
~~- Optimize copy GitModule copy~~ #6373
This fixes the performance problem I see in my "real" repos even if the core problem should be fixed too.
See #6357 for a test setup
This is verified by git-rev-parse calls for only the modules with changes
See #6357 , a submodule with changes required
=> GitModule Encoding lazy encoding

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUICommands.cs
Fixes #6093 
- GitModule.GetRemotes no longer throws an exception if the module opened isn't a valid Git module; rather, it returns an empty list.
- Opening and closing Settings dialog doesn't throw an exception if a valid module isn't open.
- GIT version 2.19.1.windows.1
- Windows 10
----
=> Fix exception thrown GitModule.GetRemotes on an invalid git directory

GitUI/Editor/FileViewer.Designer.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/IFileViewer.cs, GitUI/UserControls/BlameControl.cs
As noted in https://github.com/gitextensions/gitextensions/pull/6393#issuecomment-475447254 if you "click-hold-move-mouse-to-the-right" to move to the right in
the pane to see the rest of the text, there is no way to ever move back.
The fix handles horizontal scroll for the committer and blocks the hscroll.
- manual tests to ensure there is no hscroll in the committer control.
----
=> Fix blame control click hold move mouse to the right

GitUI/GitUI.csproj, GitUI/Properties/Resources.Designer.cs, GitUI/Properties/Resources.resx, GitUI/UserControls/BlameControl.Designer.cs, GitUI/UserControls/BlameControl.cs
(Like asked in https://github.com/gitextensions/gitextensions/pull/6393#issuecomment-476001787 a new PR for the blame contextual menu improvments)
* Reorder items in contextual menu
* Add icons in contextual menu
* Add a "Copy to clipboard" menu items
* with a new copy "all commit info" entry
* with a new copy "commit hash" entry
=> Improve blame contextual menu

GitCommands/Git/GitBlame.cs, GitUI/UserControls/BlameControl.cs, UnitTests/GitCommandsTests/Git/GitBlameCommitTests.cs
Fixes #6389
-  Fix date formatting in blame form (fix #6389)
-  Blame: Remove clutter by displaying file path only when not corresponding to the file blamed
Before:
After:
-  Better not costly approximation to have all the lines of the same size & lines of 120 characters is long enough
Before:
After:  (all the lines are of the same length and shorter)
-  Better display by inverting date and author
Before:
After: (all is better aligned and the dates are much more readable without compromising on author readability)
-  Align content of tooltip info with commit info content 
Before:
After: (labels updated to the same than the commit info and commit hash added)
Note: My only regrets here is that we can't use the translated strings here because the project `ResourceManager` that contains the …
=> Some improvments on blame form

GitUI/Editor/FileViewer.cs, contributors.txt
Fixes #6170 
- FileViewer should directly use the `IFullPathResolver` without probing a relative path first when calculating the file length, as the latter could lead to erroneous `PathTooLongExceptions`. (It already does so when summarizing binary files.)
- The `FileInfo` code in `GetFileLength` and `SummariseBinaryFileAsync` should be consolidated for symmetry.
- A `PathTooLongException` would sometimes be thrown for files whose path wasn't really longer than 260 characters. This happened when the GitExtensions process was started in some longish working directory (as done, e.g., by the VSIX) and the file viewer then combined a file's relative path (relative to the repository, that is) with that current working directory. If that path (which was usually wrong anyway) exceeded 260 …
=> #6170 Fix PathTooLongException for files whose path is shorter than 260 characters

GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs, GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
Fixes #3517
- Added an option to restrict history (`--depth`) when cloning from GitHub.
- The `--depth <depth>` flag will only be added to the `git clone` command if the checkbox was checked and a valid number was entered in the textbox.
- Cloned a repo from GitHub using the new feature, ensured `git clone` was commanded with the correct value in the flag.
- Ensured no flag was added when the checkbox is unchecked, or if the textbox contains no valid number.
----
=> Add depth option to GitHub Fork/Clone form

GitUI/Editor/FileViewer.Designer.cs, GitUI/Editor/FileViewer.cs
Fixes #6391 
-  Apply settings right after command source has changed in `FileViewer`.
-  Remove default value of 80 that is set to the `FileViewerInternal.VRulerPosition` property in `FileViewer`'s `InitializeComponent` method. The `FileViewerInternal` gets actual value for vertical ruler from app settings in its constructor.
- Build 7a5680d2fe317c08a4cb99f66a3f5e5e1c1c6c81 (Dirty)
----
=> Fix vertical ruler position not correctly read from settings

GitCommands/ExternalLinks/ExternalLinkRevisionParser.cs, GitCommands/GitCommands.csproj, GitCommands/Remotes/ConfigFileRemote.cs, GitCommands/Remotes/ConfigFileRemoteSaveResult.cs, GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/CommandsDialogs/FormPush.cs, GitUI/CommandsDialogs/FormRemotes.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/UserControls/RemotesComboboxControl.cs, UnitTests/GitCommandsTests/ExternalLinks/ExternalLinkRevisionParserTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/Remote/ConfigFileRemoteSettingsManagerTests.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.Remotes.cs
`IGitRemoteManager` only interacts with configured remotes in .gitconfig so it is renamed to `IConfigFileRemoteSettingsManager` to better reflect its nature.
----
=> refactor: Rename IGitRemoteManager to IConfigFileRemoteSettingsManager

GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, GitUI/Hotkey/HotkeySettingsManager.cs, GitUI/Translation/English.xlf, UnitTests/GitUITests/CommandsDialogs/RevisionDiffControllerTests.cs
Fixes #6296
Small changes to RevisionDiffControl as suggested in #6296:
* "Delete file" context menu item is no longer shown for 'historical' commits, and only visible for 'artificial' i.e. WorkTree or Index, and it makes sense to leave the menu item in that case.
* "Edit file" is replaced with: "Edit working directory file", "Edit working directory file with...", "Open this revision (temp file)", "Open this revision with... (temp file)" similar to the items in commit file tree tab. 
* Menu items "Edit working directory file" and "Edit working directory file with..." only appear if a file actually exists.
* Menu items "Open this revision (temp file)", "Open this revision with... (temp file)" are hidden in case if commit is "artificial" because there's no revision.
* All new menu items are …
=> Fix issue #6296: Incorrect context menu items in commit diff tab

Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
that could happens if you open a form that display CI results
quickly after starting GitExtensions (and that the plugin has not finished
to be initialized in the browse form)
* Open GitExtension repository (which use AppVeyor CI build)
* Very quickly , open the blame form
* Crash!
#Screenshots
##Before
##After
No more exception.
- Manual
- Build 6c855242d9ba489004643e717f48b0ea344f401a (Dirty)
=> AppVeyor plugin: Prevent crash when trying to add the same project again

GitCommands/Git/GitModule.cs, Plugins/GitUIPluginInterfaces/IGitModule.cs
- [git-scm.com](https://www.git-scm.com) recently changed the structure of the HTML anchors in the git reference manual. These are used to link directly to specific options of git commands.
GE has a few of those links in code comments, which still linked to the correct page (i.e. git command), but no longer to the correct section (i.e. option). For example:
- old: https://git-scm.com/docs/git-rev-parse#git-rev-parse---git-common-dir
- new: https://git-scm.com/docs/git-rev-parse#Documentation/git-rev-parse.txt---git-common-dir
- N/A. This PR changes only some URLs contained in comments. Nothing more. The code is not altered in any way.
----
=> Updated links to git-scm.com

GitUI/Editor/FileViewer.Designer.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/IFileViewer.cs
and thus line numbers were displayed in blame even if explicitly set to be hidden
That was the case since 456ea65d7143e1555455c44d8bd385169f2feaf4
See https://github.com/gitextensions/gitextensions/commit/456ea65d7143e1555455c44d8bd385169f2feaf4#diff-555178f3fd75ec9d4f3aebcef1f48882R128
The strategy adopted is to not set the value by default so the setting is determined by the content (actual behavior)
but if explicitly set, the value is used.
Fixes regression (surely introduced in 456ea65d7143e1555455c44d8bd385169f2feaf4 /cc @RussKie ) on blame commiter fileviewer that show the line numbers even if explicitly set to not show them.
The line numbers are displayed even if set to be hidden ( https://github.com/gitextensions/gitextensions/blob/16aea8ca2ad8b3d4bf84f0f26c1c6f71ff0684d0/GitUI/Use …
=> Fix fileviewer ShowLineNumbers setting that was not honored

GitCommands/Git/ExecutableExtensions.cs, GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitModule.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/AutoCompletion/CommitAutoCompleteProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs, GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormMergeSubmodule.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/Editor/FileViewer.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes #6357
- Load submodules info with async api. It was not enough, the lag was smaller but still significant.
- Load submodules info sequentially - this helped.
- Manual tests
----
=> Serialize submodules info loading

GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #6147 
- The `HashSet ToBeSelectedObjectIds` should be a `List`, because order matters.
- There is no need for `ToBeSelectedRowIndexes` to be a `ConcurrentQueue`, since we want to wait till we have all the rows to be selected and, when we have them, we select them. The list of indices can thus be stored in a `List` that includes order information.
The grid attempts to select a commit as soon as it is loaded. Consequently, rows are being selected in the order in which revisions are read, not in the order in which they had originally been selected.
By waiting till all rows to be selected have been added to the grid before attempting to select them, we can select them in the correct order. With the current implementation, that's the best that can be done if we don't want to wait till …
=> #6147 inverted diffs after refresh

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes part of #6225
- Changed how `AppSettings.ShowErrorsWhenStagingFiles=false` works (flag for skipping "warning: LF will be replaced by CRLF" messages). Instead of simply not showing the warning messages after the git command has been executed, pass an additional option to git to not even generate the warning messages.
Advantages:
- A cleaner implementation.
- It provides at least a workaround for #6225. Setting `AppSettings.ShowErrorsWhenStagingFiles` to false will allow to stage any number of files, regardless of their line ending and the user's `core.autocrlf` setting. The freeze remains though with `AppSettings.ShowErrorsWhenStagingFiles` true (the default value).
- manual tests, in particular with the reproduction repo and steps described in …
=> Avoid freeze when staging many files at once (works only when AppSettings.ShowErrorsWhenStagingFiles==false)

GitUI/CommandsDialogs/FormBrowse.cs
Regression from #6372
The submenu status in the dropdown menu was not updated after rework in #6372 
As a not released regression, this is not added to the 3.1.0 milestone
Manual test: Make a test to a submodule
----
=> Detailed submodule status in dropdown menu was not updated

GitUI/UserControls/ExListView.cs
Fixes #6375
- Open gitextensions repository with gitextensions
- find commit 9c637272d41d5b43598f3a53f2f6c2aa4a5dcd8b
- select the commit in revision grid
- collapse / expand second group in file list in Diff tab
result: the list items (changed file names) are painted correctly
Also verified there is no flicker when moving mouse over the list, as the removed code's intent
was to fix the flicker, see 77bf3b610138824b5f02d55e6f3ed7f0425847d1
- Windows 7 SP1
----
=> fix #6375 ExListView not custom drawing after collapse / expand group

GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.Designer.cs
Fixes #6447
- extend the label text
- manual
- Build 385cf8b60c17f3ab2fbac3f10aa2858a59a51833
----
=> Mention regex in label of FileStatusList's filter

GitCommands/Git/GitException.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/RefsWarningException.cs, GitCommands/GitCommands.csproj, GitUI/CommitInfo/CommitInfo.cs
Fixes #6442.
- detect the Git warning returned by the command "for-each-ref" (although the exit code is 0)
- cancel loading refs
- display the warning
- manually
- Build 400b68461b38c7d51a9bee8b1d15bd751bb97a87
----
=> Detect and display Git warning on broken refs

GitExtensions.sln
Closes #5064
GitHub allows submitting issues by navigating a dedicated URL supplying issue data via query string parameters.
More info: https://help.github.com/en/articles/about-automation-for-issues-and-pull-requests-with-query-parameters
Whenever Git Extensions experiences an issue that is handled by NBug, a user is presented with an option to submit an issue to our GitHub repo.
By clicking "Send and quit" button the following occurs:
* an issue payload is generated,
* the payload gets encoded into a url, and
* the user is navigated to the generated url in a browser of their choice
- manual, added an exception to `CommitInfo` control and observed it handled by the NBug.
```diff
diff --git a/GitUI/CommitInfo/CommitInfo.cs b/GitUI/CommitInfo/CommitInfo.cs
index e00813929..78d564d44 100644 …
```
=> feat: Submit issue to GitHub

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTest.cs
Fixes #5923
Replaces #6356 because
- @NOYB has no dev environment (https://github.com/gitextensions/gitextensions/issues/6355#issuecomment-471221075),
- has not signed the CLA and
- @vbjay found the reason (https://github.com/gitextensions/gitextensions/issues/6355#issuecomment-471215388)
- fix typo in Git command arguments for "format-patch" for the case of multiple patches, i.e. with a start number
- added a NUnit test for the Git command arguments
- manual tests of `Commands | Format patch...`
- Build ebc44475d44e878e26ba74e7ebcca419914d3d38
---- …
=> Fix Git arguments for formatting multiple patches

GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/PathFormatter.cs, UnitTests/GitUITests/CommandsDialogs/PathFormatterTests.cs, UnitTests/GitUITests/GitUITests.csproj
Fixes #6465
- detect renamed/copied files
- draw only the new filename black
- manual
- Build 4ba5be25f33398170adc8651825b3c0107092ae2
----
=> Highlight the new name in the FileStatusList

GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid/QuickSearchProvider.cs, ResourceManager/Strings.cs
Fixes #6419
- Added a string "Searching for: " before the query when performing a quick search, to clarify it's purpose.
- I only changed the label string, so it does not affect the search query nor the logic behind it.
----
=> Clarify quick search by adding a prefix

GitUI/UserControls/CommitDiff.cs
Fixes #6271
- Clear FileViewer in history form when empty area is clicked (i.e. below the changed files). This is the same behavior as already implemented in the main form and commit form. 
- manual tests
- Build 5d2c8c94ba6b7f3e788e82707dc1ca2c8391f8d0
----
=> Clear diff in history form when no file selected

UnitTests/CommonTestUtils/GitModuleTestHelper.cs
Executing path for submodule was incorrect.
The following command executes from repo1 instead of repo2, it just happens to return the correct answer:
https://github.com/gitextensions/gitextensions/blob/master/UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs#L135
Part of #6487 
Do not use incorrect git executable in submodule tests
Run tets
----
=> TestHelper used GitExecutable for superproject

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Fixes #6487 
Only affects test code
This is only used for mocking in tests and should be avoided in the public API.
A TestAccessor is not straightforward (this is a readonly field),
reflection is used instead.
Tests still working
----
=> Remove executable arg for GitModule

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/Hotkey/HotkeySettingsManager.cs
Fixes #6481
- add hotkeys for Open with difftool | First/Selected to working directory
(active in RevisionDiffControl and FormBrowse)
- manual
- Build e3b9bc3bf78d0dc19579f7bc32aa56132f379042
----
=> Hotkeys for Open with difftool | First/Selected to working directory

GitCommands/Git/ExecutableExtensions.cs, contributors.txt
Fix by setting up reading from output & error buffers before starting to
write to input. When staging files one by one git process will write to
error buffer at the same time as we write commands to the input buffer.
If we don't read from the error buffer before all the input has be
written, the output buffer can fill up, resulting in Git blocking to
wait until we read something.
Fixes #6225
- Tested that the issue is fixed on a repository with 1000 files with LF line endings and core.autorcrlf = true.
- Also a case where the files have CRLF line endings and core.autocrlf=input was tested.
- Ran unit tests.
- GIT git version 2.20.1.windows.1
- Windows 10 version 1803
----
=> Fix freezing when staging many files with autocrlf

GitCommands/Submodules/SubmoduleInfo.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs, GitUI/CommandsDialogs/FormBrowse.cs, UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs, UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormBrowseTests.LeftPanel.Submodules.cs
Part of #5769
(closes the issue with #6373 that may be dropped)
Submodule structure is separated from detailed status
Previously, the structure was always recalculated when status was updated
Also, the status is only calculated for the submodule trees where
git-status has detected changes.
This has simplified the code as well decreased the time before the
detailed status is displayed. The status was also flashing for several
seconds while updating (occurred regularly if any submodule had a change).
The normal use case with submodules is that most changes are done in the top project and that there are no or few changes in submodules.
#5777 (3.1.0) changed to only get the detailed status if there were any changes in submodules so the no-change scenario is handled already in master.
However, …
=> Separate submodule structure and status

GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs, Plugins/GitHub3/GitHubRepo.cs, Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs
Fixes #5109
- Added default branch to a repository, fetched from GitHub API (see [PR in submodule](https://github.com/gitextensions/Git.hub/pull/10))
- Selecting the default branch when creating Github pull request.
- Run with different repositories with different default branch to make sure it works properly. 
=> Select the default branch when creating Github pull request

GitExtUtils/GitUI/ControlHotkeyExtensions.cs
Fixes problems introduced by #6029
1. Removing word on `Ctrl`+`Backspace` manually instead of using `SendKeys.Send("^+{LEFT} {BACKSPACE}")`
turns out `SendKeys.Send` solution is
- Unreliable: in some environments, maybe depending on keyboard type, the second and subsequent words are not removed by 1 `Backspace` click.
[proof](https://github.com/gitextensions/gitextensions/pull/6049#issuecomment-464287771)
- Incomplete: Only `LeftCtrl` + `Backspace` was handled correctly
2. Apply the same fix to `ComboBox`es
manual
- Windows 7SP1
----
=> Manually handle Ctrl+Backspace on TextBox and ComboBox controls

GitCommands/Settings/DefaultImageType.cs, GitUI/Avatars/AvatarDownloader.cs, GitUI/Avatars/AvatarMemoryCache.cs, GitUI/Avatars/AvatarPersistentCache.cs, GitUI/Avatars/AvatarService.cs, GitUI/Avatars/BackupAvatarProvider.cs, GitUI/Avatars/IAvatarGenerator.cs, GitUI/Avatars/IAvatarProvider.cs, GitUI/Avatars/InitialsAvatarGenerator.cs, GitUI/CommitInfo/CommitInfoHeader.cs, GitUI/GitUI.csproj, GitUI/UserControls/AvatarControl.cs, GitUI/UserControls/RevisionGrid/Columns/AvatarColumnProvider.cs, Plugins/Gource/GourceStart.cs, UnitTests/GitUITests/Avatars/AvatarCacheTestBase.cs, UnitTests/GitUITests/Avatars/AvatarMemoryCacheTests.cs, UnitTests/GitUITests/Avatars/AvatarPersistentCacheTests.cs, UnitTests/GitUITests/Avatars/AvatarTestBase.cs, UnitTests/GitUITests/Avatars/BackupAvatarProviderTests.cs, UnitTests/GitUITests/Avatars/InitialsAvatarGeneratorTests.cs, UnitTests/GitUITests/GitUITests.csproj
A smaller step than #6417 as it requires no ("not everyone agrees") UI changes but bringing most of the added value...
- Add a new new gravatar fallback possibility with avatars generated from author initials
* Unit tests
* Manual
- Build c937777048244969bee4b89f19e641543dd9a6e7
- .NET Framework 4.7.3362.0
----
=> Generate avatars with author initials as fallback of gravatar

GitUI/Script/ScriptOptionsParser.cs, GitUI/Script/ScriptRunner.cs
Fixes #6285
- resolve regression introduced by 1b8bb93c7121cd291a17303edfdd313c8edb9f88
by correctly detecting script options starting with "s" again
The regression was a NRE instead of the message (see screenshot).
- bugfix: The script options {cHash}, {cMessage}, {cAuthor}, {cCommitter}, {cAuthorDate}, {cCommitDate} did not work due to currentRevision being null when the script was not run from RevisionGridControl.
before 1b8bb93c7121cd291a17303edfdd313c8edb9f88
since 1b8bb93c7121cd291a17303edfdd313c8edb9f88
NRE 
messagebox if the RevisionGrid is not focused
- manual
- Build ca548259cc4cbee4b99ae6724a75345e57ab023c
----
:black_nib: I …
=> correctly detect/handle script options

GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/Translation/English.xlf
Fixes #6507
- Checkout branch: Remove inopportune line return in message box message
- Manual
- Build 290db968d32089960a018a67e30da65c65182b40 (Dirty)
=> Checkout branch: Fix inopportune line return in message box message

Plugins/Bitbucket/BitbucketPlugin.cs, Plugins/Bitbucket/BitbucketPullRequestForm.cs
Part of #4229
BitBucket Server has a link (that can be copied) to simplify creating BB PRs. (The BitBucket plugin is a little limited and for instance do not set default reviewers.)
The current link opens the general form.
This PR formats the link so the source address is set, you do not have to select in the list.
This is a minor feature, but simplifies when there are many branches.
No translation strings changed.
Link changed from
```
<bitbucket-server>/projects/<project>/repos/<repo>/pull-requests
```
to
```
<bitbucket-server>/projects/<project>/repos/<repo>/compare/commits?sourceBranch=<branch>
```
Requires BitBucket Server to open the GE form
Click the link and verify that the source branch is filled in
BitBucket Server 6.0 (believe this is the same in BBS5).
----
:black_nib: I …
=> Include source branch in link to BitBucket create pull request

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Fixes #6512
Do not parse invalid rev-parse responses
Added a unit test
See issue for how to reproduce
----
=> Do not parse invalid rev-parse responses

GitUI/CommandsDialogs/FormFormatPatch.cs
Note : same than #6525 but merge in master
Fixes :
When selecting 2 revisions in the wrong order (even if it seems the more logical one: from selected first and to selected last), the patchs are not generated and a blank message box is displayed
When selecting more than 2 revisions, patch are generated in the wrong order.
- Order of selection of revisions should not have effect on what is generated (patches are now generated in chronological order). Patches are generated successfully in any selection order.
- prevent an empty message box when no file generated (replace by an error message)
- Don't close form when generation failed
And patches are not generated.
* Patches are generated successfully in any selection order.
* New error message (even if I can't display it anymore due to the …
=> Format patch: fix patch creation when selection order is invalid (master) 

GitUI/CommandsDialogs/FormFormatPatch.cs
Fixes :
When selecting 2 revisions in the wrong order (even if it seems the more logical one: from selected first and to selected last), the patchs are not generated and a blank message box is displayed
When selecting more than 2 revisions, patch are generated in the wrong order.
- Order of selection of revisions should not have effect on what is generated (patches are now generated in chronological order). Patches are generated successfully in any selection order.
- prevent an empty message box when no file generated (replace by an error message)
- Don't close form when generation failed
And patches are not generated.
* Patches are generated successfully in any selection order.
* New error message (even if I can't display it anymore due to the fix on selection order):
- Manual
- Git …
=>  Format patch: fix patch creation when selection order is invalid 

GitUI/CommitInfo/CommitInfo.cs
Fixes #6516
- remove the unnecessary call of the function `LoadSortedRefsAsync` from `StartAsyncDataLoad`,
which results in `GetSortedRefs` being called three times on startup
- remove the duplicated implementation which does not handle the possible `RefsWarningException`
- manual tests
finding: On startup, `StartAsyncDataLoad` is called twice. I.e. the startup actions should be optimized. -> #6520
- Build e0cfed7d0d82a5ebb5c2d20f103b25a56bbec874
----
=> Remove duplicated implementation and call of function LoadSortedRefsAsync

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/UserControls/BlameControl.Designer.cs, GitUI/UserControls/BlameControl.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/UserControls/BlameControlTests.cs
- Add settings to customize blame display (see screenshot for list of settings)
- Also improve a little more memory usage when building the commiter text
Result with some settings enabled:
- Manual 
- Build 84b65c3f6542f6adb817c308906522c66c611009
- .NET Framework 4.7.3362.0
=> Add settings to configure blame display

GitUI/CommitInfo/CommitInfo.cs
Fixes #6535
- avoid loading data of incoherent revisions
by loading all data for the same revision
**Drawback:** The initial commit is selected again when the loading has finished.
- manual tests
- Build cbd5ad5caeab7721dc4693abc94b10e89c6ed6b5
----
=> Avoid loading data of incoherent revisions (for 3.1)

GitUI/CommitInfo/CommitInfo.cs
Fixes #6535
- avoid loading data of incoherent revisions
by loading all data for the same revision
**Drawback:** The initial commit is selected again when the loading has finished.
- manual tests
- Build c14ba78cca3a50f5daa6519d615f819fb0ede1f7
----
=> Avoid loading data of incoherent revisions

appveyor.yml
It appears we aren't marking portable builds as such:
/cc: @vbjay
=> fix: Mark portable version as such

GitCommands/Git/GitModule.cs, GitCommands/Patches/PatchFile.cs, GitUI/CommandsDialogs/FormApplyPatch.cs, GitUI/CommandsDialogs/FormRebase.Designer.cs, GitUI/CommandsDialogs/FormRebase.cs, GitUI/Translation/English.xlf, GitUI/UserControls/PatchGrid.cs
Fixes a wrong status displayed 
- Form Rebase & Form Apply Patches: The status on each row display the good patch state
- The transiant "skipped" state is handled
- The "skip"button label as been changed to better explain what it does (skip the currently applying patch and not skipping the selected commit/patch)
- Little ergonomical improvement: The "Applying" patch row is selected when opening the form
The patches applied are wrongly displayed as "skipped"
- Manual
- Build 1acb4c9940f8bf0d7c828b3a7a3a1ff77c246cc0
=> Fix rebase and apply patches displayed patches status

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
It looks like there was a change in wording after git 2.16 that changed from "fatal: Not a git..." to "fatal: not a git...".
The existing parser expected the warning to be in the lower case, and thus failed for earlier versions of git.
Fixes #6562
Closes #6563
Closes #6565
Closes #6570
Closes #6571
Closes #6574
Closes #6577
Closes #6571
- The fix makes the check case insensitive.
- downgraded to git 2.16.4
- manual repro
- unit tests
- Git Extensions 3.1.1
- Build bb1687f6bd0450d0c1a2bae10a37c65493fc1294 (Dirty)
- Git 2.16.1.windows.4
----
=> fix: Throws on `git remote` call outside git repo

GitExtUtils/GitExtUtils.csproj, GitExtUtils/GitUI/ThreadHelper.cs, Setup/MakePortableArchive.cmd, Setup/Product.wxs
with smaller stacktraces and matching the real source code
Fixes #6569
```
System.Exception: This is a test
at GitCommands.GitModule.<GetRemotesAsync>g__ParseRemotes|155_0(IEnumerable`1 lines) in C:\...\gitextensions\GitCommands\Git\GitModule.cs:line 2196
at GitCommands.GitModule.<GetRemotesAsync>d__155.MoveNext() in C:\...\gitextensions\GitCommands\Git\GitModule.cs:line 2163
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.VisualStudio.Threading.AwaitExtensions.ExecuteContinuationSynchronouslyAwaiter`1.GetResult()
at GitUI.BranchTreePanel.RepoObjectsTree.RemoteBranchTree.<LoadNodesAsync> …
```
=> Use `Ben.Demystifier` to display or report better stacktraces

GitUI/Script/ScriptOptionsParser.cs, UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
Fixes #6567
- Complete the refactoring done in #6004 for sRemotePathFromUrl
----
=> Bugfix script option {sRemotePathFromUrl}

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormCreateBranch.cs, GitUI/CommandsDialogs/FormCreateTag.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #6597
Low priority
For artificial commits, use HEAD instead
This affected commands invoked by the hardcoded Ctrl-B and Ctrl-T shortcuts only (the shortcut in FormBrowse is not invoved).
The menu items are disabled for artificial commands already, the shortcut is not blocked though. The commands could be blocked in RevisionGridControl (as well as FormBrowse, even if that code will not be executed as the menu items are checked). However, the Form should check this anyway and it seem OK that the HEAD is used here.
See issue
Manual test:
- Select an an artificial command
- Ctrl-B/Ctrl-T to invoke the dialogs
- Verify that HEAD is set as base version
----
=> Create branch or tag: Not for artificial commits

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/GitUI.csproj, GitUI/Properties/Resources.Designer.cs, GitUI/Properties/Resources.resx
- Add icons in the "Repo" and "Branch" dropdowns of the Browse form
- Manual
- Build ee10522ce9ea2bcb93f6c30dceaa133b55bf16c0 (Dirty)
=> Add icons in "Repo" and "Branch" dropdowns

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormPull.cs, UnitTests/GitUITests/CommandsDialogs/CommitDialog/FormPullTests.cs
If "Open Pull dialog ..." is set as a default pull operation, the pull dialog does not have correct settings preselected upon open.
Also since refactors in v3 pull dialog does not remember user selection (such as `Auto stash`).
Fixes #6503
(cherry picked from commit 691c45b52016d3698bb0a4c60eba938d217e36c0)
- The fix restores `FormPullAction` setting that remembers user's selection in the dialog.
- The fix also restores the capture of `AutoStash` selection.
- reproduced the issue / compared with v2.51.04
- manual tests
- unit tests
- Git Extensions 3.1.1
- Build 691c45b52016d3698bb0a4c60eba938d217e36c0
- Git 2.16.1.windows.4
----
:black_nib: I contribute this code under [The Developer Certificate …
=> fix: Pull dialog not remember user selection

GitUI/UserEnvironmentInformation.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/UserEnvironmentInformationTests.cs
Fixes something evoked there: https://github.com/gitextensions/gitextensions/issues/6562#issuecomment-493673925
- Add "Last supported" and "Recommended" versions of git in the about form and reports message to let us more easily process bug reports.
```
- Build f5c59e63703641975d3bf3616c94e5eed0f4157b (Dirty)
```
```
- Build f5c59e63703641975d3bf3616c94e5eed0f4157b (Dirty)
- Git 2.21.0.windows.1 (Last supported: 2.11.0 / Minimum recommended: 2.20.1)
```
- Manual
- Build f5c59e63703641975d3bf3616c94e5eed0f4157b (Dirty) …
=> Add Git "Last supported" and "Recommended" versions in reports

GitUI/UserControls/PathFormatter.cs, UnitTests/GitUITests/CommandsDialogs/PathFormatterTests.cs
Fixes #6559 for 3.1
- do not split paths at trailing slash of submodules
- added NUnit test cases
- Build 16417f69e30d0326cb6d40306df197a86c082cb2
- .NET Framework 4.7.3362.0
----
=> Fix FileStatusList: New submodule without text if unstaged

GitUI/UserControls/PathFormatter.cs, UnitTests/GitUITests/CommandsDialogs/PathFormatterTests.cs
Fixes #6559
- do not split paths at trailing slash of submodules
- added NUnit test cases
- Build 9190a2cdd2ee3bde4693e58cf32a4a49f0d30be9
- .NET Framework 4.7.3362.0
----
=> Do not split paths at trailing slash of submodules

GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs, GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
https://github.com/gitextensions/gitextensions/issues/4033#issuecomment-491493535
Move the toggle to view artificial commits (working directory and Index commits) in the revision grid from Settings to the View menu.
This is consistent with other grid 'decorations'.
This setting was maybe affecting the performance when first added but has no direct effect right now. The General tab is also too crowded right now.
Note: The old setting was called "Show current working directory changes as an artificial commit".
I choose to call the new "Show artificial commits". As the setting now is closer to the change, it should be easier to understand. (This will have to be described in the documentation.)
Manual test
---- …
=> Move ArtificialCommits from Settings to grid View menu

GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs, Plugins/GitHub3/GitHubRepo.cs, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/RepositoryHosts/GitProtocol.cs, Plugins/GitUIPluginInterfaces/RepositoryHosts/GitProtocolExtensions.cs, Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRepository.cs, UnitTests/Plugins/GitUIPluginInterfacesTests/GitProtocolTests.cs, UnitTests/Plugins/GitUIPluginInterfacesTests/GitUIPluginInterfacesTests.csproj
Refactoring, so fixes nothing...
- Introduce a class (edit: after some refactorings, that end up as an enum) `GitProtocol` to handle supported git protocol (a refactoring required to be used in 2 PR #6328 and #6515)
- Easier to review and merge before the 2 PRs...
- Added some unit tests
- Build 9602479c6bb5464dee4add337527ffcf47fb35fc (Dirty)
----
=> Refactor: Create an enum GitProtocol.cs

.gitmodules
GE has currently hardcoded the submodule references like https://github.com/gitextensions/NBug.git
So if you clone the superproject with ssh (or git or file if you have a cloned server for some reason) the submodule references are still using https: It is a little confusing when cloning why you get Git Credential Manager (if GCM is installed) or get prompts for each subrepo.
- Clone repo git@github.com:gerhardol/gitextensions.git with branch feature/relative-subm-url recursively
- Verify that the submodule references are using ssh
- Check out branch feature/relative-subm-url
- git submodule sync
- Check that the url for the submodule with base matching the superproject changes (all will not change).
---- …
=> Use relative submodule references to clone with ssh

GitExtUtils/GitUI/ControlHotkeyExtensions.cs
Fixes #6667 introduced by #6256
Manually verified the problem from screenshot below was fixed.
- Windows 7 SP1
----
=> Fix Ctrl+Backspace affecting ReadOnly TextBox

GitCommands/Git/GitModule.cs, GitUI/CommitInfo/CommitInfo.cs, UnitTests/CommonTestUtils/CommonTestUtils.csproj, UnitTests/CommonTestUtils/MockExecutable.cs, UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/GitModuleTests.cs, UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs, UnitTests/GitUITests/GitUITests.csproj
`GitModule.GetSortedRefs` method has been moved into `CommitInfo` control because that's was its only call site. As such the method added little value and a significant overhead to the public API surface.
To get the tests working,
* `MockExecutable` was moved to `CommonTestUtils` projects to it can now be accessed across all tests; and
* `LoadSortedRefsAsync()` method was refactored and `ToDictionary` method was inlined into `GetSortedRefs()` to facilitate testing.
Also while building tests I discovered the following:
* `CommitInfo` would call `RefreshSortedRefs()` when the control was passed an instance of `UICommandsSource`, which was pretty much at the instantiation time, way before a display of a commit information was requested.
* A second redundant call to `RefreshSortedRefs()` was …
=> refactor: GitModule.GetSortedRefs

GitExtUtils/GitUI/ControlHotkeyExtensions.cs
Follow up #6668
The change is cosmetic, `Ctrl`+`Backspace` does not
affect non-editable ComboBox anyway
----
=> ignore Ctrl+Backspace in non-editable ComboBox

GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs, Setup/Product.wxs
Relates to #6679
Original Code from my own software adapted to GitExtensions.
GitExtensions:
- Download MSI to users temp directory
- Launch MSI to silently upgrade, have basic display progress and set LAUNCH property to 1
- Exit GitExtensions after launching MSI
- After successful upgrade, MSI will auto launch GitExtensions.exe
GitExtensions Installer:
- Add new property called LAUNCH and set value to 0
- Default install / upgrade will not auto launch GitExtensions.exe
- Setting LAUNCH to a value of 1 will launch GitExtensions.exe after successful install / upgrade
----
=> Feature: Download / Install MSI without redirect to Browser

GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
Fixes #6031 (and #6568)
- width calculation factors in that two line numbers are displayed
- do not multiply `TextHorizontalMargin` by `textArea.TextView.WideSpaceWidth`!
- manual
- Build 2bfd1153219c59c1c418541d2beee0ae7be5b6fa
----
=> FileDiff: Factor in that two line numbers are displayed

GitCommands/Settings/AppSettings.cs
Since the application name has been updated in AssemblyInfo (in fce96e3), `Application.UserAppDataPath` has started pointing to a different directory, thus losing the original app settings.
Remove introduced " " (space) chars from the path.
Closes #6696
- manual checks
----
=> fix: Settings path has changed

GitUI/CommitInfo/CommitInfo.cs, UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
Fixes #6725
- restore call of `RefreshSortedRefs` in the `UICommandsSourceSet` event handler
- remove unnecessary call of `ReloadCommitInfo`
- adapt test setup
- manual
- Build a62ac4df274a67c0811011181011ad8e33ba82dd
----
=> CommitInfo: Bugfix "Contained in branches/tags"

GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs
Some minor issues seen 
- FormDiff: Compare Worktree to worktree. 
FormDiff should be aligned to https://github.com/gitextensions/gitextensions/blob/master/GitUI/CommandsDialogs/RevisionDiffControl.cs#L682
- RevisionDiff: Delete worktree directories
Directories (like deleted submodules) could not be deleted, only files
This is only possible with Delete key, context menu only allows deletion of single files. (DEL also allows deleting several files at the same time.)
- RevisionDiff: Delete multiple files must unstage
If Selected revision was not Index (for instance HEAD to worktree) the file was not unstaged.
Manual tests - there are unittests already
----
=> artificial context fixes

GitUI/CommandsDialogs/FormCommit.cs
Fixes #6583 
Check that file is still selected when manipulating lines in FormCommit.
Reported for reset, similar possible for stage/unstage
Code review, race condition. This is hard to recreate in current master
----
=> Commit: Stage/unstage/reset lines null reference

GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
Part of a solution to #6757
- Move a call to a github api outside of a for loop to do only one call
- Manual
- Build c501b6ac6f64d845dc35af19b009fea50570f14c
----
=> CreatePullRequestForm: prevent multiple same call to github api

GitUI/CommandsDialogs/FormCommit.cs, UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs
Fixes #6771
Null check before evaluating filename.
This could occur when pressing F4 with no selected files
Code review, hard to reproduce with the problem
----
=> FormCommit: No selection and F4 could give null refs

GitUI/Translation/English.Plugins.xlf, Plugins/Gerrit/FormGerritPublish.Designer.cs, Plugins/Gerrit/FormGerritPublish.cs, contributors.txt
Fixes #6127
Changed deprecated options for publish type and topic in Gerrit to support newer version
Changed push reference to use /refs/for with %wip and %private for instead of deprecated /refs/publish and /refs/draft
Changed the way topic is passed into gerrit to use new `-o topic=TOPIC` format.
Draft changes (that are currently used in Git Extensions) have been marked obsolete in Gerrit 2.15 in 2017 (
https://github.com/GerritCodeReview/gerrit/commit/4b44bdc7022653cec0cf0322b1161a210d46b8fb).
`refs/publish` have been removed last year (https://github.com/GerritCodeReview/gerrit/commit/605941e57f1fefd029e8c6b6af63a04dfbcaf08d)
`refs/for` syntax used in this PR to publish changes, have been introduced around 2011-2013, and were synonym of `refs/publish`. This change will break pushing …
=> Fixed Gerrit plugin using deprecated features

GitUI/CommandsDialogs/FormPush.cs
Fixes #6717
When selecting a specific URL to push to, FormPush validates that the push url is not empty.
RepositoryHistoryManager.Remotes.AddAsMostRecentAsync() will raise an exception if the url does not seem to be a vaild URL (not starting with ssh, http, git) and raises an exception.
If URL starts with a correct protocol but is invalid, git will report that the URL is unavailable. (This should be understandable by the user).
FormPush should check the protocol to avoid that RepositoryHistoryManager raises exceptions.
The warning popup is good enough already.
No GUI change, 
Exception
manual testing
FormPush.PushChanges() is a GUI method, not worth it to add tests.
----
=> Check that PushUrl has a valid protocol

GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs, GitUI/CommandsDialogs/BrowseDialog/FormUpdates.resx, GitUI/Translation/English.Plugins.xlf, GitUI/Translation/English.xlf
Fixes #6738
Updated button text from "Download Now" to "Update Now".
Updated Update Now button / event names.
Moved Update Now button position to where the Close button was located.
Added a new link called "Direct Download" which restores original functionality of launching default browser to download MSI.
----
=> Refactor "Check for updates" dialog

GitCommands/Git/GitModule.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/GitUICommands.cs, GitUI/Plugin/PluginRegistry.cs, GitUI/Translation/English.Plugins.xlf, GitUI/Translation/English.xlf, Plugins/GitHub3/GitHub3Plugin.cs, Plugins/GitHub3/GitHubHostedRemote.cs, Plugins/GitHub3/GitHubRepo.cs, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/IGitModule.cs, Plugins/GitUIPluginInterfaces/Remote.cs, Plugins/GitUIPluginInterfaces/RepositoryHosts/IHostedRemote.cs, Plugins/GitUIPluginInterfaces/RepositoryHosts/IRepositoryHostPlugin.cs
~~Note: better reviewable and merged after #6514 (a small part of the refactoring done in this PR was extracted in #6514)~~ done.
- Add a menu item to easily add the "upstream" remote to the repository
- refactoring:  also introduce a refactoring on `GitHubHostedRemote` where the underneath repository should be initialized with the `GitProtocol` already used ( make use of `GitHubHostedRemote` easier)
- Manual
- Build 9c567e63a5bfb30af412bce86e356e169735d5af
=> GitHub: easily add upstream remote

GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs, GitUI/Translation/English.xlf
- restore the title of the `AppearanceSettingsPage`
(Lost in 5814698d982b34b36d415f6de41f3bea40898ab4. Perhaps the same effect which led to #6242.)
- manual
- Build a68be687b7a21f467d5718afda51f12507e6b342
----
=> Restore title of AppearanceSettingsPage

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs, GitUI/Script/ScriptOptionsParser.cs, GitUI/Translation/English.xlf, UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs
Fixes #6736
- add script options `{cRemoteBranchName}`, `{sRemoteBranchName}` and `{RepoName}`
- update help in `ScriptsSettingsPage.cs`
- factor out methods `SelectOne`
- handle `module == null` for `{WorkingDir}`
- new NUnit tests
- Build 83eee9de9ca55b6e70253aec0218473212a218e1
----
=> Add script options c/sRemoteBranchName and RepoName

GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs
Fixes #6726
- use the `FormChooseTranslation`'s fallback in case of empty selection
- manual
- Build 3972aa02f5e29c9a4256ff56d51eb42219a636ea
----
=> Check for empty language selection

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitUIExtensions.cs
Closes #6799
- Rewrite the callsite to use `InvokeAsync` instead, that switches the execution context to the UI thread.
----
=> Deprecate and remove InvokeAsyncDoNotUseInNewCode

GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
before renabling the the FileWatcher for GitStatusMonitor
Fixes #6812
FileSystemWatcher is deactivated when the need for an update is determined and restarted when the timer fires and GE is to start a new git-status.
When (re)activating FileSystemWatcher the control raises an exception if the directory does not exist.
This change skips starting file system watcher (and git-status) and relies on the periodic 5 minute timer retry. (Normally, if a directory is no longer available the user should know about it and refresh if necessary.) 
Manual (see the issue).
----
=> Check that directory (still) exists

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs
Resolves #1391
Previously, images were displayed as binary diffs, except some in
FormCommit:  .png and new worktree images
Other:
* FormCommit always show the worktree commit for index .png
* Show all images in FormCommit
(i.e. show index images and changed other than .png)
* Regression from a94a30af90ddcb8bad08220e171af20fd1f31b19 (ObjectId)
where blob guid were ignored if existing "cache miss" and attempted to be used if null
(not sure where this is seen, blob id is not always fetched though)
* Combined guid should never be used to get file blob guid - assert added
* openWithDiffTool action were not called from stash and RevisionDiff
Manual, change and stage image files
----
=> Show changed images in all diff tabs

GitUI/CommandsDialogs/FormCreateBranch.Designer.cs, GitUI/Translation/English.xlf
make all checkboxes of the form work the same standard way
by setting CheckBox.Text instead of a separate Label
in order to indicate the focus and to make the hotkey work directly 
(I know this won't win a design price. Though I think it's not worth breaking the table layout and trying to align a left-labeled CheckBox under DPI scaling.)
`Checkout after create` _is_ focused:
- manual
- Build 7b273006d0221522e6fb0a5e6097afbcf777965b
----
=> FormCreateBranch: Improve UX of CheckBox "Checkout after create"

GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/Translation/English.xlf
Closes #6687
- KDiff3 was unbundled few versions ago, and some users no longer have a diff/merge tool installed.
Until now the "resolve conflicts" dialog did not check whether a configured tool physically existed in the system.
An error dialog is shown to the user if the tool is absent.
- Enhance error messages
- manual
----
=> Fix 6687 diff tool not configured

GitCommands/Settings/FileSettingsCache.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs
Fixes #6783 
* Use Path.GetTempFileName() instead of a temp file in the settings directory to avoid various access errors.
* Ignore copy errors to create the backup file, if the settings file is in a directory where no new files can be created.
* If the settings file has no valid path, an exception would be raised. Not seen in any logs, seen when reviewing other occurrences of #6834 .  
Manual
----
=> SettingsCache: Tempfile in temp dir

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/CommitDialogSettingsPage.cs, GitUI/Translation/English.xlf, UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs
Fixes #5908
Supersedes #6539
- do not skip empty lines of commit messages
- rename to `AppSettings.EnsureCommitMessageSecondLineEmpty`
- factor out method `FormatCommitMessageFromTextBox` and add tests
- NUnit tests
- manual
- Build 6aa762c35e6bdf63cfda6e560c4f364d7e883bce
----
=> Retain newlines in commit message

GitCommands/ExternalLinks/ExternalLinksManager.cs, GitCommands/GitCommands.csproj, GitCommands/Remotes/AzureDevOpsRemoteParser.cs, GitCommands/Remotes/GitHubRemoteParser.cs, GitCommands/Remotes/RemoteParser.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.resx, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/AzureDevopsExternalLinkDefinitionExtractor.cs, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/CloudProviderExternalLinkDefinitionExtractorFactory.cs, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/CloudProviderKind.cs, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/ExternalLinkDefinitionExtractor.cs, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/GitHubExternalLinkDefinitionExtractor.cs, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/ICloudProviderExternalLinkDefinitionExtractor.cs, GitUI/CommandsDialogs/SettingsDialog/RevisionLinks/ICloudProviderExternalLinkDefinitionExtractorFactory.cs, GitUI/GitUI.csproj, GitUI/Properties/Resources.Designer.cs, GitUI/Properties/Resources.resx, GitUI/Translation/English.xlf, Plugins/GitHub3/GitHub3Plugin.cs, UnitTests/GitCommandsTests/GitCommandsTests.csproj, UnitTests/GitCommandsTests/Remote/AzureDevOpsRemoteParserTests.cs, UnitTests/GitCommandsTests/Remote/GitHubRemoteParserTests.cs, UnitTests/GitUITests/CommandsDialogs/Settings/AzureDevOpsExternalLinkDefinitionExtractorTests.cs, UnitTests/GitUITests/CommandsDialogs/Settings/GitHubExternalLinkDefinitionExtractorTests.cs, UnitTests/GitUITests/GitUITests.csproj
- Being able to easily add revision links for GitHub and Azure DevOps services
That create:
Result: 
- Manual and some Unit tests
- Build dee6de4cdfb281f0b42bb102ae9ea295ae032b98 (Dirty)
----
=> Add revision links templates for GitHub and Azure DevOps services

GitUI/UserControls/FileStatusList.Designer.cs, GitUI/UserControls/FileStatusList.cs
Fixes #6532
- hide `FilterWatermarkLabel`, too, if `FilterComboBox` is invisible
- make its appearance the same as of "There are no unstaged changes"
- manual
- Git Extensions 3.2.0.918
- Build b7cd26f9f860aa3f1423e8475ca1c08ad8987cf2 (Dirty)
----
=> FormCommit: Fix overlapping labels

GitUI/CommandsDialogs/SettingsDialog/Pages/DetailedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/DetailedSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs, GitUI/Translation/English.xlf
- Move email settings from `General` to `Detailed` 
* ![image](https://user-images.githubusercontent.com/4403806/60396562-6d1c3980-9b86-11e9-9aef-074715f8e936.png)
* ![image](https://user-images.githubusercontent.com/4403806/60396551-54138880-9b86-11e9-9471-5fa1502d1671.png)
* ![image](https://user-images.githubusercontent.com/4403806/60396557-5d045a00-9b86-11e9-8142-4910b453836c.png)
----
=> refactor: Move email settings from General to Detailed

Plugins/GitUIPluginInterfaces/ObjectId.cs, UnitTests/GitCommandsTests/Git/ObjectIdTests.cs
Relates to #6872.
- Make `ObjectId.TryParseAsciiHexBytes` return `false` when various invalid inputs are provided, rather than throwing an exception.
- Added unit tests.
----
=> Fix TryParseAsciiHex bytes bounds check

GitCommands/RevisionReader.cs, GitUI/CommandsDialogs/FormFileHistory.cs
This is a cherry-pick of #6807 for master
Author unchanged from @fschmied (cla signed)
Quickfix for #5944 based on release/3.1, no tests, no big refactoring.
Intended as a placeholder until #6132 is done.
See #6807 - restore follow rename files
Manual
Note:
If test cases must be added to merge this, someone else should drive this PR
----
=> Fix #5944 by fixing --follow and revision reading

GitCommands/Git/GitVersion.cs
Set recommended version to 2.22
- Review of Release Notes.  
No major changes in this release, similar to the stable 2.21.0. 
git-diff --no-index --dir-diff is no longer allowed, not used together in ST.
- Use of Git - to be in use for week or so before removing WIP
n/a
----
=> Set recommended Git version to 2.22.0

GitUI/GitUI.csproj, GitUI/Properties/Resources.Designer.cs, GitUI/Properties/Resources.resx, GitUI/Translation/English.xlf, GitUI/UserControls/BlameControl.Designer.cs, GitUI/UserControls/BlameControl.cs
Partly fixes #6605 (other part will be fixed by #6807 or #6132)
- Fix "Blame to previous revision" behavior to select the first commit before the one introducing the changes (so the previous, no!?!) as explained in https://github.com/gitextensions/gitextensions/issues/6605#issuecomment-493797272
- While I was at it, I have added a context menu item to blame selected revision to make explicit what could be done by double-clicking (because I realised with https://github.com/gitextensions/gitextensions/issues/6832#issuecomment-504363872 that it was probably not evident for new users)
For the 2nd point (the 1st change nothing to the ui)
Focus only on the menu (and not the colors of the lines)
- Manual
- Build 8e4b5fc9c5f62b1bb3f937f4e49819b081863c9b (Dirty)
- Git …
=> Blame: Fix "blame previous revision" feature

GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.Designer.cs, GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/Translation/English.xlf
Fixes bad display of "Form commit template settings"
Redesign form commit template settings: 
- Use tabs to separate the 2 different kinds of settings
- Fix bad display due to dpi scaling
- More size for the Regex textbox
- rename the menu entry label to give more information
By default when opened:
When resized:
- Manual 
- Build 0877b85d6bb0417d567c29e6eea557ad7edbe0fb
=> Redesign form commit template settings

GitUI/CommandsDialogs/FormStash.Designer.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/FormStash.resx, GitUI/GitUI.csproj, GitUI/Properties/Resources.Designer.cs, GitUI/Properties/Resources.resx, GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.cs
Fixes #6902
- In the file list of a stash, add a contextual menu that allows the cherry pick of a file's changes.
nothing
PS: I don't know why but that also add a 'Sort by' menu item... but that options works, so I didn't investigated on that subject.
- Manual
- Build 12ee015dbb06e3fbff2752d3bc12fc2ceea5f87b (Dirty)
=> Stash: Add cherry pick of file's changes

GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/GitUICommands.cs, UnitTests/GitUITests/CommandsDialogs/FormFileHistoryControllerTests.cs
Fixes #6458, #6892 and #6815
Alternative for #6893 (like discussed in https://github.com/gitextensions/gitextensions/pull/6893#issuecomment-509390885 )
- Fix FileHistory/Blame for files not existing in the working directory
The bad behavior comes from the fact that `TryGetExactPath()`
changes the path to the file system path (if not existing, the path is cleared)
- Improve readability of unit tests on `TryGetExactPath()`
/cc @gerhardol  @RussKie
=> Fix different problems around FileHistory/Blame

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitVersion.cs, UnitTests/GitCommandsTests/Git/GitCommandHelpersTest.cs
now that we recommend v2.22 (#6769) that deprecate "--preserve-merges"
See:
* for option deprection: https://github.com/git/git/commit/fa1b86e45743fd5895c33adcd3769782e608bb40#diff-c7361e406139e8cd3a300b80b8f8cc8dR1220
* for some doc: https://stackoverflow.com/questions/15915430/what-exactly-does-gits-rebase-preserve-merges-do-and-why/50555740#50555740
- Manual (not heavily)
- Updated unit tests
- Build 8ee3620d3fa4b960b24240cb5ccf1822c01a33f7
- Git 2.20.1.windows.1 (recommended: 2.22.0 or later)
=> Add support for "--rebase-merges" for newest version of git

GitUI/CommitInfo/CommitInfo.cs
Closes #6898
-  Absent of an obvious way to fix it, hardcode the fix - add an extra space at the bottom
- manual testing at various scale factors
----
=> fix: Commit message incorrect height at 150% scale factor

UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegrationTests/AppVeyorIntegrationTests.csproj
Fixes build issue when building from scratch. Didn't create an issue for this pull request, because it is just a build issue, not user facing, not production code either.
- Remove the duplicate NSubstitue reference from the csproj
- Build the project to make sure can build successfully
- VS2019
----
=> Fix: Build error due to duplicate NSubstitue entry in csproj

contributors.txt
contributors.txt pushed as a separate PR (relates to PR #6949)
----
=> signed contributors.txt

Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.Designer.cs, Plugins/ReleaseNotesGenerator/ReleaseNotesGeneratorForm.cs, contributors.txt
Fixes #4444
The ReleaseNotesGenerator is initialized with a default "HEAD" text for the To field.
Another option could have been to completely remove the To field validation (blank is an "alias" for HEAD) but IMHO having an explicit default value provides a more clear/usable experience.
- Manual
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
----
=> ReleaseNotesGenerator plugin To defaults to "HEAD"

GitCommands/RevisionReader.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs, GitUI/Translation/English.xlf, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Fixes #6826
Replace #6854
Add option to sort commits by author date in the revision grid. Add menu-option and Settings checkbox to access setting. Added tool-tip in Settings to warn of potential performance impact.
Tested on repo where commit-dates were not the same as author-dates. Appearance was as-expected. Tested enabling and disabling option; the commit sorting responded as expected.
GIT 2.17.1.windows.2
Windows NT 10.0.17763.0
.NET 4.7.3416.0
----
=> Add an option to sort commits by author date in the revision grid

GitUI/CommandsDialogs/FormInit.cs, UnitTests/GitUITests/CommandsDialogs/FormInitTests.cs
Fixes #6955
- on the create new repository dialog I've improved the directory textbox validation in order to prevent the crash described in #6955 
- Manual tests
- Added some unit tests for the path validator
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
----
=> improved validation on create new repository dialog

GitUI/Editor/FileViewer.cs, GitUI/Translation/English.xlf
Closes #6982
- Do not crash the app if a repository contains illegal characters.
- clone the reported repo and reproduce the issue
- apply the fix and confirm the app no longer crashes
----
=> fix: Illegal characters in path

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs, GitUI/Translation/English.xlf
Fixes #6443 
- Add "default pull action" config in setting dialog
- Use the new combo box to set a pull action and back to the main window to check if the pull button on toolbar shows the correct action icon. And then click the button to see if the action we set is triggered.
- GIT 2.22.0.windows.1
- Windows 10 build 18362.239
----
=> Add "default pull action" config in setting dialog

GitUI/SpellChecker/TextBoxHelper.cs
Fixes #6895
- "EM_LINELENGTH message" expects a character index and not a line index: https://docs.microsoft.com/en-us/windows/win32/controls/em-linelength
- This messed up the highlighting in the commit window
- Manual
- Build 79324b84f01fd3ba5dd0276228dee6e38372c0f7 (Dirty)
----
=> Fix: Commit Dialog Spell Checker

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
TortoiseGit changed the name of the Git/Merge executable in v1.8 (2013).
TortoiseMerge.exe -> TortoiseGitMerge.exe
When selecting tmerge as difftool (or TortoiseMerge as mergetool) and clicking Browse, GE searced for the old executable name, changed in 2013.
Using Suggest was OK.
Note: There is still compatibility when selecting Suggest to select tgit <1.8 or TortoiseSVN if no TortoiseGit >=1.8. This could be removed. I added a comment, this could be removed.
Manual
----
=> TortoiseGitMerge.exe old default name

GitUI/CommandsDialogs/FormPush.cs
Fixes #6367 
When the Push-Dialog is open and an error occured after clicking "Push", the Push-Dialog will stay open to allow the user to take changes that may lead to a succesfull push. Only a succesfull push will make the dialog close.
- Manual
- Build fafe69557b0f9e79603b7f42bb1448fb3dc8d9a0 (Dirty)
----
=> Fix: Keep push dialog open on failure (#6367)

GitUI/CommandsDialogs/SettingsDialog/AutoLayoutSettingsPage.cs
- Align labels to the top because labels on multiline text fields are misleading...
- Manual
- Build eb91b7b1e0643f9bd19ac8f44bbcb8eb797e65d3 (Dirty)
=> Settings: Display label to the top to make UI more readable on multiline controls

GitCommands/CommitTemplateItem.cs, GitCommands/CommitTemplateManager.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/GitUICommands.cs, Plugins/GitUIPluginInterfaces/IGitUICommands.cs, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs, UnitTests/GitCommandsTests/CommitTemplateManagerTests.cs
- Display icons (especially the one of the **Jira** commit hint plugin) in commit templates menu items
PS: I have created because I'm mostly interested by the api change that it introduce (most of the code is common, there is just one line to update in the commit hint plugin).
With provider:
Without provider (don't block on the Azure DevOps icon, this PR add Jira icon but I only can test it with the AzureDevOps plugin I'm developping...):
- Manual
- Build 4bb4263d32fd2787bb14c191fe27f69166e88393
=> Display icons in commit templates menu items

Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs
If the value contains a `\r\n`, the result will contain `\r\r\n`
which duplicate blank lines (in multi-line controls) at the loading and each time a settings is changed and saved...
- Manual
- Build 885dbb88d9ed3e02e77b1291df54a634ac159e0e
=> Fix potential bad end of line replacement

GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
If merge/diff tool paths enclosed in quotes, clicking on "Suggest" button would crash the app.
Fixes #7000
- Strip quotes from paths before attempting to suggest.
- manual entering paths enclosed in `'` and `"`
----
=> fix: Crash when suggest merge/diff tool paths

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormPull.cs, GitUI/Script/ScriptInfo.cs
Fixes #4909
Additional scripts that should be executed before/after fetch can be added.
Manual
- Build bace57f405cdd2f5675278f88ba2947e8d5bb852
----
=> Add scripts for BeforeFetch and AfterFetch

Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
- Fix a bad check if settings exists
- open the settings if not configured
- manual
- Build 885dbb88d9ed3e02e77b1291df54a634ac159e0e
=> Open jira settings when not configured

GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
`DiffViewerLineNumberControl` did not handle when `MaxLineNumber `was 0. Either an empty file can cause this (in this case `_diffLines `is empty so no problem) or a file where diff hunks were lost due to encoding errors.
Fixes #7023
Change the current getter:
``` csharp
if (_visible && _diffLines.Any())
{
int maxDigits = (int)Math.Log10(MaxLineNumber) + 1;
return ...;
}
```
to
``` csharp
if (_visible && _diffLines.Any())
{
int maxDigits = MaxLineNumber > 0 ?  ((int)Math.Log10(MaxLineNumber) + 1) : 0;
return ...;
}
```
Tested manually.
=> fix: Overflow error in Commit Dialog

Bin/set-telemetry.ps1, Setup/UI/TelemetryDlg.wxs, Setup/UI/WixUI.wxs
Fixes #7079
* Make installer compatible with PowerShell 2.0 (needed on Win7 SP1)
* General: correct dialog order when using "back" button.  Clicking "back" in  `GitEx_VerifyReadyDlg`  jumped back by 2 dialogs to `GitEx_SSHClientDlg`.
The correct sequence is: `GitEx_SSHClientDlg` <-> `GitEx_TelemetryDlg` <-> `GitEx_VerifyReadyDlg`.
- Built MSI and verified correct installation on both Win7 and Win10 
- Git Extensions 3.2.0.67
- Build cd95abe635787a35f3574adf9d012436d0cfe950
- .NET Framework 4.8.3928.0
- Git Extensions 3.2.0.67
- Build cd95abe635787a35f3574adf9d012436d0cfe950
- Git 2.20.1.windows.1 (recommended: 2.22.0 or later)
- DPI …
=> Fix installer for Win7

Plugins/Statistics/GitStatistics/FormGitStatistics.Designer.cs, contributors.txt
- Fixed scrolling of commiters in statistics plugin
- Manual
- GIT 2.20.1
- Windows 10
----
=> Fix scrolling for committers label in statistics plugin

GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes #7087
- Ignore difftool for combined diff
- Select GE b33a12e3af16cc1164ebfa2562f06b485421fbcf
- Rightclick a file in CombinedDiff
- Verifiy that diff in menu is disabled
- Verify that nothing happens (no error or difftool) when pressing F3, Shift-F3, Shift-Alt-F3
- Select both a file in CombinedDiff and normal commit, rightclick
- Verifiy that diff in menu is disabled
- Verify that the  when pressing F3, Shift-F3, Shift-Alt-F3, that the normal diftool is shown only
----
=> Ignore difftool for CombinedDiff

Setup/Build.cmd, Setup/BuildGitExtNative.cmd, Setup/MakeInstallers.cmd
Fixes a problem where a call to hMSBuild would be the last thing executed in a batch file
- From what I gather from reading about executing nested batch files is if you simply call a batch from withing another batch file then it's executed inline and if there is an `exit` in the nested file the root batch exits as it's as if there was just one big batch file. To properly executed a nested batch files one needs to:
- Use `call` to execute `hMSBuild`
more on this: https://stackoverflow.com/questions/1103994/how-to-run-multiple-bat-files-within-a-bat-file
This raises another question... are these batch files used at all? Without this fix `MakeInstallers.cmd` would not produce an installer for me.
=> correctly call hMSBuild batch file

GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/Translation/English.xlf
"Include untracked files in stash" is only used in autostash, not in the stash dialog.
It setting this in Settings, creating a stash manually will not stash changes
(can be done in the menu or ctrl-alt-up so do not even see the stash form)
stash -> autostash
Manual
----
=> Clarify Settings-Stash label

GitUI/CommandsDialogs/FormPush.cs, GitUI/Translation/English.xlf
Fixes #3934
Changed `Force push` to `Force push with lease` in `Push was rejected` dialog (including Russian translation).
----
=> Fix 3934 add force push with lease to the push dialog

GitUI/Translation/English.Plugins.xlf, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/Settings/BoolSetting.cs, Plugins/GitUIPluginInterfaces/Settings/ChoiceSetting.cs, Plugins/GitUIPluginInterfaces/Settings/CredentialsSetting.cs, Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs, Plugins/GitUIPluginInterfaces/Settings/PasswordSetting.cs, Plugins/GitUIPluginInterfaces/Settings/PseudoSetting.cs, Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs, Plugins/GitUIPluginInterfaces/UserControls/CredentialsControl.cs, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
Fixes some paper cuts felt when developing a plugin (so I hope that you won't ask we to do one PR for each... 😉 but review is easier commit by commit).
if we let the Setting(s) classes create the controls.
Otherwise, it could will trow a NRE if we access it to get the current value
i.e. that don't save a value in the settings files.
It is used to easily display a control that is not a setting (linklabel, text,...)
PS: Also, solve problem linklabels truncated horizontally of vertically if the good size is not set
(because the size no more have to be set)
=> and apply it to the "Jira Commit Hint" plugin
PS: I'm not fond of the name of the class. If someone have a better idea (`DisplayOnlySetting` ?)
to specify other things than the currently "User name" / "Password".
For example: "email" / …
=> Make plugin settings development easier

GitCommands/Git/GitModule.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs, GitUI/Translation/English.xlf
Fixes #6991 
Use --histogram instead of --patience for the setting.
See issue for motivation.
TBD Is a setting tooltip required?
If so, a proposal
```
Use --histogram for git-diff, replacing the default algorithm as well as the git config diff.algorithm option.
```
Check the Git Command log that --histogram is used instead of --patience.
----
=> Replace git-diff patience with histogram

GitUI/Translation/English.Plugins.xlf, GitUI/Translation/English.xlf, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
To be merged after #7039 will be (just the last commit is specific to this PR).
JiraPlugin: Fix way to define TranslationString that prevent translation
+ remove TranslationString redundant with settings caption
(which is translated when defined in a private field!)
- Some more strings appears in `English.Plugins.xlf`
=> Jira commit hint plugin: fix some string not translated

GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Fixes #7046
Since the copy to clipboard menu is filled on the `DropDownOpening` event, it appears empty (has no triangle/arrow at the right) at startup. By adding a dummy element in the constructor, the triangle is present at startup indicating it as a drop down submenu.
I removed the adding of a dummy revision (according to the comment to allow shortkeys, see #5422 and #5444) since it does not seem to do anything anymore as `_revisionFunc` is not set. Shortkeys (Ctrl+C) are working nonetheless.
See #7046 
Manually
- Git Extensions 3.1.1.6049
- Build 2f872105b4eb42421d9fdafd68e90a9e27d20d96
---- …
=> Let the copy menu entry appear expandable at startup

Bin/set-telemetry.ps1, Setup/UI/TelemetryDlg.wxs, appveyor.yml
Resolves #7120
* There are few issues with the install script related to configuring the telemetry settings.
1. On W7 there is only PowerShell 2.0 (that is what ships with .NET 2.0). On the later versions of OS there are different versions of PowerShell and thus requiring a specific version would lead to failures.
2. A problem related to the logic responsible for self-removal
* First `$MyINvocation.InvocationName` returned different and unexpected         values when a script is run not from a command line but invoked as a     script-block. In the latter case, `$MyINvocation.InvocationName` is     set to `&`.
* Secondly the installer somehow would fail to remove the script     (permissions?)
The self-removal logic is removed.
* Bump the version to 3.2.1 to ensure the new fix flows through …
=> fix: Unable to intstall new version

GitExtensions/Program.cs
This will allow starting with the dashboard in the debugger
This was changed in #4740 (see the discussion there for further information), changed in #4870 (for #4809) and regressed in #5722.
This change still allows commands with arguments to find the current Git dir but starts dashboard if configured so without arguments.
In some sense, this will break command line start without arguments assuming that "browse" will start (probably not so before 3.0 though).
The workaround is not too difficult, add "browse" as an argument (and current dir will be used if in a repo).
Manual
By default "browse" is an argument for the Debugger.
----
=> Set repo workingdir from env only if cmd line arguments

GitCommands/Git/GitModule.cs, GitCommands/PathUtil.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/GitUICommands.cs, UnitTests/GitCommandsTests/Helpers/PathUtilTest.cs
Fixes #7086
* Use .NET Path.GetDirectoryName instead of PathUtil to also detect root directories
The existing function could have been adapted (by removing a few lines), but the standard function should be used. 
Manual
----
=> PathUtil.GetDirectoryName did not accept root dirs

GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs, GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs, GitUI/Translation/English.xlf
Refactoring
Somehow related to #5919
GE has a lot of hardcoded support for KDiff3. That made sense when kdiff was bundled with GE but has really no effect now and is just confusing and makes other changes harder.
There is also some duplication of code.
At startup and in the settings form, GE tries to set kdiff3 if no diif or mergetool is set.
(The situation that kdiff3 is a configured tool and that no tool is set is not a use case to optimize for.)
To let Git handle the tools supported (the list in GE is not same as in Git, also diff like tmerge -> tortoisemerge) and to cleanup is another MR.
(as well as better handle custom tools)
This is WIP as it should not be merged before 3.2
Other changes may be added to the PR
If no diff or mergetool, send users to the Git config settings form and …
=> Remove KDiff3 hardcoding

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/Translation/English.xlf, GitUI/UserControls/WarningToolStripItem.cs
Fixes #7110
- extent `WarningToolStripItem.Text` with action what will happen on click, i.e.
- "continue" rebase, bisect or patch apply
- "resolve" merge conflicts
- add hotkey `Alt+O` to these `WarningToolStripItem`s
- Build 54b165d0ecfc2161f034d2c6aee1aee50df03bef
----
=> Add hotkeys for continue rebase, resolve merge conflicts etc.

GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Fixes #7169 
Set TortoiseGitMerge.exe
Should be cherry picked to 3.2
Manual
----
=> exename not set for tortoisemerge

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormResetChanges.Designer.cs, GitUI/Translation/English.xlf
- turn mnemonic of button `Commit & push` form `Alt+O` into `Alt+P`
- add mnemonics for all labeled buttons
- manual test
- Build 3e02aadd0814cd712929d70ef741c6b7bc95aa4d
----
=> Improve some mnemonics of commit dialog

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/GitModuleControl.cs, GitUI/GitModuleForm.cs, GitUI/Script/ScriptOptionsParser.cs, GitUI/Script/ScriptRunner.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/Script/ScriptOptionsParserTests.cs, UnitTests/GitUITests/Script/ScriptRunnerTests.cs
Fixes #6285
1. commit: refactoring
- ScriptOptionsParser.GetCurrentRevision: remove argument that is always null
- ScriptRunner.RunScript: positive logic in conditions for message
2. commit: resolve regressions introduced by 1b8bb93c7121cd291a17303edfdd313c8edb9f88
The regression was a NRE instead of the message (see screenshot).
A second minor regression was that the options were searched without the surrounding '{' and '}'.
- ScriptOptionsParser to do all parsing (correctly) with factored out methods
- script.Arguments always in plural
3. commit: feature implementation
- GitModuleForm and GitModuleControl to provide the RevisionGridControl instance to ScriptRunner
4. commit: tests with a litte refactoring
5. commit: bugfix
- The script options {cHash}, {cMessage}, {cAuthor}, …
=> Execute scripts also if RevisionGrid is not focused

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/Translation/English.xlf
Fixes #7104
Fixes #6993
- add button to enable editing the special commit message of `fixup!` and `squash!` commits
- add/adapt hotkeys for buttons
- allow `Amend commit'` for any `CommitKind`
- reset `CommitKind` after commiting without closing `FormCommit`
- slightly off topic: add more test cases for empty lines in commit messages (addendum to #6877)
(different message font due to different font settings vs. portable build)
- manual tests
- Build 79dee30803b7eb1ae0ff5999ff3bb962a9cacff7
- .NET Framework 4.8.3815.0
----
=> Unblock special commit message

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Seen in CommitInfo
See https://github.com/gitextensions/gitextensions/pull/7186#issuecomment-535709962
Remove + in front of branches that are checked out in other worktrees
See #7186 
Manual
----
=> Branch list could contain '+'

GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/Translation/English.xlf
Fixes #6687
(part 3)
#6687 was partly fixed in #6869 (3.2) but occasionally still occurs.
When testing this change, I found that the remaining problems are mostly caused by kdiff3 hardcoding and more or less resolved by #7009 
Still, I believe this PR makes sense.
GE creates exceptions when failing to run processes, for instance when the mergetool does not exist.
As the executable may not have full path, it is not possible to make a generic check in Executable()
Each call to Executable().Execute() has to be checked separately
NBug
Manual
Due to #7009 and #6869 you have to force the problem:
* Make sure you have a mergeconflict
* Start merge and let MergeConflict open
* Rename the mergetool
* Click Merge button (the other buttons were already handled)
---- …
=> Popup when error staring mergetool

GitUI/FormStatus.cs
Fixes #6675
ConEmu raises exceptions in some situation, see many duplicates to #6675 (and a milestone)
All the #6675 exceptions occurs in Done(), when the Git command has already executed.
I have tried to recreated but not succeeded, but saw a coworker getting this problem once when quickly dismissing the popup. It should not be very unsafe assume that this is the core problem, no real action occurs after the form is dismissed.
Therefore, it should be OK to catch and ignore the ConEmu exception.
Code review
----
=> Catch ConEmu exception for Done()

GitUI/UserControls/RevisionGrid/IndexWatcher.cs
Fixes #7235
Only enable GitIndexWatcher when directory exists
Similar changes already done in 3.2 (do not know how this was missed)
Manual
----
=> GitIndexWatcher: check that directory exists before enabling

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs, GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs, GitUI/Translation/English.xlf
Fixes #6864
- Option in the confirmations setting menu to not ask for a confirmation when switching the worktree
Manual
- Build 429a4f06e30478c41bdfaf1f501de175b82b8126 (Dirty)
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
- .NET Framework 4.7.3460.0
----
=> Dont confirm switch worktree option

GitUI/CommandsDialogs/FormCommit.cs
That prevent a boring question to be asked to the user
because the commit message doesn't follow the regex when
"fixup!" or "squash!" prefixes are used.
- Manual
=> Exclude "fixup!" and "squash!" prefixes from commit message RegEx validation

Plugins/GitUIPluginInterfaces/ISettingControlBinding.cs
because we don't control the controls lifecycle
and the settings controls are disposed when settings are closed.
It depends on how the settings control is defined but could prevent exceptions
(and make plugins easier to write)
- Manual
- Build cacce7f5baa67af9f3863bc033eeee6b3b2bbef5 (Dirty)
- .NET Framework 4.8.3928.0
=> Settings: Regenerate the Controls when previous instance was disposed

GitCommands/CommitMessageManager.cs, GitUI/CommandsDialogs/FormCommandlineHelp.resx, GitUI/CommandsDialogs/FormCommit.cs, GitUI/GitUICommands.cs, UnitTests/GitCommandsTests/CommitMessageManagerTests.cs
This PR extends the command line commit command to enable a commit message. 
I was a bit in doubt whether we should include a new field in `FormCommit.cs` as I have done, or simply modify the `MergeOrCommitMessage` on the `_commitMessageManager`. The later will save the message to disc though and this is why I opted out of the idea
----
=> Add ability to specify commit message on the command line

GitCommands/Git/GitModule.cs
due to "orphan" filename lines that has for effect to overwrite good commit data
by incomplete ones **when "Detect move and copy in all files" is enabled**.
For example, command:
`git blame --porcelain -M -C -w -l "18fcca6d89c2d38ac1830697b5da3f78630b226e" -- "GitUI/Translation/English.Plugins.xlf"`
returns (part of the file):
```
8f8393c283e7ad60c02805182d6778e5fc0c8b28 180 13
<trans-unit id="MsBuildEnabled.Caption">
b1d567eb22570bd2f278d779695f4556a27fb2ce 7506 14 3
filename GitUI/Translation/English.xlf       <= orphan line that breaks the blame
<source>Enabled</source>
b1d567eb22570bd2f278d779695f4556a27fb2ce 7507 15
<target />
b1d567eb22570bd2f278d779695f4556a27fb2ce 7508 16
</trans-unit>
8f8393c283e7ad60c02805182d6778e5fc0c8b28 184 17 12
<trans-unit id="MsBuildPath.Caption">
```
- …
=> Blame: Fix missing commit metadata on some commits

UnitTests/GitUITests/CommandsDialogs/FormFileHistoryControllerTests.cs
Test case TryGetExactPathName_Should_output_path_with_exact_casing() uses the local file system for comparisons.
The test for "c:\Program Files (x86)\Microsoft.NET\Primary Interop Assemblies" occasionally fails for me for unknown reason (when debugging it is OK), similar in #7049). (An alternative to this PR would be to remove this specific test only.
It is possible to install to other paths, the test assumes that the PC uses standard paths.
Similar tests are already done in TryGetExactPathName_should_check_if_path_matches_case()
Note that TryGetExactPathName_Should_handle_network_path() could fail too, but there are no tests replacing that, so it is kept in this PR.
----
=> Remove test assuming local file paths

GitUI/UserControls/FileStatusList.cs, UnitTests/GitUITests/CommandsDialogs/FileStatusListTests.cs
Fixes #7246 
Fixes #6212
- Set FileStatusListView.FocusedItem, too
- manual test (see STR in #7246)
- added NUnit test
- Build 420bcdfe3fab4baef6a69b62698151b3170c2b35
----
=> Commit dialog, FileStatusList: Fix up/down selects unexpected file

GitCommands/Git/GitModule.cs, GitCommands/Remotes/ConfigFileRemote.cs, GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs, Plugins/GitUIPluginInterfaces/Remote.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Fixes #6922
Allow multiple push url in git-remote
The pushurl are not really used (can be used to display the GitHub/BitBucket icon in sidepanel, updated that logic to only use fetchurl).
Manual (test is updated)
See issue with how to reproduce (like add a repo on gitlab).
----
=> Allow multiple push url for git-remote

GitCommands/ArgumentBuilderExtensions.cs, GitCommands/Git/ExecutableExtensions.cs, GitCommands/Git/GitModule.cs, GitUI/UserControls/FileStatusList.cs, UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs, UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs, contributors.txt
Work around for Windows command line length 32767 characters limitation
Fix #6593: GitExtension Exception resetting 1500 files in Diff tab.
- Work around for Windows command line length 32767 characters limitation
- Add GitArgumentBuilderExtensions.BuildBatchArguments to wrap long commands in to multiple child commands
- Add RunBatchCommand to run commands in batch 
- Add GitArgumentBuilderTest fixture
- Manual test
- GIT: 3.2
- Windows 10 64bit
----
=> Fix #6593: GitExtension Exception resetting 1500 files in Diff tab.

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Fixes #7207 
- Implement codepoint-escaping function similar to git's `quote_c_style` 
- Pass escaped filenames to `git-update-index`
- Tested manually to ensure expected behavior from #7207 using filenames containing both unicode and ASCII characters
- Added tests similar to existing tests for UnescapeOctalCodePoints
- GIT 2.23.0
- Windows 10
----
=> Implement quotePath-like codepoint escaping

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/GitUI.csproj, GitUI/UserControls/EnterEventArgs.cs, GitUI/UserControls/FileStatusList.cs
Fixes #7266
- It appears that first item in staged/unstaged file status list should be selected only if `Entering` the control by keyboard as when using the mouse you either click on specific item to select it or on an empty space to deselect everything
- Add overridden `Enter` event to `FileStatusList` which would provide extra details as to how control was entered
- Only select first item if control wasn't entered by mouse
=> prevent flickering when selecting files in staged/unstaged FileStatusList

GitUI/FilterBranchHelper.cs, GitUI/Strings.cs, GitUI/Translation/English.xlf
to prevent an exception when the combobox is empty
Fixes #6680, #6931, #6964, #6988, #7177, #7204
- Manual
- Build 6cbbd91a7221cde0678773fb4a6b96583f076dac (Dirty)
=> Filter branches: display a placeholder when no branches found

GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
Part 2 of #7255 
(previously included in #7256)
Show multiple pushurl in the sidepanel
Follow up from #7214
GUI change only
----
=> Display multiple pushurl in the Remote sidepanel tooltip

ResourceManager/GitPluginBase.cs, TranslationApp/TranslationHelpers.cs
Closes #7286
- Fix a refactor regression - the translation app requires a parameterless constructor.
- Also add safe guards to the type iteration routine that ignore any failures.
Locally a lot of contributors would have custom plugins installed (e.g. `GitExtensions.PluginManager`) that does not belong to the main codebase and, thus, does not need to be translated.
The translation app would previously fail on these external types, and fail to update the translations as a result.
----
=> fix: missing method ResourceManager.GitPluginBase..ctor

GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs, GitUI/Translation/English.xlf
Fixes https://github.com/gitextensions/gitextensions/pull/6907#discussion_r301898228
- Remove use of possessive in "Cherry pick file's changes"
- Manual
- Build ff0e8eed0b4b577c62bbcd8469d62b31b29a6e4d
=> Remove use of possessive in "Cherry pick file's changes"

GitUI/CommandsDialogs/FormBrowse.cs, contributors.txt
Fixes #7257 
- Add an error message if ConEmu is missing instead of having a unhandled exception.
If ComEmu.exe is missing,Git Extensions shows the crash report window.
Now Git Extensions shows an error message that ask to reinstall application.
- Run the application with ComEmu.exe missing and click on the Console tab.
- An error message shall be shown.
- GIT git version 2.23.0.windows.1
- Windows 10 v 1903 18362.356
The message will need to be translated.
----
=> Fix #7257 ConEmu is missing

GitCommands/UserRepositoryHistory/RemoteRepositoryManager.cs
Fixes #7260 
Allow saving remote repositories with non-URL paths (e.g. local disk path) in the recent repositories list.
Tested manually to match the expected behavior in #7260 
- GIT 2.14.1
- Windows 10
----
=> Allow remote repositories with local disk path to be saved in recents

GitUI/Translation/English.Plugins.xlf, Plugins/GitFlow/GitFlowForm.Designer.cs, Plugins/GitFlow/GitFlowForm.cs, contributors.txt
Add new checkbox on GitFlow plugin: "Squash feature"
This checkbox enables the user to squash the merge commit form one feature to develop branch.
Simply adds the -S parameter to the git flow feature finish command
I think it can be userful :)
- GIT 3.2.1.6628
- Windows 10
=> Add Squash feature on GitFlow Plugin Form

GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
Fix #7250: Error when fetching pull requests from local branch
- Fallback to the first remote in the list when there's no current remote
- Manual test
- Build 00aa8df55d65c3318f45870a29129aba79529e81 (Dirty)
----
=> Fix #7250:  Error when fetching pull requests from local branch

Bin/set-telemetry.ps1, Setup/UI/TelemetryDlg.wxs
Fixes #7308
- cherry-picked abac1b4564a5166f0453fa3ee459769e8a199b6f & cedb5886f722349df047d87d90434e8326d8f4a2. These are the commits between v.3.2.0 and v3.2.1. They haven't been ported back into master branch yet.
- Add a check at the beginning of `set-telemetry.ps1` to verify the LanguageMode. In case it is anything different from `FullLanguage`, exit immediately with code 0. This means that the element `telemetryEnabled` **will not be written** to `GitExtensions.settings` during installation in that case.
- At first startup after installation, since the element `telemetryEnabled` is still missing in `GitExtensions.settings`, GE will act like the portable build and show the popup for telemetry. This was already implemented and I didn't change it.
- manual tests
- not relevant
---- …
=> Fix installer when PS is in ConstrainedLanguage mode

GitCommands/ArgumentBuilderExtensions.cs, GitCommands/BatchArgumentItem.cs, GitCommands/Git/BatchProgressEventArgs.cs, GitCommands/Git/ExecutableExtensions.cs, GitCommands/Git/GitModule.cs, GitCommands/GitCommands.csproj, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, UnitTests/CommonTestUtils/MockExecutable.cs, UnitTests/GitCommandsTests/ArgumentBuilderExtensionsTests.cs, UnitTests/GitCommandsTests/Git/ExecutableExtensionsTests.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Fix #3280: Optimize unstage/reset performance by git reset/unstage batch files (continue from batch processing in #6593)
Use RunBatchCommand & BuildBatchArguments from #7218 to fix performance issue with git reset/unstage individual files consequentially.
- Manual test
- Unit test cases
- GIT: 2.23.0.windows.1
- Windows: 10 x64
----
=> Fix #3280: Optimize unstage/reset performance by git reset/unstage batch files

GitUI/CommandsDialogs/FormBrowse.Designer.cs
Fixes #7130
- make `About` the last `Help` menu item again
- manual
- Build 63b6d216a875d1f51b240ca64e141a7409441656
----
=> Move tsmiTelemetryEnabled behind donateToolStripMenuItem

GitUI/Editor/FileViewer.cs
Part of #7322
Displaying hexdumps when viewing binary files (as well as when editing them...) is a nice touch to give an indication to the contents of a file in the repo that is not in text format. (In general though git-lfs should be used for binary files, do not store them in Git.)
However, the complete file is not interesting.
If you select a larger file like .nuget/NuGet.exe (5MB), it takes over 40s to display the file for me, with the spinner running. It seems like GE freezes.
This PR limits the display to the first 16384 bytes (1024 lines), which should be sufficient to display relevant information.
No configuration, save the file and use a dedicated hexeditor to see the complete file.
This cannot be an important feature as hexdump display has not been working properly (ever?), …
=> Truncate large hexdumps

ResourceManager/GitPluginBase.cs
Fixes #7286
Follow up from #7296 
The problem still occurs if the production PluginManager is installed in AppData, plugins are not loaded:
https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-544256364
This is not fixing the core issue that the PluginManager takes all plugins down, but it fixes the problem:
https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-544277915
**All credits to @NikolayXHD**
I just want to get this reviewed/merged to have a stable master
See #7213 
Manual
----
=> fix missing plugins

GitCommands/Git/GitModule.cs, GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/Translation/English.xlf, contributors.txt
Fixes #7326 
- GitCommands 
- GetPreviousCommitMessages allows filter by author
- GitUi
- Commit dialog: New option to show only my messages.
- Manual test 
----
=> CommitDialog: New Option "Show only my messages"

GitUI/CommandsDialogs/BuildReportTabPageExtension.cs, GitUI/Strings.cs, GitUI/Translation/English.xlf
by replacing html link by a link label 
(and not in an old version of Internet Explorer that have no credential stored)
+ link centered
+ open report wherever the user click on the tab page
+ translate the "Open report" string
- Manual
- Build cacce7f5baa67af9f3863bc033eeee6b3b2bbef5 (Dirty)
- .NET Framework 4.7.3460.0
=> Build Report: Open the report in the user browser

GitUI/CommandsDialogs/FormPush.Designer.cs, GitUI/CommandsDialogs/FormPush.cs
Fixes #7077
- Hide push checkbox cells when there's no local branches
- Manual test
- Build 81fe6435db607ed42c197390d34e085f3f658e33
----
=> Fix #7077: Hide push checkbox cells when there's no local branches

GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- Increase width of `Checkout` button slightly as it gets its last char clipped at 225% dpi
- Windows 10
- DPI 225%
=> increase FormCheckoutBranch Ok button size

UnitTests/GitCommandsTests/RevisionReaderTests.cs, contributors.txt
- ~Add parenthesis for correct expectedAdditionalData string null coalescing~
- Remove unnecessary null coalescing as concatenating null is allowed and does not produce a different string
----
=> Remove unnecessary null coalescing

GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/Settings/SettingsUserControl.Designer.cs, Plugins/BuildServerIntegration/TeamCityIntegration/Settings/TeamCitySettingsUserControl.Designer.cs
Fixes #7301
Corrected and verified that the TabOrder should be correct on the following pages
- "Git extensions"
-  General
-  Appearance
-  Appearance > Color
-  Appearance > Fonts
-  Revision Links
-  Build server integration
-  Scripts
-  Hotkeys
-  Shell extensions
-  Advanced
-  Advanced > Confirmations
-  Detailed
-  Detailed > Browse repository window
-  Detailed > Commit dialog
-  Detailed > Diff Viewer
-  SSH
-  Git
-  Git > Paths
-  Git > Config
-  Git > Advanced
-  Plugins
- Go to the "Tools" menu, then "Settings"
- Visit the General page, and hit the TAB key multiple times
- Control should move sequentially through all the settings
- Git Extensions 3.2.1.6628
- Build bc07663c3c893f1d896520e0bdcfbe35cfe4b729
- Git 2.18.0.windows.1 (recommended: 2.22.0 or later)
- Microsoft …
=> Incorrect tab order on multiple settings pages #7301

GitUI/CommandsDialogs/FormPull.cs
- use the proper window owner when showing the "fetch and prune all" confirmation dialog (to fix focus issues)
Fixes #7364 
- use the correct owner window to fix focus issues 
**N/A**
- built and interactively tested the fix
- Windows 10
----
=> Fix 7364: "Fetch and Prune All" confirmation modal has weird focus behavior

GitUI/CommandsDialogs/RevisionFileTreeControl.cs
-  ~Assume that `e.Node` may be null in first `if` like it's done in the second `if`~
- Don't assume e.Node is nullable
----
=> Don't assume e.Node is nullable

GitUI/Script/ScriptRunner.cs, Plugins/GitUIPluginInterfaces/IGitPlugin.cs
- add comment why the RevisionGrid cannot be refreshed for PowerShell scripts
- improve code readability
- no functional change
- Build 697478fd79be9d4b7d4518c1a8bf3583008d2f5f
----
=> Document that PowerShell scripts are run detached

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs, GitUI/GitUICommands.cs, GitUI/MessageBoxes.cs, GitUI/Translation/English.xlf
Fixes #7290
- Moved the "Update submodules on checkout" setting from Confirmation page to General page (Behaviour group).
- Verified the UI
- Tested the settings are not adversely affected by the change in UI.
----
=> Incorrect placement of  update submodules on checkout  setting #7290

GitUI/CommandsDialogs/FormCommit.cs, UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs, UnitTests/GitUITests/CommandsDialogs/ReferenceRepository.cs
Fixes #5115
When building the commit message history to display in the dropdown menu,
and the commit message is shorter than the maximum length allowed
but is a multi line commit message,
then the display is broken for all the menus items.
=> add a check that the commit message is multi line and must be shorten.
+ increase the length of text in the menu items because 50 char is too short
See the first menu item which is display onto 2 lines and so increase the height of all menu items:
- Manual
- Build bffb060100bbe3ab838b00d2a37810cb34e1638a (Dirty)
=> Commit messages menu: Fix (sometimes) broken display

GitUI/CommitInfo/CommitInfo.cs, UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs, contributors.txt
Fixes #7372
- Don't put duplicate keys in a dictory when building `CommitInfo.GetSortedRefs()`
- Add TestCase for duplicate refs in `CommitInfoTests.GetSortedRefs_should_remove_duplicate_refs()`
- There is a testcase in `CommitInfoTests`. It test a git output that contains duplicate refs
- GIT 
- Windows 
----
=> Skip duplicate ref entries when building the Sorted Refs Dictionary

GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs, UnitTests/GitUITests/CommandsDialogs/FormAddSubmoduleTests.cs, UnitTests/GitUITests/GitUITests.csproj
Fixes #6556
- use "git ls-remote" to get possible submodule branches
- add a NUnit test
- Build db1c36b00e745692448ef8b877dd0b3b858ad3b6
----
=> Add Submodule: Fill combobox with branches regardless of the repo URL type

GitUI/CommandsDialogs/FormClone.Designer.cs, GitUI/CommandsDialogs/FormClone.cs, GitUI/Translation/English.xlf
- Refactor convoluted FormClone.ToTextUpdate() method
- Fix: text is no longer colored in red when cloning to a path containing "[" or "]" symbols
-  Manual testing
- GIT 2.23
- Windows 10
----
=> Refactor FormClone.ToTextUpdate()

GitCommands/CommitMessageManager.cs, GitCommands/Git/AheadBehindDataProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.cs, GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.cs, GitUI/CommandsDialogs/ToolStripPushButton.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/NBugReports/BugReportForm.cs, GitUI/Script/ScriptOptionsParser.cs, GitUI/UserControls/PathFormatter.cs, UnitTests/CommonTestUtils/CommonTestUtils.csproj, UnitTests/CommonTestUtils/NoAssertContext.cs, UnitTests/GitCommandsTests/CommitMessageManagerTests.cs, UnitTests/GitCommandsTests/RevisionReaderTests.cs
Also add `NoAssertContext` class to prevent tests deadlocking or failing on `Debug.Fail` statements in production code.
The implementation is copied from https://github.com/dotnet/winforms/pull/2191
=> fix incorect use of TestAccessor struct

GitExtensions/Program.cs
Fixes #7381
- Ignore empty paths.
The app would fail if a user passed an invalid repo path such as:
`"C:\portable\GitExtensions\GitExtensions.exe" openrepo ""`.
- reproduced the issue locally, fixed, manual testing
----
=> fix: Fail attempting an empty path

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/CommitInfo/RefsFormatter.cs, GitUI/GitUI.csproj, GitUI/Strings.cs, GitUI/Translation/English.xlf, ResourceManager/LinkFactory.cs, ResourceManager/Strings.cs, UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs, UnitTests/GitUITests/CommitInfo/RefsFormatterTests.cs, UnitTests/GitUITests/GitUITests.csproj
Fixes #5966 (part 2 of 2).
- Build 7ff0c27138154120d4e886b8169119250af7fd5b
----
=> Limit removable for "Contained in branches/tags"

Build/Run-Tests.ps1, UnitTests/GitUITests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs
Improves #7382
- do not run tests in parallel: `--workers=1`
in order to avoid race conditions with singletons like the `AppSettings` and the clipboard
(applies only to the tests of the same test assembly)
- set a default timeout of 90 seconds for every single test, and to 10 minutes for the only long running test (the maximum runtime seen was almost 40 seconds / 5 minutes) 
N/A
- trigger AppVeyor builds
- Build e6dad27982e96ccfc37a81b6ba99f80fb062d9b9
----
=> Increase stability of test execution

GitCommands/Settings/FileSettingsCache.cs, UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs
Fixes #7376
Fixes #7395
- A settings file could not be created and the app would crash, if a user's settings directory is missing.
Ensure the directory is created, before writing the file in it.
- manual
- unit test
----
=> fix: Crash on Missing Settings Directory

GitCommands/CommitMessageManager.cs, UnitTests/GitCommandsTests/CommitMessageManagerTests.cs
Fixes #7316
Check if the repo dir where the commit message is stored exists before trying to save
Manual tests
A basic test mocking the directory storing, I find it not worth it to mock Path.GetDirectoryName().
----
=> CommitMessage: Only save if directory exists

GitUI/CommandsDialogs/FormResolveConflicts.cs
If a user selected a different row from the top, upon rescan/refresh of the dialog there would be 2 rows selected - the top and the one that the user wanted.
This would lead to a situation where an incorrect file would be shown, or worse, no file would be shown due to multiple selection.
Fix the selection by resetting the initial selection after databind and selecting the user's choice.
Also if the user selected the last row, and a conflict was resolved, retain the selection and select the new last row upon refresh.
- manual
----
=> fix: FormResolveConflicts incorrect row selection

GitUI/CommandsDialogs/FormReflog.cs
`_lastHitRowIndex` contained a bad value after the switch
and could be higher than the number of rows.
This commit:
* reset the value when reference selected is changed
* add a control to prevent it to occur again if it contains a bad value
Fixes #7410
- Manual
- Build 3b399511bbbc2cb6c1e65e13850a456c7a1ffdb8
=> FormReflog : fix crash when switching from reference

GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs, UnitTests/GitUITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
Fixes #7357
Partial revert of a regression introduced in #7084.
- `ShowDropDown` call would cause an dummy dropdown item shown on a screen while app was loading.
No ghost dropdown item
- manual
- GIT 
- Windows 
----
=> fix: SetRevisionFunc produce empty dropdown

GitCommands/Settings/FileSettingsCache.cs, UnitTests/GitCommandsTests/Settings/FileSettingsCacheTests.cs
Fixes #7345 
Fixes #6830 
Fixes #6794 
Fixes #6635 
If settings cannot be saved, show popup instead of NBug for users
Also catch all errors on the backup file, read-only gives UnauthorizedException
NBug
Manual
Set read-only on GitExtensions.settings
----
=> catch cannot write to settings

Setup/MakePortableArchive.cmd, Setup/Product.wxs
Fixes installer
- `System.Reactive.dll` is missing from an installer. We should include it to prevent crashing on startup.
=> Add System.Reactive to installer

GitUI/CommandsDialogs/FormResolveConflicts.cs
Fixes regression in #7408 
Not to be included in release notes
If no files are conflicted after resolve (at least by selecting localfiles), the selected index is set to -1 which causes an exception 
```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.Collections.ArrayList.get_Item(Int32 index)
   at System.Windows.Forms.DataGridViewRowCollection.SharedRow(Int32 rowIndex)
   at System.Windows.Forms.DataGridViewRowCollection.get_Item(Int32 index)
   at GitUI.CommandsDialogs.FormResolveConflicts.Initialize() in F:\dev\gc\gitextensions_3\GitUI\CommandsDialogs\FormResolveConflicts.cs:line 183
   at GitUI.CommandsDialogs.FormResolveConflicts.ContextChooseLocal_Click(Object sender, …
```
=> Regression: #7408 exception if no files are conflicted

Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
Fixes #7390
- Prevent http calls to be made (and fail) when the settings are invalid
(if project url is missing)
- Manual
- Build 6fb065325b568c8f9dc1a12fc9500094fc75fe56
=> AzureDevOps CI: prevent call if settings invalid

Setup/UI/TelemetryDlg.wxs
Fixes #7379 
- Ignore all errors that might be thrown from script `set-telemetry.ps1` during installation. This will avoid rollback of the installation in case the script cannot be executed for whatever reason.
- The user will get a popup on the first start asking whether they want to opt in or out of telemetry. This was already implemented for portable builds and can be used without modifications.
- Manual tests:
- Made the installer fail due to a modification in calling the script `set-telemetry.ps1`. I forced the PowerShell version to 7, which did obviously fail, since PS version 7 doesn't even exist.
->This led to the expected rollback of the installation.
- Added the change proposed in this PR and rebuilt installer.
->The call to `set-telemetry.ps1` still fails, but the installer now …
=> Ignore all potential errors from PowerShell during installation

Directory.Build.targets, GitExtUtils/GitUI/ThreadHelper.cs, UnitTests/CommonTestUtils/AsyncTestHelper.cs, UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs, UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs, UnitTests/GitUITests/CommandsDialogs/FormCommitTests.cs, UnitTests/GitUITests/ThreadHelperTests.cs
Applies a 60-second timeout to `JoinTillEmptyAsync`. When a debugger is attached, the timeout is extended to an hour.
=> Apply timeouts to JoinTillEmptyAsync

.editorconfig
This change is intended only to explicitly specify the behavior of C# coding features inside Visual Studio (i.e. the values should match what we were already using).
=> Define .editorconfig for C#

GitUI/CommandsDialogs/RevisionFileTreeControl.cs, contributors.txt
Fixes #7444
- Use file extension as filter and as save type
- I saved a file without the extra dot and verified that the file type was correct.
- GIT version 2.24.0.windows.2
- Windows Version 10.0.18363 Build 18363
----
=> Removes extra dot from Save as revfiletree dialog

GitUI/Translation/English.Plugins.xlf, GitUI/Translation/English.xlf
Adapt GE version in English translation files to 4.0.0 as it is expected after the release of 3.3.0
----
=> Adapt GE version in translation

README.md
- Update README.md to tell how to install GitExtensions with https://appget.net/
=> Install with AppGet (https://appget.net/)

GitUI/CommitInfo/CommitInfo.Designer.cs
Fixes https://github.com/gitextensions/gitextensions/issues/5741#issuecomment-564006028
- open CommitInfo context menu not only in textboxes but for the whole control
- manual
- Build 6739bd90eb258dc3732a1e91b879c9feb052a397
----
=> Open CommitInfo context menu not only in textboxes

GitUI/CommandsDialogs/FormSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/RevisionLinksSettingsPage.Designer.cs
Fixes #7514 
Fixes #7387
- switch to small font in case of clipped controls
(should fit for screens with a height of 768 pixels)
- auto-size last row of Confirmations page
- remove horizontal padding for ToolStrip of Revision Links page
There' still a glitch: The listbox is truncated at the bottom although `Dock = Fill`.
no change on higher resolution
low resolution (mocked up with huge application font):
- manual
- Build 88f51039e4f2c1b281210f8152f8521b133c6d2a
----
=> Reduce clipping in FormSettings

GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.Designer.cs, GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs, GitUI/Translation/English.xlf
Fixes #6691 
- replace `FolderBrowserButton` in order to load the repo on confirmation of folder dialog
- align button
- add mnemonics
- manual
- Build 4fe2f05123e44bed56816a6295eb09c679c46329
----
=> Open repo directly on confirmation of folder dialog

Plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsIntegration.csproj, Plugins/BuildServerIntegration/AzureDevOpsIntegration/CacheAzureDevOps.cs
Fixes (indeed reduce the chances it happens) https://github.com/gitextensions/gitextensions/pull/7452#issuecomment-559084273
- Put build definitions in cache:
Prevent doing every time calls to retrieve build definitions
by putting them in cache.
Build definitions don't change often
and it's acceptable to restart GitExtensions when it's the case
Prevent 2 to 4 api calls at each revision grid refresh
keeping only the 2 calls to get the build results (finished and running).
- Manual
- Build b9f1245890c935f0bb6e964907c952b54a732e0a (Dirty)
=> Azure devops ci: reduce calls to api when revision grid is refreshed 

Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.cs
by removing the use of the event
and relying on control placement configuration
to keep the same behavior.
Fixes #7522
- Manual
- Build 63aaf21d9ea76f72cf80640421d869f6fb444463 (Dirty)
- .NET Framework 4.8.4067.0
=> Prevent crash where _btnPreview is null when event triggered

Plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
- Solve case where a running build stay displayed as running forever even if it is finished since a long time (condition on how to filter on finished build was not good)
by filtering on the FinishTime instead of the StartTime
& solve time management as AzureDevOps use UTC time format
- AzureDevOps: Ignore first api call for finished builds
because as it is implemented now, the 2 first calls (to retrieve today finished builds and all finished builds) are doing the same api call. So we could skip the first call to only keep the one retrieving all the finished builds and so prevent a useless api call (and be more server friendly)
- Manual
- Build 63aaf21d9ea76f72cf80640421d869f6fb444463 (Dirty)
- .NET Framework …
=> CI: Improve Azure Devops builds

GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/SettingsDialog/MergeToolsHelper.cs
Fixes #7544
for 3.3, #7548 for master, since #7044 the implementation is completely different.
Correct the default arguments for kdiff3 merge tool
Also add compatibility mode to allow <3.3.1 where the options are not set. As the implementation is changed, this compatibility mode will automatically be removed
Manual testing conflict resolution
----
=> kdiff3: add configuration for merge arguments

GitCommands/DiffMergeTools/Kdiff3.cs
Fixes #7544
Correct the default arguments for kdiff3 merge tool
http://kdiff3.sourceforge.net/doc/documentation.html
kdiff3 merge commands were not set in settings.
When pressing mergetool, the Git defaults were used 
When pressing "open kdiff3", the arguments were hardcoded in FormResolveConflicts (that happened to be the same as for Git)
Manual
----
=> kdiff3: Incorrect merge cmd

GitCommands/Settings/AppSettings.cs, GitExtUtils/GitUI/Theming/AppColor.cs, GitExtUtils/GitUI/Theming/Theme.cs, GitExtUtils/GitUI/Theming/ThemeFix.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/SettingsPageBase.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Themes/win10default.colors, GitUI/Theming/FormThemeEditor.cs, GitUI/Theming/FormThemeEditorController.cs, GitUI/Theming/StaticTheme.cs, GitUI/Theming/ThemeManager.cs, GitUI/Theming/ThemeModule.cs, GitUI/Theming/ThemePersistence.cs, GitUI/Theming/Win32ThemeHooks.cs, GitUI/Translation/English.xlf, ResourceManager/GitExtensionsControl.cs, UnitTests/GitUITests/GitUITests.csproj, UnitTests/GitUITests/Theming/AppColorDefaultsTests.cs, UnitTests/GitUITests/Theming/ThemeManagerTests.cs, UnitTests/ResourceManagerTests/ResourceManagerTests.csproj
- Use regular font in restart warning, used to be increased.
https://github.com/gitextensions/gitextensions/pull/7213#issuecomment-567018830
[screenshot before](https://user-images.githubusercontent.com/4403806/71087826-35b34f00-21f1-11ea-907b-baa405151b49.png)
[screenshot after](https://user-images.githubusercontent.com/12046452/71298738-96ca5680-239a-11ea-9d9d-499b684558f2.png)
- Fix previoulsy unnoticed review comments from https://github.com/gitextensions/gitextensions/pull/7213
- Do not apply color scheme changes until restart
[documented here](https://github.com/gitextensions/gitextensions/wiki/Dark-Theme-status#restart-required-to-change-theme)
- Show warning of restart needed only when theme has changed or another theme selected
Manually, Windows 10
Added some Unit tests
---- …
=> Color scheme followup

Bin/gitex.cmd
Fixes #7542
If gitex.cmd has no arguments, open browse with the current directory.
gitextensions.exe obeys the arguments since #7147 and defaults by opening the dashboard 
Manual
----
=> gitex: If no argument start browse in current workdir

Setup/EnableUpgrades.wxi, Setup/Product.wxs, Setup/UI/WixUI.wxs
The installer would always default to PuTTY as the SSH client. Whilst in an interactive mode a user is able to choose the SSH client, a silent installer (e.g. the auto-update) will reset the setting to PuTTY despite users using OpenSSH previously.
This has caused issues like #7543 and numerous questions on SO.
The installer is updated to do the following:
* Read the currently configured value from the registry.
* If the app is being installed for the first time, there are only two choices - if the value is absent or unset - use `OpenSSH`, else presume PuTTY.
* If the app is being upgraded, SSH config and telemetry dialog screens are skipped, the existing configurations are retained
Fixes #6286
- Configure in the app: OpenSSH
- Run the installer and observe "OpenSSH" option selected
- …
=> fix: installer defaults to PuTTY

GitExtensions.sln, GitUI/Translation/English.Plugins.xlf, Plugins/Gerrit/FormGerritBase.cs, Plugins/Gerrit/FormGerritPublish.cs, Plugins/Gerrit/Gerrit.csproj, Plugins/Gerrit/GerritPlugin.cs, Plugins/Gerrit/Properties/AssemblyInfo.cs, Plugins/Gerrit/Server/CommandBuilder.cs, Plugins/Gerrit/Server/CommandBuilderWithDraftSupport.cs, Plugins/Gerrit/Server/CommandBuilderWithPrivateSupport.cs, Plugins/Gerrit/Server/GerritCapabilities.cs, UnitTests/Plugins/GerritTests/GerritTests.csproj, UnitTests/Plugins/GerritTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/GerritTests/Server/CommandBuilderWithDraftSupportTests.cs, UnitTests/Plugins/GerritTests/Server/CommandBuilderWithPrivateSupportTests.cs, UnitTests/Plugins/GerritTests/Server/GerritCapabilityTests.cs, contributors.txt
Do not parse version if request to retrieve it was unsuccessful
Fixes #7521
This is just a quick fix, see notes below.
Currently GitExt makes the following incorrect assessments about the Gerrit server and further changes are required to have a proper Gerrit integration (separate topic):
- server is available under https if protocol not specified
- port is the default protocol configuration
In our case ".gerrit" configuration looks like 
`[gerrit]
host=repo.example.lan
port=1234
defaultremote=origin
project=reponame`
while the gerrit is available at "http://repo.example.lan:8080"
- Manually tested
- GIT 2.23.0
- Windows 10
- Gerrit 2.15.3-1-g047eac59e7-dirty
=> Gerrit: fix server version parsing

GitUI/UserControls/FileStatusList.cs
Fixes #7469
If more than three parents are selected in the revision grid, only show the diff to the first.
This will avoid that the GUI freezes if Ctrl-A is selected or many are selected with shift-click.
It still allows multi selection in reasonable cases.
Manual
----
=> RevisionDiff: Limit parents

GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs, GitUI/Translation/English.xlf
Closes #7565
Closes #7563
Handle errors while downloading updates separate from errors during launches of those updates.
This way we can report an error with network configuration etc without crashing the app.
- manual
----
=> fix: Unable to update due to network configurations

GitUI/SpellChecker/EditNetSpell.cs
Fixes #7583 
- Add design check to ToggleAutoCompletion.
- Built Project.
- Opened FormCreateTag Designer
- Did not get NRE in designer
----
=> Prevent NRE in designers that use EditNetSpell

GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
This is a work-in-progress to eliminate the use of a background processing thread in `RevisionDataGridView`.
=> Remove background thread from RevisionDataGridView

GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs, contributors.txt
Fixes #7580 
Disabled the minimize and maximize boxes on update form in the designer.
Ran GitExt and checked you can no longer maximize or minimize the update form.
- Windows 10 - 1909
----
=> Disable maximising/minimising of update form

Build/Run-Tests.ps1
in order to avoid conflicts with singletons e.g.
- AppSettings
- clipboard
- ConfigureJoinableTaskFactoryAttribute
----
=> Run the test assemblies one after the other

GitUI/CommandsDialogs/FormResolveConflicts.cs
Part of #7550 
If not 2-way merge is removed as a result of #7550, this is a minimal fix.
araxis was removed as a preconfigured tool in #7044 (see hints there to readd).
beyondcompare3 was renamed to bc3 and issues like #1844 indicates that manipulation is not helping
Manual
----
=> Remove obsolete 2-way merge tool names

GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Fixes #7473
- Avoid NRE in CommitAutoCompleteProvider
----
=> Avoid NRE in CommitAutoCompleteProvider

GitCommands/ArgumentBuilderExtensions.cs, GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/GitModuleTests.cs
Fixes #7607
- Convert and quote file names for `GitModule.BatchUnstageFiles`
- manual
- adapted NUnit tests
- Build 38d5f9135c7cb0099e42c58cbe32f6c5b96a78e8
----
=> Convert and quote file names for BatchUnstageFiles

GitUI/CommandsDialogs/FormCommit.cs
- Remove duplicate `CancelAutoComplete` in FormCommit
It is done by `EditNetSpell.Dispose`.
- Store only on first close of FormCommit
- use correct event `FormClosed`, not `FormClosing
- check `Visible` because this method can still be called multiple times
----
=> Improve closing of FormCommit

GitUI/CommandsDialogs/FormCreateTag.cs
Fixes #7581 
- Show border on textbox when user can edit message
As seen in the issue, the textbox does not show a border
- Showed  Create Tag dialog
- Selected different tag types
----
=> Make message textbox bounds clear

Setup/Product.wxs
Fixes #7571
add dark theme -related files to installer
in powershell
```
> cd Setup
> Set-ExecutionPolicy Unrestricted -Scope Process
> .\Build.cmd
> .\BuildInstallers.cmd
```
run \Setup\bin\Release\GitExtensions.msi
check that `EasyHook.dll`, `EasyHook32.dll` , `EasyHook64.dll`, `win10default.colors`, `dark.colors` are deployed to installation directory
start installed GitExtensions, popup "theme file not found" does not appear anymore
choose dark theme, restart, dark theme is applied.
- GIT 
- Windows 
----
=> Include theming related files into installer

GitCommands/AppTitleGenerator.cs, GitExtensions/Program.cs
Add the branch the PR is built from to the window title.
The commit sha is visible in About, but especially if the branch is rebased there are several extra steps to find the branch (and the intended functionality included.
An alternative is to add the branch name in About for 'debug builds.
Manual
----
=> Debug: add build branch to title

GitUI/CommandsDialogs/FormClone.cs
Fixes #7528
- Check if path contains invalid char before doing a Path.Combine
Git Clone Form throws an exception if invalid path was written (or path in clipboard)
Show red message as expected.
- Open Git Clone
- Insert an invalid char |<> for example in 
- An red message should be shown without exception.
- GIT 
- Windows 
----
=> Check if path is valid before Path.Combine

GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/CommandsDialogs/FormBrowse.cs, UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs, UnitTests/GitCommandsTests/Submodules/SubmoduleStatusProviderTests.cs
Restore test Submodule_status_changes_for_top_module
- add ISubmoduleStatusProvider.UpdateSubmodulesStatus argument forceUpdate
- remove unused locals from UpdateSubmoduleStatusAndWaitForResult
- AppVeyor
- Windows 10
----
=> Restore test Submodule_status_changes_for_top_module

IntegrationTests/UITests/CommandsDialogs/FormCommitTests.cs, UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs
- Set `tempForm.Owner`
- Make `Should_update_committer_info_on_form_activated` run stable by adding wait
- Make `Should_display_detached_head_info_in_statusbar` run stable by adding wait
- Use `WaitForPendingOperations` in `[Form]CommitInfoTests`
- AppVeyor
- Windows 10
----
=> Improve [Form]CommitInfoTests

GitCommands/Git/GitModule.cs, UnitTests/GitCommandsTests/Config/ConfigFileTest.cs
Fixes #7650
Use -- to escape files starting with "-".
Quick review of other QuoteNE() usage. In addition to the issue, QuteNE was used without escaping paths in a couple of situations.
Incorrect use of QuoteNW in a testcase too.
Other commands could be affected too, this is quite hard to investigate.
Manual
Remove an image that starts with "-" and view the diff
----
=> ls-tree: Use -- to escape files starting with "-"

IntegrationTests/UITests/Properties/AssemblyInfo.cs, UnitTests/CommonTestUtils/Properties/AssemblyInfo.cs, UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs, UnitTests/GitCommandsTests/Properties/AssemblyInfo.cs, UnitTests/GitExtUtils/GitExtUtilsTests.csproj, UnitTests/GitExtUtils/Properties/AssemblyInfo.cs, UnitTests/GitUITests/Properties/AssemblyInfo.cs, UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegrationTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegrationTests/AzureDevOpsIntegrationTests.csproj, UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegrationTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/DeleteUnusedBranchesTests/DeleteUnusedBranchesTests.csproj, UnitTests/Plugins/DeleteUnusedBranchesTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/GerritTests/GerritTests.csproj, UnitTests/Plugins/GerritTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/GitUIPluginInterfacesTests/GitUIPluginInterfacesTests.csproj, UnitTests/Plugins/GitUIPluginInterfacesTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/ReleaseNotesGeneratorTests/Properties/AssemblyInfo.cs, UnitTests/Plugins/ReleaseNotesGeneratorTests/ReleaseNotesGeneratorTests.csproj, UnitTests/ResourceManagerTests/Properties/AssemblyInfo.cs, UnitTests/ResourceManagerTests/ResourceManagerTests.csproj
- Add `TempAppSettingsAttribute` for all tests
in order to set `AppSettings.CheckForUpdates = false`
There is no need to tinker the `AppSettings.SettingsFilePath` because the user's GE settings file is not used but one which is specific for the test runner, e.g. 
`SettingsFilePath: C:\Users\appveyor\AppData\Roaming\NUnit Software\NUnit Engine\GitExtensions.settings`
- AppVeyor
- Windows 10
----
=> Add TempAppSettingsAttribute for all tests

GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Discussion in #4154
Add _(A)_ and _(B)_ to some revision descriptions in RevisionDiff
manual
----
=> Add A/B to RevisionDiff revision descriptions

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormEditor.cs, GitUI/CommandsDialogs/FormLog.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/FormViewPatch.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/Editor/FileViewer.Designer.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, GitUI/UserControls/CommitDiff.cs, UnitTests/GitUITests/Editor/FileViewerTextTests.cs
This started as an attempt to #7338, but some refactoring is needed first. (Maybe #7338 will not be finalized.)
Almost all changes seen in FileViewer for RevisionDiff
See screenshots for changes
Most changes to handle the submodule patch/"diff" as text, not as a diff in the FileViewer.
FileViewer internal ViewPatch call stack was cleaned up. Previously resetting internal properties like format highlighting was done several times.
No syntax highlighting in FormViewPatch
Irrelevant context menu for submodules
Cherry-pick/revert lines must not exist for files that do not exist (popup occurs) (fixing TODO in code)
Find grouped with patches, not go to line (see above)
Tests adapted
---- …
=> FileViewer context menu fixes

GitUI/CommandsDialogs/FormBrowse.cs, contributors.txt
Fixes #7595 
Alternative to #7600
Existing code sends 10K backspaces to clear the current console line, which is slow. For `cmd` and `powershell`, we can send `Esc` to clear the line; for `bash` we can use a ConEmu macro sequence to send Ctrl+A, Ctrl+K.
- Manual
- Windows 10 v 1903 (OS Build 18362.535)
----
=> Improve speed of directory change in console tab

GitUI/CommandsDialogs/BrowseDialog/FormOpenDirectory.cs, IntegrationTests/UITests/CommandsDialogs/FileStatusListTests.cs, IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs, IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.ReorderNodes.cs, IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs, IntegrationTests/UITests/CommandsDialogs/FormBrowseTests.cs, IntegrationTests/UITests/CommandsDialogs/FormCommitTests.cs, IntegrationTests/UITests/CommandsDialogs/FormEditorTests.cs, IntegrationTests/UITests/CommandsDialogs/FormInitTests.cs, IntegrationTests/UITests/CommandsDialogs/FormPullTests.cs, IntegrationTests/UITests/NBugReports/BugReportFormTests.cs, IntegrationTests/UITests/Script/ScriptRunnerTests.cs, IntegrationTests/UITests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs, UnitTests/GitCommandsTests/ExternalLinks/ConfiguredLinkDefinitionsProviderTests.cs, UnitTests/GitCommandsTests/ExternalLinks/ExternalLinksManagerIntegrationTests.cs, UnitTests/GitUITests/Avatars/AvatarTestBase.cs, UnitTests/GitUITests/BranchTreePanel/GitRefMenuItemsTest.cs, UnitTests/GitUITests/CommandsDialogs/FormOpenDirectoryTests.cs, UnitTests/GitUITests/CommandsDialogs/RevisionFileTreeControllerTests.cs, UnitTests/GitUITests/CommitInfo/CommitInfoTests.cs, UnitTests/GitUITests/Editor/FileViewerInternal.CurrentViewPositionCacheTests.cs, UnitTests/GitUITests/Editor/FileViewerTests.cs, UnitTests/GitUITests/Editor/FileViewerTextTests.cs, UnitTests/GitUITests/GitExtensionsFormTests.cs, UnitTests/GitUITests/UserControls/BlameControlTests.cs
- More complete `TearDown`; remove `null` assignments
- No unused `Form` instance in `FormOpenDirectoryTests`
- Dispose `Form` instances in `GitExtensionsFormTests`
- Refactor `FormBrowseTests.LeftPanel.*`
- AppVeyor
- Windows 10
----
=> Cleanup tests

UnitTests/GitUITests/UserControls/ICSharpTextEditorTest.cs
Fixes #7653
- Rename vb highlight rules file
- Add test to keep names and SyntaxNodes in sync
- ~~Switch ICSharp project to debug~~
- Renamed an xshd file and ran test
- Added a copy of one of the mode elements and altered the file attribute.
----
=> Keep Syntax Highlight Rules Synced With Resources

UnitTests/CommonTestUtils/AsyncTestHelper.cs, UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs, UnitTests/GitUITests/ThreadHelperTests.cs, appveyor.yml
Solves parts of #7382
- The singleton JTF instance must not be null.
- Throw InvalidOperationException if `ThreadHelper.JoinableTaskFactory/JoinableTaskContext == null`.
- Assert in `BeforeTest` that there is no dangling singleton instance,
which should have been destroyed by `AfterTest`.
- Aggregate follow-up exceptions.
- Reset _threadException to null in `AfterTest`.
- Report detected hangs.
- Launch debugger if `GE_TEST_LAUNCH_DEBUGGER_ON_HANG` is `1`.
- Delay execution by `GE_TEST_SLEEP_SECONDS_ON_HANG` on `WaitForPendingOperations` timeout.
- AppVeyor
- Windows 10
----
=> Improve ConfigureJoinableTaskFactoryAttribute

GitCommands/Git/GitRevision.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormRebase.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, Plugins/GitUIPluginInterfaces/ObjectId.cs, UnitTests/ResourceManagerTests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Discussed here: https://github.com/gitextensions/gitextensions/pull/7626#issuecomment-574760763
The short version of commit hash was previously 10 characters but in 9 of 19 uses the size was modified (to 8 chars, except in revision diff where it was 4, changing to the default in #7666). 
The short format that is unique in a repo can be retrieved from Git. Many repos are OK with 7 bytes (this was the initial for the Linux repo), bigger repos need longer sha, Linux at least 12 bytes to _only_ use the short sha.
This short format is only used for display, in many places the link can be copied.
The short form should be used to present the sha in the GUI to correlate info in for instance CommitInfo to the revision grid. The short form should not be required to be unique.
However, the length …
=> ObjectId ShortString: set default to 8 chars

UnitTests/GitCommandsTests/GitModuleTests.cs
Disable the flaky test `GetSuperprojectCurrentCheckout` until #7681 is solved
----
=> Disable flaky test GetSuperprojectCurrentCheckout

UnitTests/CommonTestUtils/ConfigureJoinableTaskFactoryAttribute.cs
Fixes #7684
Do not deregister from `Application.ThreadException` _between_ tests in order to catch all exceptions while running tests
- AppVeyor
- Windows 10
----
=> Do not deregister from Application.ThreadException between tests

GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Discussion in #4154
Replacing #7626, already reviewed and approved, just changing A->a, B->b
This gives yet another chance to suggest changes
Add _(a)_ and _(b)_ to some revision descriptions in RevisionDiff
manual
----
=> Add A/B to RevisionDiff revision descriptions #7626

GitCommands/AppTitleGenerator.cs, UnitTests/GitCommandsTests/AppTitleGeneratorTests.cs
- Fix AppTitleGeneratorTests.Generate_should_include_debug_suffix (addendum to #7569)
- Debug: put build branch in title into square brackets (as in the screenshot of #7569)
- NUnit tests
- Build 98dba0c69be55f80f8795a7501b69ce3066cecb4
----
=> Fix AppTitleGeneratorTests.Generate_should_include_debug_suffix

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/FormViewPatch.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, ResourceManager/LocalizationHelpers.cs
Fixes #7660 
as well as some TODO in FileViewer seen in #7624 (while adding a few other)
Do not access the local file system for git items (blobs and commit=submodule) as it is irrelevant
Handle GitItemStatus objects in FileViewer to avoid guessing the file type
Cleanup a few call 
Manual
----
=> FileViewer: Do not access the file system for git blobs

GitUI/CommandsDialogs/BrowseDialog/FormUpdates.Designer.cs
Fixes #7713 
Removed the TopMost attribute from the FormUpdates dialog
Manual tests
- Git Extensions 3.3.1.7897
- Build 5a97671645532bcedc443bac7b727f40db47cb5c
- Git 2.22.0.windows.1 (recommended: 2.23.0 or later)
----
=> removed TopMost attribute from the FormUpdates dialog

GitCommands/Git/GitModule.cs, GitCommands/GitRevisionInfoProvider.cs, GitUI/CommandsDialogs/FileStatusListContextMenuController.cs, GitUI/CommandsDialogs/FormBrowseController.cs, GitUI/CommandsDialogs/FormCheckoutBranch.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs, GitUI/UserControls/CommitDiff.cs, GitUI/UserControls/FileStatusList.cs, Plugins/GitUIPluginInterfaces/ObjectId.cs
Originated as a part #4154, but broken out
Comparisions should not use GitRevision.Guid but GitRevision.ObjectId, as Guid => ObjectId.ToString()
Probably not making any noticeable difference, but sets the example and is a step to remove Guid
I would like to change e.g.  GitRevision.WorkTreeGuid -> ObjectId.WorkTreeId.ToString() when comparing to raw strings, but this will be slightly less efficient.
(The Guid version is used to compare strings, but this makes it more difficult to find the Artificial commits. There are tests that the two definitions are identical.)
Tests updated
----
=> Refactor: Compare with ObjectId rather than Guid

GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs
Resolves #7232 etc
Related to #7550, alternative to removing 2-way merge in #7552
Skip the GE specific 2-way merge and staging if cmd or path is not set, as manipulation is not possible. 
Manual
----
=> merge conflict: Do not require .cmd or .path

GitUI/CommandsDialogs/FormBrowse.cs
Fixes #6866 
- Add a feature to open a GitExtensions repository in a new window when ctrl+clicking it, both in "Recent Repositories" menu and "Favorite Repositories" menu.
- User tests of all the different scenarios.
- GIT 2.24.1.windows.2
- Windows 10 Home 64bit
----
=> Add feature to open repo in a new window

GitCommands/GitRevisionInfoProvider.cs, GitUI/CommandsDialogs/FormBrowseController.cs, UnitTests/GitCommands.Tests/GitRevisionInfoProviderTests.cs
Follow up from #7719
Changed irrelevant test for Guid
Guid => ObjectId.toString() and can only be null or valid
Flipped check for ObjectId in GitRevisionInfoProvider.cs 
Updated tests
----
=> ObjectId test corrections

GitUI/UserControls/InteractiveGitActionControl.cs
Fixes #7457 in dark theme
Adapt the colors for the warning header in the dark theme
#7457 was submitted before dark theme was merged so @NikolayXHD could not fix this too.
Light theme unchanged what I see and expect
Manual - insert code to get headers
----
=> Adapt colors for warning header with dark theme

GitExtensions/GitExtensions.csproj, Plugins/BuildServerIntegration/AppVeyorIntegration/app.config
Resolves #7735
Fixes #
The recent change saw each plugin placed in own folder under the Plugins folder. This caused a number of plugins that had additional references (e.g. to Newtonsoft.Json) fail at runtime because these the app did not know where to probe for these assemblies.
Previously all plugins were placed in the same folder, Plugins, and the app was configured to probe in this folder (refer to app.config `configuration/runtime/ns:assemblyBinding/ns:probing`).
Now upon the start-up the app will ensure that all plugins under Plugin folder are added to the probing path. And if any of the plugins are missing, the probing path is updated and the app is restarted.
- TBD
----
=> fix: Plugins private binaries not resovled

GitUI/Interops/DTT_CALLBACK_PROC.cs, GitUI/Interops/RECT.cs, GitUI/Theming/Renderers/ButtonRenderer.cs, GitUI/Theming/Renderers/ComboBoxRenderer.cs, GitUI/Theming/Renderers/EditRenderer.cs, GitUI/Theming/Renderers/HeaderRenderer.cs, GitUI/Theming/Renderers/ListViewRenderer.cs, GitUI/Theming/Renderers/ScrollBarRenderer.cs, GitUI/Theming/Renderers/SpinRenderer.cs, GitUI/Theming/Renderers/ThemeRenderer.cs, GitUI/Theming/Renderers/TooltipRenderer.cs, GitUI/Theming/Renderers/TreeViewRenderer.cs, GitUI/Theming/Win32ThemeDelegates.cs, GitUI/Theming/Win32ThemeHooks.cs
fixes #7763
tested manually in win10
=> use RECT class (not struct) in theming interop

IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs, appveyor.yml
- Dump the output of inconclusive tests to the AppVeyor console.
- Ignore failure of the flaky tests until #7743 is solved:
- `RepoObjectTree_should_load_active_remotes`
- `RepoObjectTree_should_order_active_remotes_alphabetically`
----
=> Disable flaky ROT remotes tests

GitUI/UserControls/InteractiveGitActionControl.cs
=> fix InteractiveGitActionControl buttons text in dark theme

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs
Replaces and closes #5717 
#5717 has other changes too, the discussion (over a year ago) for that PR was that the button should adapt to the context. 
(My personal opinion is to probably not changing this, but the arguments were convincing.)
top most project
submodule
----
=> Adapt submodule button to context

UnitTests/CommonTestUtils/ReferenceRepository.cs
`ReferenceRepository.Reset` is supposed to efficiently reset the repository to a fresh state. This pull request fixes two cases where state was not reset.
=> Fix incomplete reset in ReferenceRepository

GitUI/CommandsDialogs/FormCommit.cs, GitUI/SplitterManager.cs, IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs, UnitTests/GitUI.Tests/SplitterManagerTest.cs
Fixes #7588
This fixes GitExtensions issue #7588
- Inside the application code not much more as to regard the property `SplitterWidth` of the `SplitContainer` control
- Some additional comments
- Some additional tests and updates to some SplitterManager tests
See section "Current behaviour" in issue #7588
See section "Expected behaviour" in issue #7588
- Manual testing both of the main (browse) window and the commit dialog
- Adding of UI tests to ensure that the geometry of the commit dialog is restored properly after reopening the dialog
- GIT version 2.24.1.windows.2
- Windows 10 1909
----
=> Improve restoring of the commit dialog geometry (Fixes #7588)

IntegrationTests/UI.IntegrationTests/UITest.cs, contributors.txt
Related to #7382
- `Close` and `Dispose` `Form` in `UITest.RunForm`
- try to close all Forms on exception in async task of `UITest.RunForm`
(happens for many `FormCommitTests`)
- AppVeyor
- Windows 10
----
=> Improve exception-safety of UITests.RunForm

IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Remotes.cs, IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.ReorderNodes.cs, IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.LeftPanel.Submodules.cs, IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs, IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs, IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs, IntegrationTests/UI.IntegrationTests/UITest.cs
Related to #7382
Based on #7765
- `await JoinPendingOperationsAsync` right after closing the tested `Form`
in the async task of `UITest.RunForm`, i.e. inside the message loop
because with #7753 tests hang in `Application.Run(form)` called by `showForm`
- revert `await` in `TearDownAsync` of ROT tests
- standardize opening of FormBrowse and FormCommit in tests
- AppVeyor
- Windows 10
----
=> JoinPendingOperationsAsync right after closing the tested Form

GitCommands/Config/SettingKeyString.cs, GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs, GitCommands/Git/GitModule.cs, GitCommands/Git/GitVersion.cs, GitUI/CommandsDialogs/FormResolveConflicts.cs, UnitTests/GitCommands.Tests/DiffMergeTools/DiffMergeToolConfigurationManagerTests.cs
Fixes #5919
Use ```mergetool --gui```
GE already supports ```difftool --gui```.
This allows use of a separate mergetool from command line.
Added tests
- GIT 2.25 - faked tests with older version (also testcases)
----
=> Support merge.guitool

GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
Show status for top module in the side panel.
If there are changes in any submodules (commit or dirty) or changes in the topmodule itself, this status should be seen in the top most icon.
(The top module cannot be ahead/behind only dirty but will be so for any changes)
Minor refactorings and removal of unused code too, to be squashed.
There are some limitations to the implementation, due to performance issues (git-status can require some resources).
git-status reuses the call for the commit button and artificial commits in the grid, so it is executed for the current module only. If there are changes, the side panel status is currently refreshed only for the current submodule (and below).
At the initial opening, the status is calculated for all modules though, except files in the current …
=> SidePanel Submodules: Status for top module

GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs, GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.cs
Part of #4154 
A few related changes, preferably reviewed commit by commit
- Avoid a call to git-rev-parse to get common ancestor (BASE) when comparing
- Show the diff for common ancestor (BASE) in the status list
- ToolTip for multiple parents setting
English.xlf is not updated, UpdateLocalEnglishTranslations.ps1 require changes
(removed colon after with:)
Manual
----
=> improve file status list presentation

GitUI/UserControls/FileStatusList.cs
Fixes a regression in #7720
Stash Form was not loaded due to the unused revision was set to null
Test already exists - failed in master
----
=> Stash: Form fail to load

GitExtensions/Project.Publish.targets
#7785 changed the name of portable builds to `GitExtensions-portable-4.0.0.8648-65a1b55e7.zip`
This creates an issue with https://github.com/gitextensions/gitextensions.extensibility, because [this script](https://github.com/gitextensions/gitextensions.extensibility/blob/master/src/GitExtensions.Extensibility/tools/Download-GitExtensions.ps1) expects the following naming convention: `*Portable*.zip` (with upper-case P).
- Change the artifact name to `GitExtensions-Portable-4.0.0.8648-65a1b55e7.zip`
- Manual. Checked on AppVeyor that my commit produces the desired artifact name: https://ci.appveyor.com/project/mast-eu/gitextensions/builds/31056636/artifacts
----
=> Change portable artifact name

GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
Fixes #7811
Prevent crash when loading settings page if file for selected theme in AppSettings is missing.
Instead default theme is selected.
- selected dark theme
- closed GitExtensions
- renamed `dark.css` to `dark2.css`
- started GitExtensions
- opened settings page
result:
- settings page opens
- default theme is selected
----
=> do not crash on missing theme file

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs
Part of #7338 
RevisionDiff had some functionality to retain the selected file that did not really work.
This change try to retain the file selected, also when changing the selected commit. This makes it easier to follow a file from commit to commit. A more important use case is for handling artificial commits. If refreshing after staging lines, the same file should be kept (not select the first file).
A second change is to retain the index when staging/unstaging files (or staging all lines) for Artificial commits, rather than the first is selected again.
In some situations, no file was selected in RevisionDiff. This should make sure that a file is always selected. Not reproduced though.
Manual
---- …
=> RevisionDiff: Try retain the file selection when switching commits

GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormLog.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/GitUIExtensions.cs, GitUI/UserControls/CommitDiff.cs
Part of #7338
(likely the last before the feature itself)
Present new files in WorkTree as plain files instead of a diff.
This aligns RevDiff with FormCommit again.
This was changed in  2.49 or so by myself when implementing diff to artificial commits, I did not find a good solution at time.
However, the actual reason I change this is to simplify #7338 to stage changes in new files. (FilePreamble is not set for diffs, which should be fixable too.)
Alternatives:
* Change FormCommit (and more?) as well as FilePreamble
* Show all New (and removed) as files
This also makes a minor refactoring for ViewChangesAsync, tobe squashed
Manual
----
=> revdiff: Show new file in worktree as file, not diff

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormSettings.cs, GitUI/Plugin/PluginRegistry.cs, GitUI/Script/ScriptRunner.cs
as we already did it in `PluginRegistry.Initialize()` to populate the collection
Should fix #6924, #7813, ...
- manual
- Build 398d29d61eb3260555fd0c187dccef1b881b3c13 (Dirty)
- Git 2.25.0.windows.1
=> Surround access to plugin collection with a `lock()`

Plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs, Plugins/BuildServerIntegration/AzureDevOpsIntegration/Properties/AssemblyInfo.cs, UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegration.Tests/AzureDevOpsAdapterTests.cs
One commit for each (that could be reviewed separatly)
1. Make lighter and quicker api calls
* by providing filters values in the query parameters (less build are returned instead of filtering them after)
* by specifying the `properties` requested (less data returned for each build)
2.  Fix "in progress" display sometimes not refreshed for the case 
where the first display was done when the build was not yet started
i.e. `StartDate` was filled with a bad default value
that prevent later refresh once the build is really started
3. Better choose the running build to display when there is more than one build to display for a specific commit.
* Before: Multiple build was returned and due to the condition in `BuildServerWatcher.cs`/`OnBuildInfoUpdate()`, the last started build is displayed.
* …
=> AzureDevOps CI: Fix and improvements

Plugins/BuildServerIntegration/Directory.Build.props, Plugins/Directory.Build.props, Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs, Plugins/Statistics/Directory.Build.props
Fixes #7842
- Try to load only plugin dlls following pattern `GitExtensions.*.dll`
- Rename all the plugin projects to follow this new convention
- Manual
- Build 63496b38ed36086e42bb74966ea3e8554377d376
- Git 2.25.0.windows.1
=> Fix slow plugins loading

GitCommands/Patches/PatchManager.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs
Fixes #5329 
Follow up to #7824
Always show new files as files, not as a patch
Note: A sideeffect for this is that it will not be possible to cherry-pick/revert lines for new files (except FormCommit, as is now).
This is planned for revDiff artificial commits in #7825 , not for other commits or forms right now.
Manual
----
=> Show new files as file, not diff 

GitCommands/Git/GitRevisionSummaryBuilder.cs, UnitTests/GitCommands.Tests/GitRevisionSummaryBuilderTests.cs
Fixes a not visible NRE (but boring when debugging)
- test if body is null
=> Handle gracefully a NRE on body message

IntegrationTests/UI.IntegrationTests/UITest.cs, IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.cs
Fixes #7745
Fixes #7382 (hopefully the last jigsaw piece)
`CommitInfoTests` failed because the ctor `CommitInfo` triggers async tasks using `FileAndForget`.
The tests must wait until these finish before they can modify the mock-up for the next git command.
A plain `await AsyncTestHelper.JoinPendingOperationsAsync` hangs.
Running the tests with a dummy main form resolves these hangs.
- AppVeyor
- Windows 10
----
=> Fix commit info tests

Plugins/Bitbucket/ApprovePullRequest.cs, Plugins/Bitbucket/Bitbucket.csproj, Plugins/Bitbucket/BitbucketRequestBase.cs, Plugins/Bitbucket/MergePullRequest.cs
See https://github.com/gitextensions/gitextensions/pull/7878#issuecomment-601216437
Fixes #7855
Update plugin for newer RestSharp. Add .json body with supported methods.
Test to a private BitBucket Server (not working with BitBucket Cloud).
----
=> BitBucket plugin update of RestSharp

GitUI/Editor/FileViewer.cs, GitUI/Translation/English.xlf
See https://github.com/gitextensions/gitextensions/pull/7831#issuecomment-598459433
Display a text rather just an empty pane if the image has been removed or cannot be displayed for other reasons.
Manual
----
=> Display text if an image cannot be displayed

GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #5869
- use `DataGridView.FirstDisplayedScrollingRowIndex` to bring into view an already selected branch if clicked again in the RepoObjectsTree
- manual
- Build 9b925d2e09d8260a227030a790df3cb44809c208
----
=> Bring into view already selected branch on ROT click

GitUI/CommandsDialogs/FormCompareToBranch.Designer.cs, GitUI/UserControls/BranchSelector.cs
Fixes #
https://github.com/gitextensions/gitextensions/issues/7822
- Manual
- Windows 10 1909
=> Make DropDownWidth in BranchSelector adjust to longest item

GitCommands/Settings/AppSettings.cs, GitCommands/Submodules/SubmoduleStatusProvider.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs, GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs, GitUI/Translation/English.xlf
Issue: https://github.com/gitextensions/gitextensions/issues/7882
-  Show branch name in recent repos drop down (optional)
- Manual
=> Add setting to show branch name in recent repos drop down

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Fixes #7841 
Alternative or complement to #7887
Use 'internal' difftool command instead of FileViewer to view hot key diffs
RevisionFileTree tried to use FileViewer difftool, but the action was
never enabled (so the menu option was always disabled). Instead invoke Module.DiffTool,
compare displayed item to worktree, something I have occasionally missed.
(Note that if there is no diff, difftool will not open, not changed, so to test this select an older commit).
#7887 fixes the problem in FileViewer for FormDiff. 
That PR need to set difftool in ViewGitItemAsync() (by default, use explicit or use ViewChangesAsync() to set a difftool in FileViewer)
With this change #7887 is maybe not needed and FileViewer.DiffTool could possibly be removed.
There is still some use of difftool with F3, to …
=> FormCommit: F3 to diff large files

GitExtensions/Project.Publish.targets, NetSpell.SpellChecker/SpellChecker.csproj, Plugins/Bitbucket/Bitbucket.csproj, Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorIntegration.csproj, Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsIntegration.csproj, Plugins/BuildServerIntegration/Directory.Build.props, Plugins/BuildServerIntegration/Directory.Build.targets, Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsIntegration.csproj, Plugins/BuildServerIntegration/TfsIntegration/TfsIntegration.csproj, Plugins/BuildServerIntegration/TfsInterop.Vs2015/TfsInterop.Vs2015.csproj, Plugins/Directory.Build.props, Plugins/Directory.Build.targets, Plugins/GitUIPluginInterfaces/GitUIPluginInterfaces.csproj, Plugins/GitUIPluginInterfaces/ManagedExtensibility.cs, Plugins/Gource/Gource.csproj, Plugins/JiraCommitHintPlugin/JiraCommitHintPlugin.csproj, Plugins/Statistics/Directory.Build.props, Plugins/Statistics/Directory.Build.targets, scripts/tools/Imports.targets, scripts/tools/NUnit/NUnit.targets, scripts/tools/Publish.targets
Addendum to #7649, solves parts of #7702.
* Partially alter #7850 to not rename any plugins for CI builds
* Enumerate all plugin satellite files
* Publish plugins in the portable artifact
----
=> Collect and publish plugins (portable)

GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs, GitUI/MessageBoxes.cs, GitUI/ShellHelper.cs, GitUI/Translation/English.xlf
Addresses part of #7523 
- Add `pwsh` in the settings dialog as an additional option for the shell to run in the Console tab
Dialog offers choice of bash, cmd, and powershell
Dialog offers pwsh as an additional choice
-  Manual testing
- GIT 2.25.0.windows.1
- Windows Win10 1903 (build 18362.592)
----
=> Add pwsh as a choice of shell in Console tab

GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/Translation/English.xlf
Fixes #7917
Add the title label, probably lost at Designer changes when removing the Theme editor
We could add all title labels in the user code instead, but that should be changed for all pages if so
Manual
----
=> Settings: Color title label missing

GitUI/CommandsDialogs/FormSettings.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitRootIntroductionPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitRootIntroductionPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/GitRootIntroductionPage.resx, GitUI/Translation/English.xlf, contributors.txt
Fixes #5946 
- Add root node to Git tree view node on Settings page.
- I simply copied the root page from the Plugins section, renamed it and changed the label.
Clicking in the Git node automatically selects the first child node
- Using the up/down keys on the tree view to make sure navigation still works
- Can still save Git settings
- GIT 2.19.1
- Windows 10 Pro
----
=> Add root description to Git node in settings tree view

GitUI/UserControls/FileStatusList.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, GitUI/WebBrowserEmulationMode.cs
Fixes 3 exceptions not easily to reproduce but where stacktrace helps us understand what is happening...
- RevisionGridControl: fix Index was out of range exception. Fix #7374
- Don't fail when user have no rights to update the registry. Fix #7918
- Add protection againt NRE when SelectedItem is null. Probably fix #7857
- None because not reproducible. Read and write code ;)
- Build 5b00c7b4c0bddae9d93b4d01b449d57794963292
- Git 2.25.0.windows.1
=> Fix 3 not reproduced exceptions

GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/UserControls/FileStatusList.cs
Fixes #7907
Do not try to retain the selected item, if selection was done in
other than the first group or if the item is only appearing in other than the first group
See the issue for a description and discussion. I personally prefer the current behavior, but @mstv has requested this change. (This also conflicts with several other open PRs.)
The retain/follow for RevDiff was introduced in #7798 
Showing the behavior after only
Code review, manual
----
=> RevDiff: follow selection only in first list group

GitCommands/Git/GitCommandHelpers.cs, GitExtUtils/GitCommandConfiguration.cs, UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs, UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #7906
User configuration of git config diff.ignoreSubmodules need to be overridden,
to not rely on the user having proper configuration. This was done with a
git-status option --ignoreSubmodule=none
However, git-diff was not overridden, so the RevisionDiff tab could be inconsistent with the artificial status and FormCommit
Submodule config can be overridden per submodule, not just globally.
The PR #7906 argued that those configurations should be followed
Allow those overrides by using the config parameter
'-c diff.ignoreSubmodules=none'  instead of the command line option so
user specific overrides can have effect.
Similar for git-diff, if diff.ignoreSubmodules was configured, git-diff would
use the config
Showing behavior after, editing .gitmodules
The existing meaningless tests …
=> git-status:  use config to set ignoreSubmodules

GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
Fixes #7917
Follow up to #7919, more permanent solution
To avoid titles are lost when making changes in the designer, move title/text setting to the init code.
The Designer and code files for settings pages have been checked, only a few occurrences.
----
=> Move settings page titles from designer files

GitExtensions/Project.Publish.targets
Fixes broken builds like https://ci.appveyor.com/project/gitextensions/gitextensions/builds/31840877
MSBuild had a bug that caused builds not break if errors occurred in targets executed via `AfterTargets` (https://github.com/microsoft/msbuild/issues/3345). A workaround is to use `BeforeTargets` execution chain.
- Locally and on the CI: https://ci.appveyor.com/project/RussKie/gitextensions/builds/31864931
----
=> Break the build if there are any errors in publish tasks

GitUI/CommandsDialogs/FormBrowse.cs
addendum to #7883
- align recent branch names (to the right -- not influencable using the chosen approach)
- manual
- Build 40b550d01fcb1ad95db5a993cea7fcf4eb2fab72
----
=> Align recent branch names

GitCommands/Git/GitVersion.cs
Update recommended Git version to 2.25.1 (released Feb 19, 2.25.0 released Jan 13)
Latest is Git 2.26, released on Mar 23, maybe to new to set as default (I have been running the RC a little longer without issues, but nothing I know is important)
Manual
----
=> Git: Set recommended version to 2.25.1

GitCommands/Settings/AppSettings.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/WindowsJumpListManager.cs
Fixes #7683
Regression after d072142baaec034a10bedd9fa15854eed6269222 from #7750 
The button handling has been incorrect for years
Still not fully working
Windows TaskBar JumpList was not initiated correctly
ApplicationId init too late
Windows TaskBar JumpList could be initiated without the window handle was available
JumpList buttons were never enabled when starting in Dashboard
Manual
----
=> Windows TaskBar JumpList was not initiated

GitUI/CommandsDialogs/BrowseDialog/FormRecentReposSettings.Designer.cs
Make OK button same width as Cancel button
- Swap order of OK and Cancel button in Recent Repo Settings Form to make it consistent (OK to the left of Cancel)
- Manual
=> UX: Swap OK and Cancel button Recent Repo Settings UI

GitCommands/PathUtil.cs
Resolves #7947
- Correctly locate tools under `C:\Program Files` using `env.var["ProgramW6432"]`.
- manual
- GIT 
- Windows 
----
=> fix: Locate diff tools in C:\Program Files\ folder

GitCommands/Git/GitModule.cs
Followup to #7922 
#7922 added conflict icons to files in conflict, which should be set on files in index/worktree where merge conflicts have not been resolved.
Example where branch_x is merged to branch_y
However, the status was incorrectly set for files in the merge 'combined commit' too, changing the icon
(previously it was 'file modified' for all conflicts, including submodules).
See 81f72a7fdc43bc15c6d8737e65cc513a302769e8
Manual
----
=> Merge combined conflict set to IsConflict

GitUI/CommandsDialogs/FormCreateBranch.cs
- prepopulate the branch name in `FormCreateBranch` with the first branch or tag at the current revision
It can be replaced easily because the whole string is selected.
My use case:
I often create temporary copies of branches before rebasing, squashing or fetching force-pushed branches. I don't want to search the ref log.
- manual
- Build d6096c423875b5d63cf4e12469a7ae29915b7e8d
----
=> Prepopulate branch name in FormCreateBranch

contributors.txt, scripts/tools/Publish.targets
Fix "An equivalent project (a project with the same global properties and tools version is already present in the project collection)" error during Publish build.
=> Fix error during Publish build.

GitCommands/FileHelper.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormDiff.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommandsDialogs/FormLog.cs, GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/Editor/FileViewer.cs, GitUI/GitUIExtensions.cs, GitUI/UserControls/CommitDiff.cs
Part of #7338 
Related to #7825 
Fixes #7866 
There are many codepaths that "presents changes" to files (binary, images) and submodules. The presentation differs if the file is new, tracked etc.
The logic for that is split between the separate forms and GitUIExtensions.cs, ViewChangesAsync(). Some of that has been cleaned up in previous PRs.
(FormCommit.cs also needs to have some logic in FileViewer.cs ViewCurrentChanges(), that requires #7825 first.)
The presentation therefore differs from form to form.
This change unifies the handling to be consistent, all using ViewChangesAsync()
This PR shares (conflicts) a change in #7914, rev-parse is required to get guid, see the explanation there.
This only changes how FormStash presents changes, the only actual change of this PR is that images …
=> Use ViewChangesAsync consistently for changes

GitUI/CommandsDialogs/FormStash.cs, GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs, GitUI/UserControls/CommitDiff.cs, GitUI/UserControls/FileStatusList.cs, IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs
Separated from #7926 
See https://github.com/gitextensions/gitextensions/pull/7926#pullrequestreview-385057653
Stash currently presents worktree and index files as one list.
The diff for index files is incorrect, always show the worktree changes.
FileStatusList will have better support for this after #7899, but the FileStatusList can be tweaked to present this as two groups
WIP as it builds on #7926, the first two commits are from the #7926 review too and all will be squashed.
Both diffs are identical
Manual
----
=> formstash improvements

GitCommands/Git/GitCommandHelpers.cs, GitCommands/Git/GitItemStatus.cs, GitCommands/Git/GitModule.cs, GitUI/CommandsDialogs/FormArchive.cs, GitUI/GitUIExtensions.cs, UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
This was done as a part of #7902 but separated
Separate the evaluation of getting "staged status" to a separate function and add tests.
The Git documentation mostly uses stage/unstage as the action to move between the indexes, this text uses staged/unstaged to some extent too.
git-status reports if a file is changed in the worktree or index. This is used in FormCommit.
RevisionDiff allows comparing any commit to worktree/index and uses git-diff.
RevDiff allows the user to stage/unstage files if conditions allow.
The problem here is that git-diff reports the differences for the file but not if a file is changed in any of worktree, index or a intermediate commit. Therefore the staged status is calculated separately from commit. So if a file is changed from index to worktree, it must be …
=> Separate staged status from GetDiff

GitUI/CommandsDialogs/FormCommit.Designer.cs, GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs, GitUI/Strings.cs, GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.cs
See the commits for detailed explanations, this is a summary of changes.
The context menus are not aligned much, neither contents nor order.
This PR tries to align the options in a x more consistent way, grouping similar functionality and aligning RevisionDiff, RevisionFile and FormCommit.
The order can be discussed, but I doubt I will update the screen shots.
The convention in menus is that the first item should be the default 'double-clicked' action and that it should be default.
This PR makes sure that items are bot bold if they are not the default and sets submodule "Open with Git Extensions" as bold.
To change the default file action to open the history in RevDiff/RevFile, some deeper changes are required. If so, the History/Blame should probably be handled by FileStatusList as …
=> Align context menu order for FileStatusList

IntegrationTests/Directory.Build.props, UnitTests/Directory.Build.props, scripts/tools/RepoLayout.props
Resolves #7969
Tests are now written under `.\gitextensions\artifacts\tests\$(Condition)\[UnitTests|IntegrationTests]`
----
=> Fix incorrect location of tests

GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs, GitUI/Interops/User32/IsIconic.cs
Part of #6521
Avoid running git-status when GE Browse is minimized
Check Git Command Log
----
=> GitStatusMonitor: Avoid background updates if GUI is not visible

GitUI/CommandsDialogs/UserScriptContextMenuExtensions.cs, GitUI/Script/IScriptHostControl.cs, GitUI/Script/ScriptOptionsParser.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.Commands.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.RevisionGridInMemFilter.cs, GitUI/UserControls/RevisionGrid/RevisionGridControl.cs, UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
- Decouple script parsing from the revision grid. This will allow easier and simpler integration of other controls with the script manager (e.g. the left panel or the file tree)
- Extract user script binding to a context menu to an extension method. This will allow re-use of the functionality in other parts of the app (e.g. the left panel or the file tree). This is small step in the same direction as #6348 proposed by @ivangrek. Sadly we stalled on this work.
- Review the code and add multiple validations and add tests.
This work is foundational to allow re-use of user scripts in other parts of the app (e.g. the left panel or the file tree). Specifically I want to allow users to run custom scripts for files in the working tree, e.g. to achieve what was proposed in #6135, or open a file …
=> Uplift script handling

GitCommands/Settings/AppSettings.cs, GitUI/Avatars/AvatarService.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/Editor/BlameAuthorMargin.cs, GitUI/Editor/FileViewer.cs, GitUI/Editor/FileViewerInternal.cs, GitUI/Editor/GitBlameEntry.cs, GitUI/Translation/English.xlf, GitUI/UserControls/BlameControl.cs, UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
Please, give your point of view and probable improvements...
- Display avatars in the gutter with a thin vertical marker for recency
Note: the same information could be displayed in the gutter, that's just that it is configured differently
With avatars (notice the thin color line next to avatars that highlight recency of changes):
last update on heatmap colors:
* for light theme:
* for dark theme:
- Manual (for more than 6 months now...)
- Build ad8be3dafc0537dafa2a96e1cb5daf0f09b302ef
- Git 2.25.0.windows.1
=> Improve blame gutter display

GitCommands/Git/GitItemStatus.cs, GitCommands/Git/GitItemStatusFileExtensionComparer.cs, GitCommands/Git/GitItemStatusNameComparer.cs, GitCommands/Git/GitItemStatusNameEqualityComparer.cs, GitUI/Translation/English.xlf, GitUI/UserControls/FileStatusList.cs
Part of #4154 
Separated from #7899 , the first part of the compare
This is partly to simplify the review, partly to simplify my merges, partly to drive the ideas forward: What more do we want to see?
#7720 added the possibility to see differences to BASE-> selected, if the two commits first/selected shared common BASE.
This PR separate the groups for the files that are unique BASE->selected(B) and common for
BASE->selected(B) and BASE->first(A) to give a better diff of branches
#7899 contains the changes to also show the unique files BASE->first(A) and to simplify other structures in GE
See #7899 for BASE->first
Manual
----
=> RevDiff: Show common/unique files for BASE->selected(B)

GitUI/UserControls/FileStatusList.cs
Follow up from #7922 
When comparing new files from WorkTree -> commit, the files were presented with the Unknown icon instead of deleted.
Manual
----
=> Deleted files presented as Unkown

GitUI/CommandsDialogs/FormBrowse.Designer.cs, GitUI/CommandsDialogs/FormBrowse.cs, GitUI/CommandsDialogs/FormFileHistory.Designer.cs, GitUI/CommandsDialogs/FormFileHistory.cs, GitUI/CommitInfo/CommitInfo.cs, GitUI/CommitInfo/CommitInfoHeader.cs, ResourceManager/CommandEventArgs.cs, ResourceManager/LinkFactory.cs, UnitTests/ResourceManager.Tests/LinkFactoryFixture.cs
Fixes #7582
- Handle `showall` links in `CommitInfo` directly
- Pop up exception on link execution in `CommitInfo`, too
- Factor out `ILinkFactory.ExecuteLink`
- Factor out `ILinkFactory.ParseInternalScheme`
- Refactor `ILinkFactory.ParseLink to yield Uri`
- Build pop up link exception in CommitInfo, too
----
=> Fix up show all branches / tags in history

GitUI/CommandsDialogs/FormReflog.cs
Fixes #7937 
In the Reflog form, when the popup are shown, if no row or cell are selected, use the current row.
An exception are shown.
Use the commit in the current row.
I tried to copy a SHA with a line deselected. It crashes without my patch. It works with my patch.
- Git Extensions 3.3.1.7897
- Git 2.25.1.windows.1
----
=> Fix #7937 Reflog form : index was out of range.

GitUI/CommandsDialogs/FormCommit.cs, GitUI/CommandsDialogs/RevisionDiffControl.cs, GitUI/CommandsDialogs/RevisionDiffController.cs, UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Late changes to #7694 removed the possibility to delete untracked directories. This is handy to delete removed submodules.
Previously, this was possible to with DEL but no menu alternative.
This restores DEL and adds to menu.
Secondly, delete untracked directories was enabled for FormCommit but not implemented correctly. 
Tests updated
----
=> RevDiff, Commit: Delete untracked directories

GitExtensions/Project.Publish.targets, appveyor.yml
Fixes #7979
- Tweak the commit hash of portable builds both
- in the name of zip file
- in `ThisAssembly.Git.Sha` (by soft resetting git to the head commit of the PR)
- run AppVeyor
----
=> Tweak commit hash of portable build

GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.Designer.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.ScriptInfoProxy.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs, GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.resx, GitUI/Design/ExecutableFileNameEditor.cs, GitUI/Design/PropertyOrderAttribute.cs, GitUI/Design/PropertySorter.cs, GitUI/GitUI.csproj, GitUI/Script/ScriptEvent.cs, GitUI/Script/ScriptInfo.cs, GitUI/Script/ScriptManager.cs, GitUI/Themes/dark.css, GitUI/Translation/English.xlf
- Redesign script configuration settings
- One of a key change is that script modifications are no longer "destructive" _until_ the settings are accepted via [OK] or [Apply] buttons. 
The race condition where a user has multiple instances of the app open and modifies scripts in several instances at once still remains, and it completely outside the scope of this PR. 
The last instance of the app to accept changes to scripts will overwrite all other changes may have been made in other instances. 
- manual
- I may look at adding tests, but may do that at a later stage.
----
=> Redesign script config
