gitextensions/gitextensions

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
Fixes #7875
- Update artificial commit in FormBrowse on `WM_ACTIVATEAPP`
in dependency on the regarding setting used in FormCommit
- Rename `AppSettings.RefreshCommitDialogOnFormFocus`to `RefreshArtificialCommitOnApplicationActivated`
- manual
- Build 8a24eb00c4b3f4b457d1cff5845637989bb23c1b
----
> Update artificial commit diff

- GitUI/Interops/DTBGOPTS.cs
- GitUI/Theming/Renderers/ListViewRenderer.cs
- GitUI/Theming/Renderers/ThemeRenderer.cs
- GitUI/Theming/Win32ThemeDelegates.cs
- GitUI/Theming/Win32ThemeHooks.cs
- GitUI/UserControls/NativeListView.cs
The solution used to detect when check boxes are painted is dirty.
The check boxes are painted by windows once, when ListView control is created.
Theming hook method, the one that desides whether rendering shoud be overriden, receives `IntPtr hTheme` - a handle of theme data. It's always a pain to find out which type of control is being painted, because AFAIK there is no API to infer it from `hTheme`.
One workaround that worked in all previous cases, was to exploit the fact that `OpenThemeData(control.Handle, partName)` returns the same `hTheme`  until `CloseThemeData` is called with same `control.Handle` and `partName` values.
`hTheme` depends only on 2 parameters - the window class of the control, and `partName`.
So I would normally `OpenThemeData(listView.Handle, "ListView")`, remember …
> Apply dark theme for check boxes in NativeListView

- GitUI/Theming/Win32ThemeHooks.cs
A `Debug.WriteLine()` call slipped into my previous PR, only noticed it now.
> Remove debugging code

- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
Resolves #4469
Resolves #5928
Resolves #6070
Resolves #7413
Resolves #8023
We had a number of NRE reports. Most likely scenario is that GitHub is API rate limiting unauthenticated requests  that lead to failures in Git.hub library.
Nothing we can do apart from ignoring these types of errors.
> Ignore GitHub API rate limit induced errors when search for app updates

- GitCommands/CommitMessageManager.cs
- GitCommands/CommitMessageType.cs
- GitCommands/Git/GitCommandHelpers.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
- UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
Fixes #3954
This work is inspired by https://github.com/gitextensions/gitextensions/pull/7796 that was abandoned by its author.
- Centralise commiit message handling by moving the code from `FormCommit` that formatted and wrote a commit message into a temp file before a git command was run to `CommitMessageManager`. 
Leverage the same implementation for `FormMergeBranch` to write out merge-commit messages.
- Tighten git-merge log condition
Merge commit message with quotes was failing the merge `test "message text" test`
The merge succeeds.
- manual tests
- unit tests
> Fix 3954 quotes in merge commit message

- GitExtensions/Project.Publish.targets
- appveyor.experimental.yml
- appveyor.yml
- scripts/build.ps1
Fixes #7979
- Cleanup the git status of `English.xlf` and `English.Plugins.xlf` before calling the `TranslationApp` if a `git reset --soft` was done in order to tweak the commit hash
which is done only if the env var `"APPVEYOR_PULL_REQUEST_HEAD_COMMIT` is set
- Use the same commit hash for the `.msi`
- Keep the `.binlog` files on failure, too
- CI build
- with and without correct `English.xlf`
- with PR branch based on current and on earlier master
- AppVeyor
- Windows 10
----
> Cleanup git status before calling TranslationApp

- GitCommands/Git/GitCommandHelpers.cs
Seen with #8049, but has occurred since the before/after feature was added 2013 or so
GE tries to get how many commits that a changed submodule is before/after the intended commit, using git-rev-list
This check is done also if the submodule only is dirty, i.e. commit is unchanged, there cannot be any commit changes.
For instance listing the submodule status in the sidepanel could take twice the time needed.
This is normally not a big problem as only changed submodules are queried.
Excerpts from logs after refresh, starting with git-status (the response triggers the status update of submodules with changes).
All GE submodules are dirty (in this case a new files added to the worktree).
```
2020-04-29T21:44:11.8426454+02:00	145	21304	UI	0	git	--no-optional-locks -c diff.ignoreSubmodules=none …
```
> Unneeded rev-list for submodule status

- GitCommands/Git/GitModule.cs
Fixes #8057
- Catch and ignore `IOException` in `GetSelectedBranchFast` the same way as if the file did not exist
- Build d58beb57a9b070c9b00d33a6a51518423bc25f1b
----
> Ignore inaccessible file in GetSelectedBranchFast

- GitExtUtils/GitCommandConfiguration.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #7570 
Replaces #8046 
Override diff.mnemonicprefix=true, reverse diffs cannot be parsed
Adopted the test
----
> git-diff override  diff.mnemonicprefix=true

- GitUI/UserControls/NativeTreeViewExplorerNavigationDecorator.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Improve revision selection Left Panel vs. RevisionGrid:
- Minor fixup in `NativeTreeViewExplorerNavigationDecorator`:
Use the given lambda instead of `DateTime.Now`.
- Reset `RevisionGridControl.InitialObjectId` after use. (Might be related to #6057.)
- Fix up the check for the last visible row in `RevisionGridControl.SetSelectedIndex`:
- factor out a new local function `EnsureRowVisible`
- call `_gridView.Select()` first (was omitted by too early `return` from my previous PR)
- Toggle the RevisionGrid selection if `Ctrl` is pressed especially if triggered from left panel.
result of `Ctrl+Click`
- manual
- Build e3ee53618420676d92a77fd4ed9b6f3b16b20c07
---- …
> Select multiple revisions using Left Panel

- GitUI/CommandsDialogs/FormCommit.Designer.cs
Follow up to #7961 
For submodule in FormCommit, open folder is before copy path, this aligns with other menus
----
> Align folder/copy for submodule

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- Plugins/GitUIPluginInterfaces/IBrowseRepo.cs
Fixes regression https://github.com/gitextensions/gitextensions/pull/8056#issuecomment-623719356
- Make shortcuts with `Ctrl` select single revisions again
by toggling the selection from Left Panel only
- Avoid pointless `new GitRevision` for `RevisionGridControl.SetSelectedRevision(GitRevision)` by calling the `ObjectId` overload directly
- manual
- Build Toggle selection from Left Panel only
----
> Fixup regression introduced by ROT multiselect

- GitCommands/Git/GitModule.cs
Fixes #8074
- Ignore all types of exception which can be thrown by `File.ReadAllText` in `GetSelectedBranchFast`
- manual
- Build c06c3ae32425747f74329068433189e56cdf79cd
----
> Catch all types of exception thrown by ReadAllText

- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
- GitUI/Translation/English.xlf
Align tooltip with changes in #7899
Suggest inclusion in 3.4, even if translation is updated. (CThis is a clarification, not breaking existing translations)
----
> Improve tooltip for diff selection

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- ResourceManager/LocalizationHelpers.cs
- Present submodule changes where commit is unchanged without the duplicated info
- Set status as Dirty if no commit changes
- RevFileTree: Minimal info for submodules if path contained a folder as the file name was used instead of the path
Normal files were OK as the blob was used rather than the filename (except for binary files)
Text examples from FileViewer
```
Submodule subtest/s002 Change
From:	68c11dc3b22c1e1476f03c0a6cc65591a4ccc95e
2 years ago (2018-11-09 21:57:35)
Merge pull request #5729 from gerhardol/bugfix/transifex-notranslate
Remove untranslatable strings
To:		68c11dc3b22c1e1476f03c0a6cc65591a4ccc95e (dirty)
2 years ago (2018-11-09 21:57:35)
Merge pull request #5729 from gerhardol/bugfix/transifex-notranslate
Remove untranslatable strings
Type: Unknown
Status:
?? t.t
``` …
> Submodule status: Present dirty submodules

- GitCommands/CommitData.cs
- GitCommands/CommitDataManager.cs
- GitCommands/Git/GitRevision.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormDiff.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUIExtensions.cs
- GitUI/RevisionDiffInfoProvider.cs
- GitUI/UserControls/BlameControl.cs
- GitUI/UserControls/FileStatusItemExtensions.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FileStatusListTests.cs
- ResourceManager/CommitDataRenders/CommitDataHeaderRenderer.cs
- UnitTests/GitCommands.Tests/CommitDataManagerTest.cs
- UnitTests/GitUI.Tests/Helpers/DiffKindRevisionTests.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataHeaderRendererIntegrationTests.cs
Fixes #8085 
- Refactor: Align FirstParentId name
Guid suffix is quite consistently used for the string representation of the hash, while Id suffix is used for ObjectId, this was therefore switched
Some parentGuids changed too, not changing treeGuid
- Use "--root" for first revision if null
Handle GitRevision == null as the root commit, before the initial commit, i.e. compare to /dev/null
SemanticMerge and KDiff3 shows such a diff, Tortoise does not for some reason
(The alternative would be to not add null to the revisions to diff which will result in a argument popup which is OK to me.)
- RevDiff: FirstRevision is null for the initial commit
Handle that FirstRevision is not set for the initial commit
All situations changed are not causing problems, but it is easier to handle …
> RevDiff: FirstRevision is null for the initial commit

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #8072
Workaround for not reliably restored splitter positions:
Restore the layout of `FormBrowse` a second time after `base.OnLoad(e)`.
- manual
- Build e972d9a0a1c35a31bf0495a1536547ababc872b5
----
> Restore splitter positions

- GitUI/Script/ScriptOptionsParser.cs
Fixes #8128
`ScriptOptionsParser.AskToSpecify` shall return `string.Empty` in case there are no options to select
in order to avoid unhandled `ObjectDisposedException`,
e.g. when determining the current remote while parsing script arguments starting with "c"
- manual similar to the description in the bug report
- Build 51e71c23c32b22963250eb3a1dd7e3053a5d58df
----
> Support 0 options in ScriptOptionsParser.AskToSpecify

- appveyor.yml
Fixes #8034
for the case of modified `English.xml` on both `master` and the PR branch
- use `git commit` instead of `git reset` & `git checkout` in order to undo `git reset --soft`
- keep English.xlf on build fail
- run AppVeyor
- tested with #8026 before it was rebased
- Win10
----
> Fix up repo preparation before verifying loc

- GitUI/CommandsDialogs/FormRemotes.cs
- GitUI/CommandsDialogs/FormRemotesController.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormRemotesControllerTests.cs
If a user adds a new remote which index, when saved, exceeds the number of maximum recent remotes - the remote would be added to the end of the list of remotes, and trimmed off when the list of recent remotes is saved.
Fix the issue by adding the new remote to the top of the list, so it gets saved.
- manual
- unit tests
----
> fix: New remotes not saved, if exceed limit

- GitCommands/Git/GitCommandHelpers.cs
- GitCommands/Git/GitRef.cs
- GitUI/CommandsDialogs/FormReflog.cs
- GitUI/GitUICommands.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.Designer.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.resx
- GitUI/HelperDialogs/FormResetCurrentBranch.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/GitRefListsForRevision.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #2876 (Superseding #8026 )
Implementation initially based on @mdonatas
- In the revision gird, being able to reset any branch (not only the one checked out) to the selected commit, using "git reset --force"
The initial view when opening
The new reset form for "other branches"
- Manual
- Build 0a69f31ca246ebe13a212db80476180c4ac662d8
----
> Add 'Reset another branch to here' feature

- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Backport of fixes in #8119
#8119 was opened to secure the functionality with #8049 but has cleaned up the handling some
That PR is probably too big for 3.4 right now. 
This PR cherry picks some specific limitations and bugs from that PR for 3.4
* If not top project is current and current module has changed commits,
git-status with no dirty will not clear the current ahead/behind
* If not top project is current and git-status is initially not dirty for super projects
but there are changed commits in superior projects, the status is now set as dirty
* If a submodule is no longer dirty, the status was no longer cleared when initiated from git-Status
* Some attempts to not refresh status twice
These are not important, but since detected, I can as well submit a PR before 3.4 is cut
Tests are …
> SubmoduleStatusProvider: Set IsDirty from git-status

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #8153
- Restore the call sequence of before #8124
- But keep a second call of `SetSplitterPositions` after `base.OnLoad`
- manual (with an without start to the Dashboard)
- Build bec3e4e0e35853b95d307432a975ba860d82bb2d
----
> Fix up splitter positions

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #6057
- get the row index from the correct source when it is stable
- clear ToBeSelectedObjectIds again when done
corrects the wrong assumption the revisions were loaded in order
fixes multi-selections not being restored anymore
see issue
- manual
- Build 71ee25272ff39bcc59dedca0a4d8fc956cb68971
----
> Fix up restoring the selection of revisions on reload

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
Fixes #8106 
Put bold stage/unstage menu items in FileStatusList context menus
To avoid adding a translation string, the Text for the buttons are reused
Before has #8137 applied - this PR is not necessarily an alternative to the second commit, both could be merged (even if my preference is that the second commit do not go in)
Manual
----
> FormCommit: Add context menu items Stage/Unstage

- GitUI/CommandsDialogs/FormBrowse.cs
The GE documentation maintains several branches, currently release/3.4, release/3.3, release/2.51 and master. (I just obsoleted the _latest_ branch and retired 3.1 and 3.2 (doc remains but not listed in the list with versions).
Currently, we keep a pointer to the specific version in the link in the GE source code, in release/3.3 pointing to release/3.3. In master it has been pointing to master.
The intention was to maintain that when building releases. While this could be achieved with build scripts (not done right now, there is still a manual step when merging.
This PR changes the link to point to the main link: https://git-extensions-documentation.readthedocs.io/
that will redirect to the link that is configured as the latest.
Documentation how to configure the latest release updated in …
> Link to read-the-docs for release version

- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
Fixes #8150
- return 0 instead of throwing an NRE
- None. Occured one time but difficult to reproduce.
- Build 0ef262dc8eddb1d6b8958d4cf7bf730c8ce28739
> Prevent NRE when getting AppVeyor build duration

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Script/ScriptRunner.cs
* Scripts may not have arguments, pass "" in this case instead.
* Scripts may fail during execution, show an error message instead of crashing the process.
NB: there is a new string, but I'm fine with not translating it, as the use case it likely niche.
> Make scripts execution safer

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
Fixes https://github.com/gitextensions/gitextensions/pull/8139#issuecomment-634106191
- Tooltip for merged branches
no tooltip
- manual
- Build 581938786997c2db795eaea6460b79f90346fa5f
----
> Tooltip for merged branches

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes: `RevisionGridControl._latestSelectedRowIndex` can be `-1`.
Then `LatestSelectedRevision` yields `null`.
Do not use `Cursor.Position` in Mouse event handlers!
Use `MouseEventArgs.Location` instead. It contains the clicked position. `Cursor.Position` can be quite different, e.g. if the main thread is busy updating and the mouse is moved away.
- manual
- Git Extensions 4.0.0
- Build 9a8bb6d6fcfd531aeb1dcf4254d22df71287c86a
----
> Do not use Cursor.Position in Mouse event handlers

- Setup/Product.wxs
Fixes PR builds by AppVeyor I hope.
Remove incomplete translations from `Product.wxs`:
Italian, Latvian and Argentinean Spanish are lacking at least plugin translations
- build this PR 
- AppVeyor
- Windows 10
----
> Revert incomplete translations

- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes part of #8195, which broke the right click / context menu
In case of `DataGridViewCellMouseEvent`, the base class `MouseEventArgs.Location` contains the mouse position relative to the selected cell not to the `Control`.
And it already contains the `RowIndex`.
So use it instead of `HitTest(e.X, e.Y)`.
- manual (more complete this time, sorry)
- Build d60ed2270cde53b15fc84b353e77a78cf98acae3
----
> Use DataGridViewCellMouseEventArgs.RowIndex

- GitCommands/Submodules/SubmoduleInfoResult.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/CommonTestUtils/SubmoduleTestHelpers.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
I believe this is ready, but did not plan to include it in 3.4
Submitting now for discussion of #8049 
SubmoduleStatusProvider will not update the status more often than every 15th second to limit load.
This was added before the status update was fully async and before updates were pruned (latest change in #8116).
The status should not be noticable (at least comparable to git-status, that can take a long time in big repos with many submodules).
The update limitation remains with this PR, but instead of dropping frequent updates, the handling is throttled to update no more often than every 15th second.
The handling has also been simplified.
A change to specific mention is that previously, if not the top module was selected, the complete structure including the current submodule was …
> Submodule status: Throttle instead of drop frequent updates

- GitUI/WindowsJumpListManager.cs
Wrap WindowsJumpListManager calls in try..catch.
Resolves #8234
> Make WindowsJumpListManager calls safer

- GitCommands/Git/GitCommandHelpers.cs
- UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
Fixes #8235
Quote path (and gitref, not strictly needed).
Manual (check Git command log)
----
> ResetAnotherBranch: Quote path arguments

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #8245
Disable context menu items instead of hiding them:
- `Delete branch...` for current branch in RevisionGrid
- `Cherry pick changes` for e.g. multi-selections in tab "Diff"
- manual
- Build 306e547dc42e0389dfcbd5d0f394e1b2c398ec3e
----
> Disable context menu items rather than hiding them

- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
Fixes #8099
and part of #5767
- draw the message of the `RevisionGrid.CurrentCheckout` with bold font
- manual
- Build 83f645ee6e38a2d35869bf6f371c75e57f864ad4
----
> Draw current commit message bold in detached-head mode

- GitUI/Editor/FindAndReplaceForm.cs
- UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs
Fixes #7784
- Turn off "selection only" mode in Find dialog if a new text is assigned to the file viewer (see comments in the issue).
- Prevent Diff view from iterating over the files if "selection only" search is being conducted (see isMultiFileSearch in the PR).
- Unit tests
- Manual testing of Find dialog on Diff, File tree, File history views.
- GIT 2.18
- Windows 10 Pro 
----
> Fix "selection only" text search on Diff view (#7784)

- GitCommands/SshPathLocator.cs
- UnitTests/GitCommands.Tests/SshPathLocatorTest.cs
When `ssh.exe` is not in the path, the attempt to find it in git
directory will fail, resulting in a nasty crash of the whole
GitExtensions process if it is needed (an example is when
downloading a patchset in Gerrit plugin).
----
> Fix ssh not found

- GitExtensions/Program.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/GitUICommands.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- Plugins/GitUIPluginInterfaces/IGitUICommands.cs
- UnitTests/GitUI.Tests/GitUICommands/NormalizeFileNameTests.cs
Fixes #7805
Reviewed best commit by commit. Do not squash.
- Run `FormFileHistory` in a separate GE instance in order:
- to be able to use the history after opening the modal `FormCommit`,
- to refresh `FormCommit` when switching back from `FormFileHistory`,
which could have been used to modify the repo.
- Resolve TODOs regarding non-zero `ExitCode` on error parsing command line arguments.
- Refactor in order to let `FormFileHistory` activate the tab "Blame" itself.
unchanged
- manual
- Build 09d0a839579126488423ce6a53c3236287a00615 (Dirty)
----
> Run FormFileHistory in a separate GE instance

- GitUI/CommandsDialogs/RememberFileContextMenuController.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
Based on #8193, for RevisionFileHistory
Add _Remember file for diff_ for RevisionFileHistory similar to RevDiff in #8193 The context is shared between the tabs 
Tests added for RevisionDiff
----
> RevFile: Diff any two files

- GitUI/CommandsDialogs/FormBrowse.cs
- Restore the `FileStatusList` focus after the `GoToChild`/`GoToParent` hotkeys (`Ctrl+N`, `Ctrl+P`).
`RevisionGridControl.SetSelectedRevision` sets the focus to itself. So just restore it if the `RevisionDiffControl` was focused.
- manual
- Build e889d7513e9bf8eb98c3d6a9b62c29c3dd8ccbc2
----
> Restore FileStatusList focus after GoToChild/Parent

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
- Apply also the Conemu font configuration to the ConEmu popup (because that's strange to apply only just one setting, the console style and not the other)
That's bigger (even if we don't really see it due to how GitHub handle images. Compare text size inside the console with the one of the button or with the icon size)
- Manual
- Build f544aba2e27d05647ec1f7d122cbf3bea744dca7 (Dirty)
> Apply also font size setting to the ConEmu popup

- Plugins/GitFlow/GitFlowForm.cs
Disable Finish button in GitFlow form while branches are loading. Before this fix you can press Finish button while branches ComboBox displays 'Loading...', so you can finish 'Loading...' branch which doen't exists.
> Disable Finish button while loading branches in GitFlow form.

- GitCommands/Git/Executable.cs
- GitCommands/Logging/CommandLog.cs
- GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.Designer.cs
- GitUI/Script/PowerShellHelper.cs
- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
- GitUI/UserControls/EditboxBasedConsoleOutputControl.cs
Inspired by https://github.com/gitextensions/gitextensions/pull/8278#discussion_r449728071
- log exceptions thrown while attempting to start a process in the `CommandLog`
- improve `CommandLog` output formatting:
- was 2 digits for exit code ("128" happens often)
- was "Call stack: not captured"
- catch and log exception handling `ExitCode` in `Executable.OnProcessExit`
- `PowerShellHelper.RunPowerShell`: use `Executable` & `ProcessWrapper` in order to call `LogProcessEnd` correctly
- log exceptions from `ConsoleEmulatorOutputControl.StartProcess` and `EditboxBasedConsoleOutputControl.StartProcess`
- `EditboxBasedConsoleOutputControl.StartProcess`: correctly call `LogProcessEnd`
- fit footer size of `FormGitCommandLog` to usual content, i.e. 9 lines
saved log
``` …
```
> Improve CommandLog

- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Fixes nothing
Replace magic string SHA in unit test with variable
- Unit test passed
- Run the unit test with test runner
----
> Refactor to replace magic hash string with variable

- UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs
Fixes #8300
- Avoid `IEnumerable<>` in test case signature, use arrays instead
- Declare `TestCaseSource` methods `private`
- Omit `Test` attribute where `TestCaseSource` is specified
- Build dcea83bc1081ea9c345f19d76acb4cab542179ab
----
> Avoid IEnumerable<> in test case signature

- GitUI/CommandsDialogs/FormClone.Designer.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormInit.Designer.cs
- GitUI/CommandsDialogs/FormInit.cs
- GitUI/GitExtensionsDialog.Designer.cs
- GitUI/GitExtensionsDialog.cs
- GitUI/GitExtensionsDialog.resx
- GitUI/GitModuleForm.cs
- GitUI/HelperDialogs/FormProcess.cs
- GitUI/HelperDialogs/FormRemoteProcess.cs
- GitUI/HelperDialogs/FormStatus.Designer.cs
- GitUI/HelperDialogs/FormStatus.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Relates to #6183
* Add a new base dialog control `GitExtensionsDialog`that features two main sections - `MainPanel` for the main content, and `ControlPanel` for all buttons. All form should ideally inherit from this dialog to provide a consistent look and feel.
* Update `FormInit` layout
* Update `FormClone` layout
* Update `FormStatus` layout
* Update `FormProgress` layout
* Update `FormRemoteProgress` layout
⚠️ This work concentrates only on the placement of buttons, the original layout of dialogs is preserved (for the most part), and changes to the actual layout of each individual form is outside the scope of this work.
* `FormInit`
* `FormClone`
* `FormClone`
* `FormInit`
* `FormClone`
* `FormClone`
- DPI 144dpi (150% …
> Dialogs layout alignment

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #8312
- Add missing early `return` from `OnRebaseInteractivelyClicked`
- manual
- Build 4e89551f9cd8ee1b84443a1737551027b639a8b9
----
> Add missing early return from OnRebaseInteractivelyClicked

- GitUI/CommandsDialogs/FormVerify.Designer.cs
- GitUI/CommandsDialogs/FormVerify.cs
- GitUI/CommandsDialogs/FormVerify.resx
- Add a file/commit diff preview in the "Recover lost object" form to browse blob more quickly and easily
- Try to guess the file type to enable syntax highlighting
For Commits:
For Files:
- Manual
- Build 178ef2ae3b6126c29662930505e14f17589fba8b
> Recover lost object: Add a file preview

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #8320
With mono / linux reszing a form with layout issue sometimes helps, not in this case though. After maximizing / unmaximizing, the toolbar is extended to a proper width, but still the filter textbox is invisible
manually
----
> fix hidden toolStripRevisionFilterTextBox in Linux

- Plugins/Gource/GourcePlugin.cs
- Plugins/Gource/GourceStart.cs
by generating the avatars in the expected format by Gource:
i.e. `authorname.png`
The previously generated file were not found by Gource...
From [Gource documentation](https://github.com/acaudwell/Gource/blob/master/README):
```
--user-image-dir DIRECTORY
Directory containing .jpg or .png images of users
(eg "Full Name.png") to use as avatars.
```
- Manual
- Build dee83f5839711e3d365bfa5f4346f4d0673f412a
> Fix Gource avatar feature

- GitUI/Avatars/BackupAvatarProvider.cs
and keep them in a cache.
Fixes #8241
- Manual
- Build 28d1a6ad94bbf5fa375a780931d14c4107e54ce7
> Resize also the backup/default avatar image

- GitUI/Infrastructure/Telemetry/DiagnosticsClient.cs
- GitUI/Infrastructure/Telemetry/ThemingTelemetryInitializer.cs
Track theme color and other settings
Manual. What did I actually check:
- Theme properties were written to `telemetry.Context.GlobalProperties`.
- DiagnosticsClient calls OnExit, which calls _client.Flush() without exceptions.
- Windows10
----
> Track theme colors via Telemetry

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #8315
Fixes #8316
Check if a submodule exists on the filesystem before trying to create a summary.
Note that deleted submodules are ignored in the summary.
See the issue
----
> FormCommit: No summary  for deleted submodules

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormMergeSubmodule.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/HelperDialogs/FormProcess.cs
- GitUI/HelperDialogs/FormStatus.Designer.cs
- GitUI/HelperDialogs/FormStatus.cs
- GitUI/TaskbarProgress.cs
Undo plumbing and infra introduced in 1572cbd7da7af53678f05b8cd4dcfcdf9e8e46d3. With that we have one less dependency on WPF stack.
There are several scenarios that involve showing `FormStatus` or its descendants.
1. Show a progress as a modal dialog (this is standard way).
2. Do not show the progress dialog, and only show it if an operation that was running failed (e.g. staging files in `FormCommit`).
The approach to showing results of failed operations appears to be unnecessary complex, that IIUC led to issues while attempting to show a dialog that was already considered opened but invisible.
And the WPF's DispatcherFrameModalController was used to deal with this. 
This also necessitated defining delegates, and required more plumbing to pass those around, validation, etc.
However it is …
> Clean up of status reporting of failed operations

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/MessageBoxes.cs
- GitUI/Translation/English.xlf
Separating hotkey handling in RevDiff file status list from #7825 
No longer based on #8193 (some conflicts)
Add hotkeys to stage/unstage/reset in RevDiff
Checks that the status list is in focus (if the viewer is in focus in #7825, lines will be changed instead).
Manual
----
> RevDiff: Add hotkeys to stage/unstage/reset

- GitCommands/Submodules/SubmoduleStatusProvider.cs
Annoying change in 3.4: Printouts when starting GE from commandline
git-status updates more often than 15s are dropped, to limit background refreshes of the submodule status.
The handling in 3.4 is about the same since 3.1/3.0 but improved in master (updates are throttled/delayed, not just dropped).
In 3.4 a console printout was added when an update is dropped.
Every third second or so, the following is written to the console:
```
MoveNext called too early again - aborting
```
This is very annoying if you start GE from the commandline.
Not the way I use GE (and I use master), but my coworkers are annoyed
Git alias:
```
ex = !sh -c\"\\\"C:/Program Files (x86)/GitExtensions/GitExtensions.exe\\\"browse $(git rev-parse --show-toplevel)\" &
```
A workaround is to write the printout to …
> Avoid console printouts when submodule updates are throttled

- GitUI/CommandsDialogs/MergeConflictHandler.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/MessageBoxes.cs
- GitUI/Translation/English.xlf
- Factor out a common function `Show` to call `MessageBox.Show` in a single place in `MessageBoxes`
in order to prepare for easy replacement / extension, e.g. for
- mock-up in NUnit tests
- switching to the UI thread in order to show errors of external operations when they occur
- Factor out a common function `Confirm`
- Remove unreferenced `_confirmDeleteRemoteBranch` and `ConfirmDeleteRemoteBranch`
- manual
- Build b6a6047
----
> Refactor MessageBoxes

- GitCommands/Git/GitCommandHelpers.cs
- GitUI/CommandsDialogs/FormRebase.Designer.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/CommandsDialogs/FormRebase.resx
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormRebaseTests.cs
- UnitTests/GitCommands.Tests/Git/GitCommandHelpersTest.cs
Fixes #7708 
- Regression testing using the test suites provided
- Added test cases to test suite
- System testing on the rebase dialog
----
> Add "Ignore Date" and "Committer Date Is Author Date" options to rebase dialog

- UnitTests/GitUI.Tests/Editor/FindAndReplaceFormTests.cs
Fixes #8300
- Avoid round brackets in testcase argument strings
`(` and `)` are used by `ICSharpCode.TextEditor.TextLocation.ToString`
- Build 122cc41cba52ad80f8621db5e1bb49eea4465aa7
----
> Avoid round brackets in testcase argument strings

- GitCommands/DiffMergeTools/TortoiseDiff.cs
- UnitTests/GitCommands.Tests/DiffMergeTools/RegisteredDiffMergeToolsTests.cs
Fixes #8332 
Add alias _tortoisediff_ for _tortoisemerge_ 
To get around Git built in handling
https://github.com/git/git/pull/471#issuecomment-660205096
Tests updated
- Build da7659f46eed24c0d730898d8c6d0cf33d46abb2
----
> DiffTools: add 'tortoisediff' as a tool alias

- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
Fixes #8083 
- It shouldn't be necessary to restart GE to apply the new value.
- Disable limitation should not be an undocumented feature.
None
- Build d47d27eb1c7f0e566e48cce5694e6344d38dfbe4
- Git 2.26.2.windows.1
----
> Improve "Limit number of commits" option

- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Fixes #8279
Setup the Git repos used in the tests only once, to speed up tests.
For me, test time goes down from 1,6 mon to 11s, about twice the time for one test. (Longer time for other users.) 
- Setup attributes for Parallelizable to disallow the individual tests in parallel
More comments in the code
I consider this to be a major hack.
Tests only
- Build da7659f46eed24c0d730898d8c6d0cf33d46abb2
----
> SubmoduleTests: Setup repos once for all tests

- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitUI/CommandsDialogs/FormRemotes.Designer.cs
- GitUI/UserControls/CaseSensitiveComboBox.cs
Fixes #8030
- Change SaveRemote to consider case when deciding if the url text has changed
- Override Autocomplete behavior in ComboBox to prevent it from resetting case-only changes
- Manually tested by changing the url by 1,2 and 3 letters.
- Manually verified that autocomplete still works
- GIT  2.26.2
- Windows 10 latest update
----
> Fix for #8030 URL in "Edit Remote Details"is case insensitive

- GitUI/CommandsDialogs/FormSettings.Designer.cs
- GitUI/CommandsDialogs/FormSettings.cs
Contributes to #8339
Settings dialog takes on average 4+ seconds to load and show to a user. With that the initial load is tearing the UI, which is visually unpleasant.
Few major culprits:
* HasClippedControl() - ~2.5 seconds, which is 60%+ of the observed 4 seconds.
This appears to be trying to detect whether the settings dialig fully fits on a user's screen, and, if not, reduces the current font.
* settingsTreeView.GotoPage(_initialPage) - 500-600ms on average, which deals with raising notification events, removing the currently shown control, and binding the requested page. Depending on a complexity of UI of the selected page this can take anywhere from 10ms to 1 second (or longer).
* RevisionLinksSettingsPage - on average it takes 850-900ms to create this page, which breaks down to:
- …
> Optimise `FormSettings` load

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #8348
If base commit is not defined, use `--root` argument to create patch for root or orphaned comit.
- Tested on empty repository with one commit
- Tested with non root commits. Merges and single ones.
- Added additional test case for when `from` is empty.
- GIT  2.27.0.windows.1
- Windows 10 1909
----
> Fixes #8348. Allow to create patch for the root commit.

- GitCommands/Settings/FileSettingsCache.cs
- GitCommands/Settings/SaveSettingsException.cs
- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/Translation/English.xlf
- UnitTests/GitCommands.Tests/Settings/FileSettingsCacheTests.cs
Fixes #
- Don't show a message box when unable to save settings to a file.
Instead raise a `SaveSettingsException` that gets handled at the UI layer, and displayed in a task dialog.
- Remove FormSettings.Save check for git
- If git is missing the process will crash, so the check is not adding any value, but consumes cycles.
- If git is present, running `Module.GitExecutable.GetOutput("")` is for the most part pointless.
* ![image](https://user-images.githubusercontent.com/4403806/88477121-de444100-cf80-11ea-9f35-8e555e1d8b16.png)
- manual
- enabled unit tests
- GIT 
- Windows 
----
> fix test: SaveImpl_should_throw_if_invalid_path

- GitUI/GitExtensionsForm.cs
- GitUI/Interops/DwmApi/DwmApi.cs
- GitUI/Theming/ThemeModule.cs
- Set a dark titlebar when using a dark theme when the user use a supported version of Win10
The title bar is always white...
light theme:
dark theme:
- Manual
- Build 26402f0898e7107f5b8978fa8c8a2416198a864b
----
> Dark titlebar when using a dark theme on a recent Win10

- GitCommands/GitCommands.csproj
- GitCommands/Settings/BasicSettingTypes.cs
- GitCommands/Settings/Setting.cs
- Add the ability to receive an event about a change in the setting value.
- Also, in the future, we can remove all classes inherited from Setting<T> and use one generic.
----
> AppSettings Updated event

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
Fixes #7676
Whenever the treeview in the left panel is refreshed, the currently checked out branch is being selected irrespective of whether the branches node is expanded or not.
This causes unnecessary refreshes, change of selection, and generally unpleasant UX.
- manual
> Don't expand branches node on refresh

- GitCommands/DiffMergeTools/Araxis.cs
- UnitTests/GitCommands.Tests/DiffMergeTools/RegisteredDiffMergeToolsTests.cs
- contributors.txt
Fixes #8351
Added back the Araxis merge/diff tool as requested in #8351 
- Created a new class for Araxis.cs in the DiffMergeTools.cs
- Extended the existing unit tests
- GIT 
2.28.0
- Windows 
Version	10.0.19041 Build 19041
It's my first PR for GitExtensions please let me know if I need to change anything.
----
> Fix 8351 - "Araxis does not show up in Mergetool/Difftool dropdown box"

- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConsoleStyleSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConsoleStyleSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConsoleStyleSettingsPage.resx
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs
- GitUI/Translation/English.xlf
- contributors.txt
Fixes #8306
- Remove Console style and font controls from Detailed > Browse Repository Window
- Add new Settings page under Appearance > Console Styles, and add the removed controls to this
- Purely a UI thing, no real logic was changed.
- After moving the controls to another page, ensures that changing the values saved properly and were loaded at next restart
- Also ensured that the style and font settings actually got applied to ComEmu
- Other than the designer page to remove the controls, no code was touched for the Browse Repository Window page
- Windows 10
- English. Where possible I kept text  the same so as to avoid re-translations. I haven't tested with non-English locale
---- …
> Introduce a new console styles settings page under Appearance

- GitCommands/Git/GitModule.cs
- GitCommands/Settings/RepoDistSettings.cs
- GitCommands/Settings/Setting.cs
- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowseController.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Infrastructure/Telemetry/FormBrowseDiagnosticsReporter.cs
- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
- GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
- UnitTests/GitCommands.Tests/Settings/SettingTests.cs
Continuation #8450, #8451
- Drop ValueOrDefault property
- Add IsUnset property
For non nullable
Value = (value ?? Default), IsUnset = (value == null)
For nullable except "String", all values is significant
Value = value, IsUnset = false
- Manual
----
> Settings [cleanup]

- GitUI/CommandsDialogs/FormPull.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPullTests.cs
Fixes #8463
Continuation #8433
- Manual
- Unit Tests
----
> Prevent adding "--prune --prune-tags" when run from toolbar

- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs
Fixes #8446
- The use "AddSettingBinding" in "FormBrowseRepoSettingsPage" doesn't make sense because the page implements only IGlobalSettingsPage
- Manual
----
> Don't use "AddSettingBinding" in "FormBrowseRepoSettingsPage"

- GitUI/GitUIExtensions.cs
Fixes #5547
* A null patch was displayed as a text file instead of a patch, so the toolbar was missing
Manual
----
> Show empty diffs as patch, not text

- GitExtUtils/GitUI/Theming/ColorHelper.cs
- GitExtUtils/GitUI/Theming/ThemeSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
- GitUI/Theming/ThemeModule.cs
**Attention this PR is made above #8424 so only last 2 commits are to be reviewed here**
Correct color calculations to make result colorblind-friendly If "Colorblind" checkbox is set in ColorSettings page, replace red-ish colors with blue-ish by compressing blue-orange ark in hue circle into blue-violet
before
after
after v2, modified to reduce contrast loss, as @neil5280 noticed
Besides syntax highlighting colors, other auto-calculated colors get affected as well.
Observe how build status colors change
before
after
after v2
> Colorblind syntax colors

- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/Script/ScriptOptionsParser.cs
- GitUI/Translation/English.xlf
- UnitTests/GitUI.Tests/Script/ScriptOptionsParserTests.cs
Fixes #8486
together with #8487, on which this PR is based.
- add script options `{cSubject}` and `{sSubject}`
- change script options `{cMessage}` and `{sMessage}`to yield the full message
The linefeed characters are replaced with `\n`.
- adapted and added NUnit tests
- manual
- Build 8bc7355730d48b869ea0389bed8ffd59f3d77695
----
> Add script options {sSubject} and {cSubject}

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
Jenkins can start many builds for a commit, for instance for the branch and the pull request.
In some occasions the subsequent build(s) are aborted immediately, getting status NOT_BUILT
It is of course possible to abort builds too
The Jenkins build adapter presents the status for the latest build started for a commit regardless if it is complete or not.
This tries to present the most interesting status instead. 
- Cleanup from Re#, some manual adjustments
- The intervall for retrieving running builds was changed to two minutes in 3fcb4788b42d9b485880eb756e4bdc0af47d321b, but the full day obervable was kept at one minute
Manual
----
> Jenkins: Present most recent interesting build info

- GitCommands/Settings/Setting.cs
- UnitTests/GitCommands.Tests/Settings/SettingTests.cs
Fixes #8493
- Write and read enum setting as string not number
- Enum value is stored as number
- Enum value is stored as string
- Automation
----
> fix: Write and read enum setting as string not number

- GitCommands/RevisionReader.cs
- GitUI/FilterBranchHelper.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RefFilterOptionsEventArgs.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
Fixes #8484
Whenever the filter value is being cleared in the UI, the filter isn't getting reset in the underlying plumbing.
The fix resets the filter.
This unblocks #8414 
- manual
- integration tests
----
> fix: Branch filter isn't truly reset

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/WindowsJumpListManager.cs
> Fix JumpList being created too soon

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/ICheckRefs.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
Indicate branches and tags in the left panel that are currently filtered out and not visible in the revision grid.
* The hidden refs are greyed out and their icon is changed to "closed eye".
* Each node in the tree now has a new property `IsVisible` that can be used as a conditional flag when implementing necessary logic.
Detection of whether a given ref is visible or not is done by checking the revision grid, which is currently the source of truth. 
Whenever the revision grid is refreshed, it raises an event that causes the left panel to update its state, and show or hide nodes.
* Show all
* Show only current branch
----
> Filter out hidden branches

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCreateTag.Designer.cs
Fixes #8418
- When choosing to sign with a specific GPG key, the input box now supports 16 characters (instead of 8).
----
> Longer GPG key input box (8 chars -> 16 chars)

- GitUI/CommandsDialogs/FormVerify.cs
- GitUI/CommandsDialogs/FormViewPatch.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/Editor/FileViewer.cs
There is at least one issue discussing this that I cannot find right now...
- Replace a couple of booleans tracking current information in the file viewer with an enum
- Hide actions in GitHub view pull request form that have no functionality 
- Refresh Patch and GitHub file  viewer pull requests when changing the syntax highlight
This will also be used for the presentation part of https://github.com/gitextensions/gitextensions/pull/8471 that adds more internal changes as well as for #7825 when unifying code from FormCommit/RevDiff (FileStatusList will be required too then).
A CommitDiff mode can remove some duplicated code from FormCommit
Note that the title bar is not following the normal style, same for all plugins.
Manual
----
:black_nib: I contribute this code under [The Developer …
> FileViewer: ViewMode to track what is currently displayed

- GitUI/FilterBranchHelper.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Appears to be a regression from #8485 which caused the revision grid to be refreshed whenever an action was raised via the toolstrip, e.g. invoking fetch would refresh the grid before the fetch operation was performed, as well as after.
Somehow the toolstrip would pass focus to all its items, that included the Branch Filter which in turn would cause the refresh.
Update the logic to force the grid refresh only when the filter is being changed and applied.
What's worse, multiple refreshes could overlap each other due to peculiar behaviour of the toolstrip, which keeps on passing focus back to its items,
and with that invoke `FilterBranchHelper.toolStripBranches_Leave()`.
There was also another strange behaviour that could lead to a blank revision grid - if a user typed a filter but hasn't …
> Don't refresh revision grid invoking toolstrip actions

- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/Translation/English.xlf
Fixes #4421
- Set push to default for multiple branches
- Change column name _Push (Force Rewind)_ to _Force_ (The tickbox is either Push or Force, but I believe just Force is clear enough)
No implementation of ticking multiple branches
Manual
----
> Push multiple: Set default push to false

- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormPush.resx
- GitUI/Translation/English.xlf
Contribute to fixes in #4421
New contextual menu when right or left click on the "Push" column header with some options
* to unselect all
* to select all
* to select only the ones already tracked (default state)
Nothing
New contextual menu when right or left click on the "Push" column header:
- Manual
- Build 746264ccaf851fcc7e51d3cb7b49b062eec7c2e7 (Dirty)
- .NET Framework 4.8.4240.0
> FormPush: Add context menu to easily manage multiple push selection

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
Fixes #8390
Sorry @RussKie if you have it implemented already, I've noticed that you are an assignee only after investigating this issue `¯\_(ツ)_/¯` we can close this if it duplicates your effort.
- Use `treeMain.SelectedNode` to track which node is active and should be used for a context menu
- Manual testing with right-click and invoking context menu through a keyboard button
- Windows 10
----
> Use SelectedNode property to track target for context menu

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
when right clicking in the grid
Fixes #8475
- try/catch to swallow an exception that we were unable to prevent... 
- none (reading stacktrace)
- Build 905403fe2edfa879c96e293973afebe555eb6e8e
- .NET Framework 4.8.4240.0
> RevisionGrid: Prevent inopportune crash

- GitExtUtils/GitUI/Theming/ColorHelper.cs
- GitUI/UserControls/FileStatusList.cs
- UnitTests/GitExtUtils.Tests/ColorTransformationTests.cs
- contributors.txt
Fixes #5499. As a good addition, the look and feel of the selected row in this list is the same as in the commit list. It looks much better when both selected rows in different lists are in the same style. Tested on Windows 7 (with classic theme) and Windows 10 (with default theme). 
----
> [#5499] Fix invisible row selection in the file status list control.

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #8404 (Remove Files generates FileName or extension too long)
- Updated GitModule.RemoveFiles to use GetBatchOutput with BuildBatchArgumentsForFiles
- Added unit test for empty file list 
- Added unit test for 2 files in the list 
- 
- GIT 2.8
- Windows 10
----
> updated removeFiles to use GetBatchOutput and added unit tests

- GitUI/CommandsDialogs/FormSubmodules.cs
- contributors.txt
Fixes #4366 by saving the position of the splitter
- Manual
- Windows
> Submodules window now keeps the splitter position

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/CopyContextMenuItem.cs
Fixes #6304
- Create and add to context menu on the left panel CopyContextMenuItem
Manually 
----
> Add ability to Copy to Clipboard, similar to commit context menu from left panel

- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.resx
- GitUI/Translation/English.xlf
Fixes https://github.com/gitextensions/gitextensions/pull/8424#issuecomment-688712943
- Add a button to be able to open Application and User theme folders
(same than after without the button)
- Manual
- Build 62fcfcbd924a264d34b02ae9831749acc43fef8f (Dirty)
- .NET Framework 4.8.4240.0
> Add a button to be able to open Application and User theme folders

- Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
- Add a warning in the "background fetch" plugin to warn the user 
about some risk when using the "git push --force-with-lease" feature
no warning message.
- Manual
- Build 905403fe2edfa879c96e293973afebe555eb6e8e
- .NET Framework 4.8.4240.0
> BackgroundFetch & push --force-with-lease : add a warning message

- GitUI/CommandsDialogs/FormResetChanges.Designer.cs
Fixes #8467 
- Added `btnCancel.Select()` to the constructor. Left existing mnemonic of "r" for the reset button.
- "Focus" did not stick after form was shown, but after testing found that "select" worked during form load/initialization
- I currently performed manual UI tests both visual and then message feedback (removed after test) to verify focus. I can add UI test if desired.
- GIT 2.28
- Windows 10
As mentioned in the issue report - user reported they pushed r twice and files reset. This will not change that behavior due to mnemonic, but will prevent "enter" key from automatically resetting files.
----
> Ensure focus is on cancel button for Reset Form

- GitCommands/Git/GitItemStatus.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitVersion.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- GitUI/GitUIExtensions.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusItem.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/FileStatusWithDescription.cs
- UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.fatal_error.approved.json
- UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_ignored_files.approved.json
- UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_modified_files.approved.json
- UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_staged_files.approved.json
- UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_untracked_files.approved.json
- UnitTests/GitCommands.Tests/Git/GetAllChangedFilesOutputParserTest.TestGetStatusChangedFilesFromString.ForScenario.status_with_spaces.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Check_that_spaces_are_not_trimmed_in_file_names.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Check_that_the_staged_status_is_None_if_not_IndexWorkTree1.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Check_that_the_staged_status_is_None_if_not_IndexWorkTree2.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Ignore_unmerged_in_conflict_if_revision_is_work_tree.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Include_unmerged_in_conflict_if_revision_is_index.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.Rename_with_spaces.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree1.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree2.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree3.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.WorkTree4.approved.json
- UnitTests/GitCommands.Tests/GitModuleTests.GetDiffChangedFilesFromString.ForScenario.fatal_error.approved.json
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Part of #8448 support for range diff
First 4 commits are refactoring, the two following are likely to be squashed (the second changes data structures, separated for review)
#8516 is a separate PR for presentation
Present range-diff in diff tab
Limit RevDiff context menu entries for combined diff and Git Errors, to limit for range-diff too (will be kept as a separate commit)
range-diff is new
combined diff
See #8516 for range-diff
Combined diff
manual
----
> support for range-diff

- GitUI/CommandsDialogs/SubmodulesDialog/FormAddSubmodule.Designer.cs
Fixes #6557
- Change FormBorderStyle from SizableToolWindow to SizableWindow
- Manual
- Build 2487b7003669bf37828e45aa4b529930d8b72194
----
> Add ability to show "Add submodule" Dialog on taskbar.

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/GitUI.csproj
- GitUI/GitUICommands.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- Plugins/BuildServerIntegration/AzureDevOpsIntegration/ApiClient.cs
- Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsAdapter.cs
- Plugins/BuildServerIntegration/AzureDevOpsIntegration/AzureDevOpsIntegration.csproj
- Plugins/BuildServerIntegration/JenkinsIntegration/JenkinsAdapter.cs
- Plugins/BuildServerIntegration/TeamCityIntegration/TeamCityAdapter.cs
- Plugins/BuildServerIntegration/TfsIntegration/TfsAdapter.cs
- Plugins/GitUIPluginInterfaces/BuildServerIntegration/IBuildServerAdapter.cs
- Plugins/GitUIPluginInterfaces/IGitUICommands.cs
- Solution.Versions.props
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/AppVeyorAdapterTests.cs
- Detect when Azure DevOps token is invalid/expired
and display an explicit error message.
Better than the current behavior that is displaying nothing
so the user doesn't understand what is happening (even me that developped the plugin 🤣  )
It happens sometimes and is difficult to understand/detect
when the token has expired (because maximum duration is 1 year)
Nothing. Azure Devops pipeline results are just not displayed.
An error message is displayed **once**:
A tooltip is always displayed on the "Working directory" pseudo commit result (in case the user didn't carefully read the popup message):
- Manual (change the token to set a bad one to see the new behavior)
- Build 905403fe2edfa879c96e293973afebe555eb6e8e
- Microsoft Windows NT …
> Detect when Azure DevOps token is invalid/expired

- GitUI/CommandsDialogs/FormPush.cs
- GitUI/Translation/English.xlf
Fixes #8548
- Slightly safer regex to check for current branch
- If push is rejected for other than current, offer a slim-down variant of the error dialog. Currently, this is a subset of the "full" dialog, this could change
Note that the full dialog is displayed if current branch is pushed at the same time as any other branch. This is OK, the pull actions have no effect on the non current branches
none - see #8548
Manual
----
> FormPush multiple: force-with-lease if rejected

- GitUI/CommandsDialogs/FormResetChanges.Designer.cs
- GitUI/Translation/English.xlf
Fixes #8467 
Set button mnemonic to "E" for the reset button on the reset form.
visual review.
- GIT 2.28
- Windows 10
----
I agree to the Developer Certificate of Origin.
> update button mnemonic for Reset button on Reset Form to "E"

- GitUI/CommandsDialogs/FormCreateBranch.Designer.cs
- GitUI/CommandsDialogs/FormCreateBranch.cs
Relates to #6183
* Before:
* After
❗ Please note "Help" button will be removed in the follow up PRs to reduce the wasted space at the bottom.
----
> Dialogs layout alignment - `FormCreateBranch`

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Fixes #8146 "Keyboard navigation : Enter Key should open a recent repository"
- intercept "Enter" key event and attempt to open the selected repository, if anything is selected
- I've attempted to use the enter key in a variety of scenarios, including when there is no repository selected, when there is a repository selected, when there is no repository selected but the list group is collapsed, and when there is a repository selected but the list group is collapsed
- - Out of these scenarios, there seems to be an issue only when pressing enter when a repository is selected but the list group is collapsed.  Since the list group was collapsed, I would have expected a no-op, since we cannot visually tell what repository is selected.  I cannot fix this, however, as it seems like the …
> Fixes #8146 "Keyboard navigation : Enter Key should open a recent repository"

- GitUI/CommandsDialogs/FormCheckoutBranch.Designer.cs
- GitUI/CommandsDialogs/FormClone.Designer.cs
- GitUI/CommandsDialogs/FormCreateBranch.Designer.cs
- GitUI/CommandsDialogs/FormInit.Designer.cs
- GitUI/GitExtensionsDialog.Designer.cs
- GitUI/GitExtensionsDialog.cs
Addendum to #8490 
- Fix button layout in `FormCreateBranch` which slipped in #8490 due to an incorrect rebase.
- Replace the custom `GotoUserManualControl` control on dialogs that inherit from `GitExtensionsDialog` with the Windows default help mechanics, i.e. [?] button in the caption box of a dialog.
- Add missing links for the existing forms.
* Before:
* After
----
> Add dialog help that navigates to the docs

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
This should prevent "hanging" during startup
Fixes #8337
- Parallelize IsValidGitWorkingDir checks.
- Using PLINQ
- Switched out the foreach on repos to a for loop so it could access the validity results by index
- Tested Locally using Stopwatch to measure the effect on successfully validated repos
- Debugged scenarios involving Invalid Repo(s)
- I was unable to setup any shares to check 
- GIT 2.28.0.windows.1
- Windows 10 (Lastest as of 10/2/2020)
----
> Parallelized Repo Validity Checks during Startup

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #7557 - Dashboard: GitHub clone shortcut missing at initial load
- refresh the UI when plugins are done registering
- also re-register plugins whenever setting git module to an invalid git repo (means we are going to the dashboard)
Opening straight to the dashboard has missing plugin-action entries under "Clone repository"
Closing out of a repo to the dashboard has missing plugin action menus
A refresh is done when opening straight to the dashboard to render the asynchronously loaded Git-host plugins
Similar behavior occurs when closing out to the dashboard from a valid repo
- interactive testing with changes (launching straight from Visual Studio), compared against a clean install from my machine
- GIT 2.28.0.windows.1
- Windows 10
---- …
> Fixes #7557 - Dashboard: GitHub clone shortcut missing at initial load

- GitExtUtils/GitUI/Theming/ColorHelper.cs
- GitUI/UserControls/RevisionGrid/CellStyle.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
As [promised](https://github.com/gitextensions/gitextensions/pull/8371#issuecomment-694135580)
- Render commit body using gray text color in revision graph
to separate it from commit subject
- Apply draw non relatives text gray appearance setting to selected row
since now we have a ready-to use mechanism to produce a gray text color for highlighted text
- Split commit message rendering in Revision Grid to smaller methods
unselected row
selected row
draw non-relative text gray in selected row
Tested manually in Windows10
----
> gray additional commit lines in revision grid

- CONTRIBUTING.md
Seems that label names were changed and the current CONTRIBUTING.md links to label search queries without results.
----
> Fix label names in CONTRIBUTING.md

- GitUI/GitExtensionsDialog.cs
* Task Dialog
* GitExtensionsDialog
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/4403806/96721841-6909d000-13f8-11eb-8fda-78498bbfac83.png) | ![image](https://user-images.githubusercontent.com/4403806/96721517-f698f000-13f7-11eb-8a12-fa52d9ca14af.png) |
| ![image](https://user-images.githubusercontent.com/4403806/96721788-5a231d80-13f8-11eb-8eeb-04b6ff073a18.png)  | ![image](https://user-images.githubusercontent.com/4403806/96721369-c2bdca80-13f7-11eb-85b1-d49a13882c9f.png) |
----
> Draw a separator line at the top of the footer panel, similar to what Task Dialog does

- GitUI/CommitInfo/CommitInfo.cs
- Reduce the number of calls to the UpdateRevisionInfo method.
- Manual
- Visual
- Build a1c3adc78a89fed5f0d6074454164ee42a5eba65 (Dirty)
----
> Reduced the number of draw calls on the commit info panel.

- GitExtUtils/FileUtility.cs
- GitUI/CommandsDialogs/FormEditor.cs
Fixes #8347 
- Use the TextWriter Logic recommended on [StackOverflow](https://stackoverflow.com/questions/2246990/how-do-i-write-to-a-hidden-file/2247115#2247115)
- Prevents issues with hidden files caused by File.WriteAllText
- File.WriteAllBytes does not appear to have this issue based on reference source
- ~Move the general try/catch logic inside of SaveChanges()~
- ~Added a paramter rethrowException (default: false) to allow custom handling such as on Form Close.~
-  Manual Testing Saving with no special circumstances
- Debugging to explicitly throw exceptions from inside SaveChanges to test rethrow on form close
- Manually Testing Saving Changes on ReadOnly Files, Hidden Files, and Files that are Locked ( I expect Readonly and Write Locked files to fail while hidden should succeed). …
> FormEditor SaveCanges Changes

- GitUI/CommandsDialogs/FormPush.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPushTests.cs
Fix #8188: cannot force push tags
- Checking the "force push" option in the tags tab of the push form resulted in passing ForcePushOptions.ForceWithLease to the git push command builder
- Add a check for the force push checkbox for the tags tab in order to pass the correct ForcePushOptions.Force value to the command builder
- I've tested this out with a dummy remote repo on GitHub and verified that I am now able to force push a tag from one commit to another
- GIT 2.28.0.windows.1
- Windows 10
----
> Fix #8188: cannot force push tags

- GitCommands/Git/AheadBehindData.cs
- GitCommands/Git/AheadBehindDataProvider.cs
- UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
First part of #8553 
- Show ahead/behind if remote is up to date
- Show if the tracking branch no longer exists "gone"
Only the branch with differences displays the count
No indication if the branches are up to date
feature/i8553-ahead-zero-gone is not yet pushed
feature/i8548-multiple-force-push is deleted at the remote
feature/i8448-presentation is pushed and in sync with the remote
feature/i8448-range-diff-3 same as above (not displayed)
After a branch is pushed
Tests adapted and expanded
----
> Ahead/behind show up-to-date and gone

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/CommandsDialogs/BrowseDialog/MenuCommand.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowse.resx
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/Translation/English.xlf
Relates to #5525
- Break the main toolbar into two - general operations and filters. This is arbitrary, filters were the easiest to break out. The main point of the PR was to attempt the split and see how well it works. This then maybe used as a foundation for further refactoring of the toolstrip area, such as moving user scripts to own toolstrip, view-related, repo-related... Possibilities are endless.
- Save/restore positions of the toolbars
----
> Break the toolstrip

- GitUI/Themes/dark.css
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fix too low contrast between commit body and background in dark theme.
Problem was introduced in #8550 and [pointed out](https://github.com/gitextensions/gitextensions/pull/8550#issuecomment-716208279) by @gerhardol
> fix background / foreground contrast for gray text

- GitUI/Editor/Diff/DiffHighlightService.cs
- GitUI/Editor/Diff/LinePrefixHelper.cs
- GitUI/Editor/Diff/RangeDiffHighlightService.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/GitUIExtensions.cs
Fixes #8448 
Based on #8471 . Except for one line, this is independent of #8471, but it is meaningless as nothing is changed. However, changes in #8471 should result in minimal changes this PR. This is therefore not a draft.
Present range-diff output as a special diff variant with highlighting etc.
- ViewMode for range-diff, to limit menu actions (copy patches, apply patches)
- Next/previous change moves to the commit-pair header. The important with this feature is not really to see the patches
- Set syntax highlight to first found filename
- Highlight for content:
- Commit-pair "headers" - AuthoredHighlight
- Filename or patch start (very random contents...) - DiffSection
- Lines only changed in last selected - DiffAddedExtra/DiffRemovedExtra
- Lines only changed in first or same change …
> range-diff presentation

- GitCommands/Git/AheadBehindData.cs
- GitCommands/Git/AheadBehindDataProvider.cs
- GitCommands/Git/GitRefName.cs
- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/Translation/English.xlf
- UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
- UnitTests/GitCommands.Tests/Git/GitRefNameTests.cs
Part of #8553 
Based on #8562 , really separated of the original intended change
Only show remote branch name if there is a tracking branch
Show ahead/behind information in FormPush multiple branches, like "0↑↓" and "gone" added in #8562
If the current branch is not the tracking branch but a name match is possible, show "=" and "<>".
(gone is discussed in #8562)
Manual, added test for GitRef
----
> FormPush show ahead/behind for  multiple branches

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- GitUI/UserControls/InteractiveGitActionControl.cs
- Plugins/BackgroundFetch/BackgroundFetchPlugin.cs
Related to the closed issue of #6692 and others
Submitted to minimize time wasted on this again.
With regards to https://github.com/gitextensions/gitextensions/issues/6692#issuecomment-710881897
This change is like allowing the user to hot swap the engine while running, as long as they do not touch any controls,
or they have changed specific addons.
Ignore exceptions for GitStatusMonitor and Background fetch plugin,
as well as "Browse activation" (selecting the window).
This is the most common background use of Git.
The primary usage is to allow Git upgrades while GE is active.
Active use of GE will raise exceptions, not much can be done when Git is not available.
#8278 or #8358 improves the error message.
Note that GitStatusMonitor will not monitor changes until refresh or a new repo is …
> Do not  throw if Git is upgraded  while GE is started

- GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
Fixes #8591 
- When opening the form, the focus is on the commit textbox and the text is selected if textbox if filled with the clipboard content.
Perhaps not the best way to fix but it works...
- Manual
- Build 7a52bdf65744b5d760d9edb9afc9a1863b88d2e7
> FormGoToCommit: set focus on commit textbox when no control has focus

- GitCommands/FileAssociatedIconProvider.cs
- GitCommands/FullPathResolver.cs
- GitCommands/Git/GitItemStatusFileExtensionComparer.cs
- GitCommands/GitRevisionInfoProvider.cs
- GitCommands/PathUtil.cs
- GitCommands/StringExtensions.cs
- GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeController.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
- GitUI/Editor/FileViewer.cs
- GitUI/UserControls/FileStatusList.cs
- Plugins/Statistics/GitStatistics/LineCounter.cs
- UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs
- UnitTests/GitCommands.Tests/EnvironmentPathsProviderTests.cs
- UnitTests/GitCommands.Tests/FullPathResolverTests.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Fixes #8571 
Fixes #8364 
Fixes #8437
Fixes #7862
FullPathResolver throws if a file name contains Windows illegal characters that could be OK in Git repos. 
As FullPathResolver is often used to check if a local file exists for instance to enable menu items, an exception
is normally not required and null can be returned instead. 
For instance `File.Exists(null) ==false`.
In some situations returning null will still cause a null exceptions instead.
Reviewed the usage of Resolve() to change situations where null should not be fatal. This review is best effort, there may be other situations that should be changed too. Most "null unhandled" are used in Process(), there are other PRs there.
Some handling already use try-catch, like Delete in FormCommit.
An alternative would be to add a new …
> FullPathResolver: Avoid exception for illegal characters

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #8600
- Use `UICommands.OpenWithDiffTool`, just like `RevisionDiffControl`, with `diffKind = RevisionDiffKind.DiffAB`
- Manual test. FormCommit has no unit test. I found an integration test for FormCommit, but there's no test for difftool yet.
----
> Fix Open with Diff Tool does not work with staged renamed file in FormCommit dialog

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Fixes #8588 
- Do not show cherry-pick in the file status list if the file is added or if the file does not exist 
Note that the FileViewer check for support patches is quite incomplete and fails for instance for 8a8985d78edb997d094ad9642220a8457b2c7f9b GitUI\Editor\Diff\RangeDiffHighlightService.cs
This is fixed in #7825 (that is blocked for other reasons.) Will not be handled here.
- Do not show _Show in File tree_ if the file has been deleted (as it will not exist in the tree)
Tests updated
----
> RevDiff context menu for cherry-pick

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/TreeViewExtensions.cs
- Correct sorting in the left panel without enabled filters, as the current behaviour doesn't requery data, nor refresh the content.
There are two distinct, yet connected, operations:
- sort (with and without a filter), and
- filtering.
The "filter" is primarily concerned with rendering, i.e. visually indicate  which refs are accessible and which are not. Whilst the "sort"'s purpose    to requery data from git, and refresh the tree applying any existing filters.
To facilitate the above two distinct API are provided:
- `ToggleFilterMode(bool)` to turn filter-mode on/off
- `Refresh()` which breaks local caches for each participating tree, and    refreshes data.
- Whenever the refs tree is refreshed due to changes in refs order    the tree would retain the `SelectedNode` by index. E.g. if …
> Fix left panel broken sort and filtering

- GitUI/UserControls/BlameControl.cs
Seem to be regression from 3.2 6eeaa4c5acbab99a1a0d4ed8376092d06230b4fc
If an empty file is selected or there are errors parsing git-blame, viewing blame will just show the spinner.
It is possible to select other commits or select another tab, so the app is not hanging.
Manual, one of the following:
* Add an empty file (touch t.txt (emptylines will also cause the problem), add it to Git).
* Make sure git-blame fails by setting `git config blame.ignoreRevsFile .git-blame-ignore-revs` to a file that do not exist (that was what got me started with this - Git need to support `git blame --ignore-revs-file` better to make GE support meaningful.)
The handling of Git failures need a general overhaul - after the current error handling changes are done.
----
:black_nib: I contribute this code under …
> Blame: Spinner not dismissed for empty files and errors

- GitUI/CommandsDialogs/FormFileHistory.Designer.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/Translation/English.xlf
Add button to show _Git command log_ in FormFileHistory
#8076 changed FormFileHistory to run in a separate instance and Git command log is no longer including those commands.
There are no appropriate menus to put this is in, so a button on the top level is added
An alternative is maybe to only use a shortcut key.
Manual
----
> FileHistory: Git command log

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseUtil.cs
Fixes #8630
- FileInfo.Directory may fails if the name is forbidden.
Forbidden filename can't be created when checkout.
So file are shown missing in the diff window.
Click right on this file generate exception.
No more exception.
- Sorry, didn't write tests…
- Build cf43b769311b80db2bf7c92a05f6b366a69ceba0
- Git 2.22.0.windows.1 (recommended: 2.28.0 or later)
----
> Fix #8630: better handle "forbidden" filename

- GitCommands/Git/Commands/GitCommandHelpers.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Relates to #8621
Git tags may be concrete refs and ephemeral (i.e. dereferences), which
adds a layer of complexity to sorting refs.
The original sort mechanism ordered by refs first, followed by derefs.
However it caused local and remote branches to be sorted incorrectly.
Invert the sort order to ensure branches are sorted correctly at the expense
of correct tags order.
----
> Prefer correct local and remote branches sort to tags

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
#8516 etc added git-range-diff. After some usage, I would like to change the presentation a little.
Currently the first and second commits are presented. I have found that I often want to know the commit count for first/second  to the merge-base, similar to ahead/behind info. The first/second is (normally, see below) listed anyway in other groups and the second commit is not often seen as as the group name is too long.
If one of the first/second selected is artificial, the range diff uses HEAD. This is not listed in the other group names, but should be obvious.
To avoid a second call to git-rev-list (adding about 40 ms on my PC), a modified git-rev-list call was added.
FileStatusList must be wide to see the second revision
Manual
---- …
> RangeDiff: Commit count in name

- GitExtensions/GitExtensions.csproj
- GitExtensions/Properties/launchSettings.json
Move the hidden start arguments from .csproj to launchSettings.json
This allows view and edit of the arguments, otherwise hidden in MSVS
Regression of a regression fixed in #7147 
Probably introduced by SDK style projects
Store the debug startup args in the new defaults so it can be viewed and changed.
This is needed to debug the GE startup. (See related issues and PRs for a discussion.)
Without this, it is quite hard to realize that the GE command line behavior is different in the debugger.
args not visible
Manual, starting in debugger
----
> Default debug startup arguments

- GitCommands/Git/GitModule.cs
- GitUI/Editor/RebaseTodoHighlightingStrategy.cs
TryHighlightInteractiveRebaseCommand() assumes that Git sha are longer than 5 chars when highlighting.
The minimum is 4, can be set:
`git config --global core.abbrev 4`
(Separate note: I would like to read and use this value in the GUI to limit printouts, separate.)
Also a minor optimization to use a compiled RegEx. (One of the few situations where `RegexOptions.Compiled` makes sense, should slow down in most other situations.)
(Seen in other situations, no good PR to attach it to and not worth a PR on its own.)
Manual
----
> Interactive rebase: Highlight 4 byte sha

- GitCommands/Git/GitRef.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- Plugins/GitUIPluginInterfaces/IGitRef.cs
- UnitTests/GitCommands.Tests/Git/GitRefTests.cs
When using the "Reset another branch to here..." feature, if there are remotes on the selected commit, find the local tracking branches of these remotes and display them first (because there is a highest probability that this is these local branches that you want to reset).
It is very useful to easily update the local tracking branch without having to check it out before...
- Manual
- Build d30897a43b6d17e20e7c8e9e645446cb93e83f3e
> FormResetAnotherBranch: display local tracking branches first

- GitExtUtils/GitUI/Theming/ColorHelper.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FullBleedTabControl.cs
- Add paddings and borders for panels.
- Adds expressiveness and allows to clearly delineate the main panels.
It would be nice to make the colors softer. Like this.
- Manual
- Visually
- GIT 
- Windows 
----
> Add paddings and borders for panels

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.cs
See: https://github.com/dotnet/docs/issues/19274
Fixes #8363
Fixes #8367
Fixes #8425
Fixes #8634
----
> Remove support for UTF-7

- GitCommands/Git/GitModule.cs
- GitCommands/Patches/PatchFile.cs
- GitUI/CommandsDialogs/FormApplyPatch.Designer.cs
- GitUI/CommandsDialogs/FormApplyPatch.cs
- GitUI/CommandsDialogs/FormRebase.Designer.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/PatchGrid.Designer.cs
- GitUI/UserControls/PatchGrid.cs
- GitUI/UserControls/PatchGrid.resx
Fixes #8540, #7152 and #6350
- Fix the list of displayed commits that are rebased to always display all of them and with the good `Status` displayed
- other adjustments:
* Move the important 'Status' column to be the first one (and not lost after author and date so that it could be more easily compare to the `Action` and `Subject`)
* Display commit hash
* Rename "Name" header to "Action" (because it display the define action. Especially when doing an interactive rebase)
* Being able to open a commit diff window by double click (like it is possible to see the patch file for the patches)
* Set a minimum height for a row (to avoid possible strange behavior)
* Resize some columns
* New list:
* Opening a commit:
- Manual
- GIT 
- Windows 
---- …
> Fix rebase status displayed during a rebase

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Fixes #8104 
A few other NBug issues exist. I have considered this to be a too much edge case to fix it. Maybe users experience this before they have downloaded submodules? Or this is an indication that there are few serious NBug issues that are not reported.
There has been cleanups for access to submodule dirs in changes the last year, for instance #7690 and #8117, to not access submodules if the directories does not exist.
Only show context menus for work tree submodules "internals" if the submodule directories exists, required for the Git commands to run.
For FormCommit, the menus are disabled.
For RevDiff the menus the are not shown. The Controller structure (which is made this way to test) adds another layer to handle enable/disable and makes this quite complicated, it is not worth …
> Submodule context menus: Only show if dir exists

- GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/Translation/English.xlf
#8194 for merge tools
Adds a dropdown menu in FormResolve to choose the merge tool without changing the defaults.
Some tools work better in some situations.
(a separate fixup to remove unused code, will be squashed)
There are some alternatives not handled hare:
* Expose this in the split button
* Implement this in the "Git Extensions" workflow where handling of files changed is asked in a terminal instead of a popup, 2way merge filters etc is handled. 
I just do not think it is worth it to implement this.
Tests were added in #8194
----
> Custom mergetool

- UnitTests/GitCommands.Tests/GitModuleTests.cs
Tests occasionally fails:
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/36792510#L514
The branch test just before was successful
Not fixing the test as there is no information, just improve printout by removing the count check to better see what fails.
Before:
```
Expected: 3
But was:  2
```
After (removed first item in compare list)
```
Message: 
Modules: repo1 repo1/repo2 repo1/repo2/repo3
Expected is <System.String[2]>, actual is <System.Collections.Generic.List`1[System.String]> with 3 elements
Values differ at index [0]
Expected string length 11 but was 5. Strings differ at index 5.
Expected: "repo1/repo2"
But was:  "repo1"
----------------^
```
There are other tests that should be changed in a sililar way, like …
> Improve printout for flaky test

- GitUI/Theming/ThemeBasedHighlighting.cs
If ICSharpCode.TextEditor is in Debug mode, an assert occurs if setting SyntaxColor with a null value.
SyntaxColor is empty for empty lines, no need to set the value to null again.
The default configuration for the module is Release, so by default no change.
Manual, using Debug
----
> Avoid assert for null syntax color

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #8669
* Don't try to select "File tree" if it is not displayed
* Switch to "File tree" after some content check (to prevent inopportune switch to the tab)
- Manual
- Build f5362ec637de01d40be55f5d0abfbbc7b6e9d828
> Improve handling of Drag and drop

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitorState.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Display when the commit count is inactive or not yet updated.
Currently the status is shown as zero changes or shown the changes before for instance Commit or minimize.
Update is scheduled immediately after running again.
- When refreshing
- After switching to a new repo
- Minimizing GE, then activating
- Open a modal dialog, like FormCommit
@mstv has asked about about status being incorrect, for instance when committing. 
The modal dialog ("lock the repo") could still keep GitStatusMonitor active, even if I believe I prefer this.
--
A slightly separate change that builds on the change above, could be separated
@pmiossec  asked about this
Run first update with locks
GitStatusMonitor normally do not try to lock the git-status, to not interfere with Commit.
However, a lock will speed up …
> GitStatusMonitor: Display when inactive

- GitUI/Avatars/InitialsAvatarGenerator.cs
- UnitTests/GitUI.Tests/Avatars/InitialsAvatarGeneratorTests.cs
Tune the author initials to handle middle names and additional info in the name and email addresses.
See test cases for details.
I initially wanted it to handle "Lastname Firstname" as "FL", but that is too hard to find out.
The French convention to use uppercase LASTNAME could be useful to detect lastnames...
Tests expanded and updated.
----
> Handle multi-part names for author initials

- GitCommands/Git/Executable.cs
- GitCommands/Git/ExternalOperationException.cs
- GitCommands/Git/UserExternalOperationException.cs
- GitExtensions/Program.cs
- GitUI/MessageBoxes.cs
- GitUI/NBugReports/BugReportForm.cs
- GitUI/NBugReports/BugReporter.cs
- GitUI/Script/ScriptRunner.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
- UnitTests/GitCommands.Tests/Git/ExecutableExtensionsTests.cs
Contributes to #7795
Trap and route as many exceptions as possible to the central handler.
For exceptions coming from the main thread it is possible to ignore those and continue the app's execution, but for unhandled exceptions coming from background threads the app will terminate.
The main focus of this work is to intercept exceptions originated from `Executable` (i.e. executing git commands, etc.), and user scripts. However it is not limited in this scope.
- An alternative simplified proposal for https://github.com/gitextensions/gitextensions/pull/8278.
* Settings
* Script
* An arbitrary exception (reported in https://github.com/gitextensions/gitextensions/issues/8367)
* An arbitrary exception (reported in https://github.com/gitextensions/gitextensions/issues/8647)
Hitting "ignore" will …
> Better exception presentation

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- contributors.txt
Fixes #8281 and possibly also fixes #3646 and fixes #8167
Exceptions thrown from TeamCityAdapter caused immediate retry of failing operations -> spawning lot of new threads without any delay.
These cases caused high CPU usage:
- incorrect (nonexistent) TC build ID
- network or TC server outage
CPU usage stays minimal. Build server is queried in defined time intervals even when responding errors or not communicating. 
Manually testing TeamCity integration and:
- simulating network/VPN outages
- set incorrect build ID
Other build server types could be affected and were not tested.
----
> Fix high CPU usage of TeamCityAdapter

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Editor/FileViewer.Designer.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
Current text when staging changes for specific lines is cherry picking and reverting for normal commits, for worktree (index) staging (unstaging) and resetting is used. The Git commands are slightly different but this is unknown for the user, the action is the same.
Especially, the hotkey must be the same. It is very confusing to identify the view as a "reset" or "revert" with separate hotkeys.
It is possible to have separate menu items with separate texts for e.g. reset/revert, but if the hotkey is to be the same, the hotkey handler must be identical so the action in the menu and hotkey will differ.
The names are currently chosen in analogy with cherry-picking/reverting commits, giving the "different name for the same action" for the line manipulation.
See also #7825 that updates the …
> FileViewer: Consistently use Stage/Reset  Lines

- GitCommands/Git/Executable.cs
- GitExtensions/Program.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/BrowseDialog/FormDonate.cs
- GitUI/CommandsDialogs/BrowseDialog/FormGoToCommit.cs
- GitUI/CommandsDialogs/BrowseDialog/FormUpdates.cs
- GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
- GitUI/CommandsDialogs/FormAbout.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormGitIgnore.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.cs
- GitUI/NBugReports/BugReportForm.cs
- GitUI/OsShellUtil.cs
- GitUI/Script/ScriptRunner.cs
- GitUI/UserControls/AvatarControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IExecutable.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
Contributes to #7795, extracted from #8278
- Use class `Executable` for `OsShellUtil` implementation
- Use `OsShellUtil` functions instead of plain `Process.Start` where applicable
- manual
- Build cca84cd8551e5be614bf215bd77d93664b69ece6
----
> Process.Start with ExternalOperationException

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommandlineHelp.resx
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/GitUICommands.cs
- GitUI/HelperDialogs/FormChooseCommit.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
Related to discussions in #8700 how to handle diffs for submodules
GE has a decent overview of changes in a submodule, but sometimes I want to see the actual changes in files or more than first/selected commit message. A git-diff --dir-diff will not work with all difftools, not show working dir (unstaged) changes and no intermediate commit messages.
The best difftool is GE itself, when a subrepo is currently opened only the selected commit is selected though. It can be difficult to find the first submodule commit. In the screenshot it was at least the same page, harder if there are more changes.
Open submodule in e9eff4bb646ccd355f221c81cbf98e1eeab5a3b4 (or doubleclick).
If the WorkTree was browsed (Commit, RevDiff, side panel later), OldCommit->Worktree would be displayed instead after …
>  Submodule browse: Select both first/second commits

- GitCommands/Git/FileDeleteException.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/NBugReports/BugReporter.cs
- GitUI/NBugReports/UserExternalOperationException.cs
- GitUI/Script/ScriptRunner.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
Relates to #8358
- Move user-facing exceptions to UI layer because these exceptions include localisable strings, that are only available at the UI layer.
- Handle non-app related I/O exceptions that a user can resolve
NOTE: the current implementation of Task Dialog can't size itself to content, the .NET 5.0 version provided by Windows Forms SDK can.
Manually by:
- creating an index.lock file,
- locking the file (e.g. open in MS Excel)
- invoke the functionality through _Repository > Git Maintenance > Delete index.lock_
----
> Handle external I/O exceptions that user can fix

- GitCommands/PathUtil.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
Regression: https://github.com/gitextensions/gitextensions/pull/8690#issuecomment-756021266
Correct annotation for PathUtil.TryFindFullPath(), revert change to evaluate path in #8690
The mergetool path was always set to empty so the Git mergetool handling was used (not the GE special implementation to check results etc).
manual
----
> ResolveConflicts: Incorrect evaluation of mergetool path

- GitCommands/Git/Executable.cs
Fixes https://github.com/gitextensions/gitextensions/pull/8721#discussion_r552306228
- Use verb "open" in case of UseShellExecute in preparation for .NET Core
- manual
- Build 20514e62f05b7b334fe2db2ee2720ca83297561c
----
> Verb "open" for ShellExecute

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
Submodule nodes have a different base class, and if a submodule
tree node is selected while the tree is refreshed, the app would
crash with an `InvalidCastException`
```
System.InvalidCastException: Unable to cast object of type 'SubmoduleNode' to type 'BaseBranchNode'.
at void GitUI.BranchTreePanel.RepoObjectsTree+Tree.FillTreeViewNode(string originalSelectedNodeFullNamePath, bool firstTime)
at async Task GitUI.BranchTreePanel.RepoObjectsTree+Tree.ReloadNodesAsync(Func<CancellationToken, Task<Nodes>> loadNodesTask)
at void GitUI.BranchTreePanel.RepoObjectsTree+SubmoduleTree+<>c__DisplayClass4_0+<<OnStatusUpdated>b__0>d.MoveNext()
at void GitUI.ThreadHelper+<>c__DisplayClass13_0+<<FileAndForget>b__0>d.MoveNext()
```
Resolves #8658
---- …
> fix crash on refresh when submodule nodes selected

- GitUI/CommandsDialogs/FormBrowseController.cs
- GitUI/CommandsDialogs/FormMergeSubmodule.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/GitUICommands.cs
- GitUI/UserControls/FileStatusList.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
Contributes to #7795
Fixes https://github.com/gitextensions/gitextensions/pull/8726#discussion_r554511688
- Factor out `GitUICommands.Spawn` and `GitUICommands.SpawnBrowse` using `Executable` in order to throw `ExternalOperationException` on failure.
N/A
- manual
- Build a5acbea9e7a67ce50156e1e4ff38f6b5d002e6e8
----
> Use Executable for launching new GE instances

- GitUI/Editor/FileViewer.cs
Fixes #8752
- `FileViewer`: Return inapplicable hotkeys as unhandled
- 
- manual
- Build 51e102316a622b2e372a7323bd9f9f59bb0e2b00
----
> FileViewer: Return inapplicable hotkeys as unhandled

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/InteractiveGitActionControl.cs
It is possible for a repo to be in a middle of a bisect operation and be in a conflicted state. Hence detect bisect separately from the rest of git actions.
- manual
----
> Show both bisect and git operation notifications

- GitUI/Translation/English.xlf
- ResourceManager/Xliff/TranslationBody.cs
Fixes #8755
- Fixup the check in `AddTranslationItemIfNotExist` whether the `ToolTipText` differs from `Text`
- Update `English.xlf`
- `build -loc`
- check `English.xlf`
- Build f0a3df68a26e5521ea7e879c01e35706eae58ba6
----
> Translate ToolTips

- GitUI/CommandsDialogs/FormCommit.cs
If there are both stages and unstaged files the commit dialog fails to select the first unstaged file, thus showing no diff. If there are only unstaged or staged files everything works as expected.
When the form opens it expects "Commit" button to have focus (i.e. be an active control), however it is not happening, and the active control remains null.
This appears as a regression form 3.4.3, but I was unable to see any changes that could lead to this bug. I haven't bisected due to limited available time.
Treat "no active control" the same way as "active control == Commit" to force the selection.
- manual
----
> fix: Select diff when there are staged and unstaged files

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusList.cs
FollowUp on PR #8731
After implementing a minor improvement on FormCommit regarding StageAll and UnstageAll ToolStripButtons when the file-filter is active (PR #8731 / Issue #8596) @gerhardol highlighted 2 potential improvements in his review.
As the original PR has been already merged, I've opened this one.
Reason: Maintainablity
* remove status variable _filterActive (as Gerhard mentioned: someone else may reuse the status variable for a slightly separate use case or add a parallel variable)
Thus, FilterChanged will now fire on every character added/removed (instead of only when activated+deactivated) but this won't cause any issue.
* Unset tool(Un)StageAllItem.Text : to avoid unecessary double translation text as this (in fact ToolTipText) is intialized anyway (in the constructor).
N/A …
> Review feedback on PR #8731 (StageAll,UnstageAll)

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormBrowse.resx
- GitUI/Translation/English.xlf
Due to discovered layout and placement instability of toolbars
reverting most of the functionality added in #8572.
Closes #8680
----
> Revert ability for move and show/hide toolbars

- GitCommands/FullPathResolver.cs
- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitRefName.cs
- GitCommands/PathUtil.cs
- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitCommands/Settings/RepoDistSettings.cs
- GitCommands/StringExtensions.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitCommands/UserRepositoryHistory/RepositoryDescriptionProvider.cs
- GitExtUtils/ArgumentBuilder.cs
- GitExtUtils/FileUtility.cs
- GitExtUtils/GitArgumentBuilder.cs
- GitExtUtils/GitUI/ControlHotkeyExtensions.cs
- GitExtUtils/GitUI/ControlUtil.cs
- GitExtUtils/GitUI/ListViewExtensions.cs
- GitExtUtils/GitUI/Theming/AppColor.cs
- GitExtUtils/GitUI/Theming/ColorHelper.cs
- GitExtUtils/GitUI/Theming/HslColor.cs
- GitExtUtils/GitUI/Theming/Theme.cs
- GitExtUtils/GitUI/Win32ApiUtil.cs
While making recent changes for nullable reference types (#8771, #8776) SA1629 started appearing in the error list.
Just adding some punctuation. Nothing exciting here.
> Fix SA1629 Documentation text should end with a period

- GitExtUtils/GitUI/ControlUtil.cs
Reading through the code I noticed that the `skip` parameter was unused. It should be passed to its overload.
> Pass 'skip' parameter

- GitUI/GitUI.csproj
- UnitTests/GitCommands.Tests/GitCommands.Tests.csproj
- UnitTests/Plugins/GitUIPluginInterfaces.Tests/GitUIPluginInterfaces.Tests.csproj
When `CopyToOutputDirectory` has value `Always`, Visual Studio must build the project every time, which can trigger further builds. 
By changing these values to `PreserveNewest`, several project builds can be avoided, resulting in an improved inner dev loop.
To verify this, turn on minimal "up-to-date check" logging here:
> Improve build times

- GitCommands/Git/GitBranchNameNormaliser.cs
- GitCommands/Git/GitItemStatus.cs
- GitCommands/Git/GitModule.cs
- GitCommands/StringPool.cs
- GitCommands/Utils/WeakRefCache.cs
- GitExtUtils/GitUI/Theming/Theme.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceFontsSettingsPage.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUICommands.cs
- GitUI/Interops/UxTheme/SetWindowTheme.cs
- GitUI/MouseWheelRedirector.cs
- GitUI/Script/ScriptRunner.cs
- GitUI/Script/SplitButton.cs
- GitUI/SpellChecker/EditNetSpell.cs
- GitUI/UserControls/InteractiveGitActionControl.cs
- GitUI/UserControls/NativeTreeViewDoubleClickDecorator.cs
- GitUI/UserControls/NativeTreeViewExplorerNavigationDecorator.cs
- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- Plugins/Statistics/GitStatistics/PieChart/EdgeColor.cs
- Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs
- Plugins/Statistics/GitStatistics/PieChart/PieSlice.cs
- ResourceManager/GitExtensionsControl.cs
- Solution.Versions.props
- UnitTests/GitCommands.Tests/Git/GitBranchNameNormaliserTest.cs
Fixes #8728
Separated from #8734 (based on this)
Enable C#9 'syntactic sugar' for pattern matching.
Mostly changed with intellicode suggestions and a few manual changes.
Separated from #8734 to merge that quickly and discuss the changes here.
I would like to apply the changes in FileViewer.cs at least.
Maybe StyleCop changes are required toadd parenthesis to improve readability to merge this.
manual
----
> C#9 pattern enhancements

- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitCommands/Submodules/DetailedSubmoduleInfo.cs
- GitCommands/Submodules/SubmoduleInfoResult.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUICommands.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/ArtificialCommitChangeCount.cs
- GitUI/UserControls/RevisionGrid/ChangeCount.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IBrowseRepo.cs
- ResourceManager/LocalizationHelpers.cs
Closes #8714 
Second part of #8703
Based on #8703 that is set to automerge so not to be merged yet. Fully reviewable.
Best reviewed commit by commit
* Open submodule in left panel selects first/selected commit as in #8703
* Add actions in Commit/RevDiff worktree to submodules: Reset/Stash/Commit
* Add Open in new instance for submodules
* Tooltip with details for changed submodules. This adds extra git-diff for modules that are dirty only (for others the command were executed anyway). The number of changes reported are limited to five changes (similar to how the RevGrid tooltip is limited already)
* For topmodule there is no submodule status message available, display the same tooltip as for the RevGrid WorkTree commit.
* A few minor refactorings were required
Review commit by commit. …
> Sidepanel submodule improvements

- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- Add mnemonics to the RevisionGrid's context menu in order to speed-up the selection of the menu items
<kbd>Right Click</kbd>+<kbd>letter</kbd>! (of course also with the dedicated context menu key or <kbd>Shift</kbd>+<kbd>F10</kbd>)
Before | After
-|-
- manual
- Build 5a43ed39e3ec1bbe8184e81458c8691e3a7d3446
----
> Add mnemonics to RevisionGrid context menu

- GitUI/GitExtensionsForm.cs
- UnitTests/CommonTestUtils/ITestAccessor.cs
- UnitTests/CommonTestUtils/TestAccessor.cs
- UnitTests/CommonTestUtils/TestAccessors.cs
- UnitTests/GitUI.Tests/GitExtensionsFormTests.cs
Rework the test accessor pattern introduced by @sharwell, that requires creating an internal struct that exposes non-public API to tests, with a test accessor pattern used in dotent/winforms, that doesn't require additional changes to the production code. See https://github.com/dotnet/winforms/pull/3225
Added two examples of how a testaccessor can be used:
1. for a small number of tests using `Dynamic` object is totally ok,
2. when a number of tests become significant it is worth considering creating a specifc testaccessor type that provides a strongly typed facede.
Can be squash-merged.
> Add test accessors borrowed from https://github.com/dotnet/winforms/

- GitUI/GitExtensionsForm.cs
- GitUI/WindowPositionManager.cs
- UnitTests/GitUI.Tests/GitExtensionsFormTests.cs
- UnitTests/GitUI.Tests/WindowPositionManagerTests.cs
If a parent window is at a corner of a desktop, and it is smaller than a child window, it is possible to end up in a situation where the child window is positioned outside of visible and reachable area.
Coupled with the fact that locations and dimensions of most windows get persisted this may lead to a situation where the window may become permanently inaccessible until the settings are reset.
- Constrain the window to be within the desktop bounds
Steps to replicate:
1. Open the app at the top left corner of the desktop
2. Resize it to be smaller than a typical "Setting" dialog windows size
3. Open "Settings" dialog
4. Observe the dialog opened at negative coordinates, something like:
- Manual
❗ **NB:** I have a single monitor and unable to test multi-monitor setup, where a secondary …
> Constrain child windows to monitor bounds

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/GitUICommands.cs
- GitUI/HelperDialogs/FormProcess.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
In multi monitor scenarios, where the main form is on a 2ndary monitor, checking out a branch without showing the checkout dialog could lead to situations where the checkout progress dialog would be shown on the primary screen.
This was caused by setting the progress dialog's owner to `null`.
Ensure the correct owner is passed to the progress dialog in the checkout branch sequence.
Also correct various callsites in the revision grid and the left panel to pass the form as the owner instead of respective controls.
----
> Correct ownership of progress dialogs

- GitUI/Editor/FileViewer.cs
If an image cannot be viewed, an error message is shown but nothing of the file itself.
The user has has therefore no possibility to find the core problem.
If the file cannot be shown , this could be due to that the information the user has put in Git is corrupt, that the GE implementation cannot handle this type of image (like the GE hardcoded extension is used for another file) or that the image is stored with LFS. For LFS, GE (and most tools and web interfaces, but shown in GitHub) does not fetch the actual file but tries to display the LFS text as an image which obviously will fail. #6189 is WIP and has been that for some time....
Both GE not handling images and LFS will likely affect all "images"  in a certain repo and most users will not understand why.
This PR will therefore …
> ImageView: View failures as dump

- GitUI/CommandsDialogs/CommitDialog/FormCommitTemplateSettings.cs
- Increase to 10 the number of commit templates and migrate the existing ones when increasing the size
Reason behind the change:
- Because only the not empty lines are displayed in the menu, there is no drawback to allow more commit templates
- I need more lines 😉 (so perhaps someone else also...)
I can't produce it anymore (but there are only 5 lines 😉  )
- Manual 
- Build 0ccc7fcedb2b3dab976368382a58fb43db18da78
----
> Increase the number of commit templates

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
The designer keeps on wrecking havoc with toolbars - i.e. the order appears to be semi random and not [expected](https://github.com/gitextensions/gitextensions/pull/8719#discussion_r559495096). 
Revisit the toolbar layout workaround, and add assertions to validate the outcome.
Related #8719
----
> Fix toolbar order (revisited)

- GitCommands/Git/GitItem.cs
- GitCommands/Git/GitModule.cs
- GitCommands/GitRevisionInfoProvider.cs
- GitUI/CommandsDialogs/RevisionFileTreeController.cs
- Plugins/GitUIPluginInterfaces/IGitItem.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- Plugins/GitUIPluginInterfaces/IGitRef.cs
- UnitTests/GitCommands.Tests/GitRevisionInfoProviderTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionFileTreeControllerTests.cs
This comes ahead of work to null-annotate these APIs. Not all implementations will populate this property, so in the old factoring it should be marked as nullable. However the Name property is used in many places where it is assumed non-null.
This factoring splits out those usages behind a new interface, making it easier to correctly annotate these APIs.
- It compiles
----
> Introduce new interface for named git refs

- GitCommands/RevisionReader.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #8800
Manually
Windows 10
----
> Fix filter by branch with globbing characters *?[]

- GitExtensions/app.config
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.Designer.cs
- GitUI/Translation/English.xlf
- contributors.txt
1. Update app.config to pick up some .NET Framework accessibility fixes up to 4.8, depending on what version of .NET Framework is available on the device at runtime.
2. Add unique accessible names for the Browse and Suggest buttons to avoid duplicate names being exposed programmatically on sibling buttons. (If the UI is ever localized, the accessible names must be localized too.)
3. Change the order in which controls are added to their containers, in order to have the programmatic order (as exposed through the UI Automation API) of the controls match their logical order.
4. Remove the TabIndex property being set on the controls, because that interferes with WinForms setting accessible names on TextBox and ComboBox controls based on the text from the Labels that programmatically precedes …
> A variety of accessibility-related fixes for the contents of the main pane on the Config page 

- GitUI/GitUICommands.cs
- Plugins/GitUIPluginInterfaces/IGitUICommands.cs
- Expose `IGitUICommands.StartRemotesDialog` again (https://github.com/gitextensions/GitExtensions.GerritPlugin/pull/16#discussion_r570168180)
including all arguments (`owner` window is a must, the other two with default value `null` should not hurt)
N/A
- run existing tests
- Build 7c1f1bb77ed149b369d09423143b5bea5545b445
----
> Restore/expose IGitUICommands.StartRemotesDialog

- GitUI/CommandsDialogs/FormBrowse.cs
#8557 introduced new margins and borders, however those margins and borders are not correctly calculated in scaled environments, i.e. scale factor >100%.
@ivangrek in #8732 has provided probably a more "correct" fix, however this is a smaller and more targeted fix.
Resolves #8698
Closes #8732
- manual
----
> Correct padding increase

- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
by using a relative path "." instead...
This is possible because the Working directory of the command run
is the repository folder
Fixes #8822
- Manual
- Build f0e6f1b5aad2d765050c319931422057eab29f38
> Reset Another branch: prevent special characters in path to fail command

- GitCommands/FileInfoExtensions.cs
- GitUI/CommandsDialogs/BrowseDialog/FormBrowseUtil.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
Will avoid exceptions for illegal characters etc
Fixes #8839
Use File.Exists(path) before FileInfo(path) to avoid exceptions.
Can be seen as a follow up to #8575 
review
----
> Check if path exists before creating FileInfo

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
Fixes #8829
Jenkins was not requeried since a1fb6669dc20b10d6b65fffebeea9b532e60be5a
This does not seem to be a problem for other buildservers,
AppVeyor requires a manual refresh anyway.
This is not an issue if the build starts immediately after a push, but there could be a queue to start the build, then refresh is needed.
* Create a new commit, refresh grid but do not push it
* push the commit from command line
* check that the build status is updated
----
> Jenkins: requery new running jobs

- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/AppVeyorAdapterTests.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_master_build.approved.txt
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.approved.txt
Fixes #8828 
v2 tokens require that the account is prepended to the request..
This apparently is only required for quering repos for an account,
not normal info.
* Only query for project names for a configured account if no
account/repo at all is specified
Illegal repos will not report any builds anyway.
This allows a AppVeyor username/token at the same time as multiple
repos are used. For instance can gitextensions/gitextensions builds
be seen at the same time as user private builds
* Allow configuring of  account/repo also if accountName is set
* Less aggressive requery of running AppVeyor jobs
* Refactor
* remove static variables/functions
* Handle projectId (and name) as account/repo consistently
* Use local functions (and inline code)
* Remove internal data class Project (the module …
> AppVeyor: Handle v2 tokens

- GitUI/BuildServerIntegration/BuildServerWatcher.cs
#8833 for 3.5
Jenkins was not requeried since a1fb6669dc20b10d6b65fffebeea9b532e60be5a
This does not seem to be a problem for other buildservers,
AppVeyor requires a manual refresh anyway.
----
> 3.5 Jenkins: requery new running jobs

- GitCommands/CustomDiffMergeTool.cs
- GitCommands/CustomDiffMergeToolCache.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormFileHistory.Designer.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DiffViewerSettingsPage.cs
- GitUI/CustomDiffMergeToolProvider.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- ResourceManager/Strings.cs
- UnitTests/GitCommands.Tests/CustomDiffMergeToolCacheTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Followup to #8194 (and #8660)
Make all configured difftools available in more situations
The default behavior is not changed, it is still possible to click the
dropdown "parent" item to enable the functionality.
The dropdown is not shown by default for entries existing in GE3.4 to not
confuse users and to show the shortcut (that is hidden when a dropdown
is enabled).
The dropdown is toggled with a rightclick.
A tooltip is added to enable discovery.
Note that for FormFileHistory the F3 shortcut is disabled as the
shortcut is not handled as a hotkey and a dropdown disables the shortcut.
Show the default tool first and checked in the dropdown.
This is also changed for FormResolveConflicts.
Remove the separate custom difftool menu in RevDiff.
Some notes
* ~~Submodule diff for Commit Unstaged …
> Custom difftool in RevDiff, FileHistory, Commit, RevGrid

- Plugins/BuildServerIntegration/AppVeyorIntegration/AppVeyorAdapter.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/AppVeyorAdapterTests.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_master_build.approved.txt
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/ApprovedFiles/AppVeyorAdapterTests.Should_return_a_build_Info_When_Json_content_is_the_one_of_a_pull_request_build.approved.txt
#8830 for 3.5
This is not a blocker, but something that should be included.
v2 tokens require that the account is prepended to the request..
This apparently is only required for quering repos for an account,
not normal info.
* Only query for project names for a configured account if no
account/repo at all is specified
Illegal repos will not report any builds anyway.
This allows a AppVeyor username/token at the same time as multiple
repos are used. For instance can gitextensions/gitextensions builds
be seen at the same time as user private builds
* Allow configuring of  account/repo also if accountName is set
* Less aggressive requery of running AppVeyor jobs
* Refactor
* remove static variables/functions
* Handle projectId/name as account/repo consistently
* Use local functions (and …
> 3.5 AppVeyor: Handle v2 tokens

- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- contributors.txt
With the existing behavior, you still see long-deleted branches after
closing the dialog until you either refresh the repo manually, or invoke
the notifier in some other location (e.g. through committing).
- Update the whole repository after obsolete branches were deleted
Deleting any branch through the "Delete obsolete branches" dialog will only update the revision grid, i.e. remove the branch label from the corresponding commits. The branch/remotes/submodules panel on the left side will continue to show outdated branches, double-clicking on them simply shows an error "No revision found".
The branch/remotes/submodules panel is refreshed after you hit "Delete" within the dialog.
- Manual Testing
- GIT 2.24.0.windows.2
- Windows 10 Version 2004
----
:black_nib: I contribute this code under …
> Notify of repo changes when unused branches were deleted

- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Remains from #8851
- Browse: Avoid extra git-rev-parse at start
There are two calls to `git ls-files -z --unmerged` due to OnActivate()  called from both OnActivated() and InternalInitialize().
This is hard to get around as OnActivated() is needed when the form is activated (from backround, modal window closed)
and InternalInitialize is needed after the module is loaded.
Refactorings:
* GitUIExtensions: GetItemPatch to local function
* Remove Async suffix for GetCurrentSubmoduleChangesAsync
See #8851, two calls to `git rev-parse HEAD` quite early.
manual
----
> Browse: Avoid extra git-rev-parse at start

- GitUI/CommandsDialogs/FormBrowse.cs
`FormBrowse` is the main form, and hence it doesn't have `Owner` set. This leads to `FormUpdates` being created as an orphan modal form, that can be hidden behind `FormBrowse` and making the app look unresponsive.
Correct the ownership and, thus, force the new form to show above the main form.
- manual
----
> Fix ownership of FormUpdates

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
Fixes #
Apply theme to dashboard links.
theme is null when applying the link theme. No exception, but no effect.
This could be considered for 3.5 too.
An alternative to applying the theme is to remove the theme handling here.
Manual
----
> Link style was not applied to the dashboard

- GitUI/Theming/Renderers/ListViewRenderer.cs
Fixes #8863
- Windows10
- 96 dpi
----
> fix ListView column border in dark theme

- GitCommands/CommitDataManager.cs
- GitCommands/Git/CommandCache.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitUI/Editor/FileViewer.cs
- ResourceManager/LocalizationHelpers.cs
Part of #8862 
* Cache Git commands related to submodules
Cache commands with sha input and no variable input like Git Notes
Only fetch Git Notes for commands that are not cached (Notes are not displayed in Submodule scenarios anyway).
* Cache GetCommitRangeDiffCount
Used when selecting multiple commits in RevDiff
*  Increase Git command cache to 50
Not strictly needed, 40 is OK also for my use after this, but it seems like a reasonable change.
Example with one submodule changed, on a relative fast PC (Git at work is 5 times slower).
Startup followed by refresh (similar to build), marked with red line.
Commands that are cached are marked with green (so cache have effect already at first display).
Note: The refresh was done a little early, a diff command will normally be required also …
> Cache Git commands related to submodules

- GitUI/GitUIExtensions.cs
The previous code would call `GetSubmoduleStatusAsync` twice, only using the second call's result.
As the returned task is never null, this check is redundant and does redundant work.
Checking the task's result occurs below.
----
> Remove double execution of GetSubmoduleStatusAsync

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
Removes a redundant null check.
All callers pass a non-null delegate. This code is now annotated, so future code will not pass null either.
----
> Remove redundant null check

- GitCommands/CommitDataManager.cs
- GitCommands/Git/CommandCache.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitUI/Editor/FileViewer.cs
- ResourceManager/LocalizationHelpers.cs
> Cache Git commands related to submodules-3.5

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
This change removes 427,688 bytes of closure allocations while loading GE with the gitextensions repo.
Passing the argument on the stack allows the delegate to be cached by the compiler, rather than allocating a new instance for each call.
----
> Eliminate closure allocations

- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
Part of #8862
This PR handles the side panel for submodules being updated too often.
The PR has three parts that could be separated, but the discussion is easier if the combined result is presented.
Similarily, the results should be seen together with #8866 as that also improves the handling. That also reduces clutter to show what this PR really changes.
1. GitStatus updates were handled every 5th second
Regression in master after 3.4
The git-status updates are limited to at most every 5th second (or longer if git-status is really slow).
Submodule updates are limited even more, to every 15th second.
In 3.4 the extra updates were just thrown away.
In 3.5 some code to not require tests to wait these extra 15s were incorrect and updated the sidepanel too.
So the sidepanel as well as the menu …
> Submodule SidePanel updated too often

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Port of #8888 for `release/3.5`.
This change removes 537,404 bytes of boxed enum allocations while loading GE with the gitextensions repo.
> [3.5] Eliminate boxing allocation

- UnitTests/GitUI.Tests/Theming/AppColorDefaultsTests.cs
The colors from `AppColorDefaults` should match those defined in invariant.css.
Turns out I somehow forgot to add a test to ensure this, which I realized while reviewing #8900 
`AppColorDefaults` class is obsolete, the only actual usage is `src\GitUI\Theming\ThemeMigration.cs : 37`
----
> Test to force same colors in AppColorDefaults and invariant.css

- .gitmodules
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/GitExtensionsDialog.cs
- GitUI/UserManual/StandardHtmlUserManual.cs
- README.md
- UnitTests/GitCommands.Tests/TestData/README.blame
- UnitTests/GitUI.Tests/UserManual/StandardHtmlUserManualFixture.cs
- scripts/set_version_to.py
Requests are directed to / anyway
Remove GitExtensionsDoc subrepo as it is not used in builds anyway.
Remove release script update of the subrepo, this must be handled manually since
signed builds must run in AppVeyor.
(cherry picked from commit c59fd847fc6c1879ead730b7da01104ac40d74e1)
#8838 for 3.5
> Remove /en/latest from Doc links 3.5

- GitCommands/Git/GitItemStatus.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/FileStatusList.cs
Fixes @gerhardol's comments on #8875
Refactoring during annotation identified a potential issue here, but the change was not correct. This change allows the task itself to be null (an uncommon pattern) which indicates that `SetSubmoduleStatus` has not been called.
To trigger the broken behaviour:
1. Open the GE repo
2. Select the "File Tree" tab
3. Select a submodule in the tree
4. Press H to open the history
----
> Fix submodule status loading error

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
This change removes 537,404 bytes of boxed enum allocations while loading GE with the gitextensions repo.
----
> Eliminate boxing allocation

- GitExtUtils/GitUI/ControlDpiExtensions.cs
- GitExtUtils/GitUI/Theming/OtherColors.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommitInfo/CommitInfo.Designer.cs
Follows to: https://github.com/gitextensions/gitextensions/pull/8849#issuecomment-783295170.
- Add darkening to the background for a softer color combination.
- Remove paddings for message block in CommitInfo panel to align text.
- Tone down the borders.
- Manually
- Visually
- Build 96278326503d1bb87ac6f58a3881e0de027ae298 (Dirty)
----
> Add UI improvements

- GitExtUtils/GitUI/Theming/IThemeSerializationData.cs
- GitExtUtils/GitUI/Theming/IThemeSerializationFields.cs
- GitExtUtils/GitUI/Theming/Theme.cs
- GitUI/Theming/ThemeModule.cs
- GitUI/Theming/ThemePersistence.cs
Hide theme data properties from its public interface, since they don't provide a behavior one would naturally expect from a public property with a given name.
The only intended usage for these properties is serialization.
#8904 discovered a problem which this PR would have prevented.
----
> Hide theme fields for serialization from public interface

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
https://github.com/gitextensions/gitextensions/pull/8886#issuecomment-786868520
Whenever files are manipulated in RevDiff, request GitStatusMonitor refresh
- If the change was just worktree <-> index, git-status is not triggered at all (until next file system change or every fifth minute)
- If the change is throttled (#8886 increases the minimal time for updates to 30 s), an interactive request is done (delayed 200 ms to possibly bundle changes)
I considered to request the update only at (likely) worktree <-> index changes, but that got more complicated and a faster update is desired after manual changes.
If you stage files one by one, if may cause git-status to run more or less continously (where Git is slow). I do not believe this is a problem, but the request could be done with some …
> RevDiff: Request GitStatus updates at file manipulations

- GitCommands/Config/ConfigSection.cs
- GitCommands/CustomDiffMergeTool.cs
- GitCommands/CustomDiffMergeToolCache.cs
- GitCommands/UserRepositoryHistory/RecentRepoInfo.cs
- GitExtUtils/GitUI/Theming/BmpTransformation.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Remotes.cs
- GitUI/CommandsDialogs/FormBlame.cs
- GitUI/CommandsDialogs/FormRevertCommit.cs
- GitUI/CommandsDialogs/SettingsDialog/GroupSettingsPage.cs
- GitUI/HelperDialogs/FormProcess.cs
- GitUI/HelperDialogs/FormResetCurrentBranch.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
- GitUI/WindowsThumbnailToolbarButton.cs
- Plugins/FindLargeFiles/GitObject.cs
- Plugins/GitUIPluginInterfaces/IGitRemoteCommand.cs
- Plugins/GitUIPluginInterfaces/Settings/BoolSetting.cs
- Plugins/GitUIPluginInterfaces/Settings/ChoiceSetting.cs
- Plugins/GitUIPluginInterfaces/Settings/NumberSetting.cs
- Plugins/GitUIPluginInterfaces/Settings/PasswordSetting.cs
- Plugins/GitUIPluginInterfaces/Settings/StringSetting.cs
- Plugins/Statistics/GitStatistics/PieChart/PieChart3D.cs
- ResourceManager/CommandEventArgs.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/GitUI.Tests/BranchTreePanel/GitRefMenuItemsTest.cs
Remove redundant property setters. Read only properties have the stronger guarantee that their value will not change over time, making reasoning about the containing type's behaviour easier.
- Manual review. Couldn't find any late binding to these properties. CI will run tests.
----
> Remove redundant property setters

- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Remove unused field from `RevisionDiffController`. This class is stateless. Update consuming code too.
- It compiles. CI will run tests.
----
> Remove unused field from RevisionDiffController

- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- Set the initial focus of `FormResetAnotherBranch` to the (dropped down) ComboBox `Branches`
- manual
- Build 87a45ff005cff65b736453d96a00d9250536ac85
----
> Focus ComboBox Branches of FormResetAnotherBranch

- GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
- Prevent exception when running unit tests when the entry assembly is null. This can make debugging smoother.
- Manual testing.
----
> Prevent exception when running unit tests

- GitCommands/Git/Executable.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- Plugins/GitUIPluginInterfaces/IExecutable.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
- UnitTests/GitCommands.Tests/Git/Gpg/GitGpgControllerTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormAddSubmoduleTests.cs
- Remove `IExecutable.GetOutput`. This method simply delegated to an extension method anyway. It is not needed on the interface.
- It compiles. Letting CI run the tests as it takes forever on my machine.
---
> Remove IExecutable.GetOutput

- GitExtensions.sln.DotSettings
- Fix invalid XML in DotSettings file. A consequence of this fix is that the spell checker no longer flags terms we previously added here as incorrect.
- None.
----
> Fix invalid XML in DotSettings file

- GitCommands/Git/GitItemStatus.cs
Eliminate boxing when in `GitItemStatus` bool property getters.
`Enum.HasFlag` boxes its argument. Replace it with a method that does not.
----
> Avoid boxing while unpacking flags

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
Fixes #8873
- "Expand all" and "Collapse all" now has an effect only on selected node (collapse all tree could still be made through menu icon)
- Manual
- Build 873e9ed043f1d89064bae1bd4126c099c6da5410
- .NET Framework 4.8.4311.0
> Left panel: Make "Expand all" and "Collapse all" based on selected node

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
Fixes #8871
Increase the time between git-status runs from 5s to 30s
So for instance when building, git-status runs every 30s
If there has been no changes and git-status has not run in 30s,
git-status will run in about one second as now
This affects:
* Commit button count
* artificial commit summary and tooltip
* left panel status and tooltips (added in 3.5)
* submodule menu drop down
The use case with most impact as I see it is if you save one file in the editor (git-status is triggered quickly), then you select another file in the editor already edited and save that, then the status will be updated in about 30s instead of about 5s.
manual
----
> GitStatusMonitor increase minimum time between updates

- scripts/tools/NUnit/NUnit.targets
Submitting test coverage to CodeCov adds extra time to CI builds, it can be sometimes flaky, and it doesn't appear to be adding a great deal of value (At least currently).
> Disable CodeCov integration

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
#8894 for 3.5
For (most) operations related to changes of worktree or index status
in Browse, request immediate git-status update, for the commit count
and artificial commit.
This will bypass the delay between updates. Also changes worktree<->index
would not trigger updates.
Note that operations to submodules in the sidepanel still requires file
system changes.
Should be merged if #8886 is merged in 3.5
----
> RevDiff: Request GitStatus updates at file manipulations 3.5

- GitCommands/AsyncLoader.cs
- GitUI/CommandsDialogs/FormAddToGitIgnore.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/CommandsDialogs/SearchControl.cs
- GitUI/Editor/FileViewer.cs
Stop AsyncLoader passing null on cancellation. This strange pattern was identified during recent annotation work. It isn't particularly useful to be called back with a default value when the original load action was cancelled.
- Manual testing.
----
> Stop AsyncLoader passing null on cancellation

- GitCommands/AsyncLoader.cs
Further builds on #8938.
Remove return value from `AsyncLoader`. There were no usages of this value. Also, the value can be confusing in cases where cancellation occurs, as it's unclear whether a default value was returned successfully, or if the operation was cancelled. Consumption of any produced value should occur in the `onLoaded` callback.
- Compilation. CI will run unit tests.
----
> Remove return value from AsyncLoader

- GitCommands/Git/GitModule.cs
Fixes #8054
This PR has two purposes:
* Get the output in RevDiff panel to be the same as in the tool tip and in FormCommit (see #8054 for details, not much discussed here)
* Avoid unnecessary git-diff command for artificial commits
git-status is required to see new files, but git-diff was used to get other files. When selecting worktree or index only, the git-diff command is not needed, all info is in git-status. 
(Longer explanation: same as HEAD->Index and Index->Worktree, any other combination involving artificial diffs will require git-diff too.)
The git-diff can be considerably slower if viruses like Symantec are installed, delays showing the actual diff.
Note that git-status normally is slower than git-diff.
Change just line endings for a file, for instance like:
`perl -pi -e …
> RevDiff: Show worktree/index changes similar to FormCommit

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
Candidate for 3.5
* range-diff: Incorrect limit when selecting four commits
Git diff-range can be used to show the difference in 'slices' of branches.
This is advanced usage, my normal usage is just to select two heads.
But if you select baseA, A, baseB, B then range-diff shows the difference between the commits,
(see example after, just with one commit in each 'slice').
This is helpful in comparing a patchset in two separate branches (master and release for instance).
range-diff can be slow with many commits and is limited to 100 commit differences.
This calculation was incorrect and did not count the differences but the union for the "base" and the "head" why the command was normally refused.
With this, also a routine in GitModule could be removed.
* FileStatusList: avoid getRevision() …
> range-diff: Incorrect limit when selecting four commits

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- Always restore the clip region and the `SmoothingMode`
- Remove return value which is always `true`
- Reduce `if` nesting
- Replace `var`
N/A
- review, manual and existing tests
- Build 11f8f3ec566658edbf1a41d166bc7a4144024f1c
----
> Refactor PaintGraphCell

- GitCommands/Submodules/SubmoduleStatusEventArgs.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #8871
Related to #8886
The submodules in the sidepanel are recreated every time git-status is updated.
Before #8867, that occurred every 5th second. A gif show the behavior there.
#8867 restores the behavior to 3.4 and refreshing every 15th second.
#8886 proposes increasing the time further to 30 seconds.
This PR only recreate the submodule structure when there are structure changes.
No screenshot - but not much to see.
Manual
- Build 10df80cb1fe2ff8c07a30be3525635161f04c42c
----
> Sidepanel submodule: Recreate tree only at structure changes

- GitCommands/Submodules/SubmoduleStatusEventArgs.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/CommandsDialogs/FormBrowse.cs
#8902 for 3.5
Some null annotations dropped, no functional change
> Submodule: Recreate tree only at structure changes 3.5

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/Translation/English.xlf
Fixes "One or two comment asking for this feature but that I can't find anymore..."
Follow up of #8572
- Being able to choose the buttons in the browse form toolbar
- Preventing the closing of the menu to easily unselect multiple items
Gif (with not updated with last separator handling. See screenshot above)
- Manual
- Build 132668ee18374ce1ddccb8640e717ae8b70087a3 (Dirty)
- .NET Framework 4.8.4311.0
> FormBrowse Toolbar: Being able to hide each control separately

- Plugins/GitUIPluginInterfaces/UserControls/CredentialsControl.Designer.cs
Fixes #8825.
API token is required instead of user password for Jira cloud and possibly for newer versions of Jira on-premise versions.
This PR only changes label from _Password_ to _Password/API token_ to make it clearer that token can (or must) be filled there.
----
> Jira plugin configuration - Password renamed to Password/API token

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
Fixes https://github.com/gitextensions/gitextensions/pull/8942#pullrequestreview-605798471
- avoid using the property `Visible`
- manual
- Build 072518e5b13b465ef0ce466fc28435565bd14441
----
> Fixup the initial view menu item state of #8942

- GitUI/NBugReports/BugReporter.cs
- GitUI/Strings.cs
- GitUI/Translation/English.xlf
- UnitTests/GitUI.Tests/NBugReports/BugReporterTests.cs
Follow-up to #8718, parts of #8802 for release 3.5
- Display the error message of the inner-most exception
- Default to `Ignore` on `ExternalOperationException`
- Add `View details` on `UserExternalOperationException`, opens the `BugReportForm`, too
Exception|Before|After
-|-|-
`throw`<br/>`new Exception("Wrapping exception.",`<br/>`new Exception("Intermediate error.",`<br/>`new Exception("Cannot access locked file 'xyz'.")));`|![grafik](https://user-images.githubusercontent.com/36601201/111054126-39706880-846a-11eb-9243-eb157b903c06.png)|![grafik](https://user-images.githubusercontent.com/36601201/111054023-5ce6e380-8469-11eb-98bb-34b3c40236ee.png)
`throw`<br/>`new ExternalOperationException("<command>", "<arguments>", "<workdir>",`<br/>`new Exception("Wrapping exception.",`<br/>`new …
> Improve display of exceptions 3.5

- Plugins/Statistics/GitImpact/FormImpact.cs
- Plugins/Statistics/GitImpact/GitExtensions.Plugins.GitImpact.csproj
- Plugins/Statistics/GitImpact/ImpactControl.cs
- Plugins/Statistics/GitImpact/ImpactLoader.cs
Dependet on #8984
- Move ImpactLoader.cs from GitCommands.Statistics to GitExtensions.Plugins.GitImpact for incapsulation
- Manually
- Build 11d61bfcc3394beaa50eca4d395a8ac12b778489 (Dirty)
----
> Move ImpactLoader.cs from GitCommands.Statistics to GitExtensions.Plugins.GitImpact

- GitExtUtils/GitUI/Theming/OtherColors.cs
- GitUI/CommandsDialogs/FormApplyPatch.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormEditor.cs
- GitUI/CommandsDialogs/FormRebase.cs
Fixes #8976
- Change color to red (same as remote branch)
- Manually
- Visually
- Build 89c85afd9db870026449dbb4167f6a9db268a0f1
----
> Fix "Commit & push" button color when ameding is enabled

- GitCommands/Settings/FileSettingsCache.cs
Part of #8890
If the .gitconfig file is not accessible at startup you should get a prompt asking to change.
This was not happening in #8890 though, the GE config had to be edited manually.
This PR eliminates some additional exceptions at many operations due to that the FileSettingsCache cannot enable the FileSystemWatcher.
Most normal operation after this.
Note that it is still not possible to store settings, even if .gitconfig is not changed at all.
Normal operation - mostly
Manual
Repro (part of the original issue) in the issue
----
> FileSettingsCache: No exception if Git config is inaccessible

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Script/ScriptManager.cs
- GitUI/Script/ScriptRunner.cs
Should fix #2479
I am not familiar with C # programming (first C# coding). And I don't have the environment to compile and test this modification but since it seems like a simple fix with few lines, I guess it can be easily checked.
My proposal is that when a `BeforeCommit `script is called and returns a failure, the commit action should be aborted.
This script failure detection should probably be applicable to other cases (`BeforePush`... ?).
I have a doubt on the fact that this function : https://github.com/gitextensions/gitextensions/blob/e721aadada0ed6c0df8435c36df7357d2c8e957c/GitUI/Script/ScriptRunner.cs#L48
returns `Executed : false` when a script failure happen (`exit 1`) or if this function just launch the script and the output information should be found somewhere else. 
I …
> Check BeforeCommit script failure to abort commit

- GitUI/Editor/Diff/DiffHighlightService.cs
Fixes #8998
- make `DiffHighlightService.ProcessLineSegment` work for single-line text by limiting line number to 0
- manual with the steps in #8998 
- Build 883d1740edbb568ceb14f4be75be4dc094d5c887
----
> Avoid invalid line number in DiffHighlightService

- GitUI/Editor/BlameAuthorMargin.cs
The font used to compute height of image could be out of date
if font of text view is changed by user preferences.
Fixes #8684
- The height of avatar is computed at startup. But the height of the textview can be updated by user preferences. So both size could be different.
In my case, font size used by blame author margin is "Consolas 10" and text view is "Consolas 9,75". The tiny difference of size explains why it affects randomly dpi windows parameter.
None :/
- Build 3c75c4b696788cf573c856795dca61485c351ad5
- Git 2.30.0.windows.1
----
> #8684 Avatars are misaligned in blame form

- GitCommands/Properties/AssemblyInfo.cs
- GitCommands/Settings/AppSettings.cs
- GitExtensions/Program.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserManual/StandardHtmlUserManual.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/CopyContextMenuItemTests.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- UnitTests/GitUI.Tests/UserManual/StandardHtmlUserManualFixture.cs
> Inject current branch slug into the documentation link

- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitCommands/Git/Commands/GitRefsEnum.cs
- GitCommands/Git/GitModule.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Fixes #8879
Revert behavior to be same as in 3.4
If tag labels are shown, also show bisect, notes, stash etc
Note that the labels were orange in 3.4, changed in #8424
(slightly older than master)
Manual
----
> Include stash, bisect in grid if tags are shown

- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- ResourceManager/TranslatedStrings.cs
Fixes #7179
- Turn `Commit & push` button of FormCommit into `&Push` if there are no changes at all
- Move translated string `&Push` from FormPush to `TranslatedStrings`
- Remove repeated type from `new` in `TranslatedStrings`
- manual
- Build b7931b63932f834365c4d8b8da505ae2c7a07bd7
----
> Push from empty FormCommit

- GitUI/CommandsDialogs/BrowseDialog/FormBisect.Designer.cs
- GitUI/Translation/English.xlf
- Manual
- Build 549f02363b5470696a27a1f002241f5ae4f5c719
- .NET Framework 4.8.4311.0
> FormBisect: Autosize form to prevent content to be clipped

- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/GitUICommands.cs
- Update UI only after save settings.
UI is reloaded after closing settings.
UI is reloaded after saving settings dialog.
- Manually
- Visually
- Build 6aed59b6e436ee584bd9a61a4b4655f5f18530dc (Dirty)
----
> Update UI only after save settings

- GitUI/CommandsDialogs/FormCommit.cs
Fixes https://github.com/gitextensions/gitextensions/pull/9017#issuecomment-806239038
- Restore "Commit & push" button if amending without file changes
- manual
- Build 5fff126b0629a85e51b02ac513b3a2d59728f644
----
> Restore "Commit & push" button if amending

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/CommandsDialogs/FormCheckoutRevision.cs
- GitUI/CommandsDialogs/FormCreateTag.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
- GitUI/CommandsDialogs/FormDeleteTag.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/FormPull.cs
- GitUI/CommandsDialogs/FormPush.cs
Follow #9001 to apply script failure detection to others `Before` events as suggested : https://github.com/gitextensions/gitextensions/pull/9001#issuecomment-801801009
----
> Check Before script failure to abort action

- GitUI/NBugReports/BugReportForm.Designer.cs
- GitUI/NBugReports/BugReportForm.cs
- GitUI/NBugReports/BugReporter.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- UnitTests/GitUI.Tests/NBugReports/BugReporterTests.cs
Follow-up to #8718, parts of #8802 as in #8988 for 3.6
- Display the error message of the inner-most exception
- Default to `Ignore` on `ExternalOperationException`
- Add `View details` on `UserExternalOperationException`, opens the `BugReportForm`, too
- Adapt `BugReportForm` to different exception types (disable close if `isTerminating`, add `Ignore` button for `U/EOE`)
- Make `BugReportForm` resizeable
Exception|Before|After
-|-|-
`throw`<br/>`new Exception("Wrapping exception.",`<br/>`new Exception("Intermediate error.",`<br/>`new Exception("Cannot access locked file 'xyz'.")));`|![grafik](https://user-images.githubusercontent.com/36601201/111054126-39706880-846a-11eb-9243-eb157b903c06.png)|![grafik](https://user-images.githubusercontent.com/36601201/111054023-5ce6e380-8469-11eb-98bb-3 …
> Improve display of exceptions

- GitCommands/ExternalLinks/ExternalLinksStorage.cs
- Remove redundant creation of settings container
- Manually
- Build 6666fb64499e5305de7913662a3d657459f1cf6a
----
> Remove redundant creation of settings container

- GitCommands/CommitMessageManager.cs
- UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
Fixes #9036
- Handle errors accessing the amend state file the same way as for the commit message file
N/A
- manual
- slightly adapted existing NUnit tests
- Build 28d662737516d4f7d41611eb2a84ba18e240d58f
----
> Handle errors accessing the amend state file

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphRowTests.cs
Fixes #5782
- Move lanes to the right if a branch would go to one lane left for one row
- Use array instead of `List<RevisionGraphRevision>` in `RevisionGraph`
- manual
- Build b737b5330fc78f10310d5d4aec83f94db23a1e52
----
> Straighten graph lanes

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/LaneInfo.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
First commits from #5783
- Ensure lane colors are not equal to lane they are merged to
- Add `LaneInfo` class
- manual and existing tests
- Build d28d65a93206e789db25a24c9f926f1feb6e39ff
----
> Graph: Ensure branch colors are not equal to branchs they are merged to

- Plugins/Bitbucket/Settings.cs
- contributors.txt
Fixes #8965
- Changed HTTP and SSH regex patterns to match URLs, which might contain a dot in the repo name
----
> Support Bitbucket repos with dots in the name

- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
1. Event handlers in ColorSettingsPage.designer.cs were lost in fcdf2a8777e8755af3fcaa92c5a18b912bb7f729
Subscribing to event handers was moved to non- designer.cs file, because indeed, I have seen multiple times how important code is lost when massively updating .designer.cs file.
2. Fix false positive "Restart needed" message after user chooses default theme, restarts and opens color settings page.
manual
- Windows 10
----
> Color settings page events

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Really just a refactoring, to make it simpler to see in Git Command Log that gir-rev-parse and git-symbolic-ref may exit with error.
The command output has less IO too (to offset the extra parsing of options...)
The commands with actual errors stick out more.
If I see a command with --quiet, I can expect error exit to be handled.
Updated test, manual
----
> rev-parse should use --quiet --verify

- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs
- Suppress "Theme not found" if setting is empty (e.g. after first install)
- Use correct owner for MessageBox
- manual
- Build 9f34af4e57d1eb9b2032dcd22e9d3780d34ff548
----
> Suppress "Theme not found" if setting is empty

- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
- UnitTests/GitCommands.Tests/Git/ExecutableExtensionsTests.cs
- Do not reset a valid `AppSettings.GitBinDir` if `sh` is found in - GE's extended private - `PATH`
- Really try "usr\bin" *and* "bin" subfolders - in changed sequence (as recommended by @vbjay)
- Fixup false friend "gitbindir" in setup of `ExecutableExtensionsTests.SetUp`
This AppSetting was reset in the second run, and `Repair` did not work:
- have git in the `PATH`, namely "C:\Program Files\Git\cmd"
- do not specify the path to the git executable
- set Linux tools path to "C:\Program Files\Git\bin"
- restart twice
- Build 639f83d6ffd9b756a61a7e433284e70221581047
---- …
> Do not reset a valid `AppSettings.GitBinDir`

- GitUI/CommandsDialogs/FormCleanupRepository.Designer.cs
- GitUI/CommandsDialogs/FormCleanupRepository.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.Designer.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.Designer.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
Fixes #9013 
- Replace Cancel by Close to avoid confusion.
Not needed
- Build dd34ed04f62d67884675667f83493ac36e88a954 (Dirty)
- Git 2.30.0.windows.1
----
> #9013 Use Close in Clean working directory

- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPageController.cs
- GitUI/Theming/ThemeModule.cs
- UnitTests/GitUI.Tests/CommandsDialogs/SettingsDialog/Pages/ColorsPageSettingsPageControllerTests.cs
Some time ago the event handlers from ColorsSettingsPage.cs were lost by mistake.
Before knowing that, I misinterpreted what was going on, which lead me to writing [this](https://github.com/NikolayXHD/gitextensions/blob/b1f96fa753ec3d7960f71cd412f7fd80a42ac98a/GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettingsPage.cs#L89)
Here I revert that unnecessary complication, as well as the factually incorrect comment I wrote to explain it.
Tested manually and with unit tests
----
> Remove false comment regarding ColorSettingsPage

- GitCommands/Git/GitModule.cs
- GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
Requirement for #9056 
AutoComplete in FormCommit tries to list all files that are in worktree/index and parse them, to find names of functions etc to use in the autocompletion.
(Extensions and regexp in AutoCompleteRegexes.txt)
First git-diff is tried (OK, but empty), but git-show will raise a git error status. Better to not call Git here than to handle the error in #9056 
No Git calls
Manual
----
> AutoComplete: Avoid Git for non tracked files

- GitCommands/CommitDataManager.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- ResourceManager/LocalizationHelpers.cs
Preparation for #9056 
ExecutableExtensions: CommandCache for Execute()
Previously caching was possible only for GetOutput()
Instead of parsing the combined standard/error output for 'fatal' or 'error:' in IsGitErrorMessage(), use the executable exit status.
The standard usage is to add a a fake GitStatusItem to show the failed command for the user in FileStatusList.
This handling is done _after_ standard output is parsed, as it is currently. 
Note that changes like GitConfigurationException makes it hard to reach these codepaths (you get constant popups, cannot do anything) so testing this is hard.
Manual, some commands are tested though
----
> Use exit status instead of IsGitErrorMessage()

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
I hope it
Fixes #9065
- Cancel ROT background task before rebuilding the tree
- Always set the ToolTipText
N/A
- manual 
- Build c60193fffd232abf2deed81205e8407db560f916
----
> Left Panel: Fixup "is merged" status issues

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphRowTests.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Fixes #5782
Follow-up to / generalization of #9028
- Straighten lanes over multiple rows
- Fix-up missing handling of `RevisionGraphRow._revisionLane` and `RevisionGraph.GetCachedCount`
Before|After
-|-
Remark: The part of the red branch starting at `cff2c15` ending at the line with `03d75aa` could be straightened, too. Though this is not detected by the current implementation because this part consists of multiple segments. 
- manual with GE and Linux repos
- added NUnit test case
- Build 7835202d0aefbcfea65cad1ad884d6c410b978ec
---- …
> Straighten graph lanes over multiple rows

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Translation/English.xlf
Implements #4631
-  Add new option to the commit dialog to allow commits with no changes.
Manual testing
- GIT 2.29
- Windows 10, 20H2
----
> Added 'Allow Empty' checkbox to commit form, and updated command logic

- GitUI/UserControls/PatchGrid.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #9084
Avoid open FormCommitDiff for artificial commits
Other call sites (like in BlameControl) do not handle artificial commits, so these are the situations I saw.
Manual, see issue
Review
----
> FormCommitDiff cannot handle artificial commits

- GitUI/CommandsDialogs/FormSettings.Designer.cs
- GitUI/CommandsDialogs/FormSettings.cs
Fixes #9085
- Change DialogResult only after saving before closing
Settings dialog is closed
Settings dialog is not closed
- manually
- Build f840a0ab83a461035f816951fe39c752a92abc4c
----
> fix-9085 Change DialogResult only after saving before closing

- GitUI/NBugReports/BugReportInvoker.cs
Fixes #9080
amongst others
- Handle exceptions which usually are thrown by `FileSystem` functions, as "failed external operation",
i.e. prefer `Ignore` over `Report bug!` in the TaskDialog showing the error
- manual
- Build 2e79687cf81d088401e7459b580513aae5bf944a
----
> Handle more exceptions as failed external operation

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
Follow-up to #9050
- Allocate `HashSet<int> _gaps` only if lanes are straightened in a `RevisionGraph` row
N/A
- manual
- Build d488e497cc6244483794abedb8e4779495ba861c (Dirty)
----
> Reduce allocations for RevisionGraph lane straightening

- GitCommands/PathUtil.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
- contributors.txt
Fixes #6260 
-  Detects whether clipboard contents contain a potential URL using regex; if so, clipboard contents are provided as-is allowing user to modify contents prior to clone operation.
- Added new tests to PathUtilTest.IsUrl and PathUtilTest.CanBeGitURL
- GIT 2.31.0.windows.1
- Windows 10.0.19042.868
----
> Ignore git clone prefix when checking clipboard for source URL

- Bin/set-telemetry.ps1
Fixes #8228
Workaround:
- Let the installer not activate disabled telemetry
Unchanged:
- Store setting from installer if setting has not existed or if turned off
Limitation:
- The script `set-telemetry.ps1` seems to be not executed at all if just changing the installation by running the installer again:
Checked combobox is ignored if `GitExtensions.settings` already contains the `TelemetryEnabled` entry
- manual
- Build a84a1b52d40568c84c06811885a0967e0c084b11
- Microsoft Windows NT 10.0.16299.0
- .NET Framework 4.7.2633.0
----
> Let installer not activate disabled telemetry

- Setup/Product.wxs
Fixes #9110
- Always install `Newtonsoft.Json.dll` - not only for plugins
- Install it from and into the app directory
N/A
- install without plugins
- run GE
- Build 42c2639e71f08bc96844065efafbd4637edbc1ee
----
> Install `Newtonsoft.Json.dll` not only for plugins

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/SplitterManager.cs
Workaround for #8745 for 3.5.1
addendum #9102
- add similar workaround for `FormBrowse`, too
affected layout:
- manual
- Build 6d07a7312a5b84b81f7ae1ff25e505c2fdd7b31c
----
> Workaround for splitter persistence in `FormBrowse`

- GitUI/OsShellUtil.cs
Fixes #8512
using @RussKie's variant plus adaptation of further function
Quote path given to `Explorer.exe` in
- `OsShellUtil.SelectPathInFileExplorer`
- `OsShellUtil.OpenWithFileExplorer`
- manual
- Build 69cdae72a1013b85f88f13c9fc617611547cc9d5
----
> Quote path for opening with `Explorer.exe`

- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Resolves #9104
1. While staging files the 1st file would be placed on the same line as the command, which locally would lead to test failures with the following message:
````
Ignoring path ﻿"\<first filename>"
````
Rearrange file encoding routine to pass the newline before the filename.
2. Unstage using "git-reset" instead of "git-update-index"
Unstage functionality used unconventional "git-update-index" command, which appears to have caused unexplained test instability locally:
````
fatal: malformed index info ﻿0 0000000000000000000000000000000000000000	"<first filename>"?
````
Replace the implementation with the more conventional "git-reset", and remove encoding routine introduced in #7288.
"git-reset --stdin" is no available until git 2.31.1: …
> Fix stage/unstage implementations

- UnitTests/BugReporter.Tests/SerializableExceptionTests.cs
- Use fixed culture `en-US` in `SerializableExceptionTests`
- Simplify regex
- adapt NUnit test
- Build a294965deda0a16bb72cf31556c9cbc1bad20362
----
> Sanitize localized stack trace in exception tests

- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/BuildServerSettings.cs
- GitCommands/Settings/DetachedServerSettings.cs
- GitCommands/Settings/DetailedSettings.cs
- GitCommands/Settings/RepoDistSettings.cs
- GitCommands/Settings/SettingsSourceExtension.cs
- GitUI/BuildServerIntegration/BuildServerWatcher.cs
- GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/SettingsDialog/AutoLayoutSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/DetailedSettingsPage.cs
- GitUI/SpellChecker/EditNetSpell.cs
- GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
- Plugins/GitUIPluginInterfaces/Settings/IBuildServerSettings.cs
- Plugins/GitUIPluginInterfaces/Settings/IDetachedSettings.cs
- Plugins/GitUIPluginInterfaces/Settings/IDetailedSettings.cs
- Fix settings saving for "Detailed" section by selected setting source.
- Provide a way to work with settings without being tied to a specific implementation and source.
- There is plan to change the CurrentSettings type to ISettingsSource.
- Small interface for each type of setting.
~For discussion without code formatting~.
- manually
- Build f840a0ab83a461035f816951fe39c752a92abc4c
----
> Fix settings saving for "Detailed" section by selected setting source

- GitUI/Editor/FileViewer.cs
Fixes 1. of https://github.com/gitextensions/gitextensions/pull/8522#issuecomment-829594076 - unrelated to .NET 5.0
`FileViewer` toolbar: Remove the decoration of default `Encoding`
because of
- incomplete implementation: ComboBox empty due to not matching name
- inconsistent `Encoding` naming: `EncodingName` vs. `HeaderName`
- manual
- Build 7213de011d4ae508fc819473c68f27a6c1f702e8
----
> `FileViewer`: Remove decoration of default encoding

- GitUI/GitUIExtensions.cs
Temporary fix for #8914 (not closing #8914)
The proper fix is in #8923, but that PR introduces some test instabilities so the app code is patched instead.
Do not hang the application when submodule status is not evaluated when viewing.
Manual.
You may have to insert the error by installing Symantec or adding a delay to submodule status calculation.
----
> View changed submodule could hang GE

- Setup/Product.wxs
Related to #9166
- Add `BugReporter.exe` to installer
- manual
- Build fec693532c9cc0e23e0e91c841b9a343c64f86c2
- .NET Framework 4.7.2633.0
----
> Add `BugReporter.exe` to installer

- GitUI/GitUICommands.cs
Fixes #9121
Refresh revision grid after Stash pop.
Also changed after stash-apply, but that makes no practical difference as the command is only invoked from FormStash (and not update the grid...)
Regression, to be cherry-picked for 3.5
See the issue. Stash, stash-pop and see that the grid refreshes.
----
> Stash pop/apply: Refresh grid if command was successful

- GitUI/CommandsDialogs/FormCommandlineHelp.resx
- GitUI/GitUICommands.cs
Fixes #
- dot command is widespread in most applications to open the current working directory. I have added a `private` function to handle the `.` command in this pull request. For Eg: If a user wants to open their current repository in GitExtensions, he should trigger the command `GitExtensions .`
A user needs to enter different commands to open his current repository.
`GitExtensions browse .` is an example.
By these changes, a user can open the repository in GitExtensions by just triggering the command `GitExtensions .`
Need documentation for this command once this PR got sufficient approvals. 
- I have tested the changes by modifying the project launch setting property.
- Also, to ensure functionality, I have run the executables from a different git repository.
- Both negative and …
> feat: add dot command to GitUICommands

- GitCommands/Git/GitSshHelpers.cs
- GitCommands/SshPathLocator.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
- UnitTests/GitCommands.Tests/SshPathLocatorTest.cs
Part of #9112
Some SSH refactoring has changed the SSH setting to not always be stored as "" (stored in registry).
The OpenSSH setting is therefore always presented as other.
This is part of what described in #9112, but not the core problem.
OpenSSH is not set, but the path is correct
manual
---
> OpenSSH presented as OtherSSH in settings

- GitCommands/Git/Executable.cs
Fixes #9169
- Ignore failure getting `Process.Id` after successful `Process.Start` if `useShellExecute: true`
CommandLog:
- manual (see #9169)
- Build 8fbc9d3405af49bf27f1421b41874a1468018e69
----
> Ignore failure getting `Process.Id` when opening URL

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes the main part of #9165 2.
- Do not attempt to switch to a not created worktree
- Dispose worktree forms after usage
N/A
- manual 
- Build aed5edbf418d93b9e5f0497b62f226b0f5ae1b15
----
> Do not attempt to switch to a not created worktree

- GitCommands/Git/Executable.cs
Fixes #9169
(#9173 for main)
- Ignore failure getting `Process.Id` for `ShellExecute`
- Build 908f842356fd5d0323670f8ab95e179f0bf6eb77
- .NET 5.0.5
----
> Ignore failure getting Process.Id for ShellExecute

- GitUI/GitUIExtensions.cs
Fixes #9195
Do not try to view deleted images.
This applies both to difftab and commit.
3.5
Separate view in worktree and index/commit
master has the popup, not really required
Same for worktree and index
manual
----
> Do not try to show deleted images in diffviewer

- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
Fixes #9070
Avoid showing Open... menu items for deleted items.
Similar for a few other menu items, maybe not causing exceptions but having no effect (or as for Save, saving an emty file).
Note 1: "Show in folder" could be relevant for an index item if it is created in worktree, but let us skip this use case..
Note that Open in folder also exists for FormDiff, just nothing happens. I suggest we leave it at that (that form could maybe be retired).
manual
----
> Diff/Commit: Do not show Open for deleted items

- GitCommands/Git/GitSshHelpers.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
Fixes #9112
Presentation handled in #9149
A second part separated to #9188 
Also for 3.5, but translation changes to be null
If the SSH path does not exist, do not set GIT_SSH env var. 
Git will then attempt to use OpenSSH included with Git.
In 3.4 or earlier, the OpenSSH path was set in the registry, even if it was supposed to be empty (handled in #9149).
If the OpenSSH path is corrupted (as reported and discussed in #9112 when upgrading GE) it will just be ignored.
This will also recover from issues if the Git installation is changed.
The settings will check and report an illegal path too.
Note that viewing the SSH setting will change the presented, then saved path if the path does not exist. A follow up PR will address this.
Modify the gitssh key in the registry and start GE and make …
> Set GIT_SSH only if path exists

- GitUI/UserControls/CommitSummaryUserControl.Designer.cs
when displaying the application with 150% scaling
Fixes #9115
WIth 150% scaling or by reducing the window form size to the minimum
- Manual (set display scaling to 150%)
- Build 53b71f790833cff271aba3d0f4bd2cc91a2ff496 (Dirty)
> FormCreateBranch: Fix branches list display on 2 lines

- GitExtUtils/GitUI/ThreadHelper.cs
- GitUI/CommitInfo/CommitInfo.Designer.cs
- GitUI/CommitInfo/CommitInfo.cs
- UnitTests/CommonTestUtils/TestAppSettingsAttribute.cs
Fixes #9204
- Switch to UI thread before calling `CommitInfo.UpdateRevisionInfo`
That's why it should go into 3.5.1, too.
- Join async operations before disposing `CommitInfo`
- Speed up tests by `AppSettings.ShowAvailableDiffTools = false`
N/A
- manual
- run unit & integration tests
- Git Extensions 0.0.0.0
- Build d25e6402326c9a1ddbbe8145b65b34e52843a9dc
- .NET 5.0.6
----
> `CommitInfo`: Fix up threading issues

- GitCommands/Logging/CommandLog.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/BrowseDialog/FormGitCommandLog.cs
Related to Git issues, like debugging for #9056 it is very helpful to have call stacks always available in the Command Log. This is especially important for commands during the startup phase, before the capture can be enabled.
It can be hard to recreate the situation a reporter experiences.
I often have this enabled in my private builds, but with #9056 I expect at least developers to require this.
(#9056 is a good change to avoid just swallowing Git errors.)
No UI change, just showing what is made persistent
Manual
----
> LogCaptureCallStacks in AppSettings

- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
- UnitTests/GitCommands.Tests/Settings/SettingTests.cs
Fixes #9209
- Delete temp files from `AppSettingsTests` and `SettingTests`
- Dispose `GitExtSettingsCache` in all `AppSettingsTests` and in `OneTimeTearDown` of `SettingTests`
- Create `SettingTests._settingContainer` only once
- run NUnit tests
- Build 28814ce7ba5f63f1b557bbbd6f33616b5d016a45
- .NET 5.0.6
----
> Delete temp files from settings tests

- GitCommands/Git/GitSshHelpers.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/SshPathLocator.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
- GitUI/Infrastructure/Telemetry/AppEnvironmentTelemetryInitializer.cs
- UnitTests/GitCommands.Tests/SshPathLocatorTest.cs
Fixes #8162
Fixes #1663
Also see #7662 and a few others
See #9202 for a partial change for 3.5
Just read path from AppSettings.SshPath
Set GIT_SSH env var only set, not read.
Migrate explicit OpenSSH in settings to empty
Previously, the app first read registry for gitssh path and set environment variable GIT_SSH unless it was empty. This was maybe a feature for some, as you could share SSH settings.
However, when setting SSH in settings, GIT_SSH was always set which was inconsistent.
The behavior is changed to only set GIT_SSH, never set it.
Tests updated
As logic is simplified, tests are simplified too
----
> Keep persistent ssh settings in registry

- GitCommands/Git/GitSshHelpers.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/SshPathLocator.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/SshSettingsPage.cs
- GitUI/Infrastructure/Telemetry/AppEnvironmentTelemetryInitializer.cs
- UnitTests/GitCommands.Tests/SshPathLocatorTest.cs
#9182 and part of #9188 for 3.5
(#9188 could be applied but it introduces plugin interface changes)
#9182 Translation changes in #9182 was reverted too (stating "unknown" instead of "other")
Set GIT_SSH only if path exists
Just read path from AppSettings.SshPath
Set GIT_SSH env var only, not read.
Report if ssh path is not found in Settings
Manual
----
> Set GIT_SSH only if path exists 3.5

- GitCommands/Git/Executable.cs
- GitCommands/Git/GitModule.cs
- GitExtUtils/ExternalOperationException.cs
- GitExtensions/Program.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
- GitUI/NBugReports/BugReportInvoker.cs
- GitUI/NBugReports/UserExternalOperationException.cs
- GitUI/Script/ScriptRunner.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- UnitTests/GitUI.Tests/NBugReports/BugReportInvokerTests.cs
Preparations for #9056
- Handle more exceptions as "failed external operation" (same as #9094 for release/3.5)
- Do not crash on exception if debugger is attached
- Check `ExitedSuccessfully` in `GetStashDiffFiles`
- Avoid exit code 1 when checking for valid git executable
- `ExternalOperationException`: Add property `ExitCode`
- Remove unnecessary `ThreadHelper.AssertOnUIThread` before throwing `UserExternalOperationException`
- extended existing NUnit tests
- manual tests with FormStash and `Include tracked` ticked
- Build 06582e3d0114e17540b03dbaa6f9388a0a0e07a2
- .NET 5.0.6
---- …
> Preparations for exceptions on git error

- GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.Designer.cs
- GitUI/CommandsDialogs/RepoHosting/CreatePullRequestForm.cs
- GitUI/CommandsDialogs/RepoHosting/ViewPullRequestsForm.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
-  ViewPullRequestsForm: 
- better handle error on one remote (form is now still usable when a remote is on error)
- fix selection of first remote found with at least a pull request
- CreatePullRequestForm: 
- better handle error on one remote (form is now still usable when a remote is on error)
- CreatePullRequestForm: increase width of dropdown 
Unable to do one easily but red arrow in 'after' screenshot show width increase to display well long branch name
- ViewPullRequestsForm:
- CreatePullRequestForm: 
- Manual
- Build 47bb7083c58cafdb7d180c425a88389b116b6f44
> Some GitHub plugin fixes

- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- Fixup RevisionGridControlTests:
- Throw all errors instead of printing them
- Fixup a wrong test assertion, which was ignored before
- Improve RevisionGridControlTests stability
by waiting until change counts have been updated, before starting "toggle artificial" tests
- run the tests
- Build 5e6d755b7623f7d1d7f08645ddd679b3973d6e1d
- .NET 5.0.6
----
> Improve RevisionGridControlTests

- GitCommands/FileAssociatedIconProvider.cs
- GitCommands/FullPathResolver.cs
- GitCommands/Git/GitItemStatusFileExtensionComparer.cs
- GitCommands/GitRevisionInfoProvider.cs
- GitCommands/PathUtil.cs
- GitCommands/Settings/FileSettingsCache.cs
- GitUI/AutoCompletion/CommitAutoCompleteProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeController.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormChooseTranslation.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPageController.cs
- GitUI/Editor/FileViewer.cs
- Plugins/Statistics/GitStatistics/LineCounter.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Prepare to replace PathUtil.Combine and PathUtil.GetExtension with the .NET5 Path variants directly. 
https://docs.microsoft.com/dotnet/core/compatibility/2.1#path-apis-dont-throw-an-exception-for-invalid-characters
.NET5 Path no longer throws ArgumentException on
"Illegal characters in path".
Replace PathUtil Combine and GetExtinsion with the Path
variant directly as well removing other catches of ArgumentException.
* Remove .NET5 todo
Tests were updated - when PathUtil versions are removed the tests will be removed though
----
> Replace PathUtil.Combine and GetExtension with Path.

- GitCommands/Git/GitModule.cs
- GitExtUtils/GitCommandConfiguration.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Some of the preparations for #9056 contributed by @gerhardol
- Suppress git warning for safecrlf
occured if:
* core.safecrlf is warn or true
* core.autocrlf is true on Windows
* a file stored in crlf is edited to lf
* File is selected in Diff tab
- Let git filter for merge commits instead with own regex
- Avoid git error in Left Panel
occurred when the ROT is initialized in the Dashboard without a working dir, of course
not affected
- NUnit tests
- manual
- Git Extensions 0.0.0.0
- Build b430c3f01860c5cfaeeee18e72c2a1db456a449a
- .NET 5.0.6
----
> Preparations for exceptions on git error (part 2)

- GitUI/CommandsDialogs/FormMergeSubmodule.cs
Fixes part of #7466
- Do not attempt to checkout not existing submodules in `FormMergeSubmodule` by disabling the `Checkout branch` button
since the handler will attempt to parse the `ObjectId`s unconditionally:
```
private void btCheckoutBranch_Click(object sender, EventArgs e)
{
var revisions = new[] { ObjectId.Parse(tbLocal.Text), ObjectId.Parse(tbRemote.Text) };
```
- Git Extensions 0.0.0.0
- Build acd96eaa7f68a7289339c21473baf1f9f9c28548
- .NET 5.0.6
----
> Avoid `FormatException` from `FormMergeSubmodule`

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Branches.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
Fixes #9232
- Left Panel: Always check `TreeViewNode.TreeView` for `null`
not affected
- manual
- Git Extensions 0.0.0.0
- Build b988ca34e9a5c9f75f3890058963678fc0d73aec
- .NET 5.0.6
----
> Left Panel: Check `TreeViewNode.TreeView` for `null`

- GitCommands/Settings/AppSettings.cs
- GitUI/NBugReports/BugReportInvoker.cs
An attempt to capture an elusive error information for #9166.
Write an error log before showing the bug reporter dialog if `AppSettings.WriteErrorLog=true`.
Contributes to #9166
> Log errors

- GitCommands/CommitMessageManager.cs
- GitCommands/CustomDiffMergeToolCache.cs
- GitCommands/ExternalLinks/ExternalLinksStorage.cs
- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/StringPool.cs
- GitExtensions.sln.DotSettings
- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/Infrastructure/Telemetry/DiagnosticsClient.cs
- TranslationApp/Program.cs
- Fix annotations
- Fix typos
- Add words to dictionary to reduce warnings in the IDE
- Remove redundant string interpolation
----
> Small bits

- GitCommands/Git/AheadBehindDataProvider.cs
- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitCommands/Git/GitModule.cs
- GitExtUtils/GitCommandConfiguration.cs
- GitExtensions/AutoCompleteRegexes.txt
- GitUI/Editor/FileViewer.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
A collection of some smaller issues
Align git-diff -M -C arguments
GetCurrentChangesCmd() only had the options for Index/staged files but not worktree.
This is not really an error but different from all other diff commands.
git-diff options for rename and copy of files were put in various order which made me confused.
There should be no significance in the ordering, this is a cleanup to avoid dong the investigation again
Order is set to beconsistent and more aligned with Git documentation.
Also, "-M -C" was at one occasion on separate lines, which made this harder to search for.
(The alternative is to change all options to be separated.)
--
Git commands should never have colors
Colors are excluded by default in pipe/file output
However, the user can override the settings
Most common …
> Git commands should never have colors

- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormDiff.Designer.cs
- GitUI/CommandsDialogs/FormDiff.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormLog.Designer.cs
- GitUI/CommandsDialogs/FormLog.cs
- GitUI/CommandsDialogs/FormStash.Designer.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/CommitDiff.Designer.cs
- GitUI/UserControls/CommitDiff.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- Fixes #8914 so that the application doesn't hang when submodule results have not completed at the time they're requested.
- Makes the UI responsive while the submodule operation is underway.
- Discards some unawaited tasks, as these triggered compiler diagnostics after making the above changes (unsure why).
This required making methods `GitModule.GetSingleDiff` and `SubmoduleHelpers.GetCurrentSubmoduleChanges` async.
----
> Fix hang when requesting submodule status

- GitUI/UserControls/FileStatusList.cs
See https://github.com/gitextensions/gitextensions/issues/9166#issuecomment-849567022
```
Is fatal: False
System.Runtime.InteropServices.ExternalException (0x80004005): A generic error occurred in GDI+.
at System.Drawing.Image.FromHbitmap(IntPtr hbitmap, IntPtr hpalette)
at System.Drawing.Image.FromHbitmap(IntPtr hbitmap)
at System.Windows.Forms.ImageList.GetBitmap(Int32 index)
at System.Windows.Forms.ImageList.ImageCollection.get_Item(Int32 index)
at GitUI.ListViewExtensions.Image(ListViewItem item)
at GitUI.FileStatusList.FormatListViewItem(ListViewItem item, PathFormatter formatter, Int32 itemWidth)
at GitUI.FileStatusList.<>c__DisplayClass127_0.<UpdateColumnWidth>b__2(ListViewItem item)
at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
at …
```
> Ignore `Image.FromHbitmap` failure

- GitCommands/Settings/AppSettings.cs
- GitUI/NBugReports/BugReportInvoker.cs
- GitUI/UserControls/FileStatusList.cs
#9245 and #9227 for dev branch
- Log exceptions to files in `%TEMP%` if enabled using `AppSettings.WriteErrorLog`
- Catch `System.Runtime.InteropServices.ExternalException` in `FileStatusList.UpdateColumnWidth` and log it to `%TEMP%`
- manual
- Build e8aea1db1b9ffd3fdfe5b00d84ab8678838f322a
- .NET 5.0.6
----
> Catch GDI exception

- GitCommands/Git/GitVersion.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
Part of #9229 
- Reset GitVersion cache when setting Git command path
Report new GitVersion after changes
- Use static/cached GitVersion to resolve Git path
This eliminates one `git --version` command during startup. At home this is about 35ms, at work 230ms (probably serialized, so delaying the startup considerably).
Tests exist
Manual
See Git Command Log for executed command, modify gitcommand path in registry to simulate issues
----
> Use static/cached GitVersion to resolve Git path

- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
Two issues from #9243 for 3.5
(unknown when the regressions occurred)
These issues relate to that the commit body is not stored for commits older than 6 months.
The subject and info if the commit has multiline info is always available.
If you select the commit in the grid, the full body is loaded (again).
- RevGrid tooltip: Only show "click to load" for multiline
This occurred if the commit had any related refs.
- Multiline indicator only shown if Body is available
Note that there is no tooltip if there are no refs or multiline. Without the multiline indicator it is hard to understand why.
before|after
--|--
manual
----
> RevGrid multiline indicators 3.5

- GitCommands/PathUtil.cs
- GitCommands/UserRepositoryHistory/LocalRepositoryManager.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormPush.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCloneTests.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
- contributors.txt
Fixes #6260 
- Adds a new method in FormClone to extract a URL from a text string.
- Updates Clone form to use new method
- Added new integration test in FormCloneTests.cs
- GIT 2.31.0.windows.1
- Windows 10.0.19042.868
----
> Update Clone dialog's handling of clipboard text

- .editorconfig
- CommonAssemblyInfo.cs
- Directory.Build.props
- UnitTests/GitCommands.Tests/Properties/AssemblyInfo.cs
- UnitTests/GitExtUtils.Tests/Properties/AssemblyInfo.cs
- UnitTests/GitUI.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/BuildServerIntegration/AppVeyorIntegration.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegration.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/DeleteUnusedBranches.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/GitUIPluginInterfaces.Tests/Properties/AssemblyInfo.cs
- UnitTests/Plugins/ReleaseNotesGenerator.Tests/Properties/AssemblyInfo.cs
- UnitTests/ResourceManager.Tests/Properties/AssemblyInfo.cs
Related https://github.com/dotnet/roslyn-analyzers/issues/4983#issuecomment-852738069
> Enable CA1416: Validate platform compatibility

- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitCommands/Git/GitModule.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Part of #9229
Limit the number of super project refs shown in a submodule.
The value is hardcoded to 100, could be a default in AppSettings so users could override if they want to see more even if this is not exposed in settings.
Maybe the number of references should be tweaked to an even lower value than 100.
The superproject branches can be interesting in a subrepo, but with a large number of refs (I have 1200 in my GE repo) the listing of superproject branches/remotes/tags require some time, so the update takes time. Quite some CPU load is used (in background) and the Git Command log is stalling the application if open.
This also cleans up the code, an unnecessary command to candle git-for-each-ref was removed. Note that the call was incorrect for tags, fixed in the "common" variant …
> Limit superproject refs in rev grid

- global.json
- Allow `rollForward` for .NET 5.0 SDK at `feature` level in order to use the latest one installed e.g. by the update to VS 16.10.0
refer to https://andrewlock.net/exploring-the-new-rollforward-and-allowprerelease-settings-in-global-json/
- `dotnet build`
- Build 88aec72ad50172033bc707e82c9f1641ea838e47
- .NET 5.0.6
----
> Allow rollForward for .NET 5.0 SDK version

- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- Handle `laneInfo` being `null` when determining the color of commits without neither parents nor children
- Consume exceptions from `RevisionGraphColumnProvider.OnCellPainting` since they do not bubble up to our handlers, and write them to the `Debug` output and - in debug build - also to `%TEMP%`
- Remove redundant condition in `RevisionGraphColumnProvider.OnCellPainting`
Graph rows drawn black completely due to throwing `Validates.NotNull(laneInfo)`
- manual
- Build f89e7963407fb4b4cbc1229ff6db32332ed929c9
- .NET 5.0.6
----
> Handle `laneInfo` being `null`

- GitUI/CommandsDialogs/FormCheckoutRevision.Designer.cs
- GitUI/CommandsDialogs/FormCherryPick.Designer.cs
- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormRevertCommit.Designer.cs
- GitUI/Translation/English.xlf
- Add mnemonics to
- `FormCheckoutRevision`
- `FormCherryPick`
- `FormRevertCommit`
- `FormPush`
- `FormPush`: Avoid `ComboBox`es appearing focused after `ResizeDropDownWidth`
Fixes #9192 3.
Before|After
-|-
- manual
- Build 607a1b4bc424fa1667bf532b3c4b3c1827661cb5
- .NET 5.0.6
----
> Add mnemonics to frequently used dialogs

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #9283
The git status was not updated correctly for new files in the index
that also were changed in the worktree. The worktree file could therefore
not be displayed.
See issue
Manual
----
> Commit: Unstage new files did not display the worktree file

- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUIExtensions.cs
Fixes #9280
Allow line patching for worktree/index files, both in Browse and Commit.
This was a case that was ignored when the separate code paths in Commit was removed and functionality only handled in FileViewer.
Note that it is not possible to unstage the last line in a new file (same as before). Ignored.
Manual (limited tests so far)
----
> Allow line patching for new worktree/index files

- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- Add mnemonics to the context menu of the `RevisionDiffControl`
The same without most of the mnemonics
- for commit file(s)
- for unstaged file
- for staged file
- for unstaged submodule
- for staged submodule
- manual
- Build 33032a04a860c1b4a2a438dc1742e9215b1902e8
- .NET 5.0.6
----
> Add mnemonics to context menu of `RevisionDiffControl`

- GitExtUtils/GitUI/Theming/OtherColors.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #9192 1. & 2.
- Gray selection if not focused for
- `RevisionDataGridView`
- `FileStatusList` (i.e. also for other Forms lile `FormCommit`)
Inactive color value `OtherColors.InactiveSelectionHighlightColor` is chosen to be identical to `AppColor.DiffSection`, which is visible right beside.
- Remove redundant `RevisionDataGridView.OnRowPrePaint`
- Cache Brush for `AppColor.AuthoredHighlight` like for `_alternatingRowBackgroundBrush`
- Hide selection if not focused for `RepoObjectsTree`
Notice: The focus is in the `DiffView`.
- manual
- Build e5d6cdd13bf1d2c15f43272183a8e16daa7144b4
- .NET 5.0.6
---- …
> Gray / hide selections in `FormBrowse` if not focused

- CONTRIBUTING.md
- Externals/NetSpell.SpellChecker/Spelling.cs
- GitCommands/EnvironmentPathsProvider.cs
- GitExtensions/Project.Build.targets
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormRemotes.cs
- GitUI/CommandsDialogs/SettingsDialog/CheckSettingsLogic.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ScriptsSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ShellExtensionSettingsPage.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUICommands.cs
- GitUI/Resources/ChangeLog.md
- GitUI/Resources/Icons/originals/_Icon Sources.txt
- GitUI/Script/SplitButton.cs
- GitUI/Theming/ThemeLoader.cs
- GitUI/UserControls/NativeTreeViewExplorerNavigationDecorator.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRow.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
- GitUI/WindowsJumpListManager.cs
- UnitTests/GitUI.Tests/Editor/FileViewerTextTests.cs
- UnitTests/Plugins/BuildServerIntegration/AzureDevOpsIntegration.Tests/ProjectUrlHelperTests.cs
- appveyor.experimental.yml
Fixes #9292
- Fix misspellings/typos in
- Non-code files
- Comments in code files
Additionaly, there could be more commits that:
- enforces US or British English. That depends on consensus of responsible people.
- fix symbols (type/member names). It is question whether to do it here or in a separate PR.
No special testing should be needed.
> Comprehensive fix of misspellings/typos

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- contributors.txt
Original code by @FodderMK
Fixes #9298
- Readd revision graph configuration option that was previously removed
- Enabled by default as it currently is without the option
----
> Make showing commit message body in the revision graph optional

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
Fixes #9291
- Prepopulate Delete Tag dialog with the `FullName` of the tag
- manual
- Build 55dec49de1d4b378f27687d36b47b90ab8c6250d
- .NET 5.0.7
----
> Open Delete Tag dialog from Left Panel with full tag name

- GitUI/UserControls/RevisionGrid/Columns/ColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Fixes #9108
- Fixup `RevisionGraph.GetCachedCount`: return full `cachedCount` only if loading has really finished
- Fixup condition in `DrawItem` of `RevisionGraphColumnProvider`
- Fixup theoretical race condition with `RevisionGridControl._isReadingRevisions`
see issue
- manual
- Build 7287ca7ff5688e23ef3b0a0d242a80e744996e89
- .NET 5.0.6
----
> Fixup partial graph rendering

- GitCommands/Settings/AppSettings.cs
Fixes #9288
- If missing, create a minimum settings file instead of skipping the activation of the `FileSystemWatcher` (#9003)
- manual
- Build 202d4f1678f0cd15822432fdbe60800d3fbb7085
----
> Create empty settings file if missing

- GitUI/CommandsDialogs/FormStash.Designer.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/Translation/English.xlf
Fixes #8108
- HotKeys for next/previous stash and refresh
Ctrl-P navigates to next older stash item, similar to how navigation in RevGrid.
- Mnemonics for the form. 
As `Stashes` control gets a specific hotkey, it is possible to navigate in the stashes list with Alt-H arrow /PageUp/etc too
"&Apply stash" but "S&tash all changes" as I expect Ctrl-Alt-Up to be used for stash in current worktree.
- Stash: Keep position when dropping a stash 
Simplify deleting stashes, unless deleting the first, you would have to search for the stash close to where you just deleted the stash.
- Remove button for custom message, just make it writeable for worktree.
Add label for mnemonics 
Manual
---- …
> Stash: Keyboard navigation

- GitCommands/CustomDiffMergeToolCache.cs
vimdiff1 is a console only application included since Git 2.31
It should be excluded from the default difftools
This is a little annoying if you only have one difftool
This could be a hidden setting too, to allow the user to override the GE defaults.
For now this is good enough, new tools are not added that often.
To be cherry-picked for 3.5.1
With one tool only, the rightmost submenu is not added
Manual
----
> Exclude vimdiff1 from custom difftools

- GitUI/BitmapExtensions.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/HelperDialogs/FormStatus.cs
- GitUI/Interops/User32/ReleaseDC.cs
- GitUI/UserControls/TextBoxEx.cs
- GitUI/WindowsJumpListManager.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionFileTreeControllerTests.cs
Fixes #9166
Fixup GDI object leaks:
- Release DC retrieved using `GetWindowDC`
- Dispose resources in `WindowsJumpListManager.MakeIcon`
- Correctly convert `Bitmap` to `Icon`
- Cache `Icons` drawn for Taskbar overlay / Jump List
- manual
- Build 99649dc430eb85fbacda92046a639af8d1c552dc
----
> Fixup GDI object leaks

- GitUI/CommandsDialogs/FormRebase.Designer.cs
- GitUI/CommandsDialogs/FormRebase.cs
Reduce window flicker and loss of focus
1. Force child window ownership to FormBrowse
2. Show the rebase dialog *before* starting any operations. This is what appears to be the main cause of the loss of focus. The dialog isn't yet shown when we invoke the progress dialog, which is then gets closed but the window that spawned it is not visible. MS Windows gets confused and pushes another window to the foreground, thus causing the app to lose focus.
----
> Reduce window flicker and loss of focus

- GitUI/CommandsDialogs/FormRebase.cs
git-for-each-ref requires up to 300 ms, this command is executed twice when in non advanced mode (when FormRebase is not used, though it will be shown in #9311 ).
Also no need to run the command twice when the form is shown reuse the existing Git ref list.
Manual
----
> FormRebase: Avoid list refs if not advanced

- GitCommands/Git/GitRef.cs
- GitExtUtils/Linq/LinqExtensions.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/UserControls/FileStatusList.cs
- Plugins/Statistics/GitStatistics/LineCounter.cs
Fixes #9159.
- Removed custom methods.
- Started using methods from .NET 5.
- Existing tests are used for now.
- 
- 
- GIT 2.21.0.windows.1
- Windows 10
----
> Remove custom ToHashSet() methods. Fixes #9159

- GitCommands/Git/GitRevisionTester.cs
- Quick search `Body` - instead of just `Subject` - if available
- manual:
- focus RevisionGrid
- type "cherry"
- hit <kbd>Alt</kbd>+<kbd>Down</kbd>
should find cherry-picks
- Build 2e3fce40b207c8ff4c3ee5c4b442e58a3f812b7b
- .NET 5.0.7
----
> Quick search in whole commit message if loaded

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConsoleStyleSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConsoleStyleSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConsoleStyleSettingsPage.resx
- GitUI/Translation/English.xlf
- GitUI/UserControls/ConsoleEmulatorOutputControl.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
This is the 2nd part supplementing the PR to the ConEmu fork https://github.com/gitextensions/conemu-inside/pull/28. The idea  is to allow powerline supported fonts.
As shown on the screenshot below, setting the font name to a powerline supported font resulted in this nice rendering.
I could not get the design view for `ConsoleStyleSettingsPage` to load in Visual Studio 2019 but I hand edited the `ConsoleStyleSettingsPage.designer.cs` file directly. It build, runs and renders fine but as an improvement I would like to use the standard button based font selection and combine font name + size. I'll do it as a separate PR next.
> Add support for setting console emulator font name

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #9349
- Assign `BashShell` to missing `Tag`
- manual
- Build 734820868d11a17f2eac0aa5ec7b538083d9d4f3
----
> Fixup main menu item `Git bash`

- GitCommands/CommitTemplateItem.cs
Fixes #9150
- Removed BinaryFormatter code after @pmiossec discovery.
- 
- 
- Current tests were used.
- 
- 
GIT 2.21.0.windows.1
Windows 10
----
> Remove BinaryFormatter. Fixes #9150

- GitUI/Script/PowerShellHelper.cs
(#9351 for 3.6)
Fixes #9347
- Tell `Executable.Start` to create a window for user scripts which shall run PS in the foreground
- manual
- Build e5583961130d5ad7060c9f0397d983cbd6aedecf
----
> Fixup user scripts running PS in foreground

- GitCommands/Git/AheadBehindDataProvider.cs
- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
Some of the preparations for #9056 contributed by @gerhardol and me
- Fixup `GitModule.UpdateIndex`: output the newline after the file name
in order to avoid a git error message on the first file name being empty
- `AheadBehindDataProvider`: Return `null` on non-zero git exit code
not affected
- NUnit tests
- manual
- Build 35632c7562a986c041ccd632ebee1d8816e6b14e
- .NET 5.0.7
----
> Preparations for exceptions on git error (part 3 of 4)

- GitCommands/Git/GitRef.cs
- UnitTests/GitCommands.Tests/Git/GitRefTests.cs
Fixes #9338 
Check string length before using a substring.
Use full Name if not possible to remove the Remote prefix.
For the FormCreateBranch example, this may return an unexpected name, but that is just a suggestion for the user anyway.
Similar effects for a few other random usages I saw.
So this should be safe.
Code review
----
> GitRef: Remote may be as long as Name

- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
Some of the preparations for #9056 contributed by @gerhardol
- `GetMergedBranchesAsync`: Ignore (git exit code and) `StandardError`
- `GetRemotesAsync`: Return empty list on non-zero git exit code
- `GetRefs`: Return empty list on non-zero git exit code
**I am not really convinced that we should swallow errors from these commands.** That's why:
- Add `TODO`s for later generic handling of `StandardError`
not affected
- NUnit tests
- manual
- Build e6c851cfefa2e47a30f46d194c59f5e95017acbc
- .NET 5.0.7
----
> Preparations for exceptions on git error (part 4 of 4)

- GitCommands/RevisionReader.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.empty_commit.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitCommands.Tests/TestData/RevisionReader/empty_commit.bin
Fixes #9354
Allow that a subject in a commit is empty
Test case added
----
>  RevisionReader allow empty subject

- appveyor.yml
Fixes #9273
- Restore the working loc verification from 8da72f42cf02b377fbdb9ccccf1747f1b3f53e46
- Stage all files which have been modified by the build process, a.o. by `set_version_to.py`
- CI build
- AppVeyor
----
> Fixup localization verification

- GitCommands/RevisionReader.cs
- Plugins/GitUIPluginInterfaces/ObjectId.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
Followup to #9354 #9243
* A few minor optimizations, mostly using `in` parameters (likely not noticeable)
The log parsing is probably the most important code to optimize for opening a repo.
* Log parse errors (with limitations)
Before #9243 parse errors had to be ignored as the input data was incorrectly split for FileHistory.
In #9354 the parsing failed (introduced in #9243), only seen in DEBUG though.
If there are other parse errors (likely existing from before, not much of the actual parsing logging has been changed), the visibility is improved by Debug.Assert the first occurrence and Trace.Assert the first 10 errors. Printouts include the commit sha if available.
This will notify DEBUG users and give a way for production users to provide information, but avoid that the log or popups …
> Log RevisionReader parse errors

- GitCommands/Settings/AppSettings.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitExtensionsForm.cs
- GitUI/GitModuleForm.cs
- ResourceManager/GitExtensionsControl.cs
- ResourceManager/GitExtensionsControlInitialiser.cs
- ResourceManager/GitExtensionsFormBase.cs
This is likely an ongoing work where we'll need to check every form and/or control we edit and apply `IsDesignMode` check to avoid executing unnecessary code in the Windows Forms designer.
Resolves #9388
> Enable use of the designer

- GitCommands/Git/GitSshHelpers.cs
Related to #9355 #9360 #9348
Similar to #9369 that still have trace printouts and therefore is WIP (and should get cherry-pick comment when this merged).
The path in GIT_SSH may be accessible for git.exe even if not for GE
Manual
----
> Do not check if path exists before settings GIT_SSH

- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
Needed with #9056
Follow up to #9335 
See long term goals in https://github.com/gitextensions/gitextensions/issues/7598#issuecomment-864561070
(FileHistory is a sidetrack)
It is possible to blame Git Tree objects (folders) from File tree.
GE shows the history for all commits affecting the folder, but just display the file and blame for one of them (the first reported file).
The name for the displayed/blamed file is added to the title bar.
If no files are seen for a certain commit, GE uses the "FileHistory" path for blame, which is not possible for a folder.
Also the first file in the folder is viewed, not matching the folder name in the title bar.
Diff tab could have been displayed but parsing of multiple diffs fail why this is hidden too.
(So no tabs shown for folder and aritificial …
> Do not blame folders

- GitCommands/Git/Commands/GitDeleteBranchCmd.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormCheckoutBranch.cs
- GitUI/CommandsDialogs/FormDeleteBranch.Designer.cs
- GitUI/CommandsDialogs/FormDeleteBranch.cs
- GitUI/CommandsDialogs/FormDeleteBranch.resx
- GitUI/CommandsDialogs/FormPull.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ConfirmationsSettingsPage.cs
- GitUI/GitUICommands.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/BranchComboBox.Designer.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitDeleteBranchCmdTests.cs
Relates to #6183
- Apply the same design as for other updated dialogs
- Remove verbose "help" text, replaced with [?] button that links to [the docs](https://git-extensions-documentation.readthedocs.io/en/release-3.4/branches.html#delete-branch) (the link is currently broken, see: https://github.com/gitextensions/gitextensions/issues/8955)
- Remove nagging confirmations - this is NOT a data loss situation, local branches can be easily restored
- Set focus to the branches edit control
- manual
----
> Dialogs layout alignment - `FormDeleteBranch`

- GitCommands/CommitDataManager.cs
- GitCommands/FileHelper.cs
- GitCommands/Git/AheadBehindDataProvider.cs
- GitCommands/Git/Executable.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitCommands/Git/SystemEncodingReader.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/Editor/FileViewer.cs
- GitUI/OsShellUtil.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IExecutable.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
- UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs
- UnitTests/GitCommands.Tests/Git/AheadBehindDataProviderTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Fixes #6527
Fixes #8263
Fixes #8632
Closes #8906 as obsolete
Closes #8961 as obsolete
- Throw `ExternalOperationException` if a started process exits with a non-0 exit code or if the process printed output to `StandardError`
- Suppress this exception for commands whose errors are handled
- manual
- existing NUnit tests
- Build 3bed1c81024391ba2f58c2b005f915d6fac21260
----
> Throw on non-zero exit code and on stderror output

- GitUI/CommandsDialogs/FormFileHistory.Designer.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
See long term goals in #7598
- Refactor FileChanges -> RevisionGrid (the normal name for the control in other forms)
- Do not try to `--follow` for folders. Something like `Bin/` is OK, but `GitUI` will give too many files and too long command lines. (This could be solved in other ways but do not bother.)
Note that 3.5 does not follow folders (or Submodules) so not limiting functionality. History for folders is useless in 3.5 as well.
Note: There is no enforcing of using the ending "/" in the Advanced filter, manual input.
- Move detection of renamed files from FileHistory to RevisionGrid, to use the handling also for Advanced filters (with slightly more general rules).
Add an advanced filter like "\*\*/Rev\*Diff\*" to see that GitUI\CommandsDialogs\RevisionDiffControl.cs was renamed
---- …
> Rename detection for Advanced filter

- GitCommands/PathUtil.cs
- GitUI/Shells/BashShell.cs
Fixes #9353
not completely - but the regression from #8213
`git-bash.exe` cannot be used for the built-in console.
As I explained in https://github.com/gitextensions/gitextensions/issues/9353#issuecomment-881975596, `bash.exe` ignores the path to `git.exe` added by GE to `PATH`.
- `BashShell`: Try `git-bash.exe` first for stand-alone shell
- search also in the 64-bit-programs folder
- manual
- Build d4b3e13e80fd0f094fecd9f153f0fe135c4d4d09 (Dirty)
----
> Support `git-bash.exe` again

- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #9343
Check that submodule paths are not empty and unique.
This should already be the case, but non unique paths occurs in #9343 and should in a similar .ToDictionary() for the sidepanel.
The removed break in FormBrowse is not necessary - following submodules should be updated.
To be cherry-picked to release/3.5 after merge to master
Manual
----
> Do not allow duplicate submodule paths

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphSegment.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Follow up to #9335
See long term goals in #7598 (comment)
Artificial commits are added to the HEAD. If commits are filtered, HEAD may not appear.
This occurs both for files filtered in Browse and FileHistory.
Note that FileHistory for a file in HEAD would show Artificial, but not history for any other file.
This change inserts the artificial commits first if not added to the commits.
Also change the confusing diff message (especially when selecting artificial commits without changes).
Note that the first seen parent to HEAD could be queried, the artificial commits be inserted there. This adds another for a call that may delay display which is not worth it. 
~~Note: For filters where the file do exist in HEAD this is a minor regression, the Index is no longer connected to the head.~~
~~If …
> Show artificial commits also for filtered grid

- GitCommands/PathUtil.cs
- GitUI/Shells/BashShell.cs
#9416 for master
Fixes #9353
not completely - but the regression from #8213
`git-bash.exe` cannot be used for the built-in console.
As I explained in https://github.com/gitextensions/gitextensions/issues/9353#issuecomment-881975596, `bash.exe` ignores the path to `git.exe` added by GE to `PATH`.
- `BashShell`: Try `git-bash.exe` first for stand-alone shell
- search also in the 64-bit-programs folder
- manual
- Build e54cd4e7fd2df1ce5ad2525a95bac74d87b96f76
----
> BashShell: Try git-bash.exe first

- ResourceManager/CommitDataRenders/TabbedHeaderLabelFormatter.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataHeaderRendererIntegrationTests.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/TabbedHeaderLabelFormatterTests.cs
Fixes #9164
- Removed an expression that gives us an extra tab.
- Fixed tests.
- Used existing tests.
GIT 2.21.0.windows.1
Windows 10
This PR does not fix the submodule status here: [link](https://github.com/gitextensions/gitextensions/issues/9164#issuecomment-881846792).
----
> Fixed Commit info varying indents. Fixes #9164

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormLog.Designer.cs
- GitUI/HelperDialogs/FormChooseCommit.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusList.Designer.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Contributes to #7598
A few unrelated changes related to filtered commits
- From #9393 change the confusing diff message (especially when selecting artificial commits without changes).
- From #9393 squash! Use default value for ShowUncommittedChangesIfPossible
- Improve performance for GitModule.GetParents
git-rev-parse is faster than git-log
For me in GE it is about 0.18 s vs 0.30 s.
Also check input and cache results
The command will be used when calculating the Diff for filtered commits in a later PR.
- ToggleBetweenArtificialAndHeadCommits: Go to WorkTree if HEAD is hidden
Note: This has no effect until #9393 is merged as artificial commits are not shown
If HEAD is not visible (in a filtered view) nothing happens for Ctrl-< as there is nowhere to go
In this case go to WorkTree commit …
> ToggleBetweenArtificialAndHeadCommits: Go to WorkTree if HEAD is hidden

- GitCommands/Git/GitModule.cs
- GitCommands/Settings/AppSettings.cs
- GitCommands/Settings/ConfigFileSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/FormAvailableEncodings.cs
- GitUI/Editor/FileViewer.cs
Fixes #9395
- Use `Encoding.WebName` instead of `Encoding.HeaderName` in order to reduce conflicts (Japanese and Korean)
https://github.com/gitextensions/gitextensions/issues/9395#issuecomment-885231492
- Fill `ListAvailableEncodings` only with the first occurrence of a `WebName`
- manual
- Build 3cd5063e30b6f2c5b19e123954d51bdb3de5ec5e
----
> Improve handling of encodings with conflicting names

- GitCommands/RevisionReader.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/UserControls/FileStatusDiffCalculator.FileStatusDiffCalculatorInfo.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusList.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/GitRevision.cs
Contributes to #7598
Review commit by commit, could maybe be squashed before merge.
- Diff to actual parent in filtered grids
If the grid is filtered, the commit parents are rewritten to show the
displayed parent commit.
The diff in RevDiff should show the diff for the actual commit rather than
the diff to the previous node.
In FileHistory, this is not really a problem as the separate CommitInfo shows the diff for the current commit anyway, you cannot see custom diff for more than the selected file anyway.
- Diff: Avoid calculate HEAD
Optimization: HEAD is calculated in some situations (when selecting artificial commits, to present range-diff).
This is not necessary, the info is available in RevGrid
- Refactoring the diffCalculator reload handling (more info is added with the HEAD and …
> Diff to actual parent in filtered grids

- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
- IntegrationTests/UI.IntegrationTests/UI.IntegrationTests.csproj
- IntegrationTests/UI.IntegrationTests/UITest.cs
A few test changes to fix flaky tests
Integration tests fail after a clean, for instance ToggleBetweenArtificialAndHeadCommits_no_index_change.
In AppVeyor the tests time out.
Locally you get a popup
```
GitExtUtils.ExternalOperationException: fatal: not a git repository (or any of the parent directories): .git
---> System.Exception: fatal: not a git repository (or any of the parent directories): .git
--- End of inner exception stack trace ---
at void Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
at T Microsoft.VisualStudio.Threading.JoinableTask<T>.CompleteOnCurrentThread()
at T Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run<T>(Func<Task<T>> asyncMethod, JoinableTaskCreationOptions creationOptions) x 2
at int …
```
> Attempt to fix tests failure for MEF

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
Followup to #9393
Inserting artificial commits first if HEAD was not added to the grid was added in #9393.
In some situations the grid would not be refreshed correctly, requiring a manual scroll.
This normally would occur for bigger repos only.
When working with the PR, I could not get a stable repro and could not address it.
This is a follow up to invalidate the row cache properly to refresh the graph in the grid.
The normal commits are being displayed while the git-log output is created, so initially the artificial commits are not shown.
After a few seconds the graph is updated as below (that would require a scroll before).
manual
----
> Artificial commits: Invalidate rowcache when inserting

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Shells/ShellProvider.cs
Fixes #9471
ConEmuStartInfo.ConsoleProcessCommandLine cannot be assigned with null.
It seems like #8213 changes does not assign ExecutableCommandLine in all situations.
To be cherry-picked to 3.5
review
----
> ConEmu require ExecutableCommandLine to be set

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/FilterToolBarTests.cs
> Reset revision filter when switching repos

- .github/PULL_REQUEST_TEMPLATE.md
Add PR template section about merge strategy, setting squash merge as default.
Manual
----
> GitHub PR template - merge strategies

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/Dashboard.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.Designer.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesListController.cs
- GitUI/Translation/English.xlf
Fixes #9302
- A new searchbar for filtering the recent / favorite repositories
- Pressing return will open the first search result
- The default focus has been changed to focus the search textbox once the dashboard gets visible
-  This allows immediate search when opening gitextensions or when going back (strg+w) to the dashboard
- A new interface has been added for filtering repositories
- Manual tests:
- Search for repo, press return
- Search for random text (no search results), press return
- Search for non existing repo, press return
- Windows 10
- UI Scaling 100%
----
> Recent repo search

- GitExtensions/Program.cs
See https://github.com/gitextensions/gitextensions/issues/9464#issuecomment-898202703
CkecklistSettings at startup was not solved if the "autosolver" was successful (see `AutoSolveAllSettings()` for settings like Git).
For settings without an autosolve like SSH the page was not shown.
The settings page as seen in the issue is shown after startup.
Note that some paths in %windir% are not checked correctly (see #9355), the user must uncheck "Check at startup" manually.
To be cherry picked to 3.5.
manual
----
> Show ChecklistSettings also for settings without an autosolver

- GitUI/CommandsDialogs/FormDiff.cs
- GitUI/CommandsDialogs/FormLog.cs
- GitUI/UserControls/CommitDiff.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusList.cs
Followup to regression in #9426 (in master only)
Second part of https://github.com/gitextensions/gitextensions/pull/9393#issuecomment-896725634
Function GetActualRevision was not set in CommitDiff form, causing a NRE
Manual
----
> SetDiff: Init for CommitDiff

- GitCommands/FileHelper.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/SystemEncodingReader.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/Script/ScriptRunner.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/GitFlow/GitFlowForm.cs
- Plugins/Statistics/GitImpact/ImpactLoader.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Follow up to #9056, some discussions in #9476 too
* Execution: Adjust use of exit status, alloutput
Review that stderr (included in AllOutput) is not included in parsing of output data
* GetOutput only to be used where exit code is 0 and no error output
* GetOutputlines() removed, all callsites hanged on the call anyway.
Replace calls with throwOnErrorOutput:false with Execute()
Parse only StandardOutput for the replaced calls,
also where throwOnErrorOutput:false was set before.
manual
----
> Execution interface cleanup

- GitUI/CommitInfo/CommitInfo.cs
The direct cause of #9440 as it was submitted, required for a general solution too.
This is required to be able to add cancellable Git commands (at least to see the effect...).
#9405 407928a20cb395d846c6b6c07b00f102aaad199e added `ThreadHelper.JoinPendingOperations()` in Dispose for CommitInfo.
This will cause Dispose in the control to await any tasks started in the application, not just the tasks in this control.
There may be some cancellation tokens required in the existing tasks, I have not seen any obvious candidates.
For now I propose to remove the join
There are tests for this.
----
> CommitDiff: Do not Join() in Dispose()

- GitUI/CommandsDialogs/FormClone.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
- contributors.txt
Fixes #9520
- Re-use the PathUtil.CanBeGitURL when checking parts of the string rather than only looking for a valid URL.
Clipboard had to contain a valid URL, not a valid Git URL.
This meant that urls like 'git@github.com:gitextensions/gitextensions.git' were not pulled from the clipboard.
URL loaded from clipboard
- Manual test
- 
- 
- GIT 2.33.0.windows.1
- Windows 10
----
> Fix Clone URL Population

- GitUI/BranchTreePanel/ContextMenu/MenuItemsGenerator.cs
- GitUI/BranchTreePanel/RepoObjectsTree.LocalBranchNode.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
Fixes #8599
- Added listener for F2 key in RepoObjetsTree that fired the branch rename dialog.
- Unit tests (maybe). I think a some refactoring of the existing code is required to cover the added code with unit tests.
- Change de hard coded F2 with the configured key in `HotkeySettingsManager`.
- Add the configured hot key text to the context menu item.
- Manual
- GIT 2.29.2.windows.3
- Windows 10.0.17763.0
----
> Implemented F2 rename branch in RepoObjectsTree.

- GitCommands/Git/GitModule.cs
- GitUI/GitUIExtensions.cs
Follow up to #8923 
#8923 changed the "get patch" routines to be async, except for git-range-diff.
git-range-diff can take a long time (cubic to commits) and before this PR the Git command ran to completion.
On my home PC this takes about 25s, on the (newer) work PC with viruses I assume this will take several minutes.
Note: This is related to #9522, the Executable() should also have a cancellation token so the Git command is actually cancelled too.
I expect that that PR is merged after this, will add it there.
- Select commits in branches master and release/3.5
- Select range-diff (in the bottom)
- Select another file, notice that the FileViewer is updated immediately
---- …
> GetRangeDiff() should be Async

- GitCommands/Git/GitModule.cs
- GitCommands/Settings/ConfigFileSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigSettingsPage.cs
- GitUI/Editor/FileViewer.cs
ConfigFileSettings class is complex. I would like to simplify it.
- Take a general approach
- Clearer implementation
- unit tests
- manually
- Build 008ad8781cdbc7861fdc7020bdb91a15c9b13e0b
- .NET 5.0.9
----
> Remove CorePath class

- ResourceManager/TranslatedStrings.cs
Relates to https://github.com/axuno/SmartFormat/issues/192.
Our original implementations were create against SmartFormat.NET pre-dating v2.0.0. In v2.5.0 the default error action was changed to ThrowError. 
An attempt to use the Russian translation would fail with the following (likely true for other translations):
```
SmartFormat.Core.Formatting.FormattingException
HResult=0x80131500
Message=Error parsing format string: Invalid number of plural parameters at 17
{0:Child|Children}
-----------------^
Source=SmartFormat
StackTrace:
at SmartFormat.SmartFormatter.FormatError(FormatItem errorItem, Exception innerException, Int32 startIndex, FormattingInfo formattingInfo)
at SmartFormat.SmartFormatter.Format(FormattingInfo formattingInfo)
at SmartFormat.SmartFormatter.Format(FormatDetails …
```
> Reinstate SmartFormat legacy error handling

- GitUI/CommandsDialogs/FormDeleteRemoteBranch.Designer.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.resx
- GitUI/Translation/English.xlf
Relates to #6183
* Apply the same design as for other updated dialogs
* Remove verbose "help" text, replaced with [?] button that links to the docs
* Set focus to the branches edit control
- manual
----
> Dialogs layout alignment - `FormDeleteRemoteBranch`

- UnitTests/CommonTestUtils/MemorySettings.cs
- UnitTests/CommonTestUtils/MemorySettingsCache.cs
- UnitTests/GitUI.Tests/SplitterManagerTest.cs
Resolves #8745
Resolves #9000
Resolves #9089
(cherry picked from commit 1d608481ddb56dd24c3fc5aa15fd93bce5c75980 / https://github.com/gitextensions/gitextensions/pull/9106)
> Restore splitter persistence

- GitCommands/CustomDiffMergeToolCache.cs
- GitCommands/Git/Executable.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Submodules/SubmoduleStatusProvider.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CustomDiffMergeToolProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IProcess.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
Fixes #9440
#9440 is mostly closed in #9505, this handles a few effects
Closes #9501
Long running process like "git difftool --tool-help" are currently never cancelled, they must run to exit.
I have seen this command require over a minute at work.
After #9505, there is no major problem due to this, it is possible to open the console and close GE quickly after opening, but it could be a potential issue.
- CancellationToken for Executable
Possibility to cancel processes, not hanging until closing.
There may be other ways to do this too.
- CancellationToken handling for CustomDiffMergeTools
Runs in the background and was never cancelled before. This add cancellation token handling and also cancels the Git command.
A few other cleanups, review commit by commit
Manual
* Start Settings to clear …
> Cancellation for Executable

- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #9517
A regression introduced in #8489 that resets filters when repos are switched.
However it didn't account for the "Show current branch" setting.
> fix: Show current branch resets when switch repos

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeController.cs
- GitUI/Editor/FileViewer.cs
- GitUI/Editor/FileViewerInternal.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/UserControls/BlameControl.cs
Part of #7598
Closes #9435
Closes #9437 
- RevFileTree: Blame instead of View
Show blame for object type blobs (files), as is available in FileHistory.
Note that object type commit (submodules) are shown as text, as before.
It is possible to toggle the view to show file contents, as before.
In FileHistory the commit info is available in a header. This is excluded in RevFileTree. The info for the selected commit can be seen in Commit, Diff tabs, overview is available in tooltip for otyher commits.
This could be configurable.
- RevDiff: HotKey to view FileTree
A menu command existed to view the file, this as a hotkey.
Note that `T` was selected as key, `F` is to be used to add the filepath to the Advanced filter in the grid.
- RevDiff: `B` to view Blame instead of Diff
Note that this is …
> RevFileTree: Blame instead of View

- GitCommands/Git/GitBlame.cs
- GitUI/UserControls/BlameControl.cs
- UnitTests/GitCommands.Tests/Git/GitBlameCommitTests.cs
- UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
Fixes #9168
I used GitRevisionSummaryBuilder.BuildSummary on the blame commit's summary based on the approach from Revision Grid.
Also added a test to cover this truncation.
See the [PR to sign the contributors.txt](https://github.com/gitextensions/gitextensions/pull/9518).
- added a unit test to cover the truncation
- manually confirmed the UI changes
- Git Extensions 3.5.3.12551
- Build 00604a59a673142a3d34a22aa657466a922977f3
- Git 2.33.0.windows.1
----
> Truncate tooltips for blame commit long summary

- GitCommands/Git/GitModule.cs
- GitUI/GitUIExtensions.cs
- ResourceManager/LocalizationHelpers.cs
Fixes #9560 (first two parts, but third is for troubleshooting)
- Check if the submodule directory exists before executing git-diff (as done for the other commands)
- Cancellation checks in ViewChanges
Manual
----
> Check that directory exists before running submodule command

- GitCommands/CommitDataManager.cs
- GitCommands/FileHelper.cs
- GitCommands/Git/AheadBehindDataProvider.cs
- GitCommands/Git/Executable.cs
- GitCommands/Git/ExecutableExtensions.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/SubmoduleHelpers.cs
- GitCommands/Git/SystemEncodingReader.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/Editor/FileViewer.cs
- GitUI/OsShellUtil.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/DeleteUnusedBranches/DeleteUnusedBranchesForm.cs
- Plugins/GitFlow/GitFlowForm.cs
- Plugins/GitUIPluginInterfaces/IExecutable.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/CommonTestUtils/MockExecutable.cs
- UnitTests/GitCommands.Tests/Config/ConfigFileTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Submodules/SubmoduleStatusProviderTests.cs
Fixes #9462 
Replaces #9489 (no changes at PR submit). @mstv has been missing a few weeks...
When approved, will rename the remaining throwOnErrorOutput arguments (that was added in #9056) after approval https://github.com/gitextensions/gitextensions/pull/9489#discussion_r704691119
See #9489 for further PR explanation
Only throw on error exit, not on output in stderror.
Manual
----
> Do not throw if process exits with 0

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/ToolStripEx.cs
Show toolbar grips. The grips are disabled, the toolbars remain immovable.
> Show toolbar grips

- GitExtUtils/GitUI/Theming/BrushScope.cs
- GitExtUtils/GitUI/Theming/TabControlPaintContext.cs
- GitUI/Editor/Diff/DiffViewerLineNumberControl.cs
- GitUI/Interops/Gdi32/DeleteObject.cs
- GitUI/Theming/Renderers/EditRenderer.cs
- GitUI/Theming/SystemBrushesCache.cs
- GitUI/Theming/Win32ThemeHooks.cs
Fixes #9429
1. Return brush wrapper in situations when brush consumer is not certain whether it should dispose the brush.
wrapper.Dispose method will not touch the underlying brush if it is system brush.
2. Cache the native brushes returned by Win32 GetSysColorBrush override
3. Render text input backround explicitly, because 2. somehow breaks default system rendering.
- run GitExtensions
- scroll revision grid back and forth, click on different revisions
- observe GDI objects count using [GDIView](https://www.nirsoft.net/utils/gdi_handles.html) (thank you @pmiossec)
Windows 10
- Rebase merge
----
> Fix leaking brushes

- GitCommands/AppTitleGenerator.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormCommandlineHelp.resx
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeController.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs
- GitUI/GitUICommands.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockAppTitleGenerator.cs
- UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
Closes #7598
Based on #9424.
This PR could be split in several PRs, submitted as is to describe the "initial completion" of #7598 and describe what could be improved.
I consider this to be ready for review, but may tweak the functionality until #9424 is merged.
* See screenshots below
* RevDiff and FileTree selects filtered files by default when changing commits, the filtered file is "followed" when switching commits (unless another file is selected and it exists in the next commit, as already implemented).
* Some refactoring to allow for new functionality separated.
Future:
* Present active filters better. Some way to deactivate filters in a simple way. (Some discussion in #7598).
* A few tests could be added (some added)
Show path filter in title (last part is due to Debug build, …
> Blame/filter in Browse, replace formfilehistory

- GitUI/CommitInfo/CommitInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
We're endlessly spamming TaskCanceledException exceptions when `_backgroundQueue` is empty while executing
```cs
await _backgroundQueue.DequeueAsync(linkedCancellation.Token)
```
Add a check for an empty queue to avoid unnecessary attempts to dequeue, and as a result unnecessary timeout exceptions.
Try to guess at which point I added the check 😄
> Reduce amount of TaskCanceledException

- GitUI/CommandsDialogs/FormBrowse.cs
Addendum to #9106
Restore the splitter positions when we load the form irrespective of the current view (the dashboard or the repo view).
- manual
> Move the init logic from OnLoad to InternalInitialize

- GitUI/CommandsDialogs/SettingsDialog/Pages/FormFixHome.cs
Fixes #9573
Try reading the .gitconfig file at startup as File.Exists() will not catch access changes.
For me this increases the startup time of the application with about 0.1 ms (normally either 0.0 -> 0.1 ms or 0.1 -> 0.2 ms) in the normal case returning false (measured with Stopwatch).
I have a SSD, I would expect this is similar for a traditional HD as the added OH is more for exception handling then I/O.
Manual, see the issue
----
> Select HOME where .gitconfig is accessible first

- BugReporter/BugReportForm.cs
- BugReporter/ErrorReportMarkDownBodyBuilder.cs
- BugReporter/GitHubUrlBuilder.cs
- BugReporter/Program.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/NBugReports/BugReportInvoker.cs
- IntegrationTests/BugReporter.IntegrationTests/BugReportFormTests.cs
- UnitTests/GitUI.Tests/NBugReports/BugReportInvokerTests.cs
Debug info for #9560 etc , needed after #9056
* Fix regression: Separated BugReporter and #9056 was done in separate branches.
When a Git command exits with errors, info about current directory, arguments etc is collected and presented in a popup.
This info is now also included in rthe NBug report.
Note: StandardError should be included as well as in Git Command Log, this a separate PR.
The popup is unchanged:
A cut exception below (as well as modified formatting), adding the three lines below `## Error Details`
```
Command: C:\Program Files\Git\bin\git.exe
Arguments: -c color.ui=never -c diff.submodule=short -c diff.noprefix=false -c diff.mnemonicprefix=false -c diff.ignoreSubmodules=none -c core.safecrlf=false diff --find-renames --find-copies --name-status …
```
> NBug: Include GE specific exception info

- GitCommands/Git/Commands/GitCommandHelpers.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
Regression from #9678  8066c59a7b286f5b791d29cfee8c2209bb27b6db
Set path in posix format for Git
Added testcase
----
> Reset another branch to here path format

- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/HelperDialogs/FormChooseCommit.cs
Because a commit should be selected in the history of the current branch, display only this current branch to make the selection easier.
- Manual
- Build 9f8c00c90d7b232b5a5271ff87e9cdb880ef44b9 (Dirty)
- .NET 5.0.11
----
> `Rebase --onto`: Display only the current branch to make selection easier

- GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
- UnitTests/GitUI.Tests/Editor/RichTextBoxXhtmlSupportExtensionTests.cs
Fixes #9668
- use `|||` instead of `#` to separate link text and link, because both potentially could contain hash symbol `#`
- move out hardcoded separator to a variable, so it could be easily customized if needed
Incorrect links that contain `#` symbol in the text.
Native behaviour.
- Manual
- Unit tests
- GIT 2.33.1.windows.1
- Windows 10.0.19043
----
> Change Revision Links separator (#9668)

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes nothing, just improve UX in DEBUG inside Visual Studio
- Behavior is not changed, the exception is already try/catched
- This check just prevent the exception to be raised which is really boring when debugging the application
- In debug in VS, switch the opened repository
- Build e61325736ad63a00a31f3193bd91a9e946f2b810
- Git 2.28.0.windows.1 (recommended: 2.33.0 or later)
- .NET 5.0.11
> RevisionGridControl: prevent exception when switching repository

- GitExtensions/Properties/launchSettings.json
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
This originates in #9553 or similar that reworked the FormBrowse and filter init logic.
Except when starting the first time directly to a repo, the title was set to the previous repo as it used info not yet updated.
When starting from Dashboard, the path was empty.
This operation is reading refs/ normally, so not delaying the operation.
(In another PR, there is a an optimization swapping the other way...)
In addition add start to Dashboard a debug profile to simplify testing starting from Dashboard.
Manual
----
> AppTitle was set to previous repo branch

- appveyor.yml
Avoid the warnings in Appveyor, that confuses users too.
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/41525423#L74
Appveyor build
----
> appveyor: avoid warnings about crlf

- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Separated from #9729 (and #9728) as #9729 may require some more time.
* Adjust the paths for FallbackFollowedFile by removing quotes.
As before, user specific entries with wildcards and multiple files cannot
be handled.
* Update FallbackFollowedFile in RevDiff and FileHistory also when changed
in the UI filter (not just from the tab menus).
* Do not update filters by nullifying the pathfilters when switching repos.
This triggers additional FilterChanged events.
As a bonus, the pathfilter info is available (disabled) in the filter.
Could be useful if switching to a new worktree or when switching back to the
old repo.
Manual
---- …
> PathFilter: Set FallbackFollowedFile at every filter update

- Directory.Build.props
- GitExtensions/GitExtensions.csproj
- GitExtensions/Project.Publish.targets
- GitExtensions/app.config
- Packages.props
- Setup/Config.wxi
- Setup/EnableUpgrades.wxi
- Setup/Product.wxs
- appveyor.yml
- scripts/native.proj
⚠️ DO NOT SQUASH
- Resurrecting https://github.com/gitextensions/gitextensions/pull/9458 proposed by @GintasS.
- Update publish location for native artifacts
- Remove unnecessary files from the published components (e.g. xml, pdbs, etc.)
- A major clean up of the MSI definition, including
* remove all .NET Framework and .NET Standard related references
* remove all localised resources
* rebuild the component list from the published files
- Update the installer to require full uninstall before install
- Rework how the setup project is built reusing the older version of MSBuild and .NET Framework v3.5
- Bump the version to 4.0.0
* Building and inspecting the content of the generated zip and msi
* Comparing the content of the generated zip and msi against the published counterparts
* Manual …
> Generate .NET installer

- GitCommands/Settings/AppSettings.cs
- GitExtensions/GitExtensions.csproj
An addendum to #9704.
- The .NET bootstrap created a .NET Framework entry point. This tricks the debugger, and it doesn't see the app as a .NET process, and, thus, unable to hit any breakpoints. 
To mitigate this, only apply the bootstrap to the Release configuration.
- Correct path to our executable under DotnetRuntimeBootstrapper.
Resolves #9743
> Make the Debug build debuggable

- GitCommands/DiffMergeTools/DiffMergeToolConfigurationManager.cs
- GitCommands/Git/Commands/GitCommandHelpers.cs
- GitCommands/Git/Executable.cs
- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitVersion.cs
- GitCommands/Git/Tag/GitTagController.cs
- GitCommands/Logging/CommandLog.cs
- GitCommands/PathUtil.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormApplyPatch.cs
- GitUI/CommandsDialogs/FormClone.cs
- GitUI/CommandsDialogs/FormFormatPatch.cs
- GitUI/CommandsDialogs/FormMergeBranch.cs
- GitUI/CommandsDialogs/FormPush.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/CommandsDialogs/RepoHosting/ForkAndCloneForm.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ChecklistSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitSettingsPage.Designer.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
- GitUI/HelperDialogs/FormProcess.cs
- GitUI/HelperDialogs/FormResetAnotherBranch.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/IGitModule.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
Fixes #8172
For Git repos stored in WSL2 directories, execute the Git executable in WSL
where possible to improve performance. WSL Git commands are several
times faster when executed by the WSL Git executable instead of the
Git Extensions native (Windows) executable.
The paths internal to Git Extensions are always native (Windows).
Using the WSL executable requires that paths provided to WSL Git
are adjusted from/to Git Extensions native/internal (Windows) format to WSL, like
\\wsl$\Ubunto\repo to /repo and c:\repo to /mnt/c/repo.
The Git Extensions native (Windows) Git executable is still used in some situations:
* All handling and settings related to Git in Settings. This includes
display of Git version as well.
However, if the Git version is too old to be supported, the GitVersion …
> Support Git in WSL

- GitCommands/Git/Commands/GitCommandHelpers.cs
Regression in #9702
Tests fail with Debug.Assert
Note: Other tests fail locally due to other changes in master.
```
Message: 
System.TypeInitializationException : The type initializer for 'GitUI.Theming.ThemeModule' threw an exception.
----> Microsoft.VisualStudio.TestPlatform.TestHost.DebugAssertException : Method Debug.Fail failed with 'C:\dev\gc\gitextensions_4\artifacts\Debug\bin\tests\IntegrationTests\UI.IntegrationTests\net5.0-windows\testhost.exe must point to GitExtensions.exe
', and was translated to Microsoft.VisualStudio.TestPlatform.TestHost.DebugAssertException to avoid terminating the process hosting the test.
Stack Trace: 
ThemeModule.get_IsDarkTheme() line 17
GitExtensionsForm.ctor(Boolean enablePositionRestore) line 43
GitModuleForm.ctor(GitUICommands commands, Boolean …
```
> Adjust Debug.Assert for tests

- GitCommands/Settings/AppSettings.cs
Follow up to #9747
Allow that the translation app is run in debug, not asserting.
Manual
----
> Allow running TranslationApp in Debug

- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterChangedEventArgs.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.Designer.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Command.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
A follow up to #7598
Visualize if there are filters available in the advanced filter.
Add tooltip with the current filter
Exception occurred
Ctrl-shift-F to disable the current filters (similar to what is done when switching repos)
Edi: Removed one commit that was moved to #9729 
Manual
Adding TODO similar for GetRevisionFilter for FilterSummary
This is related to some other changes that should go into 4.0, so that should be done later.
----
> RevisionFilter: Indicate filters with button state and tooltip

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
@RussKie has refactored FormBrowse init and filter handling recently.
After this handling some logic like InternalInitialize() was running several times.
This included a few Git commands too, delaying the startup slightly.
There are some test instabilities for FormBrowse, this is an attempt to at least improve investigation.
I initially got som stability issues with this change when testing in isolation but this works better when restructuring commits.
`'Loading Revisions' didn't finish in 100 iterations` can still occur
There are tests for this already
Rebase merge
----
> FormBrowse init optimizations

- GitCommands/Settings/AppSettings.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Workaround for #9750 
Ignoring the two tests that seem to cause the three issues described in #9750 in Release mode, still running in Debug.
(I have done some attempts to fix them, did not succeed.)
Built on AppVeyor a couple of times.
Of course, there can be issues with other tests too that need to be ignored unless they can be changed
----
> Tests: Ignore flaky UI tests

- GitUI/UserControls/FileStatusList.cs
Discussed in #9703
For FileStatusList, can have one or more groups
- Show number of changes in a group first in the group name. Change for all group headers, except RangeDiff.
- Collapse groups RevDiff groups if they do not fulfill the following:
- All other than comparing branches with a common BASE (the only that has more than two groups, currently five)
- First group
- 5 or less files
@mstv wanted the last part to expand groups if they occupy less than 80%, but I want to keep it simple.
Manual
----
> RevDiff: Count number of changed files per group

- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitorState.cs
Fixes #9615
See also #9700 for 3.5, with the essential correction (most of the changes was done first to find the problem).
If If the monitor was inactivated while a status command was running
(minimizing/restoring the app, start a modal dialog) the current command
is canceled to give the latest data.
lock() will ensure that more than one "active" command is not running.
However, one control variable was reset also if the command was canceled
which allowed the canceled command to be followed by another.
Also changed to not request a new status command if a command is already
running. (current status should be good enough, if there are pending
changes they will be requested later).
Some refactoring and cleanups.
Manual testing
I agree that the maintainer squash merge this PR (if the commit …
> GitStatusMonitor could start multiple commands

- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusList.cs
Suggested in #9720, required #9718 too
RangeDiff shows the differences between two branches, identifying and comparing commits.
This was previously in a separate group.
This PR discards the second group and moves it into the First(A)->Second(B) goup.
The RangeDiff is always sorted last.
Note: The RangeDiff always happened to be sorted last also without the sort changes, that could be replaced with a comment.
But this could accidentally break. (A test could be added eventually.)
Manual
----
> RevDiff: Move RangeDiff to A->B group

- GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
Fixes #9726
- Let `RichTextBoxXhtmlSupportExtension.GetPlainText` ignore links, which are returned multiple times (string length of link?)
see issue
- manual
- Build d71a4f5344ecf5a5f119b4c9e18485de6366eeab
- Git 2.33.1.windows.1
- .NET 5.0.12
----
> Let RTB extension `GetPlainText` ignore links

- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitVersion.cs
Late review comments for #9680/11911493064a525045f3defa55a740e5796226dd from @mstv
No functionality change, just rename and a comment
Manual
----
> GitVersion: Remove support for obsolete versions

- GitCommands/Git/GitModule.cs
- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitUI/BranchTreePanel/RepoObjectsTree.BranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.RemoteBranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/BuildReportTabPageExtension.cs
- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitCommands.Tests/Remote/ConfigFileRemoteSettingsManagerTests.cs
Regression in master
Based on #9729 (may be separated).
Ready for review (first commit is not to be considered) even if draft.
The structuring of FormBrowse in master has changed so the left panel is initiated both at creation and at  PostRepositoryChanged.
This could add a couple of seconds to the startup. (Especially at work with virus programs.)
Also eliminate a few Git calls when starting to Dashboard.
(More confusing than a problem.)
Manual
----
> LeftPanel was initiated twice at startup

- GitCommands/Settings/AppSettings.cs
- GitExtensions/GitExtensions.csproj
- Packages.props
- contributors.txt
Fixes #9766
- Update DotnetRuntimeBootstrapper to latest version
- Revert the workaround for getting application path (it should now resolve correctly)
- Remove condition on package reference (bootstrapper is now only generated on publish, not on build)
- I tested it manually :)
- GIT 2.31.1.windows.1
- Windows 10.0.19043.1348
----
> Update .NET Runtime Bootstrapper

- GitCommands/Git/GitModule.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
Regression from #9720/2119320c3401b59c8883f52b06a230a756fb4b18
Handle artificial commits in range-diff as HEAD
This was done in FileStatusDiffCalculator.cs before #9720
Manual
----
> range-diff: Handle artificial commits

- GitCommands/Git/GitModule.cs
- GitCommands/PathUtil.cs
- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitCommands/Settings/GitExtSettingsCache.cs
- GitUI/CommandsDialogs/FormPush.cs
A few follow up from #9702 
A few a follow up related to WSL Git.
* Settings could not be read from \\wsl$
The URI is invalid, why the path has to be read with a StreamReader.
This caused various issues like remotes could not be disabled
This is not related to WSL Git, it also occurs if Windows Git is used.
This is one reason why insiders Windows builds also supports `wsl.localhost`
(\\wsl$ paths will be required to utilize wsl git. This is a feature but must be documented.)
This problem was primarily seen when deactivating remotes, an exception occurred (as a settings file were not refreshed).
* WSL: Remotes for filepaths could not be saved
Paths must be manipulated to match Git executable.
* WSL: Git internal paths were incorrectly resolved
Affected Remote mostly
* WSL: force-push was …
> Settings could not be read from \\wsl$

- GitExtensions/Program.cs
- GitUI/Theming/LocalHook.cs
- GitUI/Theming/ThemeLoader.cs
- GitUI/Theming/ThemeModule.cs
- Packages.props
- UnitTests/GitUI.Tests/Theming/ThemeLoaderTests.cs
Fixes #9782
Restore the possibility to change application colors from .css files.
While the theme handling is unfortunately disabled after .NET5, the possibility to set colors like branches was available before theming and is expected by users.
@NikolayXHD suggested that ExCSS is removed and replaced with regex parsing, to get rid of a dependency and get parse errors (that must be ignored with ExCSS >= 3).
This is not done due to simplicity, easier to fix this than to reimplement.  (If the implementation is limited to allow only single line comments, one command per line etc, it would be simpler and maybe feasible.)
Weird mix of switch local-remote colors and colorblind
Renabled and adapted tests
---- …
> Load app colors from CSS themes

- GitUI/BranchTreePanel/RepoObjectsTree.BranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.RemoteBranchTree.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/FilteredGitRefsProvider.cs
- Plugins/GitUIPluginInterfaces/GitUIEventArgs.cs
- Plugins/GitUIPluginInterfaces/IFilteredGitRefsProvider.cs
- UnitTests/GitCommands.Tests/Git/FilteredGitRefsProviderTests.cs
requires #9734
In master, GitRefs() run 13+2 times during the startup when 1+2 would be sufficient. While some of these are due to a change in master handled in #9729, there are 9+1 in 3.5 (sidepanel many of them).
At work each of these may require several hundred ms. Even if they to some extent can run in parallel, the startuptime may increase with several seconds.
After #9734 most GitRef() calls are done from PostRepositoryChanged and the call can be shared.
Timing is when running in the debugger, much different from normal operation (except Git command running  time).
From #9734 (see that PR for current master).
This contains a few commands running after the commands seen above.
Test is added
---- …
> Share GitRef() at startup

- GitUI/Themes/README.md
Followup to #9784
README update
[Wiki page on Dark Theme](https://github.com/gitextensions/gitextensions/wiki/Dark-Theme) updated too.
Manual
----
> Theming readme update

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GeneralSettingsPage.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/IndexWatcher.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Remove the specific setting for the index watcher, use the GitStatusMonitor
settings instead. UseFastChecks hardly adds any overhead, it adds
FileSystemWatcher to index and refs (GitStatusMonitor has a separate
watcher on index).
If the file system is changed, the top-left refresh button becomes red.
(As well as avoiding refreshing the grid in some situations, may not be working though.)
UseFastChecks was visible in Performance settings and expected by
users (and occasionally maintainers) to make a difference.
Sometimes the setting is mixed up with the GitStatusMonitor setting
that can make a difference (as git-status requires a lot of resources,
not FileSystemWatcher).
Manual
----
:black_nib: I contribute …
> Replace AppSettings.UseFastChecks with ShowGitStatusInBrowseToolbar

- GitUI/GitUICommands.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
#9445 uses the FormBrowse for displaying file history
(by default, configurable with AppSettings.UseBrowseForFileHistory).
FormFileHistory is deprecated.
However, command line invocation of filehistory still used FormFileHistory,
not using the setting. This is needed for all 'external' use like
Explorer and Visual Studio.
FormBrowse with path filter is opened instead of FormFileHistory
Tests are adopted to run with FormFileHistory, same as today.
There are other tests already for FormBrowse.
----
> FileHistory: Launch commandline in FormBrowse

- GitExtUtils/GitUI/Theming/ThemeFix.cs
- GitExtUtils/GitUI/ToolStripExProfessionalRenderer.cs
- GitExtUtils/GitUI/ToolStripExSystemRenderer.cs
- GitExtUtils/GitUI/ToolStripExThemeAwareRenderer.cs
- GitExtUtils/GitUI/ToolStripExtensions.cs
- GitUI/UserControls/ToolStripEx.cs
- ResourceManager/GitExtensionsFormBase.cs
Achieve the goal of #9608 without unintentionally making `ToolStripEx` use `ProfessionalRenderer` instead of `SystemRenderer`
In particular, this makes `FormBrowse` toolbars selected buttons be highlighted properly, as before.
after #9608
before #9608 and after this PR
> make ToolStripEx use ToolStripExSystemRenderer by default as before #9608

- GitExtUtils/GitUI/Theming/AppColorDefaults.cs
- GitExtUtils/GitUI/Theming/Theme.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/ColorsSettingsPageController.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/ColorsSettings/IColorsSettingsPage.cs
- GitUI/Themes/bright.css
- GitUI/Themes/dark.css
- GitUI/Themes/darksilver.css
- GitUI/Theming/ThemeModule.cs
- UnitTests/GitUI.Tests/CommandsDialogs/SettingsDialog/Pages/ColorsPageSettingsPageControllerTests.cs
Default theme uses hardoded color values. Add hardcoded color values for colorblind variation as well.
Tested manually
ColorSettingsPage logic to not disable colorblind checkbox is covered by unit test
Windows 10
----
> Support colorblind variation of default theme

- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
Follow up to #9720 
The diffs shown in Diff Tab when multi-selecting commits is slightly updated in master, missed in #9720 
Also, a lot of strings used with TranslatedStrings were translated twice.
No simple way what I see to hardcode this in TranslationApp, so changing this by renaming controls.
Compiling
----
> Updated tooltip for ShowDiffForAllParents

- GitCommands/PathUtil.cs
- GitCommands/Remotes/ConfigFileRemoteSettingsManager.cs
- GitCommands/Settings/FileSettingsCache.cs
- GitUI/CommandsDialogs/BrowseDialog/GitStatusMonitor.cs
- UnitTests/GitCommands.Tests/Helpers/PathUtilTest.cs
The FileSystemWatcher is not reporting changes for WSL
https://github.com/microsoft/WSL/issues/4581
GitStatusMonitor was not updated as well as deactivating a remote caused a BugReporter popup.
Other issues could be that the settings file were incorrectly overwritten. (That already exist in Windows, maybe worse.)
A few related changes too.
Easiest to review commit by commit
A few tests updated.
- To be decided later.
----
> FileSystemWatcher is not working for \\wsl$

- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CustomDiffMergeToolProvider.cs
Related to the listing of all diff and mergetools in #8700.
The loading of tools takes considerable time (10 s or so) and a delay was added to not interfere with diffs etc after startup.
That time was set to 15s (for difftools, mergetools has 0.5s after first time opening ResolveConflicts),
which is much longer than needed.
The command (including Git) is also fully async cancelable in master.
The time to load a the linux repo has decreased from about 8s to about 4s for me,
so it should be OK to decrease the load time from 15s to 8s.
Manual
----
> Decrease CustomDiffMergeToolProvider start delay

- GitUI/CommandsDialogs/FormSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.resx
- GitUI/Translation/English.xlf
Part of #9796
Blame settings is currently only in FileHistory. They are a little hidden there, hard to find them.
With master Blame is also in Browse so they need to be accessible.
Another option would have been to add them to the FileViewer context menu.
They would have to be added last in the menu to avoid messing with the FileViewer modes and the logic would have to be added to the blame control too.
Also if that is considered, it is expected to have this in Settings.
Designer opened, tab order tested
Unchanged
Manual
----
> Add Blame Settings page

- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.Designer.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
Fixes #4642
Fixes #9548
Fixes #7354
(This is really initiated by looking at documentation, issues are found later.)
ShowSimplifyByDecoration has been incorrectly set as dependent of
Branches filter (at least since 2.51). This is an independent revision filter.
https://git-scm.com/docs/git-log#Documentation/git-log.txt---simplify-by-decoration
This PR disconnects the option from Branches.
The implementation can probaly be done better, this is just better than what is.
Enabling the option shows the commits with branches/tags only
Tooltip when active
Manual
----
> ShowSimplifyByDecoration: Not dependent on branch filter

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/InteractiveGitActionControl.cs
git-ls-files is executed every time GE is reactivated, to determine if "InTheMiddleOfAMerge is to be displayed.
If this fails, there is nothing wrong with GE (and really not Git), no interest to throw a popup for the user.
This is especially annoying with WSL. If the Linux VM is busy will WSL occasionally time out and you get the popup regularily.
After this command, the risk for timeouts is lower, the user will get notification when actually performing actions.
Manual
----
> Do not report Git error for a command seemingly executed in the background

- GitUI/CommandsDialogs/SettingsDialog/Pages/BlameViewerSettingsPage.Designer.cs
Add scaling to checkboxes
Settings added in #9801/d6bfff8cb434c1dea4d642783ca9848ee0bce20a
See PR #9801
Manual
----
> Blame settings: Auto size for checkboxes

- GitCommands/CommitDataManager.cs
- GitUI/CommitInfo/CommitInfo.cs
Part of #4816 
A very minor optimisation to only fetch Notes and not Body when not needed.
There are only a few ms saved from this (so this is still more than most any code efficiency comment about LINQ etc but still hardly noticeable), the primary reason is to see this explicitly in the log and not check again why the Body/Subject is parsed over and over again.
First and last Git command is due to diff tab, the other are required when displaying a commit.
Manual
----
> GitNotes: Reduce overhead when Body exists

- GitCommands/AppTitleGenerator.cs
- UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
Part of #9796 
If a path filter is applied, display the filename path (if not possible use the filter path) first in the app title.
This is to separate path filters similar to how FileHistory is separated but also show the filtered path better.
I am not thrilled by the ⏱ but have no better suggestions myself.
FileHistory is not default in master but can be enabled
Updated the app title tests.
----
> AppTitle: File name in path filter first

- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/FormBrowseRepoSettingsPage.cs
- GitUI/Translation/English.xlf
Part of #9796 
This addresses what is maybe the core problem in #9796: Blame in RevDiff
This was added in #9424 and was intended for quick checks. The use
corresponding to FileHistory was intended to be used in FileTree.
(Some other changes planned for Blame in general and specifically for Blame in RevDiff for other concerns.)
Blame in RevDiff has certain limitations as revisions for a file may
not exist in the grid and the file to blame may not exist in all
revisions.
Add a setting to explicitly enable blame in RevGrid.
Blame 'B' in RevDiff by default opened in RevDiff itself
Default is only FileTree
Blame 'B' in RevDiff by default opens FileTree
Basically the same as selecting filetree in the context menu 'T' but Blame is opened if show file contents was selected ('B' in FileTree). …
> RevDiff: Setting to show Blame in FileTree

- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Submodules.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/GitUICommands.cs
- GitUI/MessageBoxes.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusList.cs
Fixes #8366
Show MessageBox with submodule information
Replaces #9612, also some other situations handling #9056
This could be done in a nicer way, but this is important to point users in a better direction just not ignoring (as in 3.5) or showing a popup recommending to report an issue on GE (as in master).
For users, the behavior in master seem like a regression.
1. See #9612 - due to null types in master
Note that the popup is shown two times when opening a repo (structure and status) then periodically when status is updated. (So did the Validate error.)
The popup could be limited to be shown for just the first popup when the structure has been updated, but this is an error in the repo setup.
See this (auto closed) PR for how to recreate the issue.
2. Open when submodule path (not yet) …
> Ignore nonexisting submodule paths

- GitUI/UserControls/BlameControl.cs
This is the core change in #9805 
To add tests to this, a lot more has to be changed and this change is useful to functional testing other upcoming GoToLine changes,
so it was broken out to a separate PR.
#9805 is kept to handle the tests.
Blame can start presenting on a line. This is is available in
RevDiff and RevFileTree since #9424.
(Even if the code enabling this has existed for long time,
it was just used for a special case.)
The "goto line" was only used if the control had to be init,
not if e.g. toggling to Diff and selecting an new diff line
and then Blame again.
See #9805 
Manual - tests in #9805
---- …
> Blame: Start on line also when control already exists

- GitCommands/Settings/AppSettings.cs
- GitUI/Theming/ThemeModule.cs
Fixes #9812
Really just point 2, but I find this sufficient - I would settle with just changing the name of the setting.
Change the settings name key to force resetting the theme
with application colors to default, as dark theme application colors will
not look good without hooks for system colors.
The user is warned once when starting the first time if the
theme is other than the default.
First time starting up with a non default theme
- Setting non default theme (using 3.5 or master)
- Start with this PR and verify the poup
- Start again, verify no popup
- Set default theme (using 3.5 or master)
- Start, verify no popup
---- …
> Reset theme to default

- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.Designer.cs
- add mnemonics to labels of `ToolStripFilters`
- manual
- Build 7c33b6fab9bee4328eb970efa6d50653f5297e74
- Git 2.31.1.windows.1 (recommended: 2.33.0 or later)
- .NET 5.0.12
----
> Add mnemonics to filter toolbar

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormBlame.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/Editor/FileViewer.cs
- GitUI/GitUIExtensions.cs
- GitUI/UserControls/BlameControl.cs
git-blame may require considerable time, the git executable
must be cancelable.
For instance git-blame of "GitUI/Translation/en_pseudo.xlf" takes about a minute for me.
Clear the blame viewer when processing a new file.
Before the contents of the previous file was not cleared, which was confusing.
(This was not a problem when a separate FileHistory had to be opened for Blame, but is now when Blame can be viewed in FileTree and RevDidd).
Note that cancelling the Git command will not kill the Git process. So clicking around in the file tree can start several long running processes.
Before, they always ran to completion in GitModule, now they are aborted (no exit status and short runtime in command log).
So in some sense cancelling is worse as the command still runs but command cache is not …
> BlameControl: cancellation token for git-blame

- GitCommands/Git/GitModule.cs
When the string is empty (i.e. no merge commits),
`LazySplit('\n').Any()` return `true`.
Replace by a check that the string contains something (i.e. a merge commit has been found)
preventing creation of potentially a lot of unnecessary substrings.
This popup is always displayed even if there is no merge commits to rebase:
The popup is displayed only when a merge commit will be rebased.
- Manual
- Build a61328ace4b35d936dbdf2e9127293452f835172
- Git 2.34.0.windows.1
- .NET 5.0.13
----
> Pull rebase: Fix detection of merge commits

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- ResourceManager/GitExtensionsControl.cs
- ResourceManager/GitExtensionsFormBase.cs
- Route hotkeys to the other visible controls in FormBrowse and FormCommit if not handled by the focused control 
- manual
- Build 9916393dc46aaeb1c5a5006d046768b301bd5721
- Git 2.31.1.windows.1 (recommended: 2.33.0 or later)
- .NET 5.0.12
----
> Route hotkeys to all visible controls

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Translation/English.xlf
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- Allows to add --reset-author to an amend commit
Amending commits with --reset-author was not possible (to my knowledge)
Obviously this PR forces --reset-author for each amend commit. I would like to take this as a basis if this should be in the product at all and if yes, how it should be realized in the UI. UI part has not been done or thought about so far.
- Manual testing :)
- GIT 2.34.1
- Windows 10 21H1
----
> Allow amend commits to also add --reset-author

- GitCommands/Git/GitModule.cs
- GitCommands/Git/GitVersion.cs
- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormCommit.Designer.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/GitUICommands.cs
- GitUI/Translation/English.xlf
Fixes #9839
- Add `git stash --staged` command to FormBrowse and to FormCommit
if Git version is >= 2.35.0
- Recommend this version of Git
My use case: Occasionally, I want to swap staged and unstaged, e.g. if the previous commit needs to be amended or when something different is to be committed urgently.
- manual
- Build 0fe73fac09d500dcd1d28123a2436645c6d983b8
- .NET 5.0.12
----
> Add git stash --staged

- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Fixes #9845
- Register the already implemented `Command`s `NavigateBackward` and `NavigateForward` in the `HotkeySettingsManager`
(The hardcoded keys did not have an effect anymore since 930e22a8b8
because they were caught by the regarding `Hotkey`s of `FileViewer`.)
- `RevisionGridControl.OnGridViewKeyDown`:
Remove the hard-coded `Alt+Left` & `Alt+Right` and set `e.Handled = true` for the remaining keys
- manual
- Build e91a0a9921e5eabe497838838c3e7b22313f77f4
- .NET 5.0.12
----
> RevisionGrid: Use Hotkeys for navigation

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCloneTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormEditorTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormInitTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPullTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormPushTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormRebaseTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPageTests.NoPlugins.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/SettingsDialog/Pages/BuildServerIntegrationSettingsPageTests.WithPlugins.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/SplitterPersistenceTests.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
- UnitTests/GitCommands.Tests/CommitMessageManagerTests.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormOpenDirectoryTests.cs
- UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
Many tests (one out of four?) have failed recently:
```red
LibGit2Sharp.LockedFileException : the index is locked; this might be due to a concurrent or crashed process
```
https://ci.appveyor.com/project/gitextensions/gitextensions/builds/42433206
These issues occur when a ReferenceRepository is to be reset before next test case.
There seem to be some reuse of repos, parallel tests or repos that happen to use the same path.
The reason for the failure is unknown, but the reset is just a way to speed up the test and should not fail the test case.
So a try-catch to create a new repo is used.
Two tests became unstable after this, ignoring.
I have no clue why they occur after these changes, seem to be related to .net5
```
at GitExtensions.UITests.CommandsDialogs.FormEditorTests.Should_preserve_ …
```
> Tests: Protect RefRepos with mutex before reset

- GitUI/CommandsDialogs/FormBrowse.BrowseArguments.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUICommands.cs
Final (?) part of #9796 
When starting up with command line arguments "filehistory" or
"blamehistory" (for instance from VS or explorer),
hide the side panel and start in FileTree tab to
provide an experience similar to old FileHistory.
The forced side panel state is not persisted to settings at shutdown.
If argument is "blamehistory" the Blame viewer is explicitly enabled
(similar to blame from DifTab), for "filehistory" the last used form
is used.
When starting with command line arguments "filehistory appveyor.yml"
manual
----
> FileHistory mode at browse startup

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/FormFileHistory.cs
- GitUI/HelperDialogs/FormChooseCommit.cs
- GitUI/MessageBoxes.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/BlameControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Discussed in relation to #9796 
If a objectId is expected to be available in the repo (for instance
retrieved with git-rev-parse), but is not included in the grid,
GE will inform the user with a popup instead of just silently ignore.
This is how GE has behaved for a long time, but there were previously less opportunities to 
enter commit sha that were in the repo but not displayed in the grid. 
There are various filters (including path filter) that hides commits and
links are exposed in the side panel and commit info.
All occurrences of `SetSelectedRevision()` are not getting the popup, it is opt-in
even if most occurrences are included. I have tried to verify that there are no popups in 
"automatic" situations and that the ObjectIds are valid Git sha (normally parsed by git-rev-parse or …
> RevGrid: Show popup when a revision is not in the revision grid

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/IndexWatcher.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Related to #9864 
Possibly fixes #9792 #9223
The IndexWatcher controls the icon for the refresh button in Browse.
Before #9791 the setting could be controlled individually,
now the same setting as for GitStatus (commit count).
Previously it also tried to optimize grid refresh operations in a few
situations, skipping when no changes was detected to the index or any refs.
These checks are now removed, always refreshing the grid.
The check for changes seem to miss updates occasionally (and never in
WSL where FileSystemWatcher do not reeport updates).
This seem to be improved by matching on creation of index.lock
in addition to index, but then also reset of worktree files
are tracked as index changes.
Before the file watcher was initiated at creation of the control and
when a new revision was …
> IndexWatcher: Use for refresh icon only

- GitCommands/Git/GitRefName.cs
- GitCommands/RevisionReader.cs
- GitUI/CommandsDialogs/FormBrowse.InitCommitDetails.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
Co-authored by RussKie
This replaces #9853
(changes pushed to #9853 too).
Improve the responsiveness in the loading phase and decrease
the revision loading time.
Revision info is read in two parallel steps:
1. Read current commit, refs, prepare grid etc.
2. Read all revisions with git-log.
Both these operations can take a long time and is done async.
Before part 1. was read synchrounously and blocked the interface
(git-log was async).
As the information is needed by step 2. when commits are added to the grid,
the information from step 1. is therefore protected with Lazy accessosors
and a semaphore.
RevisionReader (git-log) was previously also updating other information,
but is now a pure revision reader.
Other:
* The text label informing that loading of revisions still occur was
not …
> RefreshGrid: async reading refs and logs in parallel

- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridRefRenderer.cs
- GitUI/UserControls/RevisionGrid/SuperProjectInfo.cs
Seen in #9864 
For submodules, show the commit in the supermodule (index).
So if the submodule is not updated, the marker will differ.
Related to #8703 that selects the commit in superproject head when opening a submodule.
The color is not themable, also used when the submodule is in conflict.
This could be done in the grid too
(but then GetSuperprojectCheckoutAsync() will have to be split to not delay submodules too much).
The alternative to this PR is to delete the unused property.
(No extra arrow)
Manual.
----
> Show CurrentCommitId for super project for submodules

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #9884
Introduced in #9864 
The restructure in #9864 cleared the current selected revisions in the grid before they were read and HEAD was therefore always selected after a refresh.
As #9864 simplified the internals for the refresh, the handling could br simplified further, removing global variables.
This may also fix the problem with incorrect commit seleced after refresh that occurred occasionally (no refrerences right now.
Sidenote: PerformRefreshRevisions could be moved to a separate module, the metod is now 500 lines (this PR moves further methods as they are only used by PerformRefreshRevisions ).
Not now, there are further changes coming.
manual
---- …
> RevGrid: Save currently selected before clearing the grid

- GitCommands/AppTitleGenerator.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/ToolStripPushButton.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/AppTitleGeneratorTests.cs
Followup to #9864
Avoid Git calls where no branch is checked out and in submodules
This is similar to how HEAD is cached in CurrentCheckout.
For repos where a Git branch is checked out, this is handled by reading files, so some IO is needed.
This adds some ms here and there, nothing critical (but affecting performance a lot more than most programming constructs).
For submodules where normally no branch is checked out, this requires Git commands, both when loading revisions and opening menues etc.
No UI changed, just some commands (only startup shown).
manual
Removed an incorrect test and adopted another.
(A branch name like `(test)` is actually legal and should be displayed as `((test))` in the title.
---- …
> RevGrid: Lazy handling for current branch

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormPull.Designer.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Enables #7094
Enable fetching moved tags
in combination with once (manually) run `git config remote.<name>.tagOpt --tags`
by adding "--force" to "--prune" in `GetFetchArgs`.
`"C:\Program Files\Git\bin\git.exe" fetch --progress "--all" --prune`
`"C:\Program Files\Git\bin\git.exe" fetch --progress "--all" --prune --force`
- adapt existing unit test
- manual
- Build f7398a736a4ece01221601580ae586229317b53f
- .NET 5.0.12
----
> Enable fetching moved tags

- GitUI/UserControls/AccessibleDataGridViewTextBoxCell.cs
- GitUI/UserControls/RevisionGrid/Columns/CommitIdColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
Fixes #9852
- Set missing accessibility `Value` for `RevisionGrid` columns:
- message
- commit id
- Set empty string for accessibility property `Name` of all `RevisionGrid` cells
because it contained redundant information "Message Row nnn"
- manual: run "...\Windows Kits\10\bin\10.0.19041.0\x86\inspect.exe"  and hover the grid cells
- Build 687a8e3de13f4171b17e3ddd6d767225c3237840
- .NET 5.0.12
----
> RevisionGrid: Set accessibility values

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
Follow up to #9864, related to #9888
If a new repo is opened in FormBrowse the call chain is
SetGitModule() -> UICommands_PostRepositoryChanged() -> RefreshRevisions()
Most other refreshes in Browse uses RepoChangedNotifier.Notify(),
which is confusing when reading the code.
As the sidepanel is init from RepoChangedNotifier.Notify(),
the use of Notify() cannot be changed now.
This commit just separates the changes to RefreshRevisions().
Manual
----
> Browse: Clarify RefreshRevisions() handling

- GitUI/BranchTreePanel/RepoObjectsTree.BranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.RemoteBranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/FilteredGitRefsProvider.cs
- Plugins/GitUIPluginInterfaces/GitUIEventArgs.cs
Part of #9888 (that is follow up to #9864)
Leaves the "double side panel init" to later.
#9884 is already approved but have a refresh issue that I do not know how to solve in a good way and therefore separate most of the changes.
* Changing filters required 3 separate getRefs() calls (so it could be slower than refreshing the complete grid).
* Share getRefs() after loading the grid when filters are applied (normally, this is not needed though if the structure is not rebuilt).
Getting refs can take >10s in large repos and should only not be done 3 times when only one is needed.
Future: This could possibly be cached too, requiring an "external" refresh to reread the cache.
For changing sort criteria
Manual …
> Share gitRefs when reloading after changing sort criterias

- GitCommands/RevisionReader.cs
- GitCommands/Settings/AppSettings.CommitInfoPosition.cs
- GitCommands/Settings/AppSettings.LocalChangesAction.cs
- GitCommands/Settings/AppSettings.RevisionSortOrder.cs
- GitCommands/Settings/AppSettings.ShorteningRecentRepoPathStrategy.cs
- GitCommands/Settings/AppSettings.TruncatePathMethod.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/AppearanceSettingsPage.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
Fixes #9758
- Explicitly specify the argument `--topo-order` to `git log` if not sorting by author date
- 👀
- Build 624068b81beb2475fa94987dc1e0c50ab60a1618
- Git 2.31.1.windows.1 (recommended: 2.33.0 or later)
- .NET 5.0.12
----
> RevisionGrid: Option for git log with --topo-order

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes the bug of #9822
RevisionGridControl: (Re)load `Hotkeys` before `CreateOrUpdateMenuCommands`
- manual
- Build 1f4e1c088eb31e8f5a42f02167f062318011187c
- .NET 5.0.12
----
> Display assigned hotkeys in View menu on startup

- Packages.props
- ResourceManager/ResourceManager.csproj
- ResourceManager/TranslatedStrings.cs
- contributors.txt
Refers to https://github.com/gitextensions/gitextensions/discussions/9909#discussioncomment-2410663
- Upgrade package `SmartFormat` to v3.0.0, using the `Core` instead of the `Full` package, getting rid of unnecessary dependencies
- Brings higher performance in speed and memory footprint ([more details](https://github.com/axuno/SmartFormat/wiki/Why-Migrate))
- Fix: To achieve the same error behavior as in pre v2.5.0, formatter exceptions **and** parser exceptions must be set to "ignore". The latter was missing when migrating to v2.5.0
- Existing unit tests succeed with the updated package
- Manual, testing for English, French and German translations display okay (random samples)
- GIT 2.33.0.windows.2
- Windows 11 Pro
- I agree that the maintainer squash merge this PR
----
:black_nib: I …
> Upgrade pkg SmartFormat to v3.0.0

- GitUI/CommandsDialogs/FormCommit.cs
Fixes #9914
as follow-up to #8541 which fixed #8327 
Reset checked state of `Amend` and `noVerifyToolStripMenuItem` after closing the (modal) Push dialog
(i.e. no need to disable the checkbox while pushing)  
- manual
- Build ffacb5d73f973e18e8e585dc21235c10db9291d3
- .NET 5.0.12
----
> FormCommit: Reset commit options after push

- GitUI/BranchTreePanel/RepoObjectsTree.BranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.Tags.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Nodes.cs
- GitUI/BranchTreePanel/RepoObjectsTree.RemoteBranchTree.cs
- GitUI/BranchTreePanel/RepoObjectsTree.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/GridLoadEventArgs.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- Plugins/GitUIPluginInterfaces/GitUIEventArgs.cs
Follow up to #9864 
* Previously, the side panel was initiated from Browse (UICommands_PostRepositoryChanged is almost always invoked by Browse changes regardless or not if the repo is changed),
then again after loading the grid if a filter was applied or changed.
(normally the loaded branches etc were reused, so no additional Git call just making this confusing and some additional loading).
The second part is needed if the change was initiated from RevGrid itself (normally when changing filters etc).
The side panel init is now only started when loading the grid.
Update is forced if the repo changes (set for instance for F5 refreshes).
Some parts separated to #9896 and #9897
manual
Rebase merge 
---- …
> Init sidepanel only when loading

- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Local (DEBUG) tests failed with .NET6
AppVeyor tests can be reenable.
Repeated the tests in AppVeyor
Repeated AppVeyor tests in loops
----
> Fix test View_reflects_applied_branch_filter

- GitUI/CommandsDialogs/FormPush.cs
The dialog is spawned when attempting to push a branch that would result in a rewrite of the remote HEAD.
> Correct ownership of Push taskdialog

- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphLaneColor.cs
- Increase contrast between graph colors for red-pink, light-violet, red
- Remove the dark-blue graph color which is too near to the selection color
- manual
- Build c593255d9e15227fe7ddeba5e4a9fc246ad09efe
- .NET 5.0.12
----
> Increase contrast between graph colors

- GitUI/UserControls/RevisionGrid/Columns/BuildStatusColumnProvider.cs
https://github.com/gitextensions/gitextensions/pull/9932#issuecomment-1086822200
Tune build-server-in-progress color
Slightly lighter blue than light-blue branch color.
Visual
----
> Adjust color for build in progress indication

- GitUI/CommitInfo/CommitInfo.cs
- For artificial commits, clear the lower panel of the `CommitInfo`
- manual
- Build b841ac9fbb29918b75ffbf3c3826ca5bb2c5d502
- .NET 5.0.12
----
> CommitInfo: Clear RevisionInfo if no real revision

- GitCommands/Git/GitModule.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #9913
Fixes #9910
Create Stash
Goto Common ancestor
HEAD is not set for orphan branches or initial commits.
manual
----
> Handle detached HEAD for orphan branches

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FileStatusList.Designer.cs
- GitUI/UserControls/FileStatusList.cs
Fixes #9899
With this I see no more major async needs in the refreshRevision sequence,
(InternalInitialize() calls CheckForUpdates but that is only done occasionally during start.)
* Change git-diff file difference calculation to be asynchronous and
display a message indicating that the files are loading (instead of
showing the old diff).
This is also used in FormCommit etc, not much changes there as there is not much you can do until the diff is loaded anyway.
Using the same cancellationToken as is used for showing file contents.
* Browse RefreshRevisions(): Skip RefreshArtificial()
This is redundant as the revision is restored after loading the grid is done.
Duplicate update is normally avoided as revisions are not yet set when
RefreshArtificial() was called.
The diff before revision is …
> RevDiff: async SetDiff

- GitUI/Editor/FileViewer.cs
Fixes #9944 
If TreeGuid cannot be retrieved with git-ls-files
Current popup has no info about filename or revision (Git Command Log must be manually checked).
Code review
----
> FileViewer: Display error text rather than popup

- GitCommands/Git/GitModule.cs
- UnitTests/GitCommands.Tests/Git/Commands/GitCommandHelpersTest.cs
- UnitTests/GitCommands.Tests/GitModuleTests.cs
Fixes #9937
Override the Git default of one parallel job.
If the user has set fetch.parallel or submodule.fetchJobs the
the user config value is set (or git default if just one is set).
Config check adds 4ms the first check for me and <1ms the second (when the value is cached).
Manual
I guess this could be tested, someone is welcome to contribute.
----
> git-fetch --jobs==0 if no configuration

- GitUI/CommitInfo/CommitInfo.cs
At 150% scale factor the RTB containing commit messages gets randomly set to 0-height. This in turn disables all resize notifications, and commit messages become invisible.
Force the RTB to have min size (1, 1) to prevent 0-height.
- Manual at various scale factors.
----
> Ensure commit message textbox is visible

- .github/fabricbot.json
The file is a dump of the automation rules that are currently active and doesn't contain any additional changes.
Similar to https://github.com/dotnet/winforms/pull/6538.
This still means that only MS employees may be able to use modify the config via the Fabric Bot portal, however this provides an opportunity for the wider community participation, e.g., updating the milestone or labels directly via the code.
----
> Migrates FabricBot automation to "Config-as-Code"

- GitCommands/ExternalLinks/ExternalLinksStorage.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
- GitUI/Script/ScriptManager.cs
- IntegrationTests/UI.IntegrationTests/Script/ScriptManagerTests.Can_save_settings.approved.txt
- IntegrationTests/UI.IntegrationTests/Script/ScriptManagerTests.cs
- IntegrationTests/UI.IntegrationTests/Script/ScriptRunnerTests.cs
- UnitTests/GitCommands.Tests/ExternalLinks/ExternalLinksStorageIntegrationTests.Can_save_settings.approved.xml
- UnitTests/GitCommands.Tests/ExternalLinks/ExternalLinksStorageIntegrationTests.cs
- UnitTests/GitUI.Tests/Hotkey/HotkeySettingsManagerTests.Can_save_settings.approved.txt
- UnitTests/GitUI.Tests/Hotkey/HotkeySettingsManagerTests.cs
Workarounds for a regression in .NET 6, see: https://github.com/dotnet/runtime/issues/64885
----
> More xml-related fixes

- GitUI/CommandsDialogs/FormPush.Designer.cs
- GitUI/CommandsDialogs/FormPush.resx
Closes #9402
- Build b426a9c4104dd80a07a6586edc40e8fc2b8319f9
- .NET 6.0.3
Only "to" label appears to anchored incorrectly:
----
> Correct label alignment

- GitCommands/Git/GitModule.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusList.cs
Follow-up to #9908
- Provide the `CancellationToken` to `SetDiffsAsync`
(The git command itself will continue to run in the background yet. The process will be terminated in a follow-up PR.)
N/A
- manual
- Build 9f13cba2480dd30d71130c415ae829a5a26e4765
- Git 2.35.2.windows.1
- .NET 6.0.3
----
> Make SetDiffsAsync cancellable

- GitExtensions/Program.cs
- GitUI/CommitInfo/CommitInfo.Designer.cs
- GitUI/CommitInfo/CommitInfo.cs
- GitUI/CommitInfo/CommitInfoHeader.cs
- GitUI/Editor/RichTextBoxXhtmlSupportExtension.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Remotes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.ReorderNodes.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.Submodules.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowse.LeftPanelTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockAppTitleGenerator.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/Mocks/MockLinkFactory.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/SplitterPersistenceTests.cs
- IntegrationTests/UI.IntegrationTests/GitUICommands/RunCommandTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.ReloadCommitInfo_should_handle_ShowAll_branches_correctly.approved.txt
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.ReloadCommitInfo_should_handle_ShowAll_tags_correctly.approved.txt
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.ReloadCommitInfo_should_render_links_correctly.approved.txt
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- ResourceManager/LinkFactory.cs
- TranslationApp/Program.cs
- UnitTests/GitUI.Tests/TranslationTest.cs
- UnitTests/GitUI.Tests/UserControls/BlameControlTests.cs
- UnitTests/ResourceManager.Tests/LinkFactoryTests.cs
Fixes #9934
- Show both all branches and all tags regardless of which `[ Show all ]` link is clicked 
- manual
- Build b855fa621dd5ab924621b61a52f5633f39ab0230
- .NET 6.0.3
----
> CommitInfo: Workaround for `Show all tags`

- GitUI/UserControls/RevisionGrid/ArtificialCommitChangeCount.cs
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Part of #9955
Add indication similar to that on the Commit button if there is no info (grey) or no changes (green)
instead of no info.
Minor fix for ToggleBetweenArtificialAndHeadCommits that checked for count rather if the commit existed.
(This check has always bothered me, kept it when reverting a change to update the count).
manual
----
> Show 'no changes' in grid for artificial

- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
> left panel: reverted menu icon scale to match item font size

- GitUI/CommandsDialogs/FormCheckoutBranch.cs
HEAD may be null before creating branches for instance when creating
orphan branches without committing.
Assert added in 2018.
Manual.
----
> Do not assert for head when creating branches

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Behave similar to Reset all by disabling the checkbox when the filter is empty.
This makes it simpler to toggle the filter.
manual
----
> Reset pathfilter by disabling checkbox

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Part of #9987
Reword/Edit commit dialog was displayed twice with identical contents.
Regression from 03eadac015d6bbe08118fbafe898d32bf2337cce
manual
----
> Show reword commit dialog only once

- GitUI/HelperDialogs/FormProcess.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #9987
Refresh also if formProcess returns Cancel, which it supposedly do if autoclosing
No other similar occurrence for FormProcess (or FormRemoteProcess) was seen in a quick review.
Manual
----
> Refresh regardless of formProcess results

- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.BackgroundUpdater.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionLoadEventArgs.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/SplitterPersistenceTests.cs
- IntegrationTests/UI.IntegrationTests/UITest.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Fixes #935
Load grid to selected revisions
The grid loads async separately from the revisions, must be awaited
before selecting rows in the grid or executing tests.
(If the revisions are 'recent' they will normally be loaded, but not if
few revisions were loaded (like in tests) or an early commit were
selected in another repo.
If only some of the revisions were found, show those.
`CheckAndRepairInitialRevision` that tried to handle this before were
not running correctly.
Handle grids without HEAD where artificial commits are inserted.
Previously, the selection "shifted" at refresh.
(Occurs after #9393/0954ee6268a6148c53fe855c9ba9451dd4594345 after 3.5)
Abort 'restore' selection during load if manual selection is performed.
GridLoaded event renamed to RevisionsLoaded to reflect usage. …
> Load grid to selected revisions

- GitUI/CommandsDialogs/FormResolveConflicts.Designer.cs
- GitUI/CommandsDialogs/FormResolveConflicts.cs
- GitUI/Translation/English.xlf
Replaces #9907, which would be too intrusive and does not work for cherry-picks
- FormResolveConflicts: Just clearer label and confirmation messages for `Reset` button
(The command `git reset --hard` will still be used.)
- manual
- Build ec324afbbc5dec66a66e58937f98cf2e2130af69
- .NET 6.0.3
----
> FormResolveConflicts: Clearer label and confirmation messages for Reset button

- GitUI/CommitInfo/CommitInfo.cs
- GitUI/CommitInfo/RefsFormatter.cs
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.ReloadCommitInfo_should_handle_ShowAll_branches_correctly.approved.txt
- IntegrationTests/UI.IntegrationTests/UserControls/CommitInfo/CommitInfoTests.ReloadCommitInfo_should_render_links_correctly.approved.txt
- UnitTests/GitUI.Tests/UserControls/CommitInfo/RefsFormatterTests.cs
- `CommitInfo`: Ensure that there is exactly one empty line between the sections
- bugfixed the test, too
- Build 1589528398e44bc05a6e552908b1d5d637cb9563
- Git 2.35.2.windows.1
- .NET 6.0.3
----
> `CommitInfo`: Ensure empty line between sections

- GitCommands/CommitData.cs
- GitCommands/CommitDataManager.cs
- UnitTests/GitCommands.Tests/CommitDataManagerTest.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataBodyRendererTests.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataHeaderRendererIntegrationTests.cs
- UnitTests/ResourceManager.Tests/CommitDataRenders/CommitDataHeaderRendererTests.cs
Fixes #9378
I hope
Remove the unused `CommitDataManager.TreeGuid` and do not attempt to parse this *optional* value.
N/A
- adapted testcases
- Build a9241924a70caa8d687e8be477587f68f8718455
- .NET 6.0.3
----
> Remove unused `TreeGuid`

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/RevisionDiffControl.Designer.cs
- GitUI/CommandsDialogs/RevisionDiffControl.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.Designer.cs
- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
Fixes #10004
- Replace hard-coded `Ctrl+O` shortcuts with configurable `Hotkey`s
- manual
----
> Replace hard-coded `Ctrl+O` shortcuts with `Hotkey`s

- GitUI/CommandsDialogs/FormDiff.cs
- GitUI/CommandsDialogs/FormLog.cs
- GitUI/UserControls/CommitDiff.cs
- GitUI/UserControls/FileStatusDiffCalculator.FileStatusDiffCalculatorInfo.cs
- GitUI/UserControls/FileStatusDiffCalculator.cs
- GitUI/UserControls/FileStatusList.cs
FormDiff: Set HEAD for diff calculator, causing a popup 
The core problem is that HEAD is set incorrectly, could be artificial.
Set merge base also when artificial commits are selected
Regression in master.
manual 
----
> FormDiff: Set HEAD for diff calculator

- GitUI/UserControls/BlameControl.cs
https://github.com/gitextensions/gitextensions/issues/9796#issuecomment-1150520616
Changes the default behavior, to change the revision the left gutter
must be clicked.
If changing the default behavior change is not acceptable here, there are altaernatives:
* Add a setting to continue allowing this. (default off - where?)
* Add a popup confirming the behavior at first use.
I prefer the simple solution, as is.
Manual
----
> Blame: No change of control at double click

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #
- Raise questions about `_isRefreshingRevisions` and `cancellationToken`
- Avoid dangling tasks waiting for `semaphoreCurrentCommit` (might contribute to #9830)
- Exception-safe locking of `semaphoreCurrentCommit`
- Fixup typo in `UpdateSelectedRef` argument
- TODO: It is highly desirable that loading the revisions becomes cancellable.
- 
- 
- 
- Build a66f50670d4b724937f49cb7155b0904660d23dd
- Git 2.35.2.windows.1
- .NET 6.0.3
----
> RevisionGrid: Cleanup PerformRefreshRevisions

- GitUI/CommandsDialogs/FormRebase.Designer.cs
Fixes #7708 (latest comments about the tooltip clarity)
- Improve the clarity of tooltips for Rebase UI date options:
- Ignore date
- Committer date is author date
- Also, shorten the width of the tooltip by breaking text somewhere in the middle.
- Open the Rebase UI using Commands > Rebase...
- Hover on the two mentioned check boxes (date options).
- Observe the tooltips.
- Git Extensions 4.1.0.14867
- Build 2c3150d01d9c76bd13c72a742c26ceafcbf9eb64 (Dirty)
- Git 2.33.0.windows.1 (recommended: 2.35.0 or later)
- .NET 6.0.6
----
CC: …
> Improve the clarity of tooltips for Rebase UI date options

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Further optimizations loading revisions, while adding revisions to the grid (while 'Loading' is shown).
Measuring with StopWatch in a Release builds, this measures <1 ms vs 30-60 ms.
Note: `_gridView.Add(revision, flags);` requires 250 ms for me which is actually less than I expected.
There may still be optimizations there, but I doubt it will be much. (Maybe the GUI updates can be improved more.)
The refs datastructure could maybe be improved too, but that is only about 10 ms, so not much gain.
Further loading improvements should be possible with caching of commands affected by worktree/index changes, which is tricky.
Manual
---- …
> RevGrid: Optimize onlyFirstParent handling

- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
Fixes #10074
git-log --boundary and --all is included in many revision listings. (The options are currently used together.)
This basically means that the parent to matches is included. This may be desired in some situations, but not with `--grep`.
It is not obvious that --boundary and --grep should be used where they are used now.
Similarly, -all may still be used with --grep. (I do not see how that is used at all though.)
The options can be tuned and expanded in general...
Also fixed the label for search.
Manual
----
> Exclude boundary commits with --grep

- GitUI/BranchTreePanel/BaseBranchNode.cs
- GitUI/BranchTreePanel/BranchTree.cs
Fixes #9194
When Alt+Click on local branches in the sidepanel, select the tracked remote branch.
Simplify finding remote tracked branches (to for instance find differences).
For branches with no tracked remote the local is selected as before.
Note Ctrl+Alt+Click is not handled now. Should that toggle the remote branch status?
(commit message is not correct right now)
Discussed in #9194.
Cherry-picked from @mstv private branch, with a minor adjustment
The local branch was always selected.
One normal click selecting the same branch, one alt-click to select the remote branch revision.
Manual
----
> Select remote branch on Alt+Click in side panel

- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
Expose the same behaviour as "Highlight selected branch" in the revision grid via <kbd>ALT</kbd>+<kbd>Left Click</kbd>, similar to the default hotkey <kbd>CTRL</kbd>+<kbd>Shift</kbd>+<kbd>B</kbd>.
> Allow highlight branch by ALT+Click in the grid

- GitUI/CommandsDialogs/RevisionDiffControl.cs
Related to #10090
The rules to allow reset and staging from hotkeys were evaluated separately from the menu item rules.
Set Enabled property (as Visible cannot be read).
It was only possible to (un)stage multiple files from menu due to the incorrect tests, this has been aligned.
It is also possible to reset multiple files by menu/hotkey.
Manual
----
> RevDiff: Align rules for hotkey execution to menu items

- GitUI/CommandsDialogs/FormStash.cs
- GitUI/CommandsDialogs/RevisionDiffController.cs
- GitUI/Editor/FileViewer.cs
- UnitTests/GitUI.Tests/CommandsDialogs/RevisionDiffControllerTests.cs
Fix bug when cherry-picking from stash a new file. Currently when action is performed nothing happens. 
That happens because we cannot internally resolve diff chunks in a new file.
Manual testing
----
> fix: Cannot cherry-pick new file from stash

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
- GitUI/CommandsDialogs/FormBrowseController.cs
- UnitTests/GitUI.Tests/CommandsDialogs/FormBrowseControllerTests.cs
Follow up to #7883
Evaluate the branch names for favorite/recent repo branch names async
(as IO is required) instead of delaying the opening of the menu.
For me (50 recent + 15 favorites, all on SSD but about five in WSL) there was a delay of 3.5s to open the menu (first time, file caching improved subsequent opening).
With this change, I still do not see that the branch name is added after the menu is opened.
The same for the dashboard.
Note: All "branch retrieval jobs" are now done in parallel instead of serial as it was before, so there is a higher CPU load spike now.
This may flood the threadpool and may need throttling. https://devblogs.microsoft.com/premier-developer/limiting-concurrency-for-faster-and-more-responsive-apps/
For the user it is still much better than before when all …
> Set branch name in repo menu async

- GitUI/CommandsDialogs/BrowseDialog/DashboardControl/UserRepositoriesList.cs
Regression from #10124 3cf9009f8279452f7e6d7f0694e8dabf0c3c108f
Occasional NBug due to an index variable not being captured in RunAsync.
As usage of index is early, it seems to not cause any issues in most situations, including the debugger for me.
Manual
----
> Dashboard: Capture variable in RunAsync

- .vscode/extensions.json
- .vscode/launch.json
- .vscode/tasks.json
Add basic VS Code support to build, test and run GE.
Also recommending plugins.
I personally would like a .code-workspace file too, but current settings can be stored in the folder and there are no folder external dependencies, so this works.
Not much use myself, but the current configuration is broken, this is something to improve on.
VS Code is used more and more, even if a Windows only app as GE is better supported in Visual Studio, this may help occasional users.
Also for 4.0, if users try to build/debug the release.
manual
----
> VS Code build support

- GitCommands/DiffMergeTools/VsCode.cs
Fixes #10133
Add AppData\\Local\\Programs\\/Microsoft\ VS\ Code to install paths for VS Code, the default installation path.
Solution is similar as for SemanticMerge.
One alternative would be to ad "bin" to the paths and change executable to code.cmd
This is not solving the problem reported in #10133, "code" is still not working. "code.cmd" would work though.
However, it handles the user experience adding vscode.
Should be included in 4.0 too.
manual
----
> Support User local paths for VsCode merge tools

- GitCommands/Git/GitModule.cs
- Plugins/GitUIPluginInterfaces/IExecutable.cs
Exit code is other than 0 if user aborts a merge.
#9056 is a step in the right direction, this is another situation where other exit codes than 0 are OK though.
Regression in master, to be included in 4.0
Occurs in FormResolve with _Start mergetool_
manual
----
> Do not start NBug if mergetool exits with other than 0

- GitUI/CommandsDialogs/FormBrowse.InitMenusAndToolbars.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
Fixes #9872
Clearing the dropdown items changed the focus and moved the focus in the textbox to the first position, so next key was added first.
Dropdown was not opened on focus, which made the filter unusable unless you opened the dropdown first (se below).
Cache the function for getting the references with lazy result, to speed up the dropdown.
Still some weird behavior:
* If you focus away/back the first match in the dropdown is selected also if the dropdown is not shown (same in 3.5)
* When moving focus away then back to the control all is selected. In 3.5 allt ext was always selected, you had to start typing from scratch. With 4.0 you can click again, but first position in the box is always selected, you have to move with arrows.
This PR is not perfect but it is similar to the 3.5 …
> BranchFilter text was added backwards

- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Fixes this use case:
1. Searching for a string (by default searching in commit message)
2. Selecting "Diff contains" and unselecting "Commit message"
3. Launch a search but search/filtering is not launched :(
Note: I think this fix should also back-ported to v4
- Fix filtering when playing with type of filtering
No filter launched (so empty revision grid)
The filtering is launched (so get results)
- Manual
- Unit tests
- Build df80a9de42f264168585fa79e0f07645de433013
- .NET 6.0.6
---- …
> Fix search not launching/working when changing filter selection

- GitExtensions/GitExtensions.csproj
- Packages.props
- scripts/RepoLayout.props
Resolves #10075
See https://github.com/gitextensions/gitextensions/discussions/10131#discussioncomment-3405852
Discussed in https://github.com/Tyrrrz/DotnetRuntimeBootstrapper/discussions/33#discussioncomment-3413110
Set version that propagates to runtimeconfig.json that serves as the minimal version that DotnetRuntimeBootstrapper checks.
By default, the version is set to 6.0.0 in
artifacts/Debug/bin/GitExtensions/net6.0-windows/GitExtensions.runtimeconfig.json
<RuntimeFrameworkVersion>6.0.8</RuntimeFrameworkVersion>
Update DotnetRuntimeBootstrapper to latest release 2.3.1
Set version to 6.0.7, 6.0.8: Normal startup
6.0.9: Popup to install new version.
Note: I had to delete artifacts/ and restart Visual Studio to not get the popup after changing.
.NET 6.0.8 (latest release)
I agree that …
> Set RuntimeFrameworkVersion for DotnetRuntimeBootstrapper

- GitUI/UserControls/FileStatusList.Designer.cs
- GitUI/UserControls/FileStatusList.cs
- contributors.txt
- In FileStatusList, DoDragDrop is called even when mouse (left button) is up, which is unnecessary
- Besides, in some windows versions, IME has a [bug](https://support.microsoft.com/en-us/topic/kb4564002-you-might-have-issues-on-windows-10-version-20h2-and-windows-10-version-2004-when-using-some-microsoft-imes-63696506-47d2-9997-0b72-41a68e328692) that DoDragDrop call will hang up. And Git Extensions is always calling DoDragDrop, thus increases the possibilily of this bug
- In FileStatusList, shift/ctrl click function remains same
- In FileStatusList, drag drop function remains same
- GIT 
- Windows 
---- …
> Do not call DoDragDrop when mouse is up

- GitCommands/Settings/AppSettings.cs
- UnitTests/GitCommands.Tests/Settings/AppSettingsTests.cs
At new installations:
Tags in sidepanel seem to be hard to find - even if the settings now have changed to buttons
( a bad move, removed useful area for something never changed)
https://github.com/gitextensions/gitextensions/issues/5460#issuecomment-423133032
Manual
----
> Show tags by default in side panel

- GitCommands/Git/GitStash.cs
- GitUI/CommandsDialogs/FormStash.cs
so that the user could more easily track where he is...
(I always found painful to use the stashes ComboBox when you have a lot of stashs and stash index really help me to find the current selected stash once you scroll in the list --because the ComboBox doesn't highlight the current selected item 😢--)
- Display index of stashes (like it is done in the git command output)
Let's play a game: Could you find the currently selected one?
And now?
- Manual
- 
- Build c92862e1c99a55af34ff69b2698742da81bfbba9
- .NET 6.0.8
---- …
> FormStash: Display index of stashes

- GitUI/UserControls/BlameControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #10147
If the grid is filtered, get the actual parent id as the grid may
be rewritten.
Affects to reword/edit rebase and blame.
For blame, also adjust the rules to show the "blame previous" menu item.
manual
----
> Reword/Edit: Rebase on actual parent

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Custom diff/mergetools (all known to Git) is available in RevDiff, Commit, FileHistory, ResolveConflicts
In RevGrid it is available only after settings, as the loading at startup was incorrect.
Custom difftool is useful for dir diff, as some difftools does not support dir diffs (like TortoiseDiff) and also if supported, may not be the best for dir diff.
manual
----
> RevGrid: Custom tools were only loaded at settings changes

- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
Fixes #10162
Handle selection after refresh if artificial commits are
removed from the view
Manual
----
> Insert artificial commits if filter without any matches is applied

- GitUI/CommandsDialogs/FormDiff.Designer.cs
- GitUI/CommandsDialogs/FormDiff.cs
- GitUI/Translation/English.xlf
Fixes #10081
- Refactor base->first, head->second
- FormDiff: Show range diff with set merge base instead of only diff first-second
Note: I consider FormDiff to be obsolete, Browse offers more functionality than these separate forms that are difficult to maintain.
Note: merge base in diff is set initially and matches the ui. it will not change if you select new branches in the form and if the merge base is no longer a base a multi diff without range diff will be shown
Manual
To be decided later.
The refactoring commit could be separate.
----
> FormDiff:  Show range diff with merge base

- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
A few tests fail frequently, close to half the tests.
This PR disables the flaky asserts in these tests, so the tests can be trusted better.
Another common issue is downloading the plugin manager.
Disable checks in Release builds, keep them in Debug
I have tried to look into the tests and spent considerable time in trying to improve the loading sequence, but have not solved this.
One reason for this may be some FileAndForget() like the cause for #10168 (even if #10136 changed that further).
Reviewing AppVeyor test logs
----
> Tests: Disable some commonly failed tests

- GitUI/UserControls/FilterToolBar.cs
The branchfilters from the sidepanel was not applied unless the
filter dropdown contained any items, but the items were not updated
by default since #10136, only when needed (dropdown clicked or text typed).
The dropdown was updated async FileAndForget, so 'external' usage was not
always successful. This was a reason why the test
'Filters_should_behave_as_expected' had to be disabled in AppVeyor
(the test still occasionally fails though).
(The test was the primary reason why I looked at this, the side panel was detected after.)
Manual
Test Filters_should_behave_as_expected works slightly better but still fails though.
---- …
> Set branchfilter from sidepanel without checking dropdown

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
- GitUI/BranchTreePanel/RepoObjectsTree.Designer.cs
- GitUI/BranchTreePanel/SubmoduleNode.cs
https://github.com/gitextensions/gitextensions/pull/10118#issuecomment-1211078704
Add menu item to open the current submodule (including the
superproject module) instead of reopening the module
(this option was not added to the menu).
Add the menu item to open the new instance too, first in the menu.
manual
----
> Open new instance if double click on current submodule

- GitUI/BranchTreePanel/SubmoduleNode.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/GitUICommands.cs
- Plugins/GitUIPluginInterfaces/IBrowseRepo.cs
Requires #10145 to be used, but can be reviewed independent of that PR.
When launching a new GE instance from the sidepanel, set
first/last selected revisions in the grid as first/second in
the new instance.
Always selecting HEAD 
Keeping selections
manual
----
> Sidepanel: Keep revisions opening a new instance

- GitCommands/RevisionReader.cs
- GitUI/UserControls/RevisionGrid/Columns/RevisionGraphColumnProvider.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraph.cs
- GitUI/UserControls/RevisionGrid/Graph/RevisionGraphRevision.cs
- GitUI/UserControls/RevisionGrid/RevisionDataGridView.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphMultiThreadingTests.cs
- UnitTests/GitUI.Tests/UserControls/RevisionGrid/Graph/RevisionGraphTests.cs
Preparation for #5371 
The end result is pushed to feature/i5371-stash-in-grid
For all stashes (not just the latest)
Not required for 4.0 but should be considered
- Eliminate static methods in RevisionReader
Prepare RevisionReader for added functionality.
Avoid passing class instance variable with every call.
Parsing revisions may be improved by a milli second in best case.
- Remove RevisionNodeFlags from data grid
Simplify (and a minor optimization) the code when loading revisions.
RevisionNodeFlags has information that is already available in the
GitRevisions, no need to pass that info again.
Set HasNotes after revisions are loaded, that is not required when
displaying a revision.
Tests are updated
---- …
> Eliminate static methods in RevisionReader

- GitCommands/RevisionReader.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.Designer.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Follow up to #10129
The filter handling is confusing, some comments in #10129 was due to that. It is also more limiting than needed.
*  Decouple simplify-by-decoration, no-merges, boundry as well as sort
options from first-parent (they can be applied there too).
*  First-parents can be used together with other types of branch filters
(not relevant with reflog). Before it was dominating
reflog and others.
* Set prio order for the various branch-filters from having first-parent as
dominant to:
Reflog->ShowCurrent->FilteredBranches (if non null filter)->All branches
* Separate ByBranchFilter from being shared CurrentFilter and
FilteredBranches to only be used for BranchFilter
Tests are updated
----
:black_nib: …
> Decouple filter options

- GitCommands/Settings/AppSettings.cs
- ResourceManager/GitExtensionsFormBase.cs
Fixes #9752
This is a fix, probably not the correct solution, added for review.
Occasionally when restoring GE from minimized, the app fail to stay open.
One drawback with the fix is that rightclick to close on the minature in the taskbar requires that the app is not minimized. OK to select the cross.
Manual
----
> Restore WindowState when activating

- GitUI/UserControls/BlameControl.cs
It should be displayed **only** when the path is different than the current file blamed but the comparison failed because the relative path passed is in Windows format whereas the ones of blame lines are in Unix format.
So converting the one passed in Unix format for comparison.
- Manual
- Build aca5a9519c8d1febda80a0b3c2f3c65d89603554 (Dirty)
- .NET 6.0.8
----
> Blame: fix path displayed in the gutter

- GitUI/CommandsDialogs/RevisionFileTreeControl.cs
- GitUI/UserControls/BlameControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
by providing the old path to blame and selecting it in the filetree
so that the blame view is not empty anymore
failing to find a not existing file in the filetree
- Manual
- Build 7447469d3f686c3d28fba1fffbded9f39607688d (Dirty)
- .NET 6.0.8
----
> Blame: fix blame revision older revision when the file has been renamed

- global.json
- scripts/RepoLayout.props
Fixes #10177
- Use any installed .NET SDK 6.0 for building GE
- Set RuntimeFrameworkVersion for DotnetRuntimeBootstrapper to the same version 6.0.8 as on the release branch
N/A
- build GE
- Build 8ccac05c4667d48169db44a0ab5ec3b2ee67faa4
- .NET 6.0.8
----
> Update .NET references

- appveyor.yml
- scripts/Mark-RepoClean.ps1
- scripts/Update-DotnetVersion.ps1
Updates dotnet SDK and Runtime versions together
Allows for
```powershell
.\Scripts\Update-DotnetVersion.ps1
```
OR
```powershell
.\Scripts\Update-DotnetVersion.ps1 7.0
```
resolves #10192 
- Add script to allow updating dotnet version to latest of current version used or passing in a specified version
- Update appveyor build to allow user to set flag that causes the latest version to be used in build.  Useful to test version bump before applying the change.
- Ran script and verified change
----
> Add Update-DotnetVersion script

- GitCommands/RevisionReader.cs
- GitCommands/Settings/AppSettings.cs
- GitUI/CommandsDialogs/FormStash.cs
- GitUI/GitUICommands.cs
- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/RevisionGrid/Columns/MessageColumnProvider.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Command.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.Designer.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormBrowseTests.cs
- IntegrationTests/UI.IntegrationTests/UserControls/RevisionGrid/RevisionGridControlTests.cs
- Plugins/GitUIPluginInterfaces/GitRevision.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.empty_commit.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.multi_pathfilter.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.no_subject.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.normal.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.reflogselector.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.TryParseRevision_test.ForScenario.subject_no_body.approved.json
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitCommands.Tests/TestData/RevisionReader/reflogselector.bin
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Resolves #5371 (and #5785
Fixes #9873
Show stash commits in the revision grid, with menu options to pop and drop stashes.
A stash is implemented in Git with 3 internal commit.
Some more explanations in GitUI\UserControls\RevisionGrid\RevisionGridControl.cs:988
The implementations I have seen do not expose the third commit with untracked files.
The PR includes this "untracked" commit (empty "untracked" are filtered) for the first 10 stashes (see Performance below for details).
This setting is read from the settings but no setter is exposed, mostly because there is no natural place to show it (maybe in View is the best, but other similar settings are in General, that is considered full).
The implementation by default only show the stashes where the parents are shown in the grid.
So for …
> Show Stash in rev grid

- GitCommands/RevisionReader.RefFilterOptions.cs
- GitCommands/RevisionReader.cs
- GitUI/CommandsDialogs/BrowseDialog/MenuCommand.cs
- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/IRevisionGridFilter.cs
- GitUI/UserControls/RevisionGrid/MenuUtil.cs
- GitUI/UserControls/RevisionGrid/RevisionGridControl.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
- UnitTests/GitCommands.Tests/RevisionReaderTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
- UnitTests/GitUI.Tests/UserControls/FilterToolBarTests.cs
Reorder the menu items to reflect how the items are used
This menu has grown without much consideration over the years. The sorting options were recently changed in #10172 to be decoupled.
Changes the muscle memory, but even I have a problem understanding the type of setting today...
* Branch filter mode (reverse order to how they are prioritized) 
Reflog <- current branch <- filtered branches <- All
(Except for reflog visible in Advanced filter)
Note: Any branch filter could be ticked at the same time as Reflog, previously
Reflog added to the branch filter dropdown.
* Further revision filters, mostly independent to filter modes 
Show merges, first parents
(Other revision filters in Advanced filter)
* History simplification, how to handle history with filters
Full history, simplify …
> Reorder items in View menu

- GitUI/CommandsDialogs/FormDeleteBranch.cs
Fixes #10122
- Always force-delete local branches regardless of the merged state (for unmerged branches after confirmation unless disabled)
- Do not load merged branches if `DontConfirmDeleteUnmergedBranch`
N/A
- manual
- Build 5a21c57542fc869811c9804869b11e8039236eae
- .NET 6.0.9
----
> Improve deletion of local branches

- GitUI/BranchTreePanel/RepoObjectsTree.ContextActions.cs
No idea why this happens. I found [this question on stackoverflow](https://stackoverflow.com/questions/15841863/why-does-my-menustrip-appear-in-the-incorrect-location-on-first-click) in which some folk suggest it may be a Windows Forms bug and how to work around it.
I didn't like the proposed work arounds much and think I've found a simpler one that works for me. Please try it and see if your mileage varies.
Fixes #10165
----
> working around context menu strip being positioned incorrectly on first open

- GitExtUtils/GitUI/TaskManager.cs
- GitExtUtils/GitUI/ThreadHelper.cs
- GitUI/CommandsDialogs/FormDeleteRemoteBranch.cs
- Factor out `TaskManager` from `ThreadHelper`
in order to have a `JoinableTaskCollection` and `JoinableTaskFactory` per Form.
So Forms and their tests can await their own async operations in the future.
- `FormDeleteRemoteBranch`:
- Use `TaskManager` to run `GetMergedRemoteBranches()` in the background.
- Await the execution when the data is needed. 
N/A
- manual
- Build 5688d4848d9e8bcb5c7e35f40e69ce522b4350a5
- .NET 6.0.9
----
> FormDeleteRemoteBranch: GetMergedRemoteBranches() in background

- GitCommands/Settings/AppSettings.cs
Fixes #10016
- Protect `AppSettings.SaveSettings` using a global mutex common to all GE instances
N/A
- manual
- Build 403856d49cf56837f9a746c452dc3ab13b5ecb49
- .NET 6.0.9
----
> Protect AppSettings saving using global mutex

- global.json
- scripts/RepoLayout.props
- Run  ```.\scripts\Update-DotnetVersion.ps1```
- Run ```git diff -U0 -w --no-color --ignore-blank-lines | git apply --cached --ignore-whitespace --unidiff-zero --``` to stage non whitespace changes.  This time I also staged whitespace on the global.json file to make it not have much of a diff in the future.  This prevents staging the blank line removal in the RepoLayout.props file that this script generates.
```
channel-version     : 6.0
latest-release      : 6.0.9
latest-release-date : 2022-09-13
latest-runtime      : 6.0.9
latest-sdk          : 6.0.401
support-phase       : lts
eol-date            : 2024-11-12
```
- Commit changes generated and see diff
---- …
> Update to latest 6.0 .Net Runtime/SDK

- GitCommands/Git/GitModule.cs
Fixes #10223
- Do not cache the git output if querying the current checkout, i.e. let `GetRevision` use the cache only if an `ObjectId` is specified
N/A
- manual
- Build 22636a7d67522cb59de51fd9e38ec9145eeeeb30
- .NET 6.0.9
----
> Do not cache current GetRevision data

- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterChangedEventArgs.cs
https://github.com/gitextensions/gitextensions/pull/10205#issuecomment-1262772044
BranchFilter for named branches as well as the revision filter for Message/Committer/Author/DiffContent is now updated when the filters have changed.
Manual
----
> Update filter toolbar when filters change

- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Fixes #10225
Git Notes must be excluded for --all only with the previous argument "--not --glob=notes --not".
Changed to the easier to understand "--exclude=refs/notes" that could be used independent of the various branch filters (including reflog).
However, "--exclude=refs/notes" only makes sense with --all, so kept there.
Adopted test.
(It is really of the kind to increase test coverage, so quite meaningless.)
----
> ShowOnlyCurrentBranch were not showing commits

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.Designer.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.resx
- GitUI/Translation/English.xlf
* Add "Open" and "Delete" buttons instead of having it in the grid
* Strike line when a worktree is deleted (and so remove "Deleted" column)
* Change font of Sha1 column & last column fill the remaining width
* name of branch displayed more user friendly (without '/refs/heads' prefix)
- manual
- Build b9e701c3a3bb431d5ce6b4a7099ff60c80fe461f (Dirty)
- .NET 6.0.8
----
> Worktree: redesign 'Manage worktree' form

- GitUI/CommandsDialogs/FormRebase.Designer.cs
- GitUI/CommandsDialogs/FormRebase.cs
- GitUI/UserControls/PatchGrid.Designer.cs
- Prevent the rebase form to **always** close when conflicts are detected whereas it should stay open to display the conflicts to the user
- PatchGrid: small fixes
* Prevent sorting of columns (that cause crashes and doesn't make sense)
* Better size 'Action', 'Date' and 'Status' columns (autosizing)
- Display patchgrid in 'Rebase' mode and not in 'patch' mode to display more meaningfull columns
- Current branch to rebase displayed in bold
- Manual
- Build ad22840dd6944d3993ff35402cfc55c815840a87 (Dirty)
- Git 2.38.0.windows.1
- .NET 6.0.9
---- …
> Form rebase: some small fixes

- GitCommands/Settings/AppSettings.cs
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
Part of #10213, can be applied independently
Remember last 30 used items in the revision filter
Keep the last used revision filter text (but not the type) in settings, so the filters can easily be retained.
I doubt that the revision filter is used much right now, but it still simplifies.
The "memory" is stored in settings when it is changed. There are other discussions about this behavior...
This is possible to include in 4.0 but maybe the full #10213 function should be added
(--exclude is from another usage, the core #10213 functionality)
Manual
----
> Revision filter combobox

- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/FilterInfo.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
- UnitTests/GitUI.Tests/UserControls/FilterInfoTests.cs
Fixes #10213
If "Message" starts with "--not " or "--exclude=", interpret the string as options to git-log.
This enables the possibility to enter filters that the GUI does not support (like negating conditions).
The options has no checks for Git syntax or if ParentsAreRewritten etc If need to be adjusted, it is up to the user.
For now, this feature will be described in GitDoc only.
See discussion in #10213
Feature simpler to use with #10239 
Example hiding filters with wildcard
Test added
----
> Custom options to git-log

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Hotkey/HotkeySettingsManager.cs
Follow up of #9848
- Add possibility to add a hot key for "Stash staged files" (no hot key defined by default)
- Manual
- Build b78e768d55af39e5d79310d8f1b7e772cefcf30a (Dirty)
- Git 2.38.0.windows.1
- .NET 6.0.9
----
> Hotkey: Add a hotkey for "Stash Staged" menu item

- GitUI/UserControls/FileStatusList.cs
When opening FormCommit - first item in unstaged files is selected. Then when shift-clicking on 2nd and further items to select 1fst through _clicked_ items, the selection is made not from the top but from the bottom.
- Reset internal ListView "last selected item" index by resetting `Selected` to `true` for the first selected item.
Notice that when `shift-clicking` after refresh control acts as if last item in the list has focus and selection happens from it till the item being clicked on.
- Manual
- Build cb8954cc0cc839d7b33976e6befa492e5a6fde07 (Dirty)
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.10
----
:black_nib: I …
> Redo selection of the first item to fix shift-select of multiple items

- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormCreateWorktree.cs
- GitUI/CommandsDialogs/WorktreeDialog/FormManageWorktree.cs
- GitUI/GitUICommands.cs
- Plugins/GitUIPluginInterfaces/IGitUICommands.cs
- Don't close the worktree form when the creation failed to let the user fix the issue and retry
- Refresh the revision grid even when user decide not opening a new worktree because ha has created another branch or checked one out and we should display the change in a refreshed revision grid.
Note: commits better reviewed separately.
- Manual
- Build b78e768d55af39e5d79310d8f1b7e772cefcf30a (Dirty)
- .NET 6.0.8
- Rebase merge or Merge commit (not squash)
----
> Worktree form management improvements

- GitUI/TranslatedStrings.cs
- GitUI/Translation/English.xlf
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/RevisionGrid/RevisionGridMenuCommands.cs
I'm struggling with the new order of the branches view options having built a muscle memory for the past 10+ years.
----
> Restore the order of the branch view options

- GitCommands/Git/Executable.cs
Fixes #10242
if throwOnErrorExit  was not set to false for Git commands, stderr was always empty.
This is likely a remains of the first implementation of throwOnErrorExit that raised errors for contents in stderr in addition to non zero error code.
Also git-verify-tag should only parse stderr, not stdout.
Manual
----
> Git Executable: return stderr also if not throwOnErrorExit is suppressed

- GitUI/UserControls/RevisionGrid/FormRevisionFilter.Designer.cs
- GitUI/UserControls/RevisionGrid/FormRevisionFilter.cs
Follow up to #10234
I thought I had commented on that
Not strictly necessary to change this,slightly more consistent
Order of options
Note: As Reflog is the dominant setting, it is slightly weird that the lower setting disables the ones above.
|Before|After|
|---|---|
| ![image](https://user-images.githubusercontent.com/6248932/196045423-38ad7e02-74d2-48fb-95aa-2b2bd0efd9fb.png) |![image](https://user-images.githubusercontent.com/6248932/196297328-6c9e4aec-24fc-403d-b608-cbafab2745cd.png) |
Manual
----
> Advanced filter: Change order of branch filter to match menus

- GitCommands/Patches/PatchManager.cs
- GitUI/CommandsDialogs/FormCommit.cs
- GitUI/Editor/FileViewer.cs
- IntegrationTests/UI.IntegrationTests/CommandsDialogs/FormCommitTests.cs
- IntegrationTests/UI.IntegrationTests/GlobalSetupOnce.cs
- UnitTests/CommonTestUtils/GitModuleTestHelper.cs
- UnitTests/CommonTestUtils/ReferenceRepository.cs
Fixes an issue where if you reset selected lines in a staged and renamed file then rename is undone too.
- Adjust the patch header to remove "reverse rename" part.
- Manual
- Integration test
- Build 023b2d8438aa0758af2018d0fc9e998418989510 (Dirty)
- Git 2.37.3.windows.1
- Microsoft Windows NT 10.0.22000.0
- .NET 6.0.10
----
> Fix resetting selected lines for renamed files in index

- GitUI/CommandsDialogs/FormBrowse.InitRevisionGrid.cs
- GitUI/CommandsDialogs/FormBrowse.cs
Fixes #10284
https://user-images.githubusercontent.com/4403806/197306889-82c394e7-5fc6-4717-a4d2-097427d3cfaa.mp4
----
> Refresh the left panel when it's shown

- GitUI/CommandsDialogs/FormBrowse.Designer.cs
- GitUI/CommandsDialogs/FormBrowse.cs
- GitUI/Interops/Messages.cs
- GitUI/UserControls/FilterToolBar.Designer.cs
- GitUI/UserControls/FilterToolBar.cs
- GitUI/UserControls/ToolStripEx.cs
This PR does:
- remove changes made in PR #3833, which was shitty, let's be honest
- adds a suspend/resume of redraw of the `ToolTipEx` control when a child element of type `ToolStripDropDownItem` opens/closes a dropdown menus
See related issue #10254 (recent) and #3832 (old).
Previous PR as an attempt to fix this problem is #3833. It used to work but the fix was not satisfying (non-sense and dirty hack) and stopped being effective after a few versions of GE.
Also, see #10259 since this is my first PR from after 23 January 2019.
> Removed changes of PR #3833, suspend/resume redrawn of ToolStripEx when dropdown menu is opened/closed

- GitCommands/Git/GitVersion.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.Designer.cs
- GitUI/CommandsDialogs/SettingsDialog/Pages/GitConfigAdvancedSettingsPage.cs
- GitUI/Translation/English.xlf
introduced in v2.38 ( https://github.blog/2022-10-03-highlights-from-git-2-38/#rebase-dependent-branches-with-update-refs )
- Manual
- Build d5c1facf153a56aa0ddae04907a6f296b1ab5f2c (Dirty)
- .NET 6.0.10
----
> git settings: new setting to be able to enable rebase of dependent branches

- GitUI/FormPuttyError.Designer.cs
- contributors.txt
Fixes #6564 
- Reduce height of top label
Manual verification. To reproduce:
* Install PuTTY
* Configure PuTTY for SSH in settings
* Attempt to fetch a repo with an SSH URL, without an SSH key set up
- GIT version 2.35.1.windows.2
- Windows 11
----
> #6564 - make labels in putty "please load key" modal not overlap

- GitUI/CommandsDialogs/BrowseDialog/FormBrowseMenus.cs
- GitUI/UserControls/FilterToolBar.cs
Alternative to #10235
By default:
- Manual
- Build 80f823749a6fda767bd547af21b8f460d4b391e8
- .NET 6.0.10
----
> FormBrowse: Hide Reflog button by default

- GitCommands/Git/AheadBehindDataProvider.cs
- GitCommands/Git/GitModule.cs
- manual
- Build 24e8371e13366c9de155109d4a319ef0c044f9a1 (Dirty)
- .NET 6.0.10
----
> perf: ensure compiled regex are compiled only once
